### ISSUE TITLE
service_discord_youtube.bat

### ISSUE THREAD

**Issue by N0H3** [Flowseal/zapret-discord-youtube#1]
при запуске service_discord_youtube.bat не работает стим а точнее подлагивает будто частично что то пускает что то нет

**Comment by lvvqm** [comment]
можете ответить, а что меняют данные файлы и как это влияет на пинг в играх?

**Comment by receiver1** [comment]
Открой командную строку от имени администратора. Перейди в папку где находится `zapret` с помощью команды `cd ПУТЬ`. Затем отправь команду `service_discord_youtube.bat` и подожди подобной надписи:
![image](https://github.com/user-attachments/assets/d3fab453-03b4-47aa-868e-67ae71b23113)
У тебя должно быть `STATE: RUNNING`.
