### ISSUE TITLE
Клонирование с Гита бинарников запрета.

### ISSUE THREAD

**Issue by nyakokitsu** [Flowseal/zapret-discord-youtube#10]
Почему бы не скачивать бинарники запрета напрямую с Гита проекта?

**Comment by Flowseal** [comment]
Обновляются они редко.
Если делать через зависимости самого гитхаба, не все в этом разберутся. Тут более про user-friendly.
Батники на скачку/обновление с гита zapret - дело времени. Возможно, имеет смысл сделать батник только на обновление. Но опять же, нужно время на написание. Если кому-то не лень это делать - милости прошу в PR
