### ISSUE TITLE
Выдает ошибку при запуске

### ISSUE THREAD

**Issue by DimaDzen** [Flowseal/zapret-discord-youtube#1004]
Выдает ошибку при запуске, что нужно исправить?
![photo_2024-12-21_12-16-33](https://github.com/user-attachments/assets/01531ab5-f743-4533-9059-47cd604300f5)

**Comment by Flowseal** [comment]
Не может найти файл. Либо не всё разархивировали, либо антивирус съел

**Comment by DimaDzen** [comment]
почему то general.bat не разархивировал, сейчас вручную скинул в папку, вроде ютуб летает)
