### ISSUE TITLE
 На YouTube не прогружаются видео с моб. интернета, 2-х операторов

### ISSUE THREAD

**Issue by SlavaRusi88** [Flowseal/zapret-discord-youtube#1005]
Запускал видео на youtube с 2 сим карт со сбермобайла и с МТС с приложением ByeDPI при этом аватарки на каналах на сайте грузят , видео понемногу иногда загружает на минимальном качестве и видео, очень медленно модель телефона техно спарк 10, в ByeDPI  приложение настройки менял. все равно не грузит скрин настроек прилагается. Какой конфиг, поставить или как иначе скорость сделать нормальной подскажите пожалуйста.
![Screenshot_20241221-112050](https://github.com/user-attachments/assets/592ae457-fe92-4fa1-8c22-31938439ccf3)

**Comment by Flowseal** [comment]
Обращайтесь в репозиторий ByeDPI.
