### ISSUE TITLE
Как адаптировать настройки под openwrt версию

### ISSUE THREAD

**Issue by DygDyg** [Flowseal/zapret-discord-youtube#101]
Помогите сделать конфиг под поенврт.
Если честно не особо понимаю что и где подставлять из параметров запуска в батнике в конфиг. 
[config.zip](https://github.com/user-attachments/files/17318398/config.zip)

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/105
