### ISSUE TITLE
help plz 

### ISSUE THREAD

**Issue by Pawenabled** [Flowseal/zapret-discord-youtube#1012]
![photo_2024-12-21_20-16-48](https://github.com/user-attachments/assets/85a8f4a0-8a9d-45c8-97a4-213cc3e677c8)

**Comment by serpen7** [comment]
with what you need help? Everything is running.

**Comment by Pawenabled** [comment]
к сожалению не работает, сейчас пробую через версию 1.5.0
перепробовал запускать автозапуском каждый из файлов, но дискорд все равно не открывается

**Comment by serpen7** [comment]
> к сожалению не работает, сейчас пробую через версию 1.5.0 перепробовал запускать автозапуском каждый из файлов, но дискорд все равно не открывается

да не запускай ты сервис каждый раз, удали его от имени администратора и просто запускай батники сами. Открыл один, открыл дискорд и смотришь пробьет или нет. Закрыл дискорд, закрыл батник. Запустил другой батник, запустил дискорд и так смотришь какой заработает.

Потом уже если с каким то заработает ставишь его как сервис чтобы каждый раз не открывать.

**Comment by Pawenabled** [comment]
в точности так и делаю, я запускаю их по одному, через сервис, если не работает ремоваю и след пробую, и так с каждым, щас установил 1.5.0. запусти, все норм, но через время в дисе иконки пропали, ну и все такое, но на работоспособность не влияет, если подскажите как иконки вернуть буду премного благодарен

**Comment by serpen7** [comment]
> в точности так и делаю, я запускаю их по одному, через сервис, если не работает ремоваю и след пробую, и так с каждым, щас установил 1.5.0. запусти, все норм, но через время в дисе иконки пропали, ну и все такое, но на работоспособность не влияет, если подскажите как иконки вернуть буду премного благодарен

в версии 1.5.0 не химичил ркн с клаудфлерем и ECH  по протоколу тлс 1.3. У вас особо нет разницы между 1.5.0 и последним релизом, лишь фиксы. Потому что только с 1.5.0 обновлялись бинарники. Это все пишется в апдейтах.

**Comment by Pawenabled** [comment]
что то на умном, я в этой сфере не сильно разбираюсь, но факт того что работает меня радует, все же спасибо вам за ответ !

**Comment by Flowseal** [comment]
Фикс иконок и не только был в 1.5.2
