### ISSUE TITLE
Не запускается дс

### ISSUE THREAD

**Issue by Elo41993** [Flowseal/zapret-discord-youtube#1013]
![image](https://github.com/user-attachments/assets/4b19f276-8e19-4759-ba1f-a2be99af3564)
что делать если запускаю программы а дискорд серавно не открывается я все антивирусники выключил

**Comment by serpen7** [comment]
Открыл один, открыл дискорд и смотришь пробьет или нет. Закрыл дискорд, закрыл батник. Запустил другой батник, запустил дискорд и так смотришь какой заработает.

Потом уже если с каким то заработает ставишь его как сервис чтобы каждый раз не открывать.

**Comment by Elo41993** [comment]
а как поставить как сервис

**Comment by serpen7** [comment]
> а как поставить как сервис

сначала батники попробуй пробьют они или нет, смысла ставить сервис сразу нет. И его муторно каждый раз удалять, ставить, удалять, ставить с проверкой батников.

Если нашел нужный тебе батник работающий то сервис инсталл бат от имени администратора запускаешь и выбираешь нужный тебе батник который будет установлен как сервис.

**Comment by Elo41993** [comment]
а если не один не подходит

**Comment by Elo41993** [comment]
ау помогите пожалуйста

**Comment by Elo41993** [comment]
ау

**Comment by Elo41993** [comment]
ау

**Comment by Elo41993** [comment]
ау

**Comment by serpen7** [comment]
> а если не один не подходит

значит и смысла ставить сервис нет, они не сработают у вас. Нужно искать что-то другое или разбираться почему не работает.
