### ISSUE TITLE
Ошибка: The extended attributes are inconsistent.

### ISSUE THREAD

**Issue by Yuggeo** [Flowseal/zapret-discord-youtube#1014]
Очень долго пользовался версией 1.6.1 всё было прекрасно, но сейчас general.bat перестал запускаться и выдаёт ошибку: The extended attributes are inconsistent. Есть способ починить?
![image](https://github.com/user-attachments/assets/5e4c8cbb-f92b-46ed-9288-4d3f0e1ec2b6)

**Comment by Eptiy** [comment]
Попробуй заново скачать. Вообще, ошибка намекает на то, что у тебя проблемы с системой, а не с запретом. Попробуй ещё выполнить "sfc /scannow" и "dism /online /cleanup-imange /checkhealth" в терминале от админа.

Ещё вопрос: ты папку сам назвал "Zapret6"? Просто есть возможность, что ты качал запрет не отсюда, а это риск нарваться на фейковую копию с вируснёй.

**Comment by Yuggeo** [comment]
Да папку я назвал так сам, т.к. много раз переустанавливал запрет. Вот только сейчас обнаружил, что у меня при открытии терминала с правами администратора такая же ошибка возникает. Сейчас буду пытаться чинить

**Comment by serpen7** [comment]
винда 7?

**Comment by serpen7** [comment]
Эта ошибка зачастую связанна с чем то в самой ОС, либо каким то ПО которое вмешивается в администраторские права и не дает нормально ими пользоваться.

**Comment by Yuggeo** [comment]
нет, винда 10. Хух вроде починил, но пришлось мне конечно помучиться
