### ISSUE TITLE
Проблемка

### ISSUE THREAD

**Issue by Kiioshi11** [Flowseal/zapret-discord-youtube#102]
В строке пишется что в пути есть пробелы , как их убрать , где это посмотреть если файл по сути на рабочем столе

**Comment by Wo1k** [comment]
Нужно все батники расположить в папке с названием без пробелов. Проще всего в корне диска создать папку и все закинуть туда

**Comment by Kiioshi11** [comment]
> Нужно разместить все bat-файлы в папке с названием без пробелов. Проще всего создать папку в корне диска и поместить туда все файлы

СПАСИБО ТЕБЕ , ДОБРЫЙ ЧЕЛОВЕК!
