### ISSUE TITLE
zapret-discord-youtube-1.6.1 не работает

### ISSUE THREAD

**Issue by UwU-poq** [Flowseal/zapret-discord-youtube#1024]
Когда я открываю любой батник, он сразу закрывается, кто знает от чего это? Неделю назад всё нормально работало, ну могу сказать раньше я сидел на  zapret-discord-youtube-1.5.2 и всё нормально работало до этого момента.

**Comment by SnakeRemastered** [comment]
@UwU-poq решил ??

**Comment by Anime228007** [comment]
Просто удали папку с батниками и заново скачай архив, мне помогло

**Comment by SnakeRemastered** [comment]
щя в 3 раз попробую дискорд не работает а ютуб работает, и батники закрываются

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/522
