### ISSUE TITLE
не запускается не один bat

### ISSUE THREAD

**Issue by Denchik010** [Flowseal/zapret-discord-youtube#1026]
Помогите решить проблему. Скачиваю перетаскиваю в папку запукаю все bat по очереди не один не запускается, компьютер говорит вы точно хотите запустить, нажимаю да, после этого все сворачивается

**Comment by SnakeRemastered** [comment]
я 4 раза переустановил открывал закрывал, само собой решилось

**Comment by Anime228007** [comment]
> Помогите решить проблему. Скачиваю перетаскиваю в папку запукаю все bat по очереди не один не запускается, компьютер говорит вы точно хотите запустить, нажимаю да, после этого все сворачивается

https://github.com/Flowseal/zapret-discord-youtube скачай это и просто папку перетащи мне помогло

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/522
