### ISSUE TITLE
Не работает RTC в дискордике

### ISSUE THREAD

**Issue by ImHartash** [Flowseal/zapret-discord-youtube#1028]
Здравствуйте все, давненько столкнулся с проблемой того, что сборка работает, но не работает RTC. При подключении в ГЧ, просто пишет "Подключение к RTC" и потом кикает с надписью "Не установлен маршрут". Роутер МГТС, но не провайдер, однако, у моего друга с таким-же провайдером все работает. Ничего кроме zapret'а не стоит. Пробовал все батники (ни один не помогает). Искал способ исправить, ничего не работает. Моим предположением является настройка роутера, буду рад за ваши варианты. Могу добавить еще то, что Тор работал на одном роутере, переехал на другой, и вдруг перестал. Спасибо заранее <3

**Comment by Flowseal** [comment]
Пробуйте другие батники, а также
https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by ImHartash** [comment]
Батники все перепробывал, также делал как другие. Ничего не помогло
