### ISSUE TITLE
Help, У моего друга не запускаются батники, при запуске от имени админа, ошибка пути c\users\Awinws.exe. Мб кто-то сталкивался?

### ISSUE THREAD

**Issue by Swoompie** [Flowseal/zapret-discord-youtube#1029]
![photo_2024-12-18_22-37-57](https://github.com/user-attachments/assets/efedee12-b2d8-4a6e-a0b9-69d3b824577b)

**Comment by serpen7** [comment]
У вашего друга вирусная сборка не отсюда. Попробуете отрубить антивирус и запустить и у него будут вирусы. Вас спасла антивирусная защита. Такого файла ни в этом, ни в оригинальном репозитории запрета нет.

**Comment by Flowseal** [comment]
Возмоно, в пути до файла присутствуют спец. символы, что мешает работе

- Скачайте последний релиз из этого репозитория
- Разархивируйте в папку без пробелов, русских символов и спец. символов
- Действуйте по инструкции из README

**Comment by Swoompie** [comment]
> У вашего друга вирусная сборка не отсюда. Попробуете отрубить антивирус и запустить и у него будут вирусы. Вас спасла антивирусная защита. Такого файла ни в этом, ни в оригинальном репозитории запрета нет.

Увы всё отпадает, т.к. кидал ссылку на этот репозиторий, а антивирус наказал сказу выключить.

**Comment by serpen7** [comment]
в этом репозитории файла Awinws.exe нет в сборках. есть только winws.exe.

**Comment by Swoompie** [comment]
> в этом репозитории файла Awinws.exe нет в сборках. есть только winws.exe.

Всё верно, знал бы я что это за зверь, рассказал бы, поэтому и спрашиваю.....

**Comment by serpen7** [comment]
> > в этом репозитории файла Awinws.exe нет в сборках. есть только winws.exe.
> 
> Всё верно, знал бы я что это за зверь, рассказал бы, поэтому и спрашиваю.....

Этот репозиторий собран из оригинального репозитория запрета от bolvan. Тут лишь добавлены батники и стратегии в них с их использованием и установкой сервиса, а так же листы. На вашем скрине явно посторонний файл. И вам теперь надо проверять комп на вирусы. Отрубать антивирусы никогда не стоит, в них есть исключения на конкретные файлы и игнор если он вам нужен.

**Comment by Swoompie** [comment]
> > > в этом репозитории файла Awinws.exe нет в сборках. есть только winws.exe.
> > 
> > 
> > Всё верно, знал бы я что это за зверь, рассказал бы, поэтому и спрашиваю.....
> 
> Этот репозиторий собран из оригинального репозитория запрета от bolvan. Тут лишь добавлены батники и стратегии в них с их использованием и установкой сервиса, а так же листы. На вашем скрине явно посторонний файл. И вам теперь надо проверять комп на вирусы. Отрубать антивирусы никогда не стоит, в них есть исключения на конкретные файлы и игнор если он вам нужен.

Антивирус был выключен, только на момент запуска батников, до этого об был всегда включен, причём тут вирусы на пк, у него купленая лицензия касперского. 
И насчёт других репозирориев отвечу(скачивал отсюду и кидал ему как архив, так и ссылку с сопровождением как скачать), я буквально запускаю все батники и работает нормально. Человек не сведуч в этих делаю типа гитхаба и всего остального, а я фиг того знает что это за ошибка, в инете ноль инфы, вот и думал у узнающих людей спросить.

**Comment by Swoompie** [comment]
> > > > в этом репозитории файла Awinws.exe нет в сборках. есть только winws.exe.
> > > 
> > > 
> > > Всё верно, знал бы я что это за зверь, рассказал бы, поэтому и спрашиваю.....
> > 
> > 
> > Этот репозиторий собран из оригинального репозитория запрета от bolvan. Тут лишь добавлены батники и стратегии в них с их использованием и установкой сервиса, а так же листы. На вашем скрине явно посторонний файл. И вам теперь надо проверять комп на вирусы. Отрубать антивирусы никогда не стоит, в них есть исключения на конкретные файлы и игнор если он вам нужен.
> 
> Антивирус был выключен, только на момент запуска батников, до этого об был всегда включен, причём тут вирусы на пк, у него купленая лицензия касперского. И насчёт других репозирориев отвечу(скачивал отсюду и кидал ему как архив, так и ссылку с сопровождением как скачать), я буквально запускаю все батники и работает нормально. Человек не сведуч в этих делаю типа гитхаба и всего остального, а я фиг того знает что это за ошибка, в инете ноль инфы, вот и думал у узнающих людей спросить.

**Comment by serpen7** [comment]
> > > > в этом репозитории файла Awinws.exe нет в сборках. есть только winws.exe.
> > > 
> > > 
> > > Всё верно, знал бы я что это за зверь, рассказал бы, поэтому и спрашиваю.....
> > 
> > 
> > Этот репозиторий собран из оригинального репозитория запрета от bolvan. Тут лишь добавлены батники и стратегии в них с их использованием и установкой сервиса, а так же листы. На вашем скрине явно посторонний файл. И вам теперь надо проверять комп на вирусы. Отрубать антивирусы никогда не стоит, в них есть исключения на конкретные файлы и игнор если он вам нужен.
> 
> Антивирус был выключен, только на момент запуска батников, до этого об был всегда включен, причём тут вирусы на пк, у него купленая лицензия касперского. И насчёт других репозирориев отвечу, я буквально запускаю все батники и работает нормально. Человек не сведуч в этих делаю типа гитхаба и всего остального, а я фиг того знает что это за ошибка, в инете ноль инфы, вот и думал у узнающих людей спросить.

С запуском вирусных сборок вам тут никто нормальный не поможет. Если она не запустилась то это даже хорошо.

С запуском нормальной сборки только могут помочь, но на скрине явно не то что нужно. Поэтому простите. Если у вас такая ошибка будет на нормальной сборке, не вирусной и из нормального репозитория гита, то создайте с ней другой issue, чтобы не вводить никого в заблуждение.

**Comment by Swoompie** [comment]
> Если у вас такая ошибка будет на нормальной сборке, не вирусной и из нормального репозитория гита, то создайте с ней другой issue, чтобы не вводить никого в заблуждение.

И как же правильно написать?

**Comment by Swoompie** [comment]
> * Разархивируйте в папку без пробелов, русских символов и спец. символов
 Проблема была в пути к батникам, разархивировал на рабочий стол, а пользовательназывался A&I.
 Так же полагаю проблема была в самом пользователе, не имеется прав администратора.
