### ISSUE TITLE
С провайдером МТС не заходит в войс 

### ISSUE THREAD

**Issue by baberage** [Flowseal/zapret-discord-youtube#103]
Просто открывая discord_youtube я могу спокойно писать сообщения и смотреть ютуб но пытаясь зайти в войс пишет подключение и ничего не происходит.
Когда попробовал раздать интернет с телефона через USB модем в войс зашло. 
Видимо вся проблема в провайдере будет ли фикс?
![изображение](https://github.com/user-attachments/assets/f867e9ca-9dd0-49e5-bb91-475b7364a6d4)

**Comment by MaccKOT** [comment]
Потому что все программы данного типа не могут работать с протоколом UDP, по которому и передаётся войс.

**Comment by conqu1stador** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
