### ISSUE TITLE
Не подгружаются иконки в Discord

### ISSUE THREAD

**Issue by ikSleepMode** [Flowseal/zapret-discord-youtube#1030]
Не подгружаются иконки в Discord
Все остальное работает
ALT2
![image](https://github.com/user-attachments/assets/d87f9ec7-f9ce-487a-a979-e8f1ff65b854)

_Originally posted by @ikSleepMode in https://github.com/Flowseal/zapret-discord-youtube/discussions/252#discussioncomment-11639220_

**Comment by serpen7** [comment]
[zapret.zip](https://github.com/user-attachments/files/18219840/zapret.zip)
Скачай мое от этого репозитория, попробуй запустить альт 2 май лист. Я обновлял листы и перешел полностью с гудбая на запрет, прикрепил свои листы, если поможет отпиши.

**Comment by ikSleepMode** [comment]
> буй запустить альт 2 май лист. Я обновлял листы и

я на запрете и сижу, залей пж просто листы, на архив антивирь и браузер ругаются

**Comment by serpen7** [comment]
> > буй запустить альт 2 май лист. Я обновлял листы и
> 
> я на запрете и сижу, залей пж просто листы, на архив антивирь и браузер ругаются

он и будет ругаться на виндайверт в архиве как и на оригинальный запрет, это особо ничего не значит.

**Comment by serpen7** [comment]
> > буй запустить альт 2 май лист. Я обновлял листы и
> 
> я на запрете и сижу, залей пж просто листы, на архив антивирь и браузер ругаются

прикол в том что там модифицированные батники под лист гудбайдпи и с дополнением некоторым они не сработают на стандартных конфигах, нужно переписывать немножечко конфиг на лист новый.

**Comment by ikSleepMode** [comment]
> > > буй запустить альт 2 май лист. Я обновлял листы и
> > 
> > 
> > я на запрете и сижу, залей пж просто листы, на архив антивирь и браузер ругаются
> 
> он и будет ругаться на виндайверт в архиве как и на оригинальный запрет, это особо ничего не значит.

скинь просто листы и всё, у меня папка с виндивертом в исключениях есть

**Comment by serpen7** [comment]
[list-mylist.txt](https://github.com/user-attachments/files/18219853/list-mylist.txt)

**Comment by serpen7** [comment]
еще раз повторяю они не заработают без модификации конфигов батников на этот именно лист.

**Comment by ikSleepMode** [comment]
> еще раз повторяю они не заработают без модификации конфигов батников.

Заработало!
![image](https://github.com/user-attachments/assets/92f663a4-5606-4d32-80b1-1fa80f73d90b)
Спасибо!

**Comment by serpen7** [comment]
О_о

**Comment by serpen7** [comment]
я в афиге если честно

**Comment by ikSleepMode** [comment]
> я в афиге если честно

Я просто твой лист открыл и содержимое воткнул в свои листы)

**Comment by serpen7** [comment]
потому что на стандартных конфигах лист дженерал или дискорда, это мой лист и под него модифицированы батники
по примеру этого 
![image](https://github.com/user-attachments/assets/1ae400dd-0643-4f39-9c30-16c8ba3ca56c)

**Comment by serpen7** [comment]
> > я в афиге если честно
> 
> Я просто твой лист открыл и содержимое воткнул в свои листы)

ну ты даешь

**Comment by serpen7** [comment]
Хорошо что помогло, плюс один к "карме" :D

**Comment by Felix14-v2** [comment]
> Заработало!

Можно закрывать обсуждение?

**Comment by Flowseal** [comment]
Подозреваю, просто с кэша подгрузило, но ладно.

**Comment by serpen7** [comment]
> Подозреваю, просто с кэша подгрузило, но ладно.

не, если у него были непрогрузы то они в кеше будут "нулями"(ошибками данных, без подхваченного кеша т.к. сверки не было ибо не пробивало на сверку подгруженного уже кеша с сервером), а то что прогрузились то и в кеш записались новые. Тут как бы и так грузились из кеша, однако видимо он не обновлялся. А после того как пробило обновился и загрузил миниатюры и перезаписал кеш. 

Дискорд хоть и браузер по сути прилогой, но кеш без сверки со стороны сервера и перезаписи кеша не подгрузит миниатюры, если конечно не застрял. Так что заработало ну и ладно.

**Comment by serpen7** [comment]
> > Подозреваю, просто с кэша подгрузило, но ладно.

не, если у него были непрогрузы то они в кеше будут "нулями"(ошибками данных, без подхваченного кеша т.к. сверки не было ибо не пробивало на сверку подгруженного уже кеша с сервером), а то что прогрузились то и в кеш записались новые после нулей ошибочных. Тут как бы и так грузились из кеша, однако видимо он не обновлялся. А после того как пробило обновился и загрузил миниатюры и перезаписал кеш.
 
 Дискорд хоть и браузер по сути прилогой, но кеш без сверки со стороны сервера и перезаписи кеша не подгрузит миниатюры, если конечно не застрял. Так что заработало ну и ладно.

**Comment by Desgner27** [comment]
Ну кстати, вставив конец файла ( листа serpen7 ) у меня тоже начали аватарки прогружаться, видимо что-то не допилили в листе, либо хз. Главное что оно работает )
