### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Title155** [Flowseal/zapret-discord-youtube#1032]
Restarted with admin rights
The zapret service is stopping..
The zapret service was stopped successfully.

[SC] DeleteService SUCCESS

The WinDivert service was stopped successfully.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

C:\Windows\system32> 

У меня всегда вылазит ошибка 1060
при удалении
при установке эта всратая ошибка
помогите пж

**Comment by serpen7** [comment]
это не ошибка это уведомление о том что сервис не существует который есть на удалении в батнике ремув, все нормально. 

И сервис запрета был у вас успешно удален и драйвер виндайверта выгружен 
![image](https://github.com/user-attachments/assets/a090018b-f9f2-49cd-ae7a-05993a94a78a)

**Comment by Flowseal** [comment]
По логам он у вас успешно удалился - а значит, скорее всего, работал.
Если сервисы недоступны - читайте README
