### ISSUE TITLE
Срочно нужна помощь 

### ISSUE THREAD

**Issue by Onahanc** [Flowseal/zapret-discord-youtube#1033]
Почему то работает на половину. Ютуб запускается, а дискорд вообще не запускается. Что делать?

**Comment by Hadozz** [comment]
запусти **general (ALT2)**

**Comment by Onahanc** [comment]
Огромное спасибо тебе, не знакомый мне человек!)

**Comment by Anime228007** [comment]
> Почему то работает на половину. Ютуб запускается, а дискорд вообще не запускается. Что делать?

Что ты запускаешь что у тебя ютуб робит? У меня дс работает, а ютуб никак.
