### ISSUE TITLE
Ютуб не работает в Opera GX

### ISSUE THREAD

**Issue by Disijis** [Flowseal/zapret-discord-youtube#1034]
Сколько не стараюсь включить, ничего не помогает. В яндекс браузере хоть и с небольшим скрипом, но работает ютуб. В приватном окне оперы тоже, а вот в обычном окне нет, пишет "Нет подключения к интернету". А постоянно входить во все аккаунты в приватном окне та еще марока. Есть какое-то решение с оперой gx?

**Comment by Disijis** [comment]
![изображение_2024-12-22_134545966](https://github.com/user-attachments/assets/dca7174b-adaf-4294-8a41-88ba2576d86e)

**Comment by serpen7** [comment]
расширения проверить какие работают потому что те же прокси на браузере расширениями могут быть заблокированы и при работе с замедлом ютуба врубаясь просто не давать соединения.

**Comment by Disijis** [comment]
> расширения проверить какие работают потому что те же прокси на браузере расширениями могут быть заблокированы и при работе с замедлом ютуба врубаясь просто не давать соединения.

Спасибо тебе, добрый человек. Оказалось, что у меня откуда-то был установлен ссаный Юбуст(который я не устанавливал). Удалил и все заработало. Я б не додумался в расширения посмотреть

**Comment by serpen7** [comment]
> > расширения проверить какие работают потому что те же прокси на браузере расширениями могут быть заблокированы и при работе с замедлом ютуба врубаясь просто не давать соединения.
> 
> Спасибо тебе, добрый человек. Оказалось, что у меня откуда-то был установлен ссаный Юбуст(который я не устанавливал). Удалил и все заработало. Я б не додумался в расширения посмотреть

а это первый признак того что чето с расширениями если в инкогнито все работает норм а в обычке нет. Потому что в инкогнито обычно не грузятся расширения, это чистое окно.
Я вот про это:

>  яндекс браузере хоть и с небольшим скрипом, но работает ютуб. В приватном окне оперы тоже, а вот в обычном окне нет

**Comment by Wildfire0** [comment]
А у меня вот недавно токо перестал грузить ютуб, в этом браузере, причем ни в каком режиме не грузит, я попробовал другой браузер (мозилу) и там работало все ок. Почему именно в опере перестал работать непонятно. Расширений никаких лишних нет.
