### ISSUE TITLE
Не хочет запускаться от имени админа

### ISSUE THREAD

**Issue by MistaBalls** [Flowseal/zapret-discord-youtube#1035]
![image](https://github.com/user-attachments/assets/c44c3eb1-f6ca-4c9f-9bec-3f2a862e065d)
Запускаю от имени админа, а он этот факт не хочет принимать, и по итогу программа не запускается с системой и приходится при каждом запуске компьютера запускать её в ручную

**Comment by Flowseal** [comment]
Судя по скриншоту, скрипт нормально запустился. Предоставьте скриншот с состоянием сервиса (win+r -> services.msc) после перезапуска компьютера

**Comment by MistaBalls** [comment]
Как называется этот сервис? 
![image](https://github.com/user-attachments/assets/12576f8d-9b43-4add-bf5a-eeea44f4c355)
![image](https://github.com/user-attachments/assets/5690037c-a37b-47b2-806d-40bb17d033fa)
![image](https://github.com/user-attachments/assets/8b6f7265-a8a8-4947-ba32-c9b319de55de)
![image](https://github.com/user-attachments/assets/ec2814eb-e39a-4c9b-a658-d8d47dd65e5f)
![image](https://github.com/user-attachments/assets/a3330c93-aa55-4fc1-814b-e854047a17aa)
![image](https://github.com/user-attachments/assets/1fadbb79-f5ad-4bd5-b0b7-f84019265923)

**Comment by Eptiy** [comment]
Когда запускаешь service_install, тебя скрипт просит выбрать батник для установки сервиса путём ввода цифры и нажатия enter. Ты же выбираешь файл, а не просто закрываешь service_install сразу после запуска?

**Comment by MistaBalls** [comment]
![image](https://github.com/user-attachments/assets/ee56c67f-16aa-4df0-8565-dba28435b575)
Выбирал, ещё раз выбрал тот же, вот что пишет

**Comment by Eptiy** [comment]
> Выбирал, ещё раз выбрал тот же, вот что пишет

Логи нормальные. Служба должна быть установлена. После установки можешь проверить в диспетчере задач на вкладке "службы", начинается на "zapret".

**Comment by MistaBalls** [comment]
да, есть
