### ISSUE TITLE
Работает на ютуб , на дискорд нет 

### ISSUE THREAD

**Issue by bearthiss** [Flowseal/zapret-discord-youtube#1036]
Работает на ютуб , на дискорд нет , провел час на гитхабе читая что может быть , все попробовал ничего не помогает

**Comment by bearthiss** [comment]
я просто переустановил в пятый раз и запустилось через alt2 я в тильте

**Comment by JokoKenguru** [comment]
> я просто переустановил в пятый раз и запустилось через alt2 я в тильте

большое спасибо, ростелеком сработал альт2. обновление прошло и дискорд запустился

**Comment by Vaaankas** [comment]
> > я просто переустановил в пятый раз и запустилось через alt2 я в тильте
> 
> большое спасибо, ростелеком сработал альт2. обновление прошло и дискорд запустился

Ростелеком с альт 2 заработал, Спасибо!

**Comment by MIkipojo** [comment]
переустановил 6 раз не работает я уже устал долблю 3 день

> я просто переустановил в пятый раз и запустилось через alt2 я в тильте

**Comment by BF3000** [comment]
Подтверждаю. Сегодня перестало работать но на алт2 заработало
