### ISSUE TITLE
качается не архивная папка а текст из блокнота

### ISSUE THREAD

**Issue by 6ala8a** [Flowseal/zapret-discord-youtube#1038]
![image](https://github.com/user-attachments/assets/e05eb6a3-a4c3-416d-a8fc-9f78093e7786)
что делать

**Comment by serpen7** [comment]
[zapret.zip](https://github.com/user-attachments/files/18222137/zapret.zip)
держи, попробуй так. 
А хотя стоп какая ОС?
![image](https://github.com/user-attachments/assets/ce01437c-d4fa-4c8e-8292-c07a0e5f50e9)

**Comment by EgorWeders** [comment]
Как этот файл называется? Конкретно расширение

**Comment by Flowseal** [comment]
Скачайте любой архиватор
