### ISSUE TITLE
Не грузится видео на youtube при использовании goodbyedpi + service_goodbye_discord

### ISSUE THREAD

**Issue by Wo1k** [Flowseal/zapret-discord-youtube#104]
При использовании goodbyedpi сегодня запустил соответствующий батник, service_goodbye_discord. Дискорд работает отлично, войс + демонстрация экрана, все класс, но с ютубом произошла вот такая странность. Сперва сайт писал, что нет подключения к интернету, затем подгрузил боковую панель, а после перезагрузки страницы загрузился полностью, но перестали загружаться видео. Перезагрузка компьютера дело не исправило, изменение hex ключа тоже.
Не знаю, в этом ли дело, но я использую файл service_install_russia_blacklist_YOUTUBE_ALT, поскольку у меня провайдер МГТС, с которым есть свои заморочки. Понимаю, что сервис должен работать в зависимости от goodbyedpi, но может он все-таки как-то влияет, если использовать альтернативный файл? Строчки из файла:

@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)

echo This script should be run with administrator privileges.
echo Right click - run as administrator.
echo Press any key if you're running it as administrator.
pause
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -6 -e1 -q --fake-gen 32 --fake-from-hex e42fc5bdd850552516fea26a8be114083f1b2c4c25d20f34c098d9253a1a659dab03dff2dc9fe5dd1ee89a5270400daab8e9f781b3a7e9501b0e --blacklist \"%CD%\russia-blacklist.txt\" --blacklist \"%CD%\russia-youtube.txt\"" start= "auto"
sc description "GoodbyeDPI" "Passive Deep Packet Inspection blocker and Active DPI circumvention utility"
sc start "GoodbyeDPI"

POPD

**Comment by PunisherT1000** [comment]
Все тоже самое один в один тот же service_install_russia_blacklist_YOUTUBE_ALT использовал, вот мои --auto-ttl 1-7-10 -e1 -f1 --reverse-frag --wrong-seq -q --fake-gen 12, и после использования этой проги перестал работать сам goodbyedpi, жду и надеюсь фикса.

**Comment by PunisherT1000** [comment]
Как я понял в goodbyedpi менять --fake-from-hex бессмысленно сам автор это писал.

**Comment by leonelo00** [comment]
start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

**Comment by leonelo00** [comment]
Попробуйте это сейчас с гбд, у меня получилось. О великие люди с ответы маил ру

**Comment by Wo1k** [comment]
Нет, с этими параметрами на ютубе вообще соединения нет
![image](https://github.com/user-attachments/assets/a3364a98-cec5-4dc9-aaf1-fd30effbdb6e)

**Comment by VelikiyCthulhu** [comment]
Стуация аналогичная. При установке запрета, дискорд начал работать, но при этом youtube работать перестал. Если снести запрет то ранее работавший goodbyedpi работать тоже отказывается

**Comment by JS-NinjaNN** [comment]
> Стуация аналогичная. При установке запрета, дискорд начал работать, но при этом youtube работать перестал. Если снести запрет то ранее работавший goodbyedpi работать тоже отказывается

Я не использовал ничего, кроме goodbyedpi и он тоже отвалился. Видимо сам по себе goodbyedpi заглох.

**Comment by Nirraen** [comment]
дело не в этом софте. ютуб у всех опять отлетел, вот и всё.

удалил службу у goodbye dpi - service_remove.cmd - удаляет также и windivert службу
поменял строку в установке службы на `
sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt"" start= "auto"`
заработало снова.
у этого софта использую обход диса только.

**Comment by leonelo00** [comment]
> Стуация аналогичная. При установке запрета, дискорд начал работать, но при этом youtube работать перестал. Если снести запрет то ранее работавший goodbyedpi работать тоже отказывается

Есть закономерность, сначала запускаешь гбд, а потом запрет и всё работает. У меня по крайне мере так

**Comment by leonelo00** [comment]
> дело не в этом софте. ютуб у всех опять отлетел, вот и всё.
> 
> удалил службу у goodbye dpi - service_remove.cmd - удаляет также и windivert службу поменял строку в установке службы на ` sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt"" start= "auto"` заработало снова. у этого софта использую обход диса только.

Ты это с ответы ру взял? Я оттуда же брал ахаххахаххаха

**Comment by leonelo00** [comment]
> дело не в этом софте. ютуб у всех опять отлетел, вот и всё.
> 
> удалил службу у goodbye dpi - service_remove.cmd - удаляет также и windivert службу поменял строку в установке службы на ` sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt"" start= "auto"` заработало снова. у этого софта использую обход диса только.

Вообще работать ютуб стал чуть хуже, но он хотя бы работает

**Comment by JS-NinjaNN** [comment]
> дело не в этом софте. ютуб у всех опять отлетел, вот и всё.
> 
> удалил службу у goodbye dpi - service_remove.cmd - удаляет также и windivert службу поменял строку в установке службы на ` sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt"" start= "auto"` заработало снова. у этого софта использую обход диса только.

При запуске службы батник сразу автоматом закрывается? Как отследить что служба запустилась?

**Comment by PunisherT1000** [comment]
> > дело не в этом софте. ютуб у всех опять отлетел, вот и всё.
> > удалил службу у goodbye dpi - service_remove.cmd - удаляет также и windivert службу поменял строку в установке службы на ` sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt"" start= "auto"` заработало снова. у этого софта использую обход диса только.
> 
> Ты это с ответы ру взял? Я оттуда же брал ахаххахаххаха

Минус для меня большой что остальные сайты которые открывал goodbyedpi перестали работать, но да ютуб кое как ожил хотябы

**Comment by VelikiyCthulhu** [comment]
С этими настройками youtube даже соединения не видит. Не может бысть совпадения что dpi сам отвалился. Он отвалился в тот же момент что запустился запрет

**Comment by VelikiyCthulhu** [comment]
> С этими настройками youtube даже соединения не видит. Не может бысть совпадения что dpi сам отвалился. Он отвалился в тот же момент что запустился запрет

Кстати Запрет стал запускать ютуб и без дпи, нужно квик и кубер включить в браузере

**Comment by NothingToRegret1** [comment]
> > С этими настройками youtube даже соединения не видит. Не может бысть совпадения что dpi сам отвалился. Он отвалился в тот же момент что запустился запрет
> 
> Кстати Запрет стал запускать ютуб и без дпи, нужно квик и кубер включить в браузере

сработало

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90

**Comment by ShabanovAn** [comment]
Все попробовал ничего не работает, помогите подскажите  вот мой файл 1_russia_blacklist_YOUTUBE_ALT
Все вроде ок но ничего не работает

@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
PUSHD "%_arch%"

start "" goodbyedpi.exe -7 -e1 -q --fake-gen 5 --fake-from-hex 0df02df1ea6a04fda840979bd0918f62795055702d29684ff12770ce39efd7d9749dff783444f3c85b1963bf44472722008b7df50e0adb09e764 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
POPD
POPD


GoodbyeDPI v0.2.3rc3: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Loaded 154025 hosts from file ..\russia-blacklist.txt
Loaded 14 hosts from file ..\russia-youtube.txt
Block passive: 0
Block QUIC/HTTP3: 1
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 1
Fragment by SNI: 0
Native fragmentation (splitting): 1
Fragments sending in reverse: 1
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0
Allow missing SNI: 0
Fake requests, TTL: fixed (fixed: 0, auto: 0-0-0, min distance: 0)
Fake requests, wrong checksum: 1
Fake requests, wrong SEQ/ACK: 0
Fake requests, custom payloads: 6
Fake requests, resend: 1
Max payload size: 1200

Opening filter
Filter activated, GoodbyeDPI is now running!

**Comment by Djdfy14** [comment]
Присоединяюсь, у меня на ростелекоме со вчерашнего вечера не работает, сам сайт открывается, а видео не показывает...

**Comment by IZavarkaI** [comment]
Error opening filter: 1058 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. Подскажите из-за чего может быть? до этого была 433

**Comment by eugene210492** [comment]
start "" goodbyedpi.exe -e 1 -q --native-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 4 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

**Comment by rmanzman** [comment]
Там выкатили консольную утилиту под названием GoodCheck, которая сама подбирает работающие настройки для GBDPI. Не особо в неё верил, но она мне подобрала не просто работающую строчку настроек, а ютуб с ней начал открывать видосы чуть ли не быстрее, чем до блокировок. Вполне вероятно, что не у всех будет работать, но пробуйте подбирать сами.

**Мегафон (домашний интернет), Москва.**

> -e 2 -q --native-frag --fake-from-hex ec2a95f09ac0f9455219629dcf74064588104e6d27a73b23c2bdf4f45a096ce094a34a5d63dca7fafca8bce635f20b2e1cb5e2aebd65d187c69d1af75b0cde185c54581a07380afc --fake-gen 15 --set-ttl 3

Там был hex на 144 символа, я сразу вставил выше не свой, а сгенерированный тут: https://www.browserling.com/tools/random-hex

Пробуйте, пользуйтесь.

Битрейт у 4К-ролика:
![2024-10-10 14 45 42](https://github.com/user-attachments/assets/4973e591-aa5b-4347-a6bc-3f8d963070d4)

**Comment by desoxel** [comment]
> Там выкатили консольную утилиту под названием GoodCheck, которая сама подбирает работающие настройки для GBDPI. Не особо в неё верил, но она мне подобрала не просто работающую строчку настроек, а ютуб с ней начал открывать видосы чуть ли не быстрее, чем до блокировок. Вполне вероятно, что не у всех будет работать, но пробуйте подбирать сами.
> 
> **Мегафон (домашний интернет), Москва.**
> 
> > -e 2 -q --native-frag --fake-from-hex ec2a95f09ac0f9455219629dcf74064588104e6d27a73b23c2bdf4f45a096ce094a34a5d63dca7fafca8bce635f20b2e1cb5e2aebd65d187c69d1af75b0cde185c54581a07380afc --fake-gen 15 --set-ttl 3
> 
> Там был hex на 144 символа, я сразу вставил выше не свой, а сгенерированный тут: https://www.browserling.com/tools/random-hex
> 
> Пробуйте, пользуйтесь.
> 
> Битрейт у 4К-ролика: ![2024-10-10 14 45 42](https://private-user-images.githubusercontent.com/108012955/375360485-4973e591-aa5b-4347-a6bc-3f8d963070d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjExNTMsIm5iZiI6MTcyODU2MDg1MywicGF0aCI6Ii8xMDgwMTI5NTUvMzc1MzYwNDg1LTQ5NzNlNTkxLWFhNWItNDM0Ny1hNmJjLTNmOGQ5NjMwNzBkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmUwMTE4ZWFhMDIwNzg4OGY0YzljNzgwOWE2NTE4ODA0MzJlNDEzMzNlMDJiNzE5NWQ4ZWMxODljYmZhZDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Pp0ZjIG90j7nYBJ250EX7fZDLnP5e8reH7dINrZquzE)

Объясни пожалуйста подробнее, где ты нашёл утилиту и что именно заменил в каком файле.

**Comment by desoxel** [comment]
Нашёл гайд по подбору на дзене, утилита там же - https://dzen.ru/a/Zv7pKj2apwzlfYR-

**Comment by rmanzman** [comment]
> Нашёл гайд по подбору на дзене, утилита там же - https://dzen.ru/a/Zv7pKj2apwzlfYR-

Всё верно, вот ещё подобная статья напрямую на сайте этих ребят: https://app-time.ru/post/instrukciya-po-avtomaticheskomu-podboru-nastroek-dlya-goodbyedpi

Настройки вставляются в файл **1_russia_blacklist.cmd** -в строку:
start "" goodbyedpi.exe  **_СЮДАААААААА_** --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

**Comment by Wo1k** [comment]
> Нашёл гайд по подбору на дзене, утилита там же - https://dzen.ru/a/Zv7pKj2apwzlfYR-

Как-то не знаю, попробовал я обе версии программы из гайда и обе не смогли подобрать вариант, когда успешно проходило бы соединение по всем представленным ссылкам. Похоже что МГТС преуспел в блокировке всех вариантов

**Comment by rmanzman** [comment]
> Как-то не знаю, попробовал я обе версии программы из гайда и обе не смогли подобрать вариант, когда успешно проходило бы соединение по всем представленным ссылкам. Похоже что МГТС преуспел в блокировке всех вариантов

Пробуй-пробуй, я часа полтора потратил на ковыряния в GoodCheck, использовал режим подбора №7, чеклист googlevideo.txt, количество проходок (passes) не увеличивал, а то слишком долго выходит.

В итоге по логу в самом конце был всего один вариант настройки, который дал результат **Strategies with 20 out of 22 successes**, т.е. 20 из 22 успешных попыток, вот она-то гарантировано и заработала.

**Comment by ik1domari** [comment]
> start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

Тюмень, Ростелеком.
Сработало
