### ISSUE TITLE
не работает дс работает ютуб

### ISSUE THREAD

**Issue by MIkipojo** [Flowseal/zapret-discord-youtube#1043]

**Comment by MIkipojo** [comment]
я запускаю через ALT2 не работает дс но ютуб работает хз че делать уже идет 3 день
в дс идет постоянная обнова переустанавливал прогу 5 раз

**Comment by AsyaTrey** [comment]
У меня просто 2 дня назад во время разговора перестало все работать((((((((((

**Comment by ghost** [comment]
ну во первых изучите как работает zapret, и поймите одно пожалуйста - **что нету волшебной кнопочки которая откроет доступ вам ко всему и без проблем.**
советую самому посмотреть репозиторий: (https://github.com/bol-van/zapret), изучить документацию и после этого создавать самому свои стратегии для обхода. **для каждого провайдера это индивидуально**.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
