### ISSUE TITLE
Можно ли через этот файл запустить Твиттер (X)?

### ISSUE THREAD

**Issue by AtaBilay** [Flowseal/zapret-discord-youtube#1045]
Попробовал вписать x.com в list-general, но ничего не сработало, может надо вписать сопутствующие сервисы для работы x, как у дискорда вот?
![изображение_2024-12-22_223317933](https://github.com/user-attachments/assets/be4a9ef0-7e6d-4f7e-a65c-e2c7f49a7d5f)

**Comment by reveantpwnz** [comment]
нет. это говно

**Comment by toshaebosha** [comment]
попробуй вставить, у меня работает
```
twitter.com
t.co
ads-twitter.com
twimg.com
x.com
pscp.tv
twtrdns.net
twttr.com
periscope.tv
tweetdeck.com
twitpic.com
twitter.co
twitterinc.com
twitteroauth.com
twitterstat.us
```
