### ISSUE TITLE
Эта версия запрета умеет сама следить за сайтами которые заблочены и составлять списки?

### ISSUE THREAD

**Issue by bpGusar** [Flowseal/zapret-discord-youtube#1046]
Эта версия запрета умеет сама следить за сайтами которые заблочены и составлять списки?
Если нет как активировать этот функционал?

**Comment by serpen7** [comment]
нет эта версия такого не может.
В листы хосты только вручную, тут нет автоопределения или чека на заблоченые ресурсы.

**Comment by bpGusar** [comment]
активировать никак? я чет вчера попробовал подкинуть конфиг из основной репы запрета, не помогло, даже перестал запускаться

**Comment by electrifying** [comment]
> активировать никак?

Тут нет, в основном запрете есть режим автохостлист

**Comment by serpen7** [comment]
> активировать никак? я чет вчера попробовал подкинуть конфиг из основной репы запрета, не помогло, даже перестал запускаться

потому что там другая схема действия запрета в основном репозитории, она с этим то что тут по юзер френдли может уже и не работать т.к. переписывалась под надобности и обновлялась частенько. Обновлений самих файлов как в бине этого запрета существенных не было как говорил Flowseal, поэтому смысла обновлять этот репозиторий из орига пока что нет. Тут нет режима автохостлиста и нужен ли он тоже непонятно потому что есть вероятность что он может работать некорректно, что даже в основной репе запрета говорится о том что из листов автохоста некоторые ресурсы работающие некорректно придется удалять чтобы в них заново занеслось работой запрета. 

Так что как то так.

**Comment by Flowseal** [comment]
Автохостилст можно включить, если bol-van не менял синтаксис автохостлиста с того времени. Как это сделать - смотрите в оригинальном репозитории.
