### ISSUE TITLE
Error reading new version

### ISSUE THREAD

**Issue by rech2020** [Flowseal/zapret-discord-youtube#1048]
если честно я хз чо произошло
![image](https://github.com/user-attachments/assets/8f27fbbf-0428-43f1-9124-5f95dc3533e6)
после этого оно закрывается и не работает

**Comment by EgorWeders** [comment]
У вас какая версия? Выглядит как старая.

**Comment by Eptiy** [comment]
Выглядит так, будто у чекапдейта проблемы. Попробуй убрать строки из батника
```
call check_updates.bat soft
echo:
```
И запустить без них.

**Comment by serpen7** [comment]
если у вас есть файлик version.txt попробуйте его удалить.

**Comment by Flowseal** [comment]
Ошибка "Erorr reading new version" появляется, когда скрипт по проверке обновлений не смог прочитать актуальную версию на Github. Даже если возникла ошибка, она никак не вляет на основной скрипт.

Если что-то не работает, то читайте эту секцию README: [ссылка](https://github.com/Flowseal/zapret-discord-youtube?tab=readme-ov-file#%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC)
