### ISSUE TITLE
не удается найти файл проверьте правильно ли указано имя и повторите попытку

### ISSUE THREAD

**Issue by Felix10431** [Flowseal/zapret-discord-youtube#1054]
![image](https://github.com/user-attachments/assets/5f7dca04-d1ca-4c77-8927-889952fd35b2)

**Comment by Felix10431** [comment]
со временем срабатывает но там через час или около того

**Comment by Eptiy** [comment]
Что-то снесло файл, скорее всего - антивирус. Создай новую папку, добавь её в исключения защитника/любого другого антивируса, скачай в неё запрет, там распакуй и проверь работу.

**Comment by Felix10431** [comment]
![image](https://github.com/user-attachments/assets/8d7b4767-5941-4f5c-819a-fc5d42a0a455)
да нету антивируса если только значок щита сине желтый

**Comment by Eptiy** [comment]
Я не знаю, что такое "значок щита сине-желтый". В любой системе есть хотя бы защитник. Ты скинул скрин из него. Нужно добавить папку в его исключения. Как это сделать, можешь найти в интернете.

**Comment by Felix10431** [comment]
в антивирусе Майкрософт defender отключен а когда я говорил что сине-жёлтый щит я имел в виду режим администратора или что-то вроде того и также я ещё хотел добавить что через некоторое время примерно час возни у меня он включался дважды но я не понял как и мне не помогло то что я отключил встроенную защиту windows даже а твой способ не удалось осуществить как то так.

**Comment by Eptiy** [comment]
Защитник отключать может быть опасно, не советую. Встроенная защита винды - это и есть защитник. Запускаться запрет не будет в любом случае, если его файлы были удалены. В журнале защитника можно посмотреть его действия и узнать, удалял ли он файлы запрета.

**Comment by Eptiy** [comment]
> Лучше отключать :)

Это дело каждого. Если ты задрот всяких отключений "ненужных фич" и телеметрии, отключай ради бога. Если ты неопытный пользователь - уж точно не нужно отключать.

В данном случае отключение ничем не отличается от добавления в исключения. Если файлы билда исчезают даже после этого, то проблема в чём-то ещё.

**Comment by Felix10431** [comment]
я посмотрел сообщений о удалении файла не было. Ну если только я все правильно смотрел.

**Comment by Eptiy** [comment]
> я посмотрел сообщений о удалении файла не было. Ну если только я все правильно смотрел.

скинь скрин на всякий из журнала защитника.

Попробуй скачать заново в новую папку в корне диска, распаковать, проверить наличие папки bin и файлов в ней. И сами файлы не трогай, а то помню видел, как кто-то вытащил все файлы из папок и папки удалил. И обязательно распаковывай, не открывай прямо из архива, такие случаи тоже были.

**Comment by Felix10431** [comment]
а там какой-то очень важной информации не будет просто тут айди безопасности, адрес локал хост?

**Comment by Eptiy** [comment]
Где тут какая важная информация?
Это "журнал защиты" в защитнике. Находится в самом первом разделе программы, щиток нарисован, хз как на русском, у меня на английском.
![Screenshot 2024-12-24 010331](https://github.com/user-attachments/assets/209770db-af5d-4c56-86c1-f95b55ef9459)

**Comment by Felix10431** [comment]
Нет я не в windows а в Брандмауэре а та вкладка которую ты прислал у меня там пусто и пишет что „Служба работы с угрозами остановлена” и предлагают включить

**Comment by Eptiy** [comment]
Брандмауэр никак не может удалять файлы, тогда делай, что я писал дальше.

> Попробуй скачать заново в новую папку в корне диска, распаковать, проверить наличие папки bin и файлов в ней. И сами файлы не трогай, а то помню видел, как кто-то вытащил все файлы из папок и папки удалил. И обязательно распаковывай, не открывай прямо из архива, такие случаи тоже были.

**Comment by Felix10431** [comment]
А что ты имеешь в виду когда говоришь создать папку в КОРНЕ ДИСКА?

**Comment by Felix10431** [comment]
Просто я такой мамонт и в этой части (ПК, ноутбуков) не разбираюсь

**Comment by Eptiy** [comment]
Создай папку прямо на диске. Заходишь на диск, где лежат всякие program files, создаёшь папку рядом с ними. Имя лучше давать на английском без всяких спецсимволов и пробелов.

**Comment by Felix10431** [comment]
Реально помогло наверно это из за того что в  я после всё прям в бин отправлял после файлы и не английском писал благодарю за помощь и потраченное время
