### ISSUE TITLE
не работает дискорд

### ISSUE THREAD

**Issue by Guest531** [Flowseal/zapret-discord-youtube#1055]
у всех это работает у меня нет я качал разные версии но только ютуб и работает а на дискорде бесконечная загрузка , 1.5 версии пробовал из за Ростелекома не работают , если я устанавливал сервисы то при открытии сразу они выключаются P.s я читал разные схожие темы не работают

**Comment by BF3000** [comment]
Ага. У меня то же самое.
Upd. на алт2 заработало

**Comment by Guest531** [comment]
у тебя какая версия?

**Comment by Flowseal** [comment]
Пробуйте другие батники
А также https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by Guest531** [comment]
amneziaWG может мешать?

**Comment by Guest531** [comment]
да прикол в том что я не понимаю что не так вроде всё работает я всё батники проверил но дискорд отказывается работать

**Comment by Eptiy** [comment]
Амнезия мешать может только во включенном состоянии и разве что непосредственно работе запрета, не запуску батников/установочника. Если сами батники работают, но ни один из имеющихся не даёт доступа к дс, можешь поискать на гитхабе другие билды запрета, проверить конфиги в них. Самое простое - оригинал запрета под винду: https://github.com/bol-van/zapret-win-bundle. Ещё есть такой билд, там очень много конфигов: https://github.com/censorliber/zapret.
