### ISSUE TITLE
не работает дискорд

### ISSUE THREAD

**Issue by Guest531** [Flowseal/zapret-discord-youtube#1057]
у меня ростелеком пробовал разные версии не какие альты и мтгс не работают один раз написал просто закрыли и написали 251 я нечего там не понял там не было моего решения (может надо но у меня винда 10 про и на замене запрету AmneziaWG)

**Comment by Eptiy** [comment]
Амнезия мешать может только во включенном состоянии и разве что непосредственно работе запрета, не запуску батников/установочника. Если сами батники работают, но ни один из имеющихся не даёт доступа к дс, можешь поискать на гитхабе другие билды запрета, проверить конфиги в них. Самое простое - оригинал запрета под винду: https://github.com/bol-van/zapret-win-bundle. Ещё есть такой билд, там очень много конфигов: https://github.com/censorliber/zapret.

**Comment by Guest531** [comment]
спасибо для винды конфиг подошел всё работает на ура надеюсь он долго будет работать
