### ISSUE TITLE
Не открываются батники.

### ISSUE THREAD

**Issue by vood2d** [Flowseal/zapret-discord-youtube#1059]
при запуске любого батника - открывается окно терминала(пустое) и сразу же закрывается, без какого либо текста.

**Comment by vood2d** [comment]
я так понял у меня батники не хотят запускаться от имени администратора. Но как это пофиксить вообще не могу понять и найти решение. помогите люди добрые(

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/522
