### ISSUE TITLE
не работает дискорд

### ISSUE THREAD

**Issue by nal1mchik** [Flowseal/zapret-discord-youtube#1060]
батник открывается на секунду и сразу же отключается

**Comment by Eptiy** [comment]
До этого службу устанавливал через service_install? Службу гудбая когда-нибудь устанавливал? Проверь на всякий случай вкладку "службы" в диспетчере задач, удали службы запрета/гудбая, если есть, выполни service_remove в любом случае. Батники не работают, если есть установленная служба. Добавь в конце батника в новой строчке `pause` и сделай его скрин после запуска, скинь.

**Comment by Flowseal** [comment]
#522
