### ISSUE TITLE
Бесконечное подключение к RTC/не установлен маршрут к каналу.

### ISSUE THREAD

**Issue by 8say1321** [Flowseal/zapret-discord-youtube#1062]
Проблема появилась из неоткуда, все всегда работало нормально, но в какой-то момент случился вылет дискорда, и все перестало работать, к войсу невозможно подключиться.

Действия: 
1. Удаление сервиса
2. Перезагрузка ПК
3. Установка сервиса general.bat (пробовал все от 1 до 5)
4. Перезагрузка
5. Запуск дискорда.

в итоге ничего не работало, со всеми обходами не мог подключится к войсам.

Примечание:
1. Дискорд сам работает, но просто не подключается к войсу.
2. Ютуб также работает без каких-либо проблем.

Вопрос: 

Как пофиксить данную проблему?

Нету никаких проблем с интернет подключением и прочим.

**Comment by mehh0vcki** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/994#issuecomment-2553703670

**Comment by serpen7** [comment]
удали сервис и пробуй другие батники, какой заработает ставь как сервис, на дженерале обычном круг не замкнулся.

**Comment by Flowseal** [comment]
Пробуйте другие батники
А также https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by HowardTheAlienn** [comment]
Попробуй офис ркн взорвать, хз

**Comment by NoviXD** [comment]
Пробовал все советы. что были в ветке, в том числе смена региона в канале, ничего не сработало. Не подключается к войсу и висит на "Подключение к RTC"
