### ISSUE TITLE
Ростелеком, не работает вообще

### ISSUE THREAD

**Issue by DE0F1** [Flowseal/zapret-discord-youtube#1063]
пару дней назад дискорд перестал запускаться совсем, ютуб работал.
Сидел на версии 1.4, перепробовал все файлы, и результата ноль, перешел на 1.6, все тоже самое, плюс ютуб тоже стал работать сомнитетельно

**Comment by DE0F1** [comment]
покопался в других ишьюс и нашел рабочий вариант

**Comment by Eptiy** [comment]
Молодец, все бы так. Можешь сюда запостить решение, чтобы другим было легче найти.
