### ISSUE TITLE
Обход не останавливается/не удаляется

### ISSUE THREAD

**Issue by BlvckGh0st** [Flowseal/zapret-discord-youtube#1065]
Возможно конечно, что так и должно работать. Если так, то заранее извиняюсь.
В общем, запустил general.bat и YouTube работает нормально, но если я всё правильно понимаю, то при перезапуске ПК по идее эту процедуру надо проводить заново (service_install я не запускал), однако всё работает и так.

Запустил service_remove и он выдает следующее:
Restarted with admin rights
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

Использование команды >driverquery | find "Divert" результата не дает. 
Не, я конечно рад, что оно работает, но боюсь, как бы оно не повлияло на сторонние программы.
Всем заранее спасибо :)

**Comment by EgorWeders** [comment]
Вы запускаете удаление сервиса без его установки. Вам нечего удалять с service_remove

**Comment by Eptiy** [comment]
Проверить наличие установленной службы можно на соответствующей вкладке диспетчера задач. То, что доступ к ресурсам есть и после отключения/удаления запрета - совпадение, никак на работу любых ресурсов это не повлияет. На всякий случай можно проверить полностью заблокированные ресурсы (ютуб официально только "замедляется").

**Comment by serpen7** [comment]
у вас не стоит сервис судя по выводу, а так же не работает виндайверт. Если у вас сохраняется доступ и прочее - это уже не из за запрета.
