### ISSUE TITLE
Бесконечная проверка обновлений

### ISSUE THREAD

**Issue by LiLMaDDonuT** [Flowseal/zapret-discord-youtube#1068]
Еще в 3-4 утра все было ок. Проснулся - накрылось все. Все батники перепробывал, удалял и опять ставил через сервис. Не работает.

**Comment by Pan4ur** [comment]
\+

**Comment by serpen7** [comment]
по идее даже если не проходит проверка обновления версии запрета, оно должно её скипать и открывать батник. Явно чето вмешивается в процесс.

**Comment by Eptiy** [comment]
Батник виснет на check updates?

**Comment by LiLMaDDonuT** [comment]
Да, и идет постоянная попытка через n-секунд

**Comment by Eptiy** [comment]
Выполни service_remove, после, убедись, что службы в диспетчере задач нет. Создай новую папку в корне диска, назови латиницей без спец символов/пробелов, добавь в исключения антивируса/дефендера. Скачай последнюю версию запрета со вкладки релизов прямо в эту папку, распакуй. Проверяй все батники, не устанавливая службу.

Если не поможет, можешь попробовать оригинал запрета под винду: https://github.com/bol-van/zapret-win-bundle

**Comment by LiLMaDDonuT** [comment]
Первый вариант не работает, для второго я тупой и в коде не разбираюсь. Нужно объединять какие-то стратегии и знать как работает обход dpi.

**Comment by LiLMaDDonuT** [comment]
Разобрался, нужно в папке zapret-winws найти файл preset_russia.cmd и запустить(я сделал от имени администратора). Заработало.
Требует постоянного открытого окна .cmd

Edit: Обычный запрет снова заработал, не знаю почему, но ладно.
