### ISSUE TITLE
Проблема с некоторыми сайтами

### ISSUE THREAD

**Issue by Roshmak** [Flowseal/zapret-discord-youtube#1069]
"Не удается получить доступ к сайту Превышено время ожидания ответа от сайта" выдают некоторые сайты при использование zapret. Пробовал версии с 1.2 по 1.6.1
Основные сайты которые выдают это : Гитхаб (частично) , почти любой ГДЗ , Твич , ropro.io и другие
К дополнению начал тупить Ютуб и Дискорд

**Comment by Roshmak** [comment]
И да проблема только когда используется Zapret

**Comment by Eptiy** [comment]
скинь результат проверки с cloudflare-ech.com

**Comment by Roshmak** [comment]
выдаёт тоже самое

**Comment by Eptiy** [comment]
Выдаёт что? Не можешь зайти туда?

**Comment by Roshmak** [comment]
да выдает "Не удается получить доступ к сайту Превышено время ожидания ответа от сайта"

**Comment by Roshmak** [comment]
До это го дня у меня cloudflare работал

**Comment by Eptiy** [comment]
Батники все пробовал? Попробуй ещё оригинал запрета: https://github.com/bol-van/zapret-win-bundle

**Comment by Roshmak** [comment]
> Батники все пробовал? Попробуй ещё оригинал запрета: https://github.com/bol-van/zapret-win-bundle

Пробую оригинал запрета но файлы типа sh не открываются ни как

**Comment by Roshmak** [comment]
Cloudflare наконецто дал ответ
Защита DNS
Мы не смогли определить, используете ли вы DNS-резолвер с защитой передачи запросов. Обратитесь к DNS-провайдеру или попробуйте использовать 1.1.1.1 — быстрый и защищенный DNS-резолвер.
DNSSEC
Злоумышленники не смогут изменить DNS-ответ для домена, находящегося вне их контроля, и заставить вас перейти на поддельный веб-сайт.
TLS 1.3
Любой злоумышленник, отслеживающий сеть, может посмотреть сертификат веб-сайта, к которому вы подключились через TLS.
Защита SNI
Любой злоумышленник, отслеживающий сеть, может узнать, к какому именно веб-сайту вы подключились через TLS.

**Comment by Eptiy** [comment]
т.е. галка только на dnssec? Поставь в настройках сетевого адаптера днс 1.1.1.1 и 1.0.0.1, если есть возможность, включи dns over https на авто.

по поводу оригинала: либо читай доки к нему, либо - https://github.com/Flowseal/zapret-discord-youtube/issues/1068#issuecomment-2560989980

**Comment by Roshmak** [comment]
> 1.1.1.1

выдаёт также галачка только на dnssec

**Comment by Eptiy** [comment]
Скинь скрин этой вкладки настроек
![Screenshot 2024-12-24 203954](https://github.com/user-attachments/assets/e5dca9aa-275b-454a-9fa9-e1ce9e421020)

**Comment by Roshmak** [comment]
![image](https://github.com/user-attachments/assets/f8437633-3e59-4a47-b3bc-afc44f1a1072)
![image](https://github.com/user-attachments/assets/55d8d935-72a9-4f04-ac36-8a3d040b120c)

**Comment by Roshmak** [comment]
если что я использую виндоус 10

**Comment by Eptiy** [comment]
Я понял по скрину. Dns over https там не поддерживается.

Dns ты же прописал 1.1.1.1 и 1.0.0.1? По скрину не видно.

Попробуй ещё в браузере на вкладке безопасность/конфиденциальность включить безопасный днс и выбрать клаудфлэйр. После этого так же проведи проверку на cloudflare-ech.com.

**Comment by Roshmak** [comment]
Всё начало работать спасибо большое
