### ISSUE TITLE
Не открываются доки

### ISSUE THREAD

**Issue by ArtemidaGre** [Flowseal/zapret-discord-youtube#1071]
![image](https://github.com/user-attachments/assets/85860d11-7296-4887-a6c1-8b7f9427325e)
![image](https://github.com/user-attachments/assets/d74cb1ab-9d3f-4749-ad85-7c80b21a6a7b)

**Comment by serpen7** [comment]
ты перепутал репозитории.

**Comment by serpen7** [comment]
Не знаю почему ты так их открываешь потому что там МД, а не ТХТ
https://github.com/bol-van/zapret/blob/master/docs/quick_start.md
https://github.com/bol-van/zapret/blob/master/docs/readme.md

**Comment by serpen7** [comment]
А, все понял, ты открывал по старым ссылкам этим, bol-van менял немного структуру своего репозитория, так что там малость другие ссылки. Сорян не сразу понял.
