### ISSUE TITLE
OBS / Стриминг на YouTube

### ISSUE THREAD

**Issue by ct2plus** [Flowseal/zapret-discord-youtube#1073]
Благодаря Zapret можно комфортно пользоваться Дискордом и **смотреть** ролики на YouTube. Однако с каждым днем все хуже ситуация с **загрузкой** трафика на Ютуб, в частности со стримингом. Битрейт приходится подавать все ниже и ниже, с прошлой недели даже 5-7мб/сек стабильно практически нереально запустить. Опытным путем установлено, что шанс запуска стрима без Zapret равен или даже выше, чем с использованием обхода.

Буду рад любым адекватным советам. Использую alt 0-3.

**Comment by serpen7** [comment]
вы какой ДНС сервер используете?

**Comment by ct2plus** [comment]
сейчас в настройках роутера стоят

Primary DNS: 109.195.48.1
Secondary DNS: 5.3.3.3

все отлично через Zapret, кроме стриминга на Ютуб.
Dom.ru

**Comment by serpen7** [comment]
Запишите их куда нибудь, это днс адрес дома ру как я понимаю и они могут делать там с ним по адресам не малое. Второй вообще адрес эртелекома и непонятно зачем он там от другого провайдера. Хотя это может быть просто дочерка дом ру.
Вбейте 1.1.1.1 и вторичным 1.0.0.1
Либо же 8.8.8.8 и вторичным 8.8.4.4. попробуйте. 
К сожалению после применения настроек нужно будет перезагрузить роутер чтобы очистить записи, а так же ПК, желательно пока перезагружается роутер.

**Comment by ct2plus** [comment]
с гугловскими, по-моему, было не очень. но покрутить все попробую, спасибо.
а ЭР-телеком - это же и есть дом.ру, его родной ДНС автоматический, если мне не изменяет память

(+уточнение: да, там стояла автоматическая выдача обоих, кстати)

**Comment by serpen7** [comment]
> с гугловскими, по-моему, было не очень. но покрутить все попробую, спасибо. а ЭР-телеком - это же и есть дом.ру, его родной ДНС автоматический, если мне не изменяет память

в любом случае попробуйте сначала клаудфлеревский днс, там более безопаснее и побыстрее все.

**Comment by ct2plus** [comment]
большое спасибо, с первой же попытки тестовый поток подключился (на "единичках"), будем наблюдать. пригрел паразитирующего провайдера, получается
