### ISSUE TITLE
У друга не работает запрет.

### ISSUE THREAD

**Issue by De1znop** [Flowseal/zapret-discord-youtube#1076]
Пишет крч что не может найти какой-то файл как на оригинальном так и на этом репозитории
![изображение_2024-12-24_174950994](https://github.com/user-attachments/assets/8c73e1f1-390b-4095-8166-c3d99b0cc2bf)

**Comment by De1znop** [comment]
+касперский блокает дипиай

**Comment by Eptiy** [comment]
> +касперский блокает дипиай

Что это значит? Формулировка неверная в корне.

**Comment by serpen7** [comment]
Это что за запрет такой, откуда вы его качали? Не с ютуба случаем откуда-то из описания в запароленном архиве?

**Comment by Flowseal** [comment]
Это не моя сборка.
