### ISSUE TITLE
Не работает на мобильном МТС

### ISSUE THREAD

**Issue by vasvasilyev** [Flowseal/zapret-discord-youtube#108]
Здравствуйте. Только скачанный zapret, попробовал запустить discord.bat от админки, он запускается успешно, но дискорд всё ещё не может подключиться. Попробовал сам потыкать значения, но увы. Может помочь, кто разбирается в этом?

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
