### ISSUE TITLE
ДС работает очень перепадочно

### ISSUE THREAD

**Issue by Bears-Repeating** [Flowseal/zapret-discord-youtube#1085]
Установил zapret вчера. Файлы были разахивированы в папку с путем без кириллицы. Перетыкал все батники и Дискорд заработал только с батником general АLT2, но скорость соединения была чрезвычайно нестабильна; в одну минуту сообщения отсылаются моментально, в следующую - с задержкой в минуту-две или с нескольких попыток. Сегодня при включении того же батника Дискорд не заработал. Буквально минуту назад включил батник general MГТC2 и Дискорд работал нормально, но затем скорость соединения опять жестко упала, я попробовал перезапустить Дискорд и он перестал работать. Это можно как-то решить? Расскажите чайнику.

Ютуб меня не волнует. Ни один из батников как сервис я не устанавливал как раз из-за ожидания такой перепадочной работы. Батник discord не работает вообще.

**Comment by Bears-Repeating** [comment]
(под "скорость соединения была чрезвычайно нестабильна" подравумеваются сильные лаги. в одну минуту сообщения отсылаются моментально, в следующую - с задержкой в минуту-две иои с нескольких попыток)

**Comment by serpen7** [comment]
Если вы используете провайдерские днс сервера, то провайдер может химичить с ними вплоть до палева того что вы начинаете пользоваться дискордом и давить ответы от своего днс сервера насчет такой попытки. 
Попробуйте сменить днс сервера на клаудфлеревские 1.1.1.1 и вторичный 1.0.0.1. Либо же гугловские 8.8.8.8 и вторичный 8.8.4.4.

**Comment by Bears-Repeating** [comment]
> Если вы используете провайдерские днс сервера, то провайдер может химичить с ними вплоть до палева того что вы начинаете пользоваться дискордом и давить ответы от своего днс сервера насчет такой попытки. Попробуйте сменить днс сервера на клаудфлеревские 1.1.1.1 и вторичный 1.0.0.1. Либо же гугловские 8.8.8.8 и вторичный 8.8.4.4.

А вы не сможете подсказать, какой из них гарантирует наиболее стойкую и быструю скорость соединения? В этом плане как-то без разницы? Или изменение DNS сервера не влияет на скорость? Опять же, я в этих делах чайник, поэтому буду очень благодарен такой подсказке.

**Comment by serpen7** [comment]
> > Если вы используете провайдерские днс сервера, то провайдер может химичить с ними вплоть до палева того что вы начинаете пользоваться дискордом и давить ответы от своего днс сервера насчет такой попытки. Попробуйте сменить днс сервера на клаудфлеревские 1.1.1.1 и вторичный 1.0.0.1. Либо же гугловские 8.8.8.8 и вторичный 8.8.4.4.
> 
> А вы не сможете подсказать, какой из них гарантирует наиболее стойкую и быструю скорость соединения? В этом плане как-то без разницы? Или изменение DNS сервера не влияет на скорость? Опять же, я в этих делах чайник, поэтому буду очень благодарен такой подсказке.

Сначала клаудфлеревские попробуйте, у них получше с безопасностью и стабильностью.
Я бы сказал что днс не влияет на скорость если он работает нормально и как надо. Потому что скорость канала зависит от множества причин, первично от провайдера. Но с далеких 2016 я не сижу на провайдерских днс серверах потому что они бывают перегружены и падают по вечерам, либо долго отвечают. Как то тогда я попробовал скорость проверить и мне показало 60мбит вместо 94 с тарифом 100.  Долго грузились многие сайты и ресурсы. Простая смена днс на гугловские и проблемы больше не возникало вообще, а мучала она меня дней 5. Но сейчас я сижу на тех же клаудфлер днс серверах, потому что они побыстрее отвечают у меня чем гугловские и постабильнее работают и безопаснее. Клаудфлер все таки это безопасник в сети интернета.

**Comment by Bears-Repeating** [comment]
> > > Если вы используете провайдерские днс сервера, то провайдер может химичить с ними вплоть до палева того что вы начинаете пользоваться дискордом и давить ответы от своего днс сервера насчет такой попытки. Попробуйте сменить днс сервера на клаудфлеревские 1.1.1.1 и вторичный 1.0.0.1. Либо же гугловские 8.8.8.8 и вторичный 8.8.4.4.
> > 
> > 
> > А вы не сможете подсказать, какой из них гарантирует наиболее стойкую и быструю скорость соединения? В этом плане как-то без разницы? Или изменение DNS сервера не влияет на скорость? Опять же, я в этих делах чайник, поэтому буду очень благодарен такой подсказке.
> 
> сначала клаудфлеревские попробуйте, у них получше с безопасностью и стабильностью.

Попробовал. Теперь Дискорд звпускается только если я включу general ALT2 и затем быстро включу ALT4 в процессе "Checking for updates...*. Вроде бы нормально работает только если я еще на MГТС2 перескочу когда Дискорд запущен.

**Comment by serpen7** [comment]
> > > > Если вы используете провайдерские днс сервера, то провайдер может химичить с ними вплоть до палева того что вы начинаете пользоваться дискордом и давить ответы от своего днс сервера насчет такой попытки. Попробуйте сменить днс сервера на клаудфлеревские 1.1.1.1 и вторичный 1.0.0.1. Либо же гугловские 8.8.8.8 и вторичный 8.8.4.4.
> > > 
> > > 
> > > А вы не сможете подсказать, какой из них гарантирует наиболее стойкую и быструю скорость соединения? В этом плане как-то без разницы? Или изменение DNS сервера не влияет на скорость? Опять же, я в этих делах чайник, поэтому буду очень благодарен такой подсказке.
> > 
> > 
> > сначала клаудфлеревские попробуйте, у них получше с безопасностью и стабильностью.
> 
> Попробовал. Теперь Дискорд звпускается только если я включу general ALT2 и затем быстро включу ALT4 в процессе "Checking for updates...*. Вроде бы нормально работает только если я еще на MГТС2 перескочу когда Дискорд запущен.

если вы будете запускать несколько батников сразу вы будете создавать неимоверный "флуд" на канале передачи данных. Что не есть хорошо.

**Comment by Bears-Repeating** [comment]
> > > > > Если вы используете провайдерские днс сервера, то провайдер может химичить с ними вплоть до палева того что вы начинаете пользоваться дискордом и давить ответы от своего днс сервера насчет такой попытки. Попробуйте сменить днс сервера на клаудфлеревские 1.1.1.1 и вторичный 1.0.0.1. Либо же гугловские 8.8.8.8 и вторичный 8.8.4.4.
> > > > 
> > > > 
> > > > А вы не сможете подсказать, какой из них гарантирует наиболее стойкую и быструю скорость соединения? В этом плане как-то без разницы? Или изменение DNS сервера не влияет на скорость? Опять же, я в этих делах чайник, поэтому буду очень благодарен такой подсказке.
> > > 
> > > 
> > > сначала клаудфлеревские попробуйте, у них получше с безопасностью и стабильностью.
> > 
> > 
> > Попробовал. Теперь Дискорд звпускается только если я включу general ALT2 и затем быстро включу ALT4 в процессе "Checking for updates...*. Вроде бы нормально работает только если я еще на MГТС2 перескочу когда Дискорд запущен.
> 
> если вы будете запускать несколько батников сразу вы будете создавать неимоверный "флуд" на канале передачи данных. Что не есть хорошо.

Я заметил, что после изменения DNS адреса вручную и перезапуске модема с компьютером (или даже выхода из панели управления) настройка меняется обратно на "Получить DNS адрес автоматически". Возможно, это и является причниой моих проблем? Или так и должно быть? Если нет, то как это решить? В Гугле покопался, но ничего именно на такую проблему не нашел

**Comment by serpen7** [comment]
> Я заметил, что после изменения DNS адреса вручную и перезапуске модема с компьютером (или даже выхода из панели управления) настройка меняется обратно на "Получить DNS адрес автоматически". Возможно, это и является причниой моих проблем? Или так и должно быть? Если нет, то как это решить? В Гугле покопался, но ничего именно на такую проблему не нашел

у вас роутер от провайдера?

**Comment by Bears-Repeating** [comment]
> > Я заметил, что после изменения DNS адреса вручную и перезапуске модема с компьютером (или даже выхода из панели управления) настройка меняется обратно на "Получить DNS адрес автоматически". Возможно, это и является причниой моих проблем? Или так и должно быть? Если нет, то как это решить? В Гугле покопался, но ничего именно на такую проблему не нашел
> 
> у вас роутер от провайдера?

Да.

**Comment by serpen7** [comment]
> > > Я заметил, что после изменения DNS адреса вручную и перезапуске модема с компьютером (или даже выхода из панели управления) настройка меняется обратно на "Получить DNS адрес автоматически". Возможно, это и является причниой моих проблем? Или так и должно быть? Если нет, то как это решить? В Гугле покопался, но ничего именно на такую проблему не нашел
> > 
> > 
> > у вас роутер от провайдера?
> 
> Да.

Тогда никак по простому, это проблема прошивки роутера если она меняется почему то обратно. Хотя возможно вы просто забыли сохранить изменения внесенные в роутер но это маловероятно т.к. такое встречал обычно только на старых версиях где нужно было сохранять пресеты сети. Вы можете по идее вбить днс на компьютере в настройках сетевой карты ipv4 протоколе. Это конечно не будет работать на другие девайсы т.к. это не на роутере, но работать должно 
![image](https://github.com/user-attachments/assets/e54d49a3-f950-46b7-b2e2-99a31245285e)

**Comment by Bears-Repeating** [comment]
> > > > Я заметил, что после изменения DNS адреса вручную и перезапуске модема с компьютером (или даже выхода из панели управления) настройка меняется обратно на "Получить DNS адрес автоматически". Возможно, это и является причниой моих проблем? Или так и должно быть? Если нет, то как это решить? В Гугле покопался, но ничего именно на такую проблему не нашел
> > > 
> > > 
> > > у вас роутер от провайдера?
> > 
> > 
> > Да.
> 
> Тогда никак по простому, это проблема прошивки роутера если она меняется почему то обратно. Хотя возможно вы просто забыли сохранить изменения внесенные в роутер но это маловероятно. Вы можете по идее вбить днс на компьютере в настройках сетевой карты ipv4 протоколе. Это конечно не будет работать на другие девайсы т.к. это не на роутере, но работать должно ![image](https://private-user-images.githubusercontent.com/134365619/398563025-e54d49a3-f950-46b7-b2e2-99a31245285e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjI4MDQsIm5iZiI6MTczNTEyMjUwNCwicGF0aCI6Ii8xMzQzNjU2MTkvMzk4NTYzMDI1LWU1NGQ0OWEzLWY5NTAtNDZiNy1iMmUyLTk5YTMxMjQ1Mjg1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMDI4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWYxY2U0YjI5MWFkNGE1MzdiODZjYTJhZWQ1NmZmN2JlMTE4NTgxMDZjOGJlMGIxOTg3MTFmMTcxNzYzZmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tk8wxV7IrPNEJTGYp52vj3oJMIu8rxQ5w9cIDr5VYDA)

Я именно через ipv4 все и делвл. Вбиваю адрес, сохраняю нажатием "ОК", выхожу из панели управления, перезапускаю роутер с компьотером, захожу в панель управления для проверки адреса и вижу, что оно переключилось обратно на автоматическое получение адреса.

**Comment by serpen7** [comment]
>  Я именно через ipv4 все и делвл. Вбиваю адрес, сохраняю нажатием "ОК", выхожу из панели управления, перезапускаю роутер с компьотером, захожу в панель управления для проверки адреса и вижу, что оно переключилось обратно на автоматическое получение адреса.

может у вас какая то защита стоит от смены днс? Яндекс защитник или чето подобное?
Тут два варианта, либо попробовать обновить драйвера на сетевую карту, может с ними что-то не то, либо что то влияет на её настройки и не дает менять днс адрес возвращая его на автоматический.

**Comment by Bears-Repeating** [comment]
> > Я именно через ipv4 все и делвл. Вбиваю адрес, сохраняю нажатием "ОК", выхожу из панели управления, перезапускаю роутер с компьотером, захожу в панель управления для проверки адреса и вижу, что оно переключилось обратно на автоматическое получение адреса.
> 
> может у вас какая то защита стоит от смены днс? Яндекс защитник или чето подобное?

Нет, Яндексом я в принципе не пользуюсь. Пока в Гугле копался, видел, что упоминалось что-то под названием "DHCP", но в такую глубь компьютера лезть не очень хочется

**Comment by serpen7** [comment]
> DHCP

это как раз таки протокол автоматической конфигурации сети, которым трогать особо не нужно. Хотя у себя в хроме в настройках я такого не нахожу 
![image](https://github.com/user-attachments/assets/2648e841-d7bf-4b4c-af11-65b8438776ab)

**Comment by Bears-Repeating** [comment]
> > DHCP
> 
> это как раз таки протокол автоматической конфигурации сети, которым трогать особо не нужно. Хотя у себя в хроме в настройках я такого не нахожу ![image](https://private-user-images.githubusercontent.com/134365619/398564307-2648e841-d7bf-4b4c-af11-65b8438776ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjM1NDMsIm5iZiI6MTczNTEyMzI0MywicGF0aCI6Ii8xMzQzNjU2MTkvMzk4NTY0MzA3LTI2NDhlODQxLWQ3YmYtNGI0Yy1hZjExLTY1Yjg0Mzg3NzZhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMDQwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGU2Yjk4MjNkNDE3NTkzYjMxYjRkZmEzZmMwM2M4YTQxYjYzZWM2OTJiYzNkZGI1MTAwMDk4YTNjZDdkZThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tITQJhYHm_KVU0-khcqGAJKZd3yP8KzvP_kigNS3gws)

Попробовал обновить драйвера сетевого адаптера, но вроде бы как "наиболее подходящие драйвера уже установлены".

**Comment by serpen7** [comment]
> > > DHCP
> > 
> > 
> > это как раз таки протокол автоматической конфигурации сети, которым трогать особо не нужно. Хотя у себя в хроме в настройках я такого не нахожу ![image](https://private-user-images.githubusercontent.com/134365619/398564307-2648e841-d7bf-4b4c-af11-65b8438776ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjM1NDMsIm5iZiI6MTczNTEyMzI0MywicGF0aCI6Ii8xMzQzNjU2MTkvMzk4NTY0MzA3LTI2NDhlODQxLWQ3YmYtNGI0Yy1hZjExLTY1Yjg0Mzg3NzZhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMDQwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGU2Yjk4MjNkNDE3NTkzYjMxYjRkZmEzZmMwM2M4YTQxYjYzZWM2OTJiYzNkZGI1MTAwMDk4YTNjZDdkZThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tITQJhYHm_KVU0-khcqGAJKZd3yP8KzvP_kigNS3gws)
> 
> Попробовал обновить драйвера сетевого адаптера, но вроде бы как "наиболее подходящие драйвера уже установлены".

Не, это не то. нужно дрова скачать либо с сайта производителя сетевухи, либо с сайта производителя материнки.

Какая у тебя сетевуха можешь посмотреть?

**Comment by Bears-Repeating** [comment]
> > > > DHCP
> > > 
> > > 
> > > это как раз таки протокол автоматической конфигурации сети, которым трогать особо не нужно. Хотя у себя в хроме в настройках я такого не нахожу ![image](https://private-user-images.githubusercontent.com/134365619/398564307-2648e841-d7bf-4b4c-af11-65b8438776ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjM1NDMsIm5iZiI6MTczNTEyMzI0MywicGF0aCI6Ii8xMzQzNjU2MTkvMzk4NTY0MzA3LTI2NDhlODQxLWQ3YmYtNGI0Yy1hZjExLTY1Yjg0Mzg3NzZhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMDQwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGU2Yjk4MjNkNDE3NTkzYjMxYjRkZmEzZmMwM2M4YTQxYjYzZWM2OTJiYzNkZGI1MTAwMDk4YTNjZDdkZThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tITQJhYHm_KVU0-khcqGAJKZd3yP8KzvP_kigNS3gws)
> > 
> > 
> > Попробовал обновить драйвера сетевого адаптера, но вроде бы как "наиболее подходящие драйвера уже установлены".
> 
> Не, это не то. нужно дрова скачать либо с сайта производителя сетевухи, либо с сайта производителя материнки.
> 
> Какая у тебя сетевуха можешь посмотреть?

Intel(R) Wi-Fi 6 AX200 160MHz

**Comment by serpen7** [comment]
> Intel(R) Wi-Fi 6 AX200 160MHz

ааааааааа, теперь понятнее стало. Обновлять да не получится походу, но у меня малые неприятных новости я ее знаю и с ней да, творятся разного рода странности по коннектам. И там в настройках сетевухи продвинутых надо отключать всякие "зеленые" технологии, чтобы она работала нормально. Плюс у нее помоему свое ПО тоже есть, точно не помню, но оно как раз таки может и контролировать сетевые настройки.

**Comment by Bears-Repeating** [comment]
> > Intel(R) Wi-Fi 6 AX200 160MHz
> 
> ааааааааа, теперь понятнее стало. Обновлять да не получится походу, но у меня малые неприятных новости я ее знаю и с ней да, творятся разного рода странности по коннектам. И там в настройках сетевухи продвинутых надо отключать всякие "зеленые" технологии, чтобы она работала нормально. Плюс у нее помоему свое ПО тоже есть, точно не помню, но оно как раз таки может и контроллировать сетевые настройки.

Как можно получить доступ к этим продвинутым настройкам и какие технологии нужно отключать? И что-то можно сделать с прог. обеспечением без вмешательства специалиста, или его лучше не трогать?

**Comment by serpen7** [comment]
> > > Intel(R) Wi-Fi 6 AX200 160MHz
> > 
> > 
> > ааааааааа, теперь понятнее стало. Обновлять да не получится походу, но у меня малые неприятных новости я ее знаю и с ней да, творятся разного рода странности по коннектам. И там в настройках сетевухи продвинутых надо отключать всякие "зеленые" технологии, чтобы она работала нормально. Плюс у нее помоему свое ПО тоже есть, точно не помню, но оно как раз таки может и контроллировать сетевые настройки.
> 
> Как можно получить доступ к этим продвинутым настройкам и какие технологии нужно отключать? И что-то можно сделать с прог. обеспечением без вмешательства специалиста, или его лучше не трогать?

мне бы их видеть чтобы говорить что нужно отрубать но из своих воспоминаний кстати нашел одну из настроек которую надо отрубать
![image](https://github.com/user-attachments/assets/0bbdcdc9-2d74-48ac-8a4e-f3380a394792)
А продвинутые настройки, жмешь настроить на свойстве адаптера 
![image](https://github.com/user-attachments/assets/3bfa626b-e98d-4c38-994d-5c6325297973)
и там выбираешь дополнительно 
![image](https://github.com/user-attachments/assets/cb3c3ba7-0b72-40b5-a42e-1d127336abae)

**Comment by Bears-Repeating** [comment]
> > > > Intel(R) Wi-Fi 6 AX200 160MHz
> > > 
> > > 
> > > ааааааааа, теперь понятнее стало. Обновлять да не получится походу, но у меня малые неприятных новости я ее знаю и с ней да, творятся разного рода странности по коннектам. И там в настройках сетевухи продвинутых надо отключать всякие "зеленые" технологии, чтобы она работала нормально. Плюс у нее помоему свое ПО тоже есть, точно не помню, но оно как раз таки может и контроллировать сетевые настройки.
> > 
> > 
> > Как можно получить доступ к этим продвинутым настройкам и какие технологии нужно отключать? И что-то можно сделать с прог. обеспечением без вмешательства специалиста, или его лучше не трогать?
> 
> мне бы их видеть чтобы говорить что нужно отрубать

Точно, мне нужно было сначала предоставить скрины. Прошу прощения за неудобство
![Снимок экрана (34)](https://github.com/user-attachments/assets/12964fb1-f650-4a07-a698-ed8dbe2c1153)
![Снимок экрана (35)](https://github.com/user-attachments/assets/3b1f8e67-3c76-4b1e-aca0-28c8ccaee278)

**Comment by serpen7** [comment]
ты же через вайфай сидишь получается, не по проводу точно?

**Comment by serpen7** [comment]
по идее тебе только MIMO Power Save Mode нужно вырубить, переведя его на No SMPS и U-APSD support, если он включен тоже вырубить в положение disabled. И еще проверить Throughput Booster, его тоже наверное придется выключить в положение disabled. Packet Coalescing скорее всего тоже на выруб в положение disabled. Некоторые настройки могут быть вырублены по дефолту, так что их если они вырублены трогать не стоит.

**Comment by Bears-Repeating** [comment]
> ты же через вайфай сидишь получается, не по проводу точно?

Я так думаю? Ну провод от модема к компьютеру подключать для подключения к интернету мне не приходится, конечно

**Comment by serpen7** [comment]
А так там помоему в софте твоего ноута есть управление сетевухой тоже, так что смену днсов и прочего нужно будет посмотреть там, потому что многовероятно именно оно и сбрасывает настройки днс адресов на дефолт т.к. это меняется не через его софт.

**Comment by Bears-Repeating** [comment]
Понятно, возьму на заметку. Пока что Дискорд вроде бы нормализовался, но в соучае чего хотя бы будет этот тред под рукой. Большое спасибо за разьяснение!
