### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by Lordtimer** [Flowseal/zapret-discord-youtube#109]
Ютуб работает но, он прогружает половину видео, что через оригинальный goodbyedpi что через запрет, тоесть половина видео и превью и видео работает а половина превью есть а открываешь видео и там бесконечная загрузка. Вроде все перечисленные способы потыкал.

**Comment by MistikLove** [comment]
у меня вот странно - у меня работает почти нормально только в браузере firefox вообще не пашет а в других норм - что это может быть?

**Comment by TROYANCIK** [comment]
> Ютуб работает но, он прогружает половину видео, что через оригинальный goodbyedpi что через запрет, тоесть половина видео и превью и видео работает а половина превью есть а открываешь видео и там бесконечная загрузка. Вроде все перечисленные способы потыкал.

У меня грузяться превьюшки и комментарии под видео, но на самих видосах бесконечная загрузка

**Comment by AzioNik** [comment]
Началось в ночь с 10.10.2024 Youtube, бесконечная загрузка видео через goodbyedpi и zapret, Ростелеком, превью и комменты грузит

upd нашёл как починить goodbyedpi

start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
работает с 10.10.2024 ростелеком

**Comment by newexgamer** [comment]
Я изменил значение до 5 здесь --dpi-desync-autottl=2 видео на ютубе начали грузиться, но с задержкой, проблема осталась.

**Comment by saoandrey2002** [comment]
> Началось в ночь с 10.10.2024 Youtube, бесконечная загрузка видео через goodbyedpi и zapret, Ростелеком, превью и комменты грузит
> 
> upd нашёл как починить goodbyedpi
> 
> start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt работает с 10.10.2024 ростелеком

Это в каком файле внесена корректировка?

**Comment by KST-roid** [comment]
> > Началось в ночь с 10.10.2024 Youtube, бесконечная загрузка видео через goodbyedpi и zapret, Ростелеком, превью и комменты грузит
> > upd нашёл как починить goodbyedpi
> > start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt работает с 10.10.2024 ростелеком
> 
> Это в каком файле внесена корректировка?

в одном из файлов goodbyedpi, на выбор, в моём случае 1_russia_blacklist_YOUTUBE, мне помогло тоже ростелеком

**Comment by saoandrey2002** [comment]
> > > Началось в ночь с 10.10.2024 Youtube, бесконечная загрузка видео через goodbyedpi и zapret, Ростелеком, превью и комменты грузит
> > > upd нашёл как починить goodbyedpi
> > > start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt работает с 10.10.2024 ростелеком
> > 
> > 
> > Это в каком файле внесена корректировка?
> 
> в одном из файлов goodbyedpi, на выбор, в моём случае 1_russia_blacklist_YOUTUBE, мне помогло тоже ростелеком

Не работает. :( Хотя, может, дело в том, что я hex заменил.

**Comment by yar83** [comment]
Помогите пожалуйста - не могу менять параметры в батнике service_discord_youtube для просмотра видео на ютубе. При сохранении изменений появляется сообщение: "Отсутствуют разрешения на открытия этого файла. Обратитесь к владельцу файла или администратору сети". Хотя у меня учетная запись под Администратором.

**Comment by Himura777789** [comment]
> у меня вот странно - у меня работает почти нормально только в браузере firefox вообще не пашет а в других норм - что это может быть?

Перейдите по ссылке about:config
Найдите пункт network.http.http3.enabled и переведите переключатель в положение True. Повторите то же самое с security.tls.enable_kyber

**Comment by yar83** [comment]
> > у меня вот странно - у меня работает почти нормально только в браузере firefox вообще не пашет а в других норм - что это может быть?
> 
> Перейдите по ссылке about:config Найдите пункт network.http.http3.enabled и переведите переключатель в положение True. Повторите то же самое с security.tls.enable_kyber

Эти параметры разве надо включать? На GoodbyeDPI их наоборот надо отключать. По крайней мере qick и kyber. Или это другие параметры?

P.S.: подскажите как убрать задержку загрузки видео на ютубе, если это возможно?

**Comment by Nolkered** [comment]
> Я изменил значение до 5 здесь --dpi-desync-autottl=2 видео на ютубе начали грузиться, но с задержкой, проблема осталась.

Спасибо.! Весь вечер пытался починить ютуб. Не знаю в чем проблема ,но после использования запрета перестал работать ютуб с гудбайдипиай, благодаря тебе ютуб заработал на запрете. Так же  может кому поможет перевел quic и kyber в (://flags) на disable.(п.с. провайдер билайн)

**Comment by Himura777789** [comment]
> > > у меня вот странно - у меня работает почти нормально только в браузере firefox вообще не пашет а в других норм - что это может быть?
> > 
> > 
> > Перейдите по ссылке about:config Найдите пункт network.http.http3.enabled и переведите переключатель в положение True. Повторите то же самое с security.tls.enable_kyber
> 
> Эти параметры разве надо включать? На GoodbyeDPI их наоборот надо отключать. По крайней мере qick и kyber. Или это другие параметры?
> 
> P.S.: подскажите как убрать задержку загрузки видео на ютубе, если это возможно?

Для Мозиллы нужно включить то что я написал, Для браузеров на Chromium, таких как Гугл Хром, Опера, Яндекс Браузер и так далее(их много на самом деле) нужно пробовать разные комбинации этих двух настреок, как вкл. так и выкл, кому что помогает
Google Chrome
Перейдите по ссылке chrome://flags/.
Найдите пункт #enable-quic и переведите переключатель в положение Enabled. Повторите то же самое с #enable-tls13-kyber.
Opera
Перейдите по ссылке opera://flags/.
Найдите пункт #enable-quic и переведите переключатель в положение Enabled. Повторите то же самое с #enable-tls13-kyber.
«Яндекс Браузер»
Перейдите по ссылке browser://flags/.
Найдите пункт #enable-quic и переведите переключатель в положение Enabled. Повторите то же самое с #enable-tls13-kyber.
Microsoft Edge
Перейдите по ссылке edge://flags/.
Найдите пункт #enable-quic и переведите переключатель в положение Enabled. Повторите то же самое с #enable-tls13-kyber.
После изменения настроек перезапустите браузер, чтобы изменения вступили в силу. Если не сработало, попробуйте проделать те же действия, но изменить значения у флагов на Disabled или False, либо попробуйте включить один флаг и отключить другой в разных сочетаниях. Судя по отзывам в Сети, в разных ситуациях срабатывают разные настройки.
А конкретно для Мозиллы нужно обязательно включать network.http.http3.enabled и security.tls.enable_kyber

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90
