### ISSUE TITLE
not found "C:\Users\user\AppData\Local\Temp\7zO0DB4F71E\bin\winws.exe"

### ISSUE THREAD

**Issue by enigma5656835** [Flowseal/zapret-discord-youtube#1092]
![photo_5431858892192738581_x](https://github.com/user-attachments/assets/3973001e-d898-4dfe-8497-74c9485c513a)
it used to work on older versions as well . and after prolonged non-use of the computer , it stopped working even on newer versions . I do not know why nothing is displayed in the folder for the PC he is looking for. I've already tried reinstalling it completely. pls help

**Comment by serpen7** [comment]
It's a temp folder. You are not unpacked whole program in it's own folder and trying to launch from and archive. 
Это временная папка. Вы не распаковали всю программу в ее собственную папку и пытаетесь запустить одиночный файл из архива, вместо того чтобы нормально разархивировать и запускать целую программу со всеми файлами. Папка не должна содержать спецсимволов и быть на английском языке по пути, учтите.
