### ISSUE TITLE
ВСЕ ПЕРЕПРОБЫВАЛ НИЧЕГО НЕ ПОМОГАЕТ В ПРОГЕ ZAPRET ПРИ ЗАПУСКЕ BAT ФАЙЛОВ 11 WINDOWS

### ISSUE THREAD

**Issue by MSHKFREDE26** [Flowseal/zapret-discord-youtube#1097]
![Снимок экрана 2024-12-26 214100](https://github.com/user-attachments/assets/72e7521d-adbb-4d2b-98b6-14cddba71703)

**Comment by serpen7** [comment]
И не поможет потому что вы отдельные файлы программы пытаетесь запустить из архива, не разархивируя целую программу в папку(папка должна быть на английском языке и без спец символов). По отдельности файлы целой программы не работают и не будут, вам нужны все файлы  и вся программа именно в одной папке.
![image](https://github.com/user-attachments/assets/e9604f8d-3661-4dd7-bb3a-5566c62f5ddd)
