### ISSUE TITLE
"Skipping the update check because it hasnt been 6 hours" - Непонятная ошибка, пробовал разные версии: Везде одно и тоже

### ISSUE THREAD

**Issue by Maximdota2** [Flowseal/zapret-discord-youtube#1098]
![Снимок экрана 2024-12-26 195406](https://github.com/user-attachments/assets/ac797bc2-9d20-4791-97b2-071d1ceca215)

**Comment by Maximdota2** [comment]
ВАЖНО!!!!! Итак-с-с-с, начнем:
       Если у вас такая же проблема зайдите в папку "Bin",  далее запустите "winws.exe". Лично у меня сильно пролагало (комп мощный) и через 20-30 секунд отвисло. Попробовал заново запустить "General" и  все заработало. Пишу для людей с такой же проблемой

**Comment by serpen7** [comment]
Skipping the update check because it hasnt been 6 hours означает что скипает проверку апдейта. У вас все равно должно запускаться после этого. Если не запускается то возможно у вас работает сервис и его нужно удалить батником сервис ремув от имени администратора.
