### ISSUE TITLE
[SC] OpenService FAILED 1060 - помогите пожалуйста исправить

### ISSUE THREAD

**Issue by Devirelle** [Flowseal/zapret-discord-youtube#1099]
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

Собственно, выдает такую ошибку при установке любого батника из списка. Запускаю от имени администратора, дискорд работает, ютуб грузит только 59 секунд видео.  Браузер опера, ютуб добавлен в исключения в блокировщике рекламы.

**Comment by Flowseal** [comment]
а) это не ошибка
б) 59 секунд не связана с запретом.

Попробуйте выйти из аккаунта
Попробуйте открыть в режиме инкогнито
Попробуйте выключить любые блокираторы рекламы (pi-hole, AdGuard, встроенные и расширения браузера)
Попробуйте установить расширение: [ссылка](https://chromewebstore.google.com/detail/%D0%BE%D0%B1%D1%85%D0%BE%D0%B4-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BE%D0%BA-%D1%80%D1%83%D0%BD%D0%B5%D1%82%D0%B0/npgcnondjocldhldegnakemclmfkngch?hl=ru)

**Comment by serpen7** [comment]
Это не ошибка а системное оповещение, у вас все нормально прошло. 59 секунд это глобальная проблема на стороне ютуба, причем плавающая и связанная с самими аккаунтами, и возможно как предполагают на том же реддите она связана с тем что ютуб детектит какую то блокировку рекламы на странице ютуба.

**Comment by Devirelle** [comment]
В браузере у меня только встроенный блокировщик + Censor Tracker,  все рекомендации из мегатреда по ютубу тоже были выполнены. Реклама на ютубе не блочится, проверяла через впн (с ним по 2 штуки на каждом видео вылезало). В треде я нашла ссылку на обсуждение таких блокировок от ютуба на реддите и мне помог сброс DNS через команду, по крайней мере пока. Пока искала решение просто рассматривала это оповещение как одну из причин, пасибо за помощь!

**Comment by vovisim** [comment]
как в итоге решили проблемму? тоже самое просто

**Comment by Devirelle** [comment]
Мне помогло вот это 
![image](https://github.com/user-attachments/assets/2ca92c0f-6104-44bc-b15b-196e825171fe)
+ расширение Censor Tracker, ну и я на всякий поковырялась в настройке блокировщика рекламы оперы и добавила ютуб в исключения. Вообще все рекомендации из закрепленного сообщения в мегатреде по ютубу выполнила. Удачи!
UPD. Обязательно проверь с впн, показывает ли ютуб тебе рекламу, чтобы убедиться что проблема не в ее блокировщике.
