### ISSUE TITLE
Дискорд все равно не работает(МТС/МГТС)

### ISSUE THREAD

**Issue by Tacelidi** [Flowseal/zapret-discord-youtube#11]
Возможно дело в провайдере(МТС).
Путь к файлу:F:\ura

**Comment by SanStefik** [comment]
У меня билайн - все работает

**Comment by Loerft** [comment]
Такая же проблема. Провайдер МГТС

**Comment by PandaYaY** [comment]
Да, проверял со знакомым, у него работает, а у меня с МТС не работает. Путь нормальный, все остальные впн и goodbye-dpi отключил

**Comment by IDEWES** [comment]
Хз у меня мгтс все отлично работает.

**Comment by JordanELs** [comment]
Дискорд, ютуб, даже твиттер после того как в general list его добавил работают. Но к голосовым каналам в дискорде всё ещё не подключается. Провайдер - Билайн.

**Comment by vladislavt345** [comment]
Я МТС - все работает. Отключил GoodbyeDPI в службах, почистил пк и все работает. Спасибо большое за фикс дискорда!

**Comment by Memorizeu** [comment]
МТС Москва, тоже работает, выключил гудбайдпи, перезагрузил компьютер, от имени админа запустил дискорд файл, в сам дискорд заходит, но при попытке подключиться к каналам - идет бесконечное подключение
Есть какие-то варианты? Что можно сделать? Что и в каком файле поменять? Гудбайдпи с ютубом справляется хорошо, последняя обнова помогает уже месяц с лишним

**Comment by Frozildish** [comment]
К голосовым каналам не пускает, провайдер МГТС.

**Comment by omega772** [comment]
Провайдр - МТС, работает всё, кроме голосовых каналов дискорда. С другими сборками на базе zapret-а тоже самое.

**Comment by Loerft** [comment]
@sSakuray  Да, с МГТС проблемы. Я с телефона раздал билайн ( смог подключиться к войсу)

**Comment by burnedoutman** [comment]
у меня тоже мтс, я подобрал свои параметры и всё работает. попробуйте, только старую службу удалите и имя вашего списка проверьте/поправьте

```
set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 ^
--wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 ^
--filter-udp=443 --hostlist=\"%~dp0list-general.txt\" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic=\"%~dp0quic_initial_www_google_com.bin\" --new ^
--filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic=\"%~dp0quic_initial_www_google_com.bin\" --new ^
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-tcp=443 --hostlist=\"%~dp0list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=\"%~dp0tls_clienthello_www_google_com.bin\" --new ^
--dpi-desync=fake,disorder2 --dpi-desync-autottl=2

set SRVCNAME=zapret

net stop "%SRVCNAME%"
sc delete "%SRVCNAME%"
sc create "%SRVCNAME%" binPath= "%~dp0winws.exe %ARGS%" DisplayName= "zapret DPI bypass : winws1" start= auto
sc description "%SRVCNAME%" "zapret DPI bypass software"
sc start "%SRVCNAME%"
```

**Comment by prostopadla** [comment]
> у меня тоже мтс, я подобрал свои параметры и всё работает. попробуйте, только старую службу удалите и имя вашего списка проверьте/поправьте
> 
> ```
> set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 ^
> --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 ^
> --filter-udp=443 --hostlist=\"%~dp0list-general.txt\" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic=\"%~dp0quic_initial_www_google_com.bin\" --new ^
> --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic=\"%~dp0quic_initial_www_google_com.bin\" --new ^
> --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
> --filter-tcp=443 --hostlist=\"%~dp0list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=\"%~dp0tls_clienthello_www_google_com.bin\" --new ^
> --dpi-desync=fake,disorder2 --dpi-desync-autottl=2
> 
> set SRVCNAME=zapret
> 
> net stop "%SRVCNAME%"
> sc delete "%SRVCNAME%"
> sc create "%SRVCNAME%" binPath= "%~dp0winws.exe %ARGS%" DisplayName= "zapret DPI bypass : winws1" start= auto
> sc description "%SRVCNAME%" "zapret DPI bypass software"
> sc start "%SRVCNAME%"
> ```

это решает проблему минут на 15, подключается к гс каналам, даже на звонки коннектит, но через какое-то время тупо перестаёт работать

**Comment by burnedoutman** [comment]
> > у меня тоже мтс, я подобрал свои параметры и всё работает. попробуйте, только старую службу удалите и имя вашего списка проверьте/поправьте
> > ```
> > set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 ^
> > --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 ^
> > --filter-udp=443 --hostlist=\"%~dp0list-general.txt\" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic=\"%~dp0quic_initial_www_google_com.bin\" --new ^
> > --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic=\"%~dp0quic_initial_www_google_com.bin\" --new ^
> > --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
> > --filter-tcp=443 --hostlist=\"%~dp0list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=\"%~dp0tls_clienthello_www_google_com.bin\" --new ^
> > --dpi-desync=fake,disorder2 --dpi-desync-autottl=2
> > 
> > set SRVCNAME=zapret
> > 
> > net stop "%SRVCNAME%"
> > sc delete "%SRVCNAME%"
> > sc create "%SRVCNAME%" binPath= "%~dp0winws.exe %ARGS%" DisplayName= "zapret DPI bypass : winws1" start= auto
> > sc description "%SRVCNAME%" "zapret DPI bypass software"
> > sc start "%SRVCNAME%"
> > ```
> 
> можешь , пожалуйста , детально расписать процесс , как ты получал эти параметры для своей сети? Я просто пробовал использовать поиск стратегии , но ничего не получилось , не понял как и что.

почитай readme https://github.com/bol-van/zapret
в блоке Проверка провайдера написано что и как

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
