### ISSUE TITLE
Ошибка на этапе запуска файла service

### ISSUE THREAD

**Issue by Povid1o** [Flowseal/zapret-discord-youtube#110]
`Press any key to continue . . .
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 18912
        FLAGS              :
Press any key to continue . . .
`
Запускал и переустанавливал пару раз, что любопытно, при попытке остановки WRT через консоль всё успешно, а удалить не получается - такого файла не существует.
Обычные БАТники тоже совершенно не работают(запускаю от админа, путь D:\BlockBreak\) , единственное что был включен Касперский на первом запуске, но при последующих его вырубил + он и не ругался

**Comment by Flowseal** [comment]
Судя по логам, у вас всё успешно запустилось. Если что-то не работает, зайдите в соотв. issue
Youtube - https://github.com/Flowseal/zapret-discord-youtube/issues/90
Discord - https://github.com/Flowseal/zapret-discord-youtube/issues/92
