### ISSUE TITLE
Дискорд повис на "Checking for updates" со всеми батниками

### ISSUE THREAD

**Issue by wondergrauf** [Flowseal/zapret-discord-youtube#1103]
Собственно, сабж. Перепробовал все батники (discord и general со всеми alt-конфигами) - никакой из них не помогает. Дискорд при запуске зависает на "Checking for updates" на каждом из них. Пробовал посмотреть альтернативные конфиги в ветке обсуждения Дискорда - тоже ничего не помогло. Провайдер - Интекском. Ютуб работает нормально даже без дополнительных манипуляций.
Куда копать и что можно попробовать поправить?
Спасибо за ответы.

**Comment by serpen7** [comment]
Какой архив вы скачивали?

**Comment by wondergrauf** [comment]
1.6.1 (последний с релизной страницы) - https://github.com/Flowseal/zapret-discord-youtube/releases/tag/1.6.1

**Comment by serpen7** [comment]
Нет я имею ввиду именно какой архив вы скачивали?

**Comment by wondergrauf** [comment]
.zip. Есть разница? Содержимое совпадает полностью с репозиторием.

**Comment by serpen7** [comment]
> .zip. Есть разница? Содержимое совпадает полностью с репозиторием.

прочтите эту ветку, долго будет объяснять все по новой https://github.com/Flowseal/zapret-discord-youtube/issues/1102

**Comment by wondergrauf** [comment]
Принято. Сейчас попробую .rar. Отпишусь. Спасибо!

**Comment by wondergrauf** [comment]
> прочтите эту ветку, долго будет объяснять все по новой #1102

Попробовал .rar архив (разархивировал виндовым архиватором, потом - 7zip), в обоих случаях перебрал все батники, результат тот же - сервис запускается, но Дискорд также не может обновиться.

<img width="662" alt="image" src="https://github.com/user-attachments/assets/10665722-c5d4-488a-a7bb-4bfd87dde56f" />

**Comment by serpen7** [comment]
Попробуйте добавить 162.159.129.233 в лист ип сет дискорд

**Comment by wondergrauf** [comment]
> Попробуйте добавить 162.159.129.233 в лист ип сет дискорд

Добавил, перебрал еще раз все батники - ничего не изменилось, к сожалению.

**Comment by KarasDeputy** [comment]
> > попробуйте добавить 162.159.129.233 в лист ip set дискорд
> 
> Добавил, перебрал еще раз все батники - ничего не изменилось, к сожалению.

у вас заработал?

**Comment by wondergrauf** [comment]
> у вас заработал?

Не-а. Всё также - висит на "Checking for updates" бесконечно с любым батником.

**Comment by KarasDeputy** [comment]
> > у вас получилось?
> 
> Не-а. Всё также - посетите «Проверка обновлений» бесконечно с любым батником.

и что делать у меня тоже такое уже час не могу запустить дс а у меня катка через час 20

**Comment by KarasDeputy** [comment]
> > у вас получилось?
> 
> Не-а. Всё также - посетите «Проверку обновлений» бесконечно с любым батником.

только что заработал я не знаю как это всё работает но только что дс заработал и тебе спасибо за то что помощи тут просил и тем самым помог мне

**Comment by KarasDeputy** [comment]
> попробуйте добавить 162.159.129.233 в лист ip set дискорд

и тебе спасибо за помощь

**Comment by wondergrauf** [comment]
А у меня все еще не пашет. Падает на апдейте со всеми батниками.

**Comment by Flowseal** [comment]
> А у меня все еще не пашет. Падает на апдейте со всеми батниками.

README + #252

**Comment by ZotovPIE11** [comment]
> Собственно, сабж. Перепробовал все батники (discord и general со всеми alt-конфигами) - никакой из них не помогает. Дискорд при запуске зависает на "Checking for updates" на каждом из них. Пробовал посмотреть альтернативные конфиги в ветке обсуждения Дискорда - тоже ничего не помогло. Провайдер - Интекском. Ютуб работает нормально даже без дополнительных манипуляций. Куда копать и что можно попробовать поправить? Спасибо за ответы.

Пробуй через ВПН, у меня все заработало - обновился, потом через батник нет проблем запустить. Я запускал через ZoogVPN используя сервер США - Вашингтон (Чтобы скачать этот впн, надо еще допом ВПН на браузер поставить, это если захочешь конкретно мой варик протестить, а так думаю с любым ВПН прокатит)

**Comment by KarasDeputy** [comment]
> > Собственно, сабж. Перепробовал все батники (discord и general со всеми alt-конфигами) - никакой из них не помогает. Дискорд при запуске зависает на "Checking for updates" на каждом из них. Пробовал посмотреть альтернативные конфиги в ветке обсуждения Дискорда - тоже ничего не помогло. Провайдер - Интекском. Ютуб работает нормально даже без дополнительных манипуляций. Куда копать и что можно попробовать поправить? Спасибо за ответы.
> 
> Пробуй через ВПН, у меня все заработало - обновился, потом через батник нет проблем запустить. Я запускал через ZoogVPN используя сервер США - Вашингтон (Чтобы скачать этот впн, надо еще допом ВПН на браузер поставить, это если захочешь конкретно мой варик протестить, а так думаю с любым ВПН прокатит)

через впн в дс сидеть ? предлагаешь

**Comment by deniuz** [comment]
попробуйте добавить 34.126.226.51 в лист ip set дискорд

**Comment by KarasDeputy** [comment]
> попробуйте добавить 34.126.226.51 в лист ip set дискорд

бля большое спасибо ОН ЗАРАБОТАЛ ВСЕГО ТЕБЕ САМОГО НАИЛУЧШЕГО ДОБРОЙ ДУШИ ТЫ ЧЕЛОВЕК

**Comment by Spokoynich735** [comment]
> попробуйте добавить 34.126.226.51 в лист ip set дискорд

Привет у меня такая же проблема но я новичок и не понимаю как и где доабавить "в лист ip set дискорд" можешь подсказать?

**Comment by k0mmun1st** [comment]
> попробуйте добавить 34.126.226.51 в лист ip set дискорд

доброго вечера, объясните максимум тупому человеку, как, в какой файл вставлять эти цифры?

**Comment by KarasDeputy** [comment]
> > попробуйте добавить 34.126.226.51 в лист ip set дискорд
> 
> доброго вечера, объясните максимум тупому человеку, как, в какой файл вставлять эти цифры?

Смотри найди файл под названием up set discord открываешь его копируешь и вставляешь туда этот айпи адрес после сохраняешь и пробуешь запускать батники по новой

**Comment by k0mmun1st** [comment]
> > > попробуйте добавить 34.126.226.51 в лист ip set дискорд
> > 
> > 
> > доброго вечера, объясните максимум тупому человеку, как, в какой файл вставлять эти цифры?
> 
> Смотри найди файл под названием up set discord открываешь его копируешь и вставляешь туда этот айпи адрес после сохраняешь и пробуешь запускать батники по новой

спасибо, помогло!

**Comment by Mamajackk** [comment]
Проблема не решена, все также cheking for updates

**Comment by EHoTiNKA** [comment]
У меня такая же проблема началась, буквально 2 часа назад все было хорошо, теперь весит в обновлении.
Стоит adguard, в настройках сети галочка с дискорда снята, в расширенных настройках айпишники тоже добавил. И 162.159.129.233 в лист ип сет дискорд тоже добавил

**Comment by dafuqoff** [comment]
> У меня такая же проблема началась, буквально 2 часа назад все было хорошо, теперь весит в обновлении. Стоит adguard, в питание сети галочка с дискорда снята, в расширенных подключениях тоже добавлены айпишники. И 162.159.129.233 в лист айпи дискорд тоже добавил

Привет, сегодня с утра тоже с такой проблемой столкнулся, в итоге мне помогло сначала запустить дискорд, а потом батник, в итоге так дискорд заработал, до этого сначала запускал батник потом дискорд, не работало :/
Попробуй такой же тупой способ, вдруг поможет

**Comment by EHoTiNKA** [comment]
> > У меня такая же проблема началась, буквально 2 часа назад все было хорошо, теперь весит в обновлении. Стоит adguard, в питание сети галочка с дискорда снята, в расширенных подключениях тоже добавлены айпишники. И 162.159.129.233 в лист айпи дискорд тоже добавил
> 
> Привет, сегодня с утра тоже с такой проблемой столкнулся, в итоге мне помогло сначала запустить дискорд, а потом батник, в итоге так дискорд заработал, до этого сначала запускал батник потом дискорд, не работало :/ Попробуй такой же тупой способ, вдруг поможет

да и вправду помогло спасибо

**Comment by h34dl0w** [comment]
а у меня ничего из этого не сработало :(, что делать? даже переустановил дискорд, но не помогло

**Comment by Mamajackk** [comment]
починил = уберите UPDATE (discord) с автозагрузки компа в диспетчере задач

**Comment by Mamajackk** [comment]
до этого удалите все папки дискорда и переустановите сразу отключив update

**Comment by hssfleck** [comment]
Есть варианты это решить еще? Сначала заработал, через день опять потух с любым батником. Я там уже танец урожая станцевал, да бубном себе по голове побил, он то checking for update пишет, то стартинг, то серый экран вылетает пустой дискордовский, все нервы схавал уже

**Comment by sqarqa** [comment]
Я решил проблему с бесконечным апдейтом дискорда заходите на офф сайт дискорда справа сверху будет открыть дискорд авторизируйтесь и возле каналов слева будет загрузить приложение нажимаете и снизу будет надпись скачайте тестовую сборку вас перекинет на другую страницу листаете в самый низ и там будет установить тестовую сборку. Еще когда я первый раз скачал у меня запускался фэйсит и был постоянный апдейт дискорда я попробовал удалить фэйсит у и меня заработало. Пробуйте

**Comment by m60e4** [comment]
Всё вышеперечисленное не помогло, знает кто ещё способы дискорд пофиксить?

**Comment by Anakinskywalkerj** [comment]
Да где этот файл up list discord находится? Не могу найти

**Comment by FeyKin** [comment]
Сегодня во рвемя игры дискорд работал нормально, но потом крашнулся и завис на апдейте, чё делать?

**Comment by LOLVASKA** [comment]
https://github.com/therealsdy/DiscordFix/releases
Через блокчек сделал свой батник, запустился дс, но войс не работал офнул свой запустил DiscordFix все получилось

**Comment by LOLVASKA** [comment]
UPD 
Запускал и свой батник и фикс из папки

**Comment by miring1** [comment]
> > добавить форму 34.126.226.51 в лист ip set дискорд
> 
> бля большое спасибо ОН ЗАРАБОТАЛ ВСЕГО ТЕБЕ САМОГО НАИЛУЧШЕГО ДОБРОЙ ДУШИ ТЫ ЧЕЛОВЕК

ааа где найти то ip set я весь компьютер перебрал его нет

**Comment by korova2005** [comment]
Мне помогла переустановка дискорда с открытым батником.

**Comment by trybonk** [comment]
Помогла чистка DNS кэша `ipconfig /flushdns` и включить Cloudflare WARP

**Comment by Shararamosh** [comment]
У Дискорда с одной из последних версий появился очень идиотский баг - он подключается к серверу обновлений только один раз - в момент запуска, а всё остальное время просто ничего не делает. WARP необходимо включать только перед запуском Дискорда, иначе ничего не изменится.
