### ISSUE TITLE
Не устанавливается сервис

### ISSUE THREAD

**Issue by Silendy** [Flowseal/zapret-discord-youtube#1106]
Не устанавливается служба, служб старых версий не стоит. Пробовал разные запуски и релоады. Есть вариант самому службу вручную прокинуть?

**Comment by Flowseal** [comment]
А ошибку то покажете?

**Comment by Silendy** [comment]
> Ошибка то покажете?

Ошибки нет, как обычно процесс проходит, но в сервис запрет не появляется. Прошлая версия нормально в службах сидела. После ее удаления новую поставить не удалось.

**Comment by Silendy** [comment]
@Flowseal 
Раньше не обращал внимания, при запуске service_install окно запускается на мгновение и закрывается, надеюсь это поможет в решении проблемы.

**Comment by Silendy** [comment]
Решил проблему удалив из батника следующие строки, после чего идет вывод в консоли выбора батника с обходом:

set "arg=%1"
if "%arg%" == "admin" (
    echo Restarted with admin rights
) else (
    powershell -Command "Start-Process 'cmd.exe' -ArgumentList '/k \"%~f0 admin\"' -Verb RunAs"
    exit /b
)

cd /d "%~dp0"
call check_updates.bat soft
