### ISSUE TITLE
что делать

### ISSUE THREAD

**Issue by ivan52605** [Flowseal/zapret-discord-youtube#1118]
проблема с ютубом а конкретно видео загружается примерно минут на 5 а далее нет и приходится после открытия каждого  видео перематывать в середину чтобы всё сразу прогрузилось

**Comment by serpen7** [comment]
пробуйте другие батники. Тут еще и ютуб в последнее время по миру сбоит разной фигней на некоторых серверах, так что тут вам врядли скажут в чем проблема кроме как попробовать на других батниках посидеть.

**Comment by Nelasar** [comment]
У меня случилась та же фигня, никакие версии запрета не работали. Это произошло сращзу после обновы винды
Откат к предыдущей версии вернул доступ к ютубу на том же батнике, что и работал до обновления!

**Comment by ivan52605** [comment]
понял спасибо на этом
