### ISSUE TITLE
чел ты

### ISSUE THREAD

**Issue by staticremenant** [Flowseal/zapret-discord-youtube#112]
![image](https://github.com/user-attachments/assets/6f886952-8515-4e55-b40c-7cd9dde295ca)

что это?)

**Comment by exzolink** [comment]
Возьми драйвер с goodbyedpi (или вовсе с офиц. репозитория) если переживаешь, хотя тут и так с оригинального запрета

**Comment by fs0x1337** [comment]
> что это?)

драйвер захвата и манипуляции пакетов, благодаря которым и пашут обходы

**Comment by Flowseal** [comment]
> ![image](https://private-user-images.githubusercontent.com/58642663/375168120-6f886952-8515-4e55-b40c-7cd9dde295ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDYyMjksIm5iZiI6MTcyODU0NTkyOSwicGF0aCI6Ii81ODY0MjY2My8zNzUxNjgxMjAtNmY4ODY5NTItODUxNS00ZTU1LWI0MGMtN2NkOWRkZTI5NWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3Mzg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNTZiYzY4MmEyNzhhMWQxN2U3YWE0M2M4YjU1YWNhYzdjNTYwMWI1Yzg5YTA3ZjI2NzA5YzA2ODllYWRlMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QTPkAaokp7e2oDmHQKG2fXK4N5si9-feaQ-DCEP0EaY)
> 
> что это?)

Если вы хотите удалить, то в Readme есть инструкция. А так, это драйвер, благодаря которому и работают goodbyedpi и zapret. В описании драйвера автор оставил ссылку на донат.
