### ISSUE TITLE
Ютуб не работает в инкогнито

### ISSUE THREAD

**Issue by Lozaruss** [Flowseal/zapret-discord-youtube#1120]
На 10 винде все норм работало, недавно установил 11 и перестало работать в инкогнито
P.S. Не знаю что насчет других сайтов, но ютуб точно
P.S.S. Я не утверждаю, что это связано с виндой

**Comment by serpen7** [comment]
Это может быть связанно с каким то последнием обновлением винды Windows 11, version 24H2 декабрьских обнов там много кто жалуется на разного рода вещи включая и интернетные. Хотя это может быть и сам ютуб, люди даже не из РФ жалуются на том же реддите что видео становится на 0.49 на 0.59, на 2.59 и т.п. временных метках. Возможно пытаясь прогрузить рекламу которую не заблочил по скриптам адблок и останавливает просмотр видео потому что ютуб борется с адблоком довольно сильно.

**Comment by Nelasar** [comment]
serpen7 скорее всего прав, у меня zapret Перестал работать после обновления Windows и начал снова работать после отката обновления

**Comment by lozardev** [comment]
Починилось само)
