### ISSUE TITLE
Не работает при LAN-соединении

### ISSUE THREAD

**Issue by kuzmi4q** [Flowseal/zapret-discord-youtube#1129]
Проблема вот в чем: если я подключаюсь к любой WiFi сети, все работает как надо. Но если подключаться по шнуру, то обход не работает. Я бы пользовался через вайфай, но беда в том что он довольно плохо ловится и не работает в остальных аспектах. В чем может быть проблема?

**Comment by Eptiy** [comment]
В роутере ускорение сети выключи. Называться может по-разному, нужно найти что-то похожее.

**Comment by kuzmi4q** [comment]
> В роутере ускорение сети выключи. Называться может по-разному, нужно найти что-то похожее.

у нас роутер относительно старый, так что сомневаюсь что там есть такое. да и потом, это разве должно так работать что оно блочит доступ только при lan подключении но не через вайфай?

**Comment by kuzmi4q** [comment]
также я попробовал подключить шнур напрямую к компьютеру без роутера, результат был тот же

**Comment by serpen7** [comment]
> также я попробовал подключить шнур напрямую к компьютеру без роутера, результат был тот же

либо чето мешает, либо чето блокирует. Вопрос еще, какая у вас ОС? Желательно так же номер сборки. Вроде такого 
![image](https://github.com/user-attachments/assets/3b736b7b-da07-4bbc-a059-0f56e1f10573)
Потому что на винде 11 с 24h2 декабрьскими обновлениями люди много кто жалуется что там много чего поломалось, включая и какие то проблемы с интернетом, запретом, впнами, просто от обновления винды.

**Comment by kuzmi4q** [comment]
> > также я попробовал подключить шнур напрямую к компьютеру без роутера, результат был тот же
> 
> либо чето мешает, либо чето блокирует. Вопрос еще, какая у вас ОС? Желательно так же номер сборки. Вроде такого ![image](https://private-user-images.githubusercontent.com/134365619/399152924-3b736b7b-da07-4bbc-a059-0f56e1f10573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0Njg2MzksIm5iZiI6MTczNTQ2ODMzOSwicGF0aCI6Ii8xMzQzNjU2MTkvMzk5MTUyOTI0LTNiNzM2YjdiLWRhMDctNGJiYy1hMDU5LTBmNTZlMWYxMDU3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOVQxMDMyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTE5OGJlOGMxNmM3ZDdmYTBkZjM4NmEzMTA4OThiZWQxN2I0ZjAwMDg2ZGM5ZDNlMDFkNmFiZThlMTFlMWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OuEopbkg4pBr8bvzz445UDsunnMx-R4-g21G3jT_69w)

![image](https://github.com/user-attachments/assets/18c3b4cb-6aa1-4b66-abfb-28ddd1817578)

**Comment by kuzmi4q** [comment]
Получается что такая же

**Comment by serpen7** [comment]
приложения какие то стоят которые могут блокировать рекламу в других приложениях и вмешиваться в трафик на уровне ОС? Вроде Адгарда? И какой антивирус у вас?

**Comment by kuzmi4q** [comment]
> приложения какие то стоят которые могут блокировать рекламу в других приложениях на уровне ОС?

да вроде нет, блокировщик рекламы стоит только в браузере, из глобального стоит только античит валоранта. антивирус не стоит

**Comment by serpen7** [comment]
хм... есть предположение что античит валоранта может быть виноват, но я не особо знаю как вам это проверить т.к. не пользуюсь играми с этой "истеричкой", но наслышан про его "странное" поведение.

**Comment by kuzmi4q** [comment]
> хм... есть предположение что античит валоранта может быть виноват, но я не особо знаю как вам это проверить т.к. не пользуюсь играми с этой "истеричкой", но наслышан про его "странное" поведение.

я уже нашел решение проблемы. я нашел приложение драйвера и отключил в нем оптимизацию, и все заработало

**Comment by serpen7** [comment]
> > хм... есть предположение что античит валоранта может быть виноват, но я не особо знаю как вам это проверить т.к. не пользуюсь играми с этой "истеричкой", но наслышан про его "странное" поведение.
> 
> я уже нашел решение проблемы. я нашел приложение драйвера и отключил в нем оптимизацию, и все заработало

а не поделитесь желательно конкретикой, хотя бы краткой, может у кого такая же проблема будет и ему тоже поможет.

**Comment by kuzmi4q** [comment]
у моего драйвера есть программа killer intelligence center (адаптер killer e2600 gigabait Ethernet controller), и в его настройках я отключил все галочки, после чего попробовал запустить запрет и дискорд и все заработало. особо рассказать тут больше нечего

**Comment by serpen7** [comment]
> у моего драйвера есть программа killer intelligence center (адаптер killer e2600 gigabait Ethernet controller), и в его настройках я отключил все галочки, после чего попробовал запустить запрет и дискорд и все заработало. особо рассказать тут больше нечего

а, это да, это известная уже интересная фича работы киллер ннетворк адаптеров, там просто все галочки в центре по оптимизации сети снимаешь и все вдруг работает. Уже было парочку человек с такой же проблемой на ноутах, притом что комп у них работал в той же сети нормально.

**Comment by LifeWind1** [comment]
> у моего драйвера есть программа killer intelligence center (адаптер killer e2600 gigabait Ethernet controller), и в его настройках я отключил все галочки, после чего попробовал запустить запрет и дискорд и все заработало. особо рассказать тут больше нечего

спасибо, помогло, перестало работать после обновления на 24H2, отключил две галки и снова всё заработало
![image](https://github.com/user-attachments/assets/eb646008-6ff1-4480-9d11-b696d5553e89)

**Comment by wuwuwwq** [comment]
> > у моего драйвера есть программа killer intelligence center (адаптер killer e2600 gigabait Ethernet controller), и в его настройках я отключил все галочки, после чего попробовал запустить запрет и дискорд и все заработало. особо рассказать тут больше нечего
> 
> спасибо, помогло, перестало работать после обновления на 24H2, отключил две галки и снова всё заработало ![image](https://private-user-images.githubusercontent.com/20902023/399160221-eb646008-6ff1-4480-9d11-b696d5553e89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwODc5OTMsIm5iZiI6MTczNjA4NzY5MywicGF0aCI6Ii8yMDkwMjAyMy8zOTkxNjAyMjEtZWI2NDYwMDgtNmZmMS00NDgwLTlkMTEtYjY5NmQ1NTUzZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDE0MzQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NzFjYzY3ZjUxNGZhYjdiZWRjN2UzZTMzMGQ1MDFmODE0ZTlkZDVmNWFhZjhiMjI3MjMxODNhYWVlMzhiODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5FhTYVxylnkcEv3x-UlsKNdUYmJYgyTIcmxfa3y5Pdk)

мне тоже эта штука помогла, но вопрос возник. эту штуку при каждом включении ноута офать? прост ща включил ноут эта штука сама включилась, мб как то можно чтоб она всегда офнута была?

**Comment by ISKYworkerI** [comment]
Такая же проблема, но этого ПО у меня нет уже давно и установить его заново уже нет возможности, весь интернет обыскал. Как еще можно решить эту проблему? Пробовал менять параметры в свойствах адаптера, но результата это не дало

**Comment by ISKYworkerI** [comment]
> Такая же проблема, но этого ПО у меня нет уже давно и установить его заново уже нет возможности, весь интернет обыскал. Как еще можно решить эту проблему? Пробовал менять параметры в свойствах адаптера, но результата это не дало

Решение нашлось совершенно случайно. В службах системы необходимо остановить службу Killer Network Service

**Comment by inky888** [comment]
> > Такая же проблема, но у меня уже давно нет этого ПО, и установить его заново нет возможности, я весь интернет перерыл. Как еще можно решить эту проблему? Пробовал менять параметры в свойствах адаптера, но это не помогло
> 
> Решение нашлось совершенно случайно. В службах системы необходимо остановить службу Killer Network Servi

Расскажите пожалуйста подробнее, как справились с проблемой, сам мучаюсь уже давно

**Comment by inky888** [comment]
> > > Такая же проблема, но у меня уже давно нет этого ПО, и установить его заново нет возможности, я весь интернет перерыл. Как еще можно решить эту проблему? Пробовал менять параметры в свойствах адаптера, но это не помогло
> > 
> > 
> > Решение нашлось совершенно случайно. В службах системы необходимо остановить службу Killer Network Servi
> 
> Расскажите пожалуйста подробнее, как справились с проблемой, сам мучаюсь уже давно



> > Такая же проблема, но этого ПО у меня нет уже давно и установить его заново уже нет возможности, весь интернет обыскал. Как еще можно решить эту проблему? Пробовал менять параметры в свойствах адаптера, но результата это не дало
> 
> Решение нашлось совершенно случайно. В службах системы необходимо остановить службу Killer Network Service

Кажется, получилось, большое спасибо за совет!

**Comment by m1cantia** [comment]
> > Такая же проблема, но этого ПО у меня нет уже давно и установить его заново уже нет возможности, весь интернет обыскал. Как еще можно решить эту проблему? Пробовал менять параметры в свойствах адаптера, но результата это не дало
> 
> Решение нашлось совершенно случайно. В службах системы необходимо остановить службу Killer Network Service

помогло, спасибо легенда
