### ISSUE TITLE
Проблема с МГТС и небольшой прикол

### ISSUE THREAD

**Issue by MarshlowWw** [Flowseal/zapret-discord-youtube#113]
Знаю что уже есть тема насчет МТС но у меня получилось всё веселее. Буду разделять МГТС как домашний (по проводу) и МТС как мобильный (по wifi с телефона).
Просто с DPI и МГТС меня не подключает к войсу и не грузит картинки. Если подключу МТС меня все же закинет в войс но с задержкой (точнее только после второй попытки подключения самим ДС). Если подключу VPN иной страны на IKEv2 и отключу DPI то все же меня подключит но и то с той же задержкой но картинки я все равно не смогу загружать. Прокатывал трюк с отключением DPI, подключением с VPN, включением DPI и отключением VPN но на DPI v1.1.1 трюк перестал прокатывать. Если подключу одновременно МГТС и МТС не отключая DPI то меня запустит в войс с той же задержкой и также без картинок.
Но вот прикол - если я у того же VPN провайдера беру Россию и PPTP то меня пускает в войс без задержки и дает загружать картинки независимо от текущего моего интернета и состояния DPI

**Comment by conqu1stador** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92

**Comment by MarshlowWw** [comment]
> #92

о, и вправду после замены split2 на updlen все завелось. Сяб)
