### ISSUE TITLE
Не запускается установка

### ISSUE THREAD

**Issue by MrEblanische** [Flowseal/zapret-discord-youtube#1132]
При запуске появляется ошибка "Ошибка в *...\bin\winws.exe* Нет точки входа: --wf-tcp=80,443"

**Comment by serpen7** [comment]
вы ZIP архив скачивали вместо RAR?

**Comment by MrEblanische** [comment]
> вы ZIP архив скачивали вместо RAR?

Нет.
upd. Пробовал и с ZIP, и с RAR. Такая же ошибка

**Comment by serpen7** [comment]
> > вы ZIP архив скачивали вместо RAR?
> 
> Нет. upd. Пробовал и с ZIP, и с RAR. Такая же ошибка

а путь к папке запрета какой и как она называется?

**Comment by MrEblanische** [comment]
> > > вы ZIP архив скачивали вместо RAR?
> > 
> > 
> > Нет. upd. Пробовал и с ZIP, и с RAR. Такая же ошибка
> 
> а путь к папке запрета какой и как она называется?

"C:\Users\*user*\Desktop\xyuhr", имя юзера латиницей

**Comment by MrEblanische** [comment]
Сейчас поперемещал папку с батниками с системного диска на другие, все также не работает.

**Comment by serpen7** [comment]
может просто файл заблокирован, проверьте свой антивирус, он там не химичил ничего?

**Comment by MrEblanische** [comment]
> может просто файл заблокирован, проверьте свой антивирус, он там не химичил ничего?

Вроде нет, есть только упоминание архива с запретом болвана, которое я разрешил(архив с самим запретом удален
![изображение_2024-12-30_183549031](https://github.com/user-attachments/assets/da1a5167-fba4-4f99-9e0b-49061d5f3372)
)

**Comment by MrEblanische** [comment]
> может просто файл заблокирован, проверьте свой антивирус, он там не химичил ничего?

Была запись в журнале защиты про sabsik.fl.a!ml, которую я разрешил, все равно не хочет устанавливаться. Другие записи не связаны с обходом

**Comment by serpen7** [comment]
> > может просто файл заблокирован, проверьте свой антивирус, он там не химичил ничего?
> 
> Была запись в журнале защиты про sabsik.fl.a!ml, которую я разрешил, все равно не хочет устанавливаться. Другие записи не связаны с обходом

Эм, вы отсюда точно скачивали запрет? Можете сделать скриншот файлов в папке запрета и скриншот файлов в папке BIN?

**Comment by MrEblanische** [comment]
![image](https://github.com/user-attachments/assets/db5139fb-222d-44f2-a09e-1afb22fef636)
![image](https://github.com/user-attachments/assets/d4ee938e-54c2-4f7c-bc4a-82f5c72aabc5)

**Comment by serpen7** [comment]
А винда какая?

**Comment by MrEblanische** [comment]
> А винда какая?

10 pro 22h2

**Comment by serpen7** [comment]
А можете сделать скриншот ошибки и посмотреть заодно журнал системы, просмотр событий, журнал приложений? Может там что будет показано по winws. Или в системном журнале.
![image](https://github.com/user-attachments/assets/f06c7f25-d3b2-4e8d-98e1-cf20f7ccc408)

**Comment by MrEblanische** [comment]
> А можете сделать скриншот ошибки и посмотреть заодно журнал системы, просмотр событий, журнал приложений? Может там что будет показано по winws. Или в системном журнале. ![image](https://private-user-images.githubusercontent.com/134365619/399303645-f06c7f25-d3b2-4e8d-98e1-cf20f7ccc408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjY4ODQsIm5iZiI6MTczNTU2NjU4NCwicGF0aCI6Ii8xMzQzNjU2MTkvMzk5MzAzNjQ1LWYwNmM3ZjI1LWQzYjItNGU4ZC05OGUxLWNmMjBmN2NjYzQwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQxMzQ5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2QwOGRiZjMwZjRkNjJkNDEzODIyN2U3ZTE3OWMyMjkyY2RkOGQ4OGE0N2M2MTZmZWI1NWMwNzJkODViMDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q-fvyHvxoN0-BVpUlXMZsJIsSYJ0bTVQ5LMBv9gbmYQ)

![image](https://github.com/user-attachments/assets/e9182e21-250b-49cf-9c8e-96d06e177d34)
![image](https://github.com/user-attachments/assets/563cc40d-2a35-4929-acbe-9915bc772838)
![image](https://github.com/user-attachments/assets/214e98ba-3490-4d78-a077-5e0713d8d3fa)
![image](https://github.com/user-attachments/assets/6a8de0bd-4cec-49a2-98c2-0f03e2fe6fb5)
В системе установлена служба.

Имя службы:  zapret DPI bypass : zapret
Имя файла службы:  "C:\Users\dimad\Desktop\xyuhr\bin\winws.exe" --wf-tcp=443 --wf-udp=443,50000-50100 --filter-udp=443 --hostlist="C:\Users\dimad\Desktop\xyuhr\list-discord.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic="C:\Users\dimad\Desktop\xyuhr\bin\quic_initial_www_google_com.bin" --new --filter-udp=50000-50100 --ipset="C:\Users\dimad\Desktop\xyuhr\ipset-discord.txt" --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --new --filter-tcp=443 --hostlist="C:\Users\dimad\Desktop\xyuhr\list-discord.txt" --dpi-desync=fake,split --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="C:\Users\dimad\Desktop\xyuhr\bin\tls_clienthello_www_google_com.bin"
Тип службы:  служба режима пользователя
Тип запуска службы:  Автоматически
Учетная запись службы:  LocalSystem
Служба "zapret DPI bypass : zapret" является зависимой от следующей службы: "GoodbyeDPI". Возможно, эта служба не установлена.
Превышение времени ожидания (30000 мс) при ожидании подключения службы "zapret".
Сбой при запуске службы "zapret" из-за ошибки 
Служба не ответила на запрос своевременно.

**Comment by serpen7** [comment]
ну теперь мне все понятно стало
![image](https://github.com/user-attachments/assets/1f7d6017-0a7e-46e7-9c3a-7bc9b42d03e7)
Вы откуда качали до этого сборку с файлом winws1?
![image](https://github.com/user-attachments/assets/415b828a-1513-408e-8846-9545f8b8f7b1)
И отрубали ли вы антивирус чтобы ее запустить? Если да, то поздравляю вас, вам надо теперь сканировать компьютер на вирусы и вычищать. Эти фейковые вирусные сборки уже довольно давно известны из-за скаммеров с ютуба которые их распространяют как раз таки с таким левым файлом. 
Ни в этом репозитории, ни в оригинальном от bol-van таких файлов нет как видите.

**Comment by serpen7** [comment]
И кстати может поможет удалить эту службу, попробуйте запустить cmd от имени администратора, если там ничего не меняли то должны помочь команды 
net stop zapret
sc delete zapret
