### ISSUE TITLE
Не работает дискорд все пробовал все файлы открывал и от имени админа прям все ,работает только ютуб.

### ISSUE THREAD

**Issue by SpryMtg** [Flowseal/zapret-discord-youtube#1133]
![image](https://github.com/user-attachments/assets/31aff198-c928-437a-b21b-394c8d2db928)

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by SpryMtg** [comment]
Ты не чем не помог мне не помогла твоя ссылка
