### ISSUE TITLE
Не запускается обход дискорда

### ISSUE THREAD

**Issue by ZotAzot** [Flowseal/zapret-discord-youtube#1137]
Сегодня у меня перестал запускаться запрет, хотя только вчера он работал. При запуске какого-либо файла, для обхода блокировки, открывается командная строка, а после, она сразу же закрывается и работать дискорд не хочет. Сначала папку с запретом я в исключения антивируса не добавил, и он там что-то удалил, в итоге я переустановил запрет и сразу в исключения его добавил, но он все равно не хочет работать

**Comment by serpen7** [comment]
У тебя стоит сервис, батники не будут открываться если запущен сервис. Будет окрываться начальная конфига и проверка обновленных версий и все будет просто закрываться. Удаляй сервис сервис ремув батником от имени администратора.
