### ISSUE TITLE
без понятия что случилось но у меня вылезла ошибка

### ISSUE THREAD

**Issue by Gergish001** [Flowseal/zapret-discord-youtube#114]
![image](https://github.com/user-attachments/assets/e7528c92-78a3-4d08-95cd-8936adf948e5)

**Comment by Gergish001** [comment]
![image](https://github.com/user-attachments/assets/10b551d4-6e94-4960-8db9-98750fa46bbd)
а так же что вылезает в cmd

**Comment by Wo1k** [comment]
Команда не может найти файл winws.exe, который находится в папке bin в архиве запрета. У меня тоже была эта ошибка сейчас в cmd, я зашел в bin и запустил winws.exe вручную

**Comment by White-Pirate** [comment]
> Команда не может найти файл winws.exe, который находится в папке bin в архиве запрета. У меня тоже была эта ошибка сейчас в cmd, я зашел в bin и запустил winws.exe вручную

Приветствую)
![image](https://github.com/user-attachments/assets/21f45da9-e462-445b-b14f-409aa254b0fb)
у меня такая же ошибка и открытие файла приводит к демонстрации текста, но через мгновение закрывается. Запуск сервисов также выдаёт предыдущую ошибку. Подскажи, пожалуйста, знаешь ли ты решение?
![image](https://github.com/user-attachments/assets/6412437c-da74-4919-93a9-2e9c221c1674)

**Comment by Flowseal** [comment]
> ![image](https://private-user-images.githubusercontent.com/170715050/375181845-e7528c92-78a3-4d08-95cd-8936adf948e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDYxMzQsIm5iZiI6MTcyODU0NTgzNCwicGF0aCI6Ii8xNzA3MTUwNTAvMzc1MTgxODQ1LWU3NTI4YzkyLTc4YTMtNGQwOC05NWNkLTg5MzZhZGY5NDhlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNzM3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmNhN2ViN2FmN2ExZGZhYmQ3NTljNGFhOWU4Zjg0ZjA1OTRjZDk2Nzc4ZTIxOWZiNzA2NDcyYTJhYzIxZjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QWN4e3H02Cd_CUTEIc3jCRdOzxyv6PmbIcQvhqG0V9A)

Попробуйте перенести всё в папку в корень диска. Папка bin должна быть в той же папке, что и bat файлы.

**Comment by Gergish001** [comment]
я всё решил, у меня чтото именно с виндой не так походу, так что я просто скачаю амнезиювг и нормально всё будет
