### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by VLOD-ZDOV** [Flowseal/zapret-discord-youtube#117]
Программа не работает если в браузере меняли quic и kyper на disable.

**Comment by TROYANCIK** [comment]
> Программа не работает если в браузере меняли quic и kyper на disable.

Друг, ты просто гений, нет слов чтобы описать мою благодарность тебе, я всю ночь занимался любовью с различными параметрами и значениями и ни на одном из браузеров которыми я пользуюсь (Opera и Chrome) видео на Ютубе не грузилось, тогда я скачал Chrome и на нём всё работало прекрасно, я сидел и ломал голову почему, увидел созданную тобой тему и всё встало на свои места! Я просто выставил значения "Kyber и QUIC" (://flags)  в дефолтное положение и ютуб заработал! Ура товарищи!!!

**Comment by Flowseal** [comment]
Спасибо за информацию. Но лучше писать об этом здесь https://github.com/Flowseal/zapret-discord-youtube/issues/90
