### ISSUE TITLE
Воспроизводит видео только в одном браузере

### ISSUE THREAD

**Issue by ShinkarenkoMaksim** [Flowseal/zapret-discord-youtube#118]
Попробовал данную утилиту, версии 1.0.0 - ютуб/дискорд отлично заработали,  в хроме и яндексе
Спустя время увидел обновление 1.1.1, скачал новый релиз, и решил установить как службу. В это время гугл хром был запущен
В итоге, ютуб перестал воспроизводить видео в браузере google chrome/opera/firefox, но открывается быстро. Дискорд работает. Видео воспроизводится только в браузере Яндекс
Танцы с бубном вокруг различных версий данной утилиты, сброс настроек гугл хром, флаш днс, включение quic и kyber - ничего не исправляет ситуацию. Прошу помощи в решении проблемы 
P.S. GBDPI не установлен, и никогда не был установлен. Все расширения удалял
P.P.S. На другом устройстве Windows работает исправно на гугл хром. Устройства в одной сети

**Comment by CatHeisenberg** [comment]
Аналогичная проблема в браузере Firefox, в других браузерах работает стабильно

П.С Если запустить 2 браузера и запустить один видос, то в мозилле все начинает работать нормально

**Comment by stupiddeveloperName** [comment]
юзай 1 1 0

**Comment by ShinkarenkoMaksim** [comment]
> юзай 1 1 0

Не помогает. На всех трёх версиях работает одинаково

**Comment by Flowseal** [comment]
Попробуйте переключить QUIC и Kyber в Default. В Readme написал об этом. Также пишите об этом здесь - https://github.com/Flowseal/zapret-discord-youtube/issues/90
