### ISSUE TITLE
Проблемы  discord

### ISSUE THREAD

**Issue by genrihx2** [Flowseal/zapret-discord-youtube#123]
discord  check  update 

 
![image](https://github.com/user-attachments/assets/f424a5d8-4ec5-4050-9516-1fde76d482d7)

**Comment by sh2kcs** [comment]
Ты discord.bat запускал? Что в нём пишет?

**Comment by genrihx2** [comment]
я запускал   service_discord_youtube.bat

**Comment by genrihx2** [comment]
работает discord.bat

we have 3 user defined desync profile(s) and default low priority profile 0
Loading hostlist C:\test\list-discord.txt
loading plain text list
Loaded 25 hosts from C:\test\list-discord.txt
Loading hostlist C:\test\list-discord.txt
loading plain text list
Loaded 25 hosts from C:\test\list-discord.txt
windivert initialized. capture is started.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
