### ISSUE TITLE
Вирус

### ISSUE THREAD

**Issue by Igorric82** [Flowseal/zapret-discord-youtube#125]
Приветствую! Я не знаю может я такой везучий. Но у меня не то, что дс не заработал и ютуб, но у меня почему-то начали закрываться все приложение, потом вообще появился синий экран. Сразу скажу, у меня нету гудбайдпи и других на подобье. Пришлось полностью переустанавливать винду.

**Comment by Flowseal** [comment]
Такое поведение никак не связано с программой отсюда.

**Comment by Igorric82** [comment]
Просто тогда как, после этой проги, у меня всё это пошло?

**Comment by Igorric82** [comment]
Всё было нормально, потом скачал вот это и резко пошли такие случаи.
