### ISSUE TITLE
Не запускается после переустановки

### ISSUE THREAD

**Issue by VictorZapretov** [Flowseal/zapret-discord-youtube#126]
![изображение_2024-10-10_160758531](https://github.com/user-attachments/assets/55a02709-e692-4711-a3c2-dbd02c6c5b7c)

Выдаёт вот такую ошибку. Запуск драйвера вручную не помогает. До этого удалял прошлую версию, в том числе виндивёрт.

**Comment by Flowseal** [comment]
Вы запускаете service_goodbye_discord, который работает только вместе с сервисом от самого GoodbyeDPI - https://github.com/ValdikSS/GoodbyeDPI. service_goodbye_discord должен запускаться только после запущенного сервиса goodbyedpi (делается 1 раз, дальше со стартом Windows всё будет автоматически)
