### ISSUE TITLE
запускается батник а сама прога просто не открывается

### ISSUE THREAD

**Issue by kolbo-sa** [Flowseal/zapret-discord-youtube#127]
Пытался посмотреть через:
@echo %BIN% - путь указывает
--debug - лога нет
Решил попробовать от других, качал ласт релиз и менял бин с репозитория, ничего не помогает
Пытался запустить оригинальный zapret, выдавало ошибку что нет cygwil1.dll, на форумах сказали что проблема с виндой

**Comment by Gerbariy1** [comment]
Проверь панель задач, там новое окно появляется

**Comment by Flowseal** [comment]
Выполните эти инструкции:
### Остановка и удаление обхода
Для удаления оставшегося драйвера WinDivert, откройте cmd от имени администратора и пропишите следующее:
```
sc stop WinDivert
sc delete WinDivert
```
> [!NOTE]  
> Возможно, драйвер у вас будет записан по-другому. Для уточнения названия пропишите `driverquery | find "Divert"` в cmd.
