### ISSUE TITLE
Службы отказываются одновременно работать с GoodByeDPI

### ISSUE THREAD

**Issue by Karagami** [Flowseal/zapret-discord-youtube#13]
Вы можете пользоваться привычным обходом ютуба (например, goodbyedpi) вместо с обходом только дискорда из этого репозитория. Обход ютуба зависит от провайдера к провайдеру и может требовать изменения аургментов.

_Originally posted by @Flowseal in https://github.com/Flowseal/zapret-discord-youtube/issues/8#issuecomment-2401622647_

При запуске ПК только служба Гудбай работает из автозапуска. Если самому запустить сначала Запрет, а потом Гудбай, то Гудбай останавливается сам. Служба Гудбай только для ютуба, а Запрет только для дискорда. Как их заставить работать одновременно?

**Comment by lynxbites** [comment]
Попробуй поменять аргумент --dpi-desync-udplen-pattern на любой другой hex паттерн, например 0x1234ABCD

**Comment by Karagami** [comment]
> Попробуй поменять аргумент --dpi-desync-udplen-pattern на любой другой hex паттерн, например 0x1234ABCD

Теперь ни одна из служб не запускается при запуске ПК

EDIT: Наврал, каждый раз по разному видимо. Сейчас Гудбай висит, но Запрета нет

UPD: Запустил Запрет вручную, вроде обе заработали - и ютуб грузит, и голосовой канал в дискорде. Но все таки хотелось бы без этих танцев с бубном при каждом запуске ПК, иначе мне и службы бы не нужны были.

**Comment by Flowseal** [comment]
> > Попробуй поменять аргумент --dpi-desync-udplen-pattern на любой другой hex паттерн, например 0x1234ABCD
> 
> Теперь ни одна из служб не запускается при запуске ПК
> 
> EDIT: Наврал, каждый раз по разному видимо. Сейчас Гудбай висит, но Запрета нет
> 
> UPD: Запустил Запрет вручную, вроде обе заработали - и ютуб грузит, и голосовой канал в дискорде. Но все таки хотелось бы без этих танцев с бубном при каждом запуске ПК, иначе мне и службы бы не нужны были.

Как вариант, можно добавить гудбай в зависимости к службе zapret. Сегодня обновлю репозиторий.

**Comment by CyberPashtet** [comment]
После запуска service_goodbye_discord.bat всё работает до первой ПЕРЕЗАГРУЗКИ пк. После загрузки винды оба сервиса висят и работают, но ютуб пишет "нет подключения к интернету", впрочем это с любым сайтом, который должен анлочить гудбай. Если запрет отключить, то гудбай оживает, если снова включить запрет, то гудбай продолжает анлочить, НО опять же до первой перезагрузки пк. Так было и с вчерашней версией 1.0.0 service_discord.bat, то есть у меня ничего не поменялось.

Гудбай для ютуба, запрет для диса.

**Comment by Karagami** [comment]
Вроде бы новый батник помог, пару-тройку раз релогнулся и службы работают обе как надо.

> После запуска service_goodbye_discord.bat всё работает до первой ПЕРЕЗАГРУЗКИ пк. После загрузки винды оба сервиса висят и работают, но ютуб пишет "нет подключения к интернету", впрочем это с любым сайтом, который должен анлочить гудбай. Если запрет отключить, то гудбай оживает, если снова включить запрет, то гудбай продолжает анлочить, НО опять же до первой перезагрузки пк. Так было и с вчерашней версией 1.0.0 service_discord.bat, то есть у меня ничего не поменялось.
> 
> Гудбай для ютуба, запрет для диса.

Не уверен насчет "нет подключения к интернету", но у меня Гудбай иногда это и до Запрета выдавал или просто вечно грузил пустую страницу ютуба, однако исправлялось это перезапуском браузера раз так 5 подряд.

Касательно основной проблемы, думаю есть смысл несколько дней хотя бы подождать-посмотреть как будет с новым батником все работать.

**Comment by lynxbites** [comment]
> > Попробуй поменять аргумент --dpi-desync-udplen-pattern на любой другой hex паттерн, например 0x1234ABCD
> 
> Теперь ни одна из служб не запускается при запуске ПК
> 
> EDIT: Наврал, каждый раз по разному видимо. Сейчас Гудбай висит, но Запрета нет
> 
> UPD: Запустил Запрет вручную, вроде обе заработали - и ютуб грузит, и голосовой канал в дискорде. Но все таки хотелось бы без этих танцев с бубном при каждом запуске ПК, иначе мне и службы бы не нужны были.

И GoodByeDPI и zapret используют одну и ту же утилиту - [windivert](https://github.com/basil00/WinDivert), для перехвата пакетов windivert запускает сервис WinDivert64.sys для перехвата пакетов, и как только сервис видит подходящий под фильтр пакет он кидает его программе, которая использует WinDivert.dll. 
Так как и GoodByeDPI и zapret получают пакеты от одного и того же сервиса, несколько одновременно запущенных сервисов могут вызывать ошибки в этих программах. 
Я бы рекомендовал просто переключиться на zapret, так как у него присутствует фильтр UDP пакетов для обхода блокировки WebRPC, в любом случае одновременно использовать две программы, которые выполняют одну и ту же функцию, идея странная.

**Comment by Karagami** [comment]
> > > Попробуй поменять аргумент --dpi-desync-udplen-pattern на любой другой hex паттерн, например 0x1234ABCD
> > 
> > 
> > Теперь ни одна из служб не запускается при запуске ПК
> > EDIT: Наврал, каждый раз по разному видимо. Сейчас Гудбай висит, но Запрета нет
> > UPD: Запустил Запрет вручную, вроде обе заработали - и ютуб грузит, и голосовой канал в дискорде. Но все таки хотелось бы без этих танцев с бубном при каждом запуске ПК, иначе мне и службы бы не нужны были.
> 
> И GoodByeDPI и zapret используют одну и ту же утилиту - [windivert](https://github.com/basil00/WinDivert), для перехвата пакетов windivert запускает сервис WinDivert64.sys для перехвата пакетов, и как только сервис видит подходящий под фильтр пакет он кидает его программе, которая использует WinDivert.dll. Так как и GoodByeDPI и zapret получают пакеты от одного и того же сервиса, несколько одновременно запущенных сервисов могут вызывать ошибки в этих программах. Я бы рекомендовал просто переключиться на zapret, так как у него присутствует фильтр UDP пакетов для обхода блокировки WebRPC, в любом случае одновременно использовать две программы, которые выполняют одну и ту же функцию, идея странная.

Я бы хотел переключиться на Запрет, но он с ютубом совершенно ничего не делает у меня, а что конкретно тыкать там нужно я не знаю. В Гудбае считай всего 2 цифры поменять и хекс код.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90

**Comment by pritvorshik** [comment]
Я решил вопрос следующим образом.
На версии  goodbyedpi-0.2.3rc3-2
Чтобы работал сразу дискорд и ютуб, добавил в конец файла russia-blacklist.txt домены

discord-attachments-uploads-prd.storage.googleapis.com
dis.gd
discord.co
discord.com
discord.design
discord.dev
discord.gg
discord.gift
discord.gifts
discord.media
discord.new
discord.store
discord.tools
discordapp.com
discordapp.net
discordmerch.com
discordpartygames.com
discord-activities.com
discordactivities.com
discordsays.com
discordstatus.com

В 
1_russia_blacklist_dnsredir
Заменил на
start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt 

И с него же 1_russia_blacklist_dnsredir запустился. Работает и Ютуб и Дискорд
