### ISSUE TITLE
Error 1060 + HELPMSG 2185

### ISSUE THREAD

**Issue by DebilYa** [Flowseal/zapret-discord-youtube#134]
Нажмите любую клавишу, чтобы продолжить создание сервиса.
Press any key to continue . . .
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 11656
        FLAGS              :
Press any key to continue . . .

Служба хотя бы по факту создается, однако в ходе отслеживания выясняется, что компьютер в системе полностью не видит данную службу. В системе она создается как "призрак", которая не имеет никаких ключей запусков и внутреннего кода. С первым запуском все было хорошо, но когда я решил перезапустить ПК, то все bat файлы на создание "Службы" резко прекратили свою работу связи с OpenService FAILED 1060 (ошибка обозначает, что установить службу полностью не удалось и создается пустышка).

**Comment by DebilYa** [comment]
Отсылки на эти ссылки не кидать:
https://github.com/Flowseal/zapret-discord-youtube/issues/92
https://github.com/Flowseal/zapret-discord-youtube/issues/90

Причина из-за "The service name is invalid.", а также последующем MSG 2185

**Comment by Flowseal** [comment]
Нет, при открытии батника вначале останавливается и удаляется старый сервис (ошибки указывают на то, что серива нет активного), затем он успешно запускается

**Comment by DebilYa** [comment]
> Нет, при открытии батника вначале останавливается и удаляется старый сервис (ошибки указывают на то, что серива нет активного), затем он успешно запускается

Я обновил пост. Можете почитать UPD. После удаления какой-то службы консоль выдал, что треубется перезагрузка компьютера так как одна служба помечена на удаление. После этого обход заработал, но только с Дискорд, а Ютуб нет. Решил исправить Ютуб и служба отказывается удаляться/устанавливаться.

**Comment by Sasha29329** [comment]
Друже, не подскажешь, как проблему решил, после перезагрузки пк, у меня служба перестаёт работать

**Comment by Shapyshka** [comment]
решили проблему?

**Comment by maximmeshkov** [comment]
так как решить?

**Comment by XZktor** [comment]
Как по итогу то это всё решить?

**Comment by FreezeEngine** [comment]
1. win + r 
2. Services.msc в появившееся поле
3. В открывшемся меню ищите и удаляйте все с названиями похожими на "zapret"

**Comment by FreezeEngine** [comment]
Еще вариант - остановить и удалить windivert как описано тут:
https://github.com/ValdikSS/GoodbyeDPI/issues/433#issuecomment-2277618307

**Comment by temp350** [comment]
> Еще вариант - остановить и удалить windivert как описано тут: [ValdikSS/GoodbyeDPI#433 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/433#issuecomment-2277618307)

всё также...

**Comment by XXXARLTANXXX** [comment]
у меня такая де проблема можете помочь или все еще не починили у меня уже так 7 месяцев
