### ISSUE TITLE
Бат "discord" запускается, бат "discord_youtube" не запускается

### ISSUE THREAD

**Issue by PRSK13** [Flowseal/zapret-discord-youtube#135]
![1](https://github.com/user-attachments/assets/1b24fc7a-439f-44f1-8b26-adebde1ce097)

**Comment by Flowseal** [comment]
По скриншоту всё нормально запускается

**Comment by PRSK13** [comment]
Разве? Открытие сервиса зафейлилось

**Comment by DebilYa** [comment]
> Разве? Открытие сервиса зафейлилось

Конечно нет. Служба полностью не удаляется и засоряет ПК из-за чего ваш батник работать не будет. Что это за служба невидимая, даже я узнать не могу.
