### ISSUE TITLE
запускаешь и сразу вылетает батник, че делать?

### ISSUE THREAD

**Issue by qeqeqe15353** [Flowseal/zapret-discord-youtube#136]
запускаешь и сразу вылетает батник, че делать?

**Comment by Gerbariy1** [comment]
Проверь панель задач, там новое окно появляется

**Comment by artacer** [comment]
У меня была подобная история. Проверь в диспетчере задач процесс winws. Если такой есть, то закрой его "снять задачу" и попробуй ещё раз

**Comment by SharkPetro** [comment]
У друга таже проблема, ничего просто не открывается, ни в диспетчере задач ни на панели задач никаких признаков жизни.

**Comment by ingref** [comment]
Проблема с текстовыми файлами. Я просто скопировал оттуда всё, создал файлы заново, и всё заработало.

**Comment by Flowseal** [comment]
Выполните эти инструкции:
### Остановка и удаление обхода
Для удаления оставшегося драйвера WinDivert, откройте cmd от имени администратора и пропишите следующее:
```
sc stop WinDivert
sc delete WinDivert
```
> [!NOTE]  
> Возможно, драйвер у вас будет записан по-другому. Для уточнения названия пропишите `driverquery | find "Divert"` в cmd.
