### ISSUE TITLE
OpenService FAILED 1060

### ISSUE THREAD

**Issue by KonstantinPatrushev1** [Flowseal/zapret-discord-youtube#137]
Создаю службу GoodbyeDPI, запускаю файл service_goodbye_discord.bat, появляется ошибка:
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 6308
        FLAGS              :
Press any key to continue . . .

То есть служба создается, но не работает. С другими батниками та же ситуация.

**Comment by PRSK13** [comment]
Такая же ситуация, попробуй открыть бат "discord", работает?
Создатель проги говорит, что все работает, когда бат "discord_youtube" просто не открывается :)

**Comment by KonstantinPatrushev1** [comment]
> Такая же ситуация, попробуй открыть бат "discord", работает? Создатель проги говорит, что все работает, когда бат "discord_youtube" просто не открывается :)

Консоль от  discord.bat открывается, но дискорд также не работает

**Comment by DebilYa** [comment]
Ошибка говорит о том, что службы сервиса удалены не все и данное имя занято. Даже если вы поиграетесь с батниками из #90 и #92 у вас абсолютно ничего не будет работать, а все из-за того, что service_remove не удаляет службу полностью (одна из основных причин).

Другая причина это проблема с безопасностью, которая препятствует в создании службы.

**Comment by KonstantinPatrushev1** [comment]
> Ошибка говорит о том, что службы сервиса удалены не все и данное имя занято. Даже если вы поиграетесь с батниками из #90 и #92 у вас абсолютно ничего не будет работать, а все из-за того, что service_remove не удаляет службу полностью (одна из основных причин).
> 
> Другая причина это проблема с безопасностью, которая препятствует в создании службы.

Как я могу полностью удалить службу? Просто в службах ее нет

**Comment by DebilYa** [comment]
> > Ошибка говорит о том, что службы сервиса удалены не все и данное имя занято. Даже если вы поиграетесь с батниками из #90 и #92 у вас абсолютно ничего не будет работать, а все из-за того, что service_remove не удаляет службу полностью (одна из основных причин).
> > Другая причина это проблема с безопасностью, которая препятствует в создании службы.
> 
> Как я могу полностью удалить службу?

Никак. Даже я не могу найти эту службу, а если удалять вручную через sc delete zapret, то она не удалится. Файл service_remove банально не дописан (у меня случайно удалось один раз удалить какую-то службу и после перезагрузки все заработало, но из-за проблем с YouTube пришлось воспользоваться service_remove и все поломалось по новой)

**Comment by txkashi** [comment]
> > > Ошибка говорит о том, что службы сервиса удалены не все и данное имя занято. Даже если вы поиграетесь с батниками из #90 и #92 у вас абсолютно ничего не будет работать, а все из-за того, что service_remove не удаляет службу полностью (одна из основных причин).
> > > Другая причина это проблема с безопасностью, которая препятствует в создании службы.
> > 
> > 
> > Как я могу полностью удалить службу?
> 
> Никак. Даже я не могу найти эту службу, а если удалять вручную через sc delete zapret, то она не удалится. Файл service_remove банально не дописан (у меня случайно удалось один раз удалить какую-то службу и после перезагрузки все заработало, но из-за проблем с YouTube пришлось воспользоваться service_remove и все поломалось по новой)

И что делать тогда? Ждать фикса?

**Comment by DebilYa** [comment]
> > > > Ошибка говорит о том, что службы сервиса удалены не все и данное имя занято. Даже если вы поиграетесь с батниками из #90 и #92 у вас абсолютно ничего не будет работать, а все из-за того, что service_remove не удаляет службу полностью (одна из основных причин).
> > > > Другая причина это проблема с безопасностью, которая препятствует в создании службы.
> > > 
> > > 
> > > Как я могу полностью удалить службу?
> > 
> > 
> > Никак. Даже я не могу найти эту службу, а если удалять вручную через sc delete zapret, то она не удалится. Файл service_remove банально не дописан (у меня случайно удалось один раз удалить какую-то службу и после перезагрузки все заработало, но из-за проблем с YouTube пришлось воспользоваться service_remove и все поломалось по новой)
> 
> И что делать тогда? Ждать фикса?

Сейчас кое-что сделал. Незнаю, возможно поможет или возможно нет.
1. создать бат файл в папке обхода service_del и прописать:
call :srvdel winws1
rem call :srvdel winws2
goto :eof

:srvdel
net stop %1
sc delete %1

2. открыть командную строку от имени администратора и написать
sc stop WinDivert
sc delete WinDivert

sc stop zapret
sc delete zapret

3. Перезагрузить ПК и от имени администратора запустить службу.

**Comment by Flowseal** [comment]
При открытии батника вначале останавливается и удаляется старый сервис (ошибки указывают на то, что сериса нет активного), затем он успешно запускается, судя по вашим логам. Если обход не работает - ищите решение в README или в https://github.com/Flowseal/zapret-discord-youtube/issues/90 и https://github.com/Flowseal/zapret-discord-youtube/issues/92

**Comment by DebilYa** [comment]
> При открытии батника вначале останавливается и удаляется старый сервис (ошибки указывают на то, что сериса нет активного), затем он успешно запускается, судя по вашим логам. Если обход не работает - ищите решение в README или в #90 и #92

Чел, у меня такой вопрос. Ты вообще читаешь, что пишут? У тебя обход фигово работает. Я сейчас все исправил, потом перезапустил и у меня снова все нихера не работает и ты думаешь, что проблема в прописи обхода? Серьезно?

**Comment by roxlab** [comment]
Что значит данная информация?
[SC] DeleteService SUCCESS
[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
[SC] StartService FAILED 1068:

The dependency service or group failed to start.

Press any key to continue . . .

**Comment by Brosik41** [comment]
Советую просто удалить новую версию и переустановить ту, которую скачивали в прошлый раз. Последний раз обновлялся я на версию 1.7.0, просто удалил ее и запустил discord.bat отдельно, заработало. Только перед этим проверьте наличие у вас работающего впн и удалите любые расширения внутри браузера, тк zapret с ними конфликтует.

**Comment by roxlab** [comment]
> Советую просто удалить новую версию и переустановить ту, которую скачивали в прошлый раз. Последний раз обновлялся я на версию 1.7.0, просто удалил ее и запустил discord.bat отдельно, заработало. Только перед этим проверьте наличие у вас работающего впн и удалите любые расширения внутри браузера, тк zapret с ними конфликтует.

Своевременно... Уже давно проблема решена новой версией
