### ISSUE TITLE
StartServvice FAILED 2:  The system cannot find the file specifed

### ISSUE THREAD

**Issue by ShantaRam81** [Flowseal/zapret-discord-youtube#138]
![image](https://github.com/user-attachments/assets/564f4b02-fa5b-42e5-81b9-663ecdaafac7)

**Comment by VasyaTerkin-2019** [comment]
The project uses the WinDivert driver without Microsoft's digital signature. I replaced WinDivert64.sys from the [GoodbyeDPI project](https://github.com/ValdikSS/GoodbyeDPI). After that, the service started running normally.

**Comment by Flowseal** [comment]
You may have forgotten to move the bin folder. The bin folder must be in the same folder as the bat files.
