### ISSUE TITLE
Не работает веб-камера

### ISSUE THREAD

**Issue by MrM0R0Z** [Flowseal/zapret-discord-youtube#139]
Установил всё через service_discord_youtube.bat
Запустил discord_youtube.bat
Перезапустил сам дискорд.
Дискорд и ютуб работает.
Во время общения, друг решил включить вебку, бесконечно грузит. Я подключил и у меня оказалась такая же проблема. Вебкамера у меня рабочая. 
Используем версию 1.1.1

**Comment by Flowseal** [comment]
![image](https://github.com/user-attachments/assets/19944b5f-cd59-45b7-8808-f41f248a3bc1)

works for me
