### ISSUE TITLE
service_discord_youtube Некоторые сайты, после включения не открываются

### ISSUE THREAD

**Issue by soymun** [Flowseal/zapret-discord-youtube#14]
После некоторого времени вижу, что некоторые сайты, не корректно открываются, один из них - leetcode

![image](https://github.com/user-attachments/assets/606d84c4-a0e8-4ef4-b541-b3d1bc6b041f)

**Comment by Flowseal** [comment]
Что используете?

**Comment by V3nilla** [comment]
> После некоторого времени вижу, что некоторые сайты, не корректно открываются, один из них - leetcode
> 
> ![image](https://private-user-images.githubusercontent.com/95306631/374894440-606d84c4-a0e8-4ef4-b541-b3d1bc6b041f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzE1ODgsIm5iZiI6MTcyODQ3MTI4OCwicGF0aCI6Ii85NTMwNjYzMS8zNzQ4OTQ0NDAtNjA2ZDg0YzQtYTBlOC00ZWY0LWI1NDEtYjNkMWJjNmIwNDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEwNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2N2ZkNzI2ZDQ0Y2M1MjFiNDM4YWZiZWZlNGJlMjIyM2I2OTZmY2IzMzgzMjU0MmQ0NjdhNTc4YTA0YTJiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QRgsQiZIkNmgJVopKlcMOizEp3jJ91AD6G0YQQ-v_uw)

У этого репозитория обрезанный list-general.txt содержащий только адреса Discord и Youtube. Соответственно - другие сайты не будут работать. Банально скопировав все адреса из листа GBDPI и вставив его в list-general.txt, можно получить работающий Discord, Youtube, leetcode и прочие сайты с сервисами

**Comment by Flowseal** [comment]
> > После некоторого времени вижу, что некоторые сайты, не корректно открываются, один из них - leetcode
> > ![image](https://private-user-images.githubusercontent.com/95306631/374894440-606d84c4-a0e8-4ef4-b541-b3d1bc6b041f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzE1ODgsIm5iZiI6MTcyODQ3MTI4OCwicGF0aCI6Ii85NTMwNjYzMS8zNzQ4OTQ0NDAtNjA2ZDg0YzQtYTBlOC00ZWY0LWI1NDEtYjNkMWJjNmIwNDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEwNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2N2ZkNzI2ZDQ0Y2M1MjFiNDM4YWZiZWZlNGJlMjIyM2I2OTZmY2IzMzgzMjU0MmQ0NjdhNTc4YTA0YTJiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QRgsQiZIkNmgJVopKlcMOizEp3jJ91AD6G0YQQ-v_uw)
> 
> У этого репозитория обрезанный list-general.txt содержащий только адреса Discord и Youtube. Соответственно - другие сайты не будут работать

Добавляя хост - вы горите софту, чтобы он дурил эти пакеты. Если сайт до этого работал - то и с софтом должен работать без добавления его куда-либо.

**Comment by Jonerys** [comment]
Подтверждаю проблему, но она возникает только при использовании скрипта discord+youtube. Со скриптом только на discord все работает.
У меня отлетели, внезапно, яндекс почта, гугл-сервисы типа почты, переводчика

**Comment by Flowseal** [comment]
> Подтверждаю проблему, но она возникает только при использовании скрипта discord+youtube. Со скриптом только на discord все работает. У меня отлетели, внезапно, яндекс почта, гугл-сервисы типа почты, переводчика

Скорее всего я знаю причину, в ближайшем релизе должно пофиксить

**Comment by southme** [comment]
Файл с припиской "service" не работает, консоль на секунду запускается и все. Автозапуска при старте системы так же не происходит. Запускал от имени админа, в пути кириллицы нет.

**Comment by Flowseal** [comment]
> Файл с припиской "service" не работает, консоль на секунду запускается и все. Автозапуска при старте системы так же не происходит. Запускал от имени админа, в пути кириллицы нет.

Пробелы в пути

**Comment by southme** [comment]
> > Файл с припиской "service" не работает, консоль на секунду запускается и все. Автозапуска при старте системы так же не происходит. Запускал от имени админа, в пути кириллицы нет.
> 
> Пробелы в пути

Так точно, теперь все заработало. Благодарю!
