### ISSUE TITLE
Почему не пишите о наличии майнера для непосвященных?

### ISSUE THREAD

**Issue by TheRusnike** [Flowseal/zapret-discord-youtube#143]

**Comment by sorseban** [comment]
а где именно

**Comment by Flowseal** [comment]
Файлы идентичны бинарникам которые лежат в https://github.com/bol-van/zapret
Можете сравнить их хэши.

**Comment by jake66-cmd** [comment]
Типичные руссы, ниче бесплатно не делают по доброй воле. По доброй воле могут только майнер захуярить в подарок к репаку).
TheRusnike ты что то по факту сказать можешь?(В любом случае я всякой хуйне вот этой не доверял с обходом блокировок. Обошел проверяй целые штаны говна нахуевертили:D. Просто пользуюсь впн приватным с кентами)
