### ISSUE TITLE
Windivert не инициализируется

### ISSUE THREAD

**Issue by Siman742** [Flowseal/zapret-discord-youtube#148]
![image](https://github.com/user-attachments/assets/17c728da-d4c8-4356-9c4d-b33a79619b1c)
При запуске не вгружается windivert. Спустя время просто офается батник, discord_youtube сразу офается. Все версии чекнул и на разных дисках сейвил программу.

**Comment by FlowseaI** [comment]
Скачай последнее обновление.
https://github.com/FlowseaI/zapret-discord-youtube/releases/tag/1.1.1

**Comment by Flowseal** [comment]
Выполните эти инструкции:
### Остановка и удаление обхода
Для удаления оставшегося драйвера WinDivert, откройте cmd от имени администратора и пропишите следующее:
```
sc stop WinDivert
sc delete WinDivert
```
> [!NOTE]  
> Возможно, драйвер у вас будет записан по-другому. Для уточнения названия пропишите `driverquery | find "Divert"` в cmd.
