### ISSUE TITLE
Не стартует служба

### ISSUE THREAD

**Issue by Renaon** [Flowseal/zapret-discord-youtube#150]
Не стартует служба с ошибкой. Подскажите, пожалуйста
![image](https://github.com/user-attachments/assets/c43b83c6-c568-4af8-8609-55837deaccaf)

**Comment by Flowseal** [comment]
Используйте последнюю версию. Папка bin должна быть в той же папке, что и bat скрипты.

**Comment by Renaon** [comment]
Результат тот же
![mmc_0W1NxKmHc9](https://github.com/user-attachments/assets/1974dca2-1ec2-4085-bdbe-47be4c36fc3a)
Запускал вот так. Служба не стартует. На первом скрине показал попытку запустить из меню служб
![WindowsTerminal_qYg592Enae](https://github.com/user-attachments/assets/797bc54a-a3c2-464a-abca-ce6671f58276)

**Comment by Flowseal** [comment]
Ну, он не находит файл. Файл то по пути есть?

**Comment by Renaon** [comment]
Есть. Проверил
