### ISSUE TITLE
NET HELPMSG 3521 и вылетает батник

### ISSUE THREAD

**Issue by NaKaLs228** [Flowseal/zapret-discord-youtube#151]
![photo_2024-10-10_05-50-04](https://github.com/user-attachments/assets/233d0dea-0c8a-47f4-832c-cfb83ee6af45)
Выдаёт это при запуске "service_discord.bat" от имени администратора. 
При запуске "discord.bat" от имени администратора окно моментально закрывается. 
При запуске дискорда пишет: ["Checking for updates...", "Update failed - retrying in n sec..."]
Провайдер МГТС.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92

**Comment by Free4gent** [comment]
Такая же проблема, как починил?

**Comment by mila7ka** [comment]
так как починил?

**Comment by Free4gent** [comment]
Переустановка винды

чт, 16 янв. 2025 г., 16:30 mila7ka ***@***.***>:

**Comment by PrinSp1** [comment]
как это исправить?
