### ISSUE TITLE
МГТС Не работает Ютуб+голосовой чат дискорд

### ISSUE THREAD

**Issue by Shapyshka** [Flowseal/zapret-discord-youtube#156]
Главная страница ютуба выглядит так:
![image](https://github.com/user-attachments/assets/a17220d0-8604-4dbc-8037-26580761aa5e)
Дискорд открывается, но не работает голосовой чат

Провайдер МГТС. Пробовал менять строку --dpi-desync-fooling=md5sig на --dpi-desync-fooling=badseq и на --dpi-desync-fooling=datanoack - не помогает. Браузер Chrome. Игрался с QUIC и KYBER - безрезультатно. Удалял и переустаналивал службы, перезапускал компьютер - не помогает. 

Служба запущена и при включении компьютера автоматически запускается -
![image](https://github.com/user-attachments/assets/1773f76f-84b6-444d-b948-4809f1eae036)

У людей с другого города с другими провайдерами все работает. С мгтсом - беда. Почему так?

**Comment by vkeva** [comment]
Нужно во chrome://flags (или другого браузера) переключить параметры "Experimental QUIC protocol" и "TLS 1.3 hybridized Kyber support" с "Disable" на "Default"
Перезапустить браузер и на всякий случай пк, после чего все должно заработать.

у меня не мгтс, но вдруг поможет

**Comment by Shapyshka** [comment]
> Нужно во chrome://flags (или другого браузера) переключить параметры "Experimental QUIC protocol" и "TLS 1.3 hybridized Kyber support" с "Disable" на "Default" Перезапустить браузер и на всякий случай пк, после чего все должно заработать.
> 
> у меня не мгтс, но вдруг поможет

Я же написал, что уже делал это - не помогает

**Comment by Flowseal** [comment]
Читайте Readme
А также https://github.com/Flowseal/zapret-discord-youtube/issues/90
И https://github.com/Flowseal/zapret-discord-youtube/issues/92
