### ISSUE TITLE
в истории просмотра ютуба появляются видео, которые я не смотрел

### ISSUE THREAD

**Issue by ubitsakrovi2008** [Flowseal/zapret-discord-youtube#158]
когда смотрю ютуб, в истории сохраняются видео, которые я не смотрел, причем между теми, которые я буквально подряд открывал, всякие приколы на арабском и рекламы скам-схем, при этом ютуб грузит каждое видео очень долго, но потом прогружает и вссе работает без зависаний в 1080p, также возникают проблемы с кастомными серверами в инди-кооп играх, во многих других крайне нестабильный пинг, иногда подключение прерывается
на этом скриншоте история просмотров в ютубе, между самым верхним и самым нижним видео какая-то дурь, хотя я их смотрел подряд
![image](https://github.com/user-attachments/assets/43947238-6401-46c7-a068-5d3a9dc781b3)
я думаю, что автор обхода продает накрутку через батник каким-то образом, я не очень разбираюсь в этом, но мне кажется, что это как минимум странно

**Comment by Predvesnik-ai** [comment]
Просто кто то что то курит у меня за два дня нет ни одного видео в истории которого я бы не смотрел и не наводил предпросмотром...

**Comment by Flowseal** [comment]
Такое поведение никак не связано с данным репозиторием. Для ознакомления посмотрите #154
