### ISSUE TITLE
miner detected

### ISSUE THREAD

**Issue by aofrue** [Flowseal/zapret-discord-youtube#16]
![image](https://github.com/user-attachments/assets/5514878f-b3ce-4944-b7fb-4a94ac688da3)
why does this file have a bitcoin key?

**Comment by grain12** [comment]
чел ну боишься использовать так не качай и не запускай в чём проблема??

**Comment by ArtosTensei** [comment]
> ![image](https://private-user-images.githubusercontent.com/184370002/374905072-5514878f-b3ce-4944-b7fb-4a94ac688da3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0Njg1ODQsIm5iZiI6MTcyODQ2ODI4NCwicGF0aCI6Ii8xODQzNzAwMDIvMzc0OTA1MDcyLTU1MTQ4NzhmLWIzY2UtNDk0NC1iN2ZiLTRhOTRhYzY4OGRhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxMDA0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTBhZWQ0Y2IwZDUzMjMyMWJiYTIwMDI5NDVkZmE4MGQxMDM4OTRkYzBmZTA5YWQzN2I4Mzc1OGI0NjFmY2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bD1P7SMX9d3YFhBdDfcTXjLojxpizBw5pBJpoyO2w6E) why does this file have a bitcoin key?

it's for donations

**Comment by Neforio-o** [comment]
можешь в оригинальном репозитории чекнуть этот же файл

**Comment by MLNekit** [comment]
![Untitled](https://github.com/user-attachments/assets/92e902e5-a7ca-429f-854e-08d74ceb496c)

Проверил Хэш сумму из оригинального репозитория Zapret и этого

**Comment by Flowseal** [comment]
I have nothing to do with the WinDivert driver. Zapret and Goodbyedpi use it as well.
