### ISSUE TITLE
дискорд бесконечный checking for updates и иногда их фейлинг 

### ISSUE THREAD

**Issue by yaxie7777** [Flowseal/zapret-discord-youtube#161]
я не программист я понял что от провайдера к провайдеру может не работать подскажите как именно пофиксить на билайне я вообще не понимаю где и что надо изменять я пробовал включить все варианты .bat с дискордом и вместе и по отдельности. дискорд все так же бесконечно грузит разархивировал я все на рабочий стол в пути к папке не лежит никаких русских символов или пробелов кроме имени пользователя на русском. пробовал и на сам диск ц где уже ничего в пути нету на русском все так же ничего не работает. я сижу сейчас на амнезия вг но она меня не устраивает ибо иногда перестает получать рукопожатия и решает рестартнуть мне всю сеть из за чего у меня все зависает а игры вылетают

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
