### ISSUE TITLE
winws1 servise is not started. StartServise FAILED 2. The system cannot find the file specified

### ISSUE THREAD

**Issue by Manitari-iLio** [Flowseal/zapret-discord-youtube#162]
не работает, а я тупая, помогите. если что-то нажать, то просто закрывается

![Снимок](https://github.com/user-attachments/assets/c99975ed-b168-46cf-b3a2-0aa9f45282b9)

**Comment by Flowseal** [comment]
Папка bin должна быть в той же папке, что и bat файлы

**Comment by alexnumbre** [comment]
Она в этой же папке
![image](https://github.com/user-attachments/assets/30535ea3-790a-4936-b9cb-b9e1089762cb)
![image](https://github.com/user-attachments/assets/16f287fd-3e27-454d-9d78-cc0ee333f026)

**Comment by alexnumbre** [comment]
![image](https://github.com/user-attachments/assets/c7b4c920-d72a-42fd-880e-d881f9acf2a7)

**Comment by Flowseal** [comment]
> ![image](https://private-user-images.githubusercontent.com/75684587/375726596-c7b4c920-d72a-42fd-880e-d881f9acf2a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDQ0OTgsIm5iZiI6MTcyODY0NDE5OCwicGF0aCI6Ii83NTY4NDU4Ny8zNzU3MjY1OTYtYzdiNGM5MjAtZDcyYS00MmZkLTg4MGUtZDg4MWY5YWNmMmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEwNTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMzJhYzBjYzI5ZDMyMTE5NGJlNWViYjZhYjY0Y2RjNWY1MmU2Yjk1YzM4YmQwMWY3NTZiNzcyYjA3NjZiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q1HRafYOXTpW_VsnrBTXKyfiNGhOMbIChD-5NHPRZwU)

Это успешное сообщение об установке сервиса.
