### ISSUE TITLE
Удалилась половина винды

### ISSUE THREAD

**Issue by fil3ing** [Flowseal/zapret-discord-youtube#165]
После скачивания, распаковки в диск С и запуска батника комп начал сильно лагать, а после удалилась большая часть файлов с диска, включая файлы папки windows

**Comment by Flowseal** [comment]
Вы попались на фишинг - https://github.com/Flowseal/zapret-discord-youtube/issues/154

**Comment by fil3ing** [comment]
@Flowseal как так получилось что в вашей программе фишинговый скрипт оказался?

**Comment by Sifirus** [comment]
> Вы попались на фишинг - #154

Что-то известно по тому что ворует фэйк? Что делать помимо сброса до заводских?

**Comment by sh0rtener** [comment]
> Вы попались на фишинг - #154

ваше очко взломано, привыкайте
