### ISSUE TITLE
Не грузит аватарки и превью в ютубе

### ISSUE THREAD

**Issue by goldmax1412** [Flowseal/zapret-discord-youtube#166]
Проблема решаемая с ютубом. Не загружает иногда превью и аватарки каналов.
Видимо в стандартном файле list-general отсутствуют ссылки на их загрузку.
Взял ссылки из списка goodbyedpi-0.2.3rc3-2 и всё заработало.

**Comment by Flowseal** [comment]
Возможно, решилось в 1.2.0
