### ISSUE TITLE
Не работают батники

### ISSUE THREAD

**Issue by JezukoNB** [Flowseal/zapret-discord-youtube#167]
Как только я запускаю discord.bat или discord_youtube.bat программа сразу закрывается, раньше всё нормально работало но теперь почему то закрывается. При создание сервиса вроде всё нормально но winws не стартует.
![image](https://github.com/user-attachments/assets/de4fe134-fcaa-487e-9154-293a14e5b937)

Пробовал и антивирус отключать и от имени администратора запускать, не работает.

и ещё интересно что за файл создаётся под названием "Запустить"
![image](https://github.com/user-attachments/assets/60aa8faa-6ed6-4973-857f-3549863bffb4)
Через что его запускать и может в нём дело?

**Comment by Flowseal** [comment]
Покажи скриншот всех файлов

**Comment by JezukoNB** [comment]
![image](https://github.com/user-attachments/assets/7546413c-053b-4975-829a-8b675cc19135)

**Comment by JezukoNB** [comment]
> Покажи скриншот всех файлов

![image](https://github.com/user-attachments/assets/fa422609-423c-496a-a836-9e872a1128d1)

**Comment by Flowseal** [comment]
> ![image](https://private-user-images.githubusercontent.com/165131050/375774442-7546413c-053b-4975-829a-8b675cc19135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTQzMDIsIm5iZiI6MTcyODY1NDAwMiwicGF0aCI6Ii8xNjUxMzEwNTAvMzc1Nzc0NDQyLTc1NDY0MTNjLTA1M2ItNDk3NS04MjlhLThiNjc1Y2MxOTEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMzQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGMxZWI4NzdiNjc3OWFkNzkyOGRhNTM3N2VkYzJlMDIzYWVmOGY3ZmE2N2ZkZGMxZDllNDJmNjM1YzE0MzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DqbQ2TEbLX8yDfWNynAiPvxdZZr2OwMisTJDRUvl9R4)

Файл "Запустить" нетипичен для данного репозитория. Перекачай архив из релизов для безопасности

**Comment by JezukoNB** [comment]
> > ![image](https://private-user-images.githubusercontent.com/165131050/375774442-7546413c-053b-4975-829a-8b675cc19135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTQzMDIsIm5iZiI6MTcyODY1NDAwMiwicGF0aCI6Ii8xNjUxMzEwNTAvMzc1Nzc0NDQyLTc1NDY0MTNjLTA1M2ItNDk3NS04MjlhLThiNjc1Y2MxOTEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMzQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGMxZWI4NzdiNjc3OWFkNzkyOGRhNTM3N2VkYzJlMDIzYWVmOGY3ZmE2N2ZkZGMxZDllNDJmNjM1YzE0MzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DqbQ2TEbLX8yDfWNynAiPvxdZZr2OwMisTJDRUvl9R4)
> 
> Файл "Запустить" нетипичен для данного репозитория. Перекачай архив из релизов для безопасности

Скачивал с твоего профиля, батники так же моментально закрываются при открытии

**Comment by JezukoNB** [comment]
Вообще история в том, что у меня всё работало до момента когда я поспешил и открыл не батник, а само приложение winws (на старых версиях оно было ещё не в папке bin поэтому поспешил), и после этого у меня перестали вообще открываться батники

**Comment by hotlinedanya** [comment]
Такая же проблема у коллеги, батники мгновенно закрываются

**Comment by JezukoNB** [comment]
> Такая же проблема у коллеги, батники мгновенно закрываются

Видимо это распространенная ошибка, только неизвестно с чем она связана

**Comment by JezukoNB** [comment]
Я смог починить эту проблему с помощью написание в cmd sc delete WinDivert, не знаю каким боком, может кому нибудь поможет

**Comment by Flowseal** [comment]
> Я смог починить эту проблему с помощью написание в cmd sc delete WinDivert, не знаю каким боком, может кому нибудь поможет

Спасибо за фидбек.
