### ISSUE TITLE
Trojan:script/Wacatac.B!ml 

### ISSUE THREAD

**Issue by Faust7788** [Flowseal/zapret-discord-youtube#17]
![Снимок экрана 2024-10-09 125944](https://github.com/user-attachments/assets/903030aa-43fd-4562-b1dd-92daa1676c13)

**Comment by grain12** [comment]
ну боишься использовать так не качай и не запускай в чём проблема??

**Comment by SaltyManGit** [comment]
> ну боишься использовать так не качай и не запускай в чём проблема??

аргументированный ответ

**Comment by Flowseal** [comment]
Ругается на драйвер WinDivert, этот же драйвер использует goodbyedpi.
