### ISSUE TITLE
Путь содержит пробелы. Пожалуйста, переместите скрипт в директорию без пробелов. Press any key to continue . . . 

### ISSUE THREAD

**Issue by jjjjjfddddd** [Flowseal/zapret-discord-youtube#171]
Путь содержит пробелы.
Пожалуйста, переместите скрипт в директорию без пробелов.
Press any key to continue . . .
что делать?

**Comment by Flowseal** [comment]
Убрать пробелы, которые есть в папка по пути. Либо просто переместите все файлы в папку без пробелов в корень диска

**Comment by kingofwarc** [comment]
> Убрать пробелы, которые есть в папка по пути. Либо просто переместите все файлы в папку без пробелов в корень диска

Брат а можно для чайника обьяснить)
