### ISSUE TITLE
Небольшой баг с выводом echo

### ISSUE THREAD

**Issue by dDmioko** [Flowseal/zapret-discord-youtube#174]
Найдён небольшой баг с выводом через echo. Например [здесь](https://github.com/Flowseal/zapret-discord-youtube/blob/a3105c53bafd9ba856aab9f3d1a0399d52e05063/service_discord_youtube.bat#L16)

В cmd файлах используется символ `>`, который используется для записи потока в новый файл. Необходимо либо экранировать кавычками, либо записать таким образом `^>`

**Comment by Flowseal** [comment]
Это уже давно исправлено. Видимо, вы используете старую версию программы
