### ISSUE TITLE
Не работает ютуб

### ISSUE THREAD

**Issue by SistemEvil223** [Flowseal/zapret-discord-youtube#176]
браузер Firefox, на ютубе просто "нет подключения к сети".
раньше использовал гудбай тпи и с ним было куча траблов и у моего друга, у которого тоже Firefox, теже проблемы были. В итоге искали ключи/коды и спустя много времени нашли. 
Я как понимаю тут тоже нужны свои коды чтобы под себя настроить?
я что-то пробовал изменять, о чём было в инструкции написано, но оно не дало результата.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90

**Comment by SistemEvil223** [comment]
> [#90 ](https://github.com/Flowseal/zapret-discord-youtube/issues/90)

да, смотрел я, пробовал, не помогло
