### ISSUE TITLE
Как можно связаться с создателем?

### ISSUE THREAD

**Issue by 01M** [Flowseal/zapret-discord-youtube#182]
Как можно связаться с создателем в личке.

**Comment by Flowseal** [comment]
Пишите тут

**Comment by 01M** [comment]
Проблема с тем что при запуске батника, он ограничивает скорость моей сетевой карты до 100мб/c 
![image](https://github.com/user-attachments/assets/3b91a47d-a672-49b9-9cf6-9f83335deee0)

**Comment by 01M** [comment]
В настройках драйвера стоит 2.5гбит. При смене с запущенным батником на другую скорость, она всё равно остаётся 100мбс

**Comment by 01M** [comment]
Также, после закрытия батника скорость не возвращается (и после остановки сервиса WinDivert). Возвращается после перезагрузки компьютера.

**Comment by Flowseal** [comment]
Какой сетевой адаптер?

**Comment by 01M** [comment]
А нет, сейчас и после перезагрузки не вернулась, и вообще что-то не могу вернуть. RTL8125

**Comment by 01M** [comment]
Возможно у меня драйвер навернулся, попробую переустановить.

**Comment by 01M** [comment]
Видимо проблема была в драйвере.

**Comment by gerka29** [comment]
привет, как сделать что бы ubisoft не конфликтовал с запретом? а то постоянно приходится выключать его, не удобно
