### ISSUE TITLE
Фото и иконки в ютубе

### ISSUE THREAD

**Issue by Desaths** [Flowseal/zapret-discord-youtube#188]
Я вот заметил что у меня не грузят даже под ВПН, если запустить запрет, но я включал только дискорда.
Даже выключив запрет иконки не грузят не как, пробовал service_remove.bat, но ничего не произошло я даже с люди в дискорде сидел спокойно, просто по немного текстовые чаты не работали.
Я на автозагрузку не ставил.
Ну еще сделайте чтобы иконки работали с запретом.
![фотоЮтуб](https://github.com/user-attachments/assets/03198c19-4703-4170-999b-5ab27bb9fc65)

**Comment by Flowseal** [comment]
Можете попробовать использовать список из GoodbyeDPI.
