### ISSUE TITLE
youtube не работает

### ISSUE THREAD

**Issue by hc2hunter** [Flowseal/zapret-discord-youtube#19]
Ютуб не функцинирует. Сам сайт грузится бодро, а буферизует "черное окно".
И на оригинальной программе (https://github.com/bol-van/zapret-win-bundle) то же самое.

Вообще, пользую GoodbyDPI вот с такой строчкой. С этим все работает очень шустро и хорошо:
`sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -9 -e1 -q --fake-gen 29 --fake-from-hex 06ae3c1c6271d5c4c2f1e1bec79cf1dfad03e716c3dc0c98ce39de08a930bea104640a67b8157a640b1300ecafcffc24ab41cf70faf179fef0a9 --blacklist \"%CD%\russia-blacklist.txt\" --blacklist \"%CD%\russia-youtube.txt\" --blacklist \"%CD%\russia-discord.txt\"" start= "auto"`

Если начинает подтормаживать - просто перегерениваю 116-значный хэш и перезапускаю сервис, но это бывает максимум раз в неделю-две.

**p.s.** на время запуска zapret гудбайdpi я, разумеется, останавливаю.

**Comment by Flowseal** [comment]
В скором времени сделаю возможность использования сервиса гудбай вместе с запретом. Пока что можешь использовать гудбай как сервис и discord.bat в окне. Либо поиграться с параметрами в discord_youtube.bat

**Comment by Ritterru** [comment]
Таже самая проблема.
В GoodbyDPI использую такие значения:
start "" goodbyedpi.exe -9 -e1 -q --fake-gen 29 --fake-from-hex 291325b4fca70dea6a9e53c5d7823f21b71fcce9574a78048e0779ddfa32b1f761105cf3d7059c3776ae3c170fc7ea1144a738ba846e5b51a849 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

Где можно почитать про параметры которые в discord_youtube.bat ?

**Comment by hc2hunter** [comment]
> Где можно почитать про параметры которые в discord_youtube.bat ?

Предполагаю, что в оригинальном пакете ( https://github.com/bol-van/zapret ), из которого все дергают свои решения.
Но документации там выше крыши... закопаться...

**Comment by RGB-Outl4w** [comment]
> Ютуб не функцинирует. Сам сайт грузится бодро, а буферизует "черное окно".

Та же беда, но в другом формате. Различные элементы по бокам экрана (плейлисты, каналы, история просмотра) как элементы загружаются шустро и работают нормально. А вот основная часть всех страниц - не хочет ни в какую.

![firefox_Cs7mMK3epK](https://github.com/user-attachments/assets/3108560f-2831-489c-868f-2640c02358d5)

### UPD: Исправлено путём выключения TUN режима в используемой VPN-утилите.

**Comment by Flowseal** [comment]
> > Ютуб не функцинирует. Сам сайт грузится бодро, а буферизует "черное окно".
> 
> Та же беда, но в другом формате. Различные элементы по бокам экрана (плейлисты, каналы, история просмотра) как элементы загружаются шустро и работают нормально. А вот основная часть всех страниц - не хочет ни в какую.
> 
> ![firefox_Cs7mMK3epK](https://private-user-images.githubusercontent.com/101356538/374936105-3108560f-2831-489c-868f-2640c02358d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzM2MzgsIm5iZiI6MTcyODQ3MzMzOCwicGF0aCI6Ii8xMDEzNTY1MzgvMzc0OTM2MTA1LTMxMDg1NjBmLTI4MzEtNDg5Yy04NjhmLTI2NDBjMDIzNThkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxMTI4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzFlYjM1ZjdhNjM0MGVhOWIxZTYzY2U1ZjBhZTlmMzc3ZWVjMDlhNmE5MWUzNDMxNjUxNjlkN2JlMWQ3YzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-rAPD5sKHKz_fECbyNxhr0Tv7nTtG4CxGZOlfUmA_iY)

Такое бывает, когда вначале запускаешь zapret, а потом goodbyedpi

**Comment by RGB-Outl4w** [comment]
> Такое бывает, когда вначале запускаешь zapret, а потом goodbyedpi

Никогда не устанавливал и не пользовался gdpi, поэтому не очень понятно, что в таком случае предпринимать.

### UPD: Исправлено путём выключения TUN режима в используемой VPN-утилите. В своё оправдание скажу, что не предполагал его влияние на соединения в случае, когда сам VPN отключён.

**Comment by nemomode7** [comment]
Заметил странную вещь, если использовать только zapret - ютуб работает в хроме, но не работает в лисе (сам сайт грузит  шустро, но видео в бесконечном буфере).

Если использовать в комбо с гудбаем - полёт нормальный.

zapret v1.1
goodbyedpi-0.2.3rc3-2

**Comment by akelaMiss** [comment]
> В скором времени сделаю возможность использования сервиса гудбай вместе с запретом. Пока что можешь использовать гудбай как сервис и discord.bat в окне. Либо поиграться с параметрами в discord_youtube.bat

Просто хочу выразить огромную благодарность, ибо с вашей утилитой и дс и ютуб работают, хотя уже неделю как умер гуд бай. Ещё раз огромное спасибо!

**Comment by MoDerAoE** [comment]
у кого ютуб не работает попробуйте в строке --filter-tcp=443 поменять --dpi-desync-fooling=md5sig на --dpi-desync-fooling=badseq

**Comment by NuclearBeggar** [comment]
> у кого ютуб не работает попробуйте в строке --filter-tcp=443 поменять --dpi-desync-fooling=md5sig на --dpi-desync-fooling=badseq

Начал грузить но крайне медленно... И на этом спасибо. И то какими-то рывками

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90

**Comment by leonelo00** [comment]
start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

**Comment by Somebody7777** [comment]
taskkill /f /im cmd.exe
для остановки всех запущенных батников
