### ISSUE TITLE
Данный файл должен быть запущен с правами администратора

### ISSUE THREAD

**Issue by Fresko1337** [Flowseal/zapret-discord-youtube#191]
Приветствую! Запускаю батник от имени администратора, а выдаёт ошибку "Данный файл должен быть запущен с правами администратора"
![{119A8CDB-9DA9-4653-9FC2-5ADDBA8F2517}](https://github.com/user-attachments/assets/039d0901-6815-4a71-a9a3-b719f9711b04)

![{59F07133-C5AE-47C4-83EF-F41BBA3FE881}](https://github.com/user-attachments/assets/886a07a6-faff-4adb-99b8-60394482c3a4)

**Comment by SkyeDice** [comment]
Это просто сообщение, по идее? Написано дальше нажать любую клавишу, чтобы продолжить

**Comment by Fresko1337** [comment]
> Это просто сообщение, по идее? Написано дальше нажать любую клавишу, чтобы продолжить

Консоль закрывается после Enter -> Enter

**Comment by th1ks** [comment]
> > Это просто сообщение, по идее? Написано дальше нажать любую клавишу, чтобы продолжить
> 
> Консоль закрывается после Enter -> Enter

После этого ничего не происходит? Должно разблокировать по идее
