### ISSUE TITLE
Что-то подозрительное в файлах

### ISSUE THREAD

**Issue by Nocld** [Flowseal/zapret-discord-youtube#192]
Решил удалить и поставить новую версию, но один интересный файл все никак не хотел удаляться. Описание, конечно, смущает очень сильно. Есть этому объяснение?
![что это](https://github.com/user-attachments/assets/dc0403cf-2347-44f1-9433-e0d79f605167)

**Comment by mougly1337** [comment]
В этом и прикол) запустил данную программу для обхода , а в итоге все файлы с компа удалились и пришлось переустанавливать винду

**Comment by iamkuper** [comment]
1) Переименуй файл (расширение смени на exe)
2) Перезагрузи комп
3) Удали

**Comment by PROTECTORURSA** [comment]
https://github.com/basil00/reqrypt

**Comment by Vansh0ter** [comment]
Так это просто биток создателя WinDivert'а. DLL'ка просто подписана.
![image](https://github.com/user-attachments/assets/bac997f3-2e79-439c-98ec-c71395f833ee)

**Comment by th1ks** [comment]
> В этом и прикол) запустил данную программу для обхода , а в итоге все файлы с компа удалились и пришлось переустанавливать винду

Не этот скачал, а вирусняк)

**Comment by PulseDiver** [comment]
> В этом и прикол) запустил данную программу для обхода , а в итоге все файлы с компа удалились и пришлось переустанавливать винду

вы скачали из другой репы мудака, которого уже забанили днем.

**Comment by exzolink** [comment]
> В этом и прикол) запустил данную программу для обхода , а в итоге все файлы с компа удалились и пришлось переустанавливать винду

Значит рано тебе в интернет выходить
