### ISSUE TITLE
Не работает дискорд

### ISSUE THREAD

**Issue by XRBUZIX** [Flowseal/zapret-discord-youtube#194]
не работает дискорд хотя запустил цмд дискорда через админа, постоянное обновление
![image](https://github.com/user-attachments/assets/710d6e61-d67a-455f-aacb-dbf716943e4e)

**Comment by alexkosarev2009** [comment]
+

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
