### ISSUE TITLE
что происходит?

### ISSUE THREAD

**Issue by TheIlmyBoy** [Flowseal/zapret-discord-youtube#199]
ютуб опять работает через жопу, гдпи не помогает, тут вижу zapret новая штука для обхода. ну думаю скачаю.

Почему их 2?? почему один от бол-вана а второй от фловсила? Какой их них рил и чем они отличаются? почему у бол-вана нет релиза.. тут про вредоносное ПО написано, а по факту звезд то меньше чем у бол-вана (7к на 1.5к)

помогите ^_^

**Comment by iamkuper** [comment]
У бол-вана оригинальный репозиторий. тут преднастроенный под 2 проекта (опять же не у всех это сработает)..
можно скачать и там и настроить обход под себя + добавить домены. Настройка под своего провайдера всегда лучше

**Comment by TheIlmyBoy** [comment]
Спасибо)
