### ISSUE TITLE
Добавьте пожалуйста эти домены в релиз (7ТВ Забанили)

### ISSUE THREAD

**Issue by Linaryx** [Flowseal/zapret-discord-youtube#200]
7tv.app
7tv.io
7tv.gg

**Comment by Flowseal** [comment]
Не факт, что это поможет. Возможно, блок по ip, надо разбираться в этом. Времени пока что на это нет, домены закинул конечно, вдруг кому-то да поможет

**Comment by Flowseal** [comment]
upd: try dnscrypt
https://www.howtogeek.com/765940/how-to-enable-dns-over-https-on-windows-11/

**Comment by Anxwi** [comment]
> upd: попробуйте dnscrypt https://www.howtogeek.com/765940/how-to-enable-dns-over-https-on-windows-11/

Ссылка не работает! :(

**Comment by ThreePerCento** [comment]
**Добавить в lixt-general.txt:**
frankerfacez.com
cdn.betterttv.net
cdn.frankerfacez.com
betterttv.com
betterttv.net
*.frankerfacez.com
betterttv.net
frankerfacez.com
cdn.betterttv.net
cdn2.frankerfacez.com
cdn.frankerfacez.com
api.ffzap.com
api.frankerfacez.com
cloudflare-ech.com
