### ISSUE TITLE
Почему под видом исходников выложены 2 копии релиза?

### ISSUE THREAD

**Issue by Bogir** [Flowseal/zapret-discord-youtube#201]
Собственно, где глянуть исходники?

**Comment by Bubildo** [comment]
Такой же вопрос.

**Comment by FreeWind94** [comment]
https://github.com/bol-van/zapret/tree/master

**Comment by Keonik1** [comment]
@Bogir @Sordelk потому что исходники и есть релиз, в репе уже лежат прекомпилированные бинарники
source.zip и source.tar.gz автоматически генерируются гитхабом на основании тега релиза и содержат исходники, принадлежащие этому гит тегу.
rar архив уже добавил непосредственно автор репы ручками

**Comment by Bogir** [comment]
> автоматически генерируются гитхабом на основании тега релиза

Можно еще раз, только чтоб стало понятно где посмотреть на исходный код?
У бол-вана та же ситуация, а мы - новички в этом деле, и исходники в нашем понимании - это что-то читабельное, хоть и на буржуйском языке, а не "автоматически каким-то чудом скомпилированное"

**Comment by Keonik1** [comment]
@Bogir 
# tl;dr
открываешь ютуб и смотришь гайды по работе с гитом и гитхабом.

# long read
сюда нажимаешь
![image](https://github.com/user-attachments/assets/e5654a29-4152-468f-99e3-9c32269709a7)
тут директории файлов:
![image](https://github.com/user-attachments/assets/f46919fc-9772-4ce2-8842-e9ec0faad7e5)
это и есть исходники

при формировании релиза, выставляется тег:
![image](https://github.com/user-attachments/assets/7b1b74de-84c3-45e8-9e3f-aafeb1cf0e20)

тег жестко привязывается к определенному коммиту и не может быть изменен - только удален
![image](https://github.com/user-attachments/assets/1a6843cc-e849-4eec-a8e2-bc69fe67913c)

при выпуске релиза указывается тег и прочая инфа
![image](https://github.com/user-attachments/assets/901d8d80-32ce-4fb0-b2ed-10032f2bc656)

при выпуске релиза гитхаб берет этот тег и упаковывает всё содержимое из директории (скрин 2) в архивы и прикрепляет к релизу с пометкой "исходники".

больше ничего не делается. в репозитории могут лежать заранее скомпилированные файлы, этот случай такой, потому что репозиторий предназначен для распространения конфигураций для четко заданной цели - ютуб-дискорд.

скомпилированы исходники скорее всего из репозитория https://github.com/bol-van/zapret/ , но этого я не знаю.
