### ISSUE TITLE
При установке пишет, что не может установить OpenService

### ISSUE THREAD

**Issue by Magnaderra** [Flowseal/zapret-discord-youtube#202]
Добрый день! При запуске service_discord_youtube.bat программа пишет, что не может установить OpenService, но после этого работает нормально (не считая периодические подвисания ютуба).

Это нормально?

**Comment by Magnaderra** [comment]
Полный текст:

`Данный файл должен быть запущен с правами администратора (ПКМ - Запустить от имени администратора).
Нажмите любую клавишу, чтобы продолжить создание сервиса.
Press any key to continue . . .
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 2620
        FLAGS              :
Press any key to continue . . .`

**Comment by Flowseal** [comment]
По логам всё запуситлось
