### ISSUE TITLE
Очень хардовое, но решение с дискордом. RTC работает. 

### ISSUE THREAD

**Issue by KastoneX** [Flowseal/zapret-discord-youtube#203]
Постараюсь объяснить так, чтобы понял даже чел, который еле с компьютером справляется. Я не использовал интерактивные ссылки, чтобы все было довольно прозрачно, так что даже любой параноик справится:).

Как я понимаю, базовое решение от создателя данного репозитория, вам не помогло.
Начнем с того, что вам необходимо подобрать параметры. Делается это с помощью blockcheck.

Шаг 1 -  скачиваем архив https://github.com/bol-van/zapret-win-bundle/archive/refs/heads/master.zip

Шаг 2 - переносим его на рабочий стол и вытаскиваем из архива папку. в итоге у вас появляется папка "zapret-win-bundle-master" на рабочем столе

Шаг 3 - открываем эту папку, открываем папку blockcheck, запускаем от имени администратора файлик blockcheck.cmd

Шаг 4 - смотрим на наличие "Warning", если есть, то вам надо будет поменять DNS-серверы на гугловские [8.8.8.8 для первого и 8.8.4.4 для второго (погуглите пж сами как это сделать)]. Если никаких надписей "Warning" нет, то в конце командной строки у вас будет надпись "domain(s) (default: rutracker.org) :" пишем сюда discord.com, а дальше жмем enter на каждый вопрос, который вам будет там задаваться, до тех пор, пока не начнутся перебираться параметры. Ждем пока оно все не закончится

Шаг 5 - после того, как в командной строке перестали выводиться различные параметры и вас просят нажать enter чтобы продолжить - нажимайте enter. У вас должна закрыться командная строка и в папки с blockcheck.cmd должен появиться файлик blockcheck.log. Открывайте этот файлик через блокнот и ищите строку, где будет написано !!!AVAILABLE!!!, примерно так она выглядит:

- checking winws --wf-l3=ipv4 --wf-tcp=80 --dpi-desync=syndata,disorder2 --dpi-desync-fake-syndata        
!!!!! AVAILABLE !!!!!

Шаг 6 - копируем часть после checking winws, в моем случае - это: "--wf-l3=ipv4 --wf-tcp=80 --dpi-desync=syndata,disorder2 --dpi-desync-fake-syndata"

Шаг 7 - открываем папку, которую вы скачали с репозитория, в котором вы сейчас находитесь, у них может быть разное название в зависимости от релиза, в моем случае - это "zapret-discord-youtube-main".

Шаг 8 - тыкаем правой кнопкой мыши по файлу discord.bat, открываем его через блокнот (только один раз, если выскачет окно с таким вопросом)

Шаг 9 - после "start "zapret: discord" /min "%BIN%winws.exe"" удаляем все что у нас есть и вставляем то, что мы скопировали из файлика "blockcheck.log" (не забудьте пробел после ...winws.exe").

Шаг 10 - закрываем блокнот, в котором мы изменяли discord.bat и сохраняем. Запускаем discord.bat от имени администратора и включаем дискорд, скорее всего он запустится, но есть нюанс к RTC подключиться не получится из-за того что blockcheck не подбирает фильтры для UDP. После удачной проверки закрываем дискорд и нашу командную строку, она пока нам не понадобится

Шаг 11 - открываем браузер и вставляем ссылку https://shell.cloud.google.com и ждем пока у нас снизу не появится командная строка

Шаг 12 - в командную строку в браузере, которая откроется у вас по ссылке https://shell.cloud.google.com вставляем это "curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash" (Без кавычек). У вас должен скачаться файлик (он будет называться WARP.conf) после того, как в командной строке пройдут все манипуляции

Шаг 13 - качаем с этого репозитория https://github.com/amnezia-vpn/amneziawg-windows-client/releases/tag/1.0.0  файлик amneziawg-amd64-1.0.0.msi

Шаг 14 - запускаем файлик amneziawg-amd64-1.0.0.msi. после его установки откроется программа AmneziaWG. В левом нижнем углу будет кнопка "Добавить туннель" надо на нее нажать и выбрать наш файл WARP.conf. После этого можно свернуть приложение AmneziaWG

Шаг 15 - снова запускаем наш файлик discord.bat от имени администратора, заходим в дискорд, звоним кому нибудь. Теперь открываем AmneziaWG, которую мы недавно свернули и где-то по середине экрана будет кнопка "Подключить" - нажимаем на нее, через буквально 5-10 секунд вас подключит к RTC

Шаг 16 - радуемся жизни и общаемся с друзьями

Теперь о том как пользоваться всем этим в будущем. 1- открываем discord.bat,  2 - заходим в дс,  3- звоним, 4- включаем AmneziaWG, 5 - подключаемся - все работает. В случае если у вас что-то сломается, то повторите эти действия еще раз.

Огромное спасибо Автору данного репозитория. Flowseal - СПАСИБО ТЕБЕ.

Также если вы хотите меня как-то отблагодарить, то вы можете поставить звездочку (в правом верхнем углу будет кнопочка "Star") на [мой репозиторий](https://github.com/KastoneX/Google-Colab-to-Telegram-Notifications), он никак не относится к данной теме и такой же крутой, как у Flowseal, но тоже полезный (для программистов - питонистов)

Вот не интерактивная ссылка на мой репозиторий - https://github.com/KastoneX/Google-Colab-to-Telegram-Notifications

Также прошу вас поставить звездочку автору данному репозиторию. Всем спасибо, хорошего пользования

**Comment by KastoneX** [comment]
Также есть шанс, что у вас все будет работать и без discord.bat, но у меня работает только в такой связке

**Comment by myrlikk** [comment]
Дружище, ты лучший!
Получилось, спасибо

**Comment by TheDigitalMadness** [comment]
```
comparing system resolver to public DNS : 8.8.8.8
pornhub.com : OK
ntc.party : OK
rutracker.org : OK
www.torproject.org : OK
bbc.com : OK
```

Все понравилось, но эта строчка, конечно, зря высвечивается при запуске bodycheck)

**Comment by macarelov34** [comment]
Спасибо огромное! с 11 шага всё работает самостоятельно без батника!
Я долго мучался нигде норм инструкции не было!

**Comment by dwpoint** [comment]
@KastoneX а если у меня все UNAVAILABLE?

**Comment by super0210** [comment]
Когда подключаю варп, просто отключается интернет. Всё делал по инструкции. Сам обход дискорда у меня работает, однако некоторое время назад появилась проблема с подключением к RTC. Просто перестало

**Comment by yurevms** [comment]
Бро, ты просто легенда. Я с октября не мог пофиксить, перепробовал уже всё что только можно, но ничего не работало. Единственное я не понял что конкретно копировать из файла blockcheck.log, так как много похожих строк было, и когда их вставлял в батник он просто закрывался моментально. Я решил скипнуть этот момент и всё равно всё заработало. В общем спасибо большое <3

**Comment by BlandtA** [comment]
Нету "checking winws" в логах
