### ISSUE TITLE
Не работает(Ростелеком)

### ISSUE THREAD

**Issue by Shumasick** [Flowseal/zapret-discord-youtube#205]
Ребята, всем привет. У друга не работает данный метод. Запускает от имени администратора, файл запущен, но продолжается бесконечная загрузка окна Discord. Пробовал закрыть DS и запустить по новой, но результат один и тот-же. Ошибок никаких не выдаёт. Подскажите, как можно решить проблему? Заранее спасибо за разработку.

![1234567](https://github.com/user-attachments/assets/382f403a-e9ac-4b4c-a8b9-0ac2b0e6236a)

**Comment by serpen7** [comment]
Попробуйте в файле, который открываете, в строчках поменять --dpi-desync-fooling=md5sig на --dpi-desync-fooling=badseq

**Comment by Shumasick** [comment]
> Попробуйте в файле, который открываете, в строчках поменять --dpi-desync-fooling=md5sig на --dpi-desync-fooling=badseq

К сожалению не помогло. У меня же версия из архива отлично работает, а у друга ничего не происходит!

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
