### ISSUE TITLE
Ошибка 1072 при удалении WinDivert

### ISSUE THREAD

**Issue by Kxarlex** [Flowseal/zapret-discord-youtube#207]
При удалении windivert возникает ошибка 
[SC] DeleteService FAILED 1072:

The specified service has been marked for deletion.

Кто нибудь сталкивался и как решили данную проблему?

**Comment by Flowseal** [comment]
Перед удалением необходимо остановить все сервисы, которые использую WinDIvert (GoodbyeDPI, zapret)
