### ISSUE TITLE
Escape from tarkov не работает вместе с программой запрет

### ISSUE THREAD

**Issue by DifficultPhil** [Flowseal/zapret-discord-youtube#209]
![image](https://github.com/user-attachments/assets/dce2bd2c-7755-4e88-9cbe-2a51c9c841a0)
вот такая ошибка при загрузке
Версия: v1.2.0 ничего не модифицировал, впна нет, дпи удален

**Comment by AnONiM23Lord** [comment]
это после рейда или при входе в игру, если при входе то фиг знает у меня оно работает.

**Comment by ilyuzhko** [comment]
при входе) и иногда после рейда
