### ISSUE TITLE
подключения к RTC, не установлен маршрут| Не работающие демки

### ISSUE THREAD

**Issue by lemonvomit** [Flowseal/zapret-discord-youtube#210]
Дискорд открывается, работает как надо-но при подключении в войс идет подключение к ртс а далее-не установлен маршрут. Так повторяется миллионами раз, но если один из него вам удается войти в войс-не грузит демки и не дает демонстрировать самому. 
Пробовала менять порты, шарилась в изменениях других строк, пыталась установить чьи-то настройки-все тщетно.
Провайдер ростелеком
До этого дня все работало прекрасно, мб виновато обновление драйверов винды, что выкатили вчера-но как мне заявляют друзья у них все прекрасно. Поэтому не шарю, че делать. 
Мб у кого то есть работающий кодник или помощь в этом деле

**Comment by lemonvomit** [comment]
Даже если пускает, интересно что за трабл с демками-простая загрузка и далее "вы были отключены"

**Comment by Flowseal** [comment]
Скачайте последнюю версию.
Дальше вам сюда - https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by primera7790** [comment]
У меня схожая проблема появилась с обновлением AdGuard.
Добавил приложение в исключения, заработало.
Настройки -> Основные... -> Расширенные... -> Исключите...введя полный путь
Пример пути на win10: C:\Users\Username\AppData\Local\Discord\app-1.0.9168\Discord.exe
Полагаю, что при обновлении Discord, нужно будет поправить путь, указав актуальную app папку.
