### ISSUE TITLE
YouTube запускается с задержкой

### ISSUE THREAD

**Issue by Daemon26** [Flowseal/zapret-discord-youtube#213]
Добрый день,goodbyedpi работать перестал, фикс с хексом и перебором значений тоже. и тут появился запрет. Снёс goodbyedpi и использую только запрет, но заметил странность, что видео на ютубе стартует с задержкой секунд 20, потом всё нормально начинает работать. Никто не сталкивался с такой проблемой?

**Comment by k1n3c7** [comment]
Какой у тебя браузер?

**Comment by Daemon26** [comment]
Браузер вивальди, провайдер билайн

**Comment by Daemon26** [comment]
Щас замерил, даже около минуты задержка. и нет разницы шорты или большие ролики.

**Comment by Flowseal** [comment]
Поставьте в дефолт QUIC и Kyber в chrome://flags
Также о проблемах пишите здесь - https://github.com/Flowseal/zapret-discord-youtube/issues/90
