### ISSUE TITLE
Выдает ошибку не знаю с чем связана

### ISSUE THREAD

**Issue by Bermuuuuuda** [Flowseal/zapret-discord-youtube#214]
![5210948872820613096](https://github.com/user-attachments/assets/594daa03-ba1e-4206-8b9d-c4c76a3e8a90)

**Comment by KG7x** [comment]
С рабочего стола надо запускать от админа

**Comment by Bermuuuuuda** [comment]
я так и делаю

**Comment by Flowseal** [comment]
Забыли перенести папку bin. Папка bin должна быть в той же папке, что и bat файлы
