### ISSUE TITLE
Не работает демонстрация экрана 

### ISSUE THREAD

**Issue by 100wn** [Flowseal/zapret-discord-youtube#215]
При включение демонстрации экрана у пользователей при просмотре бесконечная загрузка 
![Снимок экрана 2024-10-12 183109](https://github.com/user-attachments/assets/8e6172b7-7c2a-4462-b7d6-0357bad232b5)

**Comment by Flowseal** [comment]
Скачайте последнюю версию.
Дальше вам сюда - https://github.com/Flowseal/zapret-discord-youtube/discussions/252
Возможно, нет нужных хостов
