### ISSUE TITLE
discord_youtube.bat закрывается сразу после запуска

### ISSUE THREAD

**Issue by JIacker** [Flowseal/zapret-discord-youtube#217]
sc stop windivert
sc delete windivert 

не дают эффекта

Пишет, что указанная служба не установлена
![11](https://github.com/user-attachments/assets/e1fb8530-d5d7-4a22-990f-0534f735b4ad)

При запуске service_discord_youtube.bat выдает ошибку
The filename, directory name, or volume label syntax is incorrect.
![22](https://github.com/user-attachments/assets/478bb5a8-78fa-454e-b5b9-fb9af292082f)

Служба не появляется

Все запускается от имени администратора

**Comment by Flowseal** [comment]
> Служба не появляется

На скриншоте видно, что служба создалась и запустилась (STATE : RUNNING)
Она может остановится, но самоудалится - вряд-ли
