### ISSUE TITLE
выдает ошибку more help is availableby typing net helpmsg 3521 система windows 7

### ISSUE THREAD

**Issue by idunno23124** [Flowseal/zapret-discord-youtube#221]
помогите решить проблему, я уже с ума сошел без дискорда

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/121

**Comment by defamina** [comment]
у меня все работало, сегодня запустила эту штуку и такой же трабл, тока у мя 10 винда, много чего перерыла, но я не гений мысли, и ниче не поняла хз что делать
