### ISSUE TITLE
проблема со steam после запуска discord_youtube

### ISSUE THREAD

**Issue by pbl6a4** [Flowseal/zapret-discord-youtube#222]
После запуска из стима пропадают все картинки, у всех стимовских сайтов пропадает оформление и нормальный интерфейс. Проблемы нет если запускать discord bat.

**Comment by VadPhonker** [comment]
Подтверждаю

**Comment by Mekkele** [comment]
Та же проблема, онлайн-игры в Steam сразу отваливаются, т.к. не могут законнектиться

**Comment by Flowseal** [comment]
Какую версию используете?

**Comment by pbl6a4** [comment]
перешел на последнюю версию, проблема устранилась

**Comment by Mekkele** [comment]
Проблема в версии 1.2.0. Вчера всё работало, сегодня уже нет, Discord пашет, но Steam отваливается

**Comment by Flowseal** [comment]
> Проблема в версии 1.2.0. Вчера всё работало, сегодня уже нет, Discord пашет, но Steam отваливается

В чистой 1.2.0 всё нормально. Возможно, вы используете кастомные скрипты
