### ISSUE TITLE
More help is available by typing NET HELPMSG 3521.

### ISSUE THREAD

**Issue by hochyds** [Flowseal/zapret-discord-youtube#223]
Данный файл должен быть запущен с правами администратора (ПКМ - Запустить от имени администратора).
Нажмите любую клавишу, чтобы продолжить создание сервиса.
Press any key to continue . . .
The zapret DPI bypass : zapret service is not started.

More help is available by typing NET HELPMSG 3521.

[SC] DeleteService SUCCESS
[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 12668
        FLAGS              :
Press any key to continue . . .

запустил от имени администратора
WinDivert удалял
В пути к файлу ничего нету
впн выключен

хз что делать

**Comment by Flowseal** [comment]
У вас по логам всё нормально запустилось

**Comment by defectiveheart** [comment]
> У вас по логам всё нормально запустилось

так ведь пишет  zapret service is not started.

**Comment by defectiveheart** [comment]
У меня например эта служба устанавливается, но не работает, служба zapret "Состояние - Остановлено", и не запускается (если в службах винды смотреть). Пробую просто запустить батник general (ALT2).bat появляется окошко и сразу закрывается, хотя я так понимаю оно должно появляться и работать просто в фоне висеть?

**Comment by sh3sick** [comment]
> У меня например эта служба устанавливается, но не работает, служба zapret "Состояние - Остановлено", и не запускается (если в службах винды смотреть). Пробую просто запустить батник general (ALT2).bat появляется окошко и сразу закрывается, хотя я так понимаю оно должно появляться и работать просто в фоне висеть?

тоже самое, и служба не запускается сколько не пытайся, постоянно ошибки какие-то, такие как 433 или 1067 вроде фиксишь и ничего не помогает. 
![Безымянный](https://github.com/user-attachments/assets/76b652e4-bef1-4bd5-aac2-edffdd97d1ff)

**Comment by defectiveheart** [comment]
> > У меня например эта служба устанавливается, но не работает, служба zapret "Состояние - Остановлено", и не запускается (если в службах винды смотреть). Пробую просто запустить батник general (ALT2).bat появляется окошко и сразу закрывается, хотя я так понимаю оно должно появляться и работать просто в фоне висеть?
> 
> тоже самое, и служба не запускается сколько не пытайся, постоянно ошибки какие-то, такие как 433 или 1067 вроде фиксишь и ничего не помогает. ![Безымянный](https://private-user-images.githubusercontent.com/192913252/398789044-76b652e4-bef1-4bd5-aac2-edffdd97d1ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODQ2MjIsIm5iZiI6MTczNTI4NDMyMiwicGF0aCI6Ii8xOTI5MTMyNTIvMzk4Nzg5MDQ0LTc2YjY1MmU0LWJlZjEtNGJkNS1hYWMyLWVkZmZkZDk3ZDFmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwNzI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTljM2EyODY1MDcxYzQ4NjgyOTU2MTc0MWE0YTc5NDNiN2Q4YWM0OWY2NWFhNzBmOGRiNTVkMmViYzM5MzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hf7CuEYy76FXsPpkm4wsOflZY3fxIf7PYW4V4e1NoBI)

Чтобы работали эти отдельные батники(запускались, автоматически закрывались, и потом другое окошко в фоне висело и работало), на винде должна работать служба BFE(Служба базовой фильтрации), но она у меня не включалась. Я нашел у себя твик на включение и отключение Firewall, я так понимаю от него служба работает, короче включил его, перезагрузил, и включил BFE уже. И после этого батники стали работать. Вот содержимое твика, он как батник идет.

@echo off
tittle Firewall Enabled - Disabled
mode con: cols=50 lines=10
color a
echo.
echo ----------------------------------
echo - 1) Firewall Enabled -
echo - 2) Firewall Disabled -
echo ----------------------------------
set /p frw=:
if %frw% EQU 1 goto e
if %frw% EQU 2 goto d

:e
reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\mpssvc" /v "Start" /t REG_DWORD /d "2" /f
reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\BFE" /v "Start" /t REG_DWORD /d "2" /f
echo Done, restart your computer.
timeout /t 3 /nobreak
exit

:d
reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\mpssvc" /v "Start" /t REG_DWORD /d "4" /f
reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\BFE" /v "Start" /t REG_DWORD /d "4" /f
echo Done, restart your computer.
timeout /t 3 /nobreak
exit
