### ISSUE TITLE
Как правильно добавить инстаграмм чтобы тоже был обход?

### ISSUE THREAD

**Issue by DaniHyr** [Flowseal/zapret-discord-youtube#225]
Добавляю в txt instagram.com
А сайт все равно не грузится, как правильно сделать

**Comment by siskaebat1337** [comment]
вписывай эти
instagram.com
www.instagram.com
api.instagram.com
i.instagram.com
scontent.cdninstagram.com
cdninstagram.com
graph.instagram.com
z-p3.www.instagram.com
z-p4.www.instagram.com

**Comment by DaniHyr** [comment]
![image](https://github.com/user-attachments/assets/4f31ccea-0efc-4271-9a0b-d43a53b1875c)
![изображение_2024-10-13_022011691](https://github.com/user-attachments/assets/4b138aa2-169b-4376-99dc-fd9b8cdf9425)

**Comment by MrJek** [comment]
вопрос все еще актуален, есть возможность его запустить?
