### ISSUE TITLE
Работает дискорд но не работает ютуб

### ISSUE THREAD

**Issue by LordEyE1337** [Flowseal/zapret-discord-youtube#227]
Сначала и в дискорд не заходило, убрал split2 и зашло в войс. всё гуд, но ютуб нивкакую не грузит

**Comment by suslikar2ga** [comment]
скачай goodbye dpi и запусти russia blacklist 0

**Comment by suslikar2ga** [comment]
> скачай goodbye dpi и запусти russia blacklist 0

он на гитхабе если чо

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90
