### ISSUE TITLE
Фейки

### ISSUE THREAD

**Issue by 1vanK** [Flowseal/zapret-discord-youtube#229]
> В сети появились правдоподобные копии аккаунтов, которые распространяют вредоносное ПО под видом Zapret.
Отличить оригинал от фейка вы всегда можете по количеству [⭐ звёзд](https://github.com/Flowseal/zapret-discord-youtube/stargazers) (в правом верхнем углу) у репозитория.

Ну вот например виндовс бандл от автора запрета имеет меньше звезд, чем у вас, кто из вас фейк?
https://github.com/bol-van/zapret-win-bundle

В чем смысл вообще существований этой репы? У бол-вана есть блокчекер, который подбирает параметры, а у вас настройки под конкретного провайдера, которые очевидно у многих просто не заработают.

**Comment by Flowseal** [comment]
> В чем смысл вообще существований этой репы?

User friendly, которым болван не хочет заниматься (с его же слов)

**Comment by 1vanK** [comment]
Так а в чем юзер френдли? У него запустил батник, который сам по себе поработал и выдал настройки. Запустил батник с настройками - пользуешься. А у вас просто запуск батника с нерабочими настройками.

**Comment by 1vanK** [comment]
Если уж хотели помочь людям, то не засирали бы интернет ссылкой на эту парашу, а гайд бы сделали, как пользоваться официальным запретом
