### ISSUE TITLE
майнер?))

### ISSUE THREAD

**Issue by negativishe** [Flowseal/zapret-discord-youtube#230]
![photo_2024-10-12_21-32-22](https://github.com/user-attachments/assets/6cdc40ff-b702-432e-afff-b77ee2f1fab8)
гайсы, вас не смущает вот этот файлик у него в папке "bin"?)  еще и URL очень интересный)) ([URL:
https://reqrypt.org/windivert.htmlJ [Bitcoin:
1C5vZVSbizPeZ8ydTYhUfm4LA2cNwBfcYh)

**Comment by negativishe** [comment]
![image](https://github.com/user-attachments/assets/db932e4c-6b05-4435-9351-f0817b3ea36b)
ммм, еще и полный доступ к системе))

**Comment by yfokban** [comment]
> ![photo_2024-10-12_21-32-22](https://private-user-images.githubusercontent.com/184304740/375983147-6cdc40ff-b702-432e-afff-b77ee2f1fab8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NjI0ODgsIm5iZiI6MTcyODc2MjE4OCwicGF0aCI6Ii8xODQzMDQ3NDAvMzc1OTgzMTQ3LTZjZGM0MGZmLWI3MDItNDMyZS1hZmZmLWI3N2VlMmYxZmFiOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxOTQzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWQyMTNiMTFjYTViZjE5Nzk0MzNkZDY0ZGMwYTkzYWU5NzJhNTE5MTA0M2FhYWE2NzI2Y2IzMTc1NWEwODBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.01hErv_9GqUs9rhxT8CtEE-vl7VJ2Cq5mzzgqGBZD_k) гайсы, вас не смущает вот этот файлик у него в папке "bin"?) еще и URL очень интересный)) ([URL: https://reqrypt.org/windivert.htmlJ [Bitcoin: 1C5vZVSbizPeZ8ydTYhUfm4LA2cNwBfcYh)

По итогу майнер?

**Comment by negativishe** [comment]
честно - без понятия, в интернете пишет "WinDivert64.sys — системный драйвер, связанный с WinDivert, библиотекой, используемой для перехвата и перенаправления сетевых пакетов" но мне очень не нравится этот юрл

**Comment by mainstoned** [comment]
ну, я так посмотрел, с гитхаба самого виндиверта в этом же файле такой же url и bitcoin адрес, так что хз

**Comment by negativishe** [comment]
ОТМЕНА, копался немного в интернете и нашел сайт "ReQrypt" в кратце - это сайт этого WinDrive который перенаправляет пакеты интернета и там написан адрес кошеля крипты и пишут: "Мы принимаем пожертвования через [биткоины](https://bitcoin.org/). Пожалуйста, используйте следующий адрес:

1C5vZVSbizPeZ8ydTYhUfm4LA2cNwBfcYh
Мы ценим любое пожертвование. Если вы хотите получить кредит за пожертвование, пожалуйста, отправьте по электронной почте basil детали транзакции. В противном случае, поскольку биткоин псевдоанонимен, мы не будем знать, что пожертвование поступило от вас.

Обратите внимание, что указанный выше адрес Биткоина можно проверить, просмотрев описание файла подписанного драйвера WinDivert (версия 1.1.7 или выше)."

**Comment by negativishe** [comment]
![Uploading photo_2024-10-12_21-49-20.jpg…]()

**Comment by negativishe** [comment]
![photo_2024-10-12_21-49-20](https://github.com/user-attachments/assets/d2fe93f9-eee1-439e-86e9-fc75525b9297)

**Comment by headlykyno** [comment]
@negativishe так майнер или нет?

**Comment by negativishe** [comment]
@headlyboi думаю, что нет. Я в этой теме не ахти, но вроде даже антивирусники не жалуются. если что, тут,думаю скажут

**Comment by Lvlywind** [comment]
@negativishe каспер ругается, так что скорее всего да

**Comment by JampireX** [comment]
разработчик WinDivert конечно паники внес, пихать биткоин адрес в подпись это гениально)
по теме - ничего плохого в этом драйвере нету, его в том числе гудбай использует

**Comment by negativishe** [comment]
@JampireX воот, я очень пересрался с этой подписи еще и вижу,мол, биткоин чет там, и при этом эту прогу удалить не могу,тк пишет, что в фоне работает, а дискорд бат закрыл. плюсом полный доступ тоже смутил

**Comment by negativishe** [comment]
@Lvlywind я через встроенный дефэндер прогнал и др веб с малвером. никто не ругался

**Comment by JampireX** [comment]
@negativishe работает в фоне потому что это драйвер. в папке есть батник service_remove.bat - он остановит сервис и файл будет свободен.

**Comment by Ttimofeyka** [comment]
There can be no miner, the code is publicly available and can be viewed (examined) manually.

**Comment by negativishe** [comment]
@JampireX спасибо за пояснение

**Comment by Gojikovi** [comment]
Какой майнер? Существует множество способов дурения DPI, но для большинства используется модификация TCP соединения на уровне пакетов. WinDivert это открытый драйвер, который используется как раз для перехвата и модификации пакетов. Без него ничего не будет работать. Даже goodbyedpi использует WinDivert. Если думаете, что это какой-нибудь майнер, то вперёд и с песней изучать код программы и самостоятельно всё компилировать.

**Comment by negativishe** [comment]
@Gojikovi почитай комментарии. меня очень смутило описание файла, но ниже я потом написал что это и к чему это. потом и мне пояснили за всю эту ерись:)

**Comment by Rocky4562** [comment]
Есть актуальная информация на счёт вредоносности?

**Comment by JampireX** [comment]
> Есть актуальная информация на счёт вредоносности?

мой пост выше все еще актуален

**Comment by BinAlexme** [comment]
как бы то ни было, вы соглашаетесь стать древом для развития системы. сколько пользователей сейчас им пользуются помогают владельцу дальше продолжать жить и развивать проект. на параметрах файла есть строчки кода как тихая(фон) загрузка. файлы вы возможно удалили но вот есть не задача. также файл запущен и не хочет уходить до следующего перезапуска пк. 
автор подметил что вы таким образом согласны на том при помощи вас майнить биткоин.
уже запрету как dpi лет уже 4-5 что понятное дело на вас хорошая сумма все же выйдет.

**Comment by Kirill23lol** [comment]
помогите пожалуйста как остановить это драйвер я просто папку с ним удалил а его вытащил и оставил что мне теперь делать? я не смогу его удалить?

**Comment by BinAlexme** [comment]
Нужно запустить ресурс сервис и там есть кнопки пункты удалить службу. таким образом вы выключите ее. и спокойно удалите все подчестую.
