### ISSUE TITLE
не работает discord_youtube.bat 

### ISSUE THREAD

**Issue by govnovor454** [Flowseal/zapret-discord-youtube#233]
имеется проблема, пытаюсь открыть discord_youtube.bat моментально открывается консоль и так же , моментально закрывается перед закрытием раза с 3-5 смог разобрать надпись в консоле access is denied раньше всё нормально работало но теперь почему то закрывается соответственно не ютуб не дс не фурычат
![2024-10-12_16-02-24](https://github.com/user-attachments/assets/23f648d7-f62c-4733-a759-aa3ebc25002e)
через service_discord_youtube также не работает 
![2024-10-12_23-33-58](https://github.com/user-attachments/assets/fcf2ac66-f8d9-4bc0-9478-484b2764836e)
иногда при попытке запуска вылезает вот эта
![2024-10-12_15-45-01](https://github.com/user-attachments/assets/18b323fd-999c-4af5-ba94-15d13d1b278d)
помогите пж :(

**Comment by Gojikovi** [comment]
Требования к подписи драйверов windows изменились в 2021 году.
Официальные бесплатные обновления windows 7 закончились в 2020.
После этого несколько лет продолжали идти платные обновления по программе ESU.
Именно в этих ESU обновлениях находится обновление ядра windows 7, позволяющиее загрузить драйвер
windivert 2.2.2-A, который идет в поставке zapret.
Поэтому варианты следующие :

1) Взять windivert64.sys и windivert.dll версии 2.2.0-C или 2.2.0-D отсюда : https://reqrypt.org/download
и заменить эти 2 файла.
В zapret-win-bundle есть отдельных 2 места, где находится winws : zapret-winws и blockcheck/zapret/nfq.
Надо менять в обоих местах.
Этот вариант проверен и должен работать. Тем не менее патч 10 летней давности, который включает SHA256
сигнатуры, все еще необходим.

2) Взломать ESU :
https://hackandpwn.com/windows-7-esu-patching/
http://www.bifido.net/tweaks-and-scripts/8-extended-security-updates-installer.html
и обновить систему

3) Использовать UpdatePack7R2 от simplix : https://blog.simplix.info
Но с этим паком есть проблема. Автор из Украины, он очень обиделся на русских.
Если в панели управления стоит регион RU или BY, появляется неприятный диалог.
Чтобы эту проблему обойти, можно поставить временно любой другой регион, потом вернуть.
Так же нет никаких гарантий, что автор не насовал туда какой-то зловредный код.
Использовать на свой страх и риск.
Более безопасный вариант - скачать последнюю нормальную довоенную версию : 22.2.10
https://nnmclub.to/forum/viewtopic.php?t=1530323
Ее достаточно, чтобы windivert 2.2.2-A заработал на windows 7.

**Comment by govnovor454** [comment]
а просто перейти на десятку поможет ?

**Comment by Loderuner** [comment]
Скачал и установил последнюю нормальную довоенную версию : 22.2.10, не помогло. Уточните пожалйста, где конкретно менять windivert64.sys и windivert.dll ? Что такое zapret-win-bundle с двумя отдельными местами : zapret-winws и blockcheck/zapret/nfq ?

**Comment by jestxfot** [comment]
`zapret-win-bundle` - основная папка программы zapret для винды
`zapret-winws` - непосредственно сама программа zapret
`blockcheck` - скрипт автоподбора конфига для zapret

**Comment by Loderuner** [comment]
Только в одном месте смог найти эти два файла, в папке zapret\bin. Заменил, вот что получилось: 
![Screenshot_4](https://github.com/user-attachments/assets/48cae08a-0cd5-4e82-8be4-6a08eced30be)

**Comment by jestxfot** [comment]
Вроде судя по консоли всё работает как надо

**Comment by Loderuner** [comment]
Ютуб так и не заработал, даже страница не загружается, установил Хром и Оперу - то же самое. Буду думать дальше, спасибо за обратную связь.

**Comment by jestxfot** [comment]
Проверьте что у вас в браузере есть DOH (DNS) и если нет - включите их.

**Comment by Loderuner** [comment]
Еще бы знать, как это сделать)

**Comment by Loderuner** [comment]
![Screenshot_5](https://github.com/user-attachments/assets/6ebeb7ed-da5a-4ba9-a5b3-53316f536e88) поставил true

**Comment by jestxfot** [comment]
В firefox очень много проблем с сайтами. Для начала лучше пересть на хром хотя бы ради этих сайтов. В хромиумах включается здесь 

```
chrome://settings/security
```

![image](https://github.com/user-attachments/assets/50b9f0aa-f875-4fe5-8e31-82bb017c4c63)

```
https://dns.comss.one/dns-query
```

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
https://github.com/Flowseal/zapret-discord-youtube/discussions/251

**Comment by Loderuner** [comment]
С новой версией 1.3.0 ютуб заработал, браузер LibreWolf, спасибо!
