### ISSUE TITLE
не работает service_discord_youtube.bat

### ISSUE THREAD

**Issue by nq32** [Flowseal/zapret-discord-youtube#234]
при открытии service_discord_youtube.bat: 

Нажмите любую клавишу, чтобы продолжить создание сервиса.
Press any key to continue . . .
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService FAILED 5:

Access is denied.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] StartService: OpenService FAILED 1060:

The specified service does not exist as an installed service.

Press any key to continue . . .

когда ввожу: sc stop WinDivert/sc delete WinDivert вылазит это:
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.

а если driverquery | find "Divert" то вообще никакой реакции

**Comment by Flowseal** [comment]
От имени админа запускайте
