### ISSUE TITLE
Не кидаються фото в дискорде

### ISSUE THREAD

**Issue by m1msai** [Flowseal/zapret-discord-youtube#236]
пишет постоянно обработка и всё

**Comment by m1msai** [comment]
![{21B769DD-D1A3-40EB-B909-FE3D94A80DC3}](https://github.com/user-attachments/assets/77dc138d-47a0-41c9-b64f-96b29103be62)

**Comment by Flowseal** [comment]
Скачайте последнюю версию.
Дальше вам сюда - https://github.com/Flowseal/zapret-discord-youtube/discussions/252
