### ISSUE TITLE
OpenWrt

### ISSUE THREAD

**Issue by boozzze** [Flowseal/zapret-discord-youtube#239]
привет! Чудесно работает на винде, но хочется зашить в роутер
бОльшего, Кроме ют и дискорда, от zapret мне не нужно
Подскажите (оч прошу подробно), Как перенести этот конфиг на опенврт? Запрет установил, синтаксис конфигов разный на винде и опенврт

**Comment by boozzze** [comment]
просто как запустить сервис запрет с этой строкой? на openwrt
```
start "zapret: discord" /min "%BIN%winws.exe" --wf-tcp=80,443 --wf-udp=443,50000-65535 ^
--filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-udp=50000-65535 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-tcp=80 --hostlist="list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"

```

list-general скопировал в /opt/zapret/ipset/zapret-hosts-user.txt

**Comment by Th3Nigel** [comment]
Плюсую, может это кто-нибудь перевести в кастомный скрипт для zapret на OpenWrt?

**Comment by Flowseal** [comment]
Ищите ответ в оригинальном репозитории - https://github.com/bol-van/zapret
Данный репозиторий создан для поддержки Windows пользователей
