### ISSUE TITLE
Нестабильно подгружаются ававтарки на YouTube

### ISSUE THREAD

**Issue by Bouncyfishy** [Flowseal/zapret-discord-youtube#241]
В первый раз после запуска сервиса на ютубе стали грузиться аватарки у пользователей. Однако спустя несколько минут эта возможность пропадает и перезапуск службы/переустановка службы не помогает. Только изредка удаётся через постоянные переустановки службы завести аватарки вновь, но они держатся буквально пару минут. 
Оператор Дом.Ру. В чём может быть проблема и возможный фикс?

**Comment by Flowseal** [comment]
Скачайте последнюю версию.
Дальше вам сюда - https://github.com/Flowseal/zapret-discord-youtube/discussions/251
