### ISSUE TITLE
miner?

### ISSUE THREAD

**Issue by fazendus32244** [Flowseal/zapret-discord-youtube#242]
what is this?

![image](https://github.com/user-attachments/assets/131a1a5f-4cd0-45e3-872f-6aae10640594)

**Comment by JeyBarrette** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/159#issuecomment-562666864

**Comment by srbzn** [comment]
то есть это нормально и ни чем особо не угрожает для пк и данных или наоборот ?

**Comment by Flowseal** [comment]
Майнеров нет

**Comment by socoolananas12** [comment]
Это просто описание файла.
