### ISSUE TITLE
Не запускается служба созданная через service_goodbye_discord.bat

### ISSUE THREAD

**Issue by mare077** [Flowseal/zapret-discord-youtube#243]
Сервис zapret отказывается запускаться при создании через батник и после через services.msc выдавая следующую ошибку:
![image](https://github.com/user-attachments/assets/196c911c-2304-4eb2-8fd4-1fc5624b0417)
![image](https://github.com/user-attachments/assets/c25066c9-9b67-460d-bc33-e5ef3bba6844)

**Comment by Flowseal** [comment]
Читайте в Readme про service_goodbye_discord
