### ISSUE TITLE
Services remove bat не работает

### ISSUE THREAD

**Issue by matador163** [Flowseal/zapret-discord-youtube#244]
When starting the service remove bat, it gives this why what is the problem
![Снимок экрана 2024-10-13 044229](https://github.com/user-attachments/assets/795e9cf1-829e-406c-a649-7b76d187d586)

**Comment by Flowseal** [comment]
When u tried to edit something in code, u probably have changed CLRF to Linux. Try to redownload files

**Comment by matador163** [comment]
unfortunately this didn't help, I tried it as soon as I saw the problem

**Comment by Flowseal** [comment]
> unfortunately this didn't help, I tried it as soon as I saw the problem

then, open cmd with admin rights, and execute command-by-command from file. That's only what can I advice as I can't reproduce error
