### ISSUE TITLE
Ошибка подключения tor при работе сервиса.

### ISSUE THREAD

**Issue by VitoR-InA** [Flowseal/zapret-discord-youtube#245]
При работе сервиса перестаёт работать tor на любых мостах:

> 2024-10-13 07:43:21.727 [NOTICE] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
> 2024-10-13 07:43:30.851 [NOTICE] Opening Socks listener on 127.0.0.1:9150
> 2024-10-13 07:43:30.851 [NOTICE] Opened Socks listener connection (ready) on 127.0.0.1:9150
> 2024-10-13 07:43:30.905 [NOTICE] Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
> 2024-10-13 07:43:31.853 [NOTICE] Bootstrapped 1% (conn_pt): Connecting to pluggable transport
> 2024-10-13 07:43:31.854 [NOTICE] Bootstrapped 2% (conn_done_pt): Connected to pluggable transport

И дальше в лог начинает сыпать ошибками.

**Comment by Flowseal** [comment]
Ну, наверное, ошибки и надо прикреплять

**Comment by jestxfot** [comment]
Обычно такое поведение связано с:
- Недостаточным количеством реле, которые указаны в файле torrc
- Неработающими/заблокированными мостами в Tor

Очень маловероятно что программа связана с Tor. Вы можете также удалить строчку с autohost так как она может заносить адреса в список для обходов из-за чего те перестают адекватно отвечать.

**Comment by VitoR-InA** [comment]
> Ну, наверное, ошибки и надо прикреплять

Логи скопировал после удаления сервиса, сейчас попробую повторить.
