### ISSUE TITLE
Не работает с CALL OF DUTY Warzone

### ISSUE THREAD

**Issue by ProBRo141** [Flowseal/zapret-discord-youtube#246]
Здравствуйте, помогите пожалуйста исправить проблему. Когда я запускаю CALL OF DUTY Warzone через Steam с включенным обходом - игра вроде запускается и даже прогружается, но на моменте когда я оказываюсь в лобби игра просто крашится без каких либо ошибок. Когда обход выключен - всё работает на отлично. Так же бывает что другие игры вообще не запускаются пишут ошибку 32 при запуске античита easy anti-cheat.

**Comment by Flowseal** [comment]
Античит ругается на WinDivert. Ничего не поделать

**Comment by ProBRo141** [comment]
> Античит ругается на WinDivert. Ничего не поделать

Может есть вариант обхода ? Или запустить как-то "скрытно" от античита
