### ISSUE TITLE
Не работает ютуб

### ISSUE THREAD

**Issue by fizsef** [Flowseal/zapret-discord-youtube#248]
Не работает ютуб , запускаю discord_youtube.bat
Крутится, но видео не показывает (
![1](https://github.com/user-attachments/assets/dbcbcdcb-a3bc-4cae-b1dc-6844bd7d4dae)

**Comment by Igitoro** [comment]
Аналогичная проблема... Попытался через goodbie dpi, тоже не работает, видимо что-то намутили

**Comment by suslikar2ga** [comment]
> Аналогичная проблема... Попытался через goodbie dpi, тоже не работает, видимо что-то намутили

согл

**Comment by sanchelus** [comment]
> Аналогичная проблема... Попытался через goodbie dpi, тоже не работает, видимо что-то намутили
GoodbyeDPI

В 1_russia_blacklist_YOUTUBE_ALT вставляешь команду start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

 1_russia_blacklist_YOUTUBE_ALT и запускаешь, у меня как минимум работает

**Comment by suslikar2ga** [comment]
> > Аналогичная проблема... Попытался через goodbie dpi, тоже не работает, видимо что-то намутили
> > GoodbyeDPI
> 
> В 1_russia_blacklist_YOUTUBE_ALT вставляешь команду start "" goodbyedpi.exe -5 -e 1 --reverse-frag --wrong-chksum --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --fake-gen 5 --set-ttl 3 -q --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

как?

**Comment by sanchelus** [comment]
![image](https://github.com/user-attachments/assets/7daf3913-6077-4b54-854e-63ba85a0b7f5)

нажимаешь изменить

![image](https://github.com/user-attachments/assets/942c9594-41f8-47c7-881f-ad3d67090bd6)

и вставляешь команду, которую скинул выше

**Comment by suslikar2ga** [comment]
> ![image](https://private-user-images.githubusercontent.com/117862884/376026093-7daf3913-6077-4b54-854e-63ba85a0b7f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTU4NTMsIm5iZiI6MTcyODgxNTU1MywicGF0aCI6Ii8xMTc4NjI4ODQvMzc2MDI2MDkzLTdkYWYzOTEzLTYwNzctNGI1NC04NTRlLTYzYmE4NWEwYjdmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMDMyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGMyYjVhMTE4OTk4NGEzYTRiNTVlODg2YmFkZDc0YTYzYThmMDhkNDZhYjM4Y2U1NjQyYjAyNDY4MGNmNDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GaP0V_z3IiezXyHCzOddKMyr61_swsL_3Xy3d7lSaC0)
> 
> нажимаешь изменить
> 
> ![image](https://private-user-images.githubusercontent.com/117862884/376026107-942c9594-41f8-47c7-881f-ad3d67090bd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTU4NTQsIm5iZiI6MTcyODgxNTU1NCwicGF0aCI6Ii8xMTc4NjI4ODQvMzc2MDI2MTA3LTk0MmM5NTk0LTQxZjgtNDdjNy04ODFmLWFkM2Q2NzA5MGJkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMDMyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzA5OTAyMDY1NThlMTZjNmRkMTExNzE5MzM0NjY1NzE3ZDQ1ZTdiNDdlYzg5OGY0YjM3NDE2YjlhMTg0M2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mNe6mEmAksTe8-5BXmFEgcTzcQOOEOstTNhAtdvJgME)
> 
> и вставляешь команду, которую скинул выше

не оч помогло

**Comment by sanchelus** [comment]
> > ![image](https://private-user-images.githubusercontent.com/117862884/376026093-7daf3913-6077-4b54-854e-63ba85a0b7f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTU4NTMsIm5iZiI6MTcyODgxNTU1MywicGF0aCI6Ii8xMTc4NjI4ODQvMzc2MDI2MDkzLTdkYWYzOTEzLTYwNzctNGI1NC04NTRlLTYzYmE4NWEwYjdmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMDMyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGMyYjVhMTE4OTk4NGEzYTRiNTVlODg2YmFkZDc0YTYzYThmMDhkNDZhYjM4Y2U1NjQyYjAyNDY4MGNmNDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GaP0V_z3IiezXyHCzOddKMyr61_swsL_3Xy3d7lSaC0)
> > нажимаешь изменить
> > ![image](https://private-user-images.githubusercontent.com/117862884/376026107-942c9594-41f8-47c7-881f-ad3d67090bd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTU4NTQsIm5iZiI6MTcyODgxNTU1NCwicGF0aCI6Ii8xMTc4NjI4ODQvMzc2MDI2MTA3LTk0MmM5NTk0LTQxZjgtNDdjNy04ODFmLWFkM2Q2NzA5MGJkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMDMyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzA5OTAyMDY1NThlMTZjNmRkMTExNzE5MzM0NjY1NzE3ZDQ1ZTdiNDdlYzg5OGY0YjM3NDE2YjlhMTg0M2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mNe6mEmAksTe8-5BXmFEgcTzcQOOEOstTNhAtdvJgME)
> > и вставляешь команду, которую скинул выше
> 
> не оч помогло

Возможно ты запускаешь GoodbyeDPI вместе с запретом, они вроде как достаточно плохо работают друг с другом(там вроде есть какая-то фишка для совместимости, но я её не использую), попробуй все выключить и запустить только GoodbyeDPI(когда запустишь, перезапусти браузер, на всякий случай)

**Comment by Flowseal** [comment]
Читайте README полностью. Скачайте последнюю версию.
Далее вам сюда - https://github.com/Flowseal/zapret-discord-youtube/discussions/251
