### ISSUE TITLE
запускаю от имени администратора и не работает

### ISSUE THREAD

**Issue by slayme52** [Flowseal/zapret-discord-youtube#250]
Данный файл должен быть запущен с правами администратора (ПКМ - Запустить от имени администратора).
Нажмите любую клавишу, чтобы продолжить создание сервиса.
Press any key to continue . . .
(((

**Comment by MiKhanreld** [comment]
Та же проблема, все отключал, делал по новой все как в инструкции. Отдельно Kyber и QUIC в default приводил. Ничего не помогает. При этом всем, плашка "Запуск от имени Администратора" имеется и прожимается, однако проблема та же вылезает.

**Comment by Flowseal** [comment]
> Данный файл должен быть запущен с правами администратора (ПКМ - Запустить от имени администратора). Нажмите любую клавишу, чтобы продолжить создание сервиса. Press any key to continue . . . (((

Это лишь предупреждение. Оно не проверяет, действительно ли файл запущен от имени администратора
