### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Chmonya-0** [Flowseal/zapret-discord-youtube#254]
Вчера пытался пофиксить это но даже когда включен дискорд просто ищет обновления и все
(открываю батник Discord от админа)

**Comment by Flowseal** [comment]
Скачайте новую версию.
Далее вам сюда - https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by Chmonya-0** [comment]
я скачал, не помогло

**Comment by Chmonya-0** [comment]
хорошо
