### ISSUE TITLE
П

### ISSUE THREAD

**Issue by Findi7** [Flowseal/zapret-discord-youtube#256]
Р

**Comment by Vadikimax3d** [comment]
>пук среньк

Дядя, научись документацию читать.

**Comment by ColdWindOfChange** [comment]
> > пук среньк
> 
> Дядя, научись документацию читать.

На самом деле, просто сразу видно, что автор поста каникульный дурик, который не понимает ничего в стэке технологий, которые автор скрипта использовал)
Таким лишь бы обвинить других в том, что у них руки не из плеч растут)

**Comment by jestxfot** [comment]
Удалите проблему, спам.
