### ISSUE TITLE
огромный пинг

### ISSUE THREAD

**Issue by eroomr** [Flowseal/zapret-discord-youtube#26]
при использовании этой проги в дискорде люто подскакивает пинг, без проги было около 40ms с прогой 400+ в среднем. при этом же у моего друга пинг 70 с прогой стабильно.
![image](https://github.com/user-attachments/assets/8e83359b-42c4-4087-8dfe-aaeb533272d1)

**Comment by clkwow** [comment]
Инет хуйня

**Comment by Flowseal** [comment]
Скачайте последний релиз. Попробуйте отключить VPN и сторонние программы для тунеллинга

**Comment by clkwow** [comment]
> Скачайте последний релиз. Попробуйте отключить VPN и сторонние программы для тунеллинга

Ема ты официальный

**Comment by Flowseal** [comment]
![image](https://github.com/user-attachments/assets/8da24a64-fd43-41c2-a36c-39e4a1dda8e3)
