### ISSUE TITLE
Жалуются ли античиты на эту прогу?

### ISSUE THREAD

**Issue by Milkqr** [Flowseal/zapret-discord-youtube#263]
Жалуются ли античиты на эту прогу?

**Comment by Flowseal** [comment]
Call of Duty, DS3

**Comment by Milkqr** [comment]
А если я не установлю сервис и выключу прогу то это исправит проблему @Flowseal ?

**Comment by SashaChernay** [comment]
> А если я не установлю сервис и выключу прогу то это исправит проблему @Flowseal ?

Нет пошел нахуй

**Comment by SashaChernay** [comment]
> А если я не установлю сервис и выключу прогу то это исправит проблему @Flowseal ?

Нет, скачивай на здоровье
