### ISSUE TITLE
не работает дискорд после запуска сервисов

### ISSUE THREAD

**Issue by ZWL-Decro** [Flowseal/zapret-discord-youtube#265]

**Comment by Seruios** [comment]
У меня тоже. По какой-то причине работает на ноуте с Windows 10, но на другом ноуте с Windows 11 то же самое не работает. В чем может быть проблема?

**Comment by Seruios** [comment]
Даже не так. На другом ноуте с Win 11 так же Заработал! 🤔 А вот у меня нет.. почему так?

**Comment by Dunkon** [comment]
@Seruios у тебя включен goodbyedpi? Если есть - выключи, они конфликтуют.  
Открой диспетчер задач, посмотри в сервисах, он там будет, если включен.

**Comment by Seruios** [comment]
> @Seruios у тебя включен goodbyedpi? Если есть - выключи, они конфликтуют. Открой диспетчер задач, посмотри в сервисах, он там будет, если включен.

@Dunkon 
Спасибо огромное. Что-то конфликтовало, но точно что, не понял. Я в диспетчере задач всё лишнее выключил для теста - и заработало.
