### ISSUE TITLE
Не грузятся демки/долгое подключение к войсу

### ISSUE THREAD

**Issue by lemonvomit** [Flowseal/zapret-discord-youtube#266]
Ростелеком, Россия

Обновилась до последней версии обходника. В войс пускает через пару минут. (До этого идет подключение к RTC-не установлен маршрут и так пока не подключусь). Но есть проблема-демки не грузятся. вообще. Сначала долгая загрузка-далее "вы были отключены".
Вчера писала с такой же проблемой, думала мб че изменится сегодня. Вчера просто помогло большое ожидание, демка к вечеру сидения в войсе стала работать(на удивление). Но все равно не хочется ждать когда это "чудо" случится, ведь демки мне в большинстве случаев нужны. 

Сижу на стандартном коде 1.3.0 на данный момент, ничего не меняя в коде. (До этого никакие изменения не помогали на старой версии или вовсе вели к не открытию программы)
Мб у кого-то будет рабочий батник для работы этого всего или есть решение, буду рада.

**Comment by Flowseal** [comment]
Can't reproduce
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
