### ISSUE TITLE
Service goodbye discord ОТСУТСТВУЕТ В РЕЛИЗЕ

### ISSUE THREAD

**Issue by lynrayy** [Flowseal/zapret-discord-youtube#27]
![image](https://github.com/user-attachments/assets/285d6b41-4667-4ade-b8cd-8632dd6b48d5)
Этого нет в релизе

![image](https://github.com/user-attachments/assets/3db30f69-f458-4685-a074-73352009c56a)

**Comment by clkwow** [comment]
Да и пох на него

**Comment by lynrayy** [comment]
Всмысле "ПОХ"? У меня гудбай дипиай стоит, мне надо что бы и то и другое работало

**Comment by clkwow** [comment]
https://github.com/Flowseal/zapret-discord-youtube/blob/main/service_goodbye_discord.bat на

**Comment by hc2hunter** [comment]
> Всмысле "ПОХ"? У меня гудбай дипиай стоит, мне надо что бы и то и другое работало

а service_discord.bat вы никак сами не догадываетесь запустить?
но вообще, скажу из опыта, что zapret и goodbydpi вместе могут не работать. они в памяти конфликтуют. скорее всего дискорд будет работать, а ютуб нет.
ждем решения скорее всего за пару дней что-то напилят...

**Comment by clkwow** [comment]
> > Всмысле "ПОХ"? У меня гудбай дипиай стоит, мне надо что бы и то и другое работало
> 
> а service_discord.bat вы никак сами не догадываетесь запустить? но вообще, скажу из опыта, что zapret и goodbydpi вместе могут не работать. они в памяти конфликтуют. скорее всего дискорд будет работать, а ютуб нет. ждем решения скорее всего за пару дней что-то напилят...

Это другое обалдуй

**Comment by comrad-e** [comment]
Удали старый гудбай, запусти service_discord_youtube.bat и работать будет и ютуб, и дискорд

**Comment by Flowseal** [comment]
Скачайте последний релиз - https://github.com/Flowseal/zapret-discord-youtube/releases/tag/1.1.0

**Comment by clkwow** [comment]
> Удали старый гудбай, запусти service_discord_youtube.bat и работать будет и ютуб, и дискорд

Поздно

**Comment by lynrayy** [comment]
> а service_discord.bat вы никак сами не догадываетесь запустить?

Я про итогу запустил и все работает. Просто не хочется лишний раз запускать что-то наугад, и так всё это заебало уже. То установи, это установи, половина не работает вообще. Лишние телодвижения не нужны
