### ISSUE TITLE
Провайдер МТС Windows 11

### ISSUE THREAD

**Issue by Raftaliaa** [Flowseal/zapret-discord-youtube#270]
Дискорд отказывается поключаться к голосовым каналам от слова совсем, Менял конфиги, менял ipv4, подключаться к войсу вообще не хочет, накинь идей что еще попробовать можно пжпж :')

**Comment by Bubildo** [comment]
У меня тоже дискорд перестал в войсе работать с запретом. Также очень вредничает с запуском дискорда

**Comment by Bubildo** [comment]
А, забейте, я дурак. Не увидел 1.3.0 версию

**Comment by Raftaliaa** [comment]
> А, забейте, я дурак. Не увидел 1.3.0 версию

У меня вчера 1.2.0 версия в пк клубе работала, а на ноуте вышеуказанном вообще работать отказывается(

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
