### ISSUE TITLE
![изображение_2024-10-14_011034041](https://github.com/user-attachments/assets/f5eaee20-47ef-43e2-b045-2033d181af3e)

### ISSUE THREAD

**Issue by Badnoff** [Flowseal/zapret-discord-youtube#272]
![изображение_2024-10-14_011034041](https://github.com/user-attachments/assets/f5eaee20-47ef-43e2-b045-2033d181af3e)
это майнер или что это?)

_Originally posted by @Badnoff in https://github.com/Flowseal/zapret-discord-youtube/discussions/252#discussioncomment-10930919_

**Comment by Dronatar** [comment]
Ссылка на кошелек создателей WinDivert
