### ISSUE TITLE
14.10.2024 перестал работать youtube

### ISSUE THREAD

**Issue by MadPeachTM** [Flowseal/zapret-discord-youtube#274]
Ранее все работало прекрасно, пробовал переставить service, но не помогло

Еще небольшая странность, почему то больше окошко не появляется, если discord_youtube.bat запускать (хотя при переустановке service я вижу, что там обрубается сервис + работает discord, т.е. прога работает)

не уверен, что еще дописать. есть у кого идеи в чем дело?

**Comment by Wh1teRover** [comment]
У меня была такая штука, когда я пытался добавить сервис в автозапуск, после этого все очень странно начинало себя вести. Помогало удаление сервиса из автозагрузки скриптом и перезагрузка компьютера. Как это полечить не костыльно - пока не понял.

**Comment by cvstt** [comment]
Мне помогло скачать обновлённую версию. Можно скачать её и если не работает, то всё ещё можно отталкиваться от этого.

**Comment by MadPeachTM** [comment]
> Мне помогло скачать обновлённую версию. Можно скачать её и если не работает, то всё ещё можно отталкиваться от этого.

спасибо, это помогло. не увидел, что вышла новая версия
