### ISSUE TITLE
Не работают все батники

### ISSUE THREAD

**Issue by shi-moro** [Flowseal/zapret-discord-youtube#28]
При попытке запустить обычные батники (не сервисы) ничего не происходит, нет ошибок в консоли, при этом в процессах пусто.

```
D:\ZapretDiscord>start "zapret: discord" /min "D:\ZapretDiscord\winws.exe" --wf-tcp=443 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="D:\ZapretDiscord\list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="D:\ZapretDiscord\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="D:\ZapretDiscord\quic_initial_www_google_com.bin" --new --filter-tcp=443 --hostlist="D:\ZapretDiscord\list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="D:\ZapretDiscord\tls_clienthello_www_google_com.bin"
```

При попытке запустить батники-сервисы в консоли ошибка 1060 служба не установлена

```
D:\ZapretDiscord>set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=443 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="D:\ZapretDiscord\list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="D:\ZapretDiscord\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="D:\ZapretDiscord\quic_initial_www_google_com.bin" --new --filter-tcp=443 --hostlist="D:\ZapretDiscord\list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="D:\ZapretDiscord\tls_clienthello_www_google_com.bin"

D:\ZapretDiscord>set SRVCNAME=zapret

D:\ZapretDiscord>net stop "zapret"
Неправильное имя службы.

Для вызова дополнительной справки наберите NET HELPMSG 2185.


D:\ZapretDiscord>sc delete "zapret"
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.


D:\ZapretDiscord>sc create "zapret" binPath= "\"D:\ZapretDiscord\winws.exe\" --wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=443 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="D:\ZapretDiscord\list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="D:\ZapretDiscord\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="D:\ZapretDiscord\quic_initial_www_google_com.bin" --new --filter-tcp=443 --hostlist="D:\ZapretDiscord\list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="D:\ZapretDiscord\tls_clienthello_www_google_com.bin"" DisplayName= "zapret DPI bypass : winws1" start= auto
[SC] CreateService: ошибка: 5:

Отказано в доступе.


D:\ZapretDiscord>sc description "zapret" "zapret DPI bypass software"
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.


D:\ZapretDiscord>sc start "zapret"
[SC] StartService: OpenService: ошибка: 1060:

Указанная служба не установлена.
```

**Comment by Flowseal** [comment]
Скачайте последний релиз. Запускайте от имени администратора

**Comment by shi-moro** [comment]
> Скачайте последний релиз. Запускайте от имени администратора

я скачал последний релиз, запускаю от имени администратора. попробовал в том числе обновить бинарники с оригинального репозитория. не работает

**Comment by clkwow** [comment]
Какой файл ты открываешь?

**Comment by Flowseal** [comment]
> > Скачайте последний релиз. Запускайте от имени администратора
> 
> я скачал последний релиз, запускаю от имени администратора. попробовал в том числе обновить бинарники с оригинального репозитория. не работает

Судя по логам, это не последний релиз. Последний релиз вышел 10 минут назад. 
[FAQ](https://github.com/Flowseal/zapret-discord-youtube?tab=readme-ov-file#%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82)

**Comment by comrad-e** [comment]
![image](https://github.com/user-attachments/assets/390a42a6-0839-4a82-a404-9842791ce514)
запускаю от админа

**Comment by Flowseal** [comment]
> ![image](https://private-user-images.githubusercontent.com/63198931/374976976-390a42a6-0839-4a82-a404-9842791ce514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODA1NDMsIm5iZiI6MTcyODQ4MDI0MywicGF0aCI6Ii82MzE5ODkzMS8zNzQ5NzY5NzYtMzkwYTQyYTYtMDgzOS00YTgyLWE0MDQtOTg0Mjc5MWNlNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzMjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0N2YzN2JmNWJlYzNlMDA5NmZjMjhjM2Q0NjRkMDdjNTg2ODBmMzNhMDU5MWQ5NzUxYTliYTAwNWM1NmNlODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LDiQvBS7g-HJ3CqI5EozNUE2kQPvZg6ERopM-IZpfks) запускаю от админа

У вашего пользователя Windows всё ещё не хватает прав, чтобы создать сервис. 
Можете почитать решения тут - https://remontka.pro/system-error-5-access-is-denied/

**Comment by shi-moro** [comment]
> Судя по логам, это не последний релиз. Последний релиз вышел 10 минут назад. [FAQ](https://github.com/Flowseal/zapret-discord-youtube?tab=readme-ov-file#%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82)

не знал, что он вышел так недавно. скачал его. ситуация не изменилась.

когда запускаю, например, discord.bat в консоли вообще пусто. ничего не происходит, нет ошибок, в процессах пусто.

когда запускаю, например service_discord.bat, в консоли по-прежнему ошибка 1060, в процессах и службах пусто. гудбай если что не запущен:

```
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService FAILED 5:

Access is denied.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] StartService: OpenService FAILED 1060:

The specified service does not exist as an installed service.

Press any key to continue . . .
```

**Comment by comrad-e** [comment]
> > ![image](https://private-user-images.githubusercontent.com/63198931/374976976-390a42a6-0839-4a82-a404-9842791ce514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODA1NDMsIm5iZiI6MTcyODQ4MDI0MywicGF0aCI6Ii82MzE5ODkzMS8zNzQ5NzY5NzYtMzkwYTQyYTYtMDgzOS00YTgyLWE0MDQtOTg0Mjc5MWNlNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzMjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0N2YzN2JmNWJlYzNlMDA5NmZjMjhjM2Q0NjRkMDdjNTg2ODBmMzNhMDU5MWQ5NzUxYTliYTAwNWM1NmNlODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LDiQvBS7g-HJ3CqI5EozNUE2kQPvZg6ERopM-IZpfks) запускаю от админа
> 
> У вашего пользователя Windows всё ещё не хватает прав, чтобы создать сервис. Можете почитать решения тут - https://remontka.pro/system-error-5-access-is-denied/

![image](https://github.com/user-attachments/assets/3448003b-528c-409b-8a56-fd9ed97356d1)

**Comment by Flowseal** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/63198931/374976976-390a42a6-0839-4a82-a404-9842791ce514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODA1NDMsIm5iZiI6MTcyODQ4MDI0MywicGF0aCI6Ii82MzE5ODkzMS8zNzQ5NzY5NzYtMzkwYTQyYTYtMDgzOS00YTgyLWE0MDQtOTg0Mjc5MWNlNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzMjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0N2YzN2JmNWJlYzNlMDA5NmZjMjhjM2Q0NjRkMDdjNTg2ODBmMzNhMDU5MWQ5NzUxYTliYTAwNWM1NmNlODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LDiQvBS7g-HJ3CqI5EozNUE2kQPvZg6ERopM-IZpfks) запускаю от админа
> > 
> > 
> > У вашего пользователя Windows всё ещё не хватает прав, чтобы создать сервис. Можете почитать решения тут - https://remontka.pro/system-error-5-access-is-denied/
> 
> ![image](https://private-user-images.githubusercontent.com/63198931/374979106-3448003b-528c-409b-8a56-fd9ed97356d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODA5MjIsIm5iZiI6MTcyODQ4MDYyMiwicGF0aCI6Ii82MzE5ODkzMS8zNzQ5NzkxMDYtMzQ0ODAwM2ItNTI4Yy00MDliLThhNTYtZmQ5ZWQ5NzM1NmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzMzAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNjQ2NDVlYTEzNjViMTJjODlhODZmNDUxZWRlMTNkMThmMDY1YzM2MjZkM2E4NjY4MGIyYTBmZjEzM2YxZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DCEwrrQICnd5aaWw2B0y_mxc3sEksYbUYNw2YwzGU00)

Конечно, можете попробовать убрать проверку на админа, изменив батник, но прав больше у вас для создания сервиса не станет

**Comment by Flowseal** [comment]
> [SC] CreateService FAILED 5:
> 
> Access is denied.

@shi-moro у вас недостаточно прав для создаия сервиса

**Comment by shi-moro** [comment]
> CreateService FAILED 5:
> 
> Access is denied.

а почему нет проблем с созданием службы гудбай? и в целом созданием любой службы. проблема только с этой

**Comment by Shurik244** [comment]
> ![image](https://private-user-images.githubusercontent.com/63198931/374976976-390a42a6-0839-4a82-a404-9842791ce514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODEwNjcsIm5iZiI6MTcyODQ4MDc2NywicGF0aCI6Ii82MzE5ODkzMS8zNzQ5NzY5NzYtMzkwYTQyYTYtMDgzOS00YTgyLWE0MDQtOTg0Mjc5MWNlNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMTY1MTI1NDA4MWYzYTdlNjE5NmIyZmY3MDZkMjMyMDJkZGZlMDJjZDg5NWMwNTZmMmU1MDBlN2RlNzQxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Cqc5plB-Wv_95lyCUYCtdiMnMatihQ31Z-BmH_aEdtk) запускаю от админа

Я предпологаю что у вас Win10, попробуйте отказаться от использования кастомного терминала, используйте оригинальный

За этой программой замечено странное поведение, у некоторых консоль с правами админа оказывается без прав админа, бывают случае когда вовсе при попытке запустить с правами админа, ничего не происходит

**Comment by comrad-e** [comment]
> 
> Я предпологаю что у вас Win10, попробуйте отказаться от использования кастомного терминала, используйте оригинальный

Win11, терминал родной

**Comment by Flowseal** [comment]
Попроуйте изменить проверку на права админа следующим образом:
```
:: Admin rights check
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo Скрипт запущен без прав администратора. 
    echo Нажмите любую клавишу, чтобы попробовать запустить файл от имени администратора.
    pause
    powershell start -verb runas '%0'
    exit /b
)
```
@comrad-e @shi-moro 
Сообщите, пожалуйста, о результатх 🙂

**Comment by comrad-e** [comment]
> Попроуйте изменить проверку на права админа следующим образом:
> 

После нажатия на клавишу окно перезапускается с тем же текстом

**Comment by Flowseal** [comment]
> > Попроуйте изменить проверку на права админа следующим образом:
> 
> После нажатия на клавишу окно перезапускается с тем же текстом

А без проверки на админа в целом, сервис создаётся или ошибка?

**Comment by comrad-e** [comment]
> 
> А без проверки на админа в целом, сервис создаётся или ошибка?

Удалил блок проверки, но возможно это не правильно)
![image](https://github.com/user-attachments/assets/7e6c20e7-37cb-4793-ae0a-3c11f16da39d)

**Comment by Flowseal** [comment]
> > А без проверки на админа в целом, сервис создаётся или ошибка?
> 
> Удалил блок проверки, но возможно это не правильно) ![image](https://private-user-images.githubusercontent.com/63198931/374988394-7e6c20e7-37cb-4793-ae0a-3c11f16da39d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODI1NzUsIm5iZiI6MTcyODQ4MjI3NSwicGF0aCI6Ii82MzE5ODkzMS8zNzQ5ODgzOTQtN2U2YzIwZTctMzdjYi00NzkzLWFlMGEtM2MxMWYxNmRhMzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEzNTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNmY0MTM5MjY4MTUyY2MyNjFhNDA1ZGRlN2E1MzcwN2ZhODUxNDJhNTg4ODRmMTk5MWRkZDhkYjRiNTYwNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JsA3nUxvLYeND5AaNeEBFXneS9MKfWzrL5iO9Pq3Uz0)

Спасибо за фидбек

**Comment by Flowseal** [comment]
@comrad-e 
Можете использовать последний релиз - https://github.com/Flowseal/zapret-discord-youtube/releases/tag/1.1.1

**Comment by comrad-e** [comment]
> @comrad-e можете использовать последний релиз - https://github.com/Flowseal/zapret-discord-youtube/releases/tag/1.1.1

![image](https://github.com/user-attachments/assets/00fd4493-98a7-4964-9cfc-a8a6f58bad79)

**Comment by comrad-e** [comment]
Но служба создалась)))

**Comment by shi-moro** [comment]
> Попроуйте изменить проверку на права админа следующим образом:
> 
> ```
> :: Admin rights check
> net session >nul 2>&1
> if %errorLevel% neq 0 (
>     echo Скрипт запущен без прав администратора. 
>     echo Нажмите любую клавишу, чтобы попробовать запустить файл от имени администратора.
>     pause
>     powershell start -verb runas '%0'
>     exit /b
> )
> ```
> 
> @comrad-e @shi-moro Сообщите, пожалуйста, о результатх 🙂

не мой случай оказался, но я разобрался.
я заподозрил неладное и решил прочекать, вдруг проблема в какой-то другой проге, т.к. иногда это может быть вина антивирусов например. однако ими я не пользуюсь. но пользуюсь прогой для чистки компа от мусора, у которой есть доп.функция защиты от подозрительных действий. так вот ей по какой-то причине видимо не понравилось создание этой службы. стоило ее оффнуть, все заработало.
с гудбаем такого не было, так что я не уверен, почему так вышло, но да

**Comment by cjla8ok** [comment]
жалуется на не подписанный  драйвер и не  хочет запускаться из меню в  службах. И батники не открывает с  ошибкой 1060
