### ISSUE TITLE
При включение ПК очень долгая загрузка Windows.

### ISSUE THREAD

**Issue by typeopozitive** [Flowseal/zapret-discord-youtube#281]
Вчера установил приложение, сделал автозапуск при включении ПК - чтобы программа работала.

На следующий день включаю ПК, включается нормально, но очень сильно тормозит. Перезагрузил его и жду загрузку Windows.

Upd Я многократно перезагружал его. Сейчас вхожу в безопасный режим и так же бесконечная загрузка.

**Comment by Flowseal** [comment]
Возможно, вы скачали что-то с фейк репозитория либо заразились где-то ещё. Помочь не могу, к сожалению.

**Comment by typeopozitive** [comment]
Я скачал с вашего гит хаба 2.000+ звёздочек.
Другу скинул Точно такой же файл у него все нормально.
