### ISSUE TITLE
🟣 Обход Discord

### ISSUE THREAD

**Issue by chofirka** [Flowseal/zapret-discord-youtube#282]
помогите, что делать если раньше ( до использования этого обхода ) интернет был по 100-120 mbps на сайте, и на ютуб откат загружался за пару минут.
но после скачивания обхода на сайте теперь я отображаюсь как в лондоне, скорость упала до критических 50-70 mbps, и видео на ют грузяться по минут 40.
планирую вообще винду сносить полностью, потому что я уже пробовал удалять как сами файлы, так и так как написано в описании через файлик, ничего не помогает

**Comment by Flowseal** [comment]
ip не подменяется в данном методе. Вероятно, вы используете что-то ещё.
