### ISSUE TITLE
Идея

### ISSUE THREAD

**Issue by alexshab163** [Flowseal/zapret-discord-youtube#284]
Есть ли возможность написать код так, что бы этот обход изменял пакеты по полю destination?
Типа предназначенное мы меняем, а все остальное пофиг, аля split-tunneling

**Comment by Flowseal** [comment]
> Есть ли возможность написать код так, что бы этот обход изменял пакеты по полю destination? Типа предназначенное мы меняем, а все остальное пофиг, аля split-tunneling

Почитайте как работают стратегии. А дальше --hostlist и --hostlist-exclude вам в помощь
https://github.com/bol-van/zapret
