### ISSUE TITLE
Не могу говорить в голосовом в дискорде

### ISSUE THREAD

**Issue by DanWindo** [Flowseal/zapret-discord-youtube#286]
Дискорд работает, но при заходе на рандомный чат идёт бесконечное подключение. Как решить проблему?

**Comment by DanWindo** [comment]
Я только сейчас понял, что он только для прочитывание, но про голосовой чат речи нету. Или есть?

**Comment by Flowseal** [comment]
Есть. 
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
