### ISSUE TITLE
Не работает войс, все перепробовал!

### ISSUE THREAD

**Issue by VanyaSfinkter** [Flowseal/zapret-discord-youtube#293]
Дискорд запускается и работает все кроме голосовых каналов. Бесконечное подключение RTC, затем перезаходит в войс. Попробовал решения из #252 , не помогло. Полистал другие обсуждения, но там нет ответов. Я уже убирал ,split , отключал сервисы впн киллер чек пойнт, --dpi-desync-autottl по разному заменял, тоже не помогло, GoodbieDPI никогда не скачивал (ибо ютуб и без всего этого как работал так и работает), пытался менять текст в discord.bat, но теперь он вообще перестал запускаться (надеюсь я просто делаю что-то не так). Я уже не знаю что делать, помогите!

**Comment by exzolink** [comment]
> Дискорд запускается и работает все кроме голосовых каналов. Бесконечное подключение RTC, затем перезаходит в войс. Попробовал решения из #252 , не помогло. Полистал другие обсуждения, но там нет ответов. Я уже убирал ,split , отключал сервисы впн киллер чек пойнт, --dpi-desync-autottl по разному заменял, тоже не помогло, GoodbieDPI никогда не скачивал (ибо ютуб и без всего этого как работал так и работает), пытался менять текст в discord.bat, но теперь он вообще перестал запускаться (надеюсь я просто делаю что-то не так). Я уже не знаю что делать, помогите!

Для войса нужно крутить настройки в строке после --filter-udp=50000-65535

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
