### ISSUE TITLE
Проблеме

### ISSUE THREAD

**Issue by T3TRAF1ST** [Flowseal/zapret-discord-youtube#295]
![Скриншот 15-10-2024 111705](https://github.com/user-attachments/assets/a7974958-6249-4633-9828-4a35624e0ffa)
помогите

**Comment by T3TRAF1ST** [comment]
у моего друга схожая проблема, при попытке включить обход, выскакивает это

**Comment by thisVioletHydra** [comment]
> ![Скриншот 15-10-2024 111705](https://private-user-images.githubusercontent.com/184729448/376519418-a7974958-6249-4633-9828-4a35624e0ffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTIxMzAsIm5iZiI6MTcyOTAxMTgzMCwicGF0aCI6Ii8xODQ3Mjk0NDgvMzc2NTE5NDE4LWE3OTc0OTU4LTYyNDktNDYzMy05ODI4LTRhMzU2MjRlMGZmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxNzAzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDdmYmZhNmIyZDQ1MjA5YTcwMGYzNmFlZjk4ZDc3ZWNhMjM2YTBhMjI4MGMwNDcxNGRhNjE1ZGM5YmNkZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jcZqHV-VQw6e7cJRvbPJ2GkmgjKpqVm5vcZjQxET9xc) помогите

![image](https://github.com/user-attachments/assets/c6c65051-5c5d-47d6-9bc8-a20b91eb7eef)
ты свой путь видел?

**Comment by T3TRAF1ST** [comment]
> > ![Скриншот 15-10-2024 111705](https://private-user-images.githubusercontent.com/184729448/376519418-a7974958-6249-4633-9828-4a35624e0ffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTIxMzAsIm5iZiI6MTcyOTAxMTgzMCwicGF0aCI6Ii8xODQ3Mjk0NDgvMzc2NTE5NDE4LWE3OTc0OTU4LTYyNDktNDYzMy05ODI4LTRhMzU2MjRlMGZmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxNzAzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDdmYmZhNmIyZDQ1MjA5YTcwMGYzNmFlZjk4ZDc3ZWNhMjM2YTBhMjI4MGMwNDcxNGRhNjE1ZGM5YmNkZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jcZqHV-VQw6e7cJRvbPJ2GkmgjKpqVm5vcZjQxET9xc) помогите
> 
> ![image](https://private-user-images.githubusercontent.com/11839238/376716475-c6c65051-5c5d-47d6-9bc8-a20b91eb7eef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODQzMzMsIm5iZiI6MTcyOTA4NDAzMywicGF0aCI6Ii8xMTgzOTIzOC8zNzY3MTY0NzUtYzZjNjUwNTEtNWM1ZC00N2Q2LTliYzgtYTIwYjkxZWI3ZWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEzMDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZjYxNjljZmZjNGUyNmExY2U5YzBjNWM1ZmI0MDliOWQzMDQ5OTY1NGI5Y2RlOTc5ZWJjZjZlNTljZjhlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AptqTYsjcdwjv_hh5Dbj6FySnVdbl1iVkJYWkawzii0) ты свой путь видел?

а что не так, я просто во всём этом не разбираюсь)

**Comment by T3TRAF1ST** [comment]
аааа
до меня ток щас дошло

**Comment by T3TRAF1ST** [comment]
я исправил проблему с русским текстом, но проблема никуда не исчезла

**Comment by T3TRAF1ST** [comment]
я смог решить проблему самостоятельно, достаточно было просто переустановить новую  версию фикса
