### ISSUE TITLE
Discord опять помер.

### ISSUE THREAD

**Issue by Dudedjon00** [Flowseal/zapret-discord-youtube#296]
Youtube работает, а дис крутит апдейты, хотя вчера ночью работал.

**Comment by Vatmiras** [comment]
у меня наоборот дискорд работает, а ютуб нет подключения к интернету МТС, ночью все работало

**Comment by Andrewin1Dark** [comment]
Сносите старые службы и качайте последнюю версию запрета. Мне помогло.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
