### ISSUE TITLE
Firefox 131.0 youtube загрузка.

### ISSUE THREAD

**Issue by Uoipka** [Flowseal/zapret-discord-youtube#3]
Немного не к месту, но может есть какая-то информация по поводу того что ютуб не грузит (само видео) на Лисе через запрет на Win10? 
Что через пресет с пака запрета, что через текущий, на Edge все нормально работает, причем Kyber/Http3 отключены и через безопасный режим / инкогнито тоже самое.

**Comment by Flowseal** [comment]
Информацией не обладаю. Попробуйте найти ответы в репозитория goodbyedpi/zapret
