### ISSUE TITLE
Нестабильная работа Discord

### ISSUE THREAD

**Issue by DanaScully2** [Flowseal/zapret-discord-youtube#301]
Не всегда подключает к голосовому каналу. Чаще всего останавливается на этапе "Подключение". Помогает переподключение к каналу без перезагрузки программы. Обычно требуется от одного, до 10 ручных переподключений, чтобы зайти в голосовой

**Comment by Flowseal** [comment]
Пробуйте изменять стратегию.
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
