### ISSUE TITLE
Discord не подключает в войс

### ISSUE THREAD

**Issue by DmitriyBorodin** [Flowseal/zapret-discord-youtube#309]
![Screenshot_275](https://github.com/user-attachments/assets/9d4e3258-5ed0-4af6-b5c2-931af3ad97fe)

Сам дискорд запускается, но в войс не коннектит, хотя на прошлой неделе работало

**Comment by Flowseal** [comment]
Я обновил программу до 1.4.0, попробуйте. 
Дальше сюда - https://github.com/Flowseal/zapret-discord-youtube/discussions/252
