### ISSUE TITLE
Не работает туннелирование WARP после удаления сервиса.

### ISSUE THREAD

**Issue by korobk1n** [Flowseal/zapret-discord-youtube#314]
Поставил вчера Запрет для того что бы не сидеть через туннель ВАРПа из-за высокой нагрузки вечером. С утра решил по-старинке подключить туннель обратно, однако столкнулся с проблемой, что даже после удаления сервиса, нескольких перезагрузок и сбросов параметров сети туннель не работает. Команды `driverquery | find "Divert"` и `sc stop WinDivert` `sc delete WinDivert` так же не дают никакого результата. Если уже кто-то сталкивался с этим - дайте знать как вы решили эту проблему если вовсе решили.

**Comment by FRGZ1** [comment]
Здравствуй, сегодня утром у меня тоже умер WARP, даже несмотря на то, что я не пользовался Zapret'ом. Так что я думаю, дело не в нем. В конфиге варпа менял endpoint'ы - не помогло, буду ждать решения от других пользователей

**Comment by Flowseal** [comment]
Неработающий Warp не связан с zapret.
Перегенирируйте конфиг
Эндпоинт замените на engage.cloudflareclient.com:2408

**Comment by sellsfortune** [comment]
Добрый вечер всем! У меня перестал скачиваться конфиг, после того как я его пару раз перегинероровала. Что делать?
