### ISSUE TITLE
Discord с zapret не работает через кабель Ethernet, работает через Wi-Fi

### ISSUE THREAD

**Issue by dancyuser** [Flowseal/zapret-discord-youtube#315]
Добрый день!

Столкнулся со следующей проблемой:
- при подключении через Wi-Fi, zapret обходит запрет, в т.ч. на голосовой чат
- но при подключении через кабель Ethernet, zapret перестает обходить запрет, и только один конфиг дает доступ к Discord, без голосового чата

Вопрос: что нужно сделать, чтобы zapret отрабатывал и через кабель?

Что пробовал: перезапуск сервиса, удаление и установка сервиса заново, перебор конфигураций, перезагрузка компьютера.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
Читайте советы

**Comment by MaksimNohrin** [comment]
Кто столкнется с таким же, если сетевая карта Killer, в службах отключайте все что начинается с Killer. Мне помогло.

**Comment by ZlayaZaplya** [comment]
Помогло обнволение сетевого дравйера с помощью SDI

**Comment by Xaruso** [comment]
Мне помогло решение от MaksimNohrin действительно просто отключил в службах Killer и готово
