### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by DieInCalamity** [Flowseal/zapret-discord-youtube#318]
я типо запускаю(пробовал как от имени админа так и без) на секунду командная строка и закрывается сразу что делать? Никакие впн не включены

**Comment by advokat11** [comment]
1. попробуй открыть bat'ник с командной строки
2. проверь что у тебя не включается еще одна командная строка с желтым значком, по идее так и должно быть

**Comment by DieInCalamity** [comment]
> 1. попробуй открыть bat'ник с командной строки
> 2. проверь что у тебя не включается еще одна командная строка с желтым значком, по идее так и должно быть

попробовал с командной строки, тоже самое
ниче не открывается
что делать?

**Comment by advokat11** [comment]
> > 1. попробуй открыть bat'ник с командной строки
> > 2. проверь что у тебя не включается еще одна командная строка с желтым значком, по идее так и должно быть
> 
> попробовал с командной строки, тоже самое
> ниче не открывается
> что делать?

Так вывод то пришли

**Comment by DieInCalamity** [comment]
> > > 1. попробуй открыть bat'ник с командной строки
> > > 2. проверь что у тебя не включается еще одна командная строка с желтым значком, по идее так и должно быть
> > 
> > 
> > попробовал с командной строки, тоже самое
> > ниче не открывается
> > что делать?
> 
> Так вывод то пришли

там ничего, просто краш

**Comment by advokat11** [comment]
> > > > 1. попробуй открыть bat'ник с командной строки
> > > > 2. проверь что у тебя не включается еще одна командная строка с желтым значком, по идее так и должно быть
> > > 
> > > 
> > > попробовал с командной строки, тоже самое
> > > ниче не открывается
> > > что делать?
> > 
> > Так вывод то пришли
> 
> там ничего, просто краш

Значит видос снимай

**Comment by Sofutikku** [comment]
точно такая же проблема
![image](https://github.com/user-attachments/assets/46e95c9f-eb09-468e-8edc-757a78c5315c)
и больше ничего нет

**Comment by Sofutikku** [comment]
если запустить service_remove.bat то это
![image](https://github.com/user-attachments/assets/6135997f-a8ab-4f02-8c81-9d29f91e1b2d)

**Comment by advokat11** [comment]
> точно такая же проблема ![image](https://private-user-images.githubusercontent.com/156917595/377507505-46e95c9f-eb09-468e-8edc-757a78c5315c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzU0MjYsIm5iZiI6MTcyOTE3NTEyNiwicGF0aCI6Ii8xNTY5MTc1OTUvMzc3NTA3NTA1LTQ2ZTk1YzlmLWViMDktNDY4ZS04ZWRjLTc1N2E3OGM1MzE1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNDI1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWUxOTcxMjkxZjFlYmI2ZDM2ZThmOTY0OWE1OGUzOWE3ZDc3YmRhNGNlYjQ1M2QxMzYxNWU2Y2ViNDM0YjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Yi1yfIjx8w1f1HX9_XOotcNo9wDbNVPjAqts1aBZROw) и больше ничего нет

ну во первых желательно не содержать русских букв в пути 
во вторых тоже сними видос

**Comment by Sofutikku** [comment]
> > точно такая же проблема ![image](https://private-user-images.githubusercontent.com/156917595/377507505-46e95c9f-eb09-468e-8edc-757a78c5315c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzU0MjYsIm5iZiI6MTcyOTE3NTEyNiwicGF0aCI6Ii8xNTY5MTc1OTUvMzc3NTA3NTA1LTQ2ZTk1YzlmLWViMDktNDY4ZS04ZWRjLTc1N2E3OGM1MzE1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNDI1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWUxOTcxMjkxZjFlYmI2ZDM2ZThmOTY0OWE1OGUzOWE3ZDc3YmRhNGNlYjQ1M2QxMzYxNWU2Y2ViNDM0YjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Yi1yfIjx8w1f1HX9_XOotcNo9wDbNVPjAqts1aBZROw) и больше ничего нет
> 
> ну во первых желательно не содержать русских букв в пути во вторых тоже сними видос

видео просто с запуском?
или еще что то?

**Comment by advokat11** [comment]
> > > точно такая же проблема ![image](https://private-user-images.githubusercontent.com/156917595/377507505-46e95c9f-eb09-468e-8edc-757a78c5315c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzU0MjYsIm5iZiI6MTcyOTE3NTEyNiwicGF0aCI6Ii8xNTY5MTc1OTUvMzc3NTA3NTA1LTQ2ZTk1YzlmLWViMDktNDY4ZS04ZWRjLTc1N2E3OGM1MzE1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNDI1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWUxOTcxMjkxZjFlYmI2ZDM2ZThmOTY0OWE1OGUzOWE3ZDc3YmRhNGNlYjQ1M2QxMzYxNWU2Y2ViNDM0YjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Yi1yfIjx8w1f1HX9_XOotcNo9wDbNVPjAqts1aBZROw) и больше ничего нет
> > 
> > 
> > ну во первых желательно не содержать русских букв в пути во вторых тоже сними видос
> 
> видео просто с запуском? или еще что то?

Как ты скачиваешь с репы архив, распаковываешь (на диск С, в корень) и запускаешь, с командной строки. В видео должна быть видна панель задач.

**Comment by Sofutikku** [comment]
ой заработало, сори я еблан, надо было сразу в папку с английскими символами

**Comment by advokat11** [comment]
@DieInCalamity закрывай issue если проблем больше нет

**Comment by DieInCalamity** [comment]
> @DieInCalamity закрывай issue если проблем больше нет

да не работает, значит проблемы есть

**Comment by advokat11** [comment]
> > @DieInCalamity закрывай issue если проблем больше нет
> 
> да не работает, значит проблемы есть

проверь путь к батникам и запиши видос если не помогло
не должно быть русских букв и специальных символов

**Comment by DieInCalamity** [comment]
> advokat11

да он у меня в C:\zapret алё

**Comment by advokat11** [comment]
> > advokat11
> 
> да он у меня в C:\zapret алё

переставай так разговаривать с людьми, которые хотят тебе помочь

если командная строка на секунду запускается, а потом исчезает, значит она сообщает о какой-то ошибке, неправильных путях или вроде того. все таки попробуй выловить её вывод при запуске батника с командной строки, от имени администратора

**Comment by DieInCalamity** [comment]
> > > advokat11
> > 
> > 
> > да он у меня в C:\zapret алё
> 
> переставай так разговаривать с людьми, которые хотят тебе помочь
> 
> если командная строка на секунду запускается, а потом исчезает, значит она сообщает о какой-то ошибке, неправильных путях или вроде того. все таки попробуй выловить её вывод при запуске батника с командной строки, от имени администратора

а как через командную строку запустить

**Comment by DieInCalamity** [comment]
> > > advokat11
> > 
> > 
> > да он у меня в C:\zapret алё
> 
> переставай так разговаривать с людьми, которые хотят тебе помочь
> 
> если командная строка на секунду запускается, а потом исчезает, значит она сообщает о какой-то ошибке, неправильных путях или вроде того. все таки попробуй выловить её вывод при запуске батника с командной строки, от имени администратора

там ошибка не батника, там новая командная строка открывается и закрывается сразу же

**Comment by advokat11** [comment]
> > > > advokat11
> > > 
> > > 
> > > да он у меня в C:\zapret алё
> > 
> > 
> > переставай так разговаривать с людьми, которые хотят тебе помочь
> > если командная строка на секунду запускается, а потом исчезает, значит она сообщает о какой-то ошибке, неправильных путях или вроде того. все таки попробуй выловить её вывод при запуске батника с командной строки, от имени администратора
> 
> там ошибка не батника, там новая командная строка открывается и закрывается сразу же

1. В поиске набираешь cmd
2. Высвечивается командная строка, нажимаешь на нее правой кнопкой мыши и выбираешь запустить от имени администратора
3. С помощью команды "cd /d путь_к_запрету" перемещаешься в папку с запретом
4. Открываешь батник набрав его имя файла

**Comment by DieInCalamity** [comment]
> > > > > advokat11
> > > > 
> > > > 
> > > > да он у меня в C:\zapret алё
> > > 
> > > 
> > > переставай так разговаривать с людьми, которые хотят тебе помочь
> > > если командная строка на секунду запускается, а потом исчезает, значит она сообщает о какой-то ошибке, неправильных путях или вроде того. все таки попробуй выловить её вывод при запуске батника с командной строки, от имени администратора
> > 
> > 
> > там ошибка не батника, там новая командная строка открывается и закрывается сразу же
> 
> 1. В поиске набираешь cmd
> 2. Высвечивается командная строка, нажимаешь на нее правой кнопкой мыши и выбираешь запустить от имени администратора
> 3. С помощью команды "cd /d путь_к_запрету" перемещаешься в папку с запретом
> 4. Открываешь батник набрав его имя файла

я так уже делал, у меня там новое окно открывается командной строки и сразу закрывается

**Comment by Potatomate** [comment]
> > > > > advokat11
> > > > 
> > > > 
> > > > да он у меня в C:\zapret алё
> > > 
> > > 
> > > переставай так разговаривать с людьми, которые хотят тебе помочь
> > > если командная строка на секунду запускается, а потом исчезает, значит она сообщает о какой-то ошибке, неправильных путях или вроде того. все таки попробуй выловить её вывод при запуске батника с командной строки, от имени администратора
> > 
> > 
> > там ошибка не батника, там новая командная строка открывается и закрывается сразу же
> 
> 1. В поиске набираешь cmd
> 2. Высвечивается командная строка, нажимаешь на нее правой кнопкой мыши и выбираешь запустить от имени администратора
> 3. С помощью команды "cd /d путь_к_запрету" перемещаешься в папку с запретом
> 4. Открываешь батник набрав его имя файла

У меня тоже не работает, но я добавил в конце того батника паузу, чтобы он сразу не закрывался и запустил его. Вот что он мне выдает
![изображение_2024-10-17_221155943](https://github.com/user-attachments/assets/cb9842e6-b942-443d-ad64-42370d86d944)

**Comment by advokat11** [comment]
> > > > > > advokat11
> > > > > 
> > > > > 
> > > > > да он у меня в C:\zapret алё
> > > > 
> > > > 
> > > > переставай так разговаривать с людьми, которые хотят тебе помочь
> > > > если командная строка на секунду запускается, а потом исчезает, значит она сообщает о какой-то ошибке, неправильных путях или вроде того. все таки попробуй выловить её вывод при запуске батника с командной строки, от имени администратора
> > > 
> > > 
> > > там ошибка не батника, там новая командная строка открывается и закрывается сразу же
> > 
> > 1. В поиске набираешь cmd
> > 2. Высвечивается командная строка, нажимаешь на нее правой кнопкой мыши и выбираешь запустить от имени администратора
> > 3. С помощью команды "cd /d путь_к_запрету" перемещаешься в папку с запретом
> > 4. Открываешь батник набрав его имя файла
> 
> У меня тоже не работает, но я добавил в конце того батника паузу, чтобы он сразу не закрывался и запустил его. Вот что он мне выдает
> ![изображение_2024-10-17_221155943](https://github.com/user-attachments/assets/cb9842e6-b942-443d-ad64-42370d86d944)
> 

У вас отказывает в доступе в запуске сервиса.
Открывайте от имени администратора

И кстати вы запускаете батник регистрации сервиса, при успехе он и должен закрыться. Посмотрите потом в сервисах зарегался ли он под этим названием.

**Comment by Potatomate** [comment]
> > > > > > > advokat11
> > > > > > 
> > > > > > 
> > > > > > да он у меня в C:\zapret алё
> > > > > 
> > > > > 
> > > > > переставай так разговаривать с людьми, которые хотят тебе помочь
> > > > > если командная строка на секунду запускается, а потом исчезает, значит она сообщает о какой-то ошибке, неправильных путях или вроде того. все таки попробуй выловить её вывод при запуске батника с командной строки, от имени администратора
> > > > 
> > > > 
> > > > там ошибка не батника, там новая командная строка открывается и закрывается сразу же
> > > 
> > > 
> > > 
> > > 1. В поиске набираешь cmd
> > > 2. Высвечивается командная строка, нажимаешь на нее правой кнопкой мыши и выбираешь запустить от имени администратора
> > > 3. С помощью команды "cd /d путь_к_запрету" перемещаешься в папку с запретом
> > > 4. Открываешь батник набрав его имя файла
> > 
> > 
> > У меня тоже не работает, но я добавил в конце того батника паузу, чтобы он сразу не закрывался и запустил его. Вот что он мне выдает
> > ![изображение_2024-10-17_221155943](https://private-user-images.githubusercontent.com/155758755/377566320-cb9842e6-b942-443d-ad64-42370d86d944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODU3NzgsIm5iZiI6MTcyOTE4NTQ3OCwicGF0aCI6Ii8xNTU3NTg3NTUvMzc3NTY2MzIwLWNiOTg0MmU2LWI5NDItNDQzZC1hZDY0LTQyMzcwZDg2ZDk0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNzE3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2MzOWI3ZTQ0NjI1OTMxNWEyZTI0YTFkYzk2Yzk1ZjE1NWRhZmQ5NTY0YTczOTAzNTQyYTFlNGZjM2YwYjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q87yIrCJdt0OEMcYtNW9MCU5eQY3dPS8ck8L-_8-yI8)
> 
> У вас отказывает в доступе в запуске сервиса. Открывайте от имени администратора
> 
> И кстати вы запускаете батник регистрации сервиса, при успехе он и должен закрыться. Посмотрите потом в сервисах зарегался ли он под этим названием.

я в этом вопросе быдло, поэтому нуждаюсь в пояснениях. сервисы - это службы в диспетчере задач? Если да, то там сервис появился. Однако теперь основной батник стал сразу закрываться и перед закрытием просто выдавать свое содержимое, собсна скрин прилагаю
![изображение_2024-10-17_222312630](https://github.com/user-attachments/assets/c7109b74-d6ab-42ec-b5d6-7ea83a7c26f7)

**Comment by Eptiy** [comment]
> сервисы - это службы в диспетчере задач?

Да.

> Однако теперь основной батник стал сразу закрываться и перед закрытием просто выдавать свое содержимое

Если ты установил службу и она работает, то никакие батники больше запускать не надо, служба же и так запущена. Собственно, поэтому батник и закрывается.

**Comment by Flanchie** [comment]
тоже не работает, открывается и вылетает

**Comment by Flanchie** [comment]
> > сервисы - это службы в диспетчере задач?
> 
> Да.
> 
> > Однако теперь основной батник стал сразу закрываться и перед закрытием просто выдавать свое содержимое
> 
> Если ты установил службу и она работает, то никакие батники больше запускать не надо, служба же и так запущена. Собственно, поэтому батник и закрывается.

Допустим запущена служба. Так почему у меня также Дискорд и видосы с Ютуба не грузятся?!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Potatomate** [comment]
> > сервисы - это службы в диспетчере задач?
> 
> Да.
> 
> > Однако теперь основной батник стал сразу закрываться и перед закрытием просто выдавать свое содержимое
> 
> Если ты установил службу и она работает, то никакие батники больше запускать не надо, служба же и так запущена. Собственно, поэтому батник и закрывается.

Ну, после установки службы у меня не начинает работать дискорд. У меня почему-то стойкое чувство что я что-то где-то зафакапил

**Comment by advokat11** [comment]
> > > сервисы - это службы в диспетчере задач?
> > 
> > Да.
> > 
> > > Однако теперь основной батник стал сразу закрываться и перед закрытием просто выдавать свое содержимое
> > 
> > Если ты установил службу и она работает, то никакие батники больше запускать не надо, служба же и так запущена. Собственно, поэтому батник и закрывается.
> 
> Допустим запущена служба. Так почему у меня также Дискорд и видосы с Ютуба не грузятся?!!!!!!!!!!!!!!!!!!!!!!!

Значит не подходит стратегия к твоему провайдеру, изучай readme

**Comment by Flanchie** [comment]
> Значит не подходит стратегия к твоему провайдеру, изучай readme

Значит всё, РТК пофиксил Zapret?

**Comment by advokat11** [comment]
> > Значит не подходит стратегия к твоему провайдеру, изучай readme
> 
> Значит всё, РТК пофиксил Zapret?

Нет, не значит

**Comment by Flanchie** [comment]
> > > Значит не подходит стратегия к твоему провайдеру, изучай readme
> > 
> > 
> > Значит всё, РТК пофиксил Zapret?
> 
> Нет, не значит

Я кстати пробовал на эмуляторе 10 винды, там работало, тока конечно поломал там локалку что с локалки инет не брал, приходилось напрямую коннектиться через pppoe. Но то что не работает на ноуте с той же виндой 10 и многие жалуются, то пускай фиксит! И многие жалуются на вылет и не рабочий сервис.

**Comment by Flowseal** [comment]
> > > > Значит не подходит стратегия к твоему провайдеру, изучай readme
> > > 
> > > 
> > > Значит всё, РТК пофиксил Zapret?
> > 
> > 
> > Нет, не значит
> 
> Я кстати пробовал на эмуляторе 10 винды, там работало, тока конечно поломал там локалку что с локалки инет не брал, приходилось напрямую коннектиться через pppoe. Но то что не работает на ноуте с той же виндой 10 и многие жалуются, то пускай фиксит! И многие жалуются на вылет и не рабочий сервис.

Закрываю от флуда. 🫡

**Comment by Pocket24** [comment]
Сделал как было выше сказано, в итоге получил вот эту ошибку

![Image](https://github.com/user-attachments/assets/f51f7216-8f19-4ef1-a8d4-cc762093fa96)
