### ISSUE TITLE
не грузится чат и не подключаются голосовые каналы в дискорде

### ISSUE THREAD

**Issue by 6obr** [Flowseal/zapret-discord-youtube#32]
делал все по инструкции, но не грузится чат и не подключаются голосовые каналы в дискорде
вот так выглядят текстовые каналы:
![chat](https://github.com/user-attachments/assets/e9909dc2-9b39-47d2-969d-8f6e0689dad1)
и вот так выглядят голосовые:
![voice](https://github.com/user-attachments/assets/18cca366-7bbe-4958-9a0c-9c644397dc98)
подскажите пожалуйста что не так или что то я неправильно сделал.

**Comment by Flowseal** [comment]
Попробуйте сделать всё по инструкции ещё раз

**Comment by 6obr** [comment]
> Попробуйте сделать всё по инструкции ещё раз

увы, не помогло
