### ISSUE TITLE
проблема с файлом winws.exe

### ISSUE THREAD

**Issue by TerAncH1K** [Flowseal/zapret-discord-youtube#321]
возникла такая проблема, при переносе файлов файл winws.exe какого-то черта не переносится. не вылезает никакая ошибка, ничего, файл просто не хочет переноситься в папку, из-за чего возникает ошибка об отсутствии этого файла в папке bin
![Screenshot 2024-10-16 204955](https://github.com/user-attachments/assets/03b4f104-a120-4278-ac71-091681a17fb6)

до этого хотел переустановить на новую версию и удалял старые по средством входа в командную строку через админа и вписания команды "sc stop Windivert". возможно это как то связано? есть ли возможность это как то пофиксить?

**Comment by G1Me** [comment]
у меня была похожая проблема из-за антивирусника, он также моментально удалял winws.exe после разархивирования.

**Comment by TerAncH1K** [comment]
@G1Me в том то и сюр, что у меня в первый раз использования и до сегодняшнего вечера все работало, а как только я удалил полностью и попытался установить - этот файл никак не хочет перекидываться
антивирусы то выкл, ничего не мешает, а учитывая что до этого работал прекрасно, то всяко херня случилась из-за моих махинейшен

**Comment by TerAncH1K** [comment]
> возникла такая проблема, при переносе файлов файл winws.exe какого-то черта не переносится. не вылезает никакая ошибка, ничего, файл просто не хочет переноситься в папку, из-за чего возникает ошибка об отсутствии этого файла в папке bin ![Screenshot 2024-10-16 204955](https://private-user-images.githubusercontent.com/185237764/377131792-03b4f104-a120-4278-ac71-091681a17fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTc4NjAsIm5iZiI6MTcyOTA5NzU2MCwicGF0aCI6Ii8xODUyMzc3NjQvMzc3MTMxNzkyLTAzYjRmMTA0LWExMjAtNDI3OC1hYzcxLTA5MTY4MWExN2ZiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNjUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTc5ZWIwMWFlZTgxNzExMTgzZjdjODdkODAzNjg5OGNlMzlkZmI4MzJiYTdlN2FiNGVmYjg2MDNhMWQzZTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RIdWgF0J4vHIeg6U0_H-SOKvtEowPQlnqhHUw2TkAwI)
> 
> до этого хотел переустановить на новую версию и удалял старые по средством входа в командную строку через админа и вписания команды "sc stop Windivert". возможно это как то связано? есть ли возможность это как то пофиксить?

upd. файл winws.exe просто удаляется при попытке скачать его или перенести куда либо.

**Comment by Flowseal** [comment]
Антивирусник и прочее.
