### ISSUE TITLE
🟣 Обход Discord

### ISSUE THREAD

**Issue by ArtemDog500566** [Flowseal/zapret-discord-youtube#322]
Здравствуйте, сейчас вот скачал последнюю версию обхода, и после запуска всех батников general не работает только дискорд, ибо я буквально не могу с помощью кьюар кода войти в аккаунт, когда я направляю телефон на qr код то вместо входа, будто просит по новой навести, и даже после того как я ввёл данные аккаунта, он у меня не заходил.

**Comment by Flowseal** [comment]
На телефоне тоже нужен обход.
На телефоне пробуйте через VPN
