### ISSUE TITLE
проблема с файлом winws.exe

### ISSUE THREAD

**Issue by bect217** [Flowseal/zapret-discord-youtube#324]
При запуске general.bat  не может найти  winws.exe Что можно сделать?

**Comment by bect217** [comment]
> При запуске general.bat не может найти winws.exe Что можно сделать?
![Безымянный](https://github.com/user-attachments/assets/32fe25b4-fb46-414d-9e14-583c59ed0e5e)

**Comment by Flowseal** [comment]
Ваша ОС не может %~dp0 превратить в нормальный путь. Гуглите решение сами, эта версия нативно не поддерживается

**Comment by bect217** [comment]
Спасибо.

**Comment by HillsD-sourse** [comment]
> Спасибо.

Смотри, если у тебя до этого работало то проблема в антивирусе.
Я недавно столкнулся что антивирус видит троян в winws и удаляет, а без winws zapret работать не будет. Я отключил антивирус, скачал опять zapret, в антивирусе добавил в белый лист и обратно врубил антивирус. И всё заработало

**Comment by bect217** [comment]
Пробовал отключал антивирус и всю защиту, не помогло. Видимо дело в версии Windows.
