### ISSUE TITLE
Не понимаю, почему не работает обход для ютуб

### ISSUE THREAD

**Issue by KANTOZY** [Flowseal/zapret-discord-youtube#326]
Я где-то ошибся: Почему пишет "The specified service does not exist as an installed service."?
+ не работает в Firefox, но работает в Edge, причём моментально, что не так?
Просто я вообще не понимаю, что мне тут пишет консоль
Ниже текст из консоли после попытки установки

 Final args:   --wf-raw \"@D:\Programs\zapret-discord-youtube-1.4.1\rules.txt\"  --filter-udp 443 --hostlist \"D:\Programs\zapret-discord-youtube-1.4.1\list-general.txt\" --dpi-desync fake --dpi-desync-repeats 6 --dpi-desync-fake-quic \"D:\Programs\zapret-discord-youtube-1.4.1\bin\quic_initial_www_google_com.bin\" --new  --filter-udp 50000-65535 --dpi-desync fake --dpi-desync-any-protocol --dpi-desync-cutoff d3 --dpi-desync-repeats 6 --dpi-desync-fake-quic \"D:\Programs\zapret-discord-youtube-1.4.1\bin\quic_initial_www_google_com.bin\" --new  --filter-tcp 80 --hostlist \"D:\Programs\zapret-discord-youtube-1.4.1\list-general.txt\" --dpi-desync fake split2 --dpi-desync-autottl 2 --dpi-desync-fooling md5sig --new  --filter-tcp 443 --hostlist \"D:\Programs\zapret-discord-youtube-1.4.1\list-general.txt\" --dpi-desync fake split --dpi-desync-autottl 2 --dpi-desync-repeats 6 --dpi-desync-fooling badseq --dpi-desync-fake-tls \"D:\Programs\zapret-discord-youtube-1.4.1\bin\tls_clienthello_www_google_com.bin\"
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 2320
        FLAGS              :
Press any key to continue . . .

**Comment by Flowseal** [comment]
Следуйте советам https://github.com/Flowseal/zapret-discord-youtube/discussions/251

**Comment by KANTOZY** [comment]
> Следуйте советам #251
Есть нюанс, что при запуске general.bat всё идеально, но он не хочет устанавливаться в службу, пишет "The service name is invalid." и не грузит ютуб
