### ISSUE TITLE
Нет интернета у дискорда и ютуба

### ISSUE THREAD

**Issue by Ayden006** [Flowseal/zapret-discord-youtube#328]
Программа поработала 1 день и перестала, пытался удалить службы, но не получилось
![image](https://github.com/user-attachments/assets/de415bad-9108-4818-8653-ed7ac3081fb0)

**Comment by Flowseal** [comment]
Почистите куки/кэш
Следуйте советам в README
А также https://github.com/Flowseal/zapret-discord-youtube/discussions/252 и https://github.com/Flowseal/zapret-discord-youtube/discussions/251

**Comment by Ayden006** [comment]
Как следовать советам в README, это файл в  архиве?
