### ISSUE TITLE
Выходит ошибка при запуске файла discord.bat

### ISSUE THREAD

**Issue by shakirovformal** [Flowseal/zapret-discord-youtube#33]
При запуске батника через админа выходит следующая ошибка

![photo_2024-10-09_17-01-01](https://github.com/user-attachments/assets/b7baa646-408d-476c-9e53-5870445c9728)

На устройстве только 1 профиль с правами админа, пробовали закидывать папку в Диск C:/ не помогло.

**Comment by Flowseal** [comment]
Это не ошибка, это так работает программа.
