### ISSUE TITLE
Не работает 

### ISSUE THREAD

**Issue by Lapplatte** [Flowseal/zapret-discord-youtube#330]
1. Скачала последнюю версию
2. Разархивировала в папку с латиницей( у папки в названии всего одна буква, так что пробелов нет)
3. Запускала батники от админа
Как итог: скрипт запускается, якобы работает, не закрывается, но при этом допуск все равно отсутствует. Пробовала и ребутать комп и альтернативные батники - результат всегда один.
Впны все выключены, антивирусников нет, даже дефендер винды не жаловался

**Comment by Flowseal** [comment]
Следуйте советам тут
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
и тут
https://github.com/Flowseal/zapret-discord-youtube/discussions/251
