### ISSUE TITLE
Vitustotal 10/62 security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by Wafphlez** [Flowseal/zapret-discord-youtube#331]
На что конкретно возмущается Virustotal (https://www.virustotal.com/gui/file/dece0d7d8a78470843d2345147203e1b6673cdb71c1be73e7435ac22411db400) и Windows Defender?

**Comment by FafnOff** [comment]
На windivert, закинь тот же самый goodbyedpi на вирус тотал
