### ISSUE TITLE
Дискорд: подключение к RTC. Не установлен маршрут

### ISSUE THREAD

**Issue by Honnax** [Flowseal/zapret-discord-youtube#332]
После запусков discord.bat или discord_youtube.bat ютуб работает исправно, дискорд тоже за исключение звонков - бесконечный цикл "подключение к RTC. Не установлен маршрут". Пк перезапускал, приложения запускал от имени администратора

**Comment by Flowseal** [comment]
Обновите zapret. Прочитайте ещё раз README.
