### ISSUE TITLE
general (ошибка)

### ISSUE THREAD

**Issue by WERERICH** [Flowseal/zapret-discord-youtube#333]
Нажимаю на general, запускаю от имени админа, а потом вылетает ошибка и пишет "Windows cannot find 'D:\zapret-discord-youtube-1.4.1\bin\winws.exe'. Make your sure typed the name correctly, and then try again" Плиз хелп, может я чет не то кликаю

**Comment by Flowseal** [comment]
Всё написано в ошибке. По указанному пути не может найти файл winws.exe. Возможно, ты забыл перенести из архива либо съел антивирус

**Comment by sosissmys** [comment]
Что делать если файл general.bet выдаёт ошибку "we have 4 user defined desync profile(s) and default low priority profile 0" Там пишет что то про большое кол-во аккаунтов, если это так то как удалить эти лишние аккаунты?
