### ISSUE TITLE
Троян в 1.4.1 

### ISSUE THREAD

**Issue by 0001sve** [Flowseal/zapret-discord-youtube#334]
Вчера не показывало Троян, а сегодня начал показывать троян

**Comment by Wiryyx** [comment]
В старых тоже начало показывать.

**Comment by 0001sve** [comment]
> В старых тоже начало показывать.

и что с этим делать?

**Comment by Wiryyx** [comment]
А через что ты чекал?

**Comment by 0001sve** [comment]
> А через что ты чекал?

360 total моментально блокает

**Comment by DimaSergeew** [comment]
Касперский в 1.4+ блочит сразу находи трояны ранее такого не было

**Comment by Wiryyx** [comment]
Щас goodbyedpi чекнул там поменьше конечно нашло, но мне кажется там всё чисто. Прост базы обновились мб

**Comment by 0001sve** [comment]
> Щас goodbyedpi чекнул там поменьше конечно нашло, но мне кажется там всё чисто. Прост базы обновились мб

Да, я уже к этому файлу привык и как-то не приятно такое видеть что там теперь троян показывает

**Comment by 0001sve** [comment]
> Касперский в 1.4+ блочит сразу находи трояны ранее такого не было

360 Тоже самое

**Comment by Wiryyx** [comment]
> > Касперский в 1.4+ блочит сразу находи трояны ранее такого не было
> 
> 360 Тоже самое

Можешь скрин детекта прислать?

**Comment by 0001sve** [comment]
> > > Касперский в 1.4+ блочит сразу находи трояны ранее такого не было
> > 
> > 
> > 360 Тоже самое
> 
> Можешь скрин детекта прислать?

чутка позже занят сейчас

**Comment by Flowseal** [comment]
Файлы не обновлялись, хэши можете сами проверить.

**Comment by korjikkaif** [comment]
А почему папку снести не даёт?)

**Comment by Wiryyx** [comment]
> А почему папку снести не даёт?)

Потому что служба работает, а если ты например скачаешь другой запрет и запустишь там сервис, то оно остановит прошлый и даст тому запуститься, после ты уже сможешь удалить ту папку, а вообще там есть service remove и пк перезагружаешь.

**Comment by korjikkaif** [comment]
> > А почему папку снести не даёт?)
> 
> Потому что служба работает, а если ты например скачаешь другой запрет и запустишь там сервис, то оно остановит прошлый и даст тому запуститься, после ты уже сможешь удалить ту папку, а вообще там есть service remove и пк перезагружаешь.

![втф](https://github.com/user-attachments/assets/210c932c-89bc-4597-bc72-af6f540bb8c6)

**Comment by korjikkaif** [comment]
Пробовать другой запрет что ли?

**Comment by 0001sve** [comment]
> Пробовать другой запрет что ли?

подожди до завтра, может антивирусник перестанет видеть троян (что не точно)

**Comment by Nekto01-hack** [comment]
> Quote reply

тоже самое, я утром как обычно врубаю файл и 360 total security показал плашку мол "троян" и в итоге пока что снёс с компа, завтра попробую опять скачать, dpi не для меня если честно =\

**Comment by Wiryyx** [comment]
> подожди до завтра, может антивирусник перестанет видеть троян (что не точно)

мбмб

**Comment by exzolink** [comment]
Сборище продвинутых юзеров пк, читайте, что такое WinDivert и почему он считается вирусом

**Comment by Wiryyx** [comment]
> Сборище продвинутых юзеров пк, читайте, что такое WinDivert и почему он считается вирусом

про windivert мы в курсе, просто там плюсом ещё детекты появились

**Comment by exzolink** [comment]
> > Сборище продвинутых юзеров пк, читайте, что такое WinDivert и почему он считается вирусом
> 
> про windivert мы в курсе, просто там плюсом ещё детекты появились

~~ишачок~~, сурсы открыты, иди проверяй и компиль

**Comment by Nekto01-hack** [comment]
так, я скачал свежую версию и у меня антвирусник (360 total security) не ругается, я не менял там параметры, и даже оставил в браузере возможность отменять скачку файлов с вирусом, ну чтож рискну
