### ISSUE TITLE
Ошибка при запуске программы / Error when starting the programm

### ISSUE THREAD

**Issue by djjbl** [Flowseal/zapret-discord-youtube#335]
при попытке открыть general.bat или другие файлы вылезает ошибка: не удается найти "С:\discord\zapret-discord-youtube-main\bin\winws.exe". Проверьте,правильно ли указано имя и повторите попытку https://imgur.com/a/TH2XjQN

**Comment by Mekira1** [comment]
возможно это из за того что ты не разархивировал папку

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/333
