### ISSUE TITLE
вирусы

### ISSUE THREAD

**Issue by sSkyline32** [Flowseal/zapret-discord-youtube#338]
![image](https://github.com/user-attachments/assets/d4712873-5318-43fb-a4df-18ac90e8e228)
качал отсюда. думайте.

**Comment by exzolink** [comment]
Думай

**Comment by soufied** [comment]
Нормальные антивирусы будут?
ESET, Dr.Web?

**Comment by exzolink** [comment]
Приходят олухи, впервые взявшие в руки клавиатуру и заявляют что-то, проверив через вирустотал)

**Comment by Flowseal** [comment]
не качайте. дубликат. закрыто.
