### ISSUE TITLE
Продолжает работать после закрытия и удаления

### ISSUE THREAD

**Issue by kiborger** [Flowseal/zapret-discord-youtube#339]
Файлик zapret_remove не работает, выдает ошибки. Возможно и в провайдере дело, но я не уверен, что после запуска файлика на компьютере должен начинать работать и вай-фай. В диспетчере задач и мониторе ресурсов ничего нет. Может быть кто-то смог решить данную проблему. Винду не пробовал переустанавливать, но видел писали, что не помогает. Роутер сбрасывал до заводских - толку нет.

**Comment by Flowseal** [comment]
какая ошибка то?

**Comment by kiborger** [comment]
> какая ошибка то?
Ошибка в cmd 1060, типо служба не установлена. Файлов zapreta на компе нет, так как они свободно удаляются, но все равно Дискорд и Ютуб продолжают работать, хотя вроде бы ничего не запущено. С понедельника по среду все работало как надо: запустил батник - Дискорд работает, закрыв консоль батника - переставал работать. Сейчас работает сам по себе без файлов на компе даже.

**Comment by eldarrage** [comment]
Ровно такая же проблема, удалить папку со старой версией не получается, система пишет что файл или папка используются, а при попытке удалить через cmd пишет ошибка 1060
![zapret issue](https://github.com/user-attachments/assets/aa8a1302-cb42-4022-9851-d84135d835fb)
Попытался по совету узнать название через driverquery, но окно просто сразу закрывается после открытия
Удалил все файлы из папки zapret кроме WinDivert64.sys в папке bin. 
![zapret issue 2](https://github.com/user-attachments/assets/7dfb06f6-5188-4626-aa91-d1e32a14f47a)
Очень смущает слово Bitcoin в описании
UPD. С удалением папки я лох и опозорился, всё решил. А вот с удалением через cmd проблема остаётся

**Comment by kiborger** [comment]
У меня выдает ошибку 1060 3 раза, поиск WinDivert ничего не выдает и при этом папку даёт удалить, как и все файлы.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/312#issuecomment-2416745090

**Comment by kiborger** [comment]
> Ровно такая же проблема, удалить папку со старой версией не получается, система пишет что файл или папка используются, а при попытке удалить через cmd пишет ошибка 1060 ![zapret issue](https://private-user-images.githubusercontent.com/181561059/377769539-aa8a1302-cb42-4022-9851-d84135d835fb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDk2ODEsIm5iZiI6MTcyOTI0OTM4MSwicGF0aCI6Ii8xODE1NjEwNTkvMzc3NzY5NTM5LWFhOGExMzAyLWNiNDItNDAyMi05ODUxLWQ4NDEzNWQ4MzVmYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxMTAzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjRkODQ0NmE1NWZhNmM2ZjUxZTUyNWE0OWUxY2NlMjZkMTRiYzNkYmIyOWE1MmViZmVlMjc4YjVjZTQ4YTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tf7VgtuTakhuNvMtWPsZj3eSchOCu6h9rlCmiKaviNU) Попытался по совету узнать название через driverquery, но окно просто сразу закрывается после открытия Удалил все файлы из папки zapret кроме WinDivert64.sys в папке bin. ![zapret issue 2](https://private-user-images.githubusercontent.com/181561059/377775633-7dfb06f6-5188-4626-aa91-d1e32a14f47a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDk2ODEsIm5iZiI6MTcyOTI0OTM4MSwicGF0aCI6Ii8xODE1NjEwNTkvMzc3Nzc1NjMzLTdkZmIwNmY2LTUxODgtNDYyNi1hYTkxLWQxZTMyYTE0ZjQ3YS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxMTAzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjBkZDAxOWNhNjZhYzI1ZGRhYjJiZDBhNThiNmRmNmMxNDM0NDBjOWUzZTJhZWNiYTc2MjI4ZTQyZjU1NTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o_3jMykJPUbBirFsIEmlzttcTPS8yS_OfIhY3rc7ayI) Очень смущает слово Bitcoin в описании UPD. С удалением папки я лох и опозорился, всё решил. А вот с удалением через cmd проблема остаётся

Ну если WinDivert реально не установлен, то консоль продолжит выдавать ошибки, как бы логично. Но у меня тоже выдает эти ошибки, а все продолжает работать, даже с выключенным компом на вай фае открывается Ютуб и Дискорд

**Comment by serpen7** [comment]
> Ну если WinDivert реально не установлен, то консоль продолжит выдавать ошибки, как бы логично. Но у меня тоже выдает эти ошибки, а все продолжает работать, даже с выключенным компом на вай фае открывается Ютуб и Дискорд

тут два варианта либо ваш пров недоглядел, либо что то на телефоне запущено =\
Выше коммент почти что про это
Тут варик позвонить прову если ничего на телефоне не запущено, он исправит... но надо ли это вам тут другой вопрос...
Блокировки с замедлом странное дело иногда и по разному вдруг появляются "окна", ваш выбор открыть его и дышать воздухом или запечатать его кирпичом.

**Comment by Eptiy** [comment]
> Очень смущает слово Bitcoin в описании

Там ссылка на сайт разраба виндайверта и его кошелёк для донатов.

> а все продолжает работать, даже с выключенным компом на вай фае открывается Ютуб и Дискорд

Если обход работает за пределами пк, тем более, когда он выключен, это говорит, что дело не в обходе, а в работе провайдера. Не может обход никаким образом распространяться на другие ваши устройства.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/312
