### ISSUE TITLE
service_discord_youtube.bat

### ISSUE THREAD

**Issue by Narihyon** [Flowseal/zapret-discord-youtube#34]
![image](https://github.com/user-attachments/assets/df76bd39-d9be-4863-a494-32dba1afbe2a)
Вот такая ошибка, но если убрать строчку "--filter-tcp=80 --hostlist=\"%~dp0list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^" В этом батнике, то все нормально запускается и все работает.
Я просто сравнил 2 батника, "service_discord.bat" там этой строчки нет

**Comment by Flowseal** [comment]
На скриншоте не ошибка, а успшное создание сервиса. Можете не убирать ничего.

**Comment by Narihyon** [comment]
Там не работает с той строчкой лично у меня. 
![image](https://github.com/user-attachments/assets/32fa70b1-b733-43f2-96e6-ed893774d948)
Вот без той строчки, как выглядит cmd и дискорд начинает работает вместе с ют
В самом первом моем скрине "OpenService FAILED"
