### ISSUE TITLE
Перестал работать, до этого с начала блокировки работал исправно

### ISSUE THREAD

**Issue by interplay72** [Flowseal/zapret-discord-youtube#340]
Буквально только что перестал работать zapret, просто выкинуло из дискорда и не загружается, удалось зайти только через впн
![photo_2024-10-18_00-52-53](https://github.com/user-attachments/assets/be96e0ef-c905-4367-b1dd-1eef8fa7b7a0)

**Comment by egorosi123** [comment]
аналогично

**Comment by ShamHyper** [comment]
+

**Comment by gnilobaiter** [comment]
+1 уже почти час страдаю, не работает ни одна версия. И причем локально, у кента работает на другом провайдере

**Comment by Flowseal** [comment]
У меня всё работает. Пробуйте советы тут и обсуждайте там же https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by gnilobaiter** [comment]
> У меня всё работает. Пробуйте советы тут и обсуждайте там же #252

Я в течении этого часа всё перепробывал. У меня на виртуалке тоже не работает, и с мобильного инета. Думаю до вас тоже скоро дойдёт

Это всё началось ровно в 00:00 по МСК, совпадение чтоли?

**Comment by Flowseal** [comment]
> > У меня всё работает. Пробуйте советы тут и обсуждайте там же #252
> 
> Я в течении этого часа всё перепробывал. У меня на виртуалке тоже не работает, и с мобильного инета. Думаю до вас тоже скоро дойдёт
> 
> Это всё началось ровно в 00:00 по МСК, совпадение чтоли?

Как дойдёт, тогда и буду смотреть. Или вы предлагаете в небо мне сейчас тыкать? Я без анализа трафика вам ничего не сказать не смогу 🙂

**Comment by gnilobaiter** [comment]
> > > У меня всё работает. Пробуйте советы тут и обсуждайте там же #252
> > 
> > 
> > Я в течении этого часа всё перепробывал. У меня на виртуалке тоже не работает, и с мобильного инета. Думаю до вас тоже скоро дойдёт
> > Это всё началось ровно в 00:00 по МСК, совпадение чтоли?
> 
> Как дойдёт, тогда и буду смотреть. Или вы предлагаете в небо мне сейчас тыкать? Я без анализа трафика вам ничего не сказать не смогу 🙂

Это-то понятно, просто говорю о том, что нужно быть готовым. Советы из https://github.com/Flowseal/zapret-discord-youtube/discussions/252 в данной ситуации не помогают

**Comment by interplay72** [comment]
> +1 уже почти час страдаю, не работает ни одна версия. И причем локально, у кента работает на другом провайдере

так же у друга все работает а у меня упал в 00:00

**Comment by gnilobaiter** [comment]
МСК и СПБ лежит, регионы пока дышат как я понимаю

> > +1 уже почти час страдаю, не работает ни одна версия. И причем локально, у кента работает на другом провайдере
> 
> так же у друга все работает а у меня упал в 00:00

**Comment by gnilobaiter** [comment]
У меня всё заработало, сбой был со стороны провайдера. Сайты открывались (даже ру) только с VPN

**Comment by interplay72** [comment]
> У меня всё заработало, сбой был со стороны провайдера. Сайты открывались (даже ру) только с VPN

Че за провайдер? у меня вроде как тоже заработало

**Comment by gnilobaiter** [comment]
> > У меня всё заработало, сбой был со стороны провайдера. Сайты открывались (даже ру) только с VPN
> 
> Че за провайдер? у меня вроде как тоже заработало

SkyNet

**Comment by gnilobaiter** [comment]
Я оператору мозги колупал минут 15, сказал что "вышестоящие инстанции" чето делают на линии и поэтому инет загнулся

**Comment by interplay72** [comment]
> > > У меня всё заработало, сбой был со стороны провайдера. Сайты открывались (даже ру) только с VPN
> > 
> > 
> > Че за провайдер? у меня вроде как тоже заработало
> 
> SkyNet

тоже SkyNet. тестят видимо обход обхода блокировок))

**Comment by ShamHyper** [comment]
> тоже SkyNet. тестят видимо обход обхода блокировок))

Ну на VLESS всё стабильно, пусть дальше тестят

**Comment by chbobols1** [comment]
а у меня грузит, но не прогружается МГТС. Бывало такое?
![2024-10-18_12-55-25](https://github.com/user-attachments/assets/75ab4512-3c8e-4004-94a6-91bae9552677)

**Comment by Baguhan-p** [comment]
тоже перестал робить :(

**Comment by romankholmov** [comment]
Москва, Ростелеком. Отвалился час назад, никакие dpi и zapret не включают

**Comment by romankholmov** [comment]
Решил вот так: https://vk.com/wall-207040555_17986
