### ISSUE TITLE
Обнаружен Defender

### ISSUE THREAD

**Issue by myKiraa** [Flowseal/zapret-discord-youtube#341]
Привет! Последний релиз, обнаруживается Defender, будет ли исправлено? До этого не было проблем.

**Comment by ShinkarenkoMaksim** [comment]
Kaspersky со вчерашнего дня начал ругаться на Windivert64.sys. На все версии - от 1.0 до 1.3, более поздние не качал
Тип: Легальное приложение, которое может быть использовано злоумышленниками для нанесения вреда компьютеру или данным пользователя
Название: not-a-virus:HEUR:RiskTool.Multi.WinDivert.gen

Понятное дело, что использование этой уязвимости исключительно на совести разработчика утилиты. Доверяться или нет - дело каждого. Я задумался, пока склонен вернуться на старый добрый платный VPN

**Comment by serpen7** [comment]
Антивирусня начала флагать виндайверты потому что распространилось много фейковых версий с левых репозиториев которые используются вкупе с вирусами. Об этом кстати и на гудбае и на запрете предупреждали в шапках. Оно и на виндайверт которые в гудбай дпи тоже предупреждение стало выдавать. Видимо плохие люди тоже не спят.

Это не вирус если вы скачиваете с правильного репозитория, рисктул лишь предупреждение о том что это может быть использовано в злонамеренных целях. И походу это как раз таки из за левых репозиториев с версиями с вирусней поднимает рейтинг опасности виндайверта.

**Comment by Eptiy** [comment]
Это даже не совсем уязвимость, это [RiskTool](https://threats.kaspersky.com/ru/class/RiskTool/). Но пользоваться или нет - дело ваше.
