### ISSUE TITLE
Использование/обход openai ( chatgpt ) 

### ISSUE THREAD

**Issue by s6t6n66** [Flowseal/zapret-discord-youtube#343]
Возможно ? что нибудь сделать для этого )
У них ещё и приложение вышло на винду
Или в крайний случай как то добавить обход на сайте

**Comment by GrinlexGH** [comment]
нельзя. это блокировка не от ркн, а от самой openai. они проверяют с какого региона твой ip, так что решается только сменой региона, то есть впн
