### ISSUE TITLE
🟣 Обход Discord и Call of Duty: Warzone

### ISSUE THREAD

**Issue by TheSameEskor** [Flowseal/zapret-discord-youtube#344]
Сервис [zapret-discord-youtube] работает отлично версия 1.4.1, но проблема с игрой Call od Duty: Warzon она просто вылетает, если выключаешь сервис и ребутаешь комп всё работает, но хочется что бы дс и игра работали вместе. Если есть решение, напишите пожалуйста.

**Comment by TheSameEskor** [comment]
Нашёл решение тут на Github, оно работает, но надеюсь выпустят фикс для игры. Так как это не совсем решение проблемы.

Fix by @MrVoyage [RU]Как использовать Discord что бы не вылетал COD?

Запускаю discord.bat (логично, с правами администратора)
Запускаю Discord и захожу в голосовой канал
Закрываю окно Zapret
Запускаю service_remove.bat (логично, с правами администратора)
Запускаю COD и играю

**Comment by sh1zya** [comment]
If I close the bypass, I won't be able to connect to channels, and if I'm already sitting with friends in a conference, I'll just be thrown out after a while.

**Comment by GibonKenobi** [comment]
> Нашёл решение тут на Github, оно работает, но надеюсь выпустят фикс для игры. Так как это не совсем решение проблемы.
> 
> Fix by [@MrVoyage](https://github.com/MrVoyage) [RU]Как использовать Discord что бы не вылетал COD?
> 
> Запускаю discord.bat (логично, с правами администратора) Запускаю Discord и захожу в голосовой канал Закрываю окно Zapret Запускаю service_remove.bat (логично, с правами администратора) Запускаю COD и играю

Не помогает, в дискорде из канала выкидывает минут через 15

**Comment by Matador19696** [comment]
Был бы какой то вариант замаскировать Winws этот , проблема ж явно в его процессе в системе
