### ISSUE TITLE
Антивирус начал ругаться на прогу, говорит там троян.

### ISSUE THREAD

**Issue by B0TSie** [Flowseal/zapret-discord-youtube#345]
![2024-10-18_18-01-51](https://github.com/user-attachments/assets/8f0766a1-819c-4789-9b61-491315c4c4bd)

**Comment by Flowseal** [comment]
Вирусов нет. Боитесь - не скачивайте. 
https://github.com/bol-van/zapret/issues/550

**Comment by B0TSie** [comment]
> Вирусов нет. Боитесь - не скачивайте. [bol-van/zapret#550](https://github.com/bol-van/zapret/issues/550)

Какие ваши доказательства? Мои вот:
![2024-10-18_18-49-47](https://github.com/user-attachments/assets/2eda15cd-605d-4e74-8ab7-c9cc54869384)

Имз: Прикол тут в том, что раньше он не пиздел. А теперь ныть начал, что ему чёт там не нравится (Речь идёт о старой версии, я ещё не обновлялся). Да и "вирус тотал" тоже говорит, что ругаются лишь определённые антивирусы. Паходу ждать придётся пока антивирусы не обновятся и не поймут, что тревога ложная...

**Comment by exzolink** [comment]
> > Вирусов нет. Боитесь - не скачивайте. [bol-van/zapret#550](https://github.com/bol-van/zapret/issues/550)
> 
> Какие ваши доказательства? Мои вот:
> ![2024-10-18_18-49-47](https://github.com/user-attachments/assets/2eda15cd-605d-4e74-8ab7-c9cc54869384)
> 
> Имз: Прикол тут в том, что раньше он не пиздел. А теперь ныть начал, что ему чёт там не нравится (Речь идёт о старой версии, я ещё не обновлялся). Да и "вирус тотал" тоже говорит, что ругаются лишь определённые антивирусы. Паходу ждать придётся пока антивирусы не обновятся и не поймут, что тревога ложная...
> 

Доказательства - открытые сурсы, идёшь проверяешь и компилируешь
