### ISSUE TITLE
Обход блокировок продолжает работать после полного удаления

### ISSUE THREAD

**Issue by dungeonmaster228** [Flowseal/zapret-discord-youtube#346]
Пользовался service_remove. Несколько раз вручную проверил, что все службы, сервисы и процессы связанные с zapret были полностью удалены, однако обход продолжает работать, причём на всех устройствах подключенных к сети, даже при выключенном устройстве на котором инициализировался zapret.

**Comment by exzolink** [comment]
Ну раз точно удалил, логично, что обход не работает?

**Comment by dungeonmaster228** [comment]
> Ну раз точно удалил, логично, что обход не работает?

Но он работает, и такая проблема не только у меня

**Comment by Eptiy** [comment]
Чувак, для тебя звоночком не было, что волшебным образом обход с пк работает на всю локальную сеть? Уже видел похожий тред, у ребят провайдеры разблочили доступ, а когда они отрепортили об этом, заблочили обратно https://github.com/Flowseal/zapret-discord-youtube/issues/312#issuecomment-2417477749. Просто пользуйтесь, пока не прикрыли.

**Comment by exzolink** [comment]
> > Ну раз точно удалил, логично, что обход не работает?
> 
> Но он работает, и такая проблема не только у меня

Выше уже написали, но повторюсь, как он может работать с выключенным компом, так и ещё на всю сеть?

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/312
