### ISSUE TITLE
Zapret i VAC

### ISSUE THREAD

**Issue by Milkqr** [Flowseal/zapret-discord-youtube#347]
Может ли VAC (valve anti cheat) забанить меня за прогу? и если я не скачаю сервис и закрою прогу она остановится?

**Comment by Milkqr** [comment]
Ну типо если я закрою окошко то прога не будет на инет действовать (если сервис не установлен)

**Comment by Eptiy** [comment]
> Может ли VAC (valve anti cheat) забанить меня за прогу?

Меня пока не забанил, значит, скорее всего - нет.

> Ну типо если я закрою окошко то прога не будет на инет действовать (если сервис не установлен)

Программа работает либо через сервис винды, либо через открытый батник. Если сервис не установлен, либо окно не открыто, то программа не работает и, соответственно, ни на что не влияет.

**Comment by Flowseal** [comment]
Нет
