### ISSUE TITLE
Не удаляется папка

### ISSUE THREAD

**Issue by slwowly** [Flowseal/zapret-discord-youtube#35]
При попытке удалить папку пишет что WinDivert64 работает, его нет в диспечере, перезапуск компа не помогает. Как удалить?

**Comment by 6obr** [comment]
одновременно нажмите клавишу Windows и кнопку R. Наберите в строке cmd, а затем зажмите комбинацию Ctrl+Shift+Enter. В появившемся окне пишем sc stop windivert
