### ISSUE TITLE
Без vpn не работает ютуб

### ISSUE THREAD

**Issue by Fanmag01** [Flowseal/zapret-discord-youtube#356]
Захожу сегодня на ютуб- не грузит, обновил прогу- не грузит, что на старой версии что на новой без vpn не грузит.
Пишет что нет интернета
![Снимок экрана 2024-10-19 141406](https://github.com/user-attachments/assets/74b61ad2-2a1b-44b7-8e52-061feea5e3a0)

![Снимок экрана 2024-10-19 141504](https://github.com/user-attachments/assets/daf36a96-4486-49ed-a4ed-29aa062a2d6e)

В какое положение Kyber не поставлю тоже нема
![Снимок экрана 2024-10-19 141539](https://github.com/user-attachments/assets/dcd57698-22a8-4fab-833e-884c0d3760ac)

В гайдах чуваки пишут заменить конфиг в проге, а запустить её как? где найти?
![Снимок экрана 2024-10-19 141722](https://github.com/user-attachments/assets/d6b1a7fd-6e1f-4011-b763-69bc606ba344)

**Comment by Flowseal** [comment]
Отключите GoodbyeDPI и прочие обходы
https://github.com/Flowseal/zapret-discord-youtube/discussions/251

**Comment by Fanmag01** [comment]
в том то и дело, что других обходок нет, буквально вчера все было норм
