### ISSUE TITLE
Какие вообще существуют риски использования данной штуки?

### ISSUE THREAD

**Issue by gusmanoff** [Flowseal/zapret-discord-youtube#36]
Некоторые люди (знакомые, друзья), да и я тоже, скрывать не буду, боимся использовать эти батники.
Так вот, что может произойти если использовать их? Кража данных или еще что-нибудь?
Я не силен в этой теме, но ходили слухи про это все...

**Comment by gusmanoff** [comment]
Я вот скачал, сделал все и все работает, я прямо доволен, но просто что может произойти?)

**Comment by Flowseal** [comment]
Некоторые античиты могут ругаться на драйвер WinDivert. Бана не будет, но в некоторые игры может не пустить. Известные примеры: Call of Duty. Решение: выключать перед игрой в проблемные игры 🤷
