### ISSUE TITLE
Ошибка при запуске (окно самостоятельно закрывается)

### ISSUE THREAD

**Issue by WALEXAN123** [Flowseal/zapret-discord-youtube#369]
Пытаясь запустить bat от имени администратора, он тут же закрывается, а если просто так запустить то выдает ошибку - "Не удается найти "C:\Users\*****\Desktop\Mods winws.exe". Проверьте, правильно ли указано имя и повторите попытку". Даже после перезагрузки ПК, ошибка осталась, а что делать с этим я не знаю....

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/333
