### ISSUE TITLE
Работает либо только Ютуб, либо только Дискорд

### ISSUE THREAD

**Issue by dvdidenko** [Flowseal/zapret-discord-youtube#37]
Пытался 2-мя способами:
1) discord_youtube.bat. Итог всегда один: Дискорд работает отлично, Ютуб грузит странички и предгруженные видосы, но любой новый видос уходит в вечную буферизациюю
2)GoodbyeDPI+service_goodbye_discord.bat. Итог: непостоянный. Но в основном прекрасно грузится ютуб, включая новые видосы, но Дискорд навечно остаётся в "проверке обновлений".

Сижу с ноута на Wi-Fi, Других ВПН/Прокси не включал, из антивирусников лишь МалвейрБайтс на минимальной защите, без защиты интернет трафика и подобного.

В  GoodbyeDPI использую 1_russia_blacklist_YOUTUBE, в котором у меня :
```@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
PUSHD "%_arch%"

start "" goodbyedpi.exe -12 --fake-gen 24 --fake-from-hex 160301FFFF01FFFFFF0303594F5552204144564552544953454D454E542048455245202D202431302F6D6F000000000009000000050003000000 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

POPD
POPD
```

**Comment by Flowseal** [comment]
Мои флаги GoodbyeDPI: 
`-9 --fake-gen 29 --fake-from-hex d43f40cf57cec29e80fc0ee1feb74a88d6c631c177a9dfde24dde56bec17f88a57cc74609a54217679cc80b8c93e04d6fce5582d99f1e0c2eab1`

Файл **`service_goodbye_discord.bat`** работает ТОЛЬКО с СЕРВИСОМ GoodbyeDPI:

**`service_goodbye_discord.bat`** - запустить, если вы используете СЕРВИС goodbyedpi, и хотите, чтобы zapret обходил только discord. ВНИМАНИЕ: Запускать ПОСЛЕ создания сервиса goodbyedpi. Первый раз goodbyedpi может вылететь - просто перезапустите устройство!

Сервис GoodbyeDPI: `service_install_russia_blacklist_YOUTUBE.cmd`

**Comment by dvdidenko** [comment]
Заработало, спасибо
