### ISSUE TITLE
Не могу совместить GDPI и Zapret

### ISSUE THREAD

**Issue by ExtaZzysS** [Flowseal/zapret-discord-youtube#374]
Я сначала запускаю gdpi, потом запускаю discord.bat и после запускаю service_goodbye_discord.bat и в одной из строк слово Failed и ютуб перестает работать пока не закрою discord.bat. Может я что-то не так делаю или не в том порядке?
![4RY7joPd4Jw](https://github.com/user-attachments/assets/88a6e214-ecc5-41e9-a6f7-b2c87a980515)

**Comment by Flowseal** [comment]
Читайте внимательно Readme.

**Comment by ExtaZzysS** [comment]
А можно просто сказать что я не так сделал, я бы не написал сюда, если бы не прочитал много раз ридми, вроде делаю все как сказано, сервис запускаю только после дипиай, но все равно не выходит
