### ISSUE TITLE
Конфликт с GeForce Experience или утечка памяти?

### ISSUE THREAD

**Issue by ValbertonHere** [Flowseal/zapret-discord-youtube#379]
Иногда при попытке сохранения момента через функцию мгновенного повтора систему начинает жестко перегружать до выключения программы.
После этого GFE оживает и штатно работает. 

_Или это просто закономерная утечка памяти, а GFE просто стал катализатором..._

**Comment by serpen7** [comment]
GFE сам по себе кусок софта который не всегда стабильно работает и периодически требует переустановки, например момент когда они профукали разрешения в системе и установленные дрова от GFE через него работали крайне нестабильно или вовсе крашили комп. Если с ним проблемы, попробуй его переустановить, но настройки сделанные в GFE при его удалении стираются тоже учти.

**Comment by ValbertonHere** [comment]
Вчера провел еще тесты и да, прога тут не при чем. Последние дрова НВиДэ поломали малость функцию реплеев.
