### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by MakutaGG** [Flowseal/zapret-discord-youtube#38]
Распаковал архив в каталог без пробелов, запустил от имени администратора дискорд ютуб бат, пишет это

we have 4 user defined desync profile(s) and default low priority profile 0
Loading hostlist D:\obhoddisc\list-general.txt
loading plain text list
Loaded 31 hosts from D:\obhoddisc\list-general.txt
Loading hostlist D:\obhoddisc\list-general.txt
loading plain text list
Loaded 31 hosts from D:\obhoddisc\list-general.txt
Loading hostlist D:\obhoddisc\list-general.txt
loading plain text list
Loaded 31 hosts from D:\obhoddisc\list-general.txt
windivert initialized. capture is started.
 
и дискорд не запускается

Запускаю от имени админа сервис дискорд ютуб бат, пишет это

`The zapret DPI bypass : winws1 service is not started.

More help is available by typing NET HELPMSG 3521.

[SC] DeleteService SUCCESS
[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 4996
        FLAGS              :
Press any key to continue . . .
`

**Comment by Flowseal** [comment]
По логам всё отличное запускается. Возможно, проблема в провайдере.

[FAQ](https://github.com/Flowseal/zapret-discord-youtube?tab=readme-ov-file#%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82)

Можете попробовать поменять параметры флага `--dpi-desync` в соотвествии с документацией: https://github.com/bol-van/zapret (ctrl+f -> --dpi-desync)

**Comment by XJle6yIIIk1n** [comment]
Такой вопрос: на 7й винде батник будет работать? или только начиная с 10й?

**Comment by Flowseal** [comment]
> Такой вопрос: на 7й винде батник будет работать? или только начиная с 10й?

Неизвестно

**Comment by krexik** [comment]
как убрать пробелы по пути к файлу?

**Comment by Flowseal** [comment]
> как убрать пробелы по пути к файлу?

https://github.com/Flowseal/zapret-discord-youtube/issues/44
