### ISSUE TITLE
Обход блокировки ютуба не работает с firefox 

### ISSUE THREAD

**Issue by liolouiiii** [Flowseal/zapret-discord-youtube#382]
обход блокировки ютуба нормально не работает с браузером firefox, что я только не делал, и расширения которые могут конфликтовать отключал, днс в браузере то включал то выключал и какие либо я альтернативы обхода запрета не включал либо ютуб не грузит либо грузит но так медленно, подскажите в чём может быть проблема?

UPD : Я пробовал запускать ютуб с Chrome и там всё работало

**Comment by Flowseal** [comment]
Читайте тут: https://github.com/Flowseal/zapret-discord-youtube/discussions/251
