### ISSUE TITLE
Valorant

### ISSUE THREAD

**Issue by urinmyhead** [Flowseal/zapret-discord-youtube#383]
Привет!

Батник для обхода блокировки дискорда работает нормально но почему-то увеличивает пинг в игре Valorant
И ладно бы если увеличивало немного но пинг переваливает за 400-500

Я предполагаю что некоторые айпишники в листе связанны с этой игрой

**Comment by Flowseal** [comment]
Можете попробовать скачать 1.4.0. Такой проблемы у себя не наблюдаю ни с какой версией
