### ISSUE TITLE
удаление

### ISSUE THREAD

**Issue by Ruzoveda** [Flowseal/zapret-discord-youtube#386]
приветствую, я конечно знал что нужно что то отдать от себя за пользование сервисом, но я не думал что ваш майнер будет 40% ЦП забирать, *WinSys64 не хочет удалятся так как запущен где то и вот вообще найти не могу его, зачем так ? =(

**Comment by deltaradune** [comment]
странно.. у меня ничего не нагружает всего лишь 3%

правда на вирус тотале в файле winws нашло херово туча троянов

**Comment by Ruzoveda** [comment]
> странно.. у меня ничего не нагружает всего лишь 3%
> 
> правда на вирус тотале в файле winws нашло херово туча троянов

для антивируса всё троян и тд, я запустил функцию удаления, жрать ресурсы перестало, удалил майнер отдельно, но меня напрягает БэкДор , вроде инфу на компе важную и опасную не держу, но до жути не приятно

**Comment by Flowseal** [comment]
В данном репозитории нет вирусов. Боитесь - не используйте.

**Comment by Ruzoveda** [comment]
> В данном репозитории нет вирусов. Боитесь - не используйте.

я пользую ибо удобно, спасибо, но просто скажи зачем бэкдор и какой алгоритм у майнера ? пожалуйста не делай под 40% загрузки ЦП только для него одного

**Comment by Flowseal** [comment]
> > В данном репозитории нет вирусов. Боитесь - не используйте.
> 
> я пользую ибо удобно, спасибо, но просто скажи зачем бэкдор и какой алгоритм у майнера ? пожалуйста не делай под 40% загрузки ЦП только для него одного

Иди почисти свой комп, потом создашь новый аккаунт на гитхабе (ибо с этого ты больше ничего писать здесь не сможешь) и расскажешь результатах 🫡
