### ISSUE TITLE
перенести бинари из репы в releases

### ISSUE THREAD

**Issue by gmankab** [Flowseal/zapret-discord-youtube#387]
привет

хранить бинари в репе - плохая идея

по хорошему в репе должны быть исходники соотвествующие бинарям, а в релизах бинари соответсвующие исходникам

собственно в релизах бинари уже лежат, осталось заменить бинари в репе на исходники

либо просто убрать бинари из репы, тоже сойдет

**Comment by Flowseal** [comment]
Кто сказал, что это плохая идея? Личные устои кого-то?
