### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by sheydhql** [Flowseal/zapret-discord-youtube#388]
Решил начать пользоваться этой прогой,
но сходу меня встретило это:
![image](https://github.com/user-attachments/assets/174fb44b-b984-4ff5-9f2d-2379cdb71ab7)
Желание начать пользование очень сильно снизилось или у кого-то есть дельное объяснение этому?

**Comment by XoreoxX** [comment]
Меня тоже новая версия напрягла, много лишнего появилось и доверие опустилось, скачай версию 1.2.0 там нету таких проблем принципе винда ничего не говорит про него.

**Comment by XoreoxX** [comment]
и когда запускаешь bat от имени администратора включай и разархивировать не забудь

**Comment by sheydhql** [comment]
спасибо

> Меня тоже новая версия напрягла, много лишнего появилось и доверие опустилось, скачай версию 1.2.0 там нету таких проблем принципе винда ничего не говорит про него.

**Comment by Demulazer** [comment]
"Многие антивирусники в данный момент жалуются на HackTool/RiskTool и WinDivert - это нормальное поведение, так как программа изменяет сетевые пакеты. Что с этим делать? Собрать бинарники самому из исходников, довериться уже собранным, либо не использовать вовсе."

**Comment by Flowseal** [comment]
Читайте README
