### ISSUE TITLE
bitcoin v windivert64.sys

### ISSUE THREAD

**Issue by Gurk3r** [Flowseal/zapret-discord-youtube#389]
В описании windivert ссылка на reqrypt.org 
![image](https://github.com/user-attachments/assets/061a368a-b969-4459-9878-d7f29b12e828)

**Comment by Flowseal** [comment]
круто

**Comment by Gurk3r** [comment]
а что это значит то

**Comment by Flowseal** [comment]
Сайт, где выложен WinDivert и ссылка на донат разработчику.
