### ISSUE TITLE
не может найти указанный файл

### ISSUE THREAD

**Issue by Mekira1** [Flowseal/zapret-discord-youtube#391]
В какой то момент у меня начал сборить инет, пока я сидела с прогой. Я вырубила прогу, врубаю инет, и тут без проги все запускается. Все работало без нее. И ютуб, и дискорд. Я не понимала как это, но такая ладно, окей. Причем это было только на компе. На телефоне все как всегда висло. Я решила проверить, баг ли это. Перезагружаю комп, и тут начинается это. Мне пишет при запуске "the system cannot find the file specifed". Вопрос что за баг, и почему теперь найти не может? До этого все было как обычно, работало. Я хотела переустановить версию эту же (я ничего не обновляла, как сижу на 1.1.1 так и все есть) мне браузер сам заблокал, сказал мол файл опасен (я уже скачивала, но как переустановить? Я знаю что она без вирусов, сколько сижу все норм)

**Comment by Flowseal** [comment]
Антивирус выключите и киньте в исключение winws.exe и WinDivert'ы

**Comment by Mekira1** [comment]
не сработало, все равно не может найти файл пишет

**Comment by Mekira1** [comment]
короче я нашла решение, т.к. у меня был нераспакованный файл я удалила тот и распаковала по новой и все прога нашла, и теперь все работает
