### ISSUE TITLE
Не могу отключить сервис

### ISSUE THREAD

**Issue by Tchander** [Flowseal/zapret-discord-youtube#392]
Не получается удалить/отключить сервис. Даже после перезапуска ПК он как-то продолжает работать(потому что работают ютуб и дискорд). При вызове service_remote.bat - так же выадёт ошибку - The service name is invalid по каждому скрипту. Из-за этой проблемы я не могу воспользоваться vpn-ом, так как происходит конфликт сетей

**Comment by Flowseal** [comment]
Если папка удалена, то после перезапуска компьютера программа НИКАК не может работать (она просто не существует). Возможно, вы используете что-то другое, либо провайдер в этот момент просто не блокирует данные сервисы.
