### ISSUE TITLE
После запрета на всем пк стал виснуть интернет

### ISSUE THREAD

**Issue by xxvvv1801** [Flowseal/zapret-discord-youtube#393]
я точно не могу сказать что вызывает эти зависания, но после последней версии запрета у меня даже если сервис удален и выключен виснет интернет, вкладки грузятся медленно, какие нибудь даже картинки в том же тг или дс, приложение которые требуют интернет будь то игры могут долго загружать все, когда в стиме скачивал апд для игры он минут 5 висел на пару кб только потом стал нормально скачивать, спидтест показал что с инет все окей не знаю что эт

**Comment by Flowseal** [comment]
Могу лишь посоветовать сбросить найстроки сетевого адаптера, а также рекомендации по типу flushdns. Если вы удалили через service_remove.bat, то программа уже не работает.

**Comment by xxvvv1801** [comment]
> Могу лишь посоветовать сбросить найстроки сетевого адаптера, а также рекомендации по типу flushdns. Если вы удалили через service_remove.bat, то программа уже не работает.

ничего из этого не помогло мне, уже и драйвера переустанавливал и сбрасывал и на вирусы чекал не пойму в чем причина

**Comment by CHIRO52** [comment]
Привет, похожая проблема, но работает всё, кроме проводника. По типу такого
![image](https://github.com/user-attachments/assets/f63e33c5-46a1-4b56-a0bb-7716dcee70b1)

**Comment by Safenteril1** [comment]
Привет, решил проблему?

**Comment by CHIRO52** [comment]
> Привет, решил проблему?

Привет, да. Все оказалось далеко не в запрете. Я фотограф. И моя камера снимает в формате CR3. И чтобы просматривать фотографии в данном формате. Я решил скачать расширение на дефолтную прогу винды. И вот она и оказалась проблемой. Название не помню, но она там одна. От Майкрософт.
