### ISSUE TITLE
🟣 Обход Discord

### ISSUE THREAD

**Issue by FolkyFolk** [Flowseal/zapret-discord-youtube#394]
Всем здравствуйте, хотел спросить, как мне удалить окончательно запретник?

Немного расскажу, что да как. Я не особо шарю в кодинге и системных параметрах. Вчера вечером я захотел удалить запретник и обновить его на новый zip файл, но не могу удалить папку под названием "bin", в которой файл "WinDivert64". Я листал долго диспетчер, пытался хоть что-то найти, но ничего не нашёл, как его удалить с моего устройства?

Если кто-то ответит, то огромное спасибо вам. В гитхаб пишу первый раз, так что если будет криво, то постараюсь всё объяснить лично вам. :P
![изображение_2024-10-23_164203212](https://github.com/user-attachments/assets/43abc546-a1cc-45b4-b8be-1aba43d57d95)
![изображение_2024-10-23_164229587](https://github.com/user-attachments/assets/0fcf299f-fc2d-4d08-b79c-79cf909529c8)

**Comment by grosfae** [comment]
Если запуск был не через файл "service_install", то можно просто перезагрузить комп, и удалить спокойно, а  если через "service_install", то нужно запустить файл "service_remove", и потом удалить.

**Comment by ellerotta** [comment]
Выполни в командной строке (от имени Администратора) следующую команду:
`sc stop windivert && sc delete windivert`

После этого WinDivert64.sys можно будет удалить :)
