### ISSUE TITLE
Дискорд замедлился

### ISSUE THREAD

**Issue by sdarva** [Flowseal/zapret-discord-youtube#397]
У меня  версия Запрета 1.5.1 и перестал работать discord.bat впн не включал, вроде как всё работало нормально пару дней, но с вчерашнего дня скорость отправки сообщений, захода в голосовой канал стала замедлятся, сейчас же я не могу зайти в гс, а сообщения доходят через пол минуты, и времени требуется всё больше. Я пробовал перейти на старые версии, но там наблюдается таже проблема(теперь так как раньше функционировало). К тому же для полного удаления запрета требуется перезапуск компьютера так как WinDivert64.sys продолжает работу даже после удаления всех остальных файлов(так с каждой версией не только новой).

**Comment by sdarva** [comment]
В гс подключило спустя минут 30, но это всё равно является проблемой.

**Comment by Arkashik-v** [comment]
У меня версия запрета 1.5.1 оператор - Дом.ру, такая же проблема уже пару дней. Из своих наблюдений могу сказать, что проблема появляется преимущественно вечером во время наплыва пользователей.

**Comment by Ciao735** [comment]
Столкнулся с такой же проблемой, пока что никак не проверял. В Дискорде проблемы с подключением к войсам, +-минуту вижу снизу Аутенфикация, Подключение, после чего Голосовая связь подключена ещё +- секунд 10 и подключаюсь, демки тоже грузятся дольше. Диалоги грузятся секунд 10, просто серый экран, но после выше упомянутого времени вижу последнии сообщения. С чатами в серверах точно такая же проблема, как и с диалогами. Из своих заметок помимо дискорда стал плохо работать Riot Games, в целом престало логинить в лаучнчер. Пока что всё. Оператор Дом.ру. Версия 1.5.1, на более старой была такая же проблема.

**Comment by AureaFox** [comment]
Да-да, на дом.ру утром сегодня работало, а теперь снова ужасно

**Comment by JargozD** [comment]
>  стал плохо работать Riot Games, Оператор Дом.ру. 

такая-же проблема

**Comment by Dubstep4ik** [comment]
Всё так же. 
Скачал новую версию, ссылаясь на то, что версия устарела. Ничего не изменилось, еле-еле заходит в дискорд, в войс вовсе не могу зайти. Пишет "не удалось установить путь" через 5-10 минут попытки подключения

**Comment by Mav1337lk** [comment]
ДомРу, проблема та же, без bat вообще перестал грузить, с ним или с другими грузит очень медленно, некоторые игры умерли, к примеру сервера hoyoverse

**Comment by sdarva** [comment]
Кстати да у меня тоже ДомРу

**Comment by Mav1337lk** [comment]
Поддержка ДомРу как всегда говорить что это у всех так они не одни, да и вообще они не виноваты, предложили записать трассировку через WinMTR
По опыту проблем которые у них были где то пол года назад с серверами wow, че не пиши им, они ничего не сделают 
Остается верить что они починят

**Comment by Ballista11** [comment]
Со вчерашнего дня эта проблема, я дома только по вечерам и вечерами собсна уже второй день не работает дискорд. Дом ру

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/385
