### ISSUE TITLE
Майнинг вшит!

### ISSUE THREAD

**Issue by AnatolySnegovskiy** [Flowseal/zapret-discord-youtube#399]
Ты хотя бы напиши что ты майнишь через пользаков
![image](https://github.com/user-attachments/assets/70026095-a9f7-4809-aab5-3629276d49ea)

**Comment by natanrif** [comment]
🤡

**Comment by WardenGithub** [comment]
Друг, ты хоть ссылку открой, мб поумнеешь)

**Comment by cybersaber** [comment]
> Ты хотя бы напиши что ты майнишь через пользаков ![image](https://private-user-images.githubusercontent.com/11618162/379376030-70026095-a9f7-4809-aab5-3629276d49ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDI5MzgsIm5iZiI6MTcyOTcwMjYzOCwicGF0aCI6Ii8xMTYxODE2Mi8zNzkzNzYwMzAtNzAwMjYwOTUtYTlmNy00ODA5LWFhYjUtMzYyOTI3NmQ0OWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE2NTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5N2RiNjM2ZDgzYjMxZWVmMDE2NTY3NTI2OWUxMTM5NWNiOGExYThiODlkZTIxNzlmNzMyOTBmMDc3ZTAxZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HmzkmOH_PIpetcXf6lPyBpy_ei4b5qroooHmPckyT5k)

Откройте свойства файла и узнаете, что это часть названия файла в его описании, а этот кошелёк указан по той же ссылке, где вы можете прочитать, что на него автор библиотеки WinDivert собирает пожертвования и не более. От того, что вы увидели слово биткоин в описании файла, майнить файл не начнёт.

**Comment by Dronatar** [comment]
Вот он, сотрудник🤡ркн 😆

**Comment by exzolink** [comment]
Оформите пермач ему)

**Comment by AnatolySnegovskiy** [comment]
окей ребятки, я понял, перебдел и обосрался

**Comment by vasilyvelikolepniy-ux** [comment]
почему его нельзя удалить? если это безопасный файл, почему он запускается сам вместе с системой?
