### ISSUE TITLE
Проблема с service_discord_youtube.bat

### ISSUE THREAD

**Issue by sSakuray** [Flowseal/zapret-discord-youtube#4]
Запускают service_discord_youtube.bat , моментально открывается консоль и так же , моментально , закрывается. Следовательно , дс и ютуб не работают. 
Запускаю discord_youtube.bar - могу подключаться к каналам , но бесконечно соединение. Так же проблемы с ютубом , очень долго грузит. Когда подобная проблема с ютубом была в goodbye dpi - то я дописывал "goodbyedpi.exe -5 e1 q". Может подобное можно прописать где-то в файлах твоего резила? Можешь помочь с этим , пожалуйста?

**Comment by Flowseal** [comment]
> Запускают service_discord_youtube.bat , моментально открывается консоль и так же , моментально , закрывается. Следовательно , дс и ютуб не работают.

Запускаете от админа? В пути до файла нет пробелов?
Запустите файл через cmd (запустите cmd от имени администратора, откройте текущий каталог, пропишите service_discord_youtube.bat для запуска) и покажите, что выведется

> но бесконечно соединение

goodbyedpi закрыт?

Что касается долгой загрузки ютуба - всё зависит от провайдера к провайдеру. В оригинальном репозитории можете ознакомиться с другими флагами и параметрами: https://github.com/bol-van/zapret (nfqws)

**Comment by thefireKS** [comment]
Разрешите, влечу в обсуждения, пока sSakuray не появился. Такая же проблема, бесконечное подключение к голосовому каналу в дискорде.
У меня выводит вот такое в консоли:

```
C:\zapret-winws>set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="C:\zapret-winws\list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="C:\zapret-winws\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="C:\zapret-winws\quic_initial_www_google_com.bin" --new --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist="C:\zapret-winws\list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="C:\zapret-winws\tls_clienthello_www_google_com.bin" --new --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig

C:\zapret-winws>set SRVCNAME=zapret

C:\zapret-winws>net stop "zapret"
Неправильное имя службы.

Для вызова дополнительной справки наберите NET HELPMSG 2185.


C:\zapret-winws>sc delete "zapret"
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.


C:\zapret-winws>sc create "zapret" binPath= "\"C:\zapret-winws\winws.exe\" --wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="C:\zapret-winws\list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="C:\zapret-winws\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="C:\zapret-winws\quic_initial_www_google_com.bin" --new --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist="C:\zapret-winws\list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="C:\zapret-winws\tls_clienthello_www_google_com.bin" --new --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig" DisplayName= "zapret DPI bypass : winws1" start= auto
[SC] OpenSCManager: ошибка: 5:

Отказано в доступе.


C:\zapret-winws>sc description "zapret" "zapret DPI bypass software"
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.


C:\zapret-winws>sc start "zapret"
[SC] StartService: OpenService: ошибка: 1060:

Указанная служба не установлена.
```

Думаю, что там что-то тоже самое у sSakuray.
Возможно, дело и впрямь в провайдере, поскольку мне тоже пришлось колдовать с аргументами для GDPI

**Comment by Flowseal** [comment]
@thefireKS судя по логам, ваша ошибка связана с тем, что при создании сервиса не хватило прав. Запускайте cmd от имени администратора.

**Comment by thefireKS** [comment]
Извиняюсь, вы правы. Запустил через админку, сейчас вот такое выдаёт:

```
C:\zapret-winws>set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="C:\zapret-winws\list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="C:\zapret-winws\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="C:\zapret-winws\quic_initial_www_google_com.bin" --new --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist="C:\zapret-winws\list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="C:\zapret-winws\tls_clienthello_www_google_com.bin" --new --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig

C:\zapret-winws>set SRVCNAME=zapret

C:\zapret-winws>net stop "zapret"
Неправильное имя службы.

Для вызова дополнительной справки наберите NET HELPMSG 2185.


C:\zapret-winws>sc delete "zapret"
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.


C:\zapret-winws>sc create "zapret" binPath= "\"C:\zapret-winws\winws.exe\" --wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="C:\zapret-winws\list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="C:\zapret-winws\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="C:\zapret-winws\quic_initial_www_google_com.bin" --new --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist="C:\zapret-winws\list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="C:\zapret-winws\tls_clienthello_www_google_com.bin" --new --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig" DisplayName= "zapret DPI bypass : winws1" start= auto
[SC] CreateService: успех

C:\zapret-winws>sc description "zapret" "zapret DPI bypass software"
[SC] ChangeServiceConfig2: успех

C:\zapret-winws>sc start "zapret"

Имя_службы: zapret
        Тип                : 10  WIN32_OWN_PROCESS
        Состояние          : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        Код_выхода_Win32   : 0  (0x0)
        Код_выхода_службы  : 0  (0x0)
        Контрольная_точка  : 0x0
        Ожидание           : 0x0
        ID_процесса        : 1584
        Флаги              :
```

**Comment by Flowseal** [comment]
@thefireKS служба стартовала успешно. Подключение к каналам работает?

**Comment by thefireKS** [comment]
@Flowseal нет. 20 секунд идёт подключение, после - отключение и всё по-новой.

**Comment by Flowseal** [comment]
@thefireKS goodbyedpi включен?

**Comment by thefireKS** [comment]
@Flowseal нет, gdpi был выключен всё это время.

Также заметил, что интересная проблема возникает: после установки сервиса у меня нет доступа к некоторым основным сайтам, к примеру, яндекс и гугл, а также itch.io (случайно перебирал имеющиеся под рукой сайты) не работают. Выдавалась ошибка подключения к сайту. При этом, Telegram Web, VK и WhatsApp Web работали стабильно.

Ну и, как понимаете, к голосовому чату в дискорде я всё ещё не мог подключиться

**Comment by Flowseal** [comment]
Kyber выключен? chrome://flags/kyber#enable-tls13-kyber

А так, может зависеть от провайдера к провайдеру. Можете попробовать другие параметры аргумента --dpi-desync
> synack syndata fake fakeknown rst rstack hopbyhop destopt ipfrag1 disorder disorder2 split split2 ipfrag2 udplen tamper

> Атаки на udp более ограничены в возможностях. udp нельзя фрагментировать иначе, чем на уровне ip.
Для UDP действуют только режимы десинхронизации fake,hopbyhop,destopt,ipfrag1,ipfrag2,udplen,tamper.
Возможно сочетание fake,hopbyhop,destopt с ipfrag2, fake,fakeknown с udplen и tamper.
udplen увеличивает размер udp пакета на указанное в --dpi-desync-udplen-increment количество байтов.
Паддинг заполняется нулями по умолчанию, но можно задать свой паттерн.
Предназначено для обмана DPI, ориентирующегося на размеры пакетов.
Может сработать, если пользовательский протокол не привязан жестко к размеру udp пейлоада.
Режим tamper означает модификацию пакетов известных протоколов особенным для протокола образом.

**Comment by thefireKS** [comment]
Kyber выключен, да.

Будем пробовать другие параметры. Их же просто заменить вот здесь:
```
--filter-udp=443 --hostlist="%~dp0list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^
--filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^
--filter-tcp=443 --hostlist="%~dp0list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%~dp0tls_clienthello_www_google_com.bin"
```
Нужно, верно?

**Comment by Flowseal** [comment]
Да. 50000-65535 нужны для подключения к RTC. Если проблема с подключением к RTC - то можно попробовать другие параметры именно там.

**Comment by Oxsi-alt** [comment]
Ребятки привет! Подскажите, пожалуйста, скачал, все сделал, дискорд работает на отлично, но ютуб не грузит видео, тупо черный экран с загрузкой. У меня проводной интернет Билайн. Где и что нужно поменять, что бы заработал еще и ютуб, очень благодарен буду!

**Comment by Shurik244** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/8#issuecomment-2401622647
> Вы можете пользоваться привычным обходом ютуба (например, goodbyedpi) вместо с обходом только дискорда из этого репозитория. Обход ютуба зависит от провайдера к провайдеру и может требовать изменения аургментов.

**Comment by sSakuray** [comment]
> > Запускают service_discord_youtube.bat , моментально открывается консоль и так же , моментально , закрывается. Следовательно , дс и ютуб не работают.
> 
> Запускаете от админа? В пути до файла нет пробелов? Запустите файл через cmd (запустите cmd от имени администратора, откройте текущий каталог, пропишите service_discord_youtube.bat для запуска) и покажите, что выведется
> 
> > но бесконечно соединение
> 
> goodbyedpi закрыт?
> 
> Что касается долгой загрузки ютуба - всё зависит от провайдера к провайдеру. В оригинальном репозитории можете ознакомиться с другими флагами и параметрами: https://github.com/bol-van/zapret (nfqws)

Да , всё закрыто. Как скачал ваши файлы - ничего вообще не менял , то-есть , буквально копия. 
Вот что выдает консоль:C:\Users\navix\OneDrive\Рабочий стол\AS>sc create "zapret" binPath= "\"C:\Users\navix\OneDrive\Рабочий стол\AS\winws.exe\" --wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="C:\Users\navix\OneDrive\Рабочий стол\AS\list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="C:\Users\navix\OneDrive\Рабочий стол\AS\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="C:\Users\navix\OneDrive\Рабочий стол\AS\quic_initial_www_google_com.bin" --new --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist="C:\Users\navix\OneDrive\Рабочий стол\AS\list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="C:\Users\navix\OneDrive\Рабочий стол\AS\tls_clienthello_www_google_com.bin" --new --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig" DisplayName= "zapret DPI bypass : winws1" start= auto
Описание:
        Создание записи службы в реестре и в базе данных служб.
Использование:
        sc <сервер> create [имя службы] [binPath= ] <параметр1> <параметр2>...

Параметры:
Примечание. Имя параметра включает знак равенства (=).
      Между знаком равенства и значением параметра должен быть пробел.
 type= <own|share|interact|kernel|filesys|rec|userown|usershare>
       (по умолчанию = own)
 start= <boot|system|auto|demand|disabled|delayed-auto>
       (по умолчанию = demand)
 error= <normal|severe|critical|ignore>
       (по умолчанию = normal)
 binPath= <путь_к_двоичному_файлу_EXE>
 group= <группа_запуска>
 tag= <yes|no>
 depend= <зависимости (разделенные / (косой чертой))>
 obj= <имя_учетной_записи|имя_объекта>
       (по умолчанию = LocalSystem)
 DisplayName= <отображаемое имя>
 password= <пароль>

C:\Users\navix\OneDrive\Рабочий стол\AS>sc description "zapret" "zapret DPI bypass software"
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.


C:\Users\navix\OneDrive\Рабочий стол\AS>sc start "zapret"
[SC] StartService: OpenService: ошибка: 1060:

Указанная служба не установлена.


C:\Users\navix\OneDrive\Рабочий стол\AS>

**Comment by Flowseal** [comment]
@sSakuray  У вас пробел в пути до файла \Рабочи**й с**тол\

**Comment by sSakuray** [comment]
> @sSakuray У вас пробел в пути до файла \Рабочи**й с**тол\

исправил. Перенес все просто в папку на диске c.

Microsoft Windows [Version 10.0.19045.4957]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Windows\system32>cd C:\zapretr

C:\zapretr>service_discord_youtube.bat

C:\zapretr>set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="C:\zapretr\list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="C:\zapretr\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="C:\zapretr\quic_initial_www_google_com.bin" --new --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist="C:\zapretr\list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="C:\zapretr\tls_clienthello_www_google_com.bin" --new --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig

C:\zapretr>set SRVCNAME=zapret

C:\zapretr>net stop "zapret"
Служба "zapret DPI bypass : winws1" останавливается..
Служба "zapret DPI bypass : winws1" успешно остановлена.


C:\zapretr>sc delete "zapret"
[SC] DeleteService: успех

C:\zapretr>sc create "zapret" binPath= "\"C:\zapretr\winws.exe\" --wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=80,443,50000-65535 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="C:\zapretr\list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="C:\zapretr\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="C:\zapretr\quic_initial_www_google_com.bin" --new --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist="C:\zapretr\list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="C:\zapretr\tls_clienthello_www_google_com.bin" --new --dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig" DisplayName= "zapret DPI bypass : winws1" start= auto
[SC] CreateService: успех

C:\zapretr>sc description "zapret" "zapret DPI bypass software"
[SC] ChangeServiceConfig2: успех

C:\zapretr>sc start "zapret"

Имя_службы: zapret
        Тип                : 10  WIN32_OWN_PROCESS
        Состояние          : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        Код_выхода_Win32   : 0  (0x0)
        Код_выхода_службы  : 0  (0x0)
        Контрольная_точка  : 0x0
        Ожидание           : 0x0
        ID_процесса        : 4840
        Флаги              :

C:\zapretr>


Пишет теперь вот это , что в голосовые каналы все равно отказывается подключаться.(Если что , моя сеть - МГТС).

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
