### ISSUE TITLE
valorant

### ISSUE THREAD

**Issue by h4m3RRRRRRR** [Flowseal/zapret-discord-youtube#400]
может ли из-за обхода не работать riot games и valorant? сейчас у многих не работает, может дело в нем?

**Comment by Zineo0** [comment]
Та же проблема, но дело видимо не в обходе. Не входило в акк в лаунчере риотов, я вырубил обход, перезапустил комп, запускаю чисто лаунчер риотов и всё также

**Comment by h4m3RRRRRRR** [comment]
> Та же проблема, но дело видимо не в обходе. Не входило в акк в лаунчере риотов, я вырубил обход, перезапустил комп, запускаю чисто лаунчер риотов и всё также

у меня тож не входит в акк, пишет: "Не удалось авторизоваться. Повторите попытку позже." Уже примерно часа полтора такая тема

**Comment by Zineo0** [comment]
> > Та же проблема, но дело видимо не в обходе. Не входило в акк в лаунчере риотов, я вырубил обход, перезапустил комп, запускаю чисто лаунчер риотов и всё также
> 
> у меня тож не входит в акк, пишет: "Не удалось авторизоваться. Повторите попытку позже." Уже примерно часа полтора такая тема

Вот да, также пишет. Но на сайте в акк вроде вошло, мб со стороны риотов проблема

**Comment by h4m3RRRRRRR** [comment]
> > > Та же проблема, но дело видимо не в обходе. Не входило в акк в лаунчере риотов, я вырубил обход, перезапустил комп, запускаю чисто лаунчер риотов и всё также
> > 
> > 
> > у меня тож не входит в акк, пишет: "Не удалось авторизоваться. Повторите попытку позже." Уже примерно часа полтора такая тема
> 
> Вот да, также пишет. Но на сайте в акк вроде вошло, мб со стороны риотов проблема

надо у людей поузнавать, у кого работает, у кого нет
и юзал ли этот человек обход
(у меня на сайт тоже заходит)

**Comment by Zineo0** [comment]
> > > > Та же проблема, но дело видимо не в обходе. Не входило в акк в лаунчере риотов, я вырубил обход, перезапустил комп, запускаю чисто лаунчер риотов и всё также
> > > 
> > > 
> > > у меня тож не входит в акк, пишет: "Не удалось авторизоваться. Повторите попытку позже." Уже примерно часа полтора такая тема
> > 
> > 
> > Вот да, также пишет. Но на сайте в акк вроде вошло, мб со стороны риотов проблема
> 
> надо у людей поузнавать, у кого работает, у кого нет и юзал ли этот человек обход

я щас чекаю комменты в канале тг под группой с валиком и каждый второй пишет об этой проблеме

**Comment by h4m3RRRRRRR** [comment]
> > > > > Та же проблема, но дело видимо не в обходе. Не входило в акк в лаунчере риотов, я вырубил обход, перезапустил комп, запускаю чисто лаунчер риотов и всё также
> > > > 
> > > > 
> > > > у меня тож не входит в акк, пишет: "Не удалось авторизоваться. Повторите попытку позже." Уже примерно часа полтора такая тема
> > > 
> > > 
> > > Вот да, также пишет. Но на сайте в акк вроде вошло, мб со стороны риотов проблема
> > 
> > 
> > надо у людей поузнавать, у кого работает, у кого нет и юзал ли этот человек обход
> 
> я щас чекаю комменты в канале тг под группой с валиком и каждый второй пишет об этой проблеме

я тож, но надо понять, это только у тех кто юзал обход или это рандомно как-то

**Comment by Ciao735** [comment]
Такая же проблема, и также пробывал вырубать zapret, перезапускал пк и проблема остаётся.

**Comment by Moricis** [comment]
> Такая же проблема, и также пробывал вырубать zapret, перезапускал пк и проблема остаётся.

у меня дом ру сейчас тоже риот геймс лаунчер не заходит, но утром вал, так же как и обход работал

**Comment by houken88** [comment]
аналогично, кста ночью все нормально работает

**Comment by Zineo0** [comment]
> > Такая же проблема, и также пробывал вырубать zapret, перезапускал пк и проблема остаётся.
> 
> у меня дом ру сейчас тоже риот геймс лаунчер не заходит, но утром вал, так же как и обход работал

Тоже с дом ру сижу кстати. Походу у них какие-то приколы начались опять

**Comment by Moricis** [comment]
> > > Такая же проблема, и также пробывал вырубать zapret, перезапускал пк и проблема остаётся.
> > 
> > 
> > у меня дом ру сейчас тоже риот геймс лаунчер не заходит, но утром вал, так же как и обход работал
> 
> Тоже с дом ру сижу кстати. Походу у них какие-то приколы начались опять

я позвонил в дом ру. Вот что они мне ответили https://www.youtube.com/watch?v=UVg9hqwGwao

**Comment by DarkYuuki** [comment]
Подтверждаю, вместе с очень сильно тормозящим дискордом в лигу тоже нельзя зайти. Дом ру.

**Comment by h4m3RRRRRRR** [comment]
тоже дом.ру, все лежит...

**Comment by yoursamurai** [comment]
Примерно в 18:10 по мск заметил трабл с авторизацией в райот клиент+ не смог зайти в войс канал дискорда, также начались траблы с прогрузкой серверов(текстовые каналы грузит по минуте, картинки/гифки аналогично).Пользуюсь обходом дискорд+ютьюб. Провайдер - дом.ру...

**Comment by Moricis** [comment]
> Примерно в 18:10 по мск заметил трабл с авторизацией в райот клиент+ не смог зайти в войс канал дискорда, также начались траблы с прогрузкой серверов(текстовые каналы грузит по минуте, картинки/гифки аналогично).Пользуюсь обходом дискорд+ютьюб. Провайдер - дом.ру...

Абсолютно все так же, хотя утром и днем все норм было

**Comment by houken88** [comment]
Как пофиксить??.......

**Comment by Mav1337lk** [comment]
> Как пофиксить??.......

верой в чудо

**Comment by DarkYuuki** [comment]
вчера ближе к полночи по мск само пофиксилось. и видимо до вечера сегодня все более менее работало.

**Comment by h4m3RRRRRRR** [comment]
у вас у всех домру?

**Comment by Mav1337lk** [comment]
> у вас у всех домру?

да скорее всего у всех

**Comment by houken88** [comment]
У всех домру, да

**Comment by yoursamurai** [comment]
проблема не с методом обхода, а с провайдером, поэтому думаю тему можно закрыть

**Comment by Ciao735** [comment]
> проблема не с методом обхода, а с провайдером, поэтому думаю тему можно закрыть

+, подозреваю что виновата не прога а провайдер, остаётся либо слёзно молить дом ру что бы подрубили обратно видео игрушку либо ждать(терпеть)

**Comment by Flowseal** [comment]
Спрашивайте у дом.ру, что ещё могу посоветовать 🫡
