### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by SniffRx** [Flowseal/zapret-discord-youtube#402]
![image](https://github.com/user-attachments/assets/f303a4b7-cd84-4401-a6e3-e80280fa4daa)

**Comment by exzolink** [comment]
Полистай хоть другие подобные ишью или README прочти. Боишься - да, вирус, не ставь и уходи.
По 10 ишью в день плодят, хоть бы одному мозгов хватило почитать

**Comment by gg-script** [comment]
Ебаный пиздец. На гитхабе зарегистрироваться смог, а пойти и почитать инфу - нет. К твоему глубокому сожалению WinDivert не является вирусом, он всего лишь представляет собой легитимный (законный, правомерный) инструмент, используемый В ДАННОМ СЛУЧАЕ для ПЕРЕХВАТА и МОДИФИКАЦИИ сетевых пакетов на уровне драйвера. Ты запускаешь его сам и видишь с какими параметрами, да, например, его можно использовать для создания вредоносного ПО, которое перехватывает и изменяет сетевой трафик, но в данном случае оно используется не для этого.

**Comment by Flowseal** [comment]
Читайте README

**Comment by SniffRx** [comment]
> Ебаный пиздец. На гитхабе зарегистрироваться смог, а пойти и почитать инфу - нет. К твоему глубокому сожалению WinDivert не является вирусом, он всего лишь представляет собой легитимный (законный, правомерный) инструмент, используемый В ДАННОМ СЛУЧАЕ для ПЕРЕХВАТА и МОДИФИКАЦИИ сетевых пакетов на уровне драйвера. Ты запускаешь его сам и видишь с какими параметрами, да, например, его можно использовать для создания вредоносного ПО, которое перехватывает и изменяет сетевой трафик, но в данном случае оно используется не для этого.



> Полистай хоть другие подобные ишью или README прочти. Боишься - да, вирус, не ставь и уходи. По 10 ишью в день плодят, хоть бы одному мозгов хватило почитать

Я не понимаю, почему люди такие токсичные? Я просто задал вопрос, потому что хотел получить ответ на него, разобраться, а вы начинаете оскорблять. Вот после таких как вы и умирает ру комьюнити

**Comment by gg-script** [comment]
> > Ебаный пиздец. На гитхабе зарегистрироваться смог, а пойти и почитать инфу - нет. К твоему глубокому сожалению WinDivert не является вирусом, он всего лишь представляет собой легитимный (законный, правомерный) инструмент, используемый В ДАННОМ СЛУЧАЕ для ПЕРЕХВАТА и МОДИФИКАЦИИ сетевых пакетов на уровне драйвера. Ты запускаешь его сам и видишь с какими параметрами, да, например, его можно использовать для создания вредоносного ПО, которое перехватывает и изменяет сетевой трафик, но в данном случае оно используется не для этого.
> 
> > Полистай хоть другие подобные ишью или README прочти. Боишься - да, вирус, не ставь и уходи. По 10 ишью в день плодят, хоть бы одному мозгов хватило почитать
> 
> Я не понимаю, почему люди такие токсичные? Я просто задал вопрос, потому что хотел получить ответ на него, разобраться, а вы начинаете оскорблять. Вот после таких как вы и умирает ру комьюнити

Потому что надо было открыть issues закрытые и почитать их. RU комьюнити начинает умирать когда люди задают одинаковые вопросы, хотя ранее на них уже ответили. Это тоже самое что верховный суд будет каждый раз выносить новые решения не обращаясь к опыту прошлых дел.
