### ISSUE TITLE
Discord Замедление [Dom.ru]

### ISSUE THREAD

**Issue by Werksyt** [Flowseal/zapret-discord-youtube#403]
Работает то работает дискорд, но проблема в медленном трафике. Грузит все очень долго, в войс заходит по 10-20 сек. Чаты грузит также долго. Подскажите конфиги или действия, чтобы от этого избавится
Провайдер: Dom.ru

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/385
