### ISSUE TITLE
Как включить discord-youtube в фоновом режиме, чтобы работал на фоне, а не приложением, и включался автоматически после перезагрузки ПК?

### ISSUE THREAD

**Issue by Ankoe080** [Flowseal/zapret-discord-youtube#410]
![Screenshot_114](https://github.com/user-attachments/assets/f81b4210-b283-4cf4-a7d5-1e5c5d85abe9)

**Comment by Flowseal** [comment]
service_install

**Comment by Ankoe080** [comment]
> service_install

А надо там что-то прописывать, чтобы она начала работать?
