### ISSUE TITLE
Могут ли заблокировать в играх(например:The Finals) за обход блокировки дискорда?

### ISSUE THREAD

**Issue by Kirkas12** [Flowseal/zapret-discord-youtube#415]

**Comment by DieInCalamity** [comment]
врядли

**Comment by serpen7** [comment]
вряд ли потому что программа не работает для них, она работает с тем что прописано у нее в листах. Однако как и с гудбайдпи, некоторые античиты игр могут закрыть игру или закрыть программу потому что посчитают ее подозрительной для модификации пакетов на сервер и сработать. Но пока что таковых я особо не встречал.
