### ISSUE TITLE
Сегодня перестали работать голосовые каналы в Discord [SkyNet] [решено]

### ISSUE THREAD

**Issue by Derbrent** [Flowseal/zapret-discord-youtube#417]
Перестали работать голосовые каналы. Есть какие решения ? 
Использую версию 1.5.1
провайдер SkyNet

**Comment by LucSkywalkerRu** [comment]
У вас случайно не установлена программа AdGuard? У меня после обновления AdGuard перестали работать голосовые каналы в Discord, но я добавил в исключения AdGuard'a ссылки на дискорд и IP-адреса из файла ipset-discord.txt и у меня заработало подключение к голосовым каналам Discord. У меня провайдер Goodline (Кузбасс)

**Comment by lowdeepskill** [comment]
> У вас случайно не установлена программа AdGuard? У меня после обновления AdGuard перестали работать голосовые каналы в Discord, но я добавил в исключения AdGuard'a ссылки на дискорд и IP-адреса из файла ipset-discord.txt и у меня заработало подключение к голосовым каналам Discord. У меня провайдер Goodline (Кузбасс)

Спасибо большое, помогло. Но чуть иначе сделал: настройки > сеть > "список фильтруемых приложений" > убрал галочку с Дискорда и всё заработало.

**Comment by Derbrent** [comment]
> У вас случайно не установлена программа AdGuard? У меня после обновления AdGuard перестали работать голосовые каналы в Discord, но я добавил в исключения AdGuard'a ссылки на дискорд и IP-адреса из файла ipset-discord.txt и у меня заработало подключение к голосовым каналам Discord. У меня провайдер Goodline (Кузбасс)

Да. Установлен AdGuard.
А где вы исключения прописывали ?

> Спасибо большое, помогло. Но чуть иначе сделал: настройки > сеть > "список фильтруемых приложений" > убрал галочку с Дискорда и всё заработало.

Проделал то же самое, внес Дискорд в исключение. И всё заработало, к голосовым подключается.

**Спасибо!**

**Comment by Beefut** [comment]
> У вас случайно не установлена программа AdGuard? У меня после обновления AdGuard перестали работать голосовые каналы в Discord, но я добавил в исключения AdGuard'a ссылки на дискорд и IP-адреса из файла ipset-discord.txt и у меня заработало подключение к голосовым каналам Discord. У меня провайдер Goodline (Кузбасс)

А можете подсказать пожалуйста, куда именно вы вписывали ссылки из файла  ipset-discord.txt ? 
Ибо я пошел сначала по простому методу и сделал по методу "настройки > сеть > "список фильтруемых приложений" > убрал галочку с Дискорда" - но увы, это мне не помогло 

UPD. не просто добавил в исключение Дискорд, а полностью снес AdGuard, все равно вечное подключение в дс.. 
UPD2. IPшники вписал, все равно не помогает

**Comment by LucSkywalkerRu** [comment]
IP-адреса из файла ipset-discord.txt прописывал в разделе Основные настройки > Расширенные настройки > листаем вниз до раздела Диапазоны IP-адресов, исключенные из фильтрации

> > У вас случайно не установлена программа AdGuard? У меня после обновления AdGuard перестали работать голосовые каналы в Discord, но я добавил в исключения AdGuard'a ссылки на дискорд и IP-адреса из файла ipset-discord.txt и у меня заработало подключение к голосовым каналам Discord. У меня провайдер Goodline (Кузбасс)
> 
> А можете подсказать пожалуйста, куда именно вы вписывали ссылки из файла ipset-discord.txt ? Ибо я пошел сначала по простому методу и сделал по методу "настройки > сеть > "список фильтруемых приложений" > убрал галочку с Дискорда" - но увы, это мне не помогло
> 
> UPD. не просто добавил в исключение Дискорд, а полностью снес AdGuard, все равно вечное подключение в дс.. UPD2. IPшники вписал, все равно не помогает

IP-адреса из файла ipset-discord.txt прописывал в разделе Основные настройки > Расширенные настройки > листаем вниз до раздела Диапазоны IP-адресов, исключенные из фильтрации

**Comment by masterworgen** [comment]
Помогло отключение адгуарда, спс

**Comment by Ekafik** [comment]
а кто знает,что делать если ты скачал zapret для дс, но у тебя не работают голосовые каналы? (нету звука, и не показывается что ты говоришь)

**Comment by rpo6oBLLjuk** [comment]
У меня идентичная проблема с нерабочим Voice-чатом, однако AdGuard не ставил, антивирусы тоже
Upd: брандмауэр отключён

**Comment by Lzhec41** [comment]
Огромное спасибо человекам, которые написали про AdGuard и пути решения. 2 дня искал проблему, пробовал разные версии zapret'ов, но даже в голову не пришло что дело в этой софтине. 

Дополню со скринами для тех, кто на смог найти что-то в настройках:
Вариант 1. Исключение из списка фильтруемых приложений:
![image](https://github.com/user-attachments/assets/ae070771-62cf-4194-8b16-122d582cfed6)
![image](https://github.com/user-attachments/assets/7b7e8c0f-8e25-4e06-ba17-a11c0687cd29)

Вариант 2. Исключение из списка фильтруемых приложений методом добавления пути:
![image](https://github.com/user-attachments/assets/4146aa25-4423-4b00-8356-8c88b47bcb41)
![image](https://github.com/user-attachments/assets/772b0af4-3bdd-409b-bcbd-5eeb25aa17ea)

Мне помог первый вариант.

**Comment by OpticalLines** [comment]
не установлены впн и прочее, отсутствует адгуард, подключение можно ждать час, помогите решить проблему

**Comment by Soawy89** [comment]
Все выше перечисленное сделал и голосовые каналы не заработали. что делать?

**Comment by zaklame** [comment]
AdGuard не установлен, антивирус и брэндмауэр выключен. Не работает запрет, провайдер - Ростелеком, что делать? Все советы, что были выше  и написаны в самой теме пробовал

**Comment by Spaser14** [comment]
Всем привет. Всё работало идеально, до текущего часа. Запустил обход. Зашел в дискорд. всё окей, через час отрыгнул, перезашел и теперь вечно висящая "подключение к RTC". провайдер мегафон. Пробовал и в браузере, тоже самое. Сам дискорд работает. сообщения могу отправлять. Помогите.

**Comment by MikeVSI** [comment]
Вечер. Провайдер wifire, нет адгарда, все работало вчера, сегодня подключение к RTC и висит

**Comment by MikeVSI** [comment]
> Вечер. Провайдер wifire, нет адгарда, все работало вчера, сегодня подключение к RTC и висит

UPD под general пока вроде работает

**Comment by Vladislavik-rus** [comment]
Привецтвую, испытываю схожие проблемы, что и [Soawy89](https://github.com/Soawy89), только дискорд у меня дальше проверки обновлений не уходит.
Я также испробовал все предложенные выше варианты, даже отключал AdGuard автозапуск с системой. Но дискорд по-прежнему через Запрет не работает.

**Comment by MiceMason** [comment]
Всем привет, 1.6.2 не работает полностью, только пишет update и секунды. Сначала перестал работать войс и т.д., а теперь во
все перестал работать. Нажал на все general. Можете помочь.

**Comment by drobovik69** [comment]
Всем ку, был скачен мною ад гуард впн и не разобравшись обратно удалил данный впн и всеравно не работает обход, что делать? подскажите пожалуйста

**Comment by Yury196721** [comment]
Доброго времени суток, версия  1.6.3 не работает голосовой дискорд, постоянное подключение в голосовой канал, кто-нибудь решил данную проблему?

**Comment by Vitalyplay** [comment]
Не работают голосовые каналы есть ли какое то решение? Провайдер Билайн.

**Comment by razor179** [comment]
На МГТС не работают голосовые каналы ни через ВПН ни через любые другие "вещи".

**Comment by dooexs** [comment]
Всем привет, не заходит в голосовые каналы, хотя писать и смотреть новые сообщения можно
