### ISSUE TITLE
Call Of Duty black ops 6 не запускается!

### ISSUE THREAD

**Issue by ElektroSSx** [Flowseal/zapret-discord-youtube#421]
игра не запускается когда ползуюсь обход, можем ожидать решение?

**Comment by HarGabt** [comment]
Проблема скорее всего в WinDivert, в GoodbyeDPI обсуждалось подобное:

https://github.com/ValdikSS/GoodbyeDPI/issues/148
https://github.com/ValdikSS/GoodbyeDPI/issues/172
