### ISSUE TITLE
донт ворк чё то

### ISSUE THREAD

**Issue by Mashir0ch** [Flowseal/zapret-discord-youtube#422]
![image](https://github.com/user-attachments/assets/2a56f809-80e4-41d9-a9a0-5678bc18aac0)
при запуске батника discord_youtube от админа появляется эта штука (у друга не у меня) но мой батник выглядит по другому и естественно у него не работает

**Comment by Flowseal** [comment]
Путь до файла не найден. Съел антивирус бинарники либо не скопировал папку bin
