### ISSUE TITLE
Бесконечное подколючение в Discord

### ISSUE THREAD

**Issue by Asura1928** [Flowseal/zapret-discord-youtube#424]
Ютуб и всё остальное прекрасно работает, дискорд просто запускается, но у меня просто бесконечное подключение к чату или серверу. пытался найти сервисы killer. но у меня их попросту нету

**Comment by Eptiy** [comment]
Adguard есть? Попробуй выключить.

**Comment by Mehanik511** [comment]
> Adguard есть? Попробуй выключить.

Спасибо, помогло!
Действительно, с ним проблема - чего-то они намутили с маршрутами, видимо.

**Comment by HellPainter4** [comment]
Та же история. Открыл от админа, не помогает. Добавил в исключение для дрВеб, не помогает.

**Comment by EvgenezBond** [comment]
Да кстати Adguard после недавней обновы начал блочить войс в дискорде. Причем если включен браузерный помощник он даже в игре его плавающий значек появлялся...) А как добавить "запрет" в исключение Adguard?

**Comment by Flowseal** [comment]
> Да кстати Adguard после недавней обновы начал блочить войс в дискорде. Причем если включен браузерный помощник он даже в игре его плавающий значек появлялся...) А как добавить "запрет" в исключение Adguard?

https://github.com/Flowseal/zapret-discord-youtube/issues/417
