### ISSUE TITLE
Как ты это объяснишь? 

### ISSUE THREAD

**Issue by ZeN4lth** [Flowseal/zapret-discord-youtube#425]
скачал запрет и захожу файлики чекать, то что там вирусы я заигнорил но чтоб вот так нагло показывать свой майнер и кошелек с биткоина это полная дичь
![photo_2024-10-27_04-49-48](https://github.com/user-attachments/assets/0c1062d1-450a-4e7f-8331-1afe4d9f5f8d)

**Comment by Dronatar** [comment]
Как ты это подтвердишь? 🤡

**Comment by LolikonhikSD** [comment]
Ещё один 🤡

**Comment by Eptiy** [comment]
Да капец вы конечно, это ссылка на донаты разрабу виндайверта. Совсем сами чекнуть информацию не можете? Вбивается в 2 счёта кошелёк или сайт и узнаётся их владелец. Нет там никаких майнеров.
Офай ишью с позором.

**Comment by serpen7** [comment]
Это номер биткоин кошелеька в описании файла от создателя виндайверта, чтобы те кто захотел могли поддержать его. Ты бы хоть по ссылке перешел сначала, которая там же указана, почитал бы. Тот же виндайверт использует и гудбайдпи. 

> Windows Packet Divert (WinDivert) — это пакет захвата и перенаправления пакетов в пользовательском режиме для Windows 10, Windows 11 и Windows Server.
> 
> WinDivert позволяет приложениям пользовательского режима захватывать/изменять/отбрасывать сетевые пакеты, отправляемые в/из сетевого стека Windows. Подводя итог, WinDivert может:
> 
> захват сетевых пакетов
> фильтровать/отбрасывать сетевые пакеты
> прослушивание сетевых пакетов
> (повторно)внедрить сетевые пакеты
> изменить сетевые пакеты
> WinDivert можно использовать для реализации фильтров пакетов пользовательского режима, анализаторов пакетов, брандмауэров, NAT, VPN, приложений туннелирования и т. д.

**Comment by Flowseal** [comment]
Лицо человека, который вставляет биткоин кошелёк в описание файла с майнером предстаили?

**Comment by Enot413** [comment]
Докозать я это не смогу не как (видео\скрина нету). Но у меня в принцепе обход этот не хотел работать появлялась cmd и сразу пропадала. Но суть в том что сегодня при запуске пк у меня защитник пожаловался на этот файл (как я сказал я ничего не скринел и просто запустил очистку и про сканировал через антивирус dr web, больше жалоб не было.) Но факт в том что у меня название файла было такое же я не отрицаю что возможет и майнер. Я уже ничему не удивлюсь.

**Comment by serpen7** [comment]
> Докозать я это не смогу не как (видео\скрина нету). Но у меня в принцепе обход этот не хотел работать появлялась cmd и сразу пропадала. Но суть в том что сегодня при запуске пк у меня защитник пожаловался на этот файл (как я сказал я ничего не скринел и просто запустил очистку и про сканировал через антивирус dr web, больше жалоб не было.) Но факт в том что у меня название файла было такое же я не отрицаю что возможет и майнер. Я уже ничему не удивлюсь.

он и будет жаловаться потому что это во первых подозрительный для него драйвер стороннего фильтра трафика, во вторых  если вы скачаете его незнамо откуда, незнамо от кого из интернета кто может так же его использовать в злонамеренных целях - вы получите полноценный троян, который будет лить чуть ли не весь ваш трафик. Даже касперский говорит что это не вирус но 
![image](https://github.com/user-attachments/assets/cc0fb0e0-e7bf-4110-83a3-1b24b7af91ea)

В интернетах уже распространяются сборки, особенно через ютуб с фейковыми версиями проги запрета, которые содержат вирусный winws1.exe на 22 помоему мегабайта с чем-то. И который вполне себе вирус использующий так же драйвер виндайверта вкупе с собой, чтобы навредить людям. Так что будьте осторожны если качаете незнамо от кого и откуда в интернете сборки запрета или гудбайдпи, использующие виндайверт фильтр трафика.

**Comment by KOT31506** [comment]
На днях скачал такой обход теперь вот такая беда 
![Screenshot_1](https://github.com/user-attachments/assets/e7a5044a-71b6-4f28-819a-60a43f590506)

Сейчас пытаюсь почистить 
Так как этот файл бесконечно

**Comment by serpen7** [comment]
> На днях скачал такой обход теперь вот такая беда ![Screenshot_1](https://private-user-images.githubusercontent.com/89294963/397942535-e7a5044a-71b6-4f28-819a-60a43f590506.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDMyMjAsIm5iZiI6MTczNDgwMjkyMCwicGF0aCI6Ii84OTI5NDk2My8zOTc5NDI1MzUtZTdhNTA0NGEtNzFiNi00ZjI4LTgxOWEtNjBhNDNmNTkwNTA2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE3NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMWFiY2RjODQ0MTdmY2MwMzM5YWJlNzRlOGFiODAzMzIwYzdhYzMyZWFjNTI2N2MwNWEzNGE4YjYzZjIwZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qtQR-i38o5PzybtBKIv5_fiU_n2dyk4Jx_k4YK-Us04)
> 
> Сейчас пытаюсь почистить Так как этот файл бесконечно

а это обход разве? 
![image](https://github.com/user-attachments/assets/df8d8c5b-1595-4bf2-a356-788e2dd0ffbb)

Вирус майнер как бы сам по себе не запустишь, он защищен и не будет виден человеку консолью. А вот обычный свой майнер будет виден на котором сам майнишь именно через консоль. Просто потому что там можно тогда посмотреть в нем биткоин адрес кошелька чуть ли не открыто в самой консоли. Хотя может и не показываться, однако файл с кошель адресом тогда вычислить не особо сложно.

Как пример собственного майнера с opencl на амд 
![image](https://github.com/user-attachments/assets/e83475b0-8d55-4689-984b-2fecab662781)
![image](https://github.com/user-attachments/assets/0904e49d-9354-47a4-8b1e-a4b7a9eff0e7)

**Comment by KOT31506** [comment]
> > На днях скачал такой обход теперь вот такая беда ![Screenshot_1](https://private-user-images.githubusercontent.com/89294963/397942535-e7a5044a-71b6-4f28-819a-60a43f590506.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDMyMjAsIm5iZiI6MTczNDgwMjkyMCwicGF0aCI6Ii84OTI5NDk2My8zOTc5NDI1MzUtZTdhNTA0NGEtNzFiNi00ZjI4LTgxOWEtNjBhNDNmNTkwNTA2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE3NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMWFiY2RjODQ0MTdmY2MwMzM5YWJlNzRlOGFiODAzMzIwYzdhYzMyZWFjNTI2N2MwNWEzNGE4YjYzZjIwZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qtQR-i38o5PzybtBKIv5_fiU_n2dyk4Jx_k4YK-Us04)
> > Сейчас пытаюсь почистить Так как этот файл бесконечно
> 
> а это обход разве? ![image](https://private-user-images.githubusercontent.com/134365619/397943822-df8d8c5b-1595-4bf2-a356-788e2dd0ffbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTMxODAsIm5iZiI6MTczNDg1Mjg4MCwicGF0aCI6Ii8xMzQzNjU2MTkvMzk3OTQzODIyLWRmOGQ4YzViLTE1OTUtNGJmMi1hMzU2LTc4OGUyZGQwZmZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwNzM0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTJmYzY2MTJmMGUzNDE5MzJiOGRjNjg2ZTVjY2E4NWMwMDY1YmY3MTMyMTQyY2QzNGU2YWRmOTA1MWUzYThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sEv8QdicXLvZ0LJVWqhxPT238x4gTdMO3x298eVVFhw)
> 
> Вирус майнер как бы сам по себе не запустишь, он защищен и не будет виден человеку консолью. А вот обычный свой майнер будет виден на котором сам майнишь именно через консоль. Просто потому что там можно тогда посмотреть в нем биткоин адрес кошелька чуть ли не открыто в самой консоли. Хотя может и не показываться, однако файл с кошель адресом тогда вычислить не особо сложно.
> 
> Как пример собственного майнера с opencl на амд ![image](https://private-user-images.githubusercontent.com/134365619/397944353-e83475b0-8d55-4689-984b-2fecab662781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTMxODAsIm5iZiI6MTczNDg1Mjg4MCwicGF0aCI6Ii8xMzQzNjU2MTkvMzk3OTQ0MzUzLWU4MzQ3NWIwLThkNTUtNDY4OS05ODRiLTJmZWNhYjY2Mjc4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwNzM0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmIwNDBiYjY2ODhkNzA4NGI3NDM2OTY1Mzk2YmJiZjQzZWMwNTEyOWQyYWI3ZGEyYjBmY2I0NWQ4NmY5NTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BH2DAy9C1HHKrTjN1vHDmcbfRxz8emQ7q9JCa_nL3js) ![image](https://private-user-images.githubusercontent.com/134365619/397944404-0904e49d-9354-47a4-8b1e-a4b7a9eff0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTMxODAsIm5iZiI6MTczNDg1Mjg4MCwicGF0aCI6Ii8xMzQzNjU2MTkvMzk3OTQ0NDA0LTA5MDRlNDlkLTkzNTQtNDdhNC04YjFlLWE0YjdhOWVmZjBlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwNzM0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTFhZGEwNmNhYjI5MjdmNmFjYjgwMmM1MmRlYTNiNGNlYjFjODIyMzkwYjZlOTU0ZjMxNjllYWQzZDlkMWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NbyYnc6pXrDPR-oo9uaDrdwECd0SkwqZmZ6Uh18-9ic)

Да это обход майнер лежал в нем+ троян (не один из антивирусов его не видел) заблокировал восстановление системы на ошибку 0xc00000017 
Помогла только полная переустановка системы (после чего запустил повторно обход ютуб именно эту версию) майнер прописался в видеокарту (шумел как самолёт в момент запуска) (через regedit путь как раз был до обходчика ютуб)

**Comment by KOT31506** [comment]
.

**Comment by serpen7** [comment]
> > > На днях скачал такой обход теперь вот такая беда ![Screenshot_1](https://private-user-images.githubusercontent.com/89294963/397942535-e7a5044a-71b6-4f28-819a-60a43f590506.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDMyMjAsIm5iZiI6MTczNDgwMjkyMCwicGF0aCI6Ii84OTI5NDk2My8zOTc5NDI1MzUtZTdhNTA0NGEtNzFiNi00ZjI4LTgxOWEtNjBhNDNmNTkwNTA2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE3NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMWFiY2RjODQ0MTdmY2MwMzM5YWJlNzRlOGFiODAzMzIwYzdhYzMyZWFjNTI2N2MwNWEzNGE4YjYzZjIwZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qtQR-i38o5PzybtBKIv5_fiU_n2dyk4Jx_k4YK-Us04)
> > > Сейчас пытаюсь почистить Так как этот файл бесконечно
> > 
> > 
> > а это обход разве? ![image](https://private-user-images.githubusercontent.com/134365619/397943822-df8d8c5b-1595-4bf2-a356-788e2dd0ffbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTMxODAsIm5iZiI6MTczNDg1Mjg4MCwicGF0aCI6Ii8xMzQzNjU2MTkvMzk3OTQzODIyLWRmOGQ4YzViLTE1OTUtNGJmMi1hMzU2LTc4OGUyZGQwZmZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwNzM0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTJmYzY2MTJmMGUzNDE5MzJiOGRjNjg2ZTVjY2E4NWMwMDY1YmY3MTMyMTQyY2QzNGU2YWRmOTA1MWUzYThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sEv8QdicXLvZ0LJVWqhxPT238x4gTdMO3x298eVVFhw)
> > Вирус майнер как бы сам по себе не запустишь, он защищен и не будет виден человеку консолью. А вот обычный свой майнер будет виден на котором сам майнишь именно через консоль. Просто потому что там можно тогда посмотреть в нем биткоин адрес кошелька чуть ли не открыто в самой консоли. Хотя может и не показываться, однако файл с кошель адресом тогда вычислить не особо сложно.
> > Как пример собственного майнера с opencl на амд ![image](https://private-user-images.githubusercontent.com/134365619/397944353-e83475b0-8d55-4689-984b-2fecab662781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTMxODAsIm5iZiI6MTczNDg1Mjg4MCwicGF0aCI6Ii8xMzQzNjU2MTkvMzk3OTQ0MzUzLWU4MzQ3NWIwLThkNTUtNDY4OS05ODRiLTJmZWNhYjY2Mjc4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwNzM0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmIwNDBiYjY2ODhkNzA4NGI3NDM2OTY1Mzk2YmJiZjQzZWMwNTEyOWQyYWI3ZGEyYjBmY2I0NWQ4NmY5NTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BH2DAy9C1HHKrTjN1vHDmcbfRxz8emQ7q9JCa_nL3js) ![image](https://private-user-images.githubusercontent.com/134365619/397944404-0904e49d-9354-47a4-8b1e-a4b7a9eff0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTMxODAsIm5iZiI6MTczNDg1Mjg4MCwicGF0aCI6Ii8xMzQzNjU2MTkvMzk3OTQ0NDA0LTA5MDRlNDlkLTkzNTQtNDdhNC04YjFlLWE0YjdhOWVmZjBlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwNzM0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTFhZGEwNmNhYjI5MjdmNmFjYjgwMmM1MmRlYTNiNGNlYjFjODIyMzkwYjZlOTU0ZjMxNjllYWQzZDlkMWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NbyYnc6pXrDPR-oo9uaDrdwECd0SkwqZmZ6Uh18-9ic)
> 
> Да это обход майнер лежал в нем+ троян (не один из антивирусов его не видел) заблокировал восстановление системы на ошибку 0xc00000017 Помогла только полная переустановка системы (после чего запустил повторно обход ютуб именно эту версию) майнер прописался в видеокарту (шумел как самолёт в момент запуска) (через regedit путь как раз был до обходчика ютуб)

Это ты откуда такую мощную штукенцию скачал которая всю систему прям заразила? Потому что в этом репозитории такого точно нет.

**Comment by KOT31506** [comment]
в ютубе какой то человек выставил обход ютуба 20.12 (как раз когда РКН блокнули сильнее) 
и там такая печаль началась

**Comment by KOT31506** [comment]
Возможно в этом файле и всё хорошо 
ну лучше быть осторожнее

**Comment by serpen7** [comment]
> в ютубе какой то человек выставил обход ютуба 20.12 (как раз когда РКН блокнули сильнее) и там такая печаль началась

а ну это скаммеры на ютубе, да, они еще паролят архив чтобы его не просканировало сразу, а еще кидают фолс страйки нормальным людям которые показывают как работает гудбайдпи или запрет с ссылками на нормальные репозитории. Это началось еще как люди массово начали пользовать проги обхода с замедлом ютуба.

Мне просто знакомый тоже скидывал тип "можно ставить" благо меня спросил а там файл winws1.exe в бине, который весит 22 метра с лишним. Я ему говорю откуда, он сказал с ютуба увидел в рекомендациях и поиске. Говорю ему удалить нахер это и скинул своё с этого репозитория и скинул репозиторий чтобы он знал откуда качать обнову если что. В общем чистая осторожность его тут как раз таки не подвела.

**Comment by KOT31506** [comment]
Ну просто прикол в другом много комментов всё работает думаю дай поставлю 
День отработал и запустился троян и заблокировал пол системы :D

**Comment by serpen7** [comment]
> Ну просто прикол в другом много комментов всё работает думаю дай поставлю День отработал и запустился троян и заблокировал пол системы :D

так ботов на ютубе всегда полно, вспомнить те же криптоскамы с взломанных акков, каждый коммент почти что это работает и получили кучу денег уже сразу.

**Comment by 01BROKHIM** [comment]
![Image](https://github.com/user-attachments/assets/97b0ba3b-5fa7-4ac8-b34e-ea7e2d535065)

Это адрес кошелька на донат, от сервиса reqrypt

**Comment by Iaromir12** [comment]
я бы хотел сказать что там нет вирусов. но после лютых фризов решил проверить все касперским (он у меня с подпиской). как итог файлы из обхода были заражены и пришлось делать лечение пк. как итог лаги пропали и процесор и видюха не в 100%. ну у меня теперь большие вопросы к запрету дискорда...

**Comment by serpen7** [comment]
> я бы хотел сказать что там нет вирусов. но после лютых фризов решил проверить все касперским (он у меня с подпиской). как итог файлы из обхода были заражены и пришлось делать лечение пк. как итог лаги пропали и процесор и видюха не в 100%. ну у меня теперь большие вопросы к запрету дискорда...

вопросы в том откуда вы его качали потому что тут в репозитории вирусов нет, тут лишь сборка с конфигами и файлы действующего приложения из ороигинального репозитория bol-van. И там тоже вирусов нет. Зато на ютубе в запароленных архивах распространителями вирусни, их не мало. И подлянок от них тоже. Тот же виндайверт используется так же в гудбайдпи.

**Comment by goodgame32** [comment]
2 месяца юзал с оф  гитхаба чела все окей папка не удаляется чел писал про то что он не видет ни где никакой страницы еще до этой хуйни мне кажется все норм
