### ISSUE TITLE
Не работает автозагрузка

### ISSUE THREAD

**Issue by Stelfelics** [Flowseal/zapret-discord-youtube#426]
Установила сервис через service_install.bat, после, запустила general.bat (естественно всё запускала от имени администратора). дс и ютуб ворк, но после перезапуска пк - приходится вручную запускать general.bat ибо не ворк.. добавить его в автозапуск - это микро костыль, не хочется.. в описании сказано: service_install.bat - установить на автозапуск (в сервисы) любую стратегию из этого репозитория (стратегия НЕ должна начинаться со слова service) но я не поняла что надо сделать. Есть ли тут знающие?🥹

**Comment by Flowseal** [comment]
> Установила сервис через service_install.bat, после, запустила general.bat

Не надо после установки сервиса через service_install.bat что-либо запускать. Запустили serivce_install от имени администратора - выбрали сервис - установили. Всё. Он работает и в автозапуске

**Comment by Stelfelics** [comment]
у меня батник запускался и сразу закрывался (я думала, что так и надо). Помогло пересохранение батника с кодировкой ANSI, теперь всё работает!
