### ISSUE TITLE
Странная ситуация СПБ дом.ру (KIller)

### ISSUE THREAD

**Issue by Sfars** [Flowseal/zapret-discord-youtube#428]
Не работает на моем ноутбуке от слова совсем, ни ютуб, ни дискорд(только через батник ALT5 заходит в дс, бесконечное подключение к RTC). Но есть один нюанс у меня в комнате, у товарища тоже стоит ноутбук. На нем все прекрасно работает через любой батник(И ютуб и дс). Не подскажите в чем может быть проблема? QUIC и KYBER включил. Я лично грешу на встроенный в мой ноутбук ethernet адаптер killer/DoubleShot Pro. **Ноутбук Acer Nitro AN515-58** + чистая Винда 11. Если нужна какая-то дополнительная информация, все что надо предоставлю).

**Comment by serpen7** [comment]
занятная сетевуха, учитывая ее возможности она может перебивать да работу программы т.к. в ее ПО вроде как встроен свой анализатор трафика и он может даже использоваться для того чтобы подрубится по проводу или вайфаю вместе взятых, а потом переключатся между ними в зависимости от того куда пытаешься получить доступ для "ускорения" смотря что лучше будет работать.

**Comment by Sfars** [comment]
> занятная сетевуха, учитывая ее возможности она может перебивать да работу программы т.к. в ее ПО вроде как встроен свой анализатор трафика и он может даже использоваться для того чтобы подрубится по проводу или вайфаю вместе взятых, а потом переключатся между ними в зависимости от того куда пытаешься получить доступ для "ускорения" смотря что лучше будет работать.

Знаешь как фиксить эту тему?

**Comment by serpen7** [comment]
> killer/DoubleShot Pro

К сожалению нет, без физического доступа к сетевухе и ее настройкам чтобы посмотреть что там может творится не разберешься особо. С киллер нетворк адаптерами встречался лишь несколько раз и мягко говоря впечатления всегда были отрицательными, потому что на некоторых вообще драйвер утечкой памяти глаза мозолил при включенной быстрой загрузки ноутов в ОС.

**Comment by serpen7** [comment]
Это конечно может быть предположением, но попробуй просто закрыть ПО для киллер нетворка, помоему без него анализатор трафика не будет работать. Если конечно можешь. Она по идее должна в трее висеть. Потом перезапусти прогу запрета и посмотри что будет.

Или поищи там опцию в ПО "контроль трафика", "анализатор трафика", а так же "двойной интернет" или что то подобное галочкой какой-нибудь и попробуй её отключить и посмотри что будет.

**Comment by Flowseal** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/541#issuecomment-2296038239
А также попробуй выключиь службы Killer.

**Comment by Sfars** [comment]
> [ValdikSS/GoodbyeDPI#541 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/541#issuecomment-2296038239) А также попробуй выключиь службы Killer.

Все заработало прекрасно, спасибо большое
