### ISSUE TITLE
Конфликт с NVIDIA GeForce Experience

### ISSUE THREAD

**Issue by venneste** [Flowseal/zapret-discord-youtube#43]
После установки сервиса (_service_discord_youtube.bat_) начали возникать проблемы с NVIDIA GeForce Experience и их оверлеем. На комбинацию клавиш открытия (Alt + Z) оверлея не отзывается, а при попытке зайти в приложение NVIDIA GeForce Experience выдаёт код ошибки 0x0003.

**Шаги воспроизведения проблемы:**

1. Иметь видеокарту NVIDIA (в моём случае NVIDIA GeForce GTX 1070)
2. Запустить файл _service_discord_youtube.bat_ **от имени администратора**
3. Перезапустить ПК
4. Попытаться зайти в NVIDIA GeForce Experience
5. Поймать код ошибки 0x0003

**Временное решение проблемы:**

1. Скачать GoodbyeDPI и запустить данный сервис
2. Запустить _service_goodbye_discord.bat_
3. Перезапустить ПК
4. Discord работает, нет конфликта с NVIDIA GeForce Experience

**Comment by Flowseal** [comment]
Я использую Nvidia App (новое приложение, в бете). У меня всё отлично.
В принципе, `service_goodbye_discord.bat` можно спокойно использовать на постоянной основе сейчас.
Спасибо за информацию.
