### ISSUE TITLE
Не запускается call of duty black ops 6 c работающим обходом блокировки. Я так понял это у всех юзеров.

### ISSUE THREAD

**Issue by Ballistiquell** [Flowseal/zapret-discord-youtube#430]
Вот ссылка на пост игроков из стима( https://steamcommunity.com/app/1938090/discussions/0/4756452379514384351/ ) у большинства проблема именно в этом

**Comment by exzolink** [comment]
Из-за windivert, фикса не будет, отключай сервис на время игры
