### ISSUE TITLE
Call of Duty BO6 GamePass не работает с обходом

### ISSUE THREAD

**Issue by ZevsMadness** [Flowseal/zapret-discord-youtube#431]
Как-то можно этот момент пофиксить таким образом, чтобы и обходки для ДС и ЮТ работали и игра запускалась? Удалял обходку, игра сразу начинает работать, а так выдает ошибку...

**Comment by MistikLove** [comment]
у меня такая же фигня

**Comment by exzolink** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/430

**Comment by ZevsMadness** [comment]
Слышал как-то можно скрывать windivert, и все будет работать, можешь подсказать?

**Comment by serpen7** [comment]
никак это античит игры не дает запускать фильтры трафика виндайверт

**Comment by Flowseal** [comment]
> Слышал как-то можно скрывать windivert, и все будет работать, можешь подсказать?

https://github.com/ValdikSS/GoodbyeDPI/issues/148#issuecomment-2276085368

**Comment by neolearnt** [comment]
Обнова 1.7.2b zapret`a [](https://github.com/ValdikSS/GoodbyeDPI/issues/148#issuecomment-2276085368) с этой темой теперь не помогает, есть ещё варики?

**Comment by serpen7** [comment]
> Обнова 1.7.2b zapret`a с этой темой теперь не помогает, есть ещё варики?

да никакая обнова вам не поможет, если разраб игры решил что это не будет запускаться с его игрой античитом - то это не будет запускаться с его игрой античитом. Вы можете попытаться замаскировать процесс, но за это можно схлопотать бан как за читы и вас уже не разбанят никак, потому что в логах у их античита будет сказано что вы маскировали процесс. И доказать что это не читы были вы не сможете никак им, потому что они не увидят какой это на самом деле был процесс и это были не читы..
