### ISSUE TITLE
Касаемо списка доменов Discord.

### ISSUE THREAD

**Issue by ThisIsDiver** [Flowseal/zapret-discord-youtube#436]
Я не поленился и прошёлся по списку доменов Discord. Практически все не вызывают вопросов кроме `discord.app`. Я ничего не утверждаю и хочу узнать является ли он официальным. Пытался сам узнать, но увы Интернет не дал мне ответов. Обычно Discord арендует сервера на **CloudFlare** и все домены связаны с серверами `gabe` и `sima`. Домен `discord.app` базируется не в США у **CloudFlare**, а у провайдера **ZXCS** Нидерланды, Южная Голландия. В рег. данных нет ничего, чтобы хоть как-то дало намёк о связи с доменом `discord.com` (хотя бы косвенной как с `dis.gd, discord.media` и прочих). 
Я помню, что раньше домен использовался для веб-приложения, но сейчас при его использовании переходит не на `discord.app`, а на `discord.com`.

Ничего не утверждаю, просто хочу прояснить почему в списке доменов для DS лежит домен, который особо не связан с другими.

P.S. Заодно расскажите о поддомене в `storage.googleapis.com` - `discord-attachments-uploads-prd.storage.googleapis.com`.

P.P.S. Забыл сказать, что репа нарушает лицензию WinDivert (хоть и LGPLv3, но там ещё и GPLv2) и есть малый шанс того, что за нарушение лицензии GPLv2 FSF могут кинуть репорт и репу прикроют.

**Comment by Flowseal** [comment]
> P.P.S. Забыл сказать, что репа нарушает лицензию WinDivert (хоть и LGPLv3, но там ещё и GPLv2) и есть малый шанс того, что за нарушение лицензии GPLv2 FSF могут кинуть репорт и репу прикроют.

Github даёт возможность внесения корректировок в репозторий для разрешения подобных конфликтов. Будет претензия - изменю. Сейчас этим заниматься нет желания

По мейн топику - discord.app редиректит на discord.com. Даже если в какой-то вселенной домен будет фишинговым, то вряд-ли включение домена в хостлистс будет причиной попадания на эту самую фишинговую ссылку.
