### ISSUE TITLE
Battle.net и Diablo4 магазин не работает

### ISSUE THREAD

**Issue by ConroyHMD** [Flowseal/zapret-discord-youtube#439]
Перестало работать после установки Zapret
Не загружаются страницы магазина  в лаунчере, в игре также нет доступа, пишет какие-то траблы с сертификатами безопасности, пробовал удалить сервис не помогло. VPN и других средств обхода и т.д. не установлено.
![изображение](https://github.com/user-attachments/assets/32cc80c9-d99e-4ade-9619-84e160624390)

**Comment by serpen7** [comment]
скорее всего из за связки батлнета с дискордом, а серверам батлнета не нравится когда в трафике с сертификатом присутствует модификации трафика. Но это не точно, потому что могут быть и реально проблемы с сертификатом безопасности. 
Переустановка баттлнета  не решает проблемы, не пробовали? 
И еще, вы же качали запрет с этого репозитория, а не откуда то еще?

**Comment by ConroyHMD** [comment]
Качал отсюда конечно, как-то очень совпало с установкой запрета, до этого юзал гудбай, проблем с бнет не было. Но перестал работать дискорд.
 Подскажите, удаление через service_remove с последующей перезагрузкой может решить проблему?
Какие ещё действия возможны, типа сброс днс, перезагрузки соединения и т.д. не особо силен в этом.

**Comment by serpen7** [comment]
> Качал отсюда конечно, как-то очень совпало с установкой запрета, до этого юзал гудбай, проблем с бнет не было. Но перестал работать дискорд. Подскажите, удаление через service_remove с последующей перезагрузкой может решить проблему? Какие ещё действия возможны, типа сброс днс, перезагрузки соединения и т.д. не особо силен в этом.

ты просто переустанови баттлнет он возможно просто поврежден.

**Comment by serpen7** [comment]
> Качал отсюда конечно, как-то очень совпало с установкой запрета, до этого юзал гудбай, проблем с бнет не было. Но перестал работать дискорд. Подскажите, удаление через service_remove с последующей перезагрузкой может решить проблему? Какие ещё действия возможны, типа сброс днс, перезагрузки соединения и т.д. не особо силен в этом.

Просто переустанови баттлнет, он возможно банально поврежден
Потому что если ты не прописывал сервера баттлнета в запрет листы то он на него не влияет.
И еще какая винда стоит, случаем не 7ка?
Сервис ремув от имени администратора удаляет сервис, если ты его устанавливал. Но тут вопрос зачем ты его устанавливал сразу, если ты его ставил сразу, вместо того чтобы попробовать именно те стратегии сначала, которые будут у тебя работать.

**Comment by ConroyHMD** [comment]
Видимо была проблема параметров сети, сброс сети и перезагрузка роутера помогли.
