### ISSUE TITLE
Путь содержит пробелы

### ISSUE THREAD

**Issue by Dixeone** [Flowseal/zapret-discord-youtube#44]
Не могу решить эту ошибку

**Comment by Dixeone** [comment]
![image](https://github.com/user-attachments/assets/e955ed65-8762-4638-a13b-f263c97c1cbb)

**Comment by Flowseal** [comment]
Рабочий ___ Стол. Пробел.
Перенесите программу в корень любого диска.

**Comment by Dixeone** [comment]
С путем все хорошо, только все равно не открывается

**Comment by krexik** [comment]
все равно не понимаю как

**Comment by Dixeone** [comment]
У меня теперь просто консоль закрывается сразу.
