### ISSUE TITLE
программа вовсе перестала работать 

### ISSUE THREAD

**Issue by suslikar2ga** [Flowseal/zapret-discord-youtube#440]
она включена но дискорд и ютуб очень долго грузятся и не работают

**Comment by artemryskal** [comment]
То же самое. МГТС

**Comment by serpen7** [comment]
у вас ни одна стратегия из батников не работает? Стратегии блокировок меняются.

**Comment by suslikar2ga** [comment]
Да


вт, 29 окт. 2024 г., 13:49 serpen7 ***@***.***>:

**Comment by Flowseal** [comment]
Ищите ответ в README
