### ISSUE TITLE
Троян ? 

### ISSUE THREAD

**Issue by KostiaKuzmin** [Flowseal/zapret-discord-youtube#445]
Норм что сканер показывает трояны ? 
![image](https://github.com/user-attachments/assets/9f70459c-bea0-4678-98ca-883b0bf358ea)

**Comment by serpen7** [comment]
Да норм потому что это эвристики, а не антивирусы, т.к. действие программы перехватывать определенный трафик фильтром и модифицировать его в соответствии с настройками, то это походит на действие трояна. О чем и пишут эвристики с припиской не самого кода сигнатуры трояна а со словом GENERIC или SUSPICIOUS. Т.е. поведение подобно ему, но распознать его не могут.
И да каспер даже пишет что это не вирус, а риск тулса
![image](https://github.com/user-attachments/assets/7179fecb-8f28-43e0-8803-545950d36788)
Просто потому что если вы скачаете ее откуда то с интернета непонятно от кого - вы можете вполне получить себе нехорошие последствия. О чем и как бы предупреждается на странице данного репозитория и даже у гудбайдпи, что в иннете есть фейковые версии и они вполне себе вирусы.
