### ISSUE TITLE
невозможность использовать гс (бесконечное подключение RTC)

### ISSUE THREAD

**Issue by DmitriyMalchikov** [Flowseal/zapret-discord-youtube#446]
использую ALT5, не использую AdGuard, даже отключил дефендер - безрезультатно. Сам дискорд работает, но не войс

**Comment by deletedowo** [comment]
жиза.

**Comment by deletedowo** [comment]
нашёл вот тут решение (мне помогло): https://github.com/Flowseal/zapret-discord-youtube в разделе "Не работает Discord? Попробуйте найти ответ здесь - https://github.com/Flowseal/zapret-discord-youtube/discussions/252"
