### ISSUE TITLE
бесконечное обновление дискорд

### ISSUE THREAD

**Issue by suslikar2ga** [Flowseal/zapret-discord-youtube#448]
![изображение_2024-10-29_153542060](https://github.com/user-attachments/assets/75cd6ba1-97c6-4435-a94a-4a141e13b3ed)
попробовал все обходы и каждый из них не работает

**Comment by Raz0r1** [comment]
минут 20 назад опять перестал работать дс, такая же проблема

**Comment by S-U-R-F** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
