### ISSUE TITLE
Вылетает при запуске 

### ISSUE THREAD

**Issue by Matresd** [Flowseal/zapret-discord-youtube#467]
вылетает при запуске батник, пробовал отдельно ехе тоже самое. Из архива все распаковал , не знаю уже чо делать

**Comment by EgorWeders** [comment]
Откройте cmd.exe и запустите в нем .bat или exe, скиньте скрин вывода

**Comment by Matresd** [comment]
> Откройте cmd.exe и запустите в нем .bat или exe, скиньте скрин вывода

каким образом? вообще не понял

**Comment by Matresd** [comment]
![image](https://github.com/user-attachments/assets/3a300964-7f8a-4344-aeb1-958bba433bef)
 записал и на стоп кадре сделал скрин при запуске exe-шника

**Comment by EgorWeders** [comment]
https://window-opens-and-closes.info/

А со скрином стопкадра вы конечно сильно))

**Comment by Matresd** [comment]
из гайды тоже больше не понял , я и так через cmd запускал . Если батник то просто это : 
![image](https://github.com/user-attachments/assets/968e0c63-1604-49ab-983f-19a65209848d)
если тут запустить exe то вылетает , а если внутри батника то тоже вылетает

**Comment by EgorWeders** [comment]
А вы от админа запускаете?

**Comment by Matresd** [comment]
естественно

**Comment by EgorWeders** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/136
попробуйте от туда решения

**Comment by Matresd** [comment]
а , кароче решил я значит .
Оно вылетает и висит на фоне  , но обход работает а через время сам exe появляется
вроде как помогло удаление winDivert

> sc stop WinDivert
> sc delete WinDivert

**Comment by goidamen** [comment]
такая же проблема, только обход не работает
