### ISSUE TITLE
HELP Не работает discord, вечный starting

### ISSUE THREAD

**Issue by SvetoldaK** [Flowseal/zapret-discord-youtube#47]
Скачана новая версия 1.1.1, открываю все от имени администратора,  пишет: 
we have 3 user defined desync profile(s) and default low priority profile 0
Loading hostlist C:\zapret-winws\list-discord.txt
loading plain text list
Loaded 25 hosts from C:\zapret-winws\list-discord.txt
Loading hostlist C:\zapret-winws\list-discord.txt
loading plain text list
Loaded 25 hosts from C:\zapret-winws\list-discord.txt
windivert initialized. capture is started.

При этом просто вечная загрузка дс, либо серый экран

**Comment by VadimBoev** [comment]
можно попробовать перезапустить дискорд

**Comment by SvetoldaK** [comment]
> можно попробовать перезапустить дискорд

Перезапускали и дс и комп, ставили старую версию, новую, ни с какой не работает

Антивирус тоже отключен

**Comment by VadimBoev** [comment]
> > можно попробовать перезапустить дискорд
> 
> Перезапускали и дс и комп, ставили старую версию, новую, ни с какой не работает
> 
> Антивирус тоже отключен

тогда к сожалению с провайдером не повезло, т.к. данный метод не гарантирует 100% работы
У меня тоже не работает, я не расстраиваюсь :)

**Comment by burnedoutman** [comment]
blockcheck в помощь для подбора подходящих параметров
https://github.com/N3M1X10/zapret_build/tree/main/zapret/blockcheck

**Comment by xunlu-t** [comment]
попробуйте запускать не service_discord.bat, а discord.bat

**Comment by userosos** [comment]
Точно не работает на Мегафоне в МО. Подключился по ВПН к другому провайдеру  (в РФ) и отлично заработал данный скрипт. Предлагаю сделать обсуждение, по сбору статистики по провайдерам. Тут скоро огромное количество Иисусов будет.

**Comment by SvetoldaK** [comment]
> попробуйте запускать не service_discord.bat, а discord.bat

service и не запускали

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92

**Comment by kelllmonakil** [comment]
Yota(Megaphone) тоже не хочет работать, хотя на версии 1.0.0 работал один день, дальше тютю

**Comment by Konverg** [comment]
> blockcheck в помощь для подбора подходящих параметров https://github.com/N3M1X10/zapret_build/tree/main/zapret/blockcheck

не мог бы ты для глупых объяснить, как конкретно им пользоваться?

**Comment by wef579** [comment]
Здаров , файл 16.1  не работает дискорд , а ютуб запускается у меня провайдер альянс , что делать . Я перепробывал уже все файлы , а дс не работает
