### ISSUE TITLE
Bitcoin

### ISSUE THREAD

**Issue by Ksarper** [Flowseal/zapret-discord-youtube#474]
Как это понимать?
![image](https://github.com/user-attachments/assets/d7b6ebb1-1a6d-499d-8b12-77b4824717e4)

**Comment by unluuck** [comment]
![Снимок экрана 2024-10-30 233513](https://github.com/user-attachments/assets/bed9437f-c433-4f16-9e59-15f2253ee55d)


![Снимок экрана 2024-10-30 233546](https://github.com/user-attachments/assets/894e7d84-84b7-4b03-873a-7a25c3d553e2)


думаю вопросы отпали, биток кошелек для донатов, сайт (судя по всему) создателей windivert и т.п.
UPD : не судя по всему, а так есть

**Comment by serpen7** [comment]
это описание от разраба виндайверта оригинального драйвера фильтра для пользовательского интерфейса и там зашит его кошелек для тех кто захочет поддержать его. Если бы это был майнер никто бы в описание файлов не указывал кошель и вы бы были уже жертвой его и знали бы это. Тем более что майнеры вычисляются явно не по описанию а по поведению и коду приложения.
