### ISSUE TITLE
virus or not?

### ISSUE THREAD

**Issue by YOn1ghtmare** [Flowseal/zapret-discord-youtube#475]
Здаров ребят,у меня появились подозрения по поводу этого кода.Пользовался им с 1.0.0 и антивирус молчал.Но когда первая версия слетела и я решил установить новую у меня во всю начал ругаться антивирусник(malwarebytes), а так же встроенный антивирус от винды. Кто может ответить это ложные переживания или все таки стоит побеспокоиться?

**Comment by mpustovoi** [comment]
https://github.com/Flowseal/zapret-discord-youtube/blob/main/README.md

**Comment by realsqfty** [comment]
Программу обновил, хэш поменялся — антивирус просто не узнаёт файлы, поэтому и жалуется

**Comment by YOn1ghtmare** [comment]
> https://github.com/Flowseal/zapret-discord-youtube/blob/main/README.md

я прочитал данный пост но проблема в том,что malwarebytes ругается не на эти файлы а на Generic.Malware/Suspicious и еще некоторые (извиняюсь не додумался сделать скриншот)

**Comment by YOn1ghtmare** [comment]
> Программу обновил, хэш поменялся — антивирус просто не узнаёт файлы, поэтому и жалуется

прошу прощения за глупый вопрос ,но я не знаю значения "хэш",т.к только начал познавать мир кодинга

**Comment by Nerykery** [comment]
> > Программу обновил, хэш поменялся — антивирус просто не узнаёт файлы, поэтому и жалуется
> 
> прошу прощения за глупый вопрос ,но я не знаю значения "хэш",т.к только начал познавать мир кодинга

 это уникальный идентификатор, который рассчитывается путем математических преобразований данных (информации) по специальному алгоритму с последующей конвертацией результата в строку символов. Пример хеш-кода: 9b9b17022a31abb8d443202b0b5932cb
 
 Ну или же
 
![image](https://github.com/user-attachments/assets/a0200e5a-2abf-4210-9eed-273fe759624d)
