### ISSUE TITLE
Virus??

### ISSUE THREAD

**Issue by MiskaKosolapiy** [Flowseal/zapret-discord-youtube#476]
![Снимок экрана 2024-10-30 215642](https://github.com/user-attachments/assets/f7cbd171-b59b-49f0-9bf2-b3600fb72f2a)

**Comment by MiskaKosolapiy** [comment]
![Снимок экрана 2024-10-30 215743](https://github.com/user-attachments/assets/64ccd868-a7c1-4bd5-be08-542b34973a82)

**Comment by JoCat** [comment]
Ну хочешь не юзай)

**Comment by MiskaKosolapiy** [comment]
Ну так зачем вы юзаете если там вирусы?

**Comment by JoCat** [comment]
Потому что их там нет, лол. Это ложные срабатывания.

Инглиш знаешь?)
![image](https://github.com/user-attachments/assets/f990bcd8-7682-4744-992b-693897cf2605)

**Comment by Will0376** [comment]
> Инглиш знаешь?)

![image](https://github.com/user-attachments/assets/c4139e7a-d851-4efb-b89c-54913aeee363)

**Comment by Roshmak** [comment]
> Ну так зачем вы юзаете если там вирусы?

Ну так GoodbyeDPI не может обойти блокировку дс вот и юзаем. 7 жалуются где6 из них НН какие то . А жалуется на компоненты которые есть и в GoodbyeDPI и они такиеже . Zapret создан на основе GoodbyeDPI так что омжно сказать всё норм

**Comment by MiskaKosolapiy** [comment]
> ![Снимок экрана 2024-10-30 215743](https://private-user-images.githubusercontent.com/186864114/381694900-64ccd868-a7c1-4bd5-be08-542b34973a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMTUyMzUsIm5iZiI6MTczMDMxNDkzNSwicGF0aCI6Ii8xODY4NjQxMTQvMzgxNjk0OTAwLTY0Y2NkODY4LWE3YzEtNGJkNS1iZTA4LTU0MmIzNDk3M2E4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxOTAyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmVkODRiNjYxYjBkMWRhYzZlMGQ1MDc0OTgxZjg4ZjJmMWI4ZTk3MjM4NDczZjk4N2Q1OWRlM2UwOWM1ZDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.va7DscqY1X3ouTGbqVflVVPUQ9Tq1AKWRB0XfE68T2I)

а с этим че

**Comment by mpustovoi** [comment]
> [!NOTE]  
> Данный репозиторий - **некоммерческая** *User-Friendly* сборка [оригинального репозитория](https://github.com/bol-van/zapret). Здесь используются оригинальные бинарники, сравнить которые вы можете с помощью хэша.
> Так как zapret open-source, вы всегда можете сами собрать эти бинарники и не бояться вирусов.
> 
>**Будут рад [⭐ поставленной звезде](https://github.com/Flowseal/zapret-discord-youtube/stargazers) (в правом верхнем углу) у репозитория 🙂**

##

> [!CAUTION]  
> **Многие антивирусники** в данный момент жалуются на ***HackTool/RiskTool*** и ***WinDivert*** - это нормальное поведение, так как программа изменяет сетевые пакеты. Что с этим делать? Собрать бинарники самому из исходников, довериться уже собранным, либо не использовать вовсе.



Это буквально в [README.md](https://github.com/Flowseal/zapret-discord-youtube/blob/main/README.md) написано.

**Comment by mpustovoi** [comment]
> а с этим че

Ну, модпак для танков оно тоже помечает так же.

**Comment by MiskaKosolapiy** [comment]
А какой запускать

**Comment by MiskaKosolapiy** [comment]
![Снимок экрана 2024-10-30 220936](https://github.com/user-attachments/assets/f6f18294-6b77-4886-a52d-b588cf253b49)

**Comment by MiskaKosolapiy** [comment]
чтоб автоматом запускался

**Comment by mpustovoi** [comment]
> А какой запускать
> чтоб автоматом запускался

Удалить сервис `service_remove.bat`, если был установлен ранее.
Открыть `service_install.bat` и нажать `9`.
Перезагрузить компьютер.

Если не сработало, удалить сервис ещё раз и попробовать другой `general ... .bat`.
