### ISSUE TITLE
Проблемы с service install

### ISSUE THREAD

**Issue by szaswy** [Flowseal/zapret-discord-youtube#478]
После указание сервиса а у меня обычные 9. general. не может установиться сервис. Пишет The service name is invalid. Так же пишет при попытке установить другие сервисы или возникает ошибка, что не запущен Zapret
![image](https://github.com/user-attachments/assets/ff0617e7-89fc-4e74-923f-93617093de9c)

**Comment by renkagod** [comment]
^

**Comment by Myakishow** [comment]
Аналогичная ошибка, но запускается и работает нормально, ютюб и дс работают, служба создается и запускается

**Comment by Roshmak** [comment]
Пробовал запускать Service Remover перед этим? Если не помогло етсь варик на 1.5.0 проверить у меня ваше на 1.3.0 работает прекрасно

**Comment by mpustovoi** [comment]
Это не ошибка. У меня всё то же самое написано было, но всё нормально установилось.
Перезагрузите компьютер и проверьте работу дискорда и ютуба.

Я так понимаю, между строчками, начинающимися с `[SC]` посередине, оно пишет что этот сервис ранее не устанавливался и после этого устанавливает его, о чём говорит `SUCCESS`.

**Comment by renkagod** [comment]
У меня вообще такое выдает
![image](https://github.com/user-attachments/assets/0d747542-447f-4805-8957-dfaaa0030e79)

**Comment by szaswy** [comment]
Благодарю за объяснения

**Comment by elpokol** [comment]
![Снимок экрана (101)](https://github.com/user-attachments/assets/7a65a219-8bd9-41fe-8707-c95bcfd26361)


????
После перезапуска пк дискорд не заработал. Почему пишет, что нет такой службы. Это ошибка? Что делать?
