### ISSUE TITLE
автозапуск новой версии

### ISSUE THREAD

**Issue by Reimuhak** [Flowseal/zapret-discord-youtube#479]
как на версии 1.5.1 установить автозаупск?

**Comment by mpustovoi** [comment]
Удалить сервис `service_remove.bat`, если был установлен ранее.
Открыть `service_install.bat` и нажать `9`.
Перезагрузить компьютер.

Если не сработало, удалить сервис ещё раз и попробовать другой `general ... .bat`.

**Comment by DrinkWaterPlease11** [comment]
> Удалить сервис `service_remove.bat`, если был установлен ранее. Открыть `service_install.bat` и нажать `9`. Перезагрузить компьютер.
> 
> Если не сработало, удалить сервис ещё раз и попробовать другой `general ... .bat`.

За что отвечает 9 и какую цифру вставлять, например, если мне нужен general(ALT)?

upd: слабо шарю, за тупые вопросы звиняйте

**Comment by mpustovoi** [comment]
> За что отвечает 9 и какую цифру вставлять, например, если мне нужен general(ALT)?

Цифра отвечает за файл, которые вы хотите выбрать:
![image](https://github.com/user-attachments/assets/cc56151e-61a4-4ae3-889e-a3ab4f34bc47)

Если вам нужен `general (ALT).bat`, выбирайте `2`.

**Comment by DrinkWaterPlease11** [comment]
> > За что отвечает 9 и какую цифру вставлять, например, если мне нужен general(ALT)?
> 
> Цифра отвечает за файл, которые вы хотите выбрать: ![image](https://private-user-images.githubusercontent.com/92390626/381705684-cc56151e-61a4-4ae3-889e-a3ab4f34bc47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMTc0MTEsIm5iZiI6MTczMDMxNzExMSwicGF0aCI6Ii85MjM5MDYyNi8zODE3MDU2ODQtY2M1NjE1MWUtNjFhNC00YWUzLTg4OWUtYTNhYjRmMzRiYzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE5MzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZmM0Mjg5ZGZkM2ZkMGMwOThlN2I0OWY3YzZhNmI4Zjc5YmFkNTFjNzkwMTEzZmRhMzM1YzRmMmM4ZWE5YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KByn_EgTd50CrdokLWqeXT0ABFI7tTbR6JjsKqK0qfo)
> 
> Если вам нужен `general (ALT).bat`, выбирайте `2`.

ага, так. а что делать, если батник service_install вылетает сразу же при открытии?

**Comment by mpustovoi** [comment]
> ага, так. а что делать, если батник service_install вылетает сразу же при открытии?

Если вы не устанавливали сервис ранее, то вам и не нужно его удалять. Проверьте, есть ли у вас ![image](https://github.com/user-attachments/assets/cb19400a-dca2-42be-8502-4b97033fd8c6) в `Подробности` в диспетчере задач.

Если есть, то тут я уже не знаю. Стоит дождаться ответа разработчика.

Если нет, устанавливайте.

**Comment by DrinkWaterPlease11** [comment]
> > ага, так. а что делать, если батник service_install вылетает сразу же при открытии?
> 
> Если вы не устанавливали сервис ранее, то вам и не нужно его удалять. Проверьте, есть ли у вас ![image](https://private-user-images.githubusercontent.com/92390626/381707836-cb19400a-dca2-42be-8502-4b97033fd8c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMTc4MzksIm5iZiI6MTczMDMxNzUzOSwicGF0aCI6Ii85MjM5MDYyNi8zODE3MDc4MzYtY2IxOTQwMGEtZGNhMi00MmJlLTg1MDItNGI5NzAzM2ZkOGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE5NDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMDBlNDEzZWZmZWIxY2FjOGNlNzdjZjA5NGE1ODA4Y2QwZGRkZTExMzIyODQyMDY2YzVjNjFiOWExNTljNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DYC8ICz-9TY1PAEj1MfoS3Cxv-U1Cy_K-WXJYTPQ6hU) в `Подробности` в диспетчере задач.
> 
> Если есть, то тут я уже не знаю. Стоит дождаться ответа разработчика.
> 
> Если нет, устанавливайте.

![image](https://github.com/user-attachments/assets/7e994d7e-744f-4078-a5bb-c623c476c101)
Есть в диспетчере, но только при открытом general(ALT2). Эх... Ждем отмашки от господина разработчика.

**Comment by mpustovoi** [comment]
> Есть в диспетчере, но только при открытом general(ALT2). Эх... Ждем отмашки от господина разработчика.

Так и должно быть. Это вы открыли "сессию" обхода. Как только вы закроете это окошко, программа перестанет работать и `winws.exe` пропадёт.

Если в таком виде не помогает, то попробуйте установить сервис и перезагрузить компьютер.

**Comment by DrinkWaterPlease11** [comment]
> > Есть в диспетчере, но только при открытом general(ALT2). Эх... Ждем отмашки от господина разработчика.
> 
> Так и должно быть. Это вы открыли "сессию" обхода. Как только вы закроете это окошко, программа перестанет работать и `winws.exe` пропадёт.
> 
> Если в таком виде не помогает, то попробуйте установить сервис и перезагрузить компьютер.

Открытая сессия помогает, но хотелось бы установить автозапуск, чтобы не маячило на панели задач. Но сервис не могу установить, так как по-прежнему вылетает что с открытой сессией, что с закрытой....

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/480#issuecomment-2448268288
