### ISSUE TITLE
Ошибка discord.bat

### ISSUE THREAD

**Issue by katarhisssss** [Flowseal/zapret-discord-youtube#48]
Когда запускаю от имени администратора эти файлы и вписываю из текстового все -----> ![image](https://github.com/user-attachments/assets/9ca32923-f79c-4239-81c3-c0fa3f994ca5) то сразу пропадает консоль. Может я не то пишу?

**Comment by katarhisssss** [comment]
Какой скрипт нужен? тут 
![image](https://github.com/user-attachments/assets/56a1ad24-ec8d-4bcf-99b4-20c64d8c38ee)

**Comment by Flowseal** [comment]
У вас в пути до файлов есть пробел, переместите файлы в отдельную папку в корне диска

**Comment by katarhisssss** [comment]
> w

Не совсем понимаю как можно убрать пробел
