### ISSUE TITLE
Помогите

### ISSUE THREAD

**Issue by Re1k-34** [Flowseal/zapret-discord-youtube#480]
Скачал новую версию, разархивил в папку с путем без русских символов, но попытавшись открыть от имени администратора файл general или discord, дискорд всё ещё не работает

**Comment by mpustovoi** [comment]
Скачать последнюю версию (1.5.1).
Удалить сервис `service_remove.bat`, если был установлен ранее.
Открыть `service_install.bat` и нажать `9`.
Перезагрузить компьютер.

Если не сработало, удалить сервис ещё раз и попробовать другой `general ... .bat`.

**Comment by Re1k-34** [comment]
![image](https://github.com/user-attachments/assets/cb308410-3883-4468-a655-f516fbea1f4c)
запустил от имени администратора, так должно быть?

**Comment by MorkatAV** [comment]
Вам необходимо сделать следующее

1. Скачайте версию 1.5.1 
2. В Папке со всеми сервисами и bat создать текстовой файл (Название латиницей)
3. Вставляете в него то что написано в самом низу
4. Переименовываете текстовой файл и меняете .txt в .bat
5. Запустите полученный Файл.bat
6. Наслаждайтесь

(Чинит и Дискорд и Ютуб)

```
@echo off
chcp 65001 >nul
:: 65001 - UTF-8

:: Admin rights check
echo Данный файл должен быть запущен с правами администратора (ПКМ - Запустить от имени администратора).
echo Нажмите любую клавишу, чтобы продолжить создание сервиса.
pause

set BIN=%~dp0bin\
set ARGS=--wf-tcp=443 --wf-udp=443,50000-65535 ^
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-udp=443 --hostlist="%~dp0list-general.txt" --dpi-desync=fake,disorder2 --dpi-desync-cutoff=d4 --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-tcp=443 --hostlist="%~dp0list-general.txt" --dpi-desync=fake,disorder2 --dpi-desync-autottl=1 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"

set SRVCNAME=zapret

net stop %SRVCNAME%
sc delete %SRVCNAME%
sc create %SRVCNAME% binPath= "\"%BIN%winws.exe\" %ARGS%" DisplayName= "zapret DPI bypass : %SRVCNAME%" start= auto
sc description %SRVCNAME% "zapret DPI bypass software"
sc start %SRVCNAME%

pause

**Comment by mpustovoi** [comment]
> запустил от имени администратора, так должно быть?

Видимо, он у вас не был установлен до этого.
Тогда открыть `service_install.bat` и нажать `9`.

**Comment by Skinerio** [comment]
> > запустил от имени администратора, так должно быть?
> 
> Видимо, он у вас не был установлен до этого. Тогда открыть `service_install.bat` и нажать `9`.

когда запускаю этот батник он просто открывается и закрывается, в чем может быть проблема?

**Comment by mpustovoi** [comment]
> когда запускаю этот батник он просто открывается и закрывается, в чем может быть проблема?

Возможно, открываете не от имени администратора.

**Comment by Linvin1** [comment]
> > когда запускаю этот батник он просто открывается и закрывается, в чем может быть проблема?
> 
> Возможно, открываете не от имени администратора.

Батник реально не запускается, проблема не единичная

**Comment by Skinerio** [comment]
> > когда запускаю этот батник он просто открывается и закрывается, в чем может быть проблема?
> 
> Возможно, открываете не от имени администратора.

От имени администратора, поэтому соответственно и спрашиваю

**Comment by Delitmi** [comment]
Аналогично, сервисы не ставятся от админки

старую версию выкорчевал полностью

**Comment by mpustovoi** [comment]
Если ![image](https://github.com/user-attachments/assets/7fa74cd4-7d1e-4e07-a9a8-9e3727442efe) присутствует в процессах диспетчера задач и не работает удаление, ждём ответа от разработчика.

**Comment by Flowseal** [comment]
Гадать на кофейной гуще не буду, либо логи работы service_install прикладывайте (запускайте через cmd от имени админа), либо не плодите такие треды.
