### ISSUE TITLE
Проблема с удалением сервиса

### ISSUE THREAD

**Issue by SUPERpuperGH** [Flowseal/zapret-discord-youtube#482]
все как обычно, service_remove и тут вылезает это, может кто объяснить, что это значит и где проверить удален ли сервис?
![Снимок экрана (53)](https://github.com/user-attachments/assets/1f6febdd-1700-471f-9b1f-e7526ee1532b)

**Comment by mpustovoi** [comment]
По всей видимости, у вас не установлен сервис.

Можно проверить, что он не установлен/удалён, если в разделе `Подробности` в диспетчере задач нет такого:
![image](https://github.com/user-attachments/assets/8a28b80a-8b23-49c5-8507-1768241b1d56)

**Comment by SUPERpuperGH** [comment]
> По всей видимости, у вас не установлен сервис.
> 
> Можно проверить, что он не установлен/удалён, если в разделе `Подробности` в диспетчере задач нет такого: ![image](https://private-user-images.githubusercontent.com/92390626/381706050-8a28b80a-8b23-49c5-8507-1768241b1d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMTcyODcsIm5iZiI6MTczMDMxNjk4NywicGF0aCI6Ii85MjM5MDYyNi8zODE3MDYwNTAtOGEyOGI4MGEtOGIyMy00OWM1LTg1MDctMTc2ODI0MWIxZDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE5MzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NzZjNTZjYzBmZmY1Zjk4YmEwNmI2MTMxZjkyY2YwMTU1MzA0NDliZDY1ZmRkMzgwODc5NTI2NzllYjQyNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EVhKPAEeSdkSAWnt_dxcszangC6B_IxNgp4lF0PiGsw)

при запуске батки "discord" выдает такое
![Снимок экрана (54)](https://github.com/user-attachments/assets/3e89fb35-4818-4524-84f6-5cad92338d0f)
а дальше вечная загрузка дискорда

**Comment by mpustovoi** [comment]
> при запуске батки "discord" выдает такое
> а дальше вечная загрузка дискорда

Я сразу ставил сервис. Просто "сессионные" батники не пробовал.

Через сервис установил `general.bat` и после перезагрузки всё заработало.

**Comment by serpen7** [comment]
sc query zapret  от имени админа в CMD. Нету? Значит нету. Если вы запускаете батники сервис и не ставится. Вам не нужно ничего удалять, закрываете прогу и все. Не работает? Ищите рабочий конфиг для себя. Все есть в шапке и возможных обсуждениях запрета. Плюс в последней версии несколько стратегий относительно рабочих на разных провах.

**Comment by Flowseal** [comment]
По логам всё удалилось
