### ISSUE TITLE
NET HELPMSG 3521

### ISSUE THREAD

**Issue by KirasinChan** [Flowseal/zapret-discord-youtube#484]
![image](https://github.com/user-attachments/assets/24ef12bc-3b89-482a-9c26-3315d17d1d9a)

**Comment by Flowseal** [comment]
Во первых, поправьте окончание строк на CRLF в файле (например, используя Notepad++), гугл в помощь вам. Во вторых, гуглите ошибку 1068 при StartService и решайте её
