### ISSUE TITLE
Вылеты CoD MW3 и CoD BO6 через Xbox Game Pass

### ISSUE THREAD

**Issue by Kasparione** [Flowseal/zapret-discord-youtube#485]
У друга при активном батнике/сервисе игра инста вылетает без ошибок, но, если снести батник/сервис, то какое-то время они ещё не захотят запускаться, а потом всё будет работать. Какие логи или что-то подобное можно вам на рассмотрение отправить? Происходит только там. Во всех других приложениях проблем нет.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/431
