### ISSUE TITLE
Как удалить файл WinDivert64?

### ISSUE THREAD

**Issue by EatherDM** [Flowseal/zapret-discord-youtube#486]
Я пробовал разные способы от service_remoute, выключал проводник и через командную строку пробовал удалять, искал к чему подсоединено через мониторинг ресурсов(там ничего кроме проводника) но ничего не помогло.
![Снимок экрана 2024-10-30 232948](https://github.com/user-attachments/assets/c51a6851-5373-4aa1-88a0-bb4137cfbe86)

**Comment by Kapetto-o** [comment]
Командную строку от имени администратора попробуйте запустить и потом уже удалять через консоль как в инструкции README. Консоль же сама вывела, что у вас доступа нету

**Comment by EatherDM** [comment]
> Командную строку от имени администратора попробуйте запустить и потом уже удалять через консоль как в инструкции README. Консоль же сама вывела, что у вас доступа нету

Я пробовал когда был доступ. У меня попросили подтверждения, я подтвердил и мне написало что не удалось удалить. + сейчас даже командной строке от имени администратора отказано в доступе

**Comment by Flowseal** [comment]
service_remove.bat от имени админа
затем удаляйте файлы

**Comment by EatherDM** [comment]
> service_remove.bat от имени админа затем удаляйте файлы
Не получается даже после этого. Я это первым делом пробовал. Запустил от имени администратора но вот такая проблема.
![Снимок экрана 2024-10-31 171645](https://github.com/user-attachments/assets/f00761a1-76a6-432a-8203-90e04c920457)
