### ISSUE TITLE
Почему дс не работает?

### ISSUE THREAD

**Issue by Epic-face** [Flowseal/zapret-discord-youtube#487]
на старой версии всё работало, но на новой всё сломалось, с любым батником не получается, как это исправить?

**Comment by Flowseal** [comment]
Нет никакой информации. Если работало на старой, зачем обновились? 
Создавайте тред с деталями: ошибки и прочее

**Comment by Epic-face** [comment]
> Нет никакой информации. Если работало на старой, зачем обновились? Создавайте тред с деталями: ошибки и прочее
а я откуда мог знать, будет ли работать на новой версии или нет

**Comment by Epic-face** [comment]
> Нет никакой информации. Если работало на старой, зачем обновились? Создавайте тред с деталями: ошибки и прочее
  а я откуда мог знать будет ли он работать ли нет на новой версии
