### ISSUE TITLE
Подозрительные файлы: VirusTotal расценил файлы в проекте как вредоносные

### ISSUE THREAD

**Issue by vladrrom** [Flowseal/zapret-discord-youtube#489]
При проверке проекта были обнаружены файлы, которые не прошли проверку на VirusTotal. 

• Название файла: winws.exe 
• Результат проверки на virustotal: [тык](https://www.virustotal.com/gui/file/0453fce6906402181dbff7e09b32181eb1c08bb002be89849e8992b832f43b89/detection)

• Название файла: WinDivert64.sys
• Результат проверки на virustotal: [тык](https://www.virustotal.com/gui/file/8da085332782708d8767bcace5327a6ec7283c17cfb85e40b03cd2323a90ddc2/detection)

Вопросы к автору:
• Являются ли файлы действительно вредоносными? 
• Не перенаправляет ли данные этот обход,  крадя их?
• Если файлы не вредоносные, как их можно проверить на безопасность?

Просьба к автору проекта предоставить информацию о безопасности файлов.

**Comment by StarOneButterfly** [comment]
![image](https://github.com/user-attachments/assets/e09c42d1-0ee9-4bf1-8e4d-ed25ccc4efd6)
буквально в начале README написано

**Comment by Flowseal** [comment]
Читайте README
