### ISSUE TITLE
Ошибка с путем к файлу

### ISSUE THREAD

**Issue by naikoku** [Flowseal/zapret-discord-youtube#49]
У меня возникает ошибка пути к файлу, проверил другие форумы и перенос в коренную папку не сработало как в 44 запросе.
Вылезает вот это
Пытался и в коренную, и на пустой папке и через адм и просто, не выходит. 
Иногда просто открывается закрывается и все, иногда выдает ошибку и в скрипте.
![photo_2024-10-09_17-58-37](https://github.com/user-attachments/assets/d0b5f4e8-c124-4aa5-accc-7fb0a63f6508)

**Comment by naikoku** [comment]
Если что, я вижу что пробел в рабочем столе, но даже в коренной папке он не запускается.

**Comment by Flowseal** [comment]
Покажите ошибку, которая возникает из коневой папки

**Comment by aidarxa** [comment]
А где ошибка?

**Comment by naikoku** [comment]
> Покажите ошибку, которая возникает из коневой папки

Когда запускаю в корневой папке - файл просто открывается и моментально закрывается.

**Comment by Flowseal** [comment]
> > Покажите ошибку, которая возникает из коневой папки
> 
> Когда запускаю в корневой папке - файл просто открывается и моментально закрывается.

Должен открыться файл. Попробуйте перезапустить устройство.

**Comment by burnedoutman** [comment]
> > Покажите ошибку, которая возникает из коневой папки
> 
> Когда запускаю в корневой папке - файл просто открывается и моментально закрывается.

чтобы увидеть возможную проблему, добавь в конец батника pause

**Comment by naikoku** [comment]
> > > Покажите ошибку, которая возникает из коневой папки
> > 
> > 
> > Когда запускаю в корневой папке - файл просто открывается и моментально закрывается.
> 
> Должен открыться файл. Попробуйте перезапустить устройство.

Не сработало. Всё также.

**Comment by naikoku** [comment]
> > > Покажите ошибку, которая возникает из коневой папки
> > 
> > 
> > Когда запускаю в корневой папке - файл просто открывается и моментально закрывается.
> 
> чтобы увидеть возможную проблему, добавь в конец батника pause

Можно поподробнее?

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/91#issuecomment-2403281800

**Comment by GOODZILLLA** [comment]
Можно создать папку не на рабочем столе ,а на диске и все должно заработать. Ну по крайне мере у меня так и заработало
