### ISSUE TITLE
Проблема с батником "service_install"

### ISSUE THREAD

**Issue by MezuHumka** [Flowseal/zapret-discord-youtube#490]
Проблема заключается в том, что при запуске от имени администратора батника "service_install" появляется консоль на секунду, а потом закрывается. Был на версии, когда не было альт версий, там не работал батник "service_remove". Видео прилагается

Uploading Запись 2024-10-31 011513.mp4…

**Comment by MezuHumka** [comment]
понял, сейчас скину ссылку на видео
https://imgur.com/a/zf90AA3

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/449

**Comment by MezuHumka** [comment]
Поменять SRVCNAME на  CRLF или что куда? Простите, искал в инете сейчас вообще ничего не помогло

**Comment by MezuHumka** [comment]
окей, я поменял
@echo off
chcp 65001 >nul
:: 65001 - UTF-8

:: Admin rights check
echo Данный файл должен быть запущен с правами администратора (ПКМ - Запустить от имени администратора).
echo Нажмите любую клавишу, чтобы продолжить создание сервиса.
pause

set BIN=%~dp0bin\
set ARGS=--wf-tcp=443 --wf-udp=443,50000-65535 ^
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-udp=443 --hostlist="%~dp0list-discord.txt" --dpi-desync=fake,disorder2 --dpi-desync-cutoff=d4 --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-tcp=443 --hostlist="%~dp0list-discord.txt" --dpi-desync=fake,disorder2 --dpi-desync-autottl=1 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"

set SRVCNAME=zapret

net stop %SRVCNAME%
sc delete %SRVCNAME%
sc create %SRVCNAME% binPath= "\"%BIN%winws.exe\" %ARGS%" DisplayName= "zapret DPI bypass : %SRVCNAME%" start= auto
sc description %SRVCNAME% "zapret DPI bypass software"
sc start %SRVCNAME%

pause
