### ISSUE TITLE
Пояснить тупому что и куда надо вставлять в service_install

### ISSUE THREAD

**Issue by yakeuita** [Flowseal/zapret-discord-youtube#491]
Установил новую версию батников, работают. Но вот install запускается и закрывается, я так понимаю там надо что-то в файле вписать. Подскажите что именно.

**Comment by Trudol** [comment]
install_service создаёт сервис (работу в фоне + включается при запуске пк) из батника.
В нём ты выбираешь из списка сценариев (bat файлов) и запускаешь.
