### ISSUE TITLE
При запуске service_install моментально закрывается, с предыдущей версией такого не было.

### ISSUE THREAD

**Issue by Darkshtorm** [Flowseal/zapret-discord-youtube#494]
Все остальные батники работают нормально.

**Comment by Hexaedrr** [comment]
Точно также. Ещё не нашёл ответа?

**Comment by MusornyyPaket** [comment]
Ждем, пока найдут решение.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/480#issuecomment-2448268288
