### ISSUE TITLE
Вирусы

### ISSUE THREAD

**Issue by S4N321** [Flowseal/zapret-discord-youtube#497]
А трояны и стилер, в подарок идут?

**Comment by vxrypl** [comment]
Разочарую, или может быть порадую - нет, не идут.

**Comment by DimaSergeew** [comment]
но мне система и антивирус пишут что там вирус

**Comment by S4N321** [comment]
> Разочарую, или может быть порадую - нет, не идут.
трояны то ладно, они должны быть, а стилер с майнером в подарок

**Comment by Flowseal** [comment]
читайте readme
