### ISSUE TITLE
Kaspersky ругается на tamp файлы создаваемой запуском goodbyedpi!

### ISSUE THREAD

**Issue by tau3737** [Flowseal/zapret-discord-youtube#498]
Здравствуйте добавил в исключение Касперского папку goodbyedpi но при использовании программы эта программа создает временные файлы в папке temp на что Касперский ругается , всю папку temp я не могу добавить в исключение из соображений безопасности подскажите что делать и возможно ли убрать это или сделать так чтобы прога не создавала временные файлы 
![udd](https://github.com/user-attachments/assets/4b7a71f7-8a66-4af3-9eba-bffced1a73d1)

**Comment by Flowseal** [comment]
Во первых, это репозиторий не goodbyedpi. Во вторых, в касперском, возможно, есть способ добавить в исключения по паттерну, чтобы не добавлять всю папку temp. Кто-то это уже решал в тредах. Подсказать не могу, антивирусами не пользуюсь

**Comment by tau3737** [comment]
> Во первых, это репозиторий не goodbyedpi. Во вторых, в касперском, возможно, есть способ добавить в исключения по паттерну, чтобы не добавлять всю папку temp. Кто-то это уже решал в тредах. Подсказать не могу, антивирусами не пользуюсь

Я про то что я чайник в этом можешь просто объяснить что это получается при запуске батника создается  этот временный файл для работы и это нормально? ? по поводу касперского вроде получилос добавить в исключение по маске файла но там тоже свои заморочки
