### ISSUE TITLE
service_discord

### ISSUE THREAD

**Issue by sst4nk0** [Flowseal/zapret-discord-youtube#5]
Сервис, в отличи от простого discord.bat - не работает.  Путь к файлу выглядит так - D:\Program Files\gZapretDiscord - русских символов и пробелов нет. Мб это у всех проблема, а не только моя?

**Comment by R1zonChik** [comment]
тоже самое, автор фиксани пж сервис

**Comment by Flowseal** [comment]
От имени админа запускаете?
Запустите файл через cmd (запустите cmd от имени администратора, откройте текущий каталог, пропишите service_discord.bat для запуска) и покажите, что выведется

**Comment by sst4nk0** [comment]
Запускал от имени админа.


D:\Program Files\gZapretDiscord>service_discord

D:\Program Files\gZapretDiscord>set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=443 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="D:\Program Files\gZapretDiscord\list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="D:\Program Files\gZapretDiscord\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="D:\Program Files\gZapretDiscord\quic_initial_www_google_com.bin" --new --filter-tcp=443 --hostlist="D:\Program Files\gZapretDiscord\list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="D:\Program Files\gZapretDiscord\tls_clienthello_www_google_com.bin"

D:\Program Files\gZapretDiscord>set SRVCNAME=zapret

D:\Program Files\gZapretDiscord>net stop "zapret"
The service name is invalid.

More help is available by typing NET HELPMSG 2185.


D:\Program Files\gZapretDiscord>sc delete "zapret"
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.


D:\Program Files\gZapretDiscord>sc create "zapret" binPath= "\"D:\Program Files\gZapretDiscord\winws.exe\" --wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=443 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="D:\Program Files\gZapretDiscord\list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="D:\Program Files\gZapretDiscord\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="D:\Program Files\gZapretDiscord\quic_initial_www_google_com.bin" --new --filter-tcp=443 --hostlist="D:\Program Files\gZapretDiscord\list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="D:\Program Files\gZapretDiscord\tls_clienthello_www_google_com.bin"" DisplayName= "zapret DPI bypass : winws1" start= auto
DESCRIPTION:
        Creates a service entry in the registry and Service Database.
USAGE:
        sc <server> create [service name] [binPath= ] <option1> <option2>...

OPTIONS:
NOTE: The option name includes the equal sign.
      A space is required between the equal sign and the value.
 type= <own|share|interact|kernel|filesys|rec|userown|usershare>
       (default = own)
 start= <boot|system|auto|demand|disabled|delayed-auto>
       (default = demand)
 error= <normal|severe|critical|ignore>
       (default = normal)
 binPath= <BinaryPathName to the .exe file>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <Dependencies(separated by / (forward slash))>
 obj= <AccountName|ObjectName>
       (default = LocalSystem)
 DisplayName= <display name>
 password= <password>

D:\Program Files\gZapretDiscord>sc description "zapret" "zapret DPI bypass software"
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.


D:\Program Files\gZapretDiscord>sc start "zapret"
[SC] StartService: OpenService FAILED 1060:

The specified service does not exist as an installed service.


D:\Program Files\gZapretDiscord>

**Comment by Flowseal** [comment]
Попробуйте этот батник:
```
set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 ^
--wf-tcp=443 --wf-udp=443,50000-65535 ^
--filter-udp=443 --hostlist="%~dp0list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^
--filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^
--filter-tcp=443 --hostlist="%~dp0list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%~dp0tls_clienthello_www_google_com.bin"

set SRVCNAME=zapret

net stop "%SRVCNAME%"
sc delete "%SRVCNAME%"
sc create "%SRVCNAME%" binPath= "%~dp0winws.exe %ARGS%" DisplayName= "zapret DPI bypass : winws1" start= auto
sc description "%SRVCNAME%" "zapret DPI bypass software"
sc start "%SRVCNAME%"
```
Запустите также через cmd

**Comment by sst4nk0** [comment]
D:\Program Files\gZapretDiscord>fix

D:\Program Files\gZapretDiscord>set ARGS=--wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=443 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="D:\Program Files\gZapretDiscord\list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="D:\Program Files\gZapretDiscord\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="D:\Program Files\gZapretDiscord\quic_initial_www_google_com.bin" --new --filter-tcp=443 --hostlist="D:\Program Files\gZapretDiscord\list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="D:\Program Files\gZapretDiscord\tls_clienthello_www_google_com.bin"

D:\Program Files\gZapretDiscord>set SRVCNAME=zapret

D:\Program Files\gZapretDiscord>net stop "zapret"
The service name is invalid.

More help is available by typing NET HELPMSG 2185.


D:\Program Files\gZapretDiscord>sc delete "zapret"
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.


D:\Program Files\gZapretDiscord>sc create "zapret" binPath= "D:\Program Files\gZapretDiscord\winws.exe --wf-tcp=443-65535 --wf-udp=443-65535 --wf-tcp=443 --wf-udp=443,50000-65535 --filter-udp=443 --hostlist="D:\Program Files\gZapretDiscord\list-discord.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="D:\Program Files\gZapretDiscord\quic_initial_www_google_com.bin" --new --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="D:\Program Files\gZapretDiscord\quic_initial_www_google_com.bin" --new --filter-tcp=443 --hostlist="D:\Program Files\gZapretDiscord\list-discord.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="D:\Program Files\gZapretDiscord\tls_clienthello_www_google_com.bin"" DisplayName= "zapret DPI bypass : winws1" start= auto
DESCRIPTION:
        Creates a service entry in the registry and Service Database.
USAGE:
        sc <server> create [service name] [binPath= ] <option1> <option2>...

OPTIONS:
NOTE: The option name includes the equal sign.
      A space is required between the equal sign and the value.
 type= <own|share|interact|kernel|filesys|rec|userown|usershare>
       (default = own)
 start= <boot|system|auto|demand|disabled|delayed-auto>
       (default = demand)
 error= <normal|severe|critical|ignore>
       (default = normal)
 binPath= <BinaryPathName to the .exe file>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <Dependencies(separated by / (forward slash))>
 obj= <AccountName|ObjectName>
       (default = LocalSystem)
 DisplayName= <display name>
 password= <password>

D:\Program Files\gZapretDiscord>sc description "zapret" "zapret DPI bypass software"
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.


D:\Program Files\gZapretDiscord>sc start "zapret"
[SC] StartService: OpenService FAILED 1060:

The specified service does not exist as an installed service.


D:\Program Files\gZapretDiscord>

**Comment by Flowseal** [comment]
А, не заметил. У вас пробел в пути до сервиса. **Program Files**

**Comment by sst4nk0** [comment]
Сейчас исправлю

**Comment by sst4nk0** [comment]
Да, моя ошибка. Я сам слепой.
