### ISSUE TITLE
не запускается никакой батник из 1.5.1 и других версий (кроме service.install.bat и service_remove.bat)

### ISSUE THREAD

**Issue by KirillGoode** [Flowseal/zapret-discord-youtube#502]
никакой ошибки не выдает, запускается на 1 секунду и сразу выключается, а когда я запускаю serivce_remove.bat, мне вот такое пишет, запускаю от имени администратора что просто батники, что service_remove.bat
![image](https://github.com/user-attachments/assets/618acf3c-458d-4f62-b4b6-c16c1976f60d)
виндуос 10

прилагаю ошибку в этом сообщение:Данный файл должен быть запущен с правами администратора (ПКМ - Запустить от имени администратора).
Нажмите любую клавишу, чтобы продолжить удаление и остановку сервиса.
Press any key to continue . . .
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

The service is starting or stopping.  Please try again later.

[SC] DeleteService FAILED 1072:

The specified service has been marked for deletion.

The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

Press any key to continue . . .

Дискорд закрыт был, комп перезагружал

**Comment by VokerTO** [comment]
удали все старые версии запрета и гудбай 
ОБЯЗАТЕЛЬНО НУЖНО УДАЛИТЬ ИМЕННО bin 
Если не удаляется bin самый простой способ перезапустите пк и удалите "работает только при использовании программы без авто запуска"
если юзали авто запуск тут теории прописать команды в cmd "командная строка" [sc stop WinDivert] [sc delete WinDivert] если не удается удалить перезапустить пк 
3 способ запустить винду в безопасном режиме работает 100% в любом случаи

**Comment by KirillGoode** [comment]
а безопасный режим для чего, чтобы удалить или как?

**Comment by KirillGoode** [comment]
![image](https://github.com/user-attachments/assets/17e64a6d-edce-4153-8967-5d1c46649249)
ммм, я остановил службу WinDivert, но он тупо не даёт удалить((

**Comment by VokerTO** [comment]
да в безопасном режиме не  запускаются посторонние службы и другие вещи завязанные на старте винды

**Comment by KirillGoode** [comment]
окей

**Comment by KirillGoode** [comment]
а гудбай dpi никогда не ставил

**Comment by VokerTO** [comment]
сама программа находится в bin 
bat файлы выступают в роле конфигов

**Comment by Flowseal** [comment]
Ищи процессы, который используют WinDivert, если не помогает service_remove.bat. Кто-то использовал сторонние программы анлокеры для файлов (не ручаюсь)
