### ISSUE TITLE
Не запускается консоль

### ISSUE THREAD

**Issue by Dixeone** [Flowseal/zapret-discord-youtube#51]
При запуске discord.bat консоль открывается и сразу закрывается. Что делать?

**Comment by Flowseal** [comment]
Запустите через cmd от имени администратора

**Comment by Dixeone** [comment]
![image](https://github.com/user-attachments/assets/13117979-a703-4a47-aff9-61a210f5222f)

**Comment by Dixeone** [comment]
русские символов не должно быть?

**Comment by Dixeone** [comment]
Через рабочий стол открывается, но там пробел. Через корень диска не открывается.

**Comment by Dixeone** [comment]
![image](https://github.com/user-attachments/assets/2a18a79b-70bb-40cf-8143-167114743784)

**Comment by Dixeone** [comment]
![image](https://github.com/user-attachments/assets/58fcb3ab-b4e4-493c-81d6-4c75ec12dba9)
Вот вообщем

**Comment by Flowseal** [comment]
Судя по ошибке, вы забыли перенести папку bin
