### ISSUE TITLE
Не работает войс. Бесконечное подключение к RTC

### ISSUE THREAD

**Issue by Keissonlax** [Flowseal/zapret-discord-youtube#513]
Сидел на старой версии запрета, но вчера перестал работать. Сразу обновил до 1.5.1 и запустил discord.bat и все работало, но сегодня перестал работать. Пробовал все батники: с какими-то дискорд не запускался совсем с какими-то работало все кроме войса. При попытке подключиться к войсу пишет о попытке подключиться к RTC а потом пишет что не установлен маршрут и так по кругу.  Также пробовал альтернативные батники которые предлагали в других ветках тем у кого не работают дефолтные, но ничего не помогает. Может кто помочь с этим ?
провайдер: exnet

**Comment by Keissonlax** [comment]
Изучил схожие проблемы в обсуждениях и выяснил что причина в AdGuard. Надеюсь помог кому-то с схожей проблемой

**Comment by SherstiK** [comment]
Проблема бесконечного "подключение к rtc" и " не установлен маршрут" действительно в Adguard. Стоит добавить Discord в исключения в Adguard.

**Comment by jif22** [comment]
> Изучил схожие проблемы в обсуждениях и выяснил что причина в AdGuard. Надеюсь помог кому-то с схожей проблемой

Бро, ты лучший!! Спасибо. Неделю не мог решить проблему
