### ISSUE TITLE
Подозрительная работа winws.exe

### ISSUE THREAD

**Issue by Flstudioenjoyer1** [Flowseal/zapret-discord-youtube#515]
При запуске программы появляется процесс в диспетчере задач winws.exe которая в ветке имеет службу zapret dpi bypass и именно эта служба кажется для меня подозрительной, потому что она имеет тип авто запуска автоматический, все бы ничего да только если этот тип авто запуска поставить на выключен или ручной, то после ВЫКЛЮЧЕНИЯ (не перезагрузки) и дальнейшего включения тип авто запуска обратно поменяется на автоматический и соответственно процесс winws.exe также будет запущен, я понимаю что на гитхабе навряд ли будут вирусы, но этот прикол с программой мне хотелось бы прояснить, как зачем и почему это происходит, как отключить автоматическое изменение типа загрузки (я не хочу чтобы программа сама стартовала вместе с системой)

**Comment by Flowseal** [comment]
> я понимаю что на гитхабе навряд ли будут вирусы

Смелое заявление

По теме: не используйте сервис инсталлер и не будет службы. Логично? Если хотите убрать сервис - пользуйтесь service_remove

**Comment by Flstudioenjoyer1** [comment]
Ладно все я решил вопрос, проблема была в том, что в одном за гайдов обсуждений был код, который надо было вставить в батник и в этом коде стоит запуск автоматический. Можете пожалуйста сказать что нужно вставить вместо [DisplayName= "zapret DPI bypass : %SRVCNAME%" start= auto] в значении start
