### ISSUE TITLE
.bat запускается и сразу пропадает.

### ISSUE THREAD

**Issue by CSIskemo** [Flowseal/zapret-discord-youtube#517]
Вчера перезагружал интернет тк не работал после этого включаю пк и bat в запрет дискорде перестал работать просто запускался и через секунду пропадал пытался переустанавливать и пробовал много чего но не получилось. Как это можно исправить?

**Comment by B0mak** [comment]
У моего товарища такая же проблема была, что не было окна winws.exe после запуска ЦМДшника. Решилось путём перекачки архива из релиза в другом браузере. 

У товарища я.браузер каким-то макаром корёжил архив, в итоге перекачал через Эдж (бывший Internet Explorer), извлёк всё и заработало. Попробуй у себя так же, может поможет, чем чёрт не шутит в конце-концов.

**Comment by B0mak** [comment]
> У моего товарища такая же проблема была, что не было окна winws.exe после запуска ЦМДшника. Решилось путём перекачки архива из релиза в другом браузере.
> 
> У товарища я.браузер каким-то макаром корёжил архив, в итоге перекачал через Эдж (бывший Internet Explorer), извлёк всё и заработало. Попробуй у себя так же, может поможет, чем чёрт не шутит в конце-концов.

Алсо, отключи на всякий все антивиры перед скачкой, в том числе дефендер от винды.

**Comment by Ptalemon** [comment]
> Вчера перезагружал интернет тк не работал после этого включаю пк и bat в запрет дискорде перестал работать просто запускался и через секунду пропадал пытался переустанавливать и пробовал много чего но не получилось. Как это можно исправить?

Такая же проблема. При попытке удалить или установить баты жалуется, что указанный файл не существует

ПС: Пофиксил, но нестандартным методом. Просто подрубился к раздаче мобильного с телефона. Видимо рофлы со стороны провайдера (коммент всё равно оставлю, вдруг кому СРОЧНО в дис с такой проблемой надо)
![Установщик](https://github.com/user-attachments/assets/21c9c5ed-8716-4176-89f5-1976ed066e53)
![Пытаюсь удалить](https://github.com/user-attachments/assets/8d8793b9-989d-44ff-8a29-249ddb36fccd)
