### ISSUE TITLE
Не работают батники

### ISSUE THREAD

**Issue by zashita-penis** [Flowseal/zapret-discord-youtube#525]
При запуске батника от имени администратора все открывается должным образом. Но при открытии дискорда ничего не происходит, пишется бесконечный checking for updates. Пробовал копаться в свойствах и открывать альты генерал батов, скачивал 3 версии запрета. Не помогало.
![Uploading изображение_2024-11-01_104421122.png…]()
![Uploading Screenshot 2024-11-01 104117.png…]()

**Comment by CreepyPanda357** [comment]
Попробуй это

Есть решение!
После суток обдумывания и 4 часов сюрфа по интернету и теста различных вариантов нашелся один способ, может далеко не у всех сработать.
Сделал следующее:
Зашел в службы windows, нашел службу GoodBuy DPI
![изображение_2024-10-31_222251380](https://github.com/user-attachments/assets/b2cd139a-c66a-4022-bbe1-7a3292262f05)
, я GDPI не качал, не знаю откуда взялась. Отключил эту службу и скачав последнюю версию релиза, запустил general.bat и о чудо, оно заработало! Мб кому-то поможет

**Comment by KirillGoode** [comment]
> Попробуй это
> 
> Есть решение! После суток обдумывания и 4 часов сюрфа по интернету и теста различных вариантов нашелся один способ, может далеко не у всех сработать. Сделал следующее: Зашел в службы windows, нашел службу GoodBuy DPI ![изображение_2024-10-31_222251380](https://private-user-images.githubusercontent.com/119042036/382088285-b2cd139a-c66a-4022-bbe1-7a3292262f05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDA0ODYsIm5iZiI6MTczMDQ0MDE4NiwicGF0aCI6Ii8xMTkwNDIwMzYvMzgyMDg4Mjg1LWIyY2QxMzlhLWM2NmEtNDAyMi1iYmUxLTdhMzI5MjI2MmYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwNTQ5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDQ0NDIwY2M5NTY0NjcxNjhmZGVjODJiMWZkZTZlYjQxNTI4NWMyMmM4OWJiMGQ0MzljOWQ4ZDA4OTkyYTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p4JWPa0fmKNjpmW1wnnPhPiJwgs6y0fuqgn8mVbGqRo) , я GDPI не качал, не знаю откуда взялась. Отключил эту службу и скачав последнюю версию релиза, запустил general.bat и о чудо, оно заработало! Мб кому-то поможет

эх жаль что у меня такого нету и не запускается(

**Comment by damirs11** [comment]
Попробуй это

Запусти cmd от админа
sc stop windivert
sc delete windivert

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
