### ISSUE TITLE
созданный сервис называется zpret вместо zapret

### ISSUE THREAD

**Issue by fendalf** [Flowseal/zapret-discord-youtube#529]
Скачал версию 1.5.1, запустил service_install, выбрал general (ALT), по окончании получил следующее

```
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 13352
        FLAGS              :
```

В списке сервисов нашёл zpret вместо zapret, который мне вывелся в консоль
![image](https://github.com/user-attachments/assets/a097e091-3eaf-4353-83a5-124da3b4752d)

**Comment by ch4og** [comment]
duplicate of https://github.com/Flowseal/zapret-discord-youtube/issues/464, 
since that one issue is closed as completed with no comments  seems like it's wonfix

**Comment by ch4og** [comment]
Fixed in https://github.com/Flowseal/zapret-discord-youtube/commit/2588cae778f695ee341f3659a3721a8562c16393, get new bat from main branch or this commit

**Comment by serpen7** [comment]
Это лишь отображаемое имя в сервисах ОС в пользовательской среде, сам же сервис получает название в системе именно zapret. Это особо ни на что не влияет. Просто вы видите его в сервисах как zpret, а система видит его как zapret. Это лишь отображаемое вам имя в пользовательском интерфейсе.
Потому что в дисплей нейм была пропущена одна буква в слове zapret 
![image](https://github.com/user-attachments/assets/a7acdd88-b6d6-4224-b123-94cc6f81300a)
