### ISSUE TITLE
Возникает конфликт Windows-огово антивируса

### ISSUE THREAD

**Issue by Vasyokvk** [Flowseal/zapret-discord-youtube#53]
Есть какие-то советы?
![Screenshot 09 10 2024 18_06_47](https://github.com/user-attachments/assets/c9952375-4db2-4fa2-9cdb-de4c81128d04)

**Comment by FANTASYnbrl** [comment]
Это стандартное уведомление винды если у ПО официально не указан издатель. Просто кликай Подробнее и игнорируй уведомление
