### ISSUE TITLE
Не запускаются файлы

### ISSUE THREAD

**Issue by Aleksseyy** [Flowseal/zapret-discord-youtube#530]
При попытке открыть «general» или «service_remove» появляется курсор загрузки и через секунду ничего не происходит. При открытии от имени администратора, окно подтверждения не появляется, и также ничего не происходит.

https://github.com/user-attachments/assets/324e7af8-7ecc-47bf-9f33-0a6868628f55

**Comment by serpen7** [comment]
проверьте ваш антивирус он там ничего втихую не сделал просто чтобы вас не беспокоить?

**Comment by Aleksseyy** [comment]
> проверьте свой антивирус, он ничего не сделал втихаря, просто чтобы вас не беспокоить?

у меня от винды ток который изначально стоит я там все отключил

**Comment by damirs11** [comment]
Попробуй это

Запусти cmd от админа
sc stop windivert
sc delete windivert

**Comment by Aleksseyy** [comment]
> Попробуй это
> 
> Запусти cmd от админа sc stop windivert sc delete windivert

пишет C:\WINDOWS\system32>sc stop windivert
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.

**Comment by serpen7** [comment]
может они просто настолько быстро у вас запускаются... попробуйте посмотреть в диспетчере задач приложение winws

**Comment by Aleksseyy** [comment]
> может они просто настолько быстро у вас запускаются... попробуйте посмотреть в диспетчере задач приложение winws

неа, ничего не появляется

**Comment by serpen7** [comment]
хм, тогда явно что то не дает запускаться батникам чтобы потом запустить winws.

**Comment by damirs11** [comment]
Для подсказки куда смотреть, можно открыть журнал событий. Нам с другом он помог с поиском решения

**Comment by 1krasyuk** [comment]
такая же проблема. при запуске от администратора консоль открывается и сразу закрывается. если не от администратора открывать, то просто пишет, что путь неправильный. отдельно файл winws пробовал открыть, он закрывается сразу после подтверждения в предупредительном окне. WinDivert пишет, что служба не установлена.

**Comment by serpen7** [comment]
> такая же проблема. при запуске от администратора консоль открывается и сразу закрывается. если не от администратора открывать, то просто пишет, что путь неправильный. отдельно файл winws пробовал открыть, он закрывается сразу после подтверждения в предупредительном окне. WinDivert пишет, что служба не установлена.

может у вас та же проблема? 
https://github.com/Flowseal/zapret-discord-youtube/issues/531

**Comment by 1krasyuk** [comment]
да, если открывать батники, то выдает ошибку. но файл winws есть в папке bin

**Comment by serpen7** [comment]
> да, если открывать батники, то выдает ошибку. но файл winws есть в папке bin

попробуйте посмотреть эту тему https://github.com/Flowseal/zapret-discord-youtube/issues/522

**Comment by 1krasyuk** [comment]
смотрел ее, пробовал, не помогло. батник service_remove тоже запускается от администратора и сразу пропадает. 
Скачал с релиза по второй ссылке, открывается батник на ремув, но в нем выдает ошибки
![image](https://github.com/user-attachments/assets/566ab6a1-cd46-4056-86c1-8fd948fb881d)

**Comment by serpen7** [comment]
эти ошибки означают что сервис не установлен, Поэтому и ошибки что нечего убирать.

**Comment by Flowseal** [comment]
> смотрел ее, пробовал, не помогло. батник service_remove тоже запускается от администратора и сразу пропадает. Скачал с релиза по второй ссылке, открывается батник на ремув, но в нем выдает ошибки ![image](https://private-user-images.githubusercontent.com/46215218/382281383-566ab6a1-cd46-4056-86c1-8fd948fb881d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NzE3OTAsIm5iZiI6MTczMDQ3MTQ5MCwicGF0aCI6Ii80NjIxNTIxOC8zODIyODEzODMtNTY2YWI2YTEtY2Q0Ni00MDU2LTg2YzEtOGZkOTQ4ZmI4ODFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE0MzEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZTM2MDNhMDY1NzU0YjI3MDNiOGEwMzYyMGRiOWM2NDY1NWEyOTczNWRiYTg2Nzk2OTMwNjlmYTdjNDIwNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n9uI6wV5HJdHlxa84UV4p5c04Clt4w5cDjf2JHysDOI)

Как на счёт перестать качать файлы с гита, а качать релизы?

**Comment by Flowseal** [comment]
Читайте README
