### ISSUE TITLE
Выдаёт ошибку при запуске 

### ISSUE THREAD

**Issue by Resrph** [Flowseal/zapret-discord-youtube#531]
что делать при запуске батника выдаёт такую ошибку 
![Снимок экрана 2024-11-01 160858](https://github.com/user-attachments/assets/fd1eaf79-9787-462d-99ab-53ca80cff401)
![Снимок экрана 2024-11-01 160851](https://github.com/user-attachments/assets/856fc645-66aa-49e0-85f6-2c3eee5e2204)

**Comment by serpen7** [comment]
А вы откуда скачивали запрет?

**Comment by Resrph** [comment]
> А вы откуда скачивали запрет?

Ну с гетхаба 
![image](https://github.com/user-attachments/assets/540e88f0-0d8a-4c44-9fb4-3dcfc5009cac)

**Comment by serpen7** [comment]
Проверьте антивирус он возможно снес вам winws файл в бин папке.

**Comment by Resrph** [comment]
> Проверьте антивирус он возможно снес вам winws файл в бин папке.

Спасибо за помощь

**Comment by 7thmoon5** [comment]
Не работают все батники для ютуба, понятия не имею почему. Просто сервис говорить что "zapret" is NOT running.

![Image](https://github.com/user-attachments/assets/fac9727f-8a91-47b9-93bc-9458d0719a50)

![Image](https://github.com/user-attachments/assets/2012f218-f459-4bf1-bb20-797102292e26)

![Image](https://github.com/user-attachments/assets/4b2e3c53-827d-48eb-8f45-df188bf9bd9e)

При это это точно не антивирус, он не работает. Скачала последний релиз. Помогите пж
