### ISSUE TITLE
Как удалить Zpret?

### ISSUE THREAD

**Issue by Reitern77** [Flowseal/zapret-discord-youtube#533]
Хотел полностью снести прогу из за ненадобности, но не удаляется. Пишет, что файлы открыты в zpret

**Comment by serpen7** [comment]
service_remove.bat от имени администратора запускаешь

**Comment by Reitern77** [comment]
> service_remove.bat от имени администратора запускаешь

А если я удалил все файлы, просто выдеоив и закинув в корзину, очистив ее
То я смогу удалить оставшиеся, скачав заново и воспользовавшись service_remove.bat?

**Comment by serpen7** [comment]
> > service_remove.bat от имени администратора запускаешь
> 
> А если я удалил все файлы, просто выдеоив и закинув в корзину, очистив ее То я смогу удалить оставшиеся, скачав заново и воспользовавшись service_remove.bat?

скачайте просто заново с репозитория этого и используйте сервис ремув, а потом удалите.
