### ISSUE TITLE
бесконечное подключение к rtc

### ISSUE THREAD

**Issue by zxcqred** [Flowseal/zapret-discord-youtube#534]
Я ничего не понимаю в командной строке и в приндципе в компьютере более углубленно. Прочитал что нужно поменять порты, но не понимаю как. Есть какой нибудь способ для чайников как я? (я не админ сервера)

**Comment by serpen7** [comment]
Поменять порты? Это где вы такое прочитали?

**Comment by Flowseal** [comment]
Не надо порты менять. Вся инструкция в README
