### ISSUE TITLE
Не запускается дискорд zapret 1.5.1 версия.

### ISSUE THREAD

**Issue by 45SADERT45** [Flowseal/zapret-discord-youtube#536]
Не запускается дискорд, ни с 1 из способов, все батники запускаются, ошибок нет, но дискорд просто крутит и все ни с места.

**Comment by MartinDawgor** [comment]
Провайдер какой? Устанавливал ли другие версии запрета/гудбайдпи?

**Comment by 45SADERT45** [comment]
> Провайдер какой? Устанавливал ли другие версии запрета/гудбайдпи?
> 
> 

Умные сети, мск.
Другие версии тоже не робят, goodbydpi сегодня решил чекнуть тоже не работает, но иногда между огромным количеством попыток запуска и тд дс переходит на след этап прогрузки и пишет старт, но не открывается, потом все тоже самое, если повторить не прогружает уже.
Добавлю так же , на ноуте, которые к той же сети подрублен все работает, сегодня даже поставил ту же винду, была 10 поставил 11, но всеравно не работает, вообще не понятно, что за дичь происходит.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
