### ISSUE TITLE
Как удалить старый zapret? 

### ISSUE THREAD

**Issue by h1tezly** [Flowseal/zapret-discord-youtube#538]
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.
Когда я пытаюсь ремувнуть сервис, пишет это.

**Comment by serpen7** [comment]
если вы не запускали сервис инсталл сервис и не устанавливался, поэтому выдает ошибку что сервис не найден, а на все остальное есть сервис ремув.

**Comment by h1tezly** [comment]
> если вы не запускали сервис-инсталлятор, то сервис не устанавливался, поэтому выдается ошибка, что сервис не найден, а для всего остального есть сервис-ремувер.

когда запускаю сервис-инсталлятор, тоже самое пишет

**Comment by serpen7** [comment]
> > если вы не запускали сервис-инсталлятор, то сервис не устанавливался, поэтому выдается ошибка, что сервис не найден, а для всего остального есть сервис-ремувер.
> 
> когда запускаю сервис-инсталлятор, тоже самое пишет

вы как то странно читаете, я не про него писал.

**Comment by Flowseal** [comment]
Пишет, что сервиса нет. Значит, нет запрета
