### ISSUE TITLE
Помогите! Все перепробовал, Discord, вечное подключение к RTC , при том что на ноутбуке все работает штатно. 

### ISSUE THREAD

**Issue by Serigala444** [Flowseal/zapret-discord-youtube#539]

**Comment by EvgenezBond** [comment]
Блокировщик рекламы AdGuard стоит? Если да то добавь Discord в исключения.

**Comment by Serigala444** [comment]
> Блокировщик рекламы AdGuard стоит? Если да то добавь Discord в исключения.

Спасибо огромное! Помогло!
