### ISSUE TITLE
бесконечный "cheking for updates"

### ISSUE THREAD

**Issue by azura1618** [Flowseal/zapret-discord-youtube#54]
вроде запустил всё как надо, антивирусов, кроме антивирусника от винды, у меня нет, всё равно не работает

**Comment by xunlu-t** [comment]
попробуйте запускать не service_discord.bat, а discord.bat

**Comment by azura1618** [comment]
я пробовал и то и другое, не помогает ни в каком случае

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92

**Comment by if7D0** [comment]
привет, у меня возникла эта проблема, как её решить, я совсем новичок в настройке таких программ
