### ISSUE TITLE
Не работают некотрые bat файл илм очень долго грузят

### ISSUE THREAD

**Issue by MOSS1K** [Flowseal/zapret-discord-youtube#543]
Буквально вчера все работало отлично.
Ну придя вечером домой запустил самый первый файл discord bat. - открывает дискорд очень медленно, а после как откроет подключение к войсу идёт секунд 30 не меньше.
Так же запуская general bat. Который самый первый тоже самое. А вот когда запускаешь general bat. (ALT2) работает и грузит все как нужно!

Подскажите пожалуйста в чем может быть проблема? Почему именно эти 2 файла перестали работать корректно? А другие работают нормально.

**Comment by MOSS1K** [comment]
Забыл добавить провайдер КСТ

**Comment by serpen7** [comment]
потому что меняется блокировка\замедло? Вы же не думали что они будут сидеть сложа руки и просто смотреть на то вот всё это тут?

**Comment by MOSS1K** [comment]
То есть вы хотите сказать что эти файлы больше не заработают? Ну почему у моих знакомых они работают и все в порядке.  Может это и за провайдера? Или и за смены динамического ip?

**Comment by serpen7** [comment]
> То есть вы хотите сказать что эти файлы больше не заработают? Ну почему у моих знакомых они работают и все в порядке. Может это и за провайдера? Или и за смены динамического ip?

у ваших знакомых другой провайдер, другое расположение даже если это сосед по площадке вашей, они подключены к другим узлам, тут кучи вариантов которые вы думаете что схожи с вашими но на самом деле нет. Поэтому и говорится даже в ридми что конфиги нужно подбирать под себя индивидуально. Нет общей таблетки для всех и всего. Это борьба "они сделали и ты ответил или спасовал". Тем более что вам дали инструменты для этого.  То что старые стратегии не заработают нет никакой гарантии т.к. у тех кто это делает тоже ресурсы не неограниченные, им приходится урезать что то, чтобы иннет вообще не лег от наплыва всего что будет фильтровать оборудование.

То что у вас заработала какая то стратегия если вы не разбираетесь лучше для вас даже, потому, что иначе вам бы пришлось ее подбирать или писать самому конфигом, либо искать таких же как и вы друзей по несчастью и пробовать что у них заработало, а потом дорабатывать под себя и прова своего на то что у вас происходит.

**Comment by MOSS1K** [comment]
> > То есть вы хотите сказать что эти файлы больше не заработают? Ну почему у моих знакомых они работают и все в порядке. Может это и за провайдера? Или и за смены динамического ip?
> 
> у ваших знакомых другой провайдер, другое расположение даже если это сосед по площадке вашей, они подключены к другим узлам, тут кучи вариантов которые вы думаете что схожи с вашими но на самом деле нет. Поэтому и говорится даже в ридми что конфиги нужно подбирать под себя индивидуально. Нет общей таблетки для всех и всего. Это борьба "они сделали и ты ответил или спасовал". Тем более что вам дали инструменты для этого. То что старые стратегии не заработают нет никакой гарантии т.к. у тех кто это делает тоже ресурсы не неограниченные, им приходится урезать что то, чтобы иннет вообще не лег от наплыва всего что будет фильтровать оборудование.



Вы говорите подобрать свой конфиг, а как это сделать? Под свой провайдер.

**Comment by serpen7** [comment]
> > > То есть вы хотите сказать что эти файлы больше не заработают? Ну почему у моих знакомых они работают и все в порядке. Может это и за провайдера? Или и за смены динамического ip?
> > 
> > 
> > у ваших знакомых другой провайдер, другое расположение даже если это сосед по площадке вашей, они подключены к другим узлам, тут кучи вариантов которые вы думаете что схожи с вашими но на самом деле нет. Поэтому и говорится даже в ридми что конфиги нужно подбирать под себя индивидуально. Нет общей таблетки для всех и всего. Это борьба "они сделали и ты ответил или спасовал". Тем более что вам дали инструменты для этого. То что старые стратегии не заработают нет никакой гарантии т.к. у тех кто это делает тоже ресурсы не неограниченные, им приходится урезать что то, чтобы иннет вообще не лег от наплыва всего что будет фильтровать оборудование.
> 
> Вы говорите подобрать свой конфиг, а как это сделать? Под свой провайдер.

читать ридми, читать команды, подбирать их, штрудить форумы, смотреть другие стратегии и их тоже пробовать, если что-то  пробило то дорабатывать под себя с знаниями из "о программе" ридми информации о запрете.

**Comment by MOSS1K** [comment]
Понял вас спасибо за консультацию, надеюсь что данный создатель данного конфинга в следующем обновление сделает все ещё лучше чтобы было меньше проблем и все работало ещё лучше!

**Comment by serpen7** [comment]
> Понял вас спасибо за консультацию, надеюсь что данный создатель данного конфинга в следующем обновление сделает все ещё лучше чтобы было меньше проблем и все работало ещё лучше!

Нет таблетки лечащей все болезни для всех. Так  же как и нет универсального конфига который будет работать у всех и на него не найдут управу со временем. Создатель репозитория и так малость заморочался, чтобы создать множество стратегий на разные ситуации даже для капризных провов порой. Чтобы все более было юзер френдли. Но это не работает для всех уникально и это не панацея, найдутся люди у кого это не будет работать все равно, поэтому и нужно будет вникать и понимать как писать конфиг и пробовать его, тестить на что триггерится фильтр ТСПУ.
