### ISSUE TITLE
🔴 Обход YouTube ребят я вообще ничего не понимаю программировании, и прочитав это у меня только голова закружилась. Пожалуйста кто-нибудь может подсказать как обойти блокировку чтоб я хоть что-то понял, умоляю 🙏🏻

### ISSUE THREAD

**Issue by TheVM0** [Flowseal/zapret-discord-youtube#544]
### Discussed in https://github.com/Flowseal/zapret-discord-youtube/discussions/251

<div type='discussions-op-text'>

<sup>Originally posted by **Flowseal** October 13, 2024</sup>
### Здесь вы можете обсуждать различные стратегии обхода YouTube
Обсуждение создано на замену Issue в пользу удобным комментариям и сортировке
Закрытый Issue - https://github.com/Flowseal/zapret-discord-youtube/issues/90

### ⬆️ Если вам помог чей-либо ответ, то проголосуйте за него!

- ## Общие советы
Не прогружается видео на ютубе? Многим помогает поставить **`Kyber`** и **`QUIC`** в default (`chrome://flags/`).
Также в файле, который открываете, в строчке с `--filter-tcp=443`: попробуйте поменять `--dpi-desync-fooling=md5sig` на `--dpi-desync-fooling=badseq`.

Попробуйте использовать **DNS over HTTPS/TLS** (просто загуглите это в паре с вашим браузером)

- ## МГТС
Многим помогает убрать `,split` в строчке с `--filter-tcp=443`

- ## Firefox
В Firefox и Waterfox многим пользователям проблемы с ютубом помогает решить изменение параметра network.http.http3.retry_different_ip_family на true (чтобы открыть настройки, впишите в адресную строку браузера about:config). Должно также работать с другими браузерами на движке Gecko (by @k1n3c7)</div>

**Comment by exzolink** [comment]
https://github.com/Flowseal/zapret-discord-youtube/blob/main/README.md#guides

**Comment by TheVM0** [comment]
> https://github.com/Flowseal/zapret-discord-youtube/blob/main/README.md#guides

так я попробовал все что там есть, но ничего не сработало. А дальше когда я зашел в обсуждение там была только абсолютно не понятная мне информация. Там какие-то kyber и Quic, я вообще не понимаю что это
