### ISSUE TITLE
Что делать если ты скачал zapret для дс, но у тебя не работают голосовые каналы? (нету звука, и не показывается что ты говоришь)

### ISSUE THREAD

**Issue by Ekafik** [Flowseal/zapret-discord-youtube#547]
а кто знает,что делать если ты скачал zapret для дс, но у тебя не работают голосовые каналы? (нету звука, и не показывается что ты говоришь)

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
