### ISSUE TITLE
Нашёл троян. Сомневаюсь в подленности антивирусов

### ISSUE THREAD

**Issue by Lina-bash** [Flowseal/zapret-discord-youtube#549]
Возможно какая-то ошибка?
![Скриншот 02-11-2024 224257](https://github.com/user-attachments/assets/4243bf50-1949-44a6-b2f5-672df88a8906)

**Comment by serpen7** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/516#issuecomment-2453108238

И еще, а вы точно качали с этого репозитория? Последний билд? 
https://www.virustotal.com/gui/file/0453fce6906402181dbff7e09b32181eb1c08bb002be89849e8992b832f43b89?nocache=1
![image](https://github.com/user-attachments/assets/8183cc9f-25c4-40aa-9a3b-80e253bad6a3)

**Comment by Flowseal** [comment]
Хэш не совпадает с последней версией. Другие проверять не буду. Возможно, вы скачали не отсюда.

**Comment by valek1011** [comment]
![2024-12-23 02-09-20 Скриншот экрана](https://github.com/user-attachments/assets/309ad3b4-4493-4963-94f3-8057dd863ed4)
Качал с этого репозитария и тоже говорит что есть вирусы.

**Comment by serpen7** [comment]
> ![2024-12-23 02-09-20 Скриншот экрана](https://private-user-images.githubusercontent.com/56658085/398018437-309ad3b4-4493-4963-94f3-8057dd863ed4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mzc2NTEsIm5iZiI6MTczNDkzNzM1MSwicGF0aCI6Ii81NjY1ODA4NS8zOTgwMTg0MzctMzA5YWQzYjQtNDQ5My00OTYzLTk0ZjMtODA1N2RkODYzZWQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA3MDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMzQyNGEwYTVlZmI4OWJmNzNhZjQzMzZkNWQ1MzhmNjE5ZDQyYmZlZTQwYTg5YmI4Y2M4MTg2MWE3ODI4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mByiHrYYZJOHH7-vVW4Yk12q3q6_kQ2Ubov3WvEROO8) Качал с этого репозитария и тоже говорит что есть вирусы.

не, их тут нет, это эвристики говорят "о возможной угрозе" из-за запакованного виндайверта. А виндайверт да, ведет себя как троян для антивирусов и винды, потому что перехватывает и модифицирует трафик в соответствии с конфигом.
![image](https://github.com/user-attachments/assets/e9a10380-4b93-4cbf-91c0-704c71fced88)
