### ISSUE TITLE
ЭТО ВИРУСНЯК

### ISSUE THREAD

**Issue by uertyk** [Flowseal/zapret-discord-youtube#551]
Окей, давайте пройдётся по фактам!

В этом репозитории имеются вирусы, а именно в файле winws.exe, это можно проверить с помощью VirusTotal (выводит 9 вирусов), скрины ниже:
![Screenshot_2024-11-02-23-50-56-715_com discord-edit](https://github.com/user-attachments/assets/8e66f874-510e-46b3-a665-88268c2081e9)
![IMG_20241102_234133_413](https://github.com/user-attachments/assets/ead7b934-a058-40b7-8b39-9b80f4abeb6b)
Как мы поняли, по нашему расследованию мы разъяснили, что все батники запускают этот файл, который имеет как мы уже поняли в себе вирусы. При первом запуске, он просит права администратора, после чего рассылает по вашему устройству вирусы. Если почитать посты/форумы, то эта программа имеет доступ к блокированию вашего устройства а так же имеет червь-троян (Trojan/win23.agent , вроде так).

❗ГАЙД ПО УДАЛЕНИЮ ВСЕХ ВИРУСНИКОВ❗

Шаги:
1. Удаляйте все файлы zapret-discord, (bin особенно).
2. Проверьте комп на вирусы (касперски не поможет, ничего не выдает так как вирусы хорошо шифруются), советую скачать оффициальную прогу от Microsoft "Удаление вредоносных программ" ( [ссылка](https://www.microsoft.com/ru-ru/download/details.aspx?id=9905) , и запускайте полную проверку (это тот же самый дефендер, так что можно запустить и его).
3. Если нашло вирусы, УДАЛЯЙТЕ ИХ ВСЕ!!!
4. Выключите все программы и послушайте, не шумит/греется ваше устройство, если все еще есть проблема с нагрузкой, то тут уже лучше обращаться к мастерам.

Мы вср еще ведем расследование, и я буду писать ниже!

Доп. информация:
Вирус блокирует ваш проводник и диспетчер задачь, так же он шифруется у вирусников (касперски и тд. не найдут его).

**Comment by uertyk** [comment]
Добавление к доп. информации:
Оно снижает вам производительность устройства, так же потому что троян.

**Comment by SMorganYu** [comment]
так может потому что winws подменяет пакеты для обхода? в репозитории всё написано
![{3A73099A-53C4-4C3B-B02F-D83EB087B011}](https://github.com/user-attachments/assets/1b62885e-0eaf-4834-b18a-7cb6286abd83)

**Comment by uertyk** [comment]
> так может потому что winws подменяет пакеты для обхода? в репозитории всё написано ![{3A73099A-53C4-4C3B-B02F-D83EB087B011}](https://private-user-images.githubusercontent.com/73845574/382554413-1b62885e-0eaf-4834-b18a-7cb6286abd83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MTkxNjMsIm5iZiI6MTczMDYxODg2MywicGF0aCI6Ii83Mzg0NTU3NC8zODI1NTQ0MTMtMWI2Mjg4NWUtMGVhZi00ODM0LWIxOGEtN2NiNjI4NmFiZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA3Mjc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMTAwNDJkZmYyYmI3ZTc3ODg3MzA2NTQ3MTlkNzdkMThmYTk5YTIzOTk5YzE3OTczMDNkNGE2Nzk2NThmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4GcxK-xlnZek2dkQLLemcGqpcztwDfTXwwOAdQT8WEU)

Нет, это сделано специально для некого "успокоения пользователя"

**Comment by uertyk** [comment]
> так может потому что winws подменяет пакеты для обхода? в репозитории всё написано ![{3A73099A-53C4-4C3B-B02F-D83EB087B011}](https://private-user-images.githubusercontent.com/73845574/382554413-1b62885e-0eaf-4834-b18a-7cb6286abd83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MTkxNjMsIm5iZiI6MTczMDYxODg2MywicGF0aCI6Ii83Mzg0NTU3NC8zODI1NTQ0MTMtMWI2Mjg4NWUtMGVhZi00ODM0LWIxOGEtN2NiNjI4NmFiZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA3Mjc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMTAwNDJkZmYyYmI3ZTc3ODg3MzA2NTQ3MTlkNzdkMThmYTk5YTIzOTk5YzE3OTczMDNkNGE2Nzk2NThmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4GcxK-xlnZek2dkQLLemcGqpcztwDfTXwwOAdQT8WEU)

По тому же можно сказать, что само название "HackTool/RickTool" , не говорит само за себя.

**Comment by serpen7** [comment]
Это же мой скриншот там вообще и я как бы ниже объяснял что это не вирус =/
Чел это эвристики, естественно они будут флагать поведение трояна на прилоге которая не подписана и которая является фильтром трафика, модифицируя его, чтобы задурить ТСПУ. Каспер даже писал в свое время что это не вирус риск тулса, потому что это можно превратить в вирус в нехороших руках. Поэтому и пишут как и с гудбайдпи, что не скачивайте прогу непонятно от кого и откуда в интернете т.к. риск словить вирь реальный не маленький. И уже были случаи. И были случаи подделки репозиториев.

И да этот скриншот вообще был в теме человечка который возможно таки и скачал не с этого репозитория, а откуда то с интернета т.к. там довольно много срабатываний было по сравнению с винвс в последней версии. И хеш тоже не сходился.

Тебя почитать так ты просто пособирал информацию разную обрывками и вырвал слова из контекста у многих. Пытаешься навести суету как скандальные блогеры для просмотров? Нафига? Любой более менее прошаренный человек в компах и прогах прочтет только твои "умозаключения" и сделает жест "рукалицо"...
Тем более что ты явно не знаешь как читать вирустотал по анализу и что за сигнатуры он выдает, зачем и почему.

> По тому же можно сказать, что само название "HackTool/RickTool" , не говорит само за себя.

ты видимо и игры с торрентов поэтому не ставишь потому что все кряки это хактул\рисктул т.к. они ломают код защиты игры или программ чтобы обойти его. А это по сути дела поведение трояна на компе. Вмешиваться в процесс и делать свои дела в системе.

И да насчет каспер не найдет - файл явно отправляли на лабу касперского или форумы для анализа потому что его флагало как раз таки пару дней и потом с обновлением баз это пропало, видимо там проанализировали файл и поняли что это не вирус. А отправляли его туда скорее всего кучи людей которые были обеспокоены тоже. Видимо для тебя целая лаба касперского и профессиональные люди работающие на определении вирусни вручную анализирующие файлы это пустой звук, у тебя больше опыта в этой сфере явно =/

**Comment by uertyk** [comment]
> Это же мой скриншот там вообще и я как бы ниже объяснял что это не вирус =/ Чел это эвристики, естественно они будут флагать поведение трояна на прилоге которая не подписана и которая является фильтром трафика, модифицируя его, чтобы задурить ТСПУ. Каспер даже писал в свое время что это не вирус риск тулса, потому что это можно превратить в вирус в нехороших руках. Поэтому и пишут как и с гудбайдпи, что не скачивайте прогу непонятно от кого и откуда в интернете т.к. риск словить вирь реальный не маленький. И уже были случаи. И были случаи подделки репозиториев.
> 
> И да этот скриншот вообще был в теме человечка который возможно таки и скачал не с этого репозитория, а откуда то с интернета т.к. там довольно много срабатываний было по сравнению с винвс в последней версии. И хеш тоже не сходился.
> 
> Тебя почитать так ты просто пособирал информацию разную обрывками и вырвал слова из контекста у многих. Пытаешься навести суету как скандальные блогеры для просмотров? Нафига? Любой более менее прошаренный человек в компах и прогах прочтет только твои "умозаключения" и сделает жест "рукалицо"... Тем более что ты явно не знаешь как читать вирустотал по анализу и что за сигнатуры он выдает, зачем и почему.
> 
> > По тому же можно сказать, что само название "HackTool/RickTool" , не говорит само за себя.
> 
> ты видимо и игры с торрентов поэтому не ставишь потому что все кряки это хактул\рисктул т.к. они ломают код защиты игры или программ чтобы обойти его.
> 
> И да насчет каспер не найдет - файл явно отправляли на лабу касперского или форумы для анализа потому что его флагало как раз таки пару дней и потом с обновлением баз это пропало, видимо там проанализировали файл и поняли что это не вирус. А отправляли его туда скорее всего кучи людей которые были обеспокоены тоже. Видимо для тебя целая лаба касперского и профессиональные люди работающие на определении вирусни вручную анализирующие файлы это пустой звук, у тебя больше опыта в этой сфере явно =/

Я так же искал информацию в лабе Касперского, там писали что это те же вирусы, и пытались их вывести.

**Comment by serpen7** [comment]
> Я так же искал информацию в лабе Касперского, там писали что это те же вирусы, и пытались их вывести.

Потому что люди качали непойми откуда с интернета сборки? Незнамо от кого? Тебе уже сказали что и гудбайдпи, и запрет подделывают в интернете и ловят реальные вирусы люди от этого. Потому что ими стало пользоваться кучи людей, думаешь даже школьники которые банально могут вирь встроить не поняли этого?

Гудбайдпи так вообще сталкивался пару месяцев назад с подделкой репозитория где была реально вирусня. Люди за пару дней снесли его репортами. А там даже подделывали имя разраба проги просто добавив в него S на конце. Но снесли и снесли, а сколько людей скачали это? Потому что как минимум один все же решил спросить на форуме нтс и тогда начался движ.

**Comment by uertyk** [comment]
> > Я так же искал информацию в лабе Касперского, там писали что это те же вирусы, и пытались их вывести.
> 
> Потому что люди качали непойми откуда с интернета сборки? Незнамо от кого? Тебе уже сказали что и гудбайдпи, и запрет подделывают в интернете и ловят реальные вирусы люди от этого. Потому что ими стало пользоваться кучи людей, думаешь даже школьники которые банально могут вирь встроить не поняли этого?

Я всегда перед скачиванием чего либо проверяю файл разными путями, особенно читаю форумы, тут же я просто скачал, а задался вопросом только сейчас, так как многие писали мне, чтобы удалять запрет. Я не придавал этому значения до нынешнего, но, допустим я был не прав, почему тогда лагает проводник, как и у многих, и в общем устройство после скачивания сильно нагружается?

**Comment by serpen7** [comment]
Что у 10ки, что у 11 винды, но у 11 чаще даже и особенно в последние месяцы, из за обнов ломался функционал. Это было даже до запрета. Чтобы понять это нужно разбираться в ситуации, а не кричать что это просто из за проги которую ты недавно скачал и значит она виновата. 
Гуглом умеешь пользоваться же?
Загугли windows 11 explorer crashing и поставь чтобы выбрало ссылки за последний месяц
![image](https://github.com/user-attachments/assets/a38c8561-7887-40d9-93fd-5b7c8c0f63f3)

**Comment by uertyk** [comment]
> Что у 10ки, что у 11 винды, но у 11 чаще даже и особенно в последние месяцы, из за обнов ломался функционал. Это было даже до запрета. Чтобы понять это нужно разбираться в ситуации, а не кричать что это просто из за проги которую ты недавно скачал и значит она виновата. Гуглом умеешь пользоваться же? Загугли windows 11 explorer crashing и поставь чтобы выбрало ссылки за последний месяц ![image](https://private-user-images.githubusercontent.com/134365619/382556426-a38c8561-7887-40d9-93fd-5b7c8c0f63f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjE4MjYsIm5iZiI6MTczMDYyMTUyNiwicGF0aCI6Ii8xMzQzNjU2MTkvMzgyNTU2NDI2LWEzOGM4NTYxLTc4ODctNDBkOS05M2ZkLTViN2M4YzBmNjNmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwODEyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmQxZmE1MWIxYzIwZDY1NDQ0MjgzYzhiOTBiOTIzNjVhYjc3ZTRjMzI2MGM5N2I0N2Q1NDcyMjUwMDExYmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hbTWYHPIXHiwdsbw1bSXZBtNEwIMcl9vSSN_JFmelDw)

Тогда ладно, признаю что ошибся, спасибо за помощь!

**Comment by serpen7** [comment]
Я еще в бородатые годы когда пробовал 11 винду тоже ловил краш эксплорера сразу же считай, потом пробовал через год они не такие частые были, но раза 2 в неделю стабильно. Плюнул на все и откатывал на 10ку. Благо я делал перед всеми этими пробами полный бекап системы 10ки поэтому восстановить ее без проблем как была  не представляло трудности.

Ты главное не качай не пойми откуда, что запрет, что гудбайдпи, а проверяй репозитории т.к. могут быть и фейки как раз таки с вирусней.

На 10ке кстати тоже были проблемы когда они обновили панель и ввели там погоду, это повесило ее считай или вешало через какое то время. Даже пуск не открывался. И что ты думаешь они быстро это пофиксили? Майки не из этих. Они пофиксили это только спустя 1-3 месяца =/

**Comment by uertyk** [comment]
> Я еще в бородатые годы когда пробовал 11 винду тоже ловил краш эксплорера сразу же считай, потом пробовал через год они не такие частые были, но раза 2 в неделю стабильно. Плюнул на все и откатывал на 10ку. Благо я делал перед всеми этими пробами полный бекап системы 10ки поэтому восстановить ее без проблем как была не представляло трудности.
> 
> Ты главное качай не пойми откуда, что запрет, что гудбайдпи, а проверяй репозитории т.к. могут быть и фейки как раз таки с вирусней.

Я и проверяю, вроде скачал именно с этого репозитория, гудбай у меня сам по себе почему-то не работает, по этому лучше не качаю (все с официальных источников 100%)

**Comment by serpen7** [comment]
> Я и проверяю, вроде скачал именно с этого репозитория, гудбай у меня сам по себе почему-то не работает, по этому лучше не качаю (все с официальных источников 100%)

гудбай может не работать из за конфига. Я например не мог заставить нормально работать гудбай и запрет в связке со своим старым конфигом и периодически врубая впн, иннет крашился. Но подобрал конфиг для запрета и вроде как начало все работать особенно с последней версией general alt заработал у меня идеально. А в гудбайдпи я понял что set ttl все как раз таки и химичил что не открывались блок сайты. В итоге сменил конфиг на старую 9ку, поставил вместо сет ттл ауто ттл и запускаю вместе с запретом на генерал альт, ютуб вообще перестал почти что тормозить видосы. А то были прогрузки по секунд 12-16 периодически что бесило. Ну и на сайты заблоченные пускает бодро тоже.

**Comment by exzolink** [comment]
Каждый раз забавно такие заявления читать
