### ISSUE TITLE
Вылетает батник после запуска.

### ISSUE THREAD

**Issue by OSINTyou** [Flowseal/zapret-discord-youtube#552]
Скачал запрет 1.5.1.
Распаковал в C:\Zapret.
Запустил при помощи администратора discord.bat, появилось окно и сразу вылетело.
Открыл и выдаёт такое.
![image](https://github.com/user-attachments/assets/878ddfdf-9fb4-4dbf-ad16-ac793cb21065)

Windows 10 Pro | 22H2

Помогите пожалуйста.

**Comment by serpen7** [comment]
А у тебя винвс процесс не появился внизу на панели такой
![image](https://github.com/user-attachments/assets/b3db2a3f-9363-4736-b341-18dcb824980b)

**Comment by serpen7** [comment]
а у тебя винвс не появился на панели такой? 
![image](https://github.com/user-attachments/assets/9a8e87f9-6768-4706-93ec-7996ca0f2a27)

**Comment by serpen7** [comment]
А у тебя винвс не появился на панельке внизу вот такой?
![image](https://github.com/user-attachments/assets/cc72c10a-6b0b-4084-a44c-4e15ee7774f4)

**Comment by OSINTyou** [comment]
> а у тебя винвс не появился на панели такой? ![изображение](https://private-user-images.githubusercontent.com/134365619/382559182-9a8e87f9-6768-4706-93ec-7996ca0f2a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjUxNjksIm5iZiI6MTczMDYyNDg2OSwicGF0aCI6Ii8xMzQzNjU2MTkvMzgyNTU5MTgyLTlhOGU4N2Y5LTY3NjgtNDcwNi05M2VjLTc5OTZjYTBmMmEyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwOTA3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTNlZWQyMDIxYmI5MTk4NDg0ODFhYjZiZmViNGJkZDgwY2YyZDNhZDM0ODI2OTAyNGYwZDUwM2UzY2IyMTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6FRO8cSPw6S9eIJQQ3npdHGwJT-aJ0z3mY-91mi9MRE)

Нет

**Comment by serpen7** [comment]
у тебя винвс не появился внизу на панельке? Или может ты думаешь что батник должен запускаться?

**Comment by serpen7** [comment]
> > а у тебя винвс не появился на панели такой? ![изображение](https://private-user-images.githubusercontent.com/134365619/382559182-9a8e87f9-6768-4706-93ec-7996ca0f2a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjUxNjksIm5iZiI6MTczMDYyNDg2OSwicGF0aCI6Ii8xMzQzNjU2MTkvMzgyNTU5MTgyLTlhOGU4N2Y5LTY3NjgtNDcwNi05M2VjLTc5OTZjYTBmMmEyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwOTA3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTNlZWQyMDIxYmI5MTk4NDg0ODFhYjZiZmViNGJkZDgwY2YyZDNhZDM0ODI2OTAyNGYwZDUwM2UzY2IyMTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6FRO8cSPw6S9eIJQQ3npdHGwJT-aJ0z3mY-91mi9MRE)
> 
> Нет

так это он и есть он работает

**Comment by serpen7** [comment]
странно а можешь открыть просто cmd от имени администратора и написать sfc /scannow что выдаст?

**Comment by serpen7** [comment]
нифига не пойму что с сообщениями на гите, какое то месиво получается почему то в теме.

**Comment by OSINTyou** [comment]
> у тебя винвс не появился внизу на панельке? Или может ты думаешь что батник должен запускаться?

На панельке снизу? не не вижу. Я смотрел гайды он не должен вылетать

**Comment by serpen7** [comment]
проверь антивирус на наличие манипуляции с папкой запрета, в антивирусе есть журнал.

**Comment by OSINTyou** [comment]
> странно а можешь открыть просто cmd от имени администратора и написать sfc /scannow что выдаст?

Проверка 100% завершена.

Программа защиты ресурсов Windows обнаружила поврежденные файлы и успешно
их восстановила.

**Comment by serpen7** [comment]
> > странно а можешь открыть просто cmd от имени администратора и написать sfc /scannow что выдаст?
> 
> Проверка 100% завершена.
> 
> Программа защиты ресурсов Windows обнаружила поврежденные файлы и успешно их восстановила.

ну команды у тебя проходят, а значти с консолью все впорядке.

**Comment by OSINTyou** [comment]
> > > странно а можешь открыть просто cmd от имени администратора и написать sfc /scannow что выдаст?
> > 
> > 
> > Проверка 100% завершена.
> > Программа защиты ресурсов Windows обнаружила поврежденные файлы и успешно их восстановила.
> 
> ну команды у тебя проходят, а значит с консолью все в порядке.

У моих друзей батник не закрывается.

**Comment by serpen7** [comment]
А вообще зачем ты запускаешь батник из CMD вместо того чтобы просто запустить его из проводника?

**Comment by OSINTyou** [comment]
Может это из за сервисов? 
Я всё выключил но в сервисах выполняется AmneziaVPN-service
OpenVPNService
Radmin VPN Control Service

**Comment by OSINTyou** [comment]
Что с гитом происходит?

**Comment by OSINTyou** [comment]
> А вообще зачем ты запускаешь батник из CMD вместо того чтобы просто запустить его из проводника?

Я когда его запускаю он сразу вылетает

**Comment by serpen7** [comment]
> Может это из за сервисов? Я всё выключил но в сервисах выполняется AmneziaVPN-service OpenVPNService Radmin VPN Control Service

врядли, они не должны по идее мешать

**Comment by OSINTyou** [comment]
У меня сначала была проблема с "chcp" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

Но ChatGpt мне помог её решить

**Comment by serpen7** [comment]
Выглядит примерно так запуск из командной строки если ты по каким то соображениям не хочешь запускать его просто из проводника почему то. 

https://github.com/user-attachments/assets/2612d47e-ecda-4509-828b-b1d42a0053cf

**Comment by serpen7** [comment]
> Что с гитом происходит?

вот и я тоже не пойму, комментарии превращаются в месиво какое то...

**Comment by OSINTyou** [comment]
> проверьте антивирус на наличие манипуляций с папкой запрета, в антивирусе есть журнал.
> 
> А также убедись, что ты скачал его из репозитория https://github.com/Flowseal/zapret-discord-youtube/releases

![image](https://github.com/user-attachments/assets/d470163c-c567-442d-bf3d-9df00d8e8245)
Антивирусник отключён.
Я уверен, что я скачал с. https://github.com/Flowseal/zapret-discord-youtube/releases

**Comment by OSINTyou** [comment]
> Выглядит примерно так запуск из командной строки если ты по каким то соображениям не хочешь запускать его просто из проводника почему то.
> 
>  2024-11-03.12-43-03.mp4

https://github.com/user-attachments/assets/9b77a8d4-98af-4e53-bd49-869c8a4eee5a

**Comment by OSINTyou** [comment]
> > Что с гитом происходит?
> 
> вот и я тоже не пойму, комментарии превращаются в месиво какое то...

Ну что там понял как решить эту проблему?

**Comment by serpen7** [comment]
так у тебя ж он вот же не? 
![image](https://github.com/user-attachments/assets/8e8f3937-10ae-4d10-bbdb-ed08f4853233)

**Comment by OSINTyou** [comment]
> так у тебя ж он вот же не? ![image](https://private-user-images.githubusercontent.com/134365619/382564381-8e8f3937-10ae-4d10-bbdb-ed08f4853233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzA4NDEsIm5iZiI6MTczMDYzMDU0MSwicGF0aCI6Ii8xMzQzNjU2MTkvMzgyNTY0MzgxLThlOGYzOTM3LTEwYWUtNGQxMC1iYmRiLWVkMDhmNDg1MzIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMDQyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDg3Y2JmNTA4YzI5ZDM4ZjgzOGNhODU1ZDQ5ZjFkNDM5NDZkZGE5NDUxNzk2NGE1NWUyMTY5MmEwMmQ1MGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rUX5EDh1fiPDTsv2iIlH6-LodsIwAsLgzwThRAzvo2Y)

Это сервисы services.msc

**Comment by serpen7** [comment]
> > так у тебя ж он вот же не? ![image](https://private-user-images.githubusercontent.com/134365619/382564381-8e8f3937-10ae-4d10-bbdb-ed08f4853233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzA4NDEsIm5iZiI6MTczMDYzMDU0MSwicGF0aCI6Ii8xMzQzNjU2MTkvMzgyNTY0MzgxLThlOGYzOTM3LTEwYWUtNGQxMC1iYmRiLWVkMDhmNDg1MzIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMDQyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDg3Y2JmNTA4YzI5ZDM4ZjgzOGNhODU1ZDQ5ZjFkNDM5NDZkZGE5NDUxNzk2NGE1NWUyMTY5MmEwMmQ1MGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rUX5EDh1fiPDTsv2iIlH6-LodsIwAsLgzwThRAzvo2Y)
> 
> Это сервисы services.msc

я так понимаю winws не хочет запускаться почему то, посмотри может в системном журнале винды найдешь почему, может быть он не совместим с 11 виндой.

**Comment by serpen7** [comment]
Потому что в оригинальном репозитории bol-van там есть такая вот приписочка 
![image](https://github.com/user-attachments/assets/0fa33a4e-cbef-4551-9b5d-eda029934fe3)

**Comment by OSINTyou** [comment]
> > > так у тебя ж он вот же не? ![image](https://private-user-images.githubusercontent.com/134365619/382564381-8e8f3937-10ae-4d10-bbdb-ed08f4853233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzA4NDEsIm5iZiI6MTczMDYzMDU0MSwicGF0aCI6Ii8xMzQzNjU2MTkvMzgyNTY0MzgxLThlOGYzOTM3LTEwYWUtNGQxMC1iYmRiLWVkMDhmNDg1MzIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMDQyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDg3Y2JmNTA4YzI5ZDM4ZjgzOGNhODU1ZDQ5ZjFkNDM5NDZkZGE5NDUxNzk2NGE1NWUyMTY5MmEwMmQ1MGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rUX5EDh1fiPDTsv2iIlH6-LodsIwAsLgzwThRAzvo2Y)
> > 
> > 
> > Это сервисы services.msc
> 
> я так понимаю winws не хочет запускаться почему то, посмотри может в системном журнале винды найдешь почему, может быть он не совместим с 11 виндой.

![image](https://github.com/user-attachments/assets/9aedb766-014c-4ec4-b52e-b02d38a705ad)

**Comment by OSINTyou** [comment]
> Потому что в оригинальном репозитории bol-van там есть такая вот приписочка ![image](https://private-user-images.githubusercontent.com/134365619/382564823-0fa33a4e-cbef-4551-9b5d-eda029934fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzEzOTcsIm5iZiI6MTczMDYzMTA5NywicGF0aCI6Ii8xMzQzNjU2MTkvMzgyNTY0ODIzLTBmYTMzYTRlLWNiZWYtNDU1MS05YjVkLWVkYTAyOTkzNGZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMDUxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDgxMzY1NDc2MjIyYjI5YTBiMmRmNTgzMTkwMzBkZjViNzFkY2MxNTM0OWJkZjQ5Y2QwOTVhMzA1YWQyYzA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ib90JMibRVXv_iBXvfWjLuJ2MS7HMpuiUQI9iyyEPzQ)

И что делать? В BIOS лезть?

**Comment by serpen7** [comment]
> ![image](https://private-user-images.githubusercontent.com/181209770/382564838-9aedb766-014c-4ec4-b52e-b02d38a705ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzEyOTAsIm5iZiI6MTczMDYzMDk5MCwicGF0aCI6Ii8xODEyMDk3NzAvMzgyNTY0ODM4LTlhZWRiNzY2LTAxNGMtNGVjNC1iNTJlLWIwMmQzOGE3MDVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMDQ5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWM3OWUxYjBhMGZkZTcwOWNkZjJhNDg5ZjI4YzNmMTI5ZGRhMjU2NTc0OWU5NjhiOWFiYjJmYWI5YTFlMmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ExYK3xO5pPQNexJe7KRFuOSkWoiZesXrba9Uq10xNe8)

Винда почему то не дает запустить, все оказалось просто. А вот почему тут другой вопрос и он более сложный.

**Comment by serpen7** [comment]
> > Потому что в оригинальном репозитории bol-van там есть такая вот приписочка ![image](https://private-user-images.githubusercontent.com/134365619/382564823-0fa33a4e-cbef-4551-9b5d-eda029934fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzEzOTcsIm5iZiI6MTczMDYzMTA5NywicGF0aCI6Ii8xMzQzNjU2MTkvMzgyNTY0ODIzLTBmYTMzYTRlLWNiZWYtNDU1MS05YjVkLWVkYTAyOTkzNGZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMDUxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDgxMzY1NDc2MjIyYjI5YTBiMmRmNTgzMTkwMzBkZjViNzFkY2MxNTM0OWJkZjQ5Y2QwOTVhMzA1YWQyYzA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ib90JMibRVXv_iBXvfWjLuJ2MS7HMpuiUQI9iyyEPzQ)
> 
> И что делать? В BIOS лезть?

не, у тебя винда блочит драйвер виндайверта, без него и не запускается винвс.

**Comment by OSINTyou** [comment]
> > > Потому что в оригинальном репозитории bol-van там есть такая вот приписочка ![image](https://private-user-images.githubusercontent.com/134365619/382564823-0fa33a4e-cbef-4551-9b5d-eda029934fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzEzOTcsIm5iZiI6MTczMDYzMTA5NywicGF0aCI6Ii8xMzQzNjU2MTkvMzgyNTY0ODIzLTBmYTMzYTRlLWNiZWYtNDU1MS05YjVkLWVkYTAyOTkzNGZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMDUxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDgxMzY1NDc2MjIyYjI5YTBiMmRmNTgzMTkwMzBkZjViNzFkY2MxNTM0OWJkZjQ5Y2QwOTVhMzA1YWQyYzA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ib90JMibRVXv_iBXvfWjLuJ2MS7HMpuiUQI9iyyEPzQ)
> > 
> > 
> > И что делать? В BIOS лезть?
> 
> не, у тебя винда блочит драйвер виндайверта, без него и не запускается винвс.

И как это чинить?

**Comment by serpen7** [comment]
![image](https://github.com/user-attachments/assets/2bcc8359-ffb2-45af-b820-2d929b3d8680)

**Comment by serpen7** [comment]
> И как это чинить?

в этом то и вопрос, почему она его блочит у тебя.

**Comment by OSINTyou** [comment]
у меня 10 win

**Comment by OSINTyou** [comment]
> > И как это чинить?
> 
> в этом то и вопрос, почему она его блочит у тебя.

![image](https://github.com/user-attachments/assets/11f0a1c3-6f81-45b9-8345-3cb13983a045)

**Comment by serpen7** [comment]
так бы не работало у всех на винде 11, тут дело в чем то другом, почему пишет отказано в доступе и что происходит. Попробуй запустить service_remove от имени администратора батник

**Comment by serpen7** [comment]
> у меня 10 win

эм, панелька кастомная?

**Comment by OSINTyou** [comment]
> так бы не работало у всех на винде 11, тут дело в чем то другом, почему пишет отказано в доступе и что происходит. Попробуй запустить service_remove от имени администратора батник

https://github.com/user-attachments/assets/239df7b4-b47d-4656-88c1-08a5f6456de4

**Comment by OSINTyou** [comment]
> > у меня 10 win
> 
> эм, панелька кастомная?

Да

**Comment by hennessy73** [comment]
такая же проблема:(
ПКМ по папке бин - общие - другие и ставь галочку над пунктом "разрешить индексировать содержимое файлов в этой папке в дополнение к свойствам файла - ок - применить 
после запуска батник не пропадал, но после повторного запуска пк проблема осталась

**Comment by OSINTyou** [comment]
> такая же проблема:( ПКМ по папке бин - общие - другие и ставь галочку над пунктом "разрешить индексировать содержимое файлов в этой папке в дополнение к свойствам файла - ок - применить после запуска батник не пропадал, но после повторного запуска пк проблема осталась

Действительно работает.
Спасибо добрый человек)

**Comment by OSINTyou** [comment]
> такая же проблема:( ПКМ по папке бин - общие - другие и ставь галочку над пунктом "разрешить индексировать содержимое файлов в этой папке в дополнение к свойствам файла - ок - применить после запуска батник не пропадал, но после повторного запуска пк проблема осталась
Я это сделал и теперь мне ну нужно всегда разрешать индексировать содержимое файла.


1. Настройка запуска драйвера через реестр
Если ни один из вышеперечисленных методов не помогает, можно попробовать настроить загрузку драйвера через реестр:
Откройте Редактор реестра (Win + R, затем введите regedit).
Перейдите в HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert.
Убедитесь, что значение параметра Start установлено на 3 (Manual), а не 4 (Disabled).


2. Проверка прав доступа к файлу после перезагрузки
Иногда после перезагрузки могут сбрасываться права на файл. Убедитесь, что вашей учетной записи и SYSTEM разрешён полный доступ к файлу WinDivert64.sys:
Щелкните правой кнопкой мыши на WinDivert64.sys > Свойства > Безопасность > Изменить права доступа.
Всем полный доступ расставь.

**Comment by Flowseal** [comment]
Решено, я полагаю?
