### ISSUE TITLE
Ошибка не удаётся найти файл

### ISSUE THREAD

**Issue by Cenz0Red** [Flowseal/zapret-discord-youtube#556]
Какой бы батник я ни запускал, всегда пишется один и тот же текст: не удаётся найти С:\Users\.....\zapret-discord-youtube-1.5.1 проверьте, правильно ли указано имя
Подскажите, что я делаю не так?

**Comment by Flowseal** [comment]
Либо не разархивировали, либо файлы съел антивирус (или прочее защитное по, в т.ч. браузерная защита)
