### ISSUE TITLE
После проверки касперским перестал работать скрипт помогите

### ISSUE THREAD

**Issue by Impat1a** [Flowseal/zapret-discord-youtube#558]

**Comment by serpen7** [comment]
Откуда качали запрет, какая версия касперского? Потому что сколько стоит каспер он не трогает запрет.

**Comment by Impat1a** [comment]
скачял запрет от сюда же а касперский не знаю просто мне высветил касперский что здесь вредоносный файл и я его проверил я перезапустил пк и теперь не заходит в программу
\

**Comment by serpen7** [comment]
> скачял запрет от сюда же а касперский не знаю просто мне высветил касперский что здесь вредоносный файл и я его проверил я перезапустил пк и теперь не заходит в программу \

он и не зайдет он его удалил потому что у вас автомат на действиях полный, а не лечение или же информирование при блоке. Вам нужно его перекачивать и заносить в исключения файл на который он ругается. Обновите так же базы касперского может он перестанет ругаться на файлы запрета. У меня перестал уже как почти неделю. Лишь выдает что это риск тулса потому что если вы скачаете ее незнамо от кого и откуда вы рискуете что это превратится в полноценный вирус.

**Comment by Impat1a** [comment]
у меня в касперском нету вкладкаи что бы сделать искючение
я уже просто пытался решить эту проблему а в каспермком по инструкции я не нашел этой вкладки

**Comment by serpen7** [comment]
ну не знаю как ее нельзя найти либо тут 
![image](https://github.com/user-attachments/assets/3d1508f1-e91a-4419-99de-e1cba20d234c)

, либо тут

![image](https://github.com/user-attachments/assets/3b12eec6-e657-42fe-8d44-52dd8cfbf086)

**Comment by Impat1a** [comment]
а где это ?

**Comment by Impat1a** [comment]
у меня касперский free  и везде  на видосах другая версия  или я не понимаю

**Comment by serpen7** [comment]
> у меня касперский free и везде на видосах другая версия или я не понимаю

какая версия каспера?

**Comment by Impat1a** [comment]
а ты не знаешь где можно узнать?

**Comment by serpen7** [comment]
> а ты не знаешь где можно узнать?

в приложениях и возможностях в винде легче

**Comment by Impat1a** [comment]
Я нашел с помощю поиска  исключения

**Comment by Impat1a** [comment]
можешь подсказать как попасть к tool

**Comment by Impat1a** [comment]
или сказать полное название

**Comment by serpen7** [comment]
> можешь подсказать как попасть к tool

зачем? 
![image](https://github.com/user-attachments/assets/79207dd6-404d-4ef9-b797-f37dc3dbbe4d)

**Comment by Impat1a** [comment]
нет нет нет не к  касперскому а то что нужно добавить в исключение

**Comment by serpen7** [comment]
> нет нет нет не к касперскому а то что нужно добавить в исключение

то что каспер будет выводить как рисктулсу или нотвирус а это будет по идее windivert. Без него winws не запустится.

**Comment by serpen7** [comment]
так будет думаю понятнее 
![image](https://github.com/user-attachments/assets/56a0c293-773e-44cc-930a-d1cf08d7ac96)
делается тут внизу 

![Image](https://github.com/user-attachments/assets/5e75bb83-571e-4604-817e-10e38c1a1500)

**Comment by Impat1a** [comment]
да я это нашел я не могу вписать название объекта

**Comment by serpen7** [comment]
> да я это нашел я не могу вписать название объекта

оно и не нужно, тебе нужно только указать файл и все, все остальное там не нужно особо

но если хочешь вот тебе описание
not-a-virus:HEUR:RiskTool.Multi.WinDivert.gen

**Comment by Impat1a** [comment]
ух значит я все равно не понимаю в чем проблема
 потому что я попробовал и все равно закрываеться консоль

**Comment by serpen7** [comment]
> ух значит я все равно не понимаю в чем проблема потому что я попробовал и все равно закрываеться консоль

ее и должно закрывать открываться должен процесс новый winws.

**Comment by Impat1a** [comment]
я два раза кликаю мне просит запрос winws и все пропадает
а дискорд не работает

**Comment by serpen7** [comment]
закрывай вин вс на панели и пробуй другие батники.
![image](https://github.com/user-attachments/assets/0a90d5c9-b90e-4651-9e21-26645339fef2)

**Comment by Impat1a** [comment]
а winws тоже закрываеться сразу

**Comment by Impat1a** [comment]
я уже все батники по открывал

**Comment by Impat1a** [comment]
сударь а вы не против пойти в телеграм и я вам включу демонстрацию экрана и так будет намного легче

**Comment by serpen7** [comment]
> а winws тоже закрываеться сразу

тогда смотри скачиваешь это https://github.com/ValdikSS/GoodbyeDPI/releases
И это https://github.com/Flowseal/zapret-discord-youtube/releases
 по последним версиям
 запускаешь service remove bat из обоих скачанных репозиториев поочередно от имени администратора, жмешь кнопку любую, жмешь еще раз любую кнопку, перезагружаешь комп, опять повторяешь сервис ремув бат от администратора и уже после пробуешь что либо из этих батников, смотря что у тебя заработает.
 
 Запускать все батники одновременно не надо, их нужно пробовать по одному и закрывая если он не сработал процесс winws который у тебя открывается после батника каждого на твоей панельке внизу.

**Comment by Impat1a** [comment]
а гуд бай дпи в одну папку с запретом или ив разные?

**Comment by serpen7** [comment]
> а гуд бай дпи в одну папку с запретом или ив разные?

в разные это на случай если когда то ставилась эта служба когда либо и ты не помнишь точно
Все равно ничему не повредит.

**Comment by Impat1a** [comment]
я так и не понял в разные или в одну

**Comment by serpen7** [comment]
> я так и не понял в разные или в одну

лучше в разные чтобы не путать

**Comment by Impat1a** [comment]
о господи

**Comment by Impat1a** [comment]
списибо я бы без тебя не справился

**Comment by Impat1a** [comment]
спасибо незнакомец я очень тебе благодарен

**Comment by serpen7** [comment]
> спасибо незнакомец я очень тебе благодарен

так заработало?

**Comment by Ivveod** [comment]
@serpen7, Я не знаю, кто ты, какой у тебя характер и какой ты вообще человек по жизни. Но я могу сказать, что ты делаешь хорошее дело, и за это могут сказать как минимум те двое, которым ты помог. Я прочитал весь ваш диалог, и теперь у меня тоже всё работает. К чёрту «Касперский»!

**Comment by suhco1** [comment]
змея7 спасибо за инструкцию, крассавчик. просто лучший!

**Comment by raddy222** [comment]
Ребят, у меня не работает, делал все как этот бро говорил. Помогите

**Comment by Ivveod** [comment]
> Ребята, у меня не работает, я делал все, как этот чувак говорил. Помогите

Напиши мне почту, я попробую помочь svodpravill@gmail.com

**Comment by Flyggy** [comment]
у меня ничего не получилось :( помогите пожалуйста
