### ISSUE TITLE
Долгий заход в дискорд, бесконечное подключение во время звонка

### ISSUE THREAD

**Issue by wraayyak** [Flowseal/zapret-discord-youtube#56]
![image](https://github.com/user-attachments/assets/d5b538ad-66ef-4ab7-97df-675b0d7fa960)

**Comment by 4ainik4aevarov** [comment]
Вот точно также. При попытке зайти в любой голосовой канал идут бесконечные попытки подключиться

**Comment by Vasyokvk** [comment]
Да, абсолютно то же самое, всё работает - но в гс не заходит, кстати и для ютуба тоже попробовал - там просто идеально всё работает, ни малейшей ни на секунду просадки - ютуб идеально, осталось дискорд наладить.
P.s. Буквально только что заработало - видимо думал\грузил, попробуйте перейти в другой гс и подождать минут 5-10, у меня подключилось

**Comment by wraayyak** [comment]
> Вот точно также. При попытке зайти в любой голосовой канал идут бесконечные попытки подключиться

поменяй сервер подключения, помогло

**Comment by Leon74RA** [comment]
ты открыл service_discord.bat от имени администратора? мне помогло

**Comment by 4ainik4aevarov** [comment]
> > Вот точно также. При попытке зайти в любой голосовой канал идут бесконечные попытки подключиться
> 
> поменяй сервер подключения, помогло

А как его менять?

**Comment by 4ainik4aevarov** [comment]
> ты открыл service_discord.bat от имени администратора? мне помогло

От имени администратора открывал и service файлы, и обычные. Весь остальной дискорд работает нормально, но к звонку он присоединиться не может

**Comment by MazayZ** [comment]
Такая же проблема

**Comment by MazayZ** [comment]
Такая же проблема, ютуб робит, а дис бесконечное подключение(

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92

**Comment by dark654-cell** [comment]
После сегодняшний обновы дискорд не работает вообще и ни чего не помагает!

**Comment by luxor10** [comment]
![Image](https://github.com/user-attachments/assets/152fdeac-ecce-40a6-b0f4-396f964c8c25)
Попробуйте по открывать эти файли от имени от админа, мне помогло
