### ISSUE TITLE
Что делать?

### ISSUE THREAD

**Issue by Dixeone** [Flowseal/zapret-discord-youtube#57]
![image](https://github.com/user-attachments/assets/33931a90-6770-46b6-881d-6b8231966496)

**Comment by Flowseal** [comment]
Вы не перенесли папку bin
Примерная структура:
![image](https://github.com/user-attachments/assets/32ad7b7a-640d-4736-970c-9c074c4e4d27)

**Comment by Dixeone** [comment]
> Вы не перенесли папку bin Примерная структура: ![image](https://private-user-images.githubusercontent.com/50780822/375044575-32ad7b7a-640d-4736-970c-9c074c4e4d27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTYzODIsIm5iZiI6MTcyODQ5NjA4MiwicGF0aCI6Ii81MDc4MDgyMi8zNzUwNDQ1NzUtMzJhZDdiN2EtNjQwZC00NzM2LTk3MGMtOWMwNzRjNGU0ZDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE3NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmU1MGFkNGY3Y2IyNTBhZTc4MTBhMTQyMjVjMjI0ZWY5ZTUwZjdiYTUyNjk3OTZhNWNiMzgwMGI5Njk3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L9VQ8ii-1QQTobhACkKZdPgviqqOpnmiqzjvjxW1cEM)

Я перенес все также
