### ISSUE TITLE
Туго подгружаются картинки, аватарки, баннеры, видео и т.п. (Discord)

### ISSUE THREAD

**Issue by VivishkaRU** [Flowseal/zapret-discord-youtube#570]
Только вот пару минут назад началось, через VPN всё догружает, а сам запрет словно не могёт по какой-то причине

**Comment by PesDaLisik** [comment]
подтверждаю, такая же фигня

**Comment by OihhoMoiss** [comment]
Точно такая же проблема

**Comment by Fozien** [comment]
вообще перестало что-либо грузить

**Comment by VivishkaRU** [comment]
Отштормило, всё снова работает в штатном режиме, отбой

**Comment by Necoachan** [comment]
> Отштормило, всё снова работает в штатном режиме, отбой

ДВ все ещё туго

**Comment by Maks14a** [comment]
тоже самое а сам запрет словно не могёт по какой-то причине
