### ISSUE TITLE
вылеты игр, при запуске zapret

### ISSUE THREAD

**Issue by LevTrot** [Flowseal/zapret-discord-youtube#575]
Если коротко, то по какой-то причине, если запрет установлен(то есть запущен) на пк, то игры в стиме(последняя колда и пэйдэй 3, если быть совсем точным), просто закрываются через какое-то время после запуска. Без ошибки, без какой-либо причины. При этом использую только zapret для дискорда. После удаления запрета, все идеально работает, ни одного вылета. Пробовал уже около десятка раз, проблема действительно именно в zapret. С чем может быть связано и как такое теоритически можно решить? 
P.S. добавлю что проблемы наблюдаются только в данных играх, в нескольких других все нормально(не так уж много я пробовал, но условно лишь 2 из 10 не работают)

**Comment by serpen7** [comment]
Античитам этих игр не нравится драйвер фильтра и модификации трафика windivert.  Они и закрываются, это известная проблема. С гудбайдпи то же самое будет. Решения нет, потому что так работают эти античиты. А если маскировать это можно вполне себе отхватить полноценный бан поэтому маскировка это крайне рискованный выход.

**Comment by LevTrot** [comment]
Я так понимаю решить данную проблему не получится?

**Comment by serpen7** [comment]
> Я так понимаю решить данную проблему не получится?

Нет, если разрабы игры самой не сделают что-то на их стороне https://github.com/ValdikSS/GoodbyeDPI/issues/148
