### ISSUE TITLE
Не загружаются аватары пользователей, серверов, баннеры, эмоджи в Discord

### ISSUE THREAD

**Issue by ackylmyst** [Flowseal/zapret-discord-youtube#576]
Система Windows 11, Version 23H2. Провайдер МТС Новосибирск. При запуске любого из general-батников дискорд запускается, загружаются изображения, отправленные в чат. но аватары, баннеры, эмоджи с серверов не загружаются. Проблема появилась 05.11.2024 в 17:01EEST. Примеры прикреплены ниже.
![Снимок экрана 2024-11-05 221147](https://github.com/user-attachments/assets/045e9855-522d-48a7-a371-1b7f30902a91)
![Снимок экрана 2024-11-05 221245](https://github.com/user-attachments/assets/f74dece2-790d-4e53-a315-c41e441a41fb)

**Comment by AlexMeowler** [comment]
Та же проблема, Скайнет СПб, стандартные настройки zapret (service_goodbye_discord.bat)

**Comment by serpen7** [comment]
У вас походу та же самая проблема но она "плавает" от провайдера к провайдеру.
https://github.com/Flowseal/zapret-discord-youtube/issues/571
 Запрет не отменяет сбои в работе сервисов от разных провайдеров. Просто эти сбои стало сложно диагностировать что сбоит, из за блокировки ресурса.

**Comment by sh2kcs** [comment]
+1

**Comment by Anatomis** [comment]
+1

**Comment by Mitradis** [comment]
Перестал работать. Экотелеком. Чтото мутят ...... . Дискорд открывается, но не связь ни картинки ни аватарки не загружаются. Перестали открываться заблокированные сайты. Я совместил список сайтов от Гудбай с вашим запретом и использовал его для разблокировки (торренты в основном). Вот это все теперь отвалилось где-то процентов на 60-70. Что-то открывается, а что-то уже нет. Ютуб пока работает. Пришлось включить плагин в браузере для торрентов снова...
В общем враг не спит и разрабатывает новые методы запрета информации. Делается это тихо.

**Comment by AnonymousFS** [comment]
Здравствуйте дорогие читатели. Весь день пытался решить данную проблему и наконец то решил. Столкнулся вообще с тем что не запускался Discord из за бесконечной загрузки в окне Starting... .Не грузятся картинки тоже, но зайти в голосовой канал и разговаривать можно. На официальном сайте скачивайте версию DiscordPBT публичную бета версию. Главное чтобы работал zapret, я думал я один такой с проблемой) Переустановил винду и столкнулся, аж в тильт в пал на какое то время) 

Уральский провайдер Интерсвязь, столкнулся с такой же проблемой.

**Comment by MrGoldenFoxx** [comment]
![image](https://github.com/user-attachments/assets/89b4ac15-6d44-4363-bac4-83630b5ad54b)
Мб в этом проблема?

**Comment by AnonymousFS** [comment]
> Здравствуйте дорогие читатели. Весь день пытался решить данную проблему и наконец то решил. Столкнулся вообще с тем что не запускался Discord из за бесконечной загрузки в окне Starting... .Не грузятся картинки тоже, но зайти в голосовой канал и разговаривать можно. На официальном сайте скачивайте версию DiscordPBT публичную бета версию. Главное чтобы работал zapret, я думал я один такой с проблемой) Переустановил винду и столкнулся, аж в тильт в пал на какое то время)
> 
> Уральский провайдер Интерсвязь, столкнулся с такой же проблемой.

![image](https://github.com/user-attachments/assets/eb9d2eda-d948-4754-8e13-3b6b3dbf6281)

**Comment by scream-dev** [comment]
это точно хорошая идея? нет способа проще?

**Comment by AnonymousFS** [comment]
> это точно хорошая идея? нет способа проще?

сложности никакой, точно так же включаешь zapret устанавливаешь бета версию discrod логинешься и пользуешься)

**Comment by Boklan34** [comment]
> сложности никакой, точно так же включаешь zapret устанавливаешь бета версию discrod логинешься и пользуешься)
все равно не грузит

**Comment by enricfur** [comment]
+1

**Comment by Dronatar** [comment]
> это точно хорошая идея? нет способа проще?

После --filter-tcp=443 удали --hostlist="list-general.txt"

**Comment by serpen7** [comment]
> > это точно хорошая идея? нет способа проще?
> 
> После --filter-tcp=443 удали --hostlist="list-general.txt"

так ты будешь фильтровать весь трафик по этому порту, а не определенные вещи из листа, чтобы не ломать остальное что не поймет такие манипуляции с трафиком, чего не рекомендуется делать ибо это черевато...

**Comment by Dronatar** [comment]
> > это точно хорошая идея? нет способа проще?
> 
> После --filter-tcp=443 удали --hostlist="list-general.txt"

Новый способ _(будет разблокирован только Discord)_:
После --filter-tcp=443 заменить --hostlist="list-general.txt" на --ipset="ipset-discord.txt"

**Comment by pavuchek2** [comment]
> и

для особо одаренных можно подробнее?

**Comment by Reslik** [comment]
на, радуйтесь 
https://www.youtube.com/watch?v=t89R0gIlNww
https://www.youtube.com/watch?v=zZfPPAMHcqE&list=LL&index=7

**Comment by Kaiiliyy** [comment]
не помогло

**Comment by quetness** [comment]
^ также

обычная версия дискорда в целом не загружалась, то бишь идет успешный быстрый запуск и после некликабельный серый экран
вчера еще помогала перезагрузка интернета, сегодня перестала. установил бета версию дискорда - он запустился, ура, теперь просто не грузит аватарки, профили и изображения.

**Comment by Kaiiliyy** [comment]
помогла ульта от создателей юбуст

**Comment by anawellis** [comment]
такая же проблема,ростелеком

**Comment by Lightko** [comment]
cloudflare-ech.com

В листы добавьте прост

**Comment by svpev** [comment]
можно совместимость поменять либо на 8 винду либо на 7 и тогда все норм будет

**Comment by LSgANN** [comment]
> cloudflare-ech.com
> 
> В листы добавьте прост

добавил в оба листа, помогло, спасибо

**Comment by Caranir** [comment]
> можно совместимость поменять либо на 8 винду либо на 7 и тогда все норм будет

Помогло, спасибо

**Comment by Flowseal** [comment]
Используйте новую версию

**Comment by Oklysion** [comment]
cloudflare-ech.com помогло и совместимости thx

**Comment by starayazip** [comment]
> cloudflare-ech.com
> 
> В листы добавьте прост

Хороший способ, помог!

**Comment by w1q17** [comment]
> cloudflare-ech.com
> 
> В листы добавьте прост

спасибо, помогло

**Comment by SlavaGrishin** [comment]
Да мне тоже помогло спасибо!!

**Comment by notritee** [comment]
> Система Windows 11, Version 23H2. Провайдер МТС Новосибирск. При запуске любого из general-батников дискорд запускается, загружаются изображения, отправленные в чат. но аватары, баннеры, эмоджи с серверов не загружаются. Проблема появилась 05.11.2024 в 17:01EEST. Примеры прикреплены ниже. ![Снимок экрана 2024-11-05 221147](https://private-user-images.githubusercontent.com/120936346/383203123-045e9855-522d-48a7-a371-1b7f30902a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzAyODAsIm5iZiI6MTczMDk2OTk4MCwicGF0aCI6Ii8xMjA5MzYzNDYvMzgzMjAzMTIzLTA0NWU5ODU1LTUyMmQtNDhhNy1hMzcxLTFiN2YzMDkwMmE5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwODU5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjM3OTI3NjUwZDlhOTU4MDMyZjM4MmFiOWRiYTBkNjU3ZDRlYzY2NWE2MjgyMjE1NTliOTI0N2ExYmEyYTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IoF-2f0UFmuekpzvm-WzruEvk8rvk_dTefZLdof0UkU) ![Снимок экрана 2024-11-05 221245](https://private-user-images.githubusercontent.com/120936346/383203524-f74dece2-790d-4e53-a315-c41e441a41fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzAyODAsIm5iZiI6MTczMDk2OTk4MCwicGF0aCI6Ii8xMjA5MzYzNDYvMzgzMjAzNTI0LWY3NGRlY2UyLTc5MGQtNGU1My1hMzE1LWM0MWU0NDFhNDFmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwODU5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzg3YzUyYmIwZTA1ZWJlNmM3ZmJjNDUyYTAzNDYxNjBmZDEwNzg4YTFlNDVmNzUxZTExNmM4NjhlM2QxMzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TnlfjKsvzb3jJtZQN8OY8zkVZ6JMgVaZIDlzr_8r2-Y)

Скачай последнюю версию 1.5.2 , мне помогло

**Comment by ereshenkodashka1** [comment]
cloudflare-ech.com

 не помогает
 мегафон/ростелеком

**Comment by RuCybernetic** [comment]
> cloudflare-ech.com
> 
> В листы добавьте прост

Помогло спс

**Comment by KusniChitas** [comment]
> cloudflare-ech.com
> 
> В листы добавьте прост

не работает у меня виндовс 11 я добавил в лист 
не работает

**Comment by myrnavero** [comment]
Удалите сервис, обновитесь до 1.5.2. Мне помогло

**Comment by Yak0vlr** [comment]
> cloudflare-ech.com
> 
> В листы добавьте прост

помогло спс

**Comment by Naaapiie** [comment]
ни обновление до 1.5.2, ни вписание в листы "cloudflare-ech.com" тоже не помогло. частично аватарки вернулись, но всё равно большинство остаются прозрачными, так же с эмоджи, стикерами и всем остальным. кто-то смог найти альтернативное решение?

**Comment by serpen7** [comment]
> ни обновление до 1.5.2, ни вписание в листы "cloudflare-ech.com" тоже не помогло. частично аватарки вернулись, но всё равно большинство остаются прозрачными, так же с эмоджи, стикерами и всем остальным. кто-то смог найти альтернативное решение?

есть теория, что если вы используете ДНС от провайдера это может быть вариантом того что ваши запросы так же фильтруются у провайдера. Это очень легко проверить кстати банально использовать альтернативные днс сервера cloudflare или google. Их легко можно вписать в настройки сетевого адаптера, перезагрузить комп и посмотреть будут ли пропадать аватарки.

**Comment by Karimov-Akbar** [comment]
> cloudflare-ech.com
> 
> В листы добавьте прост

А как это сделать

**Comment by WastoLord06** [comment]
> > Здравствуйте дорогие читатели. Весь день пытался решить данную проблему и наконец то решил. Столкнулся вообще с тем что не запускался Discord из за бесконечной загрузки в окне Starting... .Не грузятся картинки тоже, но зайти в голосовой канал и разговаривать можно. На официальном сайте скачивайте версию DiscordPBT публичную бета версию. Главное чтобы работал zapret, я думал я один такой с проблемой) Переустановил винду и столкнулся, аж в тильт в пал на какое то время)
> > Уральский провайдер Интерсвязь, столкнулся с такой же проблемой.
> 
> ![image](https://github.com/user-attachments/assets/eb9d2eda-d948-4754-8e13-3b6b3dbf6281)

Скачал дискорПБТ, аватары заработали, но эмодзи не хотят,  и аудио пнель
