### ISSUE TITLE
при запуске general.bat он сразу закрывается и не работает

### ISSUE THREAD

**Issue by VALL325** [Flowseal/zapret-discord-youtube#579]
вчера в 23:00 примерно он начал дурить и дискорд перестал работать а призапуске генерала или дискорд бет он сразу закрывается кто поумней подскажите что делать

**Comment by serpen7** [comment]
попробуй это https://github.com/Flowseal/zapret-discord-youtube/issues/558#issuecomment-2454954017

**Comment by VALL325** [comment]
так там такая же хрень я запускаю штуку для дипиай а она моментом закрывается

**Comment by serpen7** [comment]
> так там такая же хрень я запускаю штуку для дипиай а она моментом закрывается

а вы прочитайте внимательно коммент на который я дал ссылку. Потому что у вас винда могла просто заблокать дравер виндайверта с отказом доступа, это способ его очистить и удалить, не запускать батники для обхода, пока он присутствует.

**Comment by VALL325** [comment]
я просто в этом глуп поэтому и не понимаю

**Comment by serpen7** [comment]
> я просто в этом глуп поэтому и не понимаю

там нет магии, нужно только читать и следовать словам.

**Comment by VALL325** [comment]
а можешь мне понятным языком написать а то я не понимаю чайник в общем какие мыши какой сервис запускать я в душе ни чаю

**Comment by VALL325** [comment]
можешь*

**Comment by VALL325** [comment]
> а может мне понятным языком написать а то я не понимаю сервис чайник в общем какие мыши какие стреляю я в душе не чаю



> > я просто в этом глуп, поэтому и не понимаю
> 
> там нет магии, нужно только читать и произносить слова.

а можешь мне понятным языком написать а то я не понимаю чайник в общем какие мыши какой сервис запускать я в душе ни чаю

**Comment by VALL325** [comment]
> > я просто в этом глуп, поэтому и не понимаю
> 
> там нет магии, нужно только читать и произносить слова.

а можешь мне понятным языком написать а то я не понимаю чайник в общем какие мыши какой сервис запускать я в душе ни чаю

**Comment by serpen7** [comment]
> а можешь мне понятным языком написать а то я не понимаю чайник в общем какие мыши какой сервис запускать я в душе ни чаю

мыши?

**Comment by VALL325** [comment]
![image](https://github.com/user-attachments/assets/a408cfe0-5209-43ff-8a03-db6f0849f665)

**Comment by serpen7** [comment]
> ![image](https://private-user-images.githubusercontent.com/187427482/383278351-a408cfe0-5209-43ff-8a03-db6f0849f665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzMyMjgsIm5iZiI6MTczMDgzMjkyOCwicGF0aCI6Ii8xODc0Mjc0ODIvMzgzMjc4MzUxLWE0MDhjZmUwLTUyMDktNDNmZi04YTAzLWRiNmYwODQ5ZjY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxODU1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWU1MDgzNmJmZGJhOTU4OThjOWE3NzhlZjQzNDQzYTQ1MDEwODMzOWYyZGNlYjVlMTcwYzczNWYxZGQwODJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rSQ37Km6DVRt8FTfRHRv4X4gxI5Xm3YfmmWFT9NBQik)

эм чего... 
![image](https://github.com/user-attachments/assets/b48dc9d5-a06d-4ba5-ac66-611b8ce347d5)

**Comment by VALL325** [comment]
о

**Comment by VALL325** [comment]
> > ![image](https://private-user-images.githubusercontent.com/187427482/383278351-a408cfe0-5209-43ff-8a03-db6f0849f665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzMyMjgsIm5iZiI6MTczMDgzMjkyOCwicGF0aCI6Ii8xODc0Mjc0ODIvMzgzMjc4MzUxLWE0MDhjZmUwLTUyMDktNDNmZi04YTAzLWRiNmYwODQ5ZjY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxODU1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWU1MDgzNmJmZGJhOTU4OThjOWE3NzhlZjQzNDQzYTQ1MDEwODMzOWYyZGNlYjVlMTcwYzczNWYxZGQwODJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rSQ37Km6DVRt8FTfRHRv4X4gxI5Xm3YfmmWFT9NBQik)
> 
> эм чего... ![image](https://private-user-images.githubusercontent.com/134365619/383278616-b48dc9d5-a06d-4ba5-ac66-611b8ce347d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzQwOTgsIm5iZiI6MTczMDgzMzc5OCwicGF0aCI6Ii8xMzQzNjU2MTkvMzgzMjc4NjE2LWI0OGRjOWQ1LWEwNmQtNGJhNS1hYzY2LTYxMWI4Y2UzNDdkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxOTA5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTI3YzcyODVlYjhkYjUyNDRhZGQzNzVlNzIzOTc0YzQ1NDc5MWM3ZWRkMmZhODU4ODcyYzY3MDYzNWVkMmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uNc47kYzESh1RAErRwfZZEByJHv0z3Z-CIR9r4IKbHI)

не работает

**Comment by VALL325** [comment]
я посмотрел и лказывается касперский блочит всё это при запуске и наде файлы в исключении не помогают

**Comment by Eptiy** [comment]
> я посмотрел и лказывается касперский блочит всё это при запуске и наде файлы в исключении не помогают

Всю папку с запретом в исключения пробовал добавлять?

**Comment by xbxbcjd** [comment]
> Всю папку с запретом в исключения пробовал добавлять?
такая же проблема и папку добовлял в исключение, все равно выкидывает сразу же

**Comment by FAiN253** [comment]
Недавно у меня была похожая проблема из-за антивируса «Касперский». Использовал его для очистки ПК, и после этого возникли неполадки. 

Чтобы исправить ситуацию, запустил в командной строке с правами администратора команду /scannow. Файлы Windows восстановились, и всё заработало.

**Comment by DimaUniverse22** [comment]
> Недавно у меня была похожая проблема из-за антивируса «Касперский». Я использовал его для очистки ПК, и после этого возникли неполадки.
> 
> Чтобы исправить ситуацию, я запустил в командной строке с правами администратора команду /scannow. Файлы Windows восстановились, и всё заработало.

можешь пожалуйста помочь, а то я не прям монимаю

**Comment by strike1123** [comment]
мало ли пригодится кому  
2 часа сидел с этой проблемой, потом вспомнил что прежде, чем файл открывать, нужно winws.exe запустить, другие способы в инете есть, про этот еще не находил
