### ISSUE TITLE
не работает дс

### ISSUE THREAD

**Issue by Zzeynosso** [Flowseal/zapret-discord-youtube#581]
прога запускается, но в дискорде бесконечная загрузка, помогите пж кто умный
у друзей работает у меня нет(

**Comment by holocost43** [comment]
> прога запускается, но в дискорде бесконечная загрузка, помогите пж кто умный

да такая же херь, ютуб работает а дс нет

**Comment by Tortu62** [comment]
так же

**Comment by Artem285425** [comment]
Всё так же, Ютуб работает,а в дс только серый экран

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
