### ISSUE TITLE
Плохо работает ютуб и дискорд [РОСТЕЛЕКОМ]

### ISSUE THREAD

**Issue by Evgencheg** [Flowseal/zapret-discord-youtube#582]
Картинки грузятся еле еле через минуту, сообщения через пару секунд. Ютуб загружается ещё дольше, первые секунды в районе 1.5-2минут, пробовал все general'ы - всё плохо... Раньше такого не было, типо за секунды грузило. Видел уже много репортов но там нет не решений - ничего, люди просто ждали...

**Comment by Evgencheg** [comment]
Лучший из лучших это general без ALT и другого, чистый general. Грузит 5 секунд все картинки и видосы 15-20 секунд.

**Comment by holocost43** [comment]
> Лучший из лучших это general без ALT и другого, чистый general. Грузит 5 секунд все картинки и видосы 15-20 секунд.

да, тоже использовал именно этот general всё работало, но после перезапуска дс он перестал открываться под любыми батниками. Идёт просто бесконечная загрузка starting

**Comment by Da22nd** [comment]
У меня похожая проблема. Discord и YouTube как-бы открываются и работают, но не полностью. YouTube лагает, а Discord не прогружает изображения и аватарки.

**Comment by Evgencheg** [comment]
У меня хоть и не стартинг бесконечный, меня подгружает в дс но... ТАААААААААААААК долго грузит картинки не на обычном генерале.

**Comment by V3nilla** [comment]
Видимо проблема не только у дискорда с ютубом. На многие сайты перестало пускать, сразу выбивает ошибку ERR_QUIC_PROTOCOL_ERROR, в том числе и к CDN серверу дискорда

**Comment by e2li1386** [comment]
> Видимо проблема не только у дискорда с ютубом. На многие сайты перестало пускать, сразу выбивает ошибку ERR_QUIC_PROTOCOL_ERROR, в том числе и к CDN серверу дискорда

Да. Такое впечатление, что попытались заблокировать что-то одно, а пошло-поехало глобально. Многие сайты просто тупо не открываются, даже которые не в списках. Ссылки с гитхаба даже не открываются, на сторонние ресурсы.
п.с сайт Дискорда работает кстати. И если залогинится через сайт, то пускает в дискорд (web версия именно), но аватарок нет, смайлов нет, чаты все балалайкой...

**Comment by V3nilla** [comment]
> > Видимо проблема не только у дискорда с ютубом. На многие сайты перестало пускать, сразу выбивает ошибку ERR_QUIC_PROTOCOL_ERROR, в том числе и к CDN серверу дискорда
> 
> Да. Такое впечатление, что попытались заблокировать что-то одно, а пошло-поехало глобально. Многие сайты просто тупо не открываются, даже которые не в списках. Ссылки с гитхаба даже не открываются, на сторонние ресурсы. п.с сайт Дискорда работает кстати. И если залогинится через сайт, то пускает в дискорд (web версия именно), но аватарок нет, смайлов нет, чаты все балалайкой...

Проблема найдена - Роскомпозор взялся за ВСЕ сайты с методом шифрования ECH, таким образом отвалилось половина интернета. Чтобы вставить палки в колёса позору, нужно отключить ECH(Encrypted ClientHello) в браузере как мы раньше отключали Kyber и QUIC
Для Edge: `edge://flags`
Для Chrome: `chrome://flags`
Для Opera: `opera:flags`
Для Brave: `brave://flags`

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
https://github.com/Flowseal/zapret-discord-youtube/discussions/251
