### ISSUE TITLE
После открытия servis_install.bat моментально закрывается

### ISSUE THREAD

**Issue by BubaPauka02** [Flowseal/zapret-discord-youtube#583]
Не удаётся запустить батник, после открытия на правах администратора, файл закрывается без возможности выбрать файл для установки в сервисы

**Comment by serpen7** [comment]
Попробуйте это https://github.com/Flowseal/zapret-discord-youtube/issues/558#issuecomment-2454954017 .Потому что у вас винда могла просто заблокать дравер виндайверта с отказом доступа, это способ его очистить и удалить, не запускать батники для обхода, пока он присутствует.

**Comment by BubaPauka02** [comment]
Проблема решилась установкой релиза 1.5.1
main код на весь экран не соответствует коду из релизов, при возможности обновите
![Проблема](https://github.com/user-attachments/assets/85222893-98b9-48a7-a8b5-ad824c9770c3)

**Comment by serpen7** [comment]
@Flowseal где то тут писал что не нужно скачивать с мейна тупо код под правками релиза вроде как вместо того чтобы качать релиз. Это как у гудбайдпи скачать мейн и ничего не получить кроме нестабильного релиза или ничего, который в правках. Я так понимаю он потом когда все это более менее норм в релизы кладет, с мейна разве что что-то отдельное можно разве что качать с правками как в сервис инсталл где просто не хватает одной буквы в дисплей нейме сервиса при установке, что ни на что не влияет по сути.

**Comment by Flowseal** [comment]
В main ветке может быть не CRLF
