### ISSUE TITLE
ужасно работает дискорд, не грузятся аватарки и видео, провайдер info-lan

### ISSUE THREAD

**Issue by DeltaOmegas** [Flowseal/zapret-discord-youtube#584]

**Comment by V3nilla** [comment]
Видимо проблема не только у дискорда с ютубом. На многие сайты перестало пускать, сразу выбивает ошибку ERR_QUIC_PROTOCOL_ERROR, в том числе и к CDN серверу дискорда. Провайдер - Ростелеком МРФ "Волга"

**Comment by OgamLab** [comment]
Такая же проблема, провайдер ДомРу

**Comment by Dronatar** [comment]
Дело в --hostlist то есть в списках, но не понятно почему...

Удалите --hostlist="list-general.txt" после --filter-tcp=443
_(это будет фильтровать всё по порту TCP 443)_ 
Или после --filter-tcp=443 заменить --hostlist="list-general.txt" на --ipset="ipset-discord.txt"
_(будет разблокирован только Discord)_

**Comment by vampirsoft** [comment]
Да нет, судя по всему, ситуация гораздо круче. У меня часа 3 назад рубануло и ютьюб, и дискорд (я сидел под GoodbyeDPI, с которым даже не заметил блокировки дискорда, когда об этом все стали говорить), и пошёл искать варианты, наткнулся на данную утилиту, но как я понимаю, и тут головняк случился. Вероятно РКН всё же нашёл способ обойти обход блокировки. Так что подозреваю, что только впн... ну для ютьюба ещё помогает плагин ЮБуст для хрома, но надолго ли?

**Comment by nikskom** [comment]
> Дело в --hostlist то есть в списках, но не понятно почему...
> 
> Удалите --hostlist="list-general.txt" после --filter-tcp=443 _(это будет фильтровать всё по порту TCP 443)_ Или после --filter-tcp=443 заменить --hostlist="list-general.txt" на --ipset="ipset-discord.txt" _(будет разблокирован только Discord)_

Мне помогла смена метода --dpi-desync на disorder в той же самой строке, провайдер Электронный город (он же Новотелеком)

**Comment by Da22nd** [comment]
> Дело в --hostlist то есть в списках, но не понятно почему...
> 
> Удалите --hostlist="list-general.txt" после --filter-tcp=443 _(это будет фильтровать всё по порту TCP 443)_ Или после --filter-tcp=443 замените --hostlist="list-general.txt" на --ipset="ipset-discord.txt" _(будет разблокирован только Discord)_

И где-же мне это найти в программе?

**Comment by nikskom** [comment]
> > Дело в --hostlist то есть в списках, но не понятно почему...
> > Удалите --hostlist="list-general.txt" после --filter-tcp=443 _(это будет фильтровать всё по порту TCP 443)_ Или после --filter-tcp=443 замените --hostlist="list-general.txt" на --ipset="ipset-discord.txt" _(будет разблокирован только Discord)_
> 
> И где-же мне это найти в программе?

Это в самом батнике надо править

**Comment by Da22nd** [comment]
> > > Дело в --hostlist то есть в списках, но не понятно почему...
> > > Удалите --hostlist="list-general.txt" после --filter-tcp=443 _(это будет фильтровать всё по порту TCP 443)_ Или после --filter-tcp=443 замените --hostlist="list-general.txt" на --ipset="ipset-discord.txt" _(будет разблокирован только Discord)_
> > 
> > 
> > И где-же мне это найти в программе?
> 
> Это в самом батнике надо править

Я тебя вообще не понял. Где это надо копаться

**Comment by nikskom** [comment]
> > > > Дело в --hostlist то есть в списках, но не понятно почему...
> > > > Удалите --hostlist="list-general.txt" после --filter-tcp=443 _(это будет фильтровать всё по порту TCP 443)_ Или после --filter-tcp=443 замените --hostlist="list-general.txt" на --ipset="ipset-discord.txt" _(будет разблокирован только Discord)_
> > > 
> > > 
> > > И где-же мне это найти в программе?
> > 
> > 
> > Это в самом батнике надо править
> 
> Я тебя вообще не понял. Где это надо копаться

![image](https://github.com/user-attachments/assets/37131495-056d-4858-b0a6-29fbd65ba9d8)

**Comment by TesterHere06** [comment]
> > > > Дело в --hostlist то есть в списках, но не понятно почему...
> > > > Удалите --hostlist="list-general.txt" после --filter-tcp=443 _(это будет фильтровать всё по порту TCP 443)_ Или после --filter-tcp=443 замените --hostlist="list-general.txt" на --ipset="ipset-discord.txt" _(будет разблокирован только Discord)_
> > > 
> > > 
> > > И где-же мне это найти в программе?
> > 
> > 
> > Это в самом батнике надо править
> 
> Я тебя вообще не понял. Где это надо копаться

Правой кнопкой мыши по .bat файлу который используешь для себя и выбираешь открыть с помощью. Открываешь с помощью notepad и там изменяешь что сказано

**Comment by TesterHere06** [comment]
Добавил эти линии, но теперь невозможно отправлять какие-либо файлы/изображения

**Comment by Da22nd** [comment]
> > > > > Дело в --hostlist то есть в списках, но не понятно почему...
> > > > > Удалите --hostlist="list-general.txt" после --filter-tcp=443 _(это будет фильтровать всё по порту TCP 443)_ Или после --filter-tcp=443 замените --hostlist="list-general.txt" на --ipset="ipset-discord.txt" _(будет разблокирован только Discord)_
> > > > 
> > > > 
> > > > И где-же мне это найти в программе?
> > > 
> > > 
> > > Это в самом батнике надо править
> > 
> > 
> > Я тебя вообще не понял. Где это надо копаться
> 
> ![image](https://private-user-images.githubusercontent.com/47252756/383340919-37131495-056d-4858-b0a6-29fbd65ba9d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDU2MTAsIm5iZiI6MTczMDg0NTMxMCwicGF0aCI6Ii80NzI1Mjc1Ni8zODMzNDA5MTktMzcxMzE0OTUtMDU2ZC00ODU4LWIwYTYtMjlmYmQ2NWJhOWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDIyMjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YjJlZTliZGE0M2IzMGE3ZDU2NDc4ZTY1MDc5NTRkZDI1YThiOTYwNzhhMGQ5NDE1NmQyMDVhYjMxOGMxYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HgRf6Q29lF0CtDOy0sY4qXcgKS1i3fot0nO4hrRmVZo)

Теперь понял. Спасибо. Попробую хотя-бы Discord полностью оживить.

**Comment by V3nilla** [comment]
> Да нет, судя по всему, ситуация гораздо круче. У меня часа 3 назад рубануло и ютьюб, и дискорд (я сидел под GoodbyeDPI, с которым даже не заметил блокировки дискорда, когда об этом все стали говорить), и пошёл искать варианты, наткнулся на данную утилиту, но как я понимаю, и тут головняк случился. Вероятно РКН всё же нашёл способ обойти обход блокировки. Так что подозреваю, что только впн... ну для ютьюба ещё помогает плагин ЮБуст для хрома, но надолго ли?

Проблема найдена - Роскомпозор взялся за ВСЕ сайты с методом шифрования ECH, таким образом отвалилось половина интернета. Чтобы вставить палки в колёса позору, нужно отключить ECH(Encrypted ClientHello) в браузере как мы раньше отключали Kyber и QUIC
Для Edge: `edge://flags`
Для Chrome: `chrome://flags`
Для Opera: `opera:flags`
Для Brave: `brave://flags`

**Comment by vampirsoft** [comment]
К сожалению, не находит такого флага в хроме (версия 130.0.6723.116)

**Comment by DeltaOmegas** [comment]
А в дискорде как отключить или в других десктопных приложениях?

**Comment by vampirsoft** [comment]
Более того, у меня сейчас гугл полностью отвалился, без впн даже на google.com не пускает

**Comment by starlight332** [comment]
> > Да нет, судя по всему, ситуация гораздо круче. У меня часа 3 назад рубануло и ютьюб, и дискорд (я сидел под GoodbyeDPI, с которым даже не заметил блокировки дискорда, когда об этом все стали говорить), и пошёл искать варианты, наткнулся на данную утилиту, но как я понимаю, и тут головняк случился. Вероятно РКН всё же нашёл способ обойти обход блокировки. Так что подозреваю, что только впн... ну для ютьюба ещё помогает плагин ЮБуст для хрома, но надолго ли?
> 
> Проблема найдена - Роскомпозор взялся за ВСЕ сайты с методом шифрования ECH, таким образом отвалилось половина интернета. Чтобы вставить палки в колёса позору, нужно отключить ECH(Encrypted ClientHello) в браузере как мы раньше отключали Kyber и QUIC Для Edge: `edge://flags` Для Chrome: `chrome://flags` Для Opera: `opera:flags` Для Brave: `brave://flags`

ХВАТИТ ПОСТИТЬ ЭТУ ПАРАШУ!
Уже давно этого флага нет в хроме, его не отключить.

**Comment by johnnyd-78** [comment]
Ничего отключать не надо (ржу вечно с РЕШАЛ с гитхаба ))) ), просто добавьте в list-general.txt (ну или list-discord стратегии один фиг одинаковые) домен **cloudflare-ech.com**
И ntc.party добавьте, чтобы в поисках "решения" фигней по полдня не страдать )

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by kiroffYT** [comment]
> > Дело в --hostlist то есть в списках, но не понятно почему...
> > Удалите --hostlist="list-general.txt" после --filter-tcp=443 _(это будет фильтровать всё по порту TCP 443)_ Или после --filter-tcp=443 заменить --hostlist="list-general.txt" на --ipset="ipset-discord.txt" _(будет разблокирован только Discord)_
> 
> Мне помогла смена метода --dpi-desync на disorder в той же самой строке, провайдер Электронный город (он же Новотелеком)

Очень помог(-ла), спасибо 👍🏻
