### ISSUE TITLE
Не прогружаються аватарки и банера в дискорде

### ISSUE THREAD

**Issue by Risawiska** [Flowseal/zapret-discord-youtube#588]
Столкнулся с такой проблемой можно ее как-то пофиксить?
![Discord_BSYxtCCcEn](https://github.com/user-attachments/assets/25fddea5-231e-469c-a4cb-7fe7bd563123)
![ExILDb1HCj](https://github.com/user-attachments/assets/4e10a6ea-f58e-43a4-8c0d-8bfa2e18264a)
Это произашло буквально на днях.

**Comment by Risawiska** [comment]
Самое интересное, если откатить версию запретки то самой проблемы нету 
Так что люди попробуйте старые версии запретки может и у вас сработает как у меня

**Comment by gameplay330** [comment]
![image](https://github.com/user-attachments/assets/fca1369a-cb6a-4839-be5c-6e290bafb755)
такая же фигня

**Comment by Emopunkkk** [comment]
+

**Comment by 6DIAMOND6** [comment]
не я один такой

ещё следует подметить что видео и аудио файлы не играют а картинки не копируются 
у меня лично такое только с десктоп версией, в браузере всё идеально работает

**Comment by kastentop2005** [comment]
+. У меня всё ок, но у меня плагин на возможность просмотра картинок из профиля, и они там не грузятся

**Comment by hoolygunn** [comment]
Такая же проблема

**Comment by 0ember1** [comment]
Такая же проблема, в браузере тоже не открываются картинки из дса, но я обнаружил что с впном всё работает, что-то случилось именно с запретом

**Comment by nxofumi** [comment]
Помогла обновленная версия 1.5.2

**Comment by keetsta** [comment]
+

**Comment by Ivashka37** [comment]
1.5.2 все работает

**Comment by Risawiska** [comment]
все скачивайте 1.5.2 и все заработает
