### ISSUE TITLE
Не работает 7tv

### ISSUE THREAD

**Issue by emtrAAAA** [Flowseal/zapret-discord-youtube#589]
Не работает 7tv, в меню смайлов не показываются смайлы ни franky ни betterTV ни самого твича, только смайлы винды.

В genreal прописано

- 7tv.app
- 7tv.io
- 7tv.gg
- 10tv.app
- frankerfacez.com
- cdn.betterttv.net
- cdn.frankerfacez.com
- betterttv.com
- betterttv.net
- *.frankerfacez.com

**Comment by chereshnyaj** [comment]
попробуй удалить все кроме 7tv.app, 
![image](https://github.com/user-attachments/assets/88b46914-3fc2-48ad-9772-ecdb8c0f133f)

**Comment by cheeft** [comment]
Обновись на новую версию 1.5.2, либо добавь в general
cloudflare-ech.com

**Comment by indeboss** [comment]
bttv всё равно не отображается в 1.6.0 - для них что-то ещё нужно прописать?
upd: нашёл список [здесь](https://github.com/Flowseal/zapret-discord-youtube/issues/672)

**Comment by ReDxc-derp** [comment]
Привет всем
Ребят, есть кто с провайдером ТТК? 
Ввел все адреса по спискам выше, версию обхода использую последнюю
Ютуб работает превосходно, Дискорд тоже, но вот 7tv работать отказывается
У кого-нибудь есть идеи, что сделал не так?
Ниже прикладываю текущий list-general

[list-general.txt](https://github.com/user-attachments/files/18321712/list-general.txt)

UPD: с туннелем 7tv работает нормально, но часто сбоит сам плеер. Поэтому хотелось бы настроить это через обход

**Comment by stormlightt** [comment]
> Привет всем Ребят, есть кто с провайдером ТТК? Ввел все адреса по спискам выше, версию обхода использую последнюю Ютуб работает превосходно, Дискорд тоже, но вот 7tv работать отказывается У кого-нибудь есть идеи, что сделал не так? Ниже прикладываю текущий list-general
> 
> [list-general.txt](https://github.com/user-attachments/files/18321712/list-general.txt)
> 
> UPD: с туннелем 7tv работает нормально, но часто сбоит сам плеер. Поэтому хотелось бы настроить это через обход

добавь в папку  list-general через блокнот https://www.twitch.tv смайлики появятся
