### ISSUE TITLE
Нет подключения к Интернету

### ISSUE THREAD

**Issue by reklamayota69** [Flowseal/zapret-discord-youtube#59]
При запуске service_discord_youtube.bat появляется доступ к дискорду, однако Ютуб умирает с ошибкой "Нет подключения к Интернету".
![image](https://github.com/user-attachments/assets/0dc4a98a-b788-4ab4-a007-844d2363b670)

С чем может быть связано? Как фиксить?

**Comment by Flowseal** [comment]
- Если используете VPN, отключите функцию TUN (Tunneling) в настройках VPN
- Если используете GoodbyeDPI, то вначале запускаете GoodbyeDPI, а потом уже zapret. Однако советую использовать сервисы. Более подробно на главное странице https://github.com/Flowseal/zapret-discord-youtube

**Comment by reklamayota69** [comment]
Не использую ни ВПН, ни ГудбайДПИ - последний снёс до перезагрузки.

**Comment by Flowseal** [comment]
> Не использую ни ВПН, ни ГудбайДПИ - последний снёс до перезагрузки.

Ну если GoodbyeDPI работал, то через него можете сделать

**Comment by curswqq** [comment]
> > Не использую ни ВПН, ни ГудбайДПИ - последний снёс до перезагрузки.
> 
> Ну если GoodbyeDPI работал, то через него можете сделать

Почините тогда у себя в запрете ютуб, зачем людям жизнь усложнять

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90

**Comment by Kerr42** [comment]
Щя добавил в list-general www.youtube.com и нормально заработал, скорее всего с доменами связанно

**Comment by jekeam** [comment]
У меня в этом случае был включен VPN c Tunneling настроенным на ютуб, спасибо за подсказку
