### ISSUE TITLE
При запуске батника service_discord пишет,что имя сервиса неправильное либо не сущевствует.

### ISSUE THREAD

**Issue by maksonii** [Flowseal/zapret-discord-youtube#591]
Всем добрый день, я вообще н разбираюсь в этом всем деле, просто запустил батник от имени администратора ,а он не работает
general_discord запускал, он открывался но так же ничего не работало,кто нибудь может мне разжевать как и что делать?
вот как выглядит ошибка:
Введите номер файла: 1
Final args:   --wf-tcp 443 --wf-udp 443,50000-50100  --filter-udp 443 --hostlist \"C:\Users\777\Desktop\3232\list-discord.txt\" --dpi-desync fake --dpi-desync-repeats 6 --dpi-desync-fake-quic \"C:\Users\777\Desktop\3232\bin\quic_initial_www_google_com.bin\" --new  --filter-udp 50000-50100 --ipset \"C:\Users\777\Desktop\3232\ipset-discord.txt\" --dpi-desync fake --dpi-desync-any-protocol --dpi-desync-cutoff d3 --dpi-desync-repeats 6 --new  --filter-tcp 443 --hostlist \"C:\Users\777\Desktop\3232\list-discord.txt\" --dpi-desync fake,split --dpi-desync-autottl 2 --dpi-desync-repeats 6 --dpi-desync-fooling badseq --dpi-desync-fake-tls \"C:\Users\777\Desktop\3232\bin\tls_clienthello_www_google_com.bin\"
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 12328
        FLAGS              :
Press any key to continue . . .

**Comment by DieInCalamity** [comment]
win+r нажимаешь, пишешь services.msc, там все где написано VPN и GoodbyeDPI нажимаешь два раза и нажимаешь тип запуска и выбираешь Отключена

**Comment by maksonii** [comment]
> я такого не вижу в службах не впн,не гудбай дипиая

**Comment by Linad-danich** [comment]
maksonii, там не GoodbyeDPI а Zapret, по крайней мере у меня так

**Comment by warstarzer** [comment]
> > я такого не вижу в службах не впн,не гудбай дипиая

Вы запускаете discord.bat, general.bat или service_goodbye_discord.bat? Если последний, то он требует УЖЕ запущенного goodbyeDPI, работая поверх него. Если же нет - проверьте антивирус, отключите если есть, может он блочит и удаляет winws.exe. Ну и база - запуск от имени админа

**Comment by Flowseal** [comment]
У вас нет ошибки, всё запускается
