### ISSUE TITLE
не работает ни ютуб ни дс ни на одной из версий запрета

### ISSUE THREAD

**Issue by qwe1eqwe2** [Flowseal/zapret-discord-youtube#593]
утром столкнулся с траблом в виде не работающего дискорда, хотя на ДРУГОМ ПОЛЬЗОВАТЕЛЕ винды было все окей(да и сейчас тоже работает, но почему то на администраторе нет), сейчас же отвалилось вообще все. Ни ютуб ни дс ничего не работает хелпаните кто нибудь пж

**Comment by memiks333** [comment]
та же самая проблема ни дискорд не работает ни ютуб друг алт батники запустил у него заработало у меня же с этим проблема вчера могли не отправляться сообщения и всё а войсы работали что это предположить не могу даже

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/251
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
