### ISSUE TITLE
Не загружает больше 19 секунд

### ISSUE THREAD

**Issue by NullPointerExeptionBruh** [Flowseal/zapret-discord-youtube#594]
![image](https://github.com/user-attachments/assets/190c38f8-0bbd-4e26-a260-fb63f52fd458)
перестаёт грузится видео на 19 секунде, проблема плавающая но довольно частая, иногда помогает перезагрузка страницы а иногда само чинится

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/251

**Comment by SWAPERMAN** [comment]
Такая же фигня
