### ISSUE TITLE
Дискорд не запускается 

### ISSUE THREAD

**Issue by DenolaFlame** [Flowseal/zapret-discord-youtube#595]
В общем, дс у меня слетел вчера, при его запуске у меня сначала долго грузило окно starting по итогу через несколько минут слава яйцам он запустился и чтобы так не мучиться, я решил начисто удалить дс и потом скачать обратно, не помогло.
По рекомендациям из Интернета нужно было изменить DNS-сервер и очистить папку в appdata. Однако это мне не принесло результата. Теперь я банально не могу войти в аккаунт из-за очень долгой загрузки. Новая версия запрета также не помогла решить долгий стартинг

**Comment by Tofif1** [comment]
Тоже самое, дискорд еле грузит сегодня именно

**Comment by serpen7** [comment]
Скачайте последнюю версию запрета.

**Comment by DenolaFlame** [comment]
> Тоже самое, дискорд еле грузит сегодня именно

Можно скачать конечно дискордПБТ, но придется смириться с серыми иконками

**Comment by NIkNatIon** [comment]
То же самое, буквально вчера все слетело, ни переустановка запрета, ни переустановка диса не помогла, зарегался в нем после переустановки через впн, а дальше все, ток браузерная версия хоть как-то работает

**Comment by Sofutikku** [comment]
то же самое

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
