### ISSUE TITLE
UMOD.ORG

### ISSUE THREAD

**Issue by RustRobin** [Flowseal/zapret-discord-youtube#599]
Не открывает сайт umod.org
![image](https://github.com/user-attachments/assets/1a6e3b17-5e80-498a-bcb6-3a206307d87a)

**Comment by Flowseal** [comment]
Качайте последнюю версию
![image](https://github.com/user-attachments/assets/6dd8da9d-f2f3-4b0a-8dd1-6b26a159cec1)
