### ISSUE TITLE
cod bo6 doesn't work

### ISSUE THREAD

**Issue by solitudematter** [Flowseal/zapret-discord-youtube#605]
game conflicts with a previously launched program and does not start
are there any options to solve the problem?

**Comment by serpen7** [comment]
it's common problem with windivert cause Windows Packet Divert (WinDivert) is a user-mode packet capture-and-divert package. Anticheat does not like it. There is nothing dev can do, it's on game devs side to decide which program their anticheat will accept or not. COD BO known for not loving windivert even in goodbyedpi repository. The only option is to close program or remove service before you want to play that game.
