### ISSUE TITLE
WinDriver.sys анти вирус говорит что это троян

### ISSUE THREAD

**Issue by venysuperr** [Flowseal/zapret-discord-youtube#606]
WinDriver.sys при его запуске программу больше нельзя удалить и анти-вирус говорит что в папке присутствует роян и в названии WinDriver.sys появляется приписка Bitcoin и ссылка

**Comment by serpen7** [comment]
да потому что это по сути дела "троян" из за поведения в системе, перехватывающий пакеты твоего трафика, модифицирующий их в соответствии с твоим конфигом и делающий для тебя работу чтобы задурить ТСПУ. Главное что ты скачал этот "троян" на службе у людей обычных с доверенных репозиториев, а не откуда то из интернета незнамо от кого. Потому что этот "троян" тогда рискует стать реальным вирусом возможно, об этом и предупреждено на главной.

Если хочешь можешь почитать https://reqrypt.org/windivert.html

**Comment by weren9000** [comment]
Есть майнер точно 
![37034063 5_image](https://github.com/user-attachments/assets/73533351-41e4-43c9-9177-129c754b7db9)

**Comment by serpen7** [comment]
> Есть майнер точно ![37034063 5_image](https://private-user-images.githubusercontent.com/54658029/383703287-73533351-41e4-43c9-9177-129c754b7db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjM0MTYsIm5iZiI6MTczMDkyMzExNiwicGF0aCI6Ii81NDY1ODAyOS8zODM3MDMyODctNzM1MzMzNTEtNDFlNC00M2M5LTkxNzctMTI5Yzc1NGI3ZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE5NTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhN2NiZTFiMjlmOGYxZDA1ZDFhYWNmMDNkMTRlMDJjYzU4NjY5ZDFjNzBhYzhlY2U5MzQyYzkzMmY1NzEyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-O8tEj_dkcvf0W6c75TKBKYVNxzPNiYB7-hQEiIJQkc)

то что там в описании зашит кошель для поддержки оригинального разраба фильтра выглядит так себе майнером т.к. ни один чувак создавший реальный майнер не будет зашивать его в описании драйвера как разработчик =/
Такое себе определение майнера если честно.
Ты бы хоть посмотрел прежде чем такое вообще постить 
![image](https://github.com/user-attachments/assets/310c0d5e-7a7d-4738-ba2d-72cef7134c12)

**Comment by Zub35** [comment]
1. WinDivert имеет исходники, любой может скомпилировать, но с подписанием могут возникнуть проблемы.
2. WinDivert с оф.сайта - подписанный аккредитованной организацией драйвер т.е. есть те кто взял на себя ответственность.
