### ISSUE TITLE
7тв не работает

### ISSUE THREAD

**Issue by KSONTAS** [Flowseal/zapret-discord-youtube#608]
Не отображаются смайлы вообще, раньше как сломанные картинки были, теперь просто текст в general вводил
cloudflare-ech.com
7tv.app
7tv.io
7tv.gg
10tv.app
frankerfacez.com
cdn.betterttv.net
cdn.frankerfacez.com
betterttv.com
betterttv.net
*.frankerfacez.com
twitch.tv
не работает, мб есть способ?

**Comment by Vovchiques** [comment]
+

**Comment by Flowseal** [comment]
обновитесь и не используйте бесполезные домены
