### ISSUE TITLE
гайс хелп не работает дс 

### ISSUE THREAD

**Issue by SKEBEDEKIRILL** [Flowseal/zapret-discord-youtube#61]
Скачал 
Сделал все как надо
Но звонки не работают
Бесконечное подключение 
надеюсь на ответ

**Comment by SKEBEDEKIRILL** [comment]
в зв не заходит

**Comment by Leon74RA** [comment]
ты открыл service_discord.bat от имени администратора? мне помогло

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
