### ISSUE TITLE
у меня вот такая вот шняга вылазит к сожалению...не понимаю как что и почему

### ISSUE THREAD

**Issue by Miamipolice1** [Flowseal/zapret-discord-youtube#610]
![Снимок экрана 2024-11-07 003409](https://github.com/user-attachments/assets/87666b87-add2-4887-b1d5-c6627a10179e)

**Comment by serpen7** [comment]
это и есть работающий фильтр.

**Comment by Miamipolice1** [comment]
мне кент говорил что у него такой штуки не было когда он открывал файл
мдээ

**Comment by Miamipolice1** [comment]
Да и Дискорд продолжает не работать даже если сам фильтр

**Comment by serpen7** [comment]
> мне кент говорил что у него такой штуки не было когда он открывал файл мдээ

он по видимому запускал тупо сервис что есть большая ошибка потому что сначала нужно на батниках стратегий что у вас вообще работает в вашем случае, потому что каждый случай индивидуален, а некоторые требуют вообще доработки конфига.

**Comment by Miamipolice1** [comment]
Понял принял, благодарю
