### ISSUE TITLE
Не работает при раздаче с мобильного

### ISSUE THREAD

**Issue by catnep228** [Flowseal/zapret-discord-youtube#613]
Столкнулся с такой ситуацией, что при раздаче с мобильного интернета со смартфона программа перестаёт работать (но запускается)

**Comment by ereshenkodashka1** [comment]
cloudflare-ech.com

не помогает, мегафон

**Comment by Eptiy** [comment]
> Столкнулся с такой ситуацией, что при раздаче с мобильного интернета со смартфона программа перестаёт работать (но запускается)

На мобильном операторе и на провайдере почти наверняка разные ТСПУ. Это значит, что нужны другие конфиги.

Данный билд предназначен в первую очередь для использования на провайдере, поэтому подходящий под мобильного оператора конфиг нужно подбирать вручную через блокчек.

**Comment by Eptiy** [comment]
> cloudflare-ech.com
> 
> не помогает, мегафон

Он вообще работал у тебя? ECH пока не везде возможен. У меня, например, никак не заводится.

**Comment by catnep228** [comment]
> > Столкнулся с такой ситуацией, что при раздаче с мобильного интернета со смартфона программа перестаёт работать (но запускается)
> 
> На мобильном операторе и на провайдере почти наверняка разные ТСПУ. Это значит, что нужны другие конфиги.
> 
> Данный билд предназначен в первую очередь для использования на провайдере, поэтому подходящий под мобильного оператора конфиг нужно подбирать вручную через блокчек.

спасибо! всё заработало

**Comment by Eptiy** [comment]
> спасибо! всё заработало

Можешь поделиться тут решением, может, у кого-то ещё есть подобные проблемы.
