### ISSUE TITLE
Не подключается через AnyDesk

### ISSUE THREAD

**Issue by warstarzer** [Flowseal/zapret-discord-youtube#615]
Что нужно прописывать в .txt (адреса серверов или чего там), чтобы начал работать AnyDesk? Он в сети, по при попытке подключения -  "Превышено время оиждания". Ладно дома, через VPN - OK, но не буду же я на работе всем доступ к своей VPS давать, итак ни у одног провайдера нормальной скорости нет

**Comment by serpen7** [comment]
Добавь в лист txt general если ты запускаешь general батник или его конфигу
`*.net.anydesk.com`

**Comment by testidcode** [comment]
Все равно не работает. Как и половина сайтов AD

**Comment by warstarzer** [comment]
Проблема решена, по крайней мере ясно куда копать. Методом перебора комбинаций подключения выясняется, что причина конкретно в моем рабочем компе, т.к. не подключается только к нему, с остальными все ок. Потом надо будет переустановить с нуля прогу. Всем откликнувшимся спасибо, не сейчас, так чую нутром потом понадобится ваши методы решения...

**Comment by Eptiy** [comment]
У меня сайт anydesk.com работает и с обходом, и без обхода. Ты уверен, что он вообще заблокирован? Скорее всего у тебя какие-то проблемы с ним, и они не связаны с запретом.

**Comment by Flowseal** [comment]
![image](https://github.com/user-attachments/assets/e46712d3-6ce3-488e-b62a-2fdb9d28f973)
80 и 443 TCP работают по хостлисту, anydesk в котором не значится.
UDP 50001-50003 работают по ipset'у, и айпи 239.* там не записан.

Убедитесь, что используете последнюю версию. У меня AnyDesk отлично работает.
Можете попробовать советы, описанные здесь - https://support.anydesk.com/knowledge/firewall
