### ISSUE TITLE
Не грузятся видео, большинство аватарок серверов, стикеры и аватарки пользователей.

### ISSUE THREAD

**Issue by sdarva** [Flowseal/zapret-discord-youtube#616]
Примерно с позавчерашнего дня в дискорде просто пропали все аватарки у серверов, видео которые я кидал с компа я не мог посмотреть на нём, с телефона с впн всё стабильно. Провайдер-Дом ру

**Comment by sdarva** [comment]
глянул другие проблемы, у меня нет адблоков и подобного так как до этого не было такой проблемы.

**Comment by sdarva** [comment]
о появилась так же проблема с загрузкой фото. Качество шакальное, и чтобы оно было хорошим нужно по минут 5 сидеть и ждать.

**Comment by Fryxet** [comment]
Версию обновил до 1.5.2? Роскомнадзор блокнул cloudflare из-за новой технологии

**Comment by sdarva** [comment]
о да теперь работает
