### ISSUE TITLE
эмоции bttv не отображаются

### ISSUE THREAD

**Issue by CongoBB** [Flowseal/zapret-discord-youtube#617]

**Comment by serpen7** [comment]
потому что в листе general нет.
```
frankerfacez.com
cdn.frankerfacez.com
betterttv.com
cdn.betterttv.net
```
 Их как бы блокнули. А если нет в листах то и обхода нет.

**Comment by DanzoGit** [comment]
> потому что в листе general нет.
> 
> ```
> frankerfacez.com
> cdn.frankerfacez.com
> betterttv.com
> cdn.betterttv.net
> ```
> 
> Их как бы блокнули. А если нет в листах то и обхода нет.

`--hostlist=<filename>				; действовать только над доменами, входящими в список из filename. поддомены автоматически учитываются.`

Выдержка из оригинального репозитория.
Достаточно добавлять основной домен, поддомены и маски ни к чему.

**Comment by CongoBB** [comment]
в том-то и дело что есть у меня

**Comment by DanzoGit** [comment]
> в том-то и дело что есть у меня

Скиньте батник, который используете. И список хостов.

**Comment by CongoBB** [comment]
тьфу, мисскликнул
[general.zip](https://github.com/user-attachments/files/17667080/general.zip)

**Comment by DanzoGit** [comment]
> тьфу, мисскликнул [general.zip](https://github.com/user-attachments/files/17667080/general.zip)

[zapret-all.zip](https://github.com/user-attachments/files/17667115/zapret-all.zip)
попробуйте такой батник.
еще вместо
```
cdn.betterttv.net
cdn.frankerfacez.com
```
можете сделать просто
```
betterttv.net
frankerfacez.com
```
заодно скинул список моих хостов, которые брал с gdpi

**Comment by CongoBB** [comment]
попробовал, кажется все видно теперь, спасибо огромное!

**Comment by CongoBB** [comment]
использую оба файла (для справки)
