### ISSUE TITLE
не грузит звонки

### ISSUE THREAD

**Issue by LPD-xuy** [Flowseal/zapret-discord-youtube#62]
всё скачал, запускаю от имени администратора, ДС открывается, грузит чаты и даже отправляет соо, но при попытке созвониться идёт подключение
![изображение_2024-10-09_190012086](https://github.com/user-attachments/assets/c6535ce1-1089-4af6-bd19-5f0b8dba545c)

**Comment by Leon74RA** [comment]
ты открыл service_discord.bat от имени администратора?

**Comment by del2H** [comment]
> ты открыл service_discord.bat от имени администратора?

У меня такая же проблема, и да я запускал от имени администратора. (Провайдер МТС)

**Comment by ApokGG** [comment]
у меня вроде работает голос, подключение к голосовому чату долго идет (секунд 10-15)

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
