### ISSUE TITLE
Страйк за видео на ютубе.

### ISSUE THREAD

**Issue by GoSamOfficial** [Flowseal/zapret-discord-youtube#623]
Добрый день. Я на почту вам написал но ответа не дождался. Честно говоря не могу поверить что страйк сделан вами добровольно. Может ркн до вас добрался и попросил все видео обозревающие программу удалить. Но будучи владельцем канала не могу не попробовать попросить отозвать страйк

**Comment by serpen7** [comment]
А скриншот страйка можно там же написано от кого он, может ты ошибся чем?)
Нафига автору запрета кидать страйк на какое то видео обозревающее его программу и то как ей пользоваться?

**Comment by GoSamOfficial** [comment]
> А скриншот страйка можно там же написано от кого он, может ты ошибся чем?) Нафига автору запрета кидать страйк на какое то видео обозревающее его программу и то как ей пользоваться?

страйк от [zepretgit@gmail.com]

**Comment by serpen7** [comment]
> > А скриншот страйка можно там же написано от кого он, может ты ошибся чем?) Нафига автору запрета кидать страйк на какое то видео обозревающее его программу и то как ей пользоваться?
> 
> страйк от [[zepretgit@gmail.com](mailto:zepretgit@gmail.com)]

Тебя явно пытаются заблочить фолс страйками или увести канал. Там должны быть точные данные компании или человека которые подают страйк и источника который этот человек представляет.

**Comment by GoSamOfficial** [comment]
> > > А скриншот страйка можно там же написано от кого он, может ты ошибся чем?) Нафига автору запрета кидать страйк на какое то видео обозревающее его программу и то как ей пользоваться?
> > 
> > 
> > страйк от [[zepretgit@gmail.com](mailto:zepretgit@gmail.com)]
> 
> Тебя явно пытаются заблочить фолс страйками или увести канал. Там должны быть точные данные компании или человека которые подают страйк и источника который этот человек представляет.

Здравствуйте, Go SAM!

Мы получили запрос на удаление видео в связи с нарушением авторских прав. Согласно применимому закону о защите авторских прав, с YouTube удалено следующее видео:

Название видео: САМЫЙ ЛУЧШИХ ФИКС ДИСКОРДА И ЮТУБА ЗА 1 МИНУТУ. Без Пинга, Без ВПН, Автозапуск
URL видео: https://www.youtube.com/watch?v=T8P9ViKMFE4
Использованный контент: zapret
Временные метки: 0:00:31 – 0:00:34
Отправитель запроса на удаление: zapret
Контактная информация: zepretgit@gmail.com

Ваше видео теперь недоступно для просмотра на YouTube.

Вам вынесено предупреждение
 
У вас 1 предупреждение о нарушении авторских прав. Если вы получите ещё два, мы заблокируем ваш канал. Чтобы избежать этого, не загружайте видео с контентом, на использование которого у вас нет прав.

**Comment by GoSamOfficial** [comment]
Я поэтому сюда и написал что бы разобраться в ситуации. Само видео я удалил с ютуба, но его копия у меня осталась.

**Comment by serpen7** [comment]
Тебе самому не смешно что там отправитель на удаление видео написан zapret, а не автор программы? Тебя программа страйкнула?)
Тебе кто то хочет снести канал.

**Comment by GoSamOfficial** [comment]
> Тебе самому не смешно что там отправитель на удаление видео написан zapret, а не автор программы? Тебя программа страйкнула?) Тебе кто то хочет снести канал.

Если мне разработчики ответят, может быть мы сможем эту ситуацию решить

**Comment by GoSamOfficial** [comment]
В любом случае ютуб же проверяет все жалобы, и это жалоба каким то образом прошла. Если это не автор программы кинул страйк, то можно апелляцию подать

**Comment by serpen7** [comment]
> zapret

тогда пиши и разработчику оригинального запрета тоже, а с их ответами и ссылками на них тогда уж обжалуй страйк.

**Comment by GoSamOfficial** [comment]
> Добрый день. Я на почту вам написал но ответа не дождался. Честно говоря не могу поверить что страйк сделан вами добровольно. Может ркн до вас добрался и попросил все видео обозревающие программу удалить. Но будучи владельцем канала не могу не попробовать попросить отозвать страйк

я написал на почту указанную в страйке. Ну и сейчас в этом же разделе на ориг. запрете написал тот же пост

**Comment by serpen7** [comment]
> В любом случае ютуб же проверяет все жалобы, и это жалоба каким то образом прошла. Если это не автор программы кинул страйк, то можно апелляцию подать

ютуб нифига не проверяет, там автомат, поэтому флагать фолс страйками можно любой канал, за фолс страйки лишь снесут канал и учетку тому кто их подавал как разберутся. Он уже проверяет только после обжалования и то не всегда. ТЫ наверное не слышал о троллях с фейк страйками, которые подавали их даже на официальные каналы ютуба компаний якобы что это их контент)))

**Comment by GoSamOfficial** [comment]
> > В любом случае ютуб же проверяет все жалобы, и это жалоба каким то образом прошла. Если это не автор программы кинул страйк, то можно апелляцию подать
> 
> ютуб нифига не проверяет, там автомат, поэтому флагать фолс страйками можно любой канал, за фолс страйки лишь снесут канал и учетку тому кто их подавал. Он уже проверяет только после обжалования и то не всегда. ТЫ наверное не слышал о троллях с фейк страйками, которые подавали их даже на официальные каналы ютуба компаний якобы что это их контент)))

ну у меня опять же тяжёлая ситуация. Без разрешения реального создателя запрета у меня руки связаны

**Comment by GoSamOfficial** [comment]
> > В любом случае ютуб же проверяет все жалобы, и это жалоба каким то образом прошла. Если это не автор программы кинул страйк, то можно апелляцию подать
> 
> ютуб нифига не проверяет, там автомат, поэтому флагать фолс страйками можно любой канал, за фолс страйки лишь снесут канал и учетку тому кто их подавал как разберутся. Он уже проверяет только после обжалования и то не всегда. ТЫ наверное не слышал о троллях с фейк страйками, которые подавали их даже на официальные каналы ютуба компаний якобы что это их контент)))

А ещё что бы обжаловать страйк нужно свои личные данные писать, может ркн так хотят выведать кто я такой. Но попытки четные ибо я гражданин совсем другой страны

**Comment by serpen7** [comment]
> > > В любом случае ютуб же проверяет все жалобы, и это жалоба каким то образом прошла. Если это не автор программы кинул страйк, то можно апелляцию подать
> > 
> > 
> > ютуб нифига не проверяет, там автомат, поэтому флагать фолс страйками можно любой канал, за фолс страйки лишь снесут канал и учетку тому кто их подавал как разберутся. Он уже проверяет только после обжалования и то не всегда. ТЫ наверное не слышал о троллях с фейк страйками, которые подавали их даже на официальные каналы ютуба компаний якобы что это их контент)))
> 
> А ещё что бы обжаловать страйк нужно свои личные данные писать, может ркн так хотят выведать кто я такой. Но попытки четные ибо я гражданин совсем другой страны

может, это было бы логично немножко, потому что есть закончик на эту тему которым занимается ркн. Но чето сомнительно, скорее всего либо тебя троллят, либо кому то ты мешаешь на ютубе.

**Comment by GoSamOfficial** [comment]
> > > > В любом случае ютуб же проверяет все жалобы, и это жалоба каким то образом прошла. Если это не автор программы кинул страйк, то можно апелляцию подать
> > > 
> > > 
> > > ютуб нифига не проверяет, там автомат, поэтому флагать фолс страйками можно любой канал, за фолс страйки лишь снесут канал и учетку тому кто их подавал как разберутся. Он уже проверяет только после обжалования и то не всегда. ТЫ наверное не слышал о троллях с фейк страйками, которые подавали их даже на официальные каналы ютуба компаний якобы что это их контент)))
> > 
> > 
> > А ещё что бы обжаловать страйк нужно свои личные данные писать, может ркн так хотят выведать кто я такой. Но попытки четные ибо я гражданин совсем другой страны
> 
> может, это было бы логично немножко, потому что есть закончик на эту тему которым занимается ркн. Но чето сомнительно, скорее всего либо тебя троллят, либо кому то ты мешаешь на ютубе.

мне просто за неделю до этого приходило уведомление что ркн добавляет моё видео в реестр запрещённых. Вот я и думаю что у них это не сработало и они решили такими методами загасить видео

**Comment by serpen7** [comment]
> мне просто за неделю до этого приходило уведомление что ркн добавляет моё видео в реестр запрещённых. Вот я и думаю что у них это не сработало и они решили такими методами загасить видео

ну это немного отвечает на вопрос почему там подавали страйк не от авторов программы, а якобы от самой программы zapret, чтобы потом не иметь юридический последствий от присвоения себе чужой личности)

**Comment by GoSamOfficial** [comment]
> > мне просто за неделю до этого приходило уведомление что ркн добавляет моё видео в реестр запрещённых. Вот я и думаю что у них это не сработало и они решили такими методами загасить видео
> 
> ну это немного отвечает на вопрос почему там подавали страйк не от авторов программы, а якобы от самой программы zapret, чтобы потом не иметь юридический последствий от присвоения себе чужой личности)

если получится с автором связаться, может он поможет разобраться. И с другой стороны мне канал дороже всяких дискордов, таким больше не буду заниматься. 3 месяца страйк пройдёт, жизнь продолжается.

**Comment by serpen7** [comment]
> если получится с автором связаться, может он поможет разобраться. И с другой стороны мне канал дороже всяких дискордов, таким больше не буду заниматься. 3 месяца страйк пройдёт, жизнь продолжается.

Авторы тебе вряд ли чем помогут т.к. они же не зарегеные компании, это разработчики свободного ПО. Разве что могут сказать что это не они и ты можешь ссылаться на это в обжаловании. Проблема фейковых страйков она да, фиговая, это скажем дно ютуба которое он не хочет разгребать ибо там существуют реальные проблемы и это уже даже было показано глобально с несколькими оффициальными компаниями такими как банджи. Но слава богу за троллем тем банджи через полтора года помоему тяжб судебных решили не оставлять как есть, а пойти дальше и наказать его уже через официальную систему т.к. получили данные его, парень влетел вроде там на 300к баксов или чето такое.

**Comment by serpen7** [comment]
Кстати если это не ты то ты не один такой
https://ntc.party/t/youtube-strike/12793

**Comment by GoSamOfficial** [comment]
> Кстати если это не ты то ты не один такой https://ntc.party/t/youtube-strike/12793

нет это не я. Теория с тем что разработчики вирусов пытаются удалить нормальные видео тоже интересная

**Comment by skallekss** [comment]
Мне тоже снесли видео, и тоже от zapret)

**Comment by GoSamOfficial** [comment]
> Мне тоже снесли видео, и тоже от zapret)

мне bol-van ответил сказал что ничего не делал

**Comment by skallekss** [comment]
> > Мне тоже снесли видео, и тоже от zapret)
> 
> мне bol-van ответил сказал что ничего не делал
 
а как его снимать теперь собственно, гугл только послать может

**Comment by GoSamOfficial** [comment]
> > > Мне тоже снесли видео, и тоже от zapret)
> > 
> > 
> > мне bol-van ответил сказал что ничего не делал
> 
> а как его снимать теперь собственно, гугл только послать может

я сейчас пытаюсь списаться с создателем проги, с его разрешения можно отозвать так то жалобу. Но на самом деле не хочется тролям раскрывать свои данные тоже

**Comment by Flowseal** [comment]
И Финарготу, и Вам, страйк я не кидал. И явно это не bol-van, заняться ему нечем. Поддерживаю идею про страйки от распространителей вирусов.

**Comment by GoSamOfficial** [comment]
> И Финарготу, и Вам, страйк я не кидал. И явно это не bol-van, заняться ему нечем. Поддерживаю идею про страйки от распространителей вирусов.

Да, мне он тоже сказал что ничего не кидал. Мошенники какие то видимо
