### ISSUE TITLE
Не удаётся подключиться к RTC в Дискорде

### ISSUE THREAD

**Issue by stalker1iodine** [Flowseal/zapret-discord-youtube#624]
Сегодня внезапно столкнулся с проблемой, что не удаётся подключиться к голосовым в Дискорде. Ну вернее как, смотреть демонстрацию экрана я могу, но я не могу говорить в голосовой чат и не могу слышать, что говорят другие. Постоянно пишет, что пытается подключиться к RTC, но в итоге не может установить маршрут и пытается подключиться заново. И так до бесконечности.
Некоторые говорили, что это может мешать AdGuard, но я не знаю, что это и где оно располагается на пк, так как поиск приложений, установленных на пк, не даёт никаких результатов.

**Comment by Flowseal** [comment]
Читайте README.
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
