### ISSUE TITLE
Добавление дополнительных адресов заблокированных сайтов

### ISSUE THREAD

**Issue by Botan626** [Flowseal/zapret-discord-youtube#628]
> После добавления сервис нужно перезапустить.

Как? Дополните справку.

**Comment by MokuHub** [comment]
Перезагрузи компьютер

**Comment by Botan626** [comment]
> Перезагрузи компьютер

А другие способы есть?

**Comment by MokuHub** [comment]
Можешь окошко с запретом закрыть и запустить заново

**Comment by Botan626** [comment]
> Можешь окошко с запретом закрыть и запустить заново

У меня сервис создан с помощью `service_install.bat`.

Помимо перезагрузки компьютера ещё как-нибудь можно перезапустить сервис?

**Comment by MokuHub** [comment]
В службах виндоус находишь zapret и там есть возможность его перезагрузить, а вообще не проще снести сервис позапускать в ручную настроить 100500 сайтов и потом установить сервис еще раз

**Comment by Botan626** [comment]
> позапускать в ручную настроить 100500 сайтов

А как настраивать? 
Чтобы попробовать я добавил в `list-general.txt` `instagram.com`, сделал рестарт запрета в сервисах, а сайт всё равно не открывается.

**Comment by Flowseal** [comment]
service_remove
заново service_install

**Comment by Botan626** [comment]
> service_remove заново service_install

Почему закрыл? Как настраивать? Не написано ведь.
