### ISSUE TITLE
service_install незапускается

### ISSUE THREAD

**Issue by raru1040** [Flowseal/zapret-discord-youtube#630]
хз в чем проблема просто не открывает и всё. Прошлые версии работали на ноутбуке а на компе нет. на пк general запускается а
service_install нет, антивирусов и всякого такого нету. можете помочь

**Comment by Flowseal** [comment]
Качайте с релизов: https://github.com/Flowseal/zapret-discord-youtube/releases/download/1.5.2/zapret-discord-youtube-1.5.2.rar

Если не помогает, то скачайте Notepad++, откройте им service_install и снизу справа поменяйте с LF на CRLF
