### ISSUE TITLE
Добавление дополнительных адресов заблокированных сайтов

### ISSUE THREAD

**Issue by Botan626** [Flowseal/zapret-discord-youtube#631]
Я добавил в `list-general.txt` `instagram.com`, сделал рестарт запрет сервиса, а сайт всё равно не открывается.

Он должен открываться после этого? Что и как надо настраивать?

**Comment by serpen7** [comment]
зачем ты ставишь сразу сервис не попробовав батники стратегий general чтобы знать какой ставить как сервис? Их там еще 7.

**Comment by Botan626** [comment]
> зачем ты ставишь сразу сервис не попробовав батники стратегий general чтобы знать какой ставить как сервис? Их там еще 7.

попробую

**Comment by serpen7** [comment]
> > зачем ты ставишь сразу сервис не попробовав батники стратегий general чтобы знать какой ставить как сервис? Их там еще 7.
> 
> попробую

сервис сначала только удали запустив сервис ремувом от имени администратора правой кнопочкой.

**Comment by Botan626** [comment]
> сервис сначала только удали запустив сервис ремувом от имени администратора правой кнопочкой.


это я знаю

а вообще если сам добавляешь адрес в лист что-то ещё настраивать надо?

**Comment by serpen7** [comment]
> > сервис сначала только удали запустив сервис ремувом от имени администратора правой кнопочкой.
> 
> это я знаю
> 
> а вообще если сам добавляешь адрес в лист что-то ещё настраивать надо?

по идее нет, нужно лишь будет удалять и устанавливать заново сервис, ну или перезагружать комп т.к. это перезапускает тоже сервис. Т.к. прога подхватывает листы при запуске же только. Ну и не перемещать папочку запрета иначе сервис будет не находить файлы нужные. Поэтому ее лучше разместить сначала там где захочешь чтобы она была.

**Comment by Botan626** [comment]
> > > сервис сначала только удали запустив сервис ремувом от имени администратора правой кнопочкой.
> > 
> > 
> > это я знаю
> > а вообще если сам добавляешь адрес в лист что-то ещё настраивать надо?
> 
> по идее нет, нужно лишь будет удалять и устанавливать заново сервис, ну или перезагружать комп т.к. это перезапускает тоже сервис. Т.к. прога подхватывает листы при запуске же только. Ну и не перемещать папочку запрета иначе сервис будет не находить файлы нужные. Поэтому ее лучше разместить там где захочешь сначала чтобы она была.

ясно спасибо
