### ISSUE TITLE
Вирусы?

### ISSUE THREAD

**Issue by nerpyatski** [Flowseal/zapret-discord-youtube#633]
VirusTotal нашёл троян в архиве.
Это точно безопасно? Я что-то побаиваюсь качать.
![изображение_2024-11-08_200737189](https://github.com/user-attachments/assets/8b41d0c2-ae0d-4308-815e-170ee977d6af)

**Comment by serpen7** [comment]
Да господи когда вы уже фигней то прекратите страдать если не можете нормально понимать что выдает вирустотал с эвристиками и антивирусами. И сочетать это с тем чем является и запрет и гудбайдпи. Естественно на них будут реагировать эвристики особенно в запакованном виде.
https://github.com/Flowseal/zapret-discord-youtube/issues/551
https://github.com/Flowseal/zapret-discord-youtube/issues/445
https://github.com/Flowseal/zapret-discord-youtube/issues/474
