### ISSUE TITLE
Видео на ютубе иногда выдают ошибку при загрузке. Помогает перезагрузка страницы, но всё равно раздражает.

### ISSUE THREAD

**Issue by ivanevkan** [Flowseal/zapret-discord-youtube#635]
![изображение](https://github.com/user-attachments/assets/f6e05280-c0e3-4ea5-be7b-654af05e9875)

использую файл general

**Comment by ivanevkan** [comment]
Проблема наблюдается уже примерно три дня
Полагаю это может быть связано с выходом новой версии, так как примерно одновременно с этим стали пропадать аватарки в дисике

**Comment by serpen7** [comment]
это не связано с выходом новой серии вам ютуб буквально говорит что по какой то причине он не может воспроизвести видео, видимо не может добится в хранилище для воспроизведения или какая то другая ошибка. Пропажа ав в  дискорде с этим не связана вообще. Это значит что у вас либо что то вмешивается в работу сети и программы из-за чего возникает конфликт, либо тактика блокировки сменилась и шейпит ваш трафик распознавая его.

**Comment by Flowseal** [comment]
Адблок выключите
