### ISSUE TITLE
Не запускается версия 1.5.2

### ISSUE THREAD

**Issue by Icecreamed** [Flowseal/zapret-discord-youtube#637]
Новый запрет даже не запускается(1.5.2), сижу на версии 1.5.1 и не грузится большинство аватарок в Дискорде, а также очень долго запускаются видео. В ютубе очень долго грузят видео

**Comment by serpen7** [comment]
ты же качаешь с релизов первый файл надеюсь, а не соурс код или с самого репозитория?

**Comment by Icecreamed** [comment]
Да, именно саму зипку с батниками

**Comment by serpen7** [comment]
> Да, именно саму зипку с батниками

там релиз в рарке
![image](https://github.com/user-attachments/assets/285e48a2-45a5-48e2-a708-01f38c09d823)

**Comment by Icecreamed** [comment]
что ты именно имел ввиду

**Comment by serpen7** [comment]
> ты же качаешь с релизов первый файл надеюсь, а не соурс код или с самого репозитория?

> Да, именно саму зипку с батниками

> там релиз в рарке ![image](https://private-user-images.githubusercontent.com/134365619/384593064-285e48a2-45a5-48e2-a708-01f38c09d823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDQ5MTksIm5iZiI6MTczMTE0NDYxOSwicGF0aCI6Ii8xMzQzNjU2MTkvMzg0NTkzMDY0LTI4NWU0OGEyLTQ1YTUtNDhlMi1hNzA4LTAxZjM4YzA5ZDgyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwOTMwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjhjZDNlYTRiN2RjYTRhNTlkOWQ3YmY3Y2Q2ODUxNDliMjcyMGZkZjQ2ZjJmNDMxZWJhM2IwY2MyZTBjNDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DspVbR3uEKWnJ27aJauVO0QKtwGbfN_JsfjfBwd-pdY)

**Comment by Icecreamed** [comment]
которая первая же именно?

**Comment by serpen7** [comment]
> которая первая же именно?

да

**Comment by Icecreamed** [comment]
и что делать?

**Comment by serpen7** [comment]
скачиваешь, распаковываешь в папку, запускаешь сервис ремув бат от имени админа и пробуешь батники, если какой то из них работал то можешь запускать его сразу.  Закрываешь, открываешь браузер\дискорд, смотришь. Ставишь как сервис по желанию батник свой через сервис инсталл от имени администратора, если захочешь так сделать.

**Comment by Icecreamed** [comment]
щас попробую

**Comment by serpen7** [comment]
Но перед тем как ставить сервис, если будешь, положи папочку туда куда тебе нужно т.к. ее потом перемещать будет нельзя.

**Comment by Icecreamed** [comment]
божечки мой спасибо сработало
