### ISSUE TITLE
Не работает дискорд . 

### ISSUE THREAD

**Issue by UpdSnejinKA** [Flowseal/zapret-discord-youtube#639]
В прошлых версиях все работало, запустил 1 раз обход и все время работал. В новой версии (Ласт апдейт), консоль закрывается и выдаёт такую ошибку (скрин) Если эту консоль не закрывать, дискорд будет работать, при закрытие - наработает. 
![Screenshot 2024-11-09 180713](https://github.com/user-attachments/assets/0b900800-8394-452f-b31f-07d99cc2ba7a)

**Comment by serpen7** [comment]
ну так правильно это и есть фильтр работающий запускаемый с батников и он работает пока открыт.
![image](https://github.com/user-attachments/assets/c7ccbe0d-ef56-4de6-adef-b9c71fdba28a)

Или вам что то другое надо?

**Comment by Maximilian-Leonhard** [comment]
У меня вообще почему-то не работает дискорд. Ютуб при этом работает чудесно, но конкретно дискорд вообще ни в какую.
![222](https://github.com/user-attachments/assets/2508f34b-cadb-4285-8928-04fcf09adc2b)
![111](https://github.com/user-attachments/assets/fcc54886-33a5-4bf5-a8c1-a0d1f34778ea)

**Comment by UpdSnejinKA** [comment]
@serpen7 Интересно, почему в пред.версии не нужно было сидеть с открытой консолью, что бы сидеть в дс? Такой "Фильтр" вылезает при открытии любого обходного батника.

**Comment by serpen7** [comment]
> @serpen7 Интересно, почему в пред.версии не нужно было сидеть с открытой консолью, что бы сидеть в дс? Такой "Фильтр" вылезает при открытии любого обходного батника.

Наверное потому что нужно было сидеть с открытой консолью если вы запускаете программу через батники, а не ставите как сервис. Я вам больше скажу в релизах репозитория есть куча старых версий и они работают точно так же через батники. Я же пользую  ее так же как и вы еще с 1.1 версии постоянно, не службой, а батниками, потому что мне так проще. И у меня на всех версиях была всегда такая консоль после запуска батника. Думаете я вру, ну скачайте старую версию из репозитория, релизов, убедитесь сами.

**Comment by serpen7** [comment]
Хотите ставьте как службу ваш батник через сервис инсталл  от имени администратора и консоли не будет, она будет скрытой работать через службу и запускаться автоматически при запуске системы. Но перед этим закройте программу и запустите service remove батник от имени администратора, чтобы у вас не было конфликта в создании сервиса.
