### ISSUE TITLE
При запуске VPN который работает чисто на конкретную игру - перестаёт подключать к каналам, стримам и прочие функции.

### ISSUE THREAD

**Issue by JustDemetrius** [Flowseal/zapret-discord-youtube#641]
Всем доброго времени суток!

В ранних версиях проблемы описанной в названии не было, но и ранние версии уже не работают)
Опишу подробно:
1. запустил как сервис данный обход, все работает отлично, спасибо;
2. запускаю впн (GameVpn), выбрал игру, нажимаю подключить (с момента подключения программа ожидает запуска конкретной игры и отлавливает весь её трафик);
3. если после первых двух шагов попробую перейти в другой канал, стримить или открыть чей то стрим - ничего не выйдет, словно и обход не работает;

**Собственно вопрос весь в чем:** возможно ли как то поправить эту проблему? Как я понимаю впн и обход конфликтуют, где слабым звеном оказывается данный способ обхода)

**Comment by serpen7** [comment]
Они не конфликтуют, ваш "ВПН" имеет встроенный фильтр трафика и он нивелирует собой то что делает запрет т.к. фильтрует трафик сам по типу тех же сетевух киллер нетворка, "оптимизируя" его. От чего и происходит такой казус. 
![image](https://github.com/user-attachments/assets/0a08a899-f351-4a17-a8ac-3b03123bafe5)

Хотя зачем вам запрет если вы все равно пользуете впн не понятно.
Заставить их работать вместе не получится т.к. тогда в вашем впне не должно быть "оптимизации" трафика, чтобы манипулировать с пакетами которые уже обработал запрет и как то чистить их или преобразовывать.
Странно что там написано что захватывает пакеты только игр, но походу явно работает и на дискорд пакеты, которые обрабатывает запрет. Чето не сходится. И странно тогда почему у вас дискорд не запускается как обычно без запрета, если ваш впн обрабатывает пакеты дискорда... какая то странная "оптимизация" получается.

**Comment by JustDemetrius** [comment]
> Они не конфликтуют, ваш "ВПН" имеет встроенный фильтр трафика и он нивелирует собой то что делает запрет т.к. фильтрует трафик сам по типу тех же сетевух киллер нетворка, "оптимизируя" его. От чего и происходит такой казус. ![image](https://private-user-images.githubusercontent.com/134365619/384603108-0a08a899-f351-4a17-a8ac-3b03123bafe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjM1MjgsIm5iZiI6MTczMTE2MzIyOCwicGF0aCI6Ii8xMzQzNjU2MTkvMzg0NjAzMTA4LTBhMDhhODk5LWYzNTEtNGExNy1hOGFjLTNiMDMxMjNiYWZlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNDQwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGMzNGUwNGVmY2JiM2NmMzFjYWExYmJmYzgzZWU3MjY3ZGIxYWVhN2UwNDRmZDhkM2Y4ZmZmZWZhNTZhNzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GtTh5CEPgQwKbbu0p3Gb89vPzqsH7LdxeC1esUrTqgo)
> 
> Хотя зачем вам запрет если вы все равно пользуете впн не понятно. Заставить их работать вместе не получится т.к. тогда в вашем впне не должно быть "оптимизации" трафика, чтобы манипулировать с пакетами которые уже обработал запрет и как то чистить их или преобразовывать. Странно что там написано что захватывает пакеты только игр, но походу явно работает и на дискорд пакеты, которые обрабатывает запрет. Чето не сходится. И странно тогда почему у вас дискорд не запускается как обычно без запрета, если ваш впн обрабатывает пакеты дискорда... какая то странная "оптимизация" получается.

Дело в том что [GameVpn ](https://vpngame.net/index.php) работает напрямую с трафиком игры. Мне не нужно весь пк накрывать впн, а только игру которая без впн не работает.

Я безусловно не понимаю как с трафиком работает ваш метод обхода и как работает тот впн, НО я связался с ними и они заверили что они явно конфликтуют и помочь они мне не могут с этим.

**Comment by JustDemetrius** [comment]
Конкретно в случае конкретно того указанного мной впн была найдено решение благодаря поддержке gameVpn. На всякий случай напишу инструкцию, если вдруг кто то когда то попадёт на этот пост:

1. В настройках программы нажать "удалить Kernel драйвер".
2. Выставить галку на "Использовать TDI драйвер".
3. Перезапустить пк.
4. Запустить программу (gameVpn) снова.

По итогу они более не конфликтуют и работают параллельно.

**Comment by serpen7** [comment]
> Конкретно в случае конкретно того указанного мной впн была найдено решение благодаря поддержке gameVpn. На всякий случай напишу инструкцию, если вдруг кто то когда то попадёт на этот пост:
> 
> 1. В настройках программы нажать "удалить Kernel драйвер".
> 2. Выставить галку на "Использовать TDI драйвер".

темнят чето они, если в кернеле оно "конфликтует" вдруг пытаясь чето сделать с манипуляциями запрета на дискорд, "оптимизировать" так сказать. То почему в транспортнике они не конфликтуют если их прога действует только на игры даже в кернеле. Помоему они не договаривают что их "оптимизатор" в кернеле работает не только на игры т.к. получает доступ ко всему что в системе, а вот на транспортнике они получают именно тот доступ который предоставлен. И вот в транспортнике он видимо работает как надо у них. 

Либо теория номер 2... они используют тот же виндайверт для перехвата трафика, но переделанный под себя)))
Тогда бы было 100% понятно почему отваливается фильтрация запрета.  И в кернеле оба драйвера просто конфликтуют.
