### ISSUE TITLE
Работает youtube, но не работает дискорд

### ISSUE THREAD

**Issue by Maximilian-Leonhard** [Flowseal/zapret-discord-youtube#642]
Добрый день. Уже какое-то время пользуюсь программой, и почему-то она не хочет у меня работать полностью.
Я запускаю от имени администратора батники general и discord и держу их обоих открытыми. Youtube у меня работал отлично, но вот дискорд отказывается даже обновляться. 
До этого пользовался dpi, но удалял его для того чтобы пользоваться zapret'ом. Помогите пожалуйста, а то у всех моих знакомых дис отлично пашет и у меня одного нет xD
![222](https://github.com/user-attachments/assets/08f8c533-c8b6-45d7-a186-dadd8c86df2a)
![111](https://github.com/user-attachments/assets/de9d476d-286c-480c-a737-8473514e2725)

**Comment by serpen7** [comment]
вам не нужно запускать несколько батников одновременно вам нужно чтобы работал какой то один.

**Comment by serpen7** [comment]
А вы просто папку удаляли с гудбайдпи или перед этим запускали сервис ремув от имени администратора?

**Comment by Maximilian-Leonhard** [comment]
Попробовал запустить с одним батником (discord) и не помогло.
У меня есть маленькое ощущение что я сначала удалил GoodbyeDPI а только потом запустил сервис ремув. Но я не уверен.

**Comment by Maximilian-Leonhard** [comment]
Сейчас запуская сервис ремув вижу это:
![3333](https://github.com/user-attachments/assets/0b902e2b-e3f8-41d4-b933-e8fe7319a1af)

**Comment by serpen7** [comment]
> Попробовал запустить с одним батником (discord) и не помогло. У меня есть маленькое ощущение что я сначала удалил GoodbyeDPI а только потом запустил сервис ремув. Но я не уверен.

Так их там еще 8 батников стратегий
![image](https://github.com/user-attachments/assets/7927fb88-ca57-417a-a0eb-d75f1d49710c)
 запускайте их по одному закрывая предыдущий если не пробило. Дискорд придется закрывать каждый раз перед тем как запускаете какой то батник.

**Comment by Maximilian-Leonhard** [comment]
ALT2 сработал!
Большое спасибо!)

**Comment by VivishkaRU** [comment]
> ALT2 сработал! Большое спасибо!)

Тему закройте если проблему решили
