### ISSUE TITLE
Проблема с аватарками, баннерами и прочим в Дискорд

### ISSUE THREAD

**Issue by VivishkaRU** [Flowseal/zapret-discord-youtube#647]
Если кто-то найдёт новый блокнутый домен, напишите, ибо эта байда уже начинает нервировать пипец

**Comment by MadPeachTM** [comment]
плюсую, тоже такая проблема появилась. правда, увидел не сразу. открыл папку с сервами, которую не открывал относительно давно, там не прогружаются. те, что не в папаках пока что отрисовываются

**Comment by StyxPZ** [comment]
Аналогичная проблема. Есть уже пару дней. С некоторыми альтовыми батниками ютуб помирает, с некоторыми дискорд

**Comment by Flowseal** [comment]
Возможно, нужно найти незаблоченный CDN и перекинуть запросы туда

**Comment by vialast** [comment]
та же самая проблема

**Comment by Eptiy** [comment]
cloudflare-ech.com добавляйте в список доменов

**Comment by StyxPZ** [comment]
> cloudflare-ech.com добавляйте в список доменов

Он и так в списке есть. Один хрен - не работает.

**Comment by Eptiy** [comment]
> > cloudflare-ech.com добавляйте в список доменов
> 
> Он и так в списке есть. Один хрен - не работает.

ты его как в список добавлял? новый билд скачивал, или?

**Comment by StyxPZ** [comment]
> > > cloudflare-ech.com добавляйте в список доменов
> > 
> > 
> > Он и так в списке есть. Один хрен - не работает.
> 
> ты его как в список добавлял? новый билд скачивал, или?

В последнем билде по-умолчанию есть.

**Comment by Eptiy** [comment]
Я только что проверил 1.5.2. Установил в севрисы discord.bat. Аватарки и медиа в дс грузятся, проверка на secure sni от клаудфлэйр проходит. Либо у тебя не подходит конфиг, либо ты где-то накосячил.

Сам по себе батник тоже работает.

**Comment by Eptiy** [comment]
Касперский может блочить secure sni. Скорее всего, есть ещё какие-то программы, которые мешают такому соединению. Возможно, у тебя дело в них.

**Comment by VivishkaRU** [comment]
> Я только что проверил 1.5.2. Установил в севрисы discord.bat. Аватарки и медиа в дс грузятся, проверка на secure sni от клаудфлэйр проходит. Либо у тебя не подходит конфиг, либо ты где-то накосячил.
> 
> Сам по себе батник тоже работает.

В прошлый раз добавлял, ещё до этих ваших обновлений, всё работало, потом опять отвалилось, так что тейк такой себе, у меня нет в целом антивирусов и прочего что мешает работе драйвера и т.п.

**Comment by Eptiy** [comment]
Я же написал

> Либо у тебя не подходит конфиг

Никто же не даёт гарантий, что у всех безоговорочно будут работать конфиги, представленные в билде.

> у меня нет в целом антивирусов и прочего что мешает работе драйвера и т.п.

Дело не в работе драйвера, а в работе ech. Я только что у себя установил, что проверка защищённых соединений в касперском буквально отключает secure sni. К работе запрета это отношения не имеет, но может мешать доступу к ресурсам, работающим по ech. И помимо каперского могут быть другие подобные программы.

Помимо прочего, secure sni не будет работать без doh, что тоже не имеет отношения к билду.

Проверь у себя соединение на https://www.cloudflare.com/ssl/encrypted-sni. Так будет понятнее, есть ли реально подключение к cloudflare-ech.com.

**Comment by VivishkaRU** [comment]
> Я же написал
> 
> > Либо у тебя не подходит конфиг
> 
> Никто же не даёт гарантий, что у всех безоговорочно будут работать конфиги, представленные в билде.
> 
> > у меня нет в целом антивирусов и прочего что мешает работе драйвера и т.п.
> 
> Дело не в работе драйвера, а в работе ech. Я только что у себя установил, что проверка защищённых соединений в касперском буквально отключает secure sni. К работе запрета это отношения не имеет, но может мешать доступу к ресурсам, работающим по ech. И помимо каперского могут быть другие подобные программы.
> 
> Помимо прочего, secure sni не будет работать без doh, что тоже не имеет отношения к билду.
> 
> Проверь у себя соединение на https://www.cloudflare.com/ssl/encrypted-sni. Так будет понятнее, есть ли реально подключение к cloudflare-ech.com.

Так почему оно работало буквально недавно? Я никаких программ не ставил.. Или кучка людей решили тупа скачать что-то что мешает работе Secure SNI?

**Comment by VivishkaRU** [comment]
+ тот же postimage не работал без вписания в домены cloudflare-ech.com, сейчас работает, но конкретно Дискорд бубнит, по итогу мы получаем что что-то работает, а что-то нет, выборочно чтоль работать не хочет?

**Comment by Eptiy** [comment]
Ты можешь проверить работу secure sni, а не демагогию разводить?

**Comment by VivishkaRU** [comment]
> Ты можешь проверить работу secure sni, а не демагогию разводить?

Сейчас оно не работает, вчера оно работало

**Comment by Eptiy** [comment]
Проверь настройку безопасного днс в браузере, он должен быть включен и выбран должен быть cloudflare. Нужно попробовать добиться работы ech хотя бы в браузере.

**Comment by VivishkaRU** [comment]
> Проверь настройку безопасного днс в браузере, он должен быть включен и выбран должен быть cloudflare. Нужно попробовать добиться работы ech хотя бы в браузере.

Включив отдельно чисто через cloudflare всё подключилось

**Comment by VivishkaRU** [comment]
Собственно как на уровне ОС это переключить? Я дундук

**Comment by Eptiy** [comment]
В настройках, во вкладке "сеть и интернет", находишь своё подключение, например "Ethernet". Там прописываешь вручную dns от клаудфлэйр (1.1.1.1 и  1.0.0.1).

Пример на win 11:

![Снимок экрана 2024-11-10 200157](https://github.com/user-attachments/assets/c0382a6a-93d0-41f6-ae7f-fc4472c7d5a8)

**Comment by VivishkaRU** [comment]
> В настройках, во вкладке "сеть и интернет", находишь своё подключение, например "Ethernet". Там прописываешь вручную dns от клаудфлэйр (1.1.1.1 и 1.0.0.1).
> 
> Пример на win 11:
> 
> ![Снимок экрана 2024-11-10 200157](https://private-user-images.githubusercontent.com/184378098/384686471-c0382a6a-93d0-41f6-ae7f-fc4472c7d5a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDE0ODQsIm5iZiI6MTczMTI0MTE4NCwicGF0aCI6Ii8xODQzNzgwOTgvMzg0Njg2NDcxLWMwMzgyYTZhLTkzZDAtNDFmNi1hZTdmLWZjNDQ3MmM3ZDVhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxMjE5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODdlOGExZjBhYmI0OWVmZDczODBjODVlM2RiYTY1MzFlMTI5YzkzNjkzMWM1ZDllMmU1MGY1NjA0MjQ1NjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h3Ksm0IyHzW22R8ipbO21g27bdp4tyaVM3kS-jplP2Y)

Включил, даже при выборе поставщика на уровне OC работает на сайте, а ДС всё ещё не прогружает картинки

**Comment by Eptiy** [comment]
Дс перезапускал?
Работает на сайте, всм веб версия дс?

**Comment by VivishkaRU** [comment]
> Дс перезапускал? Работает на сайте, всм веб версия дс?

На сайте работает, я и ПК перезапускал, лишь ДС выпендрёж выдаёт

**Comment by VivishkaRU** [comment]
Тобишь онли десктоп версия бебебе с бабаба ловит, а вэб версия в норме

**Comment by Eptiy** [comment]
Попробуй этот билд
https://github.com/N3M1X10/zapret_build

cloudflare-ech.com там нужно будет прописать в лист вручную

**Comment by VivishkaRU** [comment]
> Попробуй этот билд https://github.com/N3M1X10/zapret_build
> 
> cloudflare-ech.com там нужно будет прописать в лист вручную

Да, этот билд уже работает как надо

**Comment by Eptiy** [comment]
Видимо, дело в том, что в билде flowseal ipset.

**Comment by VivishkaRU** [comment]
> Видимо, дело в том, что в билде flowseal ipset.

Я переместил переменные из general того билда в этот и всё проперделось, хоть и со скрипом, слегка

**Comment by Eptiy** [comment]
rules.txt не забудь перенести

**Comment by VivishkaRU** [comment]
> rules.txt не забудь перенести

Короче буду пока пользоваться тем билдом, надо будет думать как этот перепоять нормально

**Comment by Eptiy** [comment]
По сути можно использовать старую версию, до перехода с rules на ipset.

**Comment by VivishkaRU** [comment]
> По сути можно использовать старую версию, до перехода с rules на ipset.

Это у нас какая версия?

**Comment by Eptiy** [comment]
до 1.5.0

**Comment by VivishkaRU** [comment]
> до 1.5.0

Очень странно, но я вернул на 1.5.0 с вписаным доменом и у меня всё снова работает.. Окончательно не понимаю, у меня просто в билдах с rule не работает ютуб в врчате, вот и решил вернуть, а оно работает, рофл

**Comment by Eptiy** [comment]
По сути изменений в конфиге с 1.5.0 не было. Это прикол какой-то

**Comment by VivishkaRU** [comment]
Может смена днс вручную и кручения верчения само собой дало пропердеть ему?

**Comment by Eptiy** [comment]
Я вообще уже ни в чём не уверен.

**Comment by lAndreyAkl** [comment]
> Может смена днс вручную и кручения верчения само собой дало пропердеть ему?

Нет, я попробовал, 1.5.0 фиксит нашу проблему! General использую.
У меня после нескольких секунд прогрузки иконки вернулись.
