### ISSUE TITLE
Не работают некоторые сайты при использовании запрета.

### ISSUE THREAD

**Issue by perfonance** [Flowseal/zapret-discord-youtube#649]
После установки сервиса (выбирал 1 пункт discord) перестал работать сайт tracklock 
![image](https://github.com/user-attachments/assets/28743c69-d8df-41ea-9cb3-9e188a11be74)

**Comment by MadPeachTM** [comment]
я не спец. но слышал, что любимый надзор стал блочить cloudflare. не уверен, что это так, просто у меня такие же проблемы появились в то же время, как прочел об этом. множественные перезагрузки для первичной прогрузки сайта (или открытие его в режиме инкогнито), помогают. неудобно, но лучше не придумал ничего

**Comment by MadPeachTM** [comment]
попробуй в домены добавить cloudflare-ech.com
мне помогло, нашел только что в обсуждении по дискорду

**Comment by perfonance** [comment]
Да все дело в том, что как только в службах выключаю сервис - все работает.

**Comment by Eptiy** [comment]
> попробуй в домены добавить cloudflare-ech.com мне помогло, нашел только что в обсуждении по дискорду

Очень вероятно, что это решит проблему. Сейчас большинство сайтов, которые находятся за cloudflare, автоматически переходят на ech без ведома владельцев, отчего они перестают работать на фоне блокировки ech.

**Comment by Eptiy** [comment]
В 1.5.2 добавлен ech в листы, так что возможно, у тебя уже он там есть. У меня tracklock работает и с запретом, и без запрета. По сути конфиг никак с ним конфликтовать не должен, т.к. сайта в листе точно нет. Даже не знаю, что тут можно сделать.

**Comment by perfonance** [comment]
Установил актуальную версию 1.5.2. Проблема решена, всем огромное спасибо!
