### ISSUE TITLE
youtube открывается не моментально

### ISSUE THREAD

**Issue by vodves-vodves** [Flowseal/zapret-discord-youtube#65]
Видео начинает проигрываться спуся 5-6 секунд после открытия. В чем может быть проблема?

**Comment by Flowseal** [comment]
Если вы до этого использовали GoodbyeDPI, можете продолжать его использовать. В [README.md](https://github.com/Flowseal/zapret-discord-youtube/blob/main/README.md) гляньте как использовать `service_goodbye_discord.bat`

**Comment by vodves-vodves** [comment]
прикол в том, что и GoodbyeDPI начала с задержкой проигрывать видео, после запуска обхода дискорда

**Comment by e2li1386** [comment]
Если запускать батник на дис+ютуб, то, допустим, с измененными параметрами для gdpi под google chrome (котлючение квика и TLC) - именно на плеере постоянно крутит круглишок. В Firefox, ничего не меняя, всё мгновенно начинает проигрывать и прогрузки с шариком нет, но сам сайт ютуба заторможенно прогружается.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90
