### ISSUE TITLE
Всё отлично работает но в дискорде не прогружаются иконки серверов

### ISSUE THREAD

**Issue by Gergish001** [Flowseal/zapret-discord-youtube#654]
![image](https://github.com/user-attachments/assets/4a1f3be5-328a-4a9d-b045-720d4fb8943a)

**Comment by Gergish001** [comment]
произошло после нового обновления

**Comment by Eptiy** [comment]
Обновления чего? Если билда, то попробуй откатиться до 1.5.0.

UPD: Только там вручную нужно будет прописать cloudflare-ech.com в листы.

**Comment by Gergish001** [comment]
> Обновления чего? Если билда, то попробуй откатиться до 1.5.0.
> 
> UPD: Только там вручную нужно будет прописать cloudflare-ech.com в листы.

недавнего обновления дискорда

**Comment by Eptiy** [comment]
А версия билда у тебя какая?

**Comment by lAndreyAkl** [comment]
Со вчерашнего вечера такое, нет ни одной прогруженной аватарки/ иконки игр/ иконки кнопок у ботов.
stable 342968 (f8fde36) Host 1.0.9169 x64 (54876) Build Override: N/A Windows 10 64-bit (10.0.19044)

**Comment by serpen7** [comment]
> Со вчерашнего вечера такое, нет ни одной прогруженной аватарки/ иконки игр/ иконки кнопок у ботов. stable 342968 (f8fde36) Host 1.0.9169 x64 (54876) Build Override: N/A Windows 10 64-bit (10.0.19044)

![image](https://github.com/user-attachments/assets/28033010-bca5-4efe-a0a2-f032d6f90b2a)
![image](https://github.com/user-attachments/assets/579db53f-b465-4d4e-8584-6e793f6b7eef)


вы скорее всего либо криво обновили версию, либо не удалили нормально сервис, если вы его ставили поэтому и не стала новая версия.

**Comment by Eptiy** [comment]
Почитайте внимательно последние посты https://github.com/Flowseal/zapret-discord-youtube/issues/647

**Comment by lAndreyAkl** [comment]
> > Со вчерашнего вечера такое, нет ни одной прогруженной аватарки/ иконки игр/ иконки кнопок у ботов. stable 342968 (f8fde36) Host 1.0.9169 x64 (54876) Build Override: N/A Windows 10 64-bit (10.0.19044)
> 
> ![image](https://private-user-images.githubusercontent.com/134365619/384706303-28033010-bca5-4efe-a0a2-f032d6f90b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTgzODYsIm5iZiI6MTczMTI1ODA4NiwicGF0aCI6Ii8xMzQzNjU2MTkvMzg0NzA2MzAzLTI4MDMzMDEwLWJjYTUtNGVmZS1hMGEyLWYwMzJkNmY5MGIyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNzAxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTM1ZjIzMDVjZDc4YTU5MmE5MTA5MDcyZDcwMzgwNzNjZGY1MjMyOGE5ZDA0MmQ5NzQ1YjBhMTI5OGEyNzdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uen5qizUjFC1xgp6X3Pescfbl_qRp6inyuQ07qNA6I4) ![image](https://private-user-images.githubusercontent.com/134365619/384706482-579db53f-b465-4d4e-8584-6e793f6b7eef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTgzODYsIm5iZiI6MTczMTI1ODA4NiwicGF0aCI6Ii8xMzQzNjU2MTkvMzg0NzA2NDgyLTU3OWRiNTNmLWI0NjUtNGQ0ZS04NTg0LTZlNzkzZjZiN2VlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNzAxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjNiYWU2NmNmYThmNzMzNDg3MTdlMWZkMGM4MTAzMjk2ODdmZDRhOWQyOTA1Njc2NTY3Mzc4ZDMzNGQyNDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U3m-FX8nSBpODqMIFqdunYJoMHadkpOq6kqE9eQjK3E)
> 
> вы скорее всего либо криво обновили версию, либо не удалили нормально сервис, если вы его ставили поэтому и не стала новая версия.

А сейчас аватарки появились, спустя сутки. Нет только иконок бокового меню серверов...

**Comment by lAndreyAkl** [comment]
> Почитайте внимательно последние посты #647

Спасибо, 1.5.0 помог без танцев с бубнами! Временно проблема решена, видно проблема будет проявляться с версии 1.5.1 и выше.

**Comment by Eptiy** [comment]
Не понятно, почему у одних ech - лечит, а у других - калечит. Не затруднит попробовать 1.5.1 или 1.5.2 с удалением cloudflare-ech.com из списков?

**Comment by Eptiy** [comment]
Короче, это уже дело разраба весь этот ужас анализировать. Я слишком плохо в этом разбираюсь, чтобы какие-то выводы сделать, но хорошо, что хоть как-то удалось помочь.

**Comment by serpen7** [comment]
> Короче, это уже дело разраба весь этот ужас анализировать. Я слишком плохо в этом разбираюсь, чтобы какие-то выводы сделать, но хорошо, что хоть как-то удалось помочь.

там по ченджам только лишь был прикручен ип сет лист дискорда из критичных ну и исправлено кое чего и так же добавлен cloudflare-ech.com от 1.5.0  до текущей версии если в общих словах. Там не много правок, все они в хистори контейнера на мейне. Ну или в релиз сравнении.

**Comment by lAndreyAkl** [comment]
> Короче, это уже дело разраба весь этот ужас анализировать. Я слишком плохо в этом разбираюсь, чтобы какие-то выводы сделать, но хорошо, что хоть как-то удалось помочь.

Да, это точно. Хоть я и сам, системный администратор, но целостной картинки в голове нет как это всё работать должно. Тут надо разбираться в софте, разбираться в механизмах и разбираться в коде... Тяжко в общем, оригинальный репозиторий zapret вообще гуру писал, не иначе!

**Comment by serpen7** [comment]
то что у парня не прогружаются иконки либо означает что его стратерия не пробивает нормально, либо палится, и уже на нее действует динамо блокировка, а это та еще фигня. Ну или он просто решил что его ркн не сменят стратегию блокировки поэтому не решил пробовать другие стратегии. При установленном сервисе это не имеет даже никакого смысла т..к ты запускаешь 2 батника даже если запускаешь 1. Сервис нужно удалять как и драйвер фильтрации, чтобы начинать с чистого листа без конфликтов с разными фильтрами.
Либо же самое баналньное он говорит что все сделал но на старом релизе, я с таким встречался и чел спалился скрином буквально. Я просто замолчал. Потому что он сказал после моего сообщения что он на последнем релизе. Тут как бы все, мои полномочия по помощи, сам понимаешь. Я просто не хочу тратить время на людей которые не слушают и думают что они правы и это должно работать на их релизе который они скачали фиг знает сколько назад.

**Comment by serpen7** [comment]
> > Короче, это уже дело разраба весь этот ужас анализировать. Я слишком плохо в этом разбираюсь, чтобы какие-то выводы сделать, но хорошо, что хоть как-то удалось помочь.
> 
> Да, это точно. Хоть я и сам, системный администратор, но целостной картинки в голове нет как это всё работать должно. Тут надо разбираться в софте, разбираться в механизмах и разбираться в коде... Тяжко в общем, оригинальный репозиторий zapret вообще гуру писал, не иначе!

это фильтр который дурит DPI т.е. ТСПУ до сервера, потом пакеты в идеале должны "умирать" чтобы не ломать пакеты ответа от сервера которые он не примет, в общем.  Сервер принимает пакеты нормальные среди манипуляций и отдает пакеты нормальные после. Все. Мод пакетов на этом завершен. Нет никакой недопонимаемости, есть лишь конфиг который пробивает это или нет. Если не пробивает ни один из стратегий данных в репозитории нужно думать над индивидуальным конфигом, либо редактить свои, например менясть стратегии fooling, либо же убирать сплиты или фейки, смотря на что триггерится ТСПУ

**Comment by Eptiy** [comment]
Суть в том, что я со дня блока дискорда сижу на, по сути, форке этого билда, который уже 4 недели не обновлялся, и всё, что я за это время словил - частичный отвал медиа в дс после блокировки ech роскомнадзором. И банальное добавление его в обход всё починло.

Судя по ченджлогу на ipset пересели как раз на 1.5.0, дальше изменений в конфигах никаких не было. И уже у двух человек откат до этой версии фиксит проблему, хотя по сути этот откат ничего менять не должен.

**Comment by serpen7** [comment]
> Суть в том, что я со дня блока дискорда сижу на, по сути, форке этого билда, который уже 4 недели не обновлялся, и всё, что я за это время словил - частичный отвал медиа в дс после блокировки ech роскомнадзором. И банальное добавление его в обход всё починло.
> 
> Судя по ченджлогу на ipset пересели как раз на 1.5.0, дальше изменений в конфигах никаких не было. И уже у двух человек откат до этой версии фиксит проблему, хотя по сути этот откат ничего менять не должен.

форке этого билда?

**Comment by Eptiy** [comment]
Билд запрета от nemixio
https://github.com/N3M1X10/zapret_build

**Comment by serpen7** [comment]
> Reference in new issue

вопрос по существу если вы сидите на запрете том от другого чела зачем пишите в этот запрет и его компиляцию? Если у них разная структура и данные по поддержке и составлению, и обновлению? На каком релизе основан его билд и обновлял ли его он вообще? Малость не понятна логика ваших действий учитывая дату обновления релиза в том репозитории, того человека.

**Comment by Eptiy** [comment]
Потому что проблемы +- у всех одинаковые, т.к. всё основано на болвановском запрете? В конце концов я пытаюсь тут помочь людям и даже помогаю.

**Comment by serpen7** [comment]
> Потому что проблемы +- у всех одинаковые, т.к. всё основано на болвановском запрете? В конце концов я пытаюсь тут помочь людям и даже помогаю.

болвановский запрет уже обновился выше этого всего там и автоопределение и автохосты но с головой. Вы хоть зайдите в его репозиторий почитайте. А ответвления от его релиза это уже индивитуальные вещи. И до его последнего прям релиза ни один реп не обновлялся потому что там нужно перестраивать кучи всего что уже не работает по его репе.

**Comment by Eptiy** [comment]
Если не нравится, что я пытаюсь помочь людям в силу своих возможностей, я могу вообще не притрагиваться больше к местным обсуждениям.

**Comment by serpen7** [comment]
> Если не нравится, что я пытаюсь помочь людям в силу своих возможностей, я могу вообще не притрагиваться больше к местным обсуждениям.

если ты про мои комменты и воспринял их как то на себя то прости, не хотел чтобы так получилось, мой посыл был несколько другой. Не принимай близко к сердцу, любая помощь это помощь людям. С благими намерениями. Мы все в одной лодке тут как бы.

**Comment by Eptiy** [comment]
Всё окей, просто я пытаюсь свой анализ провести. Тут у людей откат до версии, с которой изменений по логам существенных не было, нормализует работу обхода. В этом парадокс.

**Comment by serpen7** [comment]
> Всё окей, просто я пытаюсь свой анализ провести. Тут у людей откат до версии, с которой изменений по логам существенных не было, нормализует работу обхода. В этом парадокс.

тут малость может быть что либо ИП сет неактуален либо он конфликтует с чем то еще т.к. там масса адресов, вопрос мягко говоря довольно интересный. Но опять же в старых версиях нет актуальной ситуации и вещей на то что происходит сейчас поэтому тут малость вопрос того что людям нужно. Пробивает, ну и норм, оставь так. Не пробивает нужно думать и пробовать уже чето менять.
РКН малость кучу "говнеца" в это ввел решив заблокировать хелло клиент на tls 1.3 дополнении. Это все вводит в диссонанс о том где проблемы случаются. Не говоря уже о вреде пользователям иннета таким решением.

Хотя даже ща смотрю в 1.5.0 уже был реализован ип сет и ничего особо не менялось, кроме последнего релиза обхода ЕСН. И все по сути дела, поэтому 1.5.2 должна работать так же как и 1.5.0. Если 1.5.0 работает а если  1.5.2 не работает то тут что то явно не то и возможно обычно локально.

**Comment by lAndreyAkl** [comment]
> > > Короче, это уже дело разраба весь этот ужас анализировать. Я слишком плохо в этом разбираюсь, чтобы какие-то выводы сделать, но хорошо, что хоть как-то удалось помочь.
> > 
> > 
> > Да, это точно. Хоть я и сам, системный администратор, но целостной картинки в голове нет как это всё работать должно. Тут надо разбираться в софте, разбираться в механизмах и разбираться в коде... Тяжко в общем, оригинальный репозиторий zapret вообще гуру писал, не иначе!
> 
> это фильтр который дурит DPI т.е. ТСПУ до сервера, потом пакеты в идеале должны "умирать" чтобы не ломать пакеты ответа от сервера которые он не примет, в общем. Сервер принимает пакеты нормальные среди манипуляций и отдает пакеты нормальные после. Все. Мод пакетов на этом завершен. Нет никакой недопонимаемости, есть лишь конфиг который пробивает это или нет. Если не пробивает ни один из стратегий данных в репозитории нужно думать над индивидуальным конфигом, либо редактить свои, например менясть стратегии fooling, либо же убирать сплиты или фейки, смотря на что триггерится ТСПУ

До этого я допенькал, почитал)
А вот дальше, там такой тёмный лес из используемых сервисов в оригинальном репозитории у Болвана... Но возможно я лезу слишком глубоко, как всегда)

**Comment by serpen7** [comment]
> > > > Короче, это уже дело разраба весь этот ужас анализировать. Я слишком плохо в этом разбираюсь, чтобы какие-то выводы сделать, но хорошо, что хоть как-то удалось помочь.
> > > 
> > > 
> > > Да, это точно. Хоть я и сам, системный администратор, но целостной картинки в голове нет как это всё работать должно. Тут надо разбираться в софте, разбираться в механизмах и разбираться в коде... Тяжко в общем, оригинальный репозиторий zapret вообще гуру писал, не иначе!
> > 
> > 
> > это фильтр который дурит DPI т.е. ТСПУ до сервера, потом пакеты в идеале должны "умирать" чтобы не ломать пакеты ответа от сервера которые он не примет, в общем. Сервер принимает пакеты нормальные среди манипуляций и отдает пакеты нормальные после. Все. Мод пакетов на этом завершен. Нет никакой недопонимаемости, есть лишь конфиг который пробивает это или нет. Если не пробивает ни один из стратегий данных в репозитории нужно думать над индивидуальным конфигом, либо редактить свои, например менясть стратегии fooling, либо же убирать сплиты или фейки, смотря на что триггерится ТСПУ
> 
> До этого я допенькал, почитал) А вот дальше, там такой тёмный лес из используемых сервисов в оригинальном репозитории у Болвана... Но возможно я лезу слишком глубоко, как всегда)

у бол-вана в репозитории куда дальше утилита шагнула но она стала не простой для юзера, в принципе она и не была таковой, он уже не раз говорил что не преследует цель сделать для всех юзвер френдли утилиту, он лишь её представляет с фунционалом её, дальше уже пользователь подбирает что ему нужно для себя. Далее дело за юзером. Но смотря на всё чем она была в оригинале он таки все же пытается её сделать юзер френдли. Понимает это он или нет, добавляя, меняя, изменяя функции о том на что способен виндайверт в купе с его утилитой. Это стремление достойно уважения, потому что он пытается что-то донести не просто до прошареных в его утилите, но и для тех кто не прошарен. Такими темпами у нас многие поймут строение и работу сети и смогут противостоять многому.

**Comment by VivishkaRU** [comment]
Я тут понял одну странную хрень, если удалить запрет от Flowseal, запустить от N3M1X10, выключить и снова установить Flowseal, по какой-то НЕВЕДОМОЙ МНЕ ЛИЧНО ПРИЧИНЕ, аватары пробиваются и всё начинает работать в штатном режиме, почему? А по качану

**Comment by VivishkaRU** [comment]
Костыльно, но кому прям надо, юзайте

**Comment by Eptiy** [comment]
Скорее всего, аватары просто кешируются на диске после подключения по rules. Возможно, ipset не даёт до них пробиться.

**Comment by Eptiy** [comment]
Ещё вариант решения: https://github.com/Flowseal/zapret-discord-youtube/issues/666#issuecomment-2467927445

**Comment by Gergish001** [comment]
капец вы тут настрочили, я закрываю иссуе

**Comment by lAndreyAkl** [comment]
> капец вы тут настрочили, я закрываю иссуе

А писать то можно!

**Comment by lIKykycukIl** [comment]
А что делать если у меня именно эмодзи сервера не отображаются? всё остальное есть и работает, а их почему-то не видно(
