### ISSUE TITLE
Процесс dwm.exe грузит проц на 35%

### ISSUE THREAD

**Issue by STALKERBETA91** [Flowseal/zapret-discord-youtube#655]
Установил service_install.bat, после перезагрузки почти сразу после загрузки процесс dwm.exe начинает жрать 30-35% проца (5700 х3d) , даже после удаления сервиса через service_remove.bat , dwm запускается и жрёт проц, причём при запуске диспетчера задач он перестаёт жрать проц (прям как вирус ага) разобраться смог только через process lasso на который dwm не реагирует (не перестаёт жрать) после остановки процесса dwm в процесс лассо он (dwm) перезапускается но уже потребляет копейки и не грузит проц, помогите разобраться, сам запрет работает отлично, всё анлокает, но нагрузка проца напрягает. 
PS если перезапустить двм и запустить батник запрета анлок работает и проц не грузит, всё ок, но до перезагрузки, потом всё по кругу((
![dwm](https://github.com/user-attachments/assets/a12494ae-abb4-45cc-83e7-b1ebe86159fd)
![aca50cc5407c9572](https://github.com/user-attachments/assets/7d182a5f-0756-4fbd-91ec-4c08624fe50f)

**Comment by Eptiy** [comment]
dwm.exe это системный процесс и отношения к билду, и запрету в целом, не имеет.

> даже после удаления сервиса через service_remove.bat , dwm запускается и жрёт проц

Ты вообще уверен, что он раньше не жрал проц? Проблема с dwm.exe - распространённая и тянется ещё с win8.1. И решение всегда разное и неожиданное.

**Comment by serpen7** [comment]
Отношения к программе это не имеет, это диспетчер твоего рабочего стола. Почему он вдруг стал жрать ресурсы нужно разбираться с ОС
![image](https://github.com/user-attachments/assets/83351262-f88a-4324-ba1d-aff08597d7d0)

**Comment by Eptiy** [comment]
Кстати, их там два. Один, как положено, запущен от DWM-1, другой от СИСТЕМА, как раз подозрительный. Проверь его расположение. Не знаю, приведёт ли это к чему-то. Проблему надо гуглить, искать ответы на форумах, связанных с виндой, точно не здесь.

**Comment by serpen7** [comment]
> Кстати, их там два. Один, как положено, запущен от DWM-1, другой от СИСТЕМА, как раз подозрительный. Проверь его расположение.

проверить конечно стоит но это нормальное поведение если показываются все процессы от разных пользователей и даже от системы т.к. там процесс двм имеет такое поведение:

> Пользователь "DWM-#",
> где # указывает на номер сеанса, в котором запущен "Диспетчер окон рабочего стола".

Process lasso работает на низком уровне системы и показывает не только пользовательские штуки которые система может разрешить на системном даже уровне, а еще и много чего что скрыто даже в process explorer от майков. Что иногда сбивает с толку. 

Но может быть что человек качал левые какие то сборки из иннета, которые реально замаскировались под DWM, это довольно распространенный способ маскировки под explorer или dwm т.к. в случае чего обрубает тебе рабочий стол, нехорошие люди такие порой нехорошие, либо используют его для своей фигни. Тут не поймешь без доступа к компу и уже изысканий и анализа что происходит там вот.

**Comment by STALKERBETA91** [comment]
Понял, спасибо за советы, буду лечить
