### ISSUE TITLE
не запускается CoD

### ISSUE THREAD

**Issue by shuromo** [Flowseal/zapret-discord-youtube#656]
Помогите пж, удалил goodbyeDPI и Zapret, нажимаю играть и даже античит не появляется, тупо грузит минуту и заново кнопка играть

**Comment by serpen7** [comment]
тебе их нужно удалить и сервисами через ремув от администратора и физически если античит хотя бы раз их запалит. Оптимально их нужно выгружать полностью, закрывать или удалять сервис через сервис ремув от админа каждый раз перед тем как запускаешь игру, чтобы не делать ремув и физически их удалять. Такой вот античит у этой игры и поделать с ним могут только разрабы игры что либо.

**Comment by shuromo** [comment]
Я так и сделал, но ничего не поменялось

**Comment by serpen7** [comment]
> Я так и сделал, но ничего не поменялось

значит ты их не удалил
 ща секунду найду.

**Comment by shuromo** [comment]
Я смог удалить всю папку без проблем и ютуб и дс не работают, так что я не понимаю, что ещё я не удалил

**Comment by serpen7** [comment]
тогда смотри скачиваешь это https://github.com/ValdikSS/GoodbyeDPI/releases
И это https://github.com/Flowseal/zapret-discord-youtube/releases
по последним версиям
запускаешь service remove bat из обоих скачанных репозиториев поочередно от имени администратора, жмешь кнопку любую, жмешь еще раз любую кнопку, перезагружаешь комп, опять повторяешь сервис ремув бат от администратора, удаляешь физически потом папки с компа. 
Если хочешь можешь скачать эти утилиты снова **ПОСЛЕ**, но не ставь их в папки прежние где их запалил античит колды. И выгружай или закрывай утилиты перед тем как запускаешь колду.

**Comment by shuromo** [comment]
Я так и сделал, и не помогло

**Comment by serpen7** [comment]
> Я так и сделал, и не помогло

за 3 минуты ты сделал это включая с пекрезагрузкой пк?

**Comment by shuromo** [comment]
Я это пару часов назад сделал

**Comment by serpen7** [comment]
> Я это пару часов назад сделал

прочти внимательнее то что я написал, там не просто "удалил у себя папку"

**Comment by shuromo** [comment]
Я до этого так и сделал, мне друг помогал и сказал сделать тоже самое, что и ты сейчас, но ничего не помогло

**Comment by serpen7** [comment]
> Я до этого так и сделал, мне друг помогал и сказал сделать тоже самое, что и ты сейчас, но ничего не помогло

ох как я корю что тут нет личных сообщений, я бы посоветовал анидеск и посмотрел бы все сам что там происходит, и даже логи бы запуска посмотрел че ему не нравится.

**Comment by shuromo** [comment]
Могу скинуть тг и там продолжить, если ты не против. Только я дома буду не раньше 2 ночи по мск

**Comment by serpen7** [comment]
> Могу скинуть тг и там продолжить, если ты не против. Только я дома буду не раньше 2 ночи по мск

спать уже буду, я максимум в 1 часу ложусь ибо вставать в 8.30 максимум)))

**Comment by shuromo** [comment]
Хорошо. Тогда, вот мой тг: @Achotyt
И если тебе не будет трудно, завтра уже спишемся

**Comment by serpen7** [comment]
> Хорошо. Тогда, вот мой тг: @Achotyt И если тебе не будет трудно, завтра уже спишемся

ты? 
*тут был скриншот*

**Comment by shuromo** [comment]
Да
