### ISSUE TITLE
Не работает zapret

### ISSUE THREAD

**Issue by SpryMtg** [Flowseal/zapret-discord-youtube#657]
Открываю я все фаилы bat МГТС и вылазиет ошибка 
![image](https://github.com/user-attachments/assets/d78e0d4b-f3a7-4a29-941e-3ec489371e92)

**Comment by SpryMtg** [comment]
Помогите пж прошуу

**Comment by Eptiy** [comment]
Что-то снесло winws.exe из папки с запретом. Предположительно, антивирус. Добавь папку в исключения, распакуй туда билд заново и проверь работу.

**Comment by Eptiy** [comment]
Так, стоп, ты вообще распаковал билд? Почему у тебя путь ведёт ко временным файлам?

**Comment by serpen7** [comment]
ты запускаешь билд из архива, не распаковывая его в папку, в этом твоя проблема. Так же у тебя будет и на любой не standalone программе запускающейся не одним файлом и требующей всех файлов остальных в архиве\пакете для своей работы.

**Comment by SpryMtg** [comment]
Ну всмысл распоковал я его открыл в winrar

**Comment by SpryMtg** [comment]
![image](https://github.com/user-attachments/assets/85673d97-4118-4db1-a50c-6f3fa219045f)

**Comment by SpryMtg** [comment]
![image](https://github.com/user-attachments/assets/0477fd39-8e71-4374-8266-79a9e43526a4)

**Comment by SpryMtg** [comment]
и где сам билд что нужно запускать скажите покажите пожалуйста\

**Comment by serpen7** [comment]
> Ну всмысл распоковал я его открыл в winrar

потому что в пакетах запакованных не распаковываются остальные файлы архива. Распаковывается и запускается только то что ты выбрал.

**Comment by serpen7** [comment]
> ![image](https://private-user-images.githubusercontent.com/187964655/384702193-0477fd39-8e71-4374-8266-79a9e43526a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTM0NjMsIm5iZiI6MTczMTI1MzE2MywicGF0aCI6Ii8xODc5NjQ2NTUvMzg0NzAyMTkzLTA0NzdmZDM5LThlNzEtNDM3NC04MjY2LTc5YTllNDM1MjZhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNTM5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTgxMDU0MmNjNzg1NWI4Zjk3MzcyM2NjYzdlOGQyZTBhZjk2YThhMTc3NmM4NzA0YWNlMWRiNDYzZjNmNjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c_b526e2fH0fqNC3Z3HmRUyVCOs5OEV7bi8PbMo8nRU)

ты опять запускаешь из архива это банально палится по временной папке темпа =/

**Comment by SpryMtg** [comment]
ну а так что мне делать я не понимаю

**Comment by Eptiy** [comment]
не просто открывай его в winrar, а распакуй.

**Comment by serpen7** [comment]
> ну а так что мне делать я не понимаю

распаковать в папку архив.
![image](https://github.com/user-attachments/assets/ce63ee58-deb3-4dec-81e4-06c6e58b7e63)
![image](https://github.com/user-attachments/assets/183972f4-60fd-4acf-b033-b1b49b97a185)
![image](https://github.com/user-attachments/assets/1f23ef69-e942-452d-b350-0024d17e98af)
и пробовать батники  для начала 
![image](https://github.com/user-attachments/assets/eba51837-d05a-4cc0-8752-adf400a3fed0)

**Comment by SpryMtg** [comment]
У  меня нету распоковать

**Comment by SpryMtg** [comment]
а вот: 
![image](https://github.com/user-attachments/assets/eb114cb0-a4ca-449e-9432-9f290c65a7a9)

**Comment by SpryMtg** [comment]
все равно та же ошибка

**Comment by SpryMtg** [comment]
а  теперь ждурагя ошибка 
![image](https://github.com/user-attachments/assets/51fb018e-88cd-4b43-9ab7-3fa1cd49316b)

**Comment by Eptiy** [comment]
Ты всё ещё запускаешь его напрямую из архива.

**Comment by SpryMtg** [comment]
![Uploading image.png…]()

**Comment by SpryMtg** [comment]
![image](https://github.com/user-attachments/assets/896c780c-4c16-4171-b9dd-70dffcd33219)

**Comment by Eptiy** [comment]
Ну да, теперь ты просто открываешь его встроенным архиватором винды, но всё так же не распаковываешь. Выдели все эти файлы и перемести в любую папку.

**Comment by SpryMtg** [comment]
перенес

**Comment by serpen7** [comment]
> ![image](https://private-user-images.githubusercontent.com/187964655/384704506-896c780c-4c16-4171-b9dd-70dffcd33219.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTQ4MzQsIm5iZiI6MTczMTI1NDUzNCwicGF0aCI6Ii8xODc5NjQ2NTUvMzg0NzA0NTA2LTg5NmM3ODBjLTRjMTYtNDE3MS1iOWRkLTcwZGZmY2QzMzIxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNjAyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODEwZTRlODZiYmIwNTZjMjMzZTA4NzU4ODNhNDNiNWMyZTVhMWYwMTAzOWM4ZTEyNjc1MjI0YjBhOWVlNWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GnuADUs_rbnoZbK4_MtoQRbK2ff6pJYJZ9HEmiAO6oc)

у тебя в загрузках все так же нет папки распакованного архива, ты запускаешь его из архива 
![image](https://github.com/user-attachments/assets/3cba06f1-44d5-4f73-8b13-b8d7cc856e54)

**Comment by Eptiy** [comment]
> перенес

теперь как работает?

**Comment by SpryMtg** [comment]
Я СДЕЛАЛ ЭТО
СПАСИБО serpen7, eptiy

**Comment by Eptiy** [comment]
Пожалуйста. Научись, ради бога, распаковывать архивы.

**Comment by serpen7** [comment]
> Пожалуйста. Научись, ради бога, распаковывать архивы.

ну стендэлоун утилиты без зависимости на другие файлы он может и так запускать вприципе, однако да, лучше распаковывать ибо таких утилит крайне мало и нужно распаковывать весь архив иначе файлов нужных не хватает.

**Comment by SpryMtg** [comment]
К сожалению у меня опять проблема с дискорд

**Comment by SpryMtg** [comment]
Открывал все фаилы скачивал все зипи не зипы прям все открывал фаил дискорд и генерал работает только ютуб но не как не дискорд

**Comment by SpryMtg** [comment]
Помогитее пж

**Comment by SpryMtg** [comment]
![image](https://github.com/user-attachments/assets/affcf193-1b17-4a47-84b0-9465c00e8f47)
