### ISSUE TITLE
Не работает. 

### ISSUE THREAD

**Issue by jackpot6555** [Flowseal/zapret-discord-youtube#659]
Мб я слишком туплю, но оно не работает. Последняя версия, все открываю разрешаю (все файлы в отдельной папке), последней строкой написано capture is started. Ничего не закрываю, но ничего не работает. Тот же условный дискорд. Что делать, подскажите пж. Небольшая деталь: все превосходно работало, до тех пор пока компьютер не был перезапущен.

**Comment by Eptiy** [comment]
Проверь работу на 1.5.0 и на 1.4.1

**Comment by serpen7** [comment]
> Мб я слишком туплю, но оно не работает. Последняя версия, все открываю разрешаю (все файлы в отдельной папке), последней строкой написано capture is started. Ничего не закрываю, но ничего не работает. Тот же условный дискорд. Что делать, подскажите пж. Небольшая деталь: все превосходно работало, до тех пор пока компьютер не был перезапущен.

пробовать разные стратегии а не только одну 
![image](https://github.com/user-attachments/assets/4a56479f-0060-4989-85de-ddf9736c5c77)
их 9 штук, какая заработает у вас 
при этом нужно закрывать и открывать  приложение того же дискорда или браузера до запуска стратегии батником, чтобы оно сразу подхватило перехватываемые пакеты. И открывать батник по одному перед этим.

**Comment by Rararara8888** [comment]
Привет, превью в ютубе не показывает

**Comment by jackpot6555** [comment]
Ребят всё, всем спасибо, решено. Надо было запустить от имени администратора нужный файл.
