### ISSUE TITLE
Проблема с совместимостью

### ISSUE THREAD

**Issue by GENerAtor250** [Flowseal/zapret-discord-youtube#66]
![11111](https://github.com/user-attachments/assets/532ac157-016d-4555-afca-fcd8cc58d4cc)
Не запускает батник, выдает вот то, что на скрине
![22222](https://github.com/user-attachments/assets/ca1e3278-36d6-4601-a4c3-bcb1611609f0)
Скрин с версией системы прилагаю

**Comment by Flowseal** [comment]
Разархивируйте

**Comment by GENerAtor250** [comment]
> Разархивируйте

Уже
