### ISSUE TITLE
Не запускаются батники на win7

### ISSUE THREAD

**Issue by MrRyabena** [Flowseal/zapret-discord-youtube#661]
Отключил все защиты, добавил во все исключения, удалил все что может мешать. Пробовал качать разные релизы. При запуске батников они открываются на секунду и тут же закрываются. ОС windows 7. Может ли быть проблема с windivert или что-то блокирует батники? Вроде как раньше (компьютер не мой) работало нормально. Подскажите, у кого работает на 7ке

**Comment by serpen7** [comment]
если у вас очень старый билд то возможно возникнут проблемы с загрузкой дравера виндайверт в ОС, от чего будет неработоспособность драйвера, если у вас бизд больше 2016 года и он обновлялся - вам это не нужно. Проблема где то между утилитой и ОС скорее всего.  Если у вас обновления стоят после 2016 года то лучше не рискуйте ставить  старые обновы на обновленую ОС.

> Horribly outdated Windows 7 installations are not able to load WinDivert driver due to missing support for SHA256 digital signatures. Install KB3033929 [x86](https://www.microsoft.com/en-us/download/details.aspx?id=46078)/[x64](https://www.microsoft.com/en-us/download/details.aspx?id=46148), or better, update the whole system using Windows Update.

**Comment by EgorWeders** [comment]
Так батники сами и не должны висеть вроде, они вам другую программу запускают.

**Comment by MrRyabena** [comment]
> Так батники сами и не должны висеть вроде, они вам другую программу запускают.

Да, я имел ввиду winws который они запускают

**Comment by MrRyabena** [comment]
> если у вас очень старый билд то возможно возникнут проблемы с загрузкой дравера виндайверт в ОС
вот больше всего похоже на это

**Comment by Eptiy** [comment]
Что поменялось, если раньше работало, а теперь нет? Обновлялся билд? Или просто запрет внезапно отвалился? Самый первый звоночек в таком случае - наличие остатков старых версий билда, либо гудбая.

**Comment by EgorWeders** [comment]
Через cmd.exe запустите скиньте вывод.

**Comment by MrRyabena** [comment]
Спасибо что откликнулись, человек решил проблему: установил 10 винду))
