### ISSUE TITLE
Постоянное подключение к RTC

### ISSUE THREAD

**Issue by Wolteknsk** [Flowseal/zapret-discord-youtube#665]
Здравствуйте , при звонке идет постоянно подключение к RTC , а потом "Не установлен маршрут " , при этом все другие функции дс работают , пользуюсь антивирусником Dr.web

**Comment by Wolteknsk** [comment]
пробовал отключить антивирус , отключить VPN , ничего не помогает

**Comment by Wolteknsk** [comment]
> пробовал отключить антивирус , отключить VPN , ничего не помогает

**Comment by Eptiy** [comment]
В каком виде запускаешь и какой конфиг?

**Comment by Wolteknsk** [comment]
запускаю от имени админа  и перепробовал все батники

**Comment by Eptiy** [comment]
Попробуй версию 1.5.0. Плюс, попробуй создать заранее папку под билд и добавить её в исключения dr.web, после чего туда уже распаковывать билд.

UPD ещё можно попробовать 1.4.1

**Comment by Wolteknsk** [comment]
неа , не работает

**Comment by Eptiy** [comment]
Видимо, не подходят конфиги. Попробуй эти билды:
https://github.com/N3M1X10/zapret_build
https://howdyho.net/windows-software/discord-fix-snova-rabotayushij-diskord-vojs-zvonki

**Comment by Wolteknsk** [comment]
Не хочу расстраивать , но ничего не работает

**Comment by Eptiy** [comment]
капец

Остаётся только вручную подбирать конфиги через блокчек.

Опять же, не исключено, что кто-то из нас упускает какую-нибудь мелкую деталь. Ждём помощи от других.

**Comment by Flowseal** [comment]
> капец
> 
> Остаётся только вручную подбирать конфиги через блокчек.
> 
> Опять же, не исключено, что кто-то из нас упускает какую-нибудь мелкую деталь. Ждём помощи от других.

Как ты собираешься RTC через блокчек проверять?)

**Comment by Eptiy** [comment]
Камон, я не шарю в этой теме.

**Comment by mehh0vcki** [comment]
у меня запуск discord.bat помог на последней версии. пробывал?

**Comment by Wolteknsk** [comment]
последняя версия пишет что обнаружен вирус и пишет об этом сам браузер

**Comment by Eptiy** [comment]
С этого и недо было начинать. Ты пробовал с другого браузера скачивать?

~~Вообще могу залить на мегу последнюю версию, чтобы ты мог скачать.~~

~~UPD: залил на мегу:
https://mega.nz/file/gR9h0QrC#YauisTe_ARIESGf3ENh9kHDd7z2JjgvAgzLIMIo_nAI~~

Я чёт не подумал, что ты всё ещё с браузера будешь скачивать, забей, надо куда-то ещё залить.

**Comment by Eptiy** [comment]
Можешь попросить кого-нибудь из знакомых скачать и скинуть в тг, например.

**Comment by Wolteknsk** [comment]
получилось без проблем скачать 1.5.2 Sourse code (zip) , но ничего не поменялось все так же не работает 
![photo_2024-11-11_21-22-34](https://github.com/user-attachments/assets/be559f5a-a1d5-49c6-b1b6-ea5379a55b8a)

**Comment by Ciao735** [comment]
Такая же проблема, впны, защитники отключены, днс сервера переберал, другие билды пробывал, протыкивал файлики пока что ничего из выше перечисленного не помогло. Не работают войсы, не работают демки, лично я фиксил только тем что ребутал пеку и в ближайшие минут 5 после ребута заходил в канал/заходил на демки, после 5 минут если вышел с демки/из войса и хочу зайти обратно то возвращается проблема с RTC. Я сделал вывод что виноват провайдер: Дом.ру

**Comment by Eptiy** [comment]
Попробуйте переименовать ipset_discord, создать пустой текстовик с его названием и вписать туда эти ip:
```
138.128.136.0/21
162.158.0.0/15
172.64.0.0/13
34.0.0.0/15
34.2.0.0/16
34.3.0.0/23
34.3.2.0/24
35.192.0.0/12
35.208.0.0/12
35.224.0.0/12
35.240.0.0/13
5.200.14.128/25
66.22.192.0/18
```
Или эти:
```
66.22.0.0/16
34.0.0.0/16
35.207.0.0/16
35.214.0.0/16
35.215.0.0/16
35.213.0.0/16
35.217.0.0/16
35.219.0.0/16
```

**Comment by Wolteknsk** [comment]
Не работает

**Comment by alexlru3765** [comment]
Был установлен ADGUARD. он все блочил. Можно его отключить или добавить дискорд и браузер в списки исключений. Все заработает. Возможно так же проблема в аналогичных приложениях.

**Comment by Richarddix** [comment]
Аналогичная ситуация. Ещё самое интересное что на одном пк такое же подключение к ртс и т.д., а затем пишет не установлен маршрут, а на другом всё норм, при этом подключение на обоих пк одинаковое по кабелю от роутера и настройки тоже. Но всё равно вот так, при этом пробовал сделать всё тоже самое о чём говорилось выше, бесполезно

**Comment by Richarddix** [comment]
Только что разобрался. По какой-то причине был включен сервис checkpoint vpn, ранее им пользовался, хотя при этом везде отключал. Но в итоге выключил его в "services.msc" и свершилось чудо) 
Чекни службы, может что-нибудь там мешает

**Comment by Wolteknsk** [comment]
проблема в том что у меня на пк никогда не было впн, и всякого такого , проблема либо Dr.web либо в провайдере (Сибсети)

**Comment by Wolteknsk** [comment]
но dr web я уже отключал и ничего не работало

**Comment by Wolteknsk** [comment]
все заработало  в др вебе , брендмауре разрешил всем файлам Discord.exe запустил батник и все заработало

**Comment by hdevice** [comment]
> Только что разобрался. По какой-то причине был включен сервис checkpoint vpn, ранее им пользовался, хотя при этом везде отключал. Но в итоге выключил его в "services.msc" и свершилось чудо) Чекни службы, может что-нибудь там мешает

Спасибо тебе добрый человек!!! Просто намучался, рядом комп девушки - все работает, у меня подключение к RTC.
А на удаленке checkpoint vpn........СПАСИБО!

**Comment by lfeliks** [comment]
> все заработало в др вебе , брендмауре разрешил всем файлам Discord.exe запустил батник и все заработало

Не мог бы по подробней написать? А то вроде все разрешения даю, но голос так и не хочет подключаться.
