### ISSUE TITLE
Пропали аватарки полностью

### ISSUE THREAD

**Issue by Igorric82** [Flowseal/zapret-discord-youtube#666]
Стало ещё хуже сегодня.
![Снимок экрана 2024-11-11 193926](https://github.com/user-attachments/assets/31aae1fc-33de-4ce4-aab9-16ef2cfbb480)

**Comment by ZAReRRE** [comment]
Мне помогло использовать general (ALT2).bat, до этого использовал просто general.bat. Попробуй тоже разные, может тебе какой-нибудь подойдёт. Рекомендую перед этим закрыть дискорд.

**Comment by Igorric82** [comment]
Блин чел. Спасибо огромное! Помогло!

> Мне помогло использование general (ALT2).bat, до этого я использовал просто general.bat. Попробуй разные варианты, может, какой-нибудь тебе подойдёт. Рекомендую перед этим закрыть Discord.

**Comment by ZAReRRE** [comment]
Пожалуйста!

**Comment by ABrony** [comment]
Если кто свой батник кастомил, то похоже помогающим фактором был параметр `--dpi-desync-split-seqovl=652` в фильтре на TCP
