### ISSUE TITLE
Проблема запуска на Linux Ubuntu

### ISSUE THREAD

**Issue by KratoNius** [Flowseal/zapret-discord-youtube#67]
При запуске discord.bat с использованием wine выдает следующую ошибку:
0158:err:module:loader_init "cygwin1.dll" failed to initialize, aborting
0158:err:module:loader_init Initializing dlls for L"Z:\\home\\egor\\\0417\0430\0433\0440\0443\0437\043a\0438\\zapret-discord-youtube-main\\bin\\winws.exe" failed, status c0000142

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/7
