### ISSUE TITLE
Не работает голосовая связь Discord

### ISSUE THREAD

**Issue by dildorbek19** [Flowseal/zapret-discord-youtube#670]
Все работает замечательно, за исключением того, что я не слышу собеседников. При этом, меня они слышат прекрасно, и я даже могу смотреть их демонстрации экрана. Проверил все что можно, даже переустановил. Помогите пожалуйста!!

**Comment by Eptiy** [comment]
Похоже, что у тебя просто проблемы с микрофоном. В настройках голоса ты сам себя в микрофон слышишь?

**Comment by Eptiy** [comment]
Выглядит, как проблема с настройками звука. Возможно, в микшере заглушен дискорд. Вряд ли это имеет отношение к запрету.

**Comment by RedCapcha** [comment]
> Выглядит, как проблема с настройками звука. Возможно, в микшере заглушен дискорд. Вряд ли это имеет отношение к запрету.

У меня вот перестало подключать к голосовому, выдаёт ошибку поиска маршрута

**Comment by dildorbek19** [comment]
Прошу прощения, комп создал еще одно устройство ввода и вывода звука, которые называются почти так же, как стандартные наушники и микро на них и поставил по умолчанию в дс
