### ISSUE TITLE
Антивирус ругается не из перечисленных в README.md драйверов

### ISSUE THREAD

**Issue by thearchymain** [Flowseal/zapret-discord-youtube#671]
Крч,  качаю я последнюю версию и защитник винды ругается, что делать?(да я знаю что надо защитник вырубить)
![image](https://github.com/user-attachments/assets/ec714bf7-31fa-45a3-a942-9b0ed90ffb7f)

**Comment by Flowseal** [comment]
Читайте README. Этот детект туда же

**Comment by thearchymain** [comment]
> Читайте README. Этот детект туда же

мне то есть разрешить действие что бы работало?

**Comment by Flowseal** [comment]
В исключения кинь
