### ISSUE TITLE
Не отрывается запрет

### ISSUE THREAD

**Issue by kireeshka123** [Flowseal/zapret-discord-youtube#677]
Открывал от имени администратора, переустанавливал версии, не знаю что еще делать. Открыл с помощью командной строки - выдало это, я не шарю за это все, надеюсь на помощь
![image](https://github.com/user-attachments/assets/955ebb88-a1ec-4700-8698-c909c0814236)

**Comment by amazingdevvv** [comment]
Для быстрого решения можно вырезать проверку на обновления. Открой батник для редактирования и убери эту строку
![image](https://github.com/user-attachments/assets/9e45f1cc-3550-46bd-a931-8b26c0e9e774)

**Comment by Flowseal** [comment]
> Открывал от имени администратора, переустанавливал версии, не знаю что еще делать. Открыл с помощью командной строки - выдало это, я не шарю за это все, надеюсь на помощь ![image](https://private-user-images.githubusercontent.com/188104032/385043186-955ebb88-a1ec-4700-8698-c909c0814236.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNjE5ODEsIm5iZiI6MTczMTM2MTY4MSwicGF0aCI6Ii8xODgxMDQwMzIvMzg1MDQzMTg2LTk1NWViYjg4LWExZWMtNDcwMC04Njk4LWM5MDljMDgxNDIzNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQyMTQ4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmE2ZmY0OWIzYzNmNmNiOTk1ZTkxMDliNGYzMDU5ZGNhZDA1MTkzZjdjZDg4Y2FkMWUxNzJhZjg3ZGJkZWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Epa7zGk7ZdYrrtRfCAfq_4mNjQbLuQ_o774NRCtgEn8)

После запуска должно открываться окно winws. Если этого не происходит - читайте README.

> Для быстрого решения можно вырезать проверку на обновления. Открой батник для редактирования и убери эту строку ![image](https://private-user-images.githubusercontent.com/106401502/385053838-9e45f1cc-3550-46bd-a931-8b26c0e9e774.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNjE5ODEsIm5iZiI6MTczMTM2MTY4MSwicGF0aCI6Ii8xMDY0MDE1MDIvMzg1MDUzODM4LTllNDVmMWNjLTM1NTAtNDZiZC1hOTMxLThiMjZjMGU5ZTc3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQyMTQ4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjhjMzU2NzBjZmRkZjVmZjQ1MjVkYjc4ZWUwNDNkNTE1YmVlNjQwYzk1NDk0N2I2YmUxOTBhZGZmNzEwNzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NxAnS42osw7Al03-N_cCTt-f4824llN8Ye9pxmQQTz8)

Это никак не связано

**Comment by kireeshka123** [comment]
![image](https://github.com/user-attachments/assets/e1cc15bf-3209-48dd-931c-edafc4ec4917)
теперь просто ничего нет
