### ISSUE TITLE
Ютуб в плеерах сторонних сайтов (ВК, Нексусмод и т.п.)

### ISSUE THREAD

**Issue by CrescentXIII** [Flowseal/zapret-discord-youtube#68]
Не то что бы проблема, но помню долго с ней мучался на ByDPI и GDPI.
Т.е. допустим, на nexusmods, ВК или еще других сайтах где ссылки на ютуб можно просмотреть внутри сайта. Не грузит.
Не совсем понял как тут в батниках настройки применять то GDPI или ByDPI (на нем сейчас сижу на ПК).

Если не сложно и знаете, подскажите что дописать (изменить), что бы плееры воспроизводили ютуб на других сайтах. МГТС. По дефолту отлично все работает с ютуб.

спасибо.

**Comment by Flowseal** [comment]
Запускаете сервис GoodbyeDPI, запускаете `service_goodbye_discord.bat`, перезагружаете пк. Если goodbyedpi настроен, то так проще будет
