### ISSUE TITLE
Не подключает голосовую связь в Discord

### ISSUE THREAD

**Issue by RedCapcha** [Flowseal/zapret-discord-youtube#681]
При попытке подключения к каналам выдаёт ошибку Не установлен маршрут. Стоит последняя версия запрета, запуск альтернативных батников не помог.
![image](https://github.com/user-attachments/assets/9f9f70a4-08de-4732-b547-9edbec1ea945)

**Comment by Igorric82** [comment]
Может это у дс самого?

**Comment by RedCapcha** [comment]
> Может это у дс самого?

Нет, у корешей работает всё

**Comment by RedCapcha** [comment]
> Может это у дс самого?

Добавил в батник --dpi-desync-split-seqovl=652 и всё заработало
