### ISSUE TITLE
Не прогружаются медиа

### ISSUE THREAD

**Issue by Sanya-Coc** [Flowseal/zapret-discord-youtube#682]
### Discussed in https://github.com/Flowseal/zapret-discord-youtube/discussions/252

<div type='discussions-op-text'>

### Как эта проблема решается?

**Comment by LLlELECT** [comment]
Такая же ситуация, но скорее всего запрет ни при чем, потому что через впн то же самое

**Comment by JokoKenguru** [comment]
Я вклинюсь в ваш разговор ребят.. но может для 7тв есть строки которые стоит добавить что он работал) 
За ранее спасибо)

**Comment by serpen7** [comment]
> Я вклинюсь в ваш разговор ребят.. но может для 7тв есть строки которые стоит добавить что он работал) За ранее спасибо)

Их нет смысла добавлять потому что так же как и у гудбайдпи, строки добавляемые в листы работают и на поддоменах.
![image](https://github.com/user-attachments/assets/c1895c08-5e39-4d21-949b-ae44758e0f4b)
Единственное что это могут быть отдельные СДНы и прочее что не является поддоменом, но это уже не поведение обычного сайта, это что то вроде сервиса с множеством мультиплатформ и функций.

**Comment by Eptiy** [comment]
**_Заранее предупреждаю, что приведённые мной способы могут не сработать._**

Недавно был заблокирован cloudflare-ech.com. Начиная с версии 1.5.2 он внесён в список доменов обхода. Т.е. если версия ниже 1.5.2, либо обновляетесь, либо прописываете его вручную.

Также можете попробовать версии 1.5.0 и 1.4.1, некоторым людям это помогло.

Ещё вариант: https://github.com/Flowseal/zapret-discord-youtube/issues/666

**Comment by serpen7** [comment]
> ### Discussed in #252
> ### Приложение работает, но не прогружает иконки серверов, аватары людей и медиа контент (аудио, видео, фото)
> ### Как эта проблема решается?

Это проблема либо в конфликте чего то запретом\дискордом, либо в чем то извне. Извне не решается, проблемы конфликта выявить хотя бы можно как с адгардом или поврежденной установкой\обновой антивирусом. РКН просто вбил палки в колеса потому что банально нельзя теперь нормально говорить о технических ошибках заблокированных сервисов если вы используете обход. Может быть что угодно.

**Comment by serpen7** [comment]
> **Заранее предупреждаю, что приведённый мной способ может не сработать.**
> 
> Недавно был заблокирован cloudflare-ech.com. Начиная с версии 1.5.2 он внесён в список доменов обхода. Т.е. если версия ниже 1.5.2, либо обновляетесь, либо прописываете его вручную.
> 
> Помимо самого обхода блокировки, чтобы получить доступ к ресурсам, расположенным за cloudflare-ech.com, должен работать secure sni. Проверить его работу можно тут: https://www.cloudflare.com/ssl/encrypted-sni/ Если он не работает, нужно настроить DNS-over-HTTPS в браузере, после этого в большинстве случаев работать будет.
> 
> После того, как вы убедились, что secure sni работает, можете проверить медиа в веб-версии дискорда. Если там они заработали, то нужно настроить DNS-over-HTTPS на уровне системы и проверить работу в приложении.
> 
> Если вариант с secure sni не помог, можете попробовать версии 1.5.0 и 1.4.1, некоторым людям это помогло.

тут малость не сходится потому что секюр сни у меня хоть и не работает в браузере при DOH на клаудфларе, однако дискорд без проблем и все более менее пробивает. Зависит наверное от провайдера и параноидальности ТСПУ. У меня уже какой день отваливаются даже прокси в браузере с connection timeout или reset, но при этом работает VPN и все нормально становится. Так же тупо непонятно почему и зачем  бывает просто виснет подруб не к заблокированным сайтам. Даже при вырубе запрета, гудбайдпи, впна и прочего. Тупо таймаут или ресет. Че они там понаделали богу только известно наверное, но это явно как я могу предположить просто "месиво".

**Comment by RedCapcha** [comment]
> **Заранее предупреждаю, что приведённый мной способ может не сработать.**
> 
> Недавно был заблокирован cloudflare-ech.com. Начиная с версии 1.5.2 он внесён в список доменов обхода. Т.е. если версия ниже 1.5.2, либо обновляетесь, либо прописываете его вручную.
> 
> Помимо самого обхода блокировки, чтобы получить доступ к ресурсам, расположенным за cloudflare-ech.com, должен работать secure sni. Проверить его работу можно тут: https://www.cloudflare.com/ssl/encrypted-sni/ Если он не работает, нужно настроить DNS-over-HTTPS в браузере, после этого в большинстве случаев работать будет.
> 
> После того, как вы убедились, что secure sni работает, можете проверить медиа в веб-версии дискорда. Если там они заработали, то нужно настроить DNS-over-HTTPS на уровне системы и проверить работу в приложении.
> 
> Если вариант с secure sni не помог, можете попробовать версии 1.5.0 и 1.4.1, некоторым людям это помогло.

А как Secure SNI настроить?

**Comment by Eptiy** [comment]
> нужно настроить DNS-over-HTTPS

В браузере: https://github.com/Flowseal/zapret-discord-youtube/issues/647#issuecomment-2466699705
В системе: https://github.com/Flowseal/zapret-discord-youtube/issues/647#issuecomment-2466706758

**Comment by Eptiy** [comment]
Вот тут проблема решилась совсем по-другому: https://github.com/Flowseal/zapret-discord-youtube/issues/666

**Comment by RedCapcha** [comment]
> Вот тут проблема решилась совсем по-другому: #666

Добавил в батник --dpi-desync-split-seqovl=652 и всё заработало

**Comment by serpen7** [comment]
> > нужно настроить DNS-over-HTTPS
> 
> В браузере: [#647 (comment)](https://github.com/Flowseal/zapret-discord-youtube/issues/647#issuecomment-2466699705) В системе: [#647 (comment)](https://github.com/Flowseal/zapret-discord-youtube/issues/647#issuecomment-2466706758)

жаль в 10ку не завезли DOH как в 11 винду. Было бы проще.

**Comment by RedCapcha** [comment]
Голосовой подключает, вебку передать не даёт

**Comment by Eptiy** [comment]
> Голосовой подключает, вебку передать не даёт

Это уже совсем другая история.

**Comment by RedCapcha** [comment]
> > Голосовой подключает, вебку передать не даёт
> 
> Это уже совсем другая история.

Вебкамера не была выбрана -_-

**Comment by Eptiy** [comment]
> жаль в 10ку не завезли DOH как в 11 винду. Было бы проще.

Я вообще не понимаю, нужен он в итоге, или нет. На пк медиа грузятся и без него, на ноуте - нет. Подключены к одной сети. Везде медиа не грузились до добавления cloudflare-ech.com. Но доступ к сайтам, которые за ним стоят, по сути должен осуществляться только с рабочим secure sni.

**Comment by serpen7** [comment]
> > жаль в 10ку не завезли DOH как в 11 винду. Было бы проще.
> 
> Я вообще не понимаю, нужен он в итоге, или нет. На пк медиа грузятся и без него, на ноуте - нет. Подключены к одной сети. Везде медиа не грузились до добавления cloudflare-ech.com. Но доступ к сайтам, которые за ним стоят, по сути должен осуществляться только с рабочим secure sni.

В итоге он нужен по идее для всего т.к. это более безопасный способ связи с днс сервером без перехватов запросов. Но  ты должен понимать что кое кому до буя по безопасности в интернете и его пользователей, потому что он не может отслеживать тогда полноценно вещи и делать свою работу. В итоге то что призвано защищать людей служит уязвимостью, блокируя протоколы для защиты обычных людей, улучшающие безопасность.

**Comment by Eptiy** [comment]
Вроде разобрался в итоге. Secure sni не нужен, но нужен TLS1.3, который отваливается, как только убираешь cloudflare-ech.com. Т.е. сейчас для нормальной работы медиа в дс достаточно иметь в списке cloudflare-ech.com, DoH настраивать не надо.

**Comment by flomn1** [comment]
> ### Discussed in [#252](https://github.com/Flowseal/zapret-discord-youtube/discussions/252)
> ### Приложение работает, но не прогружает иконки серверов, аватары людей и медиа контент (аудио, видео, фото)
> ### Как эта проблема решается?

просто не закрывай окно запрета
