### ISSUE TITLE
не удаляется автоматически WinDivert

### ISSUE THREAD

**Issue by B7zvrvysaj** [Flowseal/zapret-discord-youtube#684]
Не снимается процесс после выполнения скрипта от имени администратора "service remove", при удалении директории с данной программе ругается именно на файл, где была установлен был discord zapret, а так же, в cmd пишет ошибку о неудаче остановить этот процесс. Если сделать service install и не обращать внимания на эту ошибку, то все норм, но все же...

**Comment by serpen7** [comment]
а он и не удаляется автоматически, в директории скрипт сервис ремув, который нужно запускать от имени администратора, и нужно смотреть внимательно что скрипт вам выводит прежде чем удалять саму директорию.

**Comment by AlexMagnum1337** [comment]
в терминале винды пишешь следуещее (под админом):
Sc stop windivert
После этого можно удалять WinDivert

**Comment by B7zvrvysaj** [comment]
> а он и не удаляется автоматически, в директории скрипт сервис ремув, который нужно запускать от имени администратора, и нужно смотреть внимательно что скрипт вам выводит прежде чем удалять саму директорию.

так и делал, ошибка связана с service delete, забыл упомянуть

**Comment by B7zvrvysaj** [comment]
> в терминале винды пишешь следуещее (под админом): Sc stop windivert После этого можно удалять WinDivert

не работает на 2х устройствах. ноутбук на windows 10 pro и пк на windows 10 pro

**Comment by Eptiy** [comment]
В чём конкретно ошибка? Service_remove не удаляет сервис? Тогда скрин отработавшего батника в студию.

**Comment by B7zvrvysaj** [comment]
> В чём конкретно ошибка? Service_remove не удаляет сервис? Тогда скрин отработавшего батника в студию.

![изображение](https://github.com/user-attachments/assets/0cef53ca-da9b-4d04-b3a0-a79c76e0b12c)

**Comment by myKiraa** [comment]
Тоже не удаляет..
![image](https://github.com/user-attachments/assets/2b4b7910-292b-4d15-ac70-fcec604d4dfe)

**Comment by myKiraa** [comment]
После запуска файла Service remove - дискорд продолжает работать(

**Comment by myKiraa** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/312#issuecomment-2416745090

Данный метод тоже не помог :(((
Печалька, что нельзя реализовать все 1 файлом, чтоб нормально удалить...А Windows сносить не хочется

**Comment by Eptiy** [comment]
> Тоже не удаляет..

Судя по логам батника, там и нечего удалять. С чего ты взял, что сервис всё ещё установлен? То, что дискорд работает, не значит, что он работает из-за запрета.

**Comment by Eptiy** [comment]
@B7zvrvysaj 
Судя по строчке

> The service is starting or stopping. Please try again later.

Сервис застрял на этапе запуска/отключения. Ты пробовал вручную удалить его, например, из диспетчера задач? Есть ли он вообще там (на вкладке службы) после использования service_remove?

**Comment by johnnyd-78** [comment]
Потому что надо использовать не sc а net - этот пока сервис не остановит, не выйдет.

Если так завис - просто комп перезагружаем и все. Потом удаляем все что надо.

**Comment by myKiraa** [comment]
> > Тоже не удаляет..
> 
> Судя по логам батника, там и нечего удалять. С чего ты взял, что сервис всё ещё установлен? То, что дискорд работает, не значит, что он работает из-за запрета.


Ну у меня дискорд и дальше работают) в мониторе ресурсов WinDivert отсутствует.

**Comment by B7zvrvysaj** [comment]
> @B7zvrvysaj 
> Судя по строчке
> 
> > The service is starting or stopping. Please try again later.
> 
> Сервис застрял на этапе запуска/отключения. Ты пробовал вручную удалить его, например, из диспетчера задач? Есть ли он вообще там (на вкладке службы) после использования service_remove?

пробовал все способы с интернета. решается только перезагрузкой вроде, но это бред. в диспетчере задач не отображается, в sys informer тоже не нашел

**Comment by Eptiy** [comment]
Всякое бывает. Перезагрузка - первое, что я бы попробовал, странно, что ты этого не сделал. Вообще, можно локхантером или любым другим анлокером удалять всю папку в таких случаях.

**Comment by serpen7** [comment]
> > @B7zvrvysaj
> > Судя по строчке
> > > The service is starting or stopping. Please try again later.
> > 
> > 
> > Сервис застрял на этапе запуска/отключения. Ты пробовал вручную удалить его, например, из диспетчера задач? Есть ли он вообще там (на вкладке службы) после использования service_remove?
> 
> пробовал все способы с интернета. решается только перезагрузкой вроде, но это бред. в диспетчере задач не отображается, в sys informer тоже не нашел

Это немножко не бред потому что как я заметил винда почему то блокирует иногда доступ к драйверу, решается только перезагрузкой. С остальным не советую химичить, особенно с правами т.к. разница прав не просто так сделана в ОС. У меня знакомый буквально недавно не мог гудбайдпи вычистить чтобы перейти на запрет. Из батника того же запрета мы поняли что драйвер почему то отказывает в доступе. Перезагруз компа и сервис ремувы уже после перезагрузки с гудбайдпи и запрета потом решили проблему и начисто поставили драйвер снова. Чаще всего я это у людей замечаю почему то на 11 винде. Но и на 10 бывает так что ОС почему то тоже закрывает доступ к драйверу.

**Comment by myKiraa** [comment]
> > > @B7zvrvysaj
> > > Судя по строчке
> > > > The service is starting or stopping. Please try again later.
> > > 
> > > 
> > > Сервис застрял на этапе запуска/отключения. Ты пробовал вручную удалить его, например, из диспетчера задач? Есть ли он вообще там (на вкладке службы) после использования service_remove?
> > 
> > 
> > пробовал все способы с интернета. решается только перезагрузкой вроде, но это бред. в диспетчере задач не отображается, в sys informer тоже не нашел
> 
> Это немножко не бред потому что как я заметил винда почему то блокирует иногда доступ к драйверу, решается только перезагрузкой. С остальным не советую химичить, особенно с правами т.к. разница прав не просто так сделана в ОС. У меня знакомый буквально недавно не мог гудбайдпи вычистить чтобы перейти на запрет. Из батника того же запрета мы поняли что драйвер почему то отказывает в доступе. Перезагруз компа и сервис ремувы уже после перезагрузки с гудбайдпи и запрета потом решили проблему и начисто поставили драйвер снова. Чаще всего я это у людей замечаю почему то на 11 винде. Но и на 10 бывает так что ОС почему то тоже закрывает доступ к драйверу.

В итоге никак не удалить полноценно WinDivert?( Уже все пробовал, батник пишет - отсутствует, но дискорд продолжает работать.

**Comment by serpen7** [comment]
> но дискорд продолжает работать.

да тут может быть и так что это упущение прова или ТСПУ от чего ТСПУ скипает просто трафик так что у тебя и без обходов он "заработал" но надолго ли. 
А так чтобы быть более уверенным в удалении виндайверта 
Качаешь https://github.com/ValdikSS/GoodbyeDPI/releases goodbyedpi-0.2.3rc3-2.zip
Качаешь https://github.com/Flowseal/zapret-discord-youtube/releases zapret-discord-youtube-1.6.1.rar
Все по последним версиям. Разархивируешь оба в отдельные папки. Запускаешь из каждого service_remove батники или смд от имени администратора, где надо нажимать кнопки любые нажимаешь, не обращаешь внимания на ошибки\оповещения. Перезагружаешь комп перезагрузкой обычной. Повторяешь запуск service_remove батника или цмд от имени администратора и по идее все следы виндайверта должны удалится. Даже если ты когда либо ставил гудбайдпи как сервис и забыл об этом.

**Comment by B7zvrvysaj** [comment]
думаю все разобрались что это винда классная, можно закрывать вопрос
