### ISSUE TITLE
Батник не хочет правильно работать.

### ISSUE THREAD

**Issue by Aquarxe** [Flowseal/zapret-discord-youtube#688]
Запускаю в точь точь как по инструкции, батник то запускается, но дискорд ни в какую не хочет запускаться, как будто батника просто не существует, тоже самое у меня было и с гудбай дипиай, уже сколько мучаюсь и перепробовал, ничего вообще не помогает. И если вы думаете, что вот мне нужно подождать пару минут, то вовсе не так, я сидел так 15 минут и в итоге ничего, дискорд так и не запустился. 
![image](https://github.com/user-attachments/assets/cbfb08b8-38ad-438d-8a4f-4a32578cfb77)

**Comment by Eptiy** [comment]
Не подходит конфиг. Пробуй другие батники. Может быть даже так, что ни один не подойдёт.

**Comment by Aquarxe** [comment]
Я уже все перепробовал, и в итоге ничего, понять не могу одного, почему у меня ни один батник не хочет работать, весь интернет перерыл, так и не нашел свою проблему.

**Comment by Eptiy** [comment]
Потому что нет универсального решения для обхода. Никто не даёт гарантий, что у тебя заработает хотя бы с одним из конфигов. Подбирай конфиги сам через блокчек.

**Comment by SpheNay4** [comment]
> Запускаю в точь точь как по инструкции, батник то запускается, но дискорд ни в какую не хочет запускаться, как будто батника просто не существует, тоже самое у меня было и с гудбай дипиай, уже сколько мучаюсь и перепробовал, ничего вообще не помогает. И если вы думаете, что вот мне нужно подождать пару минут, то вовсе не так, я сидел так 15 минут и в итоге ничего, дискорд так и не запустился. ![image](https://private-user-images.githubusercontent.com/184359465/385282765-cbfb08b8-38ad-438d-8a4f-4a32578cfb77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjYxMjQsIm5iZiI6MTczMTQyNTgyNCwicGF0aCI6Ii8xODQzNTk0NjUvMzg1MjgyNzY1LWNiZmIwOGI4LTM4YWQtNDM4ZC04YTRmLTRhMzI1NzhjZmI3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxNTM3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWM4NTk2NTJkMWMxOTQxNGMyNTJhODVhYjBiMzBhMDhhZTU2YTgyYTEwMmU2OTIyM2JjY2Y1MGY3NzlmNjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pLRmXM1lOD7M6jyThreuhx0So-clF744ypDZErWH2kg)

Попробуй файл Updater.exe в свойствах поставить совместимость с Windows 8, у меня было абсолютно также. Работало всё кроме дискорда, со совместимостью заработало, но начало работать немного с багами, если заработает, откати всё обратно, и попробуй запустить, если даст - закрой и удали полностью discord и переустанови его, это же и касается если и не заработает без совместимости. Не забудь потом ещё очистить папку где находиться updater.exe, после удаления. И с нуля с General.bat установи всё, должно помочь.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
