### ISSUE TITLE
не работает service_install

### ISSUE THREAD

**Issue by Zz-Zaikin** [Flowseal/zapret-discord-youtube#695]
все делал по инструкции, но general надо держать открытым чтобы ютуб и дс работали, до обновления 1.6.0 такого не было

запуск general  
![Desktop Screenshot 2024 11 12 - 23 08 56 54](https://github.com/user-attachments/assets/01d73c51-136b-4d70-b5f9-bc1ce440e80c)

запуск service_install
![Desktop Screenshot 2024 11 12 - 23 09 22 44](https://github.com/user-attachments/assets/08d4b175-18a3-4c25-82d0-b76db452221b)
как решить? или так и должно быть?

**Comment by Flowseal** [comment]
Исправно в 1.6.1
