### ISSUE TITLE
ничего не работает 1.6.0

### ISSUE THREAD

**Issue by whyshinee** [Flowseal/zapret-discord-youtube#696]
когда открываю любой батник он сразу закрывается(пробовала запускать и от имени админа, и просто так), в дс написано "checking for updates...", спустя какое то время пишет "Update failed - retrying in 30 sec", и потом снова "checking for updates..." до бесконечности.
ютуб попросту не работает. ранее была версия **1.3.0** на которой все работало, вчера перестало работать, поэтому сначала установила **1.5.2** на которой ничего не работало, и сегодня скачала **1.6.0** опять же ничего не работает

**Comment by De-Os** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/666#issuecomment-2467572759

**Comment by qo4on** [comment]
Попробуйте [это](https://ntc.party/t/ytdisbystro-%D0%B0%D1%80%D1%85%D0%B8%D0%B2-%D0%B2%D1%81%D0%B5%D1%85-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B9/12582/31)

**Comment by whyshinee** [comment]
> Попробуйте [это](https://ntc.party/t/ytdisbystro-%D0%B0%D1%80%D1%85%D0%B8%D0%B2-%D0%B2%D1%81%D0%B5%D1%85-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B9/12582/31)

спасибо большое, теперь все прекрасно работает! <3
