### ISSUE TITLE
Проблема с батниками

### ISSUE THREAD

**Issue by vmpjnk** [Flowseal/zapret-discord-youtube#698]
После переустановки винды и обновления Запрета (хз в чем вина) сломались батники. С чека апдейтов, до всех general - автоматически крашится. При запуске автозагрузчика - окно перезагружается и дает выбрать батник, который нужно поставить на загрузку, а после проблема. 
![image](https://github.com/user-attachments/assets/f40e3ebb-3e5d-4e76-a7d2-9af0f83a75bc)
А в удалении вот так - 
![image](https://github.com/user-attachments/assets/30b55eb4-d577-46ab-b73d-b37e4d11c561)
Если кто-то знает в чем может быть беда - сильно выручите

**Comment by Eptiy** [comment]
Судя по логам установочника, служба успешно установилась. Причём, она именно обновилась, потому что сначала идёт строчка

>  DeleteService SUCCESS

В чём заключается проблема на данном этапе, я не понимаю.

По логам удаления видно, что ремув не нашёл службу, значит, её во время удаления уже не было.

То, что батники крашатся, скорее всего связано  с наличием установленной службы, т.к. батник и служба - взаимоисключающие.

Я не понимаю, проблема в итоге какая? Если ты устанавливаешь службу и обход работает, то всё нормально.

**Comment by vmpjnk** [comment]
Меня смущает:
1. консолька не предлагает мне закрыть ее(из-за чего я думаю, что процесс не завершен)
2. когда я вписываю сайты в general-list - они все так же недоступны (саундклауд)(после перезагрузки тоже)
я попробовал на старой версии Запрета и консоль и general-list работают.

**Comment by Eptiy** [comment]
1. Консоль не закрывается именно для того, чтобы в случае проблем можно было посмотреть её логи и сделать хоть какие-то выводы. После того, как служба установлена, можно её закрывать. Если пользуешься батником, а не службой, очевидно, закрывать не нужно.

2. Во-первых, не всегда достаточно одного домена, чтобы получить доступ ко всему ресурсу. У того же саундклауда есть свой cdn, без доступа к которому он работать не будет. Плюс, нужно в правильные листы писать. Я точно не помню, сколько их всего и какие батники какие листы используют, можешь сам посмотреть в коде батников. Ещё стоит понимать, что этот билд создан для обхода блокировок дс и ют. Никто не даёт гарантий, что он будет обходить блокировки вообще всех ресурсов.


По поводу доменов:
Вот тут можно найти большинство доменов популярных ресурсов: https://github.com/v2fly/domain-list-community/tree/master/data
А вот тут есть готовый лист заблокированрых в рф доменов: https://github.com/1andrevich/Re-filter-lists
