### ISSUE TITLE
Не работает дискорд

### ISSUE THREAD

**Issue by andscoodey** [Flowseal/zapret-discord-youtube#699]
Не грузит дискорд после запуска любого батника. Скачана самая новая версия
В кмд пишет
_______________________

we have 3 user defined desync profile(s) and default low priority profile 0
Loading hostlist list-discord.txt
loading plain text list
Loaded 19 hosts from list-discord.txt
Loading hostlist list-discord.txt
loading plain text list
Loaded 19 hosts from list-discord.txt
Loading ipset ipset-discord.txt
loading plain text list
Loaded 721 ip/subnets from ipset-discord.txt
windivert initialized. capture is started.

__________________________

Старые версии удалял также через батник

**Comment by Flowseal** [comment]
Судя по логам, обход работает. Если дисокрд не запускается - https://github.com/Flowseal/zapret-discord-youtube/discussions/252
