### ISSUE TITLE
добавить поддержку макось / линукс

### ISSUE THREAD

**Issue by zondaxxx** [Flowseal/zapret-discord-youtube#7]
прога которую используешь есть для релиза на мак или линукс
это сильно востребовано для множества пользователей

**Comment by gg3n3** [comment]
+1 было бы здорово получить сборку под Linux, ну или гайд как исходный вариант под него собрать

**Comment by Flowseal** [comment]
Дока zapret для linux:
https://github.com/bol-van/zapret/blob/master/docs/quick_start.txt

Рабочий конфиг для линукс:
https://github.com/bol-van/zapret/issues/455#issuecomment-2400501645

**Comment by zondaxxx** [comment]
на линукс хорошо, на мак есть?

**Comment by kartavkun** [comment]
Я портировал на Линуху конфиги Флоусила и сделал простую установку, если интересно

https://github.com/kartavkun/zapret-discord-youtube
