### ISSUE TITLE
Не запускается Call of Duty: Warzone из-за программы.

### ISSUE THREAD

**Issue by nikita9091239** [Flowseal/zapret-discord-youtube#701]
Вчера я искал способы запустить игру, но она не запускалась, выбивала безопасный режим и мгновенно закрывалась. Помогло только отключение данной программы, без этого я не мог запустить её никакими способами.

**Comment by Eptiy** [comment]
Чекнул бы другие ишью для начала

https://github.com/Flowseal/zapret-discord-youtube/issues/124#issuecomment-2404737282 https://github.com/Flowseal/zapret-discord-youtube/issues/344#issuecomment-2422171348
