### ISSUE TITLE
Ошибка запуска windows10, cygwin1.dll

### ISSUE THREAD

**Issue by LinearBasis** [Flowseal/zapret-discord-youtube#702]
С какого-то рандомного (с моей точки зрения) момента перестало  запускаться, вылезает это окно. Ошибка вылезает на винде, так что на #7 прошу не ссылаться
![image](https://github.com/user-attachments/assets/cdeaeeba-7116-4969-9f7b-0035976c196f)

**Comment by Eptiy** [comment]
Написано, что не хватает файла, значит, его что-то удалило. Скорее всего, антивирус. Добавляй папку в исключения и возвращай файл из карантина, либо заново закидывай из архива.
