### ISSUE TITLE
Discord не грузит видео (только вместе с goodbyedpi)

### ISSUE THREAD

**Issue by MotaRin** [Flowseal/zapret-discord-youtube#704]
Discord не грузит видео, использую сервис от goodbyedpi и совместно с service_goodbye_discord.bat

Не грузит видео и иногда не отображаются корректно аватарки, только если убрать оба сервиса и запустить service_install.bat и выбрать discord.bat то все видео загружаются. Обновлял также до 1.6.1 то есть cloudflare-ech.com в обоих файлах выставлен, в чем корректно проблема и можно ли исправить?

**Comment by Eptiy** [comment]
Выглядит, как конфликт с гудбаем. Попробуй из его листов убрать всё, что связано с дс.

**Comment by MotaRin** [comment]
> Выглядит, как конфликт с гудбаем. Попробуй из его листов убрать всё, что связано с дс.

Помогло, достаточно было убрать сервисы и через гудбай обновив 0_russia_update_blacklist_file.cmd, также запустить по новой
