### ISSUE TITLE
Ошибка Skipping the update check because it hasnt benn 6 hours

### ISSUE THREAD

**Issue by salatik09** [Flowseal/zapret-discord-youtube#705]
![2024-11-13_18-47-11](https://github.com/user-attachments/assets/a996b197-002b-4dbe-815f-655c646d0822)

**Comment by serpen7** [comment]
вам антивирус снес файл программы.

**Comment by Flowseal** [comment]
Не может найти файл - либо распоковали неправильно, либо съел антивирус файлы
