### ISSUE TITLE
Может ли обойти блок JetBrains

### ISSUE THREAD

**Issue by DGDarkKing** [Flowseal/zapret-discord-youtube#706]
Пользуюсь некоторыми IDE от JetBrains и понадобилось поставить/обновить плагины, но блочит по региону "We are sorry, but we are currently unable to provide our products or services to you due to export control regulations."
Может ли запрет обойти этот блок.
Если может, то дайте пожалуйста все возможные их адреса/домены

**Comment by Flowseal** [comment]
Нет

**Comment by Serega007RU** [comment]
JetBrains блокирует именно по IP, только VPN тут поможет

**Comment by RealVegas** [comment]
PsiPhone 3 (VPN) не помогает. Если PyCharm интересует, то только с сайта JetBrains. WebStrom через VPN нормально плагины обновляет. Насчет PyCharm подробнее: Включаете VPN регистрируетесь на сайте JetBrains (я через аккаунт GitHub, потому что там нет намеков на то что я from Russia) В PyCharm y каждого плагина на вкладке описания есть ссылка homepage. Она ведёт на сайт JetBrains (туда только с включенным VPN) откуда можно выкачать плагины. Потом выключаете Интернет и install from disk. Если не срабатывает, то распаковываете и идете в C:\Users\<Имя Пользователя>\AppData\Roaming\JetBrains\ PyCharmCE2024.3\plugins (PyCharmCE2024.3 - будет написана ваша версия IDE) там стираете старую версию и копируете свежераспакованный plugin. Все будет работать. По другим IDE не подскажу, но думаю схема схожая.

**Comment by MVP2024** [comment]
Всем привет) полгода назад, через VPN всё установил. Сейчас залил на ноут и с VPN и с отключенным местоположением, всё равно парочку скачает, а после фиг) Буду искать, как решить проблему)

**Comment by i5anin** [comment]
Установить [AdGuard VPN](https://adguard-vpn.com/ru/welcome.html)

**Comment by Serega007RU** [comment]
> Установить [AdGuard VPN](https://adguard-vpn.com/ru/welcome.html)

не работает ссылка, какой смысл от VPN который заблокирован в России?

![Image](https://github.com/user-attachments/assets/a49e53d5-2e63-4f4c-a5bb-239dc60ce97b)

**Comment by akellavk** [comment]
> Кому нужно, можно по некоторым адресам поставить перенаправление трафика. 

Поставил DNS Yoga (не реклама) и Comss; указал правило на вышеперечисленные домены, теперь можно спокойно качать плагины и т.д.

**Comment by H1K5ik** [comment]
> Кому нужно, можно по некоторым адресам поставить перенаправление трафика. Домены вроде: download.jetbrains.com и plugins.jetbrains.com поставить и все будет ок. А что насчет CDN ? Ну тут все просто. Оно перенаправит на download-cdn.jetbrains.com если загружать их софт, а обновление плагинов для Ultimate версий (возможно уже и Community) - это downloads.marketplace.jetbrains.com Не благодарите! Если нужен список побольше - вот, вроде как можно фильтровать их все: account.jetbrains.com analytics.services.jetbrains.com api.jetbrains.ai source.jetbrains.space assets.jetbrains.space assets.source.jetbrains.space cache-redirector.jetbrains.com cloudconfig.jetbrains.com code-with-me.global.jetbrains.com code-with-me.jetbrains.com download.jetbrains.com download-cdn.jetbrains.com downloads.marketplace.jetbrains.com d3kdv2x2np28ys.cloudfront.net ea.jetbrains.com ijhttp-examples.jetbrains.com eu.region.myjetbrains.com us.region.myjetbrains.com region.myjetbrains.com youtrack.youtrack.cloud instancename.myjetbrains.com instancename.youtrack.cloud intellij.com intellij.net intellij.org intellij-support.jetbrains.com jbsintellij.zendesk.com jbs.zendesk.com jetbrains.ai jetbrains.com jetbrains.com.cn jetbrains.dev jetbrains.net jetbrains.org jetbrains.ru jetbrains.team kotl.in kotlinconf.com kotlinlang.org lp.jetbrains.com marketplace.jetbrains.com myjetbrains.com plugins.jetbrains.com jbsresharper.zendesk.com resharper-support.jetbrains.com restricted-page.jetbrains.space jbssales.zendesk.com sales.jetbrains.com status.jetbrains.com support.jetbrains.com talkingkotlin.com hub-production.pub.aws.intellij.net hub-green-production.pub.aws.intellij.net hub.jetbrains.com hub.zendesk.com hub-support.jetbrains.com datalore.jetbrains.com jbsdatalore.zendesk.com datalore-support.jetbrains.com youtrack.cloud youtrack-production.pub.aws.intellij.net youtrack-green-production.pub.aws.intellij.net youtrack.jetbrains.com jbsyoutrack.zendesk.com youtrack-support.jetbrains.com upsource.jetbrains.com jbsupsource.zendesk.com upsource-support.jetbrains.com teamcity.com teamcity.jetbrains.com jbsteamcity.zendesk.com teamcity-support.jetbrains.com fleet.jetbrains.com academy.jetbrains.com mkto-lon020062.com go.jetbrains.com blog.jetbrains.com jetbrainsmerchandise.com 62f177041d4d716d60bb7c96.cname.vantatrust.com trust-center.jetbrains.com k8s-ingressn-ingressn-79b8dff5ea-a8ee4431a9f785a2.elb.eu-west-1.amazonaws.com buildserver.labs.intellij.net internal-authentication.intellij.net confluence.jetbrains.com production.cache-redirector.aws.intellij.net package-search.services.jetbrains.com api.prod.package-search.services.jetbrains.com eu-north-1-prd-api-1888805958.eu-north-1.elb.amazonaws.com data.services.jetbrains.com data-srv.prod-eu.w3jbcom.aws.intellij.net frameworks.jetbrains.com d1gyz2dzs4t2p.cloudfront.net index-cdn.jetbrains.com intuit.fls.jetbrains.com intuit.oauth.fls.jetbrains.com oauth.account.jetbrains.com prod-oauth-public-alb-939786626.eu-west-1.elb.amazonaws.com oauth.fls.jetbrains.com resharper-plugins.jetbrains.com resources.jetbrains.com [www.jetbrains.com](http://www.jetbrains.com) packages.jetbrains.team d1do0znm134sif.cloudfront.net kmp.jetbrains.com

Спасибо бро

**Comment by P1xart** [comment]
> Посмотрите решение у данного [автора](https://github.com/V3nilla/IPSets-For-Bypass-in-Russia/blob/main/%D0%A0%D0%B0%D0%B7%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0%20%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B0%20%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D0%BE%D0%B2(%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20-%20ChatGPT)/hosts). У меня работает и не нужно даже VPN ставить. В крацте, просто добавьте в C:\Windows\System32\drivers\etc\hosts файл это: 185.87.51.182 datalore.jetbrains.com 185.87.51.182 plugins.jetbrains.com 185.87.51.182 download.jetbrains.com 185.87.51.182 api.jetbrains.ai 185.87.51.182 account.jetbrains.com Интересно, что у кого-то все еще что-то да не работает...

Спасибо бро

**Comment by ArtemAlexin** [comment]
> > Кому нужно, можно по некоторым адресам поставить перенаправление трафика. Домены вроде: download.jetbrains.com и plugins.jetbrains.com поставить и все будет ок. А что насчет CDN ? Ну тут все просто. Оно перенаправит на download-cdn.jetbrains.com если загружать их софт, а обновление плагинов для Ultimate версий (возможно уже и Community) - это downloads.marketplace.jetbrains.com Не благодарите! Если нужен список побольше - вот, вроде как можно фильтровать их все: account.jetbrains.com analytics.services.jetbrains.com api.jetbrains.ai source.jetbrains.space assets.jetbrains.space assets.source.jetbrains.space cache-redirector.jetbrains.com cloudconfig.jetbrains.com code-with-me.global.jetbrains.com code-with-me.jetbrains.com download.jetbrains.com download-cdn.jetbrains.com downloads.marketplace.jetbrains.com d3kdv2x2np28ys.cloudfront.net ea.jetbrains.com ijhttp-examples.jetbrains.com eu.region.myjetbrains.com us.region.myjetbrains.com region.myjetbrains.com youtrack.youtrack.cloud instancename.myjetbrains.com instancename.youtrack.cloud intellij.com intellij.net intellij.org intellij-support.jetbrains.com jbsintellij.zendesk.com jbs.zendesk.com jetbrains.ai jetbrains.com jetbrains.com.cn jetbrains.dev jetbrains.net jetbrains.org jetbrains.ru jetbrains.team kotl.in kotlinconf.com kotlinlang.org lp.jetbrains.com marketplace.jetbrains.com myjetbrains.com plugins.jetbrains.com jbsresharper.zendesk.com resharper-support.jetbrains.com restricted-page.jetbrains.space jbssales.zendesk.com sales.jetbrains.com status.jetbrains.com support.jetbrains.com talkingkotlin.com hub-production.pub.aws.intellij.net hub-green-production.pub.aws.intellij.net hub.jetbrains.com hub.zendesk.com hub-support.jetbrains.com datalore.jetbrains.com jbsdatalore.zendesk.com datalore-support.jetbrains.com youtrack.cloud youtrack-production.pub.aws.intellij.net youtrack-green-production.pub.aws.intellij.net youtrack.jetbrains.com jbsyoutrack.zendesk.com youtrack-support.jetbrains.com upsource.jetbrains.com jbsupsource.zendesk.com upsource-support.jetbrains.com teamcity.com teamcity.jetbrains.com jbsteamcity.zendesk.com teamcity-support.jetbrains.com fleet.jetbrains.com academy.jetbrains.com mkto-lon020062.com go.jetbrains.com blog.jetbrains.com jetbrainsmerchandise.com 62f177041d4d716d60bb7c96.cname.vantatrust.com trust-center.jetbrains.com k8s-ingressn-ingressn-79b8dff5ea-a8ee4431a9f785a2.elb.eu-west-1.amazonaws.com buildserver.labs.intellij.net internal-authentication.intellij.net confluence.jetbrains.com production.cache-redirector.aws.intellij.net package-search.services.jetbrains.com api.prod.package-search.services.jetbrains.com eu-north-1-prd-api-1888805958.eu-north-1.elb.amazonaws.com data.services.jetbrains.com data-srv.prod-eu.w3jbcom.aws.intellij.net frameworks.jetbrains.com d1gyz2dzs4t2p.cloudfront.net index-cdn.jetbrains.com intuit.fls.jetbrains.com intuit.oauth.fls.jetbrains.com oauth.account.jetbrains.com prod-oauth-public-alb-939786626.eu-west-1.elb.amazonaws.com oauth.fls.jetbrains.com resharper-plugins.jetbrains.com resources.jetbrains.com [www.jetbrains.com](http://www.jetbrains.com) packages.jetbrains.team d1do0znm134sif.cloudfront.net kmp.jetbrains.com
> 
> Мне не помогло. Чего-то не хватает..

Добавь
*.cloudfront.net

**Comment by fluffydaddy** [comment]
Адреса также поменялись, но можно добавить к старым так как есть шанс на "успех".
77.239.114.0 datalore.jetbrains.com
77.239.114.0 plugins.jetbrains.com
77.239.114.0 download.jetbrains.com
77.239.114.0 api.jetbrains.ai
77.239.114.0 account.jetbrains.com

**Comment by fluffydaddy** [comment]
> > > Кому нужно, можно по некоторым адресам поставить перенаправление трафика. Домены вроде: download.jetbrains.com и plugins.jetbrains.com поставить и все будет ок. А что насчет CDN ? Ну тут все просто. Оно перенаправит на download-cdn.jetbrains.com если загружать их софт, а обновление плагинов для Ultimate версий (возможно уже и Community) - это downloads.marketplace.jetbrains.com Не благодарите! Если нужен список побольше - вот, вроде как можно фильтровать их все: account.jetbrains.com analytics.services.jetbrains.com api.jetbrains.ai source.jetbrains.space assets.jetbrains.space assets.source.jetbrains.space cache-redirector.jetbrains.com cloudconfig.jetbrains.com code-with-me.global.jetbrains.com code-with-me.jetbrains.com download.jetbrains.com download-cdn.jetbrains.com downloads.marketplace.jetbrains.com d3kdv2x2np28ys.cloudfront.net ea.jetbrains.com ijhttp-examples.jetbrains.com eu.region.myjetbrains.com us.region.myjetbrains.com region.myjetbrains.com youtrack.youtrack.cloud instancename.myjetbrains.com instancename.youtrack.cloud intellij.com intellij.net intellij.org intellij-support.jetbrains.com jbsintellij.zendesk.com jbs.zendesk.com jetbrains.ai jetbrains.com jetbrains.com.cn jetbrains.dev jetbrains.net jetbrains.org jetbrains.ru jetbrains.team kotl.in kotlinconf.com kotlinlang.org lp.jetbrains.com marketplace.jetbrains.com myjetbrains.com plugins.jetbrains.com jbsresharper.zendesk.com resharper-support.jetbrains.com restricted-page.jetbrains.space jbssales.zendesk.com sales.jetbrains.com status.jetbrains.com support.jetbrains.com talkingkotlin.com hub-production.pub.aws.intellij.net hub-green-production.pub.aws.intellij.net hub.jetbrains.com hub.zendesk.com hub-support.jetbrains.com datalore.jetbrains.com jbsdatalore.zendesk.com datalore-support.jetbrains.com youtrack.cloud youtrack-production.pub.aws.intellij.net youtrack-green-production.pub.aws.intellij.net youtrack.jetbrains.com jbsyoutrack.zendesk.com youtrack-support.jetbrains.com upsource.jetbrains.com jbsupsource.zendesk.com upsource-support.jetbrains.com teamcity.com teamcity.jetbrains.com jbsteamcity.zendesk.com teamcity-support.jetbrains.com fleet.jetbrains.com academy.jetbrains.com mkto-lon020062.com go.jetbrains.com blog.jetbrains.com jetbrainsmerchandise.com 62f177041d4d716d60bb7c96.cname.vantatrust.com trust-center.jetbrains.com k8s-ingressn-ingressn-79b8dff5ea-a8ee4431a9f785a2.elb.eu-west-1.amazonaws.com buildserver.labs.intellij.net internal-authentication.intellij.net confluence.jetbrains.com production.cache-redirector.aws.intellij.net package-search.services.jetbrains.com api.prod.package-search.services.jetbrains.com eu-north-1-prd-api-1888805958.eu-north-1.elb.amazonaws.com data.services.jetbrains.com data-srv.prod-eu.w3jbcom.aws.intellij.net frameworks.jetbrains.com d1gyz2dzs4t2p.cloudfront.net index-cdn.jetbrains.com intuit.fls.jetbrains.com intuit.oauth.fls.jetbrains.com oauth.account.jetbrains.com prod-oauth-public-alb-939786626.eu-west-1.elb.amazonaws.com oauth.fls.jetbrains.com resharper-plugins.jetbrains.com resources.jetbrains.com [www.jetbrains.com](http://www.jetbrains.com) packages.jetbrains.team d1do0znm134sif.cloudfront.net kmp.jetbrains.com
> > 
> > 
> > Мне не помогло. Чего-то не хватает..
> 
> Добавь *.cloudfront.net

Не совсем правильно. Но для раздельного тунеля хватит думаю.

**Comment by fluffydaddy** [comment]
Если у вас что-то оъебнуло - пожалуйста, вам сюда [dns.malw.link/hosts](https://github.com/ImMALWARE/dns.malw.link/blob/master/hosts)
Так же если пройтись по этому хосту можно и гпт, гемини, спотик и другие сервисы разблокать.

**Comment by Padawan6233** [comment]
> Если у вас что-то оъебнуло - пожалуйста, вам сюда [dns.malw.link/hosts](https://github.com/ImMALWARE/dns.malw.link/blob/master/hosts) Так же если пройтись по этому хосту можно и гпт, гемини, спотик и другие сервисы разблокать.

Ты просто гений!) Спасибо за ссылку. +100 к карме тебе!

Разблочил ограничения в продуктах jetbrains (а именно datagrip). Инструкция, чтобы точно заработало:
1. Добавить актуальные адреса в файл hosts
2. В самом приложении от jetbrains выключить использование прокси. Это обязательный пункт
3. С кайфом работать

Правда не знаю как долго продержится) Только сделал себе

**Comment by fluffyuncle** [comment]
Нормально так? Знаю не сюда пишу, но видать мой аккаунт либо украли, либо заблокировали по непонятной мне причине. (Это я fluffydaddy)
Скорее всего 50/50
Я уже замечал странности моего аккаунта, но видимо уже было поздно. А на почту ничего понятно не приходило. Может показаться странным, но у меня было много репозиториев, даже полезных, и много скрытых. И вот я потерял доступ :/

**Comment by fluffyuncle** [comment]
> Нормально так? Знаю не сюда пишу, но видать мой аккаунт либо украли, либо заблокировали по непонятной мне причине. (Это я fluffydaddy) Скорее всего 50/50 Я уже замечал странности моего аккаунта, но видимо уже было поздно. А на почту ничего понятно не приходило. Может показаться странным, но у меня было много репозиториев, даже полезных, и много скрытых. И вот я потерял доступ :/

Может кто сталкивался с таким и может помочь?

**Comment by Nosnitrous1** [comment]
Сочувствую

Я сейчас занимаюсь PTC (pay-to-clcick).
Для этого посещаю несколько платящих за клики сайтов. Так вот, один из них (seoklyb.biz) вскрыли "враги" хакеры. И сейчас сообщение висит соответствующее. И мой аккаунт с 100 рублями заработка, исчез. Не бывает всё хорошо...

Успехов

--
Отправлено из Mail ( https://mail.ru/ ) для Android

среда, 17 июня 2026г., 00:42 +03:00 от fluffyuncle ***@***.*** :
