### ISSUE TITLE
детектид как вирус

### ISSUE THREAD

**Issue by pashamacho2010** [Flowseal/zapret-discord-youtube#707]
хотел скачать новую версию а там ВИРУС говорит

**Comment by DGDarkKing** [comment]
Аналогично, я смог обновиться только с 1.3 до 1.4,0
их браузер спокойно даёт скачать, вероятно, поскольку они подтверждены гитхабом - зеленная галочка (This commit was created on GitHub.com and signed with GitHub’s verified signature.)
В принципе, источник доверенный, так что можно попробовать обойти детектор браузера или скачать через утилиты (сам через утилиты не качал релизы, но вот решение на винду https://dzen.ru/a/ZCawjUVpmFdhwq6Y)

**Comment by Flowseal** [comment]
Читайте README
