### ISSUE TITLE
Не дало скачать, типа вирусы

### ISSUE THREAD

**Issue by toorboomflex** [Flowseal/zapret-discord-youtube#712]
![изображение_2024-11-14_014825593](https://github.com/user-attachments/assets/3c4084cb-fd1e-47a4-9a39-4b343d871bc2)

Еще странная тема, внезапно заиграло музло какое-то, очень громко, через пару секунд само вырубилось, играть ему неоткуда было

**Comment by toorboomflex** [comment]
Почитал про троян, окей антивирус с ума сходит. А музло то откуда взялось и куда делось? Есть идеи?

**Comment by Flowseal** [comment]
![image](https://github.com/user-attachments/assets/fbf236eb-15ea-46be-bba2-a4cab3ad3a86)

**Comment by toorboomflex** [comment]
лан пох, скачал, нормально работает, спасибо разрабу. че с музлом так и не понял, крысы наверно
