### ISSUE TITLE
Высокий пинг в голосовом канале

### ISSUE THREAD

**Issue by someone345** [Flowseal/zapret-discord-youtube#713]
Периодически подскакивает пинг до 5000 в войс чате, помогает только ребут.

**Comment by serpen7** [comment]
ребут компа, дискорда или запрета и на сколько помогает?

**Comment by Eptiy** [comment]
И какой сервер в голосовом установлен?

У меня была ситуация пару раз на russia, что взлетал пинг до максимума, решалась перезаходом в голосовой.

**Comment by someone345** [comment]
> ребут компа, дискорда или запрета и на сколько помогает?

на минут 5-10 хватает, ребут дискорда, компа соответственно тоже

**Comment by someone345** [comment]
> И какой сервер в голосовом установлен?
> 
> У меня была ситуация пару раз на russia, что взлетал пинг до максимума, решалась перезаходом в голосовой.

в каждом голосовом такая проблема как я понял

**Comment by MaidLine** [comment]
У меня аналогичная проблема

**Comment by Eptiy** [comment]
Проверьте, проходит ли проблема при использовании впн вместо запрета.

**Comment by serpen7** [comment]
> > И какой сервер в голосовом установлен?
> > У меня была ситуация пару раз на russia, что взлетал пинг до максимума, решалась перезаходом в голосовой.
> 
> в каждом голосовом такая проблема как я понял

Это провайдер. Если бы вам не помогало просто закрытие и открытие дискорда то тогда бы еще можно было чето думать на фильтр. Если помогает и вам пробрасывает новый маршрут и у вас какое то время на нем все тоже впорядке - то это провайдер. Может конечно и ТСПУ задерживать пакеты и почему то триггерится, но он бы это делал куда чаще думаю. Какой конфиг используете? Не пробовали на других конфигах посидеть?

**Comment by Eptiy** [comment]
4 года назад подобная проблема массово была у людей, тогда им помогло изменение днс на клаудфлэйровский или гугловский.

**Comment by emp04ka** [comment]
> 4 года назад подобная проблема массово была у людей, тогда им помогло изменение днс на клаудфлэйровский или гугловский.

Не помогло, в моём случае стало только хуже

**Comment by Eptiy** [comment]
> Не помогло, в моём случае стало только хуже

Впн пробовал?

**Comment by emp04ka** [comment]
> > Не помогло, в моём случае стало только хуже
> 
> Впн пробовал?

Я ламер, не знаю нормальных фри впнов

**Comment by Eptiy** [comment]
попробуй betternet

Просто нужно выяснить, дело в запрете, или нет. А то так можно вечно гадать, а дело окажется в настройках роутера, например.

**Comment by Eptiy** [comment]
@emp04ka  А, этот тред тебя не касается, тут у людей взлетает 5000 пинга и висит мертвяком.

**Comment by emp04ka** [comment]
> @emp04ka А, этот тред тебя не касается, тут у людей взлетает 5000 пинга и висит мертвяком.

У меня такая же проблема появилось, заметил только сейчас

**Comment by emp04ka** [comment]
@Eptiy Посоветуй впн, я трайну сейчас

**Comment by Eptiy** [comment]
https://app.betternet.co/

**Comment by emp04ka** [comment]
> https://app.betternet.co/
к этому впну меня вообще не подключает))00)

**Comment by emp04ka** [comment]
> https://app.betternet.co/

К этому впну меня вообще не подключает))0))

**Comment by Eptiy** [comment]
Меня тоже, давно не пользовался, мб прикрыли. У меня нет впнов на примете.

**Comment by emp04ka** [comment]
@someone345 Какой у тебя провайдер? Где живёшь?

**Comment by Awuushy** [comment]
Аналогичный трабл, провайдер ростелеком(

**Comment by someone345** [comment]
В общем, помогло поменять сервер голосового чата с русского на любой другой (там автоматически устанавливается от того, кто первый зашел в канал вроде бы). Можете попробовать перекидывать сервера с автоматического на любой другой кроме русского.
У еще одного знакомого такая же проблема, помогла

**Comment by emp04ka** [comment]
А это точно решение, а не костыль?

**Comment by Eptiy** [comment]
50/50, У нас сейчас вообще на всех серваках стоит авто, где выбирается финляндия. Там пинг стабильно на 50мс ниже, проблем подобных нет. Мб ркн просто пошёл с вилами и факелами на сервера дискорда в рф?

**Comment by emp04ka** [comment]
> 50/50, У нас сейчас вообще на всех серваках стоит авто, где выбирается финляндия. Там пинг стабильно на 50мс ниже, проблем подобных нет. Мб ркн просто пошёл с вилами и факелами на сервера дискорда в рф?

Я бы с радостью принял это за решение, если бы не жил в заднице мира, где серверов удобных нет для использования. На ближайшем роттердаме у меня потеря пакетов, которая достигает 25.
