### ISSUE TITLE
Будет ли батник обновляться под будущие блокировки?

### ISSUE THREAD

**Issue by MishaNYA12** [Flowseal/zapret-discord-youtube#714]
С огромной вероятностью у нас забанят и твич (вопрос лишь в том когда) а за ним и много чего еще. Планируется ли обновление батника под обход новых банов и будет ли это в целом реалезуемо?

**Comment by serpen7** [comment]
Вы и сами можете вносить правки в листы и конфиги так же. Если вам забанят весь интернет то запрет или гудбайдпи не сработает особо в этих условиях т.к. фильтроваться будет куча всего и не единожды. А если это случится то либо будут адские задержки, либо иннет ляжет. Не паникуйте и не паранойте. Вы всегда сможете пока иннет в целом не забанили найти что прописать в листах или что поделать. Обнова автоматом мало имеет смысла т.к. её могут заблокировать очень легко. Да и плюс учитывать что у кого заблокировали и кто чем пользуется собирать информацию тоже сомнительная перспектива лопатить чуть ли не все подряд, притом что есть сбои, ошибки маршрутизаций и прочего, и это не блокировки.

**Comment by Flowseal** [comment]
Точечно разблокировать сервис по просьбе каждого - нет.
Популярные сервисы (вроде ютуба, дискорда) - да. Твитч туда же.

**Comment by MishaNYA12** [comment]
Спасибо зв ответ
