### ISSUE TITLE
Skipping the update check because it hasnt been 6 hours 

### ISSUE THREAD

**Issue by SkibidiGoon** [Flowseal/zapret-discord-youtube#715]
я понял что ошибка вылезала из за того что касперский съел файлы, удалил его, но ошибка все равно вылазит, что делать?

**Comment by Eptiy** [comment]
В чём ошибка-то?

> Skipping the update check because it hasnt been 6 hours

Вот это не ошибка.

**Comment by serpen7** [comment]
> я понял что ошибка вылезала из за того что касперский съел файлы, удалил его, но ошибка все равно вылазит, что делать?

Зачем удалять или отрубать антивирусы? Почему просто папку не занести в исключения, а подвергать комп риску быть зараженным? Если каспер съел файлы то вам нужно их перекачивать, если их не восстановить из карантина или вы этого не сделали. Главное чтобы вы не качали запрет незнамо от кого из интернета чтобы реально не схватить вирусню. Потому что фейковые сборки запрета с вирусней довольно даже хорошо окупировали ютуб. И ютуб не спешит удалять видео и каналы таких людей по жалобам от людей.

**Comment by paqpiiiah** [comment]
Skipping the update check because it hasnt been 6 hours 
!!!!это не ошибка.!!!!!
перевод: проверка обновления пропущена так как прошло меньше 6 часов после предыдущей.

**Comment by zebraffinnn17** [comment]
у меня тоже самое, хоть и антивирус отключен и ничего не сьедал, не знаю, что делать.

**Comment by Eptiy** [comment]
Что 'то же самое'? Можешь нормально объяснить, в чём проблема? Надпись в названии треда - это не ошибка.

**Comment by serpen7** [comment]
> у меня тоже самое, хоть и антивирус отключен и ничего не сьедал, не знаю, что делать.

можно скриншот ошибки с  папочкой запрета на виду?

**Comment by SkibidiGoon** [comment]
> > у меня тоже самое, хоть и антивирус отключен и ничего не сьедал, не знаю, что делать.
> 
> можно скриншот ошибки с папочкой запрета на виду?
![Скриншот-14-11-2024 10_44_56](https://github.com/user-attachments/assets/9d8b29bd-f1db-468a-b3a3-9ef86e0e4bf6)

**Comment by Eptiy** [comment]
Проверьте версии до 1.6.0, там нет автоапдейтера, на этапе которого виснет батник.

**Comment by SkibidiGoon** [comment]
> Проверьте версии до 1.6.0, там нет автоапдейтера, на этапе которого виснет батник.

щас проверил 1.4.1, она просто без ошибки закрывается

**Comment by Eptiy** [comment]
Закрывается батник или сервис инсталл?

**Comment by Eptiy** [comment]
Если батник, значит, вы не удалили с предыдущей версии сервис.

**Comment by serpen7** [comment]
> > > у меня тоже самое, хоть и антивирус отключен и ничего не сьедал, не знаю, что делать.
> > 
> > 
> > можно скриншот ошибки с папочкой запрета на виду?
> > ![Скриншот-14-11-2024 10_44_56](https://private-user-images.githubusercontent.com/188412411/386160550-9d8b29bd-f1db-468a-b3a3-9ef86e0e4bf6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODIyMTMsIm5iZiI6MTczMTU4MTkxMywicGF0aCI6Ii8xODg0MTI0MTEvMzg2MTYwNTUwLTlkOGIyOWJkLWYxZGItNDY4YS1iM2EzLTllZjg2ZTBlNGJmNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMDU4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYThkZjBjNzFjMTEzM2M2ZDMwOTllMDBmOGUzMzgyMzEwMTI3ZGFjZmJhOWFiNTM1MzJjMTA4MTY3MTMxZGQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.00DYDJ0JtWEmkhhH_S7scFdAQSVlz78fOqvCMIAGmPg)

Зачем вы качали релиз с равки репозитория, вместо того чтобы скачать его из релизов?
![image](https://github.com/user-attachments/assets/69f4f5f8-a5d1-44b9-a118-354c1926063e)

**Comment by SkibidiGoon** [comment]
> > > > у меня тоже самое, хоть и антивирус отключен и ничего не сьедал, не знаю, что делать.
> > > 
> > > 
> > > можно скриншот ошибки с папочкой запрета на виду?
> > > ![Скриншот-14-11-2024 10_44_56](https://private-user-images.githubusercontent.com/188412411/386160550-9d8b29bd-f1db-468a-b3a3-9ef86e0e4bf6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODIyMTMsIm5iZiI6MTczMTU4MTkxMywicGF0aCI6Ii8xODg0MTI0MTEvMzg2MTYwNTUwLTlkOGIyOWJkLWYxZGItNDY4YS1iM2EzLTllZjg2ZTBlNGJmNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMDU4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYThkZjBjNzFjMTEzM2M2ZDMwOTllMDBmOGUzMzgyMzEwMTI3ZGFjZmJhOWFiNTM1MzJjMTA4MTY3MTMxZGQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.00DYDJ0JtWEmkhhH_S7scFdAQSVlz78fOqvCMIAGmPg)
> 
> Зачем вы качали релиз с равки репозитория, вместо того чтобы скачать его из релизов?

всмысле, я из релиза качал

**Comment by serpen7** [comment]
> > > > > у меня тоже самое, хоть и антивирус отключен и ничего не сьедал, не знаю, что делать.
> > > > 
> > > > 
> > > > можно скриншот ошибки с папочкой запрета на виду?
> > > > ![Скриншот-14-11-2024 10_44_56](https://private-user-images.githubusercontent.com/188412411/386160550-9d8b29bd-f1db-468a-b3a3-9ef86e0e4bf6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODIyMTMsIm5iZiI6MTczMTU4MTkxMywicGF0aCI6Ii8xODg0MTI0MTEvMzg2MTYwNTUwLTlkOGIyOWJkLWYxZGItNDY4YS1iM2EzLTllZjg2ZTBlNGJmNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMDU4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYThkZjBjNzFjMTEzM2M2ZDMwOTllMDBmOGUzMzgyMzEwMTI3ZGFjZmJhOWFiNTM1MzJjMTA4MTY3MTMxZGQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.00DYDJ0JtWEmkhhH_S7scFdAQSVlz78fOqvCMIAGmPg)
> > 
> > 
> > Зачем вы качали релиз с равки репозитория, вместо того чтобы скачать его из релизов?
> 
> всмысле, я из релиза качал

в релизе нет файла гитигнор =/
![image](https://github.com/user-attachments/assets/64e2a3d1-0aa3-4a99-a708-878347919b38)
Вы явно качали либо с мейн репозитория гита равку, либо соурс код архив вместо программы релизной выше.

**Comment by SkibidiGoon** [comment]
> > > > > > у меня тоже самое, хоть и антивирус отключен и ничего не сьедал, не знаю, что делать.
> > > > > 
> > > > > 
> > > > > можно скриншот ошибки с папочкой запрета на виду?
> > > > > ![Скриншот-14-11-2024 10_44_56](https://private-user-images.githubusercontent.com/188412411/386160550-9d8b29bd-f1db-468a-b3a3-9ef86e0e4bf6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODIyMTMsIm5iZiI6MTczMTU4MTkxMywicGF0aCI6Ii8xODg0MTI0MTEvMzg2MTYwNTUwLTlkOGIyOWJkLWYxZGItNDY4YS1iM2EzLTllZjg2ZTBlNGJmNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMDU4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYThkZjBjNzFjMTEzM2M2ZDMwOTllMDBmOGUzMzgyMzEwMTI3ZGFjZmJhOWFiNTM1MzJjMTA4MTY3MTMxZGQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.00DYDJ0JtWEmkhhH_S7scFdAQSVlz78fOqvCMIAGmPg)
> > > 
> > > 
> > > Зачем вы качали релиз с равки репозитория, вместо того чтобы скачать его из релизов?
> > 
> > 
> > всмысле, я из релиза качал
> 
> в релизе нет файла гитигнор =/ ![image](https://private-user-images.githubusercontent.com/134365619/386165906-64e2a3d1-0aa3-4a99-a708-878347919b38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODI1MTgsIm5iZiI6MTczMTU4MjIxOCwicGF0aCI6Ii8xMzQzNjU2MTkvMzg2MTY1OTA2LTY0ZTJhM2QxLTBhYTMtNGE5OS1hNzA4LTg3ODM0NzkxOWIzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMTAzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzg5YWE0NDNjOTI4YWMyNDllM2YwZGY2OGFmOTNkOGIxZWQ4MGNjOGMzMDIxZWZmNDY3ZDFmYjYyODYyMDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nO3_s_z8ZnRRSdFT3KYxy4VnhuUPRqL8syDvpVOt8T4) Вы явно качали либо с мейн репозитория гита равку, либо соурс код архив вместо программы релизной выше.

а как открыть релизную программу, у меня она просто белая

**Comment by serpen7** [comment]
> а как открыть релизную программу, у меня она просто белая

У вас походу архиватора нет, а встроенный в винду открывает только зипы. Какая винда?

**Comment by SkibidiGoon** [comment]
> > а как открыть релизную программу, у меня она просто белая
> 
> У вас походу архиватора нет, а встроенный в винду открывает только зипы. Какая винда?

десятая

**Comment by serpen7** [comment]
> > > а как открыть релизную программу, у меня она просто белая
> > 
> > 
> > У вас походу архиватора нет, а встроенный в винду открывает только зипы. Какая винда?
> 
> десятая

64 или 32 разрядности?

**Comment by SkibidiGoon** [comment]
64

**Comment by serpen7** [comment]
держите https://7-zip.org/a/7z2408-x64.exe
Устанавливаете и у вас будут открываться архивы рар и прочие даже.

**Comment by SkibidiGoon** [comment]
> держите https://7-zip.org/a/7z2408-x64.exe Устанавливаете и у вас будут открываться архивы рар и прочие даже.

![Скриншот-14-11-2024 11_20_16](https://github.com/user-attachments/assets/463bd2a9-3949-4783-8e15-06671eed44fe)
теперь это вылазит

**Comment by serpen7** [comment]
> > держите https://7-zip.org/a/7z2408-x64.exe Устанавливаете и у вас будут открываться архивы рар и прочие даже.
> 
> ![Скриншот-14-11-2024 11_20_16](https://private-user-images.githubusercontent.com/188412411/386172078-463bd2a9-3949-4783-8e15-06671eed44fe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODM1NjgsIm5iZiI6MTczMTU4MzI2OCwicGF0aCI6Ii8xODg0MTI0MTEvMzg2MTcyMDc4LTQ2M2JkMmE5LTM5NDktNDc4My04ZTE1LTA2NjcxZWVkNDRmZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMTIxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGEwMzdhZjE1YTcyOTVlNzhlYzA3YmUwMTZiNWM0YTVkYmI5MWE5OTdjNjhlMTYxMDhjNjY0MDdmMzk4ZTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QxplDNmh-gmAWFhzID2mis54wALIaOeu2PJqYTwjQm8) теперь это вылазит

потому что вы пытаетесь открыть файл из архива, не разархивируя программу в отдельную папку. Там нужны все файлы программы, а не один.

**Comment by Eptiy** [comment]
распакуй архив. Или перетащи все файлы из архива в папку, если не понимаешь, как распаковать.

**Comment by SkibidiGoon** [comment]
> распакуй архив. Или перетащи все файлы из архива в папку, если не понимаешь, как распаковать.

как перетащить, они не перетаскиваются

**Comment by Eptiy** [comment]
нажми по архиву правой кнопкой и заскринь менюшку, скинь сюда

**Comment by SkibidiGoon** [comment]
> нажми по архиву правой кнопкой и заскринь менюшку, скинь сюда

![Скриншот-14-11-2024 11_34_59](https://github.com/user-attachments/assets/3341c96b-23bc-4f6a-b52b-43813bc44563)

**Comment by Eptiy** [comment]
Нет, закрой архив, открой папку с ним, и там уже по закрытому архиву нажми пкм

**Comment by serpen7** [comment]
https://github.com/user-attachments/assets/5aa1c41f-1d2d-4671-81d9-31d9446b3a4f



> > распакуй архив. Или перетащи все файлы из архива в папку, если не понимаешь, как распаковать.
> 
> как перетащить, они не перетаскиваются

**Comment by Eptiy** [comment]
ну или так, спасибо, что запарился.

**Comment by serpen7** [comment]
> ну или так, спасибо, что запарился.

да дело минуты как бы, открыл обс, запустил запись, показал, закрыл обс, закинул запись сюда.

**Comment by SkibidiGoon** [comment]
> > ну или так, спасибо, что запарился.
> 
> да дело минуты как бы, открыл обс, запустил запись, показал, закрыл обс, закинул запись сюда.

переместил как на видео, теперь просто выдает 
![Скриншот-14-11-2024 11_49_23](https://github.com/user-attachments/assets/478318dc-698f-4d74-a3cb-521690430f84)
и ничего не происходит, дискорд не открывается

**Comment by Eptiy** [comment]
Возвращаемся к вопросу: это бантик или сервис инсталл?

**Comment by SkibidiGoon** [comment]
> Возвращаемся к вопросу: это бантик или сервис инсталл?

а как понять

**Comment by Eptiy** [comment]
ну, ты запускаешь что?

**Comment by SkibidiGoon** [comment]
> ну, ты запускаешь что?

discord.bat

**Comment by Eptiy** [comment]
значит, у тебя была установлена служба, и ты её не удалил. Запускай sevrice_remove от админа.

**Comment by SkibidiGoon** [comment]
> значит, у тебя была установлена служба, и ты её не удалил. Запускай sevrice_remove от админа.

запустил, еще раз попробовать бат открыть теперь?

**Comment by Eptiy** [comment]
Да

**Comment by SkibidiGoon** [comment]
все, наконец то запустился, спасибо вам огромное

**Comment by puttr3** [comment]
Eptiy, спасибо мужик, тоже столкнулся с такой проблемой, минут 30 пытался пофиксить с помощью советов с других сайтов.
А так почитав вашу ветку сделал все за пару минут, очень тебе благодарен!

P.S. даже акк создал чтоб поблагодарить тебя)))
