### ISSUE TITLE
Не работают онлайн-радиостанции

### ISSUE THREAD

**Issue by warstarzer** [Flowseal/zapret-discord-youtube#717]
Хотел послушать радио, одни станции прогружались, другие нет. У не рабочих выцепил URL: https://jenny.torontocast.com:2000/stream/, добавил домен torontocast.com и *.torontocast.com в list-general.txt, перезагрузил компьютер, при подключении все равно ошибка. Может еще какие-то адреса есть?
Если отключить все средства обхода - все работает; если не отключать zapret, но включить VPN- тоже все ОК

**Comment by Eptiy** [comment]
Как вообще проверить эту ссылку? В браузере она не открывается, но пинг туда идёт. Сам torontocast.com открывается с запретом.

**Comment by testidcode** [comment]
> Как вообще проверить эту ссылку? В браузере она не открылась, но пинг идет. Сам torontocast.com открывается с запретом.

Можно зайти с radio garden: https://www.radio.garden/listen/j1-radio/spoipcw5, обращение идет к toronto, не работает, при это в этой же точке https://www.radio.garden/listen/ottava/rDch0y97 - работает, но и обращение идет уже к https://ottava2.out.airtime.pro:8000/ottava2_a

**Comment by Eptiy** [comment]
Ни с одного сайта это радио не открылось, включая radio garden, ни с запретом, ни без, впн не тестил, сейчас не могу. Плюс, с половины российских ip туда не пингует.

Выше писал, про то, что сам смог пингануть, но я пинговал torontocast.com. https://jenny.torontocast.com:2000/stream/ не пингуется у меня.

**Comment by Flowseal** [comment]
У меня и без запрета оно не работает. Сдаётся мне, что там просто блок со стороны самого радио по гео

**Comment by testidcode** [comment]
> У меня и без запрета оно не работает. Сдаётся мне, что там просто блок со стороны самого радио по гео

Блок то блоком, на официальный сайт - да, говорит "упс, мы не может предоставить вашей стране контент", но радио то работает, вот только что с Ростелекома проверял, а вот на Мегафоне без vpn никак не робит

**Comment by Flowseal** [comment]
Это уже заморочки самого радио - как он блокирует. Тут zapret не поможет.
