### ISSUE TITLE
не работает ютуб но работает дискорд

### ISSUE THREAD

**Issue by testacc12-com** [Flowseal/zapret-discord-youtube#719]
Здравствуйте помогите мне! Я запускаю general дискорд работает , захожу на сайт ютуб пишет не подключения к интернету

**Comment by testacc12-com** [comment]
![cmd_XMpJ3cWYFM](https://github.com/user-attachments/assets/8035cde5-ed2d-4e5a-ac4b-2e35fa1139a7)

**Comment by serpen7** [comment]
ты запускаешь сразу сервис. Удали его сервис ремувом от имени администратора и пробуй сначала батники нормальные. 
![image](https://github.com/user-attachments/assets/9fc5b78a-f3ed-42cc-bbbf-1d575a861e1b)

**Comment by testacc12-com** [comment]
нажимаю service remove 
![cmd_MTjiBJitaY](https://github.com/user-attachments/assets/10c1a5f3-acd5-4472-8ab6-15801896142f)

**Comment by testacc12-com** [comment]
Я не могу удалить сервисы потому что опять такая же ошибка 1060 open service

**Comment by Flowseal** [comment]
Он удалился ([SC] DeleteService SUCCESS) успешно. Пробуйте теперь обычные батники (не service), пока не найдёте тот батник, при работе которого не заработает ютуб и дискорд вместе. 
Если ютуб так и не заработал - возможно, что-то ему мешает. Например, старый обход - GoodbyeDPI. Можете скачать последнюю версию GoodbyeDPI и там запустить какой-нибудь service remove, который предоставляет сам GoodbyeDPI. 
Если всё ещё не помогло, возможно, у вас включены какие-то Proxy/VPN, отключите их. Остальные советы также есть тут - https://github.com/Flowseal/zapret-discord-youtube/discussions/251.

Как только найдёте батник, с которым всё работает, запускаете service_install.bat и там выбираете этот bat'ник

**Comment by serpen7** [comment]
> Я не могу удалить сервисы потому что опять такая же ошибка 1060 open service

это не ошибка это статусное оповещение что это вот не найдено в системе, виндайверт у вас успешно остановился и удален
