### ISSUE TITLE
Не запускается скрипт

### ISSUE THREAD

**Issue by kittengo0** [Flowseal/zapret-discord-youtube#72]
при попытке запуска выкидывает ошибку:

Путь содержит пробелы.
Пожалуйста, переместите скрипт в директорию без пробелов.
Press any key to continue . . .

что делать, не шарю совсем:(

**Comment by Rolex832** [comment]
Создай папку на локальном диске С:.
В названии папки используй только латинские буквы.
Разархивируй в созданную папку.
Далее запускай от имени администратора,по инструкции.

**Comment by Spiralka** [comment]
Дополню комментарий выше тем, что в пути до этого файла не должно встречаться пробелов
C:\Users\myNickname\Downloads\zapret-discord-youtube-1.1.1 вот как-то так должно быть 
а с C:\Users\myNickname\Downloads\zapret discord youtube 1.1.1 работать не будет
