### ISSUE TITLE
Перестал подключаться к интернету через роутер (Wi-fi, кабель)

### ISSUE THREAD

**Issue by Darkskub** [Flowseal/zapret-discord-youtube#725]
После перехода на версию 1.6.1 и запуска батника, перестал видеть интернет через роутер. Если подключаться через кабель провайдера, то все работает. Также если использовать экстендер на сеть роутера, то тоже работает. 
Пробовал данный метод, он не помог. https://github.com/Flowseal/zapret-discord-youtube/issues/558#issuecomment-2454954017
Также пробовал из диспетчера устройств удалить драйвер для сетевой карты и установить снова, тоже не помогло.
Иногда помогает перезагрузка компьютера и перевтыкание кабеля в Lan портах роутера, но интернет исчезнет через 1-2 минуты, но винда будет говорить, что инет есть.

Единственное, что удалось найти по проблеме - это настройка полностью перешла на IPv6 и я не знаю как это фиксить. 
Link speed (Receive/Transmit):	100/100 (Mbps)
Link-local IPv6 address:	fe80::6055:ac66:1705:c671%33
IPv6 DNS servers:	fec0:0:0:ffff::1%1
fec0:0:0:ffff::2%1
fec0:0:0:ffff::3%1
Manufacturer:	Realtek
Description:	Realtek PCIe GbE Family Controller
Driver version:	9.1.410.2015

**Comment by Flowseal** [comment]
Сбросьте настройки сетевого адаптера

**Comment by Flowseal** [comment]
Например, тут:
Сеть и Интернет - Дополнительные сетевые параметры
![image](https://github.com/user-attachments/assets/ca85dfa3-1585-4474-8c4c-e16b378530b1)

**Comment by Darkskub** [comment]
Сделал, не помогло.

**Comment by Eptiy** [comment]
Роутер до заводских сбросить попробуй. Если адаптер подхватил ipv6, наверное, его дал роутер.

**Comment by Darkskub** [comment]
Сбросил, не помогло. Не факт, что роутер. Я через экстендер сейчас сижу, который подхватывает сеть роутера и через него работает. Также я прописал для ноута выделенный внутренний ip и он после перезапуска (выше писал, что после него он работает минуту) подхватывал его, но потом переставал работать.

**Comment by serpen7** [comment]
драйвер сетевой карты 2015 года? Это что у вас за винда и билд?

**Comment by Darkskub** [comment]
Link speed (Receive/Transmit):	100/100 (Mbps)
Link-local IPv6 address:	fe80::7e84:f00f:6270:f7e1%14
IPv6 DNS servers:	fec0:0:0:ffff::1%1
fec0:0:0:ffff::2%1
fec0:0:0:ffff::3%1
Manufacturer:	Realtek
Description:	Realtek PCIe GbE Family Controller
Driver version:	10.63.1014.2022

После переустановки внды сегодня он автоматически встал, сейчас с сайта msi поставил этот.

**Comment by Darkskub** [comment]
И сама винда:
Edition	Windows 10 Pro
Version	22H2
Installed on	‎14.‎11.‎2024
OS build	19045.3803
Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by Darkskub** [comment]
И ещё, я перезапустил роутер и стало вот так:
Link speed (Receive/Transmit):	100/100 (Mbps)
Link-local IPv6 address:	fe80::7e84:f00f:6270:f7e1%14
IPv4 address:	192.168.0.100
IPv4 DNS servers:	192.168.0.1
Manufacturer:	Realtek
Description:	Realtek PCIe GbE Family Controller
Driver version:	10.63.1014.2022

Вытащил кабель и вставил обратно:
Link speed (Receive/Transmit):	100/100 (Mbps)
Link-local IPv6 address:	fe80::7e84:f00f:6270:f7e1%14
IPv6 DNS servers:	fec0:0:0:ffff::1%1
fec0:0:0:ffff::2%1
fec0:0:0:ffff::3%1
Manufacturer:	Realtek
Description:	Realtek PCIe GbE Family Controller
Driver version:	10.63.1014.2022

**Comment by Darkskub** [comment]
Посмотрел дальше. Когда я подключаю патчкорд, то он отправляет запрос DHCP и роутер выдает ему айпишник, но потом комп переходит на ipv6 и у роутера в списке не числиться. И так он этот запрос может отправлять иногда и история повториться.

**Comment by Flowseal** [comment]
А если на устройстве выключить поддержку IPv6? 
Можно попробовать через команды ещё сбросить tcp/ip и winsock:
```
netsh int ip reset
netsh winsock reset
ipconfig /flushdns
```

**Comment by Darkskub** [comment]
Прописал команды, перезапустил, не помогло. Зашёл в панель управления, отключил адаптеру ipv6, стало так:
Link speed (Receive/Transmit):	100/100 (Mbps)
Manufacturer:	Realtek
Description:	Realtek PCIe GbE Family Controller
Driver version:	10.73.815.2024

Попробовал вручную вписать настройки (ип, который забил в роутере для компа, гейтвей, днс и маску), которые у экстендора и работают, но он говорит, что не может сохранить настройки.

**Comment by serpen7** [comment]
Роутер скорее всего не держит, сколько он у вас и что за модель? Я вижу просто что это что-то из старого которое даже гигабит на сети не поддерживает судя по инфе которую вы даете. А 100мбитные там максимум что 300мбитный вайфай на Н протоколе, 32-64 мбайта озушки, мало памяти в хранилище  одноядерка на 400-800мгц цпу. Притом если зашит на прошку от прова то там вообще ничего неизвестно что творится и как заполняется. Роутер может просто упускать утечку памяти и потом уходить в отказ при ее переполнении. В идеале должен просто перезапускаться каждый раз но watchdog можно настроить и так же полюбому. Неподнятно немного.

**Comment by Darkskub** [comment]
Возможно, просто до этого пользовался zapret больше месяца и все работало, только при переходе на новую версию это произошло. Вручную получилось вбить ipv4, при отключенном ipv6, но он все равно не видит роутер локально, через ип к нему не подключиться.

**Comment by serpen7** [comment]
> Возможно, просто до этого пользовался zapret больше месяца и все работало, только при переходе на новую версию это произошло. Вручную получилось вбить ipv4, при отключенном ipv6, но он все равно не видит роутер локально, через ип к нему не подключиться.

не надо ничего вручную вбивать вы бьете по сетям, подсетям и маскам после роутера, сеть прова и так же подсеть за ним выводя абонентов из сети или сами встречая конфликт. У меня так сосед "староватенький" сделал и в итоге выбивал меня из сети и сам страдал. Вычислить его не пресдставлялось труда, но доказать прову и соседу я себе нервы посеял.
 Максимум что вы можете без подследствий поставить в роутере это ДНСы, уже на локальной машине вы можете крепить ИП но так же если знаете что делаете и как исходя из закрепа вашего ИП на машину в самом роутере иначе есть риск ретрансляции на старых моделях.

**Comment by Eptiy** [comment]
Можно попробовать в роутере привязать по маку сетевухи любой локальный ipv4, и этот же ipv4 прописать в сетевухе.

**Comment by Darkskub** [comment]
Я так и сделал чисто для проверки пойдет ли дело дальше, но ничего.

**Comment by Darkskub** [comment]
Autoconfiguration IPv4 Address. . : 169.254.175.118(Preferred)
 Autoconfiguration IPv4 Address. . : 169.254.130.151(Preferred)
Если подключаться к роутеру по патч корду или вайфай, то встречаю APIPA

**Comment by Darkskub** [comment]
Пофиксилось путем этих двух команд:
netsh interface ipv4 show inter 
netsh interface ipv4 set interface * dadtransmits=0 store=persistent

**Comment by Darkskub** [comment]
В общем, это не помогло и проблема осталась. Дальше пытаясь разобраться в чем дело с помощью Wireshark определил, что идет огромное количество ARP запросов с ноута, у которого были проблемы.
Роутер заменил, не помогло.

**Comment by Darkskub** [comment]
Понял в чем проблема, но как она возникла не понятно.

**Comment by zlooun** [comment]
> Понял в чем проблема, но как она возникла не понятно.

Так в чем проблема то была?

**Comment by Darkskub** [comment]
Если я правильно понял, то при переходе на новую версию (1.6) я что-то сделал не так и он сбил прошивку ресивера. Это привело к тому, что в сети было бесконечное количество ARP запросов, что продолжило сеть.

**Comment by Darkskub** [comment]
> > Понял в чем проблема, но как она возникла не понятно.
> 
> Так в чем проблема то была?

Если я правильно понял, то при переходе на новую версию (1.6) я что-то сделал не так и он сбил прошивку ресивера. Это привело к тому, что в сети было бесконечное количество ARP запросов, что продолжило сеть.

Больше похоже на неудачное совпадение, так что пофиксив ресивер все заработало и больше проблем не было.
