### ISSUE TITLE
Подскажите это работает с впн?

### ISSUE THREAD

**Issue by AzatMoneta** [Flowseal/zapret-discord-youtube#73]
Мне нельзя использовать некоторые приложения так же заходить на некоторые сайты с помощью впн.Подскажите тут используется впн?Смотрю свой айпи вроде не меняется.Но очко играет.

**Comment by Flowseal** [comment]
Нет

**Comment by AzatMoneta** [comment]
Т.Е она ни как не меняет айпи адрес и геолокацию?
