### ISSUE TITLE
Запускается Discord, но не подгружаются аватарки

### ISSUE THREAD

**Issue by acidluvboi** [Flowseal/zapret-discord-youtube#732]
Использую последнею версию Запрета, пробовал разные батники если что + модифицировал самостоятельно. Регион МСК, провайдер Билайн. Сам десктоп Дискорда + сайт летают, другие "запрещенные" сервисы тоже, но **не подгружаются аватарки**. Единственный вариант их догрузить - открыть любой ВПН, дальше аватарки будут загружены даже без ВПН чисто на Запрете. Из этого делаю вывод, что _не хватает какого-то url для подгруза в кэш_. Полный список ссылок, ссылающихся на Дискорд, в файле сейчас:

- updates.discord.com
- discord.com
- gateway.discord.gg
- cdn.discordapp.com
- discordapp.net
- discordapp.com
- discord.gg
- media.discordapp.net
- images-ext-1.discordapp.net
- discord.app
- discord.media
- discordcdn.com
- discord.dev
- discord.new
- discord.gift
- discordstatus.com
- dis.gd
- discord.co
- discord-attachments-uploads-prd.storage.googleapis.com
- discord-activities.com
- discord.design
- discord.gift
- discord.gifts
- discord.new
- discord.store
- discord.tools
- discordactivities.com
- discordapp.io
- discordcdn.com
- discordmerch.com
- discordpartygames.com
- discordsays.com

Чего может не хватать?

**Comment by mehh0vcki** [comment]
привет, блокируют домен `discordapp.com` и/или `cdn.discordapp.com`, вроде бы по айпишнику. попробуй мое решение:
https://github.com/Flowseal/zapret-discord-youtube/issues/710#issuecomment-2476298034

**Comment by Zub35** [comment]
> Использую последнею версию Запрета

если бы вы реально использовали последнюю версию, то в ней был бы cloudflare-ech.com

**Comment by acidluvboi** [comment]
> > Использую последнею версию Запрета
> 
> если бы вы реально использовали последнюю версию, то в ней был бы cloudflare-ech.com

а как это влияет? он есть

**Comment by acidluvboi** [comment]
> привет, блокируют домен `discordapp.com` и/или `cdn.discordapp.com`, вроде бы по айпишнику. попробуй мое решение: [#710 (comment)](https://github.com/Flowseal/zapret-discord-youtube/issues/710#issuecomment-2476298034)

есть разница какой батник при этом используется?

**Comment by mehh0vcki** [comment]
> > привет, блокируют домен `discordapp.com` и/или `cdn.discordapp.com`, вроде бы по айпишнику. попробуй мое решение: [#710 (comment)](https://github.com/Flowseal/zapret-discord-youtube/issues/710#issuecomment-2476298034)
> 
> есть разница какой батник при этом используется?

не-а

**Comment by mehh0vcki** [comment]
> > Использую последнею версию Запрета
> 
> если бы вы реально использовали последнюю версию, то в ней был бы cloudflare-ech.com

я не думаю, что cdn дискорда, и ech от cloudflare как либо связан :)

**Comment by acidluvboi** [comment]
> привет, блокируют домен `discordapp.com` и/или `cdn.discordapp.com`, вроде бы по айпишнику. попробуй мое решение: [#710 (comment)](https://github.com/Flowseal/zapret-discord-youtube/issues/710#issuecomment-2476298034)

не-а

**Comment by Dota222** [comment]
> > привет, блокируют домен `discordapp.com` и/или `cdn.discordapp.com`, вроде бы по айпишнику. попробуй мое решение: [#710 (comment)](https://github.com/Flowseal/zapret-discord-youtube/issues/710#issuecomment-2476298034)
> 
> не-а

Добавил `cloudflare-ech.com` в `list-general` и все снова начало грузиться. Попробуйте, если айпишник не помог
