### ISSUE TITLE
Некорректно работает в ютубе с Opera GX

### ISSUE THREAD

**Issue by Arbeli25** [Flowseal/zapret-discord-youtube#734]
При запуске каждого видео загрузка останавливается на 0:59 секунде и дальше не идет. Перетаскивание ползунка видео ситуацию не меняет. В хроме такой проблемы нет. Скорее всего проблема в самой опере, но все расширения я отключал и проблема не уходит. При включении обычного впн видео грузятся нормально. Корректно обходится блокировка различных бур, на которые без впн не зайти, проблема только с ютубом

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/251
