### ISSUE TITLE
Консоль при использовании открывается на секунду и сразу закрывается.

### ISSUE THREAD

**Issue by Sebastopolis** [Flowseal/zapret-discord-youtube#735]
Изначально пробовал версию 1.5.2. скачал rar - файл, извлёк в папку. После попытался от имени администратора запустить general, консоль на секунду открылась и сразу же закрылась, перепробовал все "батники", всё одинаково, на версии 1.6.1 всё тоже самое. (в коде не разбираюсь, так что надеюсь на помощь, заранее спасибо.) Также при двойном нажатии на "батник", к примеру, general возникает ошибка (на фото) . Возможно ошибка в пути и имени файла, учитывая уведомление об ошибке, но я ничего не менял, всё в "первозданном" виде.
![Снимок экрана (199)](https://github.com/user-attachments/assets/ab311cd7-3cdf-466f-afb5-643c731ef2df)

**Comment by serpen7** [comment]
Ты же качал rar архивы релизов, не зиповские точно?
https://github.com/Flowseal/zapret-discord-youtube/releases

Если так то тебе антивирь походу снес winws файл. Посмотри и достань его из карантина. Если не достать то тогда придется перекачивать релиз восстанавливая файл и вносить папочку в исключения антивиря.

Еще странность что тебе указывает не путь в бин папку с винвс, а как будто ты качал сборку неотсюда и там какой то другой винвс называемый странно. Смотри не подцепи вирь скачивая непонятно откуда и от кого в интернете. Фейковых сборок много, на ютубе особенно хорошо обосновались мошенники с этим, что нужно якобы скачать запароленный архив, пароль там чтобы антивирь его не мог просканить, и запустить по сути вирусную сборку запрета с вирусней. 
Т.к. нормальная ошибка с запрета @Flowseal должна выглядеть так 
![image](https://github.com/user-attachments/assets/07c41324-2e82-4f4c-98b6-0d0912c2703f)
![image](https://github.com/user-attachments/assets/14b41ba8-5d47-4bf7-bf6c-505f392fc92d)
А ютуб на жалобы не реагирует.
![image](https://github.com/user-attachments/assets/22f45f9b-d4e3-455f-8c1b-99a6260956ec)

**Comment by Sebastopolis** [comment]
Да, файлы качал по той же ссылке. "Обнаружено: Trojan:Script/Wacatac.H!ml" - в журнале защиты, смущает, что там написано "троян", верно понимаю, что антивирус винды сам определяет вид вируса?

**Comment by serpen7** [comment]
> Да, файлы качал по той же ссылке. "Обнаружено: Trojan:Script/Wacatac.H!ml" - в журнале защиты, смущает, что там написано "троян", верно понимаю, что антивирус винды сам определяет вид вируса?

а можешь скриншот прислать а то я чет не уверен даже потому что в эвристиках такого даже не выдает. А выдает правильные "подозревающие" сигнатуры общие.

потому что вакатак это общее название поведения трояна у дефендера, что собственно и делает прога вмешиваясь в трафик и манипулируя им, поэтому это по сути поведение трояна. У вакатака множество ложных срабатываний. Но как бы да такой троян есть в природе интернета, да. Поэтому лучше сделай скриншот этого чтобы лишний раз так сказать перестраховаться что это именно от запрета файл, а не откуда то еще.

**Comment by Sebastopolis** [comment]
![Снимок экрана (200)](https://github.com/user-attachments/assets/4565efef-10d2-402a-a289-017543f074c9)

**Comment by Sebastopolis** [comment]
![Снимок экрана (201)](https://github.com/user-attachments/assets/e6136b34-dc8d-413f-a7ea-627044b2e22d)

**Comment by Sebastopolis** [comment]
Похоже дело в антивирусе, как ты и говорил, но почему такая реакция антивируса не знаю, скачивал по той же ссылке, что ты скинул

**Comment by Sebastopolis** [comment]
Не знаю, если поможет, я так же пробовал версию 1.0.0. и там консоль не закрывалась, работал дискорд, но не ютуб. Сейчас на компьютере нет этой версии, только 1.6.1.

**Comment by serpen7** [comment]
Это ложное срабатывание. Видимо эвристика так же параноидальна как и некоторые эвристики в вирустотале, Особенно на запакованные архивы. Это не вакатак. Он вешает почему то эту сигну как общую видимо определяя якобы поведение похожее на трояна. Но прога как бы да, троян по сути что я объяснял ранее. Так что тут малость просто эвристика антивируса постаралась хоть и ложно, но все равно заподозрила.
![image](https://github.com/user-attachments/assets/a0d833de-b6e8-4425-a5dd-1d9123bf123a)
![image](https://github.com/user-attachments/assets/3b53bb51-d16f-48e5-bb67-dcb18a23aaf9)

**Comment by serpen7** [comment]
> Не знаю, если поможет, я так же пробовал версию 1.0.0. и там консоль не закрывалась, работал дискорд, но не ютуб. Сейчас на компьютере нет этой версии, только 1.6.1.

в 1.0.0 так же поведение консоли как и в 1.6.1, батники нужны только для запуска winws с параметрами приложения который использует уже фильтр windivert, поэтому они закрываются и открывается окно winws если запуск успешный. Оно выглядит как консоль после запуска батника, но это не совсем консоль, это программа winws.

**Comment by Sebastopolis** [comment]
Добавил папку, в которой всё содержимое rar-файла, в исключения, переустановил (на всякий случай) версию с твоей ссылки, в эту папку, закрыл исправление этой программы в дефендере, т.е. запретил удаление, попытался запустить от имени администратора, всё так же как и было. Видимо я что-то проглядел...

**Comment by Sebastopolis** [comment]
Так, не знаю имеет ли это значение, но файлы в папке у меня такие:
![Снимок экрана (203)](https://github.com/user-attachments/assets/0a30120d-213c-4a52-9993-ee2f8e85293f)
![Снимок экрана (202)](https://github.com/user-attachments/assets/b83756e0-db13-40aa-99fb-6b4e0c789e3c)

**Comment by Sebastopolis** [comment]
Но тип файла в "свойствах" такой же - .bat
![Снимок экрана (204)](https://github.com/user-attachments/assets/2841fffd-7eb6-47d8-b239-397d4166830f)

**Comment by serpen7** [comment]
Запускается программа после батника?

**Comment by Sebastopolis** [comment]
Только на секунду

**Comment by serpen7** [comment]
> Только на секунду

винвс не открывается?

**Comment by Sebastopolis** [comment]
Тоже только на секунду

**Comment by serpen7** [comment]
> Тоже только на секунду

она минимизирует себя в панельку задач внизу сразу, чтобы не мешатся

**Comment by Sebastopolis** [comment]
Да, я успеваю её увидеть

**Comment by serpen7** [comment]
![image](https://github.com/user-attachments/assets/d91dbb72-3d02-4d51-a6fe-195fb9f7801c)

**Comment by Sebastopolis** [comment]
Ага, но сразу пропадает

**Comment by serpen7** [comment]
> Ага, но сразу пропадает

смотри опять журнал дефендера)

**Comment by serpen7** [comment]
или ты ставишь как сервис её?

**Comment by Sebastopolis** [comment]
Смотри, ещё окно появляется на секунду, извини за качество, скрин экрана и запись не видели этого окна (странно). 
![5314806013876102209](https://github.com/user-attachments/assets/b2ebf456-be95-4612-92d1-152683b606dc)
![5314806013876102208](https://github.com/user-attachments/assets/4430a490-4f45-4680-a48d-f48e71b2701c)

**Comment by Sebastopolis** [comment]
Щас журнал посмотрю

**Comment by serpen7** [comment]
ты батники запускаешь или сам винвс?

**Comment by Sebastopolis** [comment]
Винвс

**Comment by serpen7** [comment]
не нужно его запускать, его запускают батники с параметрами
![image](https://github.com/user-attachments/assets/f0ed3521-fe89-4e7d-b854-52cb1f113668)

**Comment by serpen7** [comment]
тебе лишь нужно выбрать один из них который у тебя заработает

**Comment by Sebastopolis** [comment]
Так, понял, секунду

**Comment by Sebastopolis** [comment]
И не один не работает, а именно происходит кратковременный запуск, появляется вкладка и сразу закрывается

**Comment by serpen7** [comment]
> И не один не работает, а именно происходит кратковременный запуск, появляется вкладка и сразу закрывается

и винвс внизу не появляется?

**Comment by Sebastopolis** [comment]
Журнал дефендера проверил, вот: 
![Снимок экрана (205)](https://github.com/user-attachments/assets/be0ef112-3fc9-429c-851d-9a2ffd50fe21)

**Comment by serpen7** [comment]
добавь папку с запретом в исключения дефендера, не архив а папку саму, архив тебе уже не нужен с разархивированноей программой.

**Comment by Sebastopolis** [comment]
папку в исключения поставил
![Снимок экрана (206)](https://github.com/user-attachments/assets/1f95c994-0afc-4fa8-bbe4-d596bebe910f)

**Comment by serpen7** [comment]
и все равно запускается и закрывается без запуска винвс внизу?

**Comment by Sebastopolis** [comment]
Да(

**Comment by Sebastopolis** [comment]
Ладно дружище, спасибо за уделённое время

**Comment by Sebastopolis** [comment]
я стал лучше понимать что да как работает, буду сам копаться , как решу проблему - скажу

**Comment by serpen7** [comment]
Если что может быть так что винда чето все равно заблочила уже даже с исключениями, перезапусти комп, может разблочит. Потом на всякий случай запусти service_remove батник от администратора правой кнопочкой и прогони его, попробуй снова батники. Может заработает.

**Comment by Dronatar** [comment]
Если через секунду после запуска закрывается, то попробуй удалить сервисы GoodByeDPI и Zapret

**Comment by Flowseal** [comment]
Убери спец символы из названия папки (&)

**Comment by Sebastopolis** [comment]
> Убери спец символы из названия папки (&)

Всё гениальное просто) Заработало, я забыл о спецсимволе, ребята спасибо вам)

**Comment by Sebastopolis** [comment]
Если у вас такая же проблема, проверьте название папки на наличие спецсимволов. Спасибо всем кто пытался и помог мне решить проблему)

**Comment by rekrytssad** [comment]
что делать если пишет skip 6 hours и закрывается папка

**Comment by Garmxd** [comment]
тоже самое( при запуске discrod.bat на милисекунду появляется консоль и закрывается

**Comment by Sebastopolis** [comment]
Антивирус может быть мешает. Добавь папку с запретом в исключения антивируса и переустанови запрет ( если не заработает после добавления в исключения, может помочь)

**Comment by Dronatar** [comment]
> что делать если пишет skip 6 hours и закрывается папка

Может поможет
https://github.com/Flowseal/zapret-discord-youtube/issues/715

**Comment by CK1234567891** [comment]
![image](https://github.com/user-attachments/assets/bea0eda9-dfb2-405c-aeca-bde74c16d3bf)
не запускается строка что делать

**Comment by TizianVSF** [comment]
Проблема решилась случайно: в новейшей версии (1.6.4) запустил general (FAKE TLS MOD), после стали запускаться все оставшиеся bat файлы. До этого, после установки антивируса,  была такая же проблема: консоль запускается на пол секунды и сразу проподает.
