### ISSUE TITLE
Не отображаются аватарки в дискорд

### ISSUE THREAD

**Issue by LincolnCox29** [Flowseal/zapret-discord-youtube#736]
Запустил сегодня дискорд, аватарки не отображаются. Пробовал перезапустить дс, не помогло, поставил последнюю версию сборки, тоже не помогло. Может нужно какие-то домены добавить ? У меня всё по дефолту стоит сейчас.

**Comment by Blueberryy** [comment]
Для меня сработал запуск ``general (ALT).bat``.

**Comment by LincolnCox29** [comment]
> Для меня сработал запуск `general (ALT).bat`.

Да уж, об этом надо было сразу подумать, мне ALT2 помог
