### ISSUE TITLE
Обновил Windows и всё перестало работать

### ISSUE THREAD

**Issue by 6VaneK9** [Flowseal/zapret-discord-youtube#741]
general.bat работал прекрасно на версии 1.5.1, и решаю обновить windows. запускаю после обновления и оно просто открывается и сразу закрывается, проделал несколько раз и результат такой же, когда скачал 1.6.1 то оно выдавало какой то текст "Skipping update check since it wasn't 6 hours" и закрывается, такое-же для всех ALT версий, как исправить?

**Comment by Flowseal** [comment]
service_remove.bat запустите, а затем пробуйте

**Comment by ddhsp** [comment]
всё равно пишет
The zapret DPI bypass : zapret service is not started.

More help is available by typing NET HELPMSG 3521.

[SC] DeleteService SUCCESS
[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
[SC] StartService FAILED 1075:

**Comment by AccountWithoutALogic** [comment]
запустил service_remove.bat и затем general.bat, ничего не сработало, но когда проделал service_install.bat на general.bat то заработало, спасибо!

**Comment by AdolfHitler-cyber** [comment]
у меня вообще ничего не помогает хелпуйте поцанчики. все перепробовал что только возможно, все ваши баты запускал оно нииииичееееегоооо не работает, и выдает эту глупую ошибку 1075

**Comment by Camorrka** [comment]
> у меня вообще ничего не помогает, помогите, пацаны. я перепробовал все, что только можно, запускал все ваши баты, но ничего не работает, и выдает эту дурацкую ошибку 1075

друг, у меня таже проблема, подскажи какой у тебя провайдер?

**Comment by dirftik** [comment]
> у меня вообще ничего не помогает, помогите поцанчики. все перепробовал что только возможно, все ваши баты запускали его нииииииииееееооо не работает, и выдает эту глупую ошибку 1075

я попробовал скачать обратно версию 1.5.1 и вроде всё стало работать. попробуй тоже поскачивать прошлые версии
