### ISSUE TITLE
Не работают чаты

### ISSUE THREAD

**Issue by mimxq** [Flowseal/zapret-discord-youtube#742]
Дискорд запускается, но никакой чат не грузит (ни на серверах, ни личку)
Пишет "Messages Failed To Load"
Пару минут назад все работало и резко возникла эта проблема

**Comment by zappere50** [comment]
Такая же беда. Даже не знаю, связано ли это конкретно с запретом

**Comment by WhatTheShawod** [comment]
Не факт что zapret-discord-youtube шалит.
По Downdetector вроде по всему миру у дискорда проблемы сейчас.

**Comment by JustMatado** [comment]
Зато работает войс. Ну, как минимум.

**Comment by vefixx** [comment]
предполагаю, что это у них с апи проблемы 
![image](https://github.com/user-attachments/assets/27434cc4-d05b-48c1-96be-338b3ab71d79)

**Comment by Radiy288** [comment]
https://discordstatus.com/ чекните

**Comment by PRXPHET** [comment]
Забейте, это у всех так)
![image](https://github.com/user-attachments/assets/ff9d413d-82b5-48e9-bb73-a1e86a797726)

**Comment by ERmak148** [comment]
пизда дсу

**Comment by Banan22Ba** [comment]
Попробовал через впн и прокси с немецким айпи. Там тоже не работает, так что спокойно, не в запрете дело.

**Comment by Radiy288** [comment]
просто ебланы починить не могут

**Comment by Radiy288** [comment]
больше миллиона людей юзают дс

**Comment by sh2kcs** [comment]
+1

**Comment by jptaro** [comment]
везде не робит

**Comment by liirios** [comment]
Как думаете, как долго это будет продолжаться?

**Comment by Titranadox** [comment]
Только бота для дискорда писать начал и он упал(

**Comment by robert-seller** [comment]
вхыахывах, значит не у меня одного

**Comment by sosik-fimozik** [comment]
Я ХУЕЮ

**Comment by jptaro** [comment]
> Как думаете, как долго это будет продолжаться?
  
  каждый день по пять подходов

**Comment by sosik-fimozik** [comment]
> Как думаете, как долго это будет продолжаться?

ты очень скоро узнаешь...

**Comment by jptaro** [comment]
> > Как думаете, как долго это будет продолжаться?
> 
> ты очень скоро узнаешь...

он знал...

**Comment by sosik-fimozik** [comment]
![image](https://github.com/user-attachments/assets/178e4a53-fe1e-4ac7-b663-97aff4813ec0)

**Comment by robert-seller** [comment]
а сколько вообще это длится? ну в плане, во сколько упал

**Comment by jptaro** [comment]
> а сколько вообще это длится? ну в плане, во сколько упал

минут 40 назад

**Comment by robert-seller** [comment]
о, уже заработал))))

**Comment by posevok** [comment]
я с помощью VPN хотел посидеть с телефона, я так и не смог никакое сообщение отправить, как и на пк

**Comment by sosik-fimozik** [comment]
![image](https://github.com/user-attachments/assets/7c5e250f-fa26-452e-b59c-6db25310834b)

**Comment by WitherTaco2** [comment]
мдэээ.... и у меня не робит. Скорее всего это со стороны самого дискорда проблемы или гдето интернетный трос оборвали с дс

**Comment by sosik-fimozik** [comment]
оно ожило!!!!

**Comment by jptaro** [comment]
починили

**Comment by mimxq** [comment]
С днем починки дс всех!

**Comment by posevok** [comment]
> о, уже заработал))))

и реально заработал!

**Comment by jptaro** [comment]
> о, уже заработал))))

спасибо пупсик

**Comment by WitherTaco2** [comment]
всё, теперь ветку можно закрывать
