### ISSUE TITLE
Эт Только У меня?

### ISSUE THREAD

**Issue by oIMINGAMESIo** [Flowseal/zapret-discord-youtube#743]
![image](https://github.com/user-attachments/assets/6f1f67f6-1a81-4aab-8c3c-c1b819aac84c)

мне кажется дискорд упал это только у меня или у всех?

**Comment by madhack2142** [comment]
тоже само

**Comment by M1NG7454** [comment]
а ну меня не забанили а то друзья по приколу накинули мне репортов

**Comment by NewSummo** [comment]
Дискорд не хард-банит. Просто закрылась лавочка. Как говорится, из депрессии три выхода: Домодедово, Шереметьево и Внуково

**Comment by Peace-5P** [comment]
у всех видимо

**Comment by M1NG7454** [comment]
всё дискорд живой
