### ISSUE TITLE
проблема при запуске service_goodbye_discord

### ISSUE THREAD

**Issue by Er1cius** [Flowseal/zapret-discord-youtube#744]
Как решить эту ошибку?
![1233](https://github.com/user-attachments/assets/07741768-e27f-4b31-8dc0-ad07407327ba)

**Comment by serpen7** [comment]
такэ этот батник сделан  чтобы работать с сервисом гудбайдпи, чтобы не мешать, его нет как бы вам и пишут.

**Comment by Flowseal** [comment]
Запустить, если вы используете СЕРВИС goodbyedpi, и хотите, чтобы zapret обходил только discord.
ВНИМАНИЕ: Запускать ПОСЛЕ создания сервиса goodbyedpi. Первый раз goodbyedpi может вылететь - просто перезапустите устройство!
