### ISSUE TITLE
Закрывается консоль

### ISSUE THREAD

**Issue by Planebb** [Flowseal/zapret-discord-youtube#745]
Я открываю консоль от имени администратора, он у меня пишет о проверке обновлений и сразу вырубается. Провайдер у меня МТС, пробовал с другими версиями, все равно не работает

**Comment by evgengoldwar** [comment]
Тоже самое ниче не открывается просто закрывается сразу же

**Comment by serpen7** [comment]
вы же качали rar архив, а не zip из релизов, чтобы там был правильный формат файлов CLRF? Если да то скорее всего вы не удалили сервис который нужен для запуска. Если у вас стоял гудбайдпи то его так же нужно будет удалить.
Качаете отсюда гудбайдпи https://github.com/ValdikSS/GoodbyeDPI/releases
Разархивируете в папочку его.
Запускаете там сервис ремув от администратора. 
Запускаете сервис ремув от администратора из папки запрета
Перезагружаете комп
Повторяете сервис ремув из гудбайдпи от администратора и из папочки запрета от администратора. 
Пробуете батники снова 
![image](https://github.com/user-attachments/assets/6ec282b0-757d-4509-89b8-35aba90626c7)

**Comment by Planebb** [comment]
> вы же качали rar архив, а не zip из релизов, чтобы там был правильный формат файлов CLRF? Если да то скорее всего вы не удалили сервис который нужен для запуска. Если у вас стоял гудбайдпи то его так же нужно будет удалить. Качаете отсюда гудбайдпи https://github.com/ValdikSS/GoodbyeDPI/releases Запускаете там сервис ремув от администратора. Разархивируете в папочку его. Запускаете сервис ремув от администратора из папки запрета Перезагружаете комп Повторяете сервис ремув из гудбайдпи от администратора и из папочки запрета от администратора. Пробуете батники снова ![image](https://private-user-images.githubusercontent.com/134365619/386927053-6ec282b0-757d-4509-89b8-35aba90626c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjcwMjAsIm5iZiI6MTczMTgyNjcyMCwicGF0aCI6Ii8xMzQzNjU2MTkvMzg2OTI3MDUzLTZlYzI4MmIwLTc1N2QtNDUwOS04OWI4LTM1YWJhOTA2MjZjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNjU4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjYxM2Q5OWE4MGUyZmJmMWZjNWRkYzYwNjU4ZWMwMjlmNmEzOTBmYTAzZjkxNmQ3NjdhODc3OTRhNWU4Y2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MbhTcM8bmw1dF0jgGRcg8GnOfYYTCQQYQAlRRtVqFO0)

**Comment by Planebb** [comment]
Спасибо! Помогло
