### ISSUE TITLE
Работает у меня, но не работает у соседа по квартире, интернет один

### ISSUE THREAD

**Issue by AminoAsh** [Flowseal/zapret-discord-youtube#75]
Уже перепробовали повырубать все антивирусы, вырубить впн, поставить другие конфигурации, ничего не помогло. У меня всё работает, у него ничего.

**Comment by Flowseal** [comment]
Какие ошибки? Больше информации надо

**Comment by AminoAsh** [comment]
Дискорд не запускается, висит на вкладке starting, в ютубе грузится страница, но не грузятся видео. Используется последняя версия. Не могу понять почему у меня всё нормально работает, а у него вот эти проблемы. Сам скрипт запускается, поэтому пробелы и русские символы исключены

**Comment by Spiralka** [comment]
В хроме по chrome://flags/ флаги сосед отключал? 
UPD: Попробуйте еще в инкогнито на ютуб зайти, возможно какие-нибудь плагины конфликтуют

**Comment by AminoAsh** [comment]
> В хроме по chrome://flags/ флаги сосед отключал? UPD: Попробуйте еще в инкогнито на ютуб зайти, возможно какие-нибудь плагины конфликтуют

Флаги он не отключал.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90
