### ISSUE TITLE
не работают батники

### ISSUE THREAD

**Issue by E6AHbK0** [Flowseal/zapret-discord-youtube#754]
![image](https://github.com/user-attachments/assets/622be6c0-4ca7-46e7-9849-d3722a5b13e3)
какой батник я бы не запускал везде ошибки и права доступа есть но не сохраняет и не запускает

**Comment by E6AHbK0** [comment]
![image](https://github.com/user-attachments/assets/522e0af4-5b41-4b99-a0ef-4e55d0d4f2fc)

**Comment by Eptiy** [comment]
Windivert вряд ли будет работать на 7ке. Скорее всего, дело не в батниках. Если надо запускать из-под вин7, иди на форумы по виндайверту и там у людей спрашивай, что, да как.

**Comment by E6AHbK0** [comment]
я как читал многие удаляют виндиверт
и я его удалил

**Comment by E6AHbK0** [comment]
гудбай впринципе работает но в голос не могу зайти

**Comment by Eptiy** [comment]
Гудбай и не даст зайти в голос. Если ты используешь запрет вместе с гудбаем, то используй соответствующий сервис с названием discord_goodbye. Другие сервисы и батники с гудбаем работать не будут.

> я как читал многие удаляют виндиверт
и я его удалил

Что значит 'удалил виндайверт'? Если ты удалил файлы виндайверта из папки билда, естественно у тебя не будет ничего работать и запускаться.

**Comment by Eptiy** [comment]
Ещё момент - у тебя билд не от flowseal, а zapret_build от nemixio. Они разные и используют разные стратегии обхода. Более того, у тебя скачана не релизная версия, а сырой архив ветки main. Скачивай билд из раздела releases.

**Comment by serpen7** [comment]
Чтобы виндайверт работал на 7ке там нужно обновление 7ки какое-то потому что 

> Horribly outdated Windows 7 installations are not able to load WinDivert driver due to missing support for SHA256 digital signatures. Install KB3033929 [x86](https://www.microsoft.com/en-us/download/details.aspx?id=46078)/[x64](https://www.microsoft.com/en-us/download/details.aspx?id=46148), or better, update the whole system using Windows Update.

Ну или кардинальным решением это просто поставить более новую винду т.к. у 7ки и дальше будут проблемы "прошлого" связанные с не поддержкой работоспособности нового софта.

**Comment by serpen7** [comment]
> я как читал многие удаляют виндиверт и я его удалил

ну а как программа будет работать без драйвера перехвата и модификации пакетов основного если его удаляют?)
Это все равно что удалить систем32 в операционке и потом удивлятся что винда не грузится)

**Comment by E6AHbK0** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/754#issuecomment-2482134470 
у меня 2 компьютер с 10 которую я прям терпеть не могу, и на нем все ништяк вот я и мучаюсь со своей родной любименькой семерочкой

**Comment by E6AHbK0** [comment]
> Horribly outdated Windows 7 installations are not able to load WinDivert driver due to missing support for SHA256 digital signatures. Install KB3033929 [x86](https://www.microsoft.com/en-us/download/details.aspx?id=46078)/[x64](https://www.microsoft.com/en-us/download/details.aspx?id=46148), or better, update the whole system using Windows Update.

и у меня есть это обновление

**Comment by E6AHbK0** [comment]
> > я как читал многие удаляют виндиверт и я его удалил
> 
> ну а как программа будет работать без драйвера перехвата и модификации пакетов основного если его удаляют?) Это все равно что удалить систем32 в операционке и потом удивлятся что винда не грузится)

в гайде написано было я просто неделю мозги се ломаю над этой херней

**Comment by E6AHbK0** [comment]
> Ещё момент - у тебя билд не от flowseal, а zapret_build от nemixio. Они разные и используют разные стратегии обхода. Более того, у тебя скачана не релизная версия, а сырой архив ветки main. Скачивай билд из раздела releases.

у меня 5 билдов скачано было я написал по факту что ни от кого не работает как бы, я и спрашиваю помощи

**Comment by Eptiy** [comment]
> в гайде написано было я просто неделю мозги се ломаю над этой херней

Ни в каком гайде не может быть совета 'удалить виндайверт'. Это основа обхода, он есть во всех билдах и гудбае не просто так. Скорее всего, ты читал невнимательно.

> мучаюсь со своей родной любименькой семерочкой

Лучше не мучайся, поставь 10. Никто не собирается в дальнейшем поддерживать ПО для устаревшей во всех смыслах системы. Сегодня ты обход костылями заводишь, завтра его обновляют, и он вообще перестаёт там заводиться.

**Comment by Eptiy** [comment]
> у меня 5 билдов скачано было я написал по факту что ни от кого не работает как бы, я и спрашиваю помощи

_**Читай внимательнее, ты вообще не читал как будто, что я написал:**_

> Более того, у тебя скачана не релизная версия, а сырой архив ветки main. Скачивай билд из раздела releases.

**Comment by E6AHbK0** [comment]
> > у меня 5 билдов скачано было я написал по факту что ни от кого не работает как бы, я и спрашиваю помощи
> 
> _**Читай внимательнее, ты вообще не читал как будто, что я написал:**_
> 
> > Более того, у тебя скачана не релизная версия, а сырой архив ветки main. Скачивай билд из раздела releases.

там тоже скачивал комон

**Comment by E6AHbK0** [comment]
![image](https://github.com/user-attachments/assets/aefb92f2-f3c8-4739-8504-ed9cbe42a304)

**Comment by E6AHbK0** [comment]
![image](https://github.com/user-attachments/assets/a91f29e5-a9af-4c38-ba8e-bb3c2fa3019e)

**Comment by E6AHbK0** [comment]
опачки движение появилось в службах до этого ни как не появлялось
ошибка 577

**Comment by Eptiy** [comment]
Судя по скринам, у тебя успешно обновилась и запустилась служба. Всё остальное билда не касается. Если у тебя не подходят конфиги - пробуй разные батники и разные билды, тем более последние у тебя уже есть. Если не работает ни один конфиг - удостоверься, что нет никаких других программ, работающих с трафиком и потенциально мешающих запрету (у людей с картой киллер мешает запрету даже служба от этой карты). Если всё так же ничего не работает - дело может быть в 7ке.

**Comment by Eptiy** [comment]
Ещё добавлю: лучше не пытать счастье и не обновлять службы. Когда тестируешь конфиги, используй сами батники, не устанавливай службы. Когда переустанавливаешь службу, либо ставишь службу из другого билда, сначала удали имеющуюся через service_remove (от админа), проверь, что служба удалилась в диспетчере задач, потом уже устанавливай другую.

**Comment by E6AHbK0** [comment]
служба не запускаеться ошибка 577

**Comment by Eptiy** [comment]
Где такая ошибка? У тебя установщик службы выдал STATE: 4 RUNNING.

**Comment by serpen7** [comment]
> ошибка 577

у него винда 7 Ошибка 577: Системе Windows не удается проверить цифровую подпись этого файла.
Оно не будет работать потому что в 7ке на старых очень билдах отсутствует обновление проверки подписи sha256.
Нужно обновлять систему саму или ставить более современную ОС. Иначе драйвер виндайверта не загрузится.

**Comment by Eptiy** [comment]
Так и подумал. Вообще, можно отключить проверку подписи, раз ему так принципиальна 7ка, но это сильно компрометирует безопасность.

**Comment by E6AHbK0** [comment]
> > ошибка 577
> 
> у него винда 7 Ошибка 577: Системе Windows не удается проверить цифровую подпись этого файла. Оно не будет работать потому что в 7ке на старых очень билдах отсутствует обновление проверки подписи sha256. Нужно обновлять систему саму или ставить более современную ОС. Иначе драйвер виндайверта не загрузится.

она есть это обновление

**Comment by E6AHbK0** [comment]
> > ошибка 577
> 
> у него винда 7 Ошибка 577: Системе Windows не удается проверить цифровую подпись этого файла. Оно не будет работать потому что в 7ке на старых очень билдах отсутствует обновление проверки подписи sha256. Нужно обновлять систему саму или ставить более современную ОС. Иначе драйвер виндайверта не загрузится.

а виндайверта нету)

**Comment by Eptiy** [comment]
Что значит "виндайверта нету"?

**Comment by E6AHbK0** [comment]
> Что значит "виндайверта нету"?

то и значит я его удалил так как пытался многие способы решения проблемы опробовать а назад не встает

**Comment by Eptiy** [comment]
Он и не встанет, тебе же объяснили причину:

> Системе Windows не удается проверить цифровую подпись этого файла.

**Comment by E6AHbK0** [comment]
> Он и не встанет, тебе же объяснили причину:
> 
> > Системе Windows не удается проверить цифровую подпись этого файла.

как отключить проверку подписи?)

**Comment by Eptiy** [comment]
Сам ищи, это запрета не касается.

**_Настоятельно не рекомендую этого делать, это очень сильно понижает безопасность системы, лучше обновись уже до 10 и не мучайся._**

**Comment by E6AHbK0** [comment]
> Сам ищи, это запрета не касается.
> 
> **_Настоятельно не рекомендую этого делать, это очень сильно понижает безопасность системы, лучше обновись уже до 10 и не мучайся._**

ок щя найду, а 10 мое железо будет тянуть с трудом, и я не любитель этой прошивки так как она капец как не привычна, на 7 уже 15 лет сижу

**Comment by Eptiy** [comment]
Тогда, так сказать, ходи и оборачивайся. Без проверки подписи ты для всего зловреда "открываешь двери нараспашку".

**Comment by E6AHbK0** [comment]
> Тогда, так сказать, ходи и оборачивайся. Без проверки подписи ты для всего зловреда "открываешь двери нараспашку".

заработало все
спасибо, а я не боюсь)

**Comment by E6AHbK0** [comment]
> Тогда, так сказать, ходи и оборачивайся. Без проверки подписи ты для всего зловреда "открываешь двери нараспашку".

так ведь если ничего не скачиваешь и не устанавливаешь бояться то нечего же?

**Comment by Eptiy** [comment]
В целом, да. Но я гарантий никаких дать не могу, я таким не баловался.

**Comment by serpen7** [comment]
> > Тогда, так сказать, ходи и оборачивайся. Без проверки подписи ты для всего зловреда "открываешь двери нараспашку".
> 
> так ведь если ничего не скачиваешь и не устанавливаешь бояться то нечего же?

уже как несколько лет это так не работает. Это было так в годах 2010-16. Сейчас есть и удаленное исполнение кода и использование уязвимостей нулевого дня и куча других вещей при которых антивирус на системе это неотъемлемый компонент защиты сейчас. Погугли видосы на ютубе за сколько винде ХР прилетает заражание от того что её просто подключили к интернету и больше ничего не делали. А в диспетчере задач стали появлятся левые процессы сами по себе, даже китайские.
Есть так же и взлом и заражение сайтов или зараженные сайты, либо сайты с баннерами которые могут проигрывать зараженную рекламу, в целом которые используют уязвимости браузеров, они могут без твоего ведома выполнять удаленный код в зависимости от уязвимости и тебе ничего не надо делать, лишь зайти на него. Антивирь ессесно такое обычно заблочит в большинстве случаев. На все остальные случаи есть обновление програм, обновления системы и закрытие дыр уязвимостей в них и системе.

**Comment by kopyurff** [comment]
Если называть вещи своими именами, то это бага. Тулза должна работать на старых осях тоже без каких-либо дополнительных действий. Просто ставиться и работать.
