### ISSUE TITLE
Не удаётся отправить закрепленные файлы

### ISSUE THREAD

**Issue by JustDemetrius** [Flowseal/zapret-discord-youtube#757]
Доброго времени суток!
При попытке загрузить прикрепленный файл вместе с сообщением или без него - под конец загрузки вылетает ошибка что загрузка не удалась. Пробовал на домен attachements подрубить прокси, но тоже не помогло. Версия стоит последняя.
Буду благодарен за совет по решению данной проблемы)

**Comment by serpen7** [comment]
Дискорд в последнее время штормит сам по себе так что тут сказать в чем проблема будет малость проблематично.

**Comment by JustDemetrius** [comment]
> Дискорд в последнее время штормит сам по себе так что тут сказать в чем проблема будет малость проблематично.

Понял, просто у других людей все ок. Видимо особенности от провайдера...

**Comment by JustDemetrius** [comment]
@serpen7 если не сложно, можете подсказать возможные способы решить эту проблему дополнительными действиями? Я уточнил что данная проблема у меня из Крыма встречается, с других регионов нет. Быть может можно как то добавить ip  в список? Через prxyfier пытался отловить куда стучится дискорд в момент загрузки, но ничего не показывает.

**Comment by serpen7** [comment]
> @serpen7 если не сложно, можете подсказать возможные способы решить эту проблему дополнительными действиями? Я уточнил что данная проблема у меня из Крыма встречается, с других регионов нет. Быть может можно как то добавить ip в список? Через prxyfier пытался отловить куда стучится дискорд в момент загрузки, но ничего не показывает.

а какая версия программы и какой батник используете?

**Comment by JustDemetrius** [comment]
> > @serpen7 если не сложно, можете подсказать возможные способы решить эту проблему дополнительными действиями? Я уточнил что данная проблема у меня из Крыма встречается, с других регионов нет. Быть может можно как то добавить ip в список? Через prxyfier пытался отловить куда стучится дискорд в момент загрузки, но ничего не показывает.
> 
> а какая версия программы и какой батник используете?

1.6.1, service install самый первый ALT
Буквально только что решил все ALT варианты попробовать и заработало на самом первом(видимо ранее я его пропускал). Полагаю все таки особенности провайдера. Спасибо!

**Comment by JustDemetrius** [comment]
> > @serpen7 если не сложно, можете подсказать возможные способы решить эту проблему дополнительными действиями? Я уточнил что данная проблема у меня из Крыма встречается, с других регионов нет. Быть может можно как то добавить ip в список? Через prxyfier пытался отловить куда стучится дискорд в момент загрузки, но ничего не показывает.
> 
> а какая версия программы и какой батник используете?

1.6.1, service install самый первый ALT
Буквально только что решил все ALT варианты попробовать и заработало на самом первом(видимо ранее я его пропускал). Полагаю все таки особенности провайдера. Спасибо!
