### ISSUE TITLE
Вирусы?

### ISSUE THREAD

**Issue by I-Synthesizer** [Flowseal/zapret-discord-youtube#759]
Почему в winws.exe virus total показывает трояны?
![image](https://github.com/user-attachments/assets/7030c543-9622-4c8a-969f-48e2cf72d42c)

**Comment by serpen7** [comment]
откуда ты качал? И что именно?https://www.virustotal.com/gui/file/0453fce6906402181dbff7e09b32181eb1c08bb002be89849e8992b832f43b89?nocache=1
У винвс да поведение трояна из за использования драйвера виндайверт фильтра и мода трафика на что и предусмотрена програма, но столько срабатываний не должно быть. Однако даже в твоем скрине по сигнам видно что эвристики срабатывают но не могут определить сигнатуру поэтому они ставят generic, agent, suspicious, malicious и прочее.

**Comment by Eptiy** [comment]
Хэш не совпадает с winws из последних версий. Либо ты качал с другого репозитория, либо качал старую версию. Но winws чистый, такой же включен в https://github.com/N3M1X10/zapret_build.
