### ISSUE TITLE
Конфликт goodbyeDpi и service_goodbye_discord

### ISSUE THREAD

**Issue by braintds** [Flowseal/zapret-discord-youtube#76]
был включен запрет, по запарке включил параллельно гудбай, все работало, спустя час ютуб отъехал и больше не вставал. выполнил действия из ридми, ноль эффекта. Ни через гудбай ни через запрет ютуб не грузит. Удалял службы, ребутал, не помогло. есть идеи как пофиксить?

**Comment by fr-nzy** [comment]
Схожая проблема. 

Запустил гдпи после запрета - отвалился ютьюб. Ремувнул службу запрета, ютуб заработал на несколько минут и упал, больше не вставая при любых манипуляциях

**Comment by PunisherT1000** [comment]
Пользовался только goodbyedpi все работало, поставил zapret по инструкции все работает а видео в ютуб умерло, пробовал перезапустить ничего и перезагрузка не дала ничего, короче щас даже через goodbyedpi ютуб по старому не работает.

**Comment by Flowseal** [comment]
Попробуйте почистить WinDivert:
> sc stop WinDivert
> sc delete WinDivert

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90

**Comment by PunisherT1000** [comment]
![image](https://github.com/user-attachments/assets/e935edae-3e31-4e45-91e5-254330430f79)

**Comment by PunisherT1000** [comment]
сделал как вы посоветовали, но это не помогло, перезапустил после goodbyeDpi, видео так же мертво

**Comment by PunisherT1000** [comment]
в общем перепробовал все возможное, goodbyeDpi полностью перестал работать после запуска zapret, перезапуски и
sc stop WinDivert
sc delete WinDivert
ничем не помогли, остался только один вариант при котором работает у меня ютуб, это discord_youtube с измененным badseq, и то видео кое как запускается примерно через 10 секунд, как это пофиксить я так не понял, перечитал весь мануал и не нашел присета такого как в goodbyeDpi при котором видео и заход в дискорд был мгновенным, кроме подключения к голосу, только по этому и решил попробовать zapret.
Хотелось бы хотя бы вернуть goodbyeDpi в рабочее состояние до всего этого.
Если Автору zapret это как то поможет то вот мои работающие настройки, может в этой проге есть похожие просто я не смог разобраться  --auto-ttl 1-7-10 -e1 -f1 --reverse-frag --wrong-seq -q --fake-gen 12

**Comment by SistemEvil223** [comment]
> в общем перепробовал все возможное, goodbyeDpi полностью перестал работать после запуска zapret, перезапуски и sc stop WinDivert sc delete WinDivert ничем не помогли, остался только один вариант при котором работает у меня ютуб, это discord_youtube с измененным badseq, и то видео кое как запускается примерно через 10 секунд, как это пофиксить я так не понял, перечитал весь мануал и не нашел присета такого как в goodbyeDpi при котором видео и заход в дискорд был мгновенным, кроме подключения к голосу, только по этому и решил попробовать zapret. Хотелось бы хотя бы вернуть goodbyeDpi в рабочее состояние до всего этого. Если Автору zapret это как то поможет то вот мои работающие настройки, может в этой проге есть похожие просто я не смог разобраться --auto-ttl 1-7-10 -e1 -f1 --reverse-frag --wrong-seq -q --fake-gen 12

автору похуй, он мне через знакомого ответил "хочешь чтобы я что-то сделал, плати 100$, либо иди нахуй. Не мешай в WarThunder играть"
