### ISSUE TITLE
не загружается видео и не загружает файлы из дискорда

### ISSUE THREAD

**Issue by posevok** [Flowseal/zapret-discord-youtube#766]
Что мне делать?

**Comment by jmnemonick123** [comment]
Такая же проблема сегодня появилась, вчера было ок всё, не открывается именно cdn.discordapp.com и просто discordapp.com оба домена в списке есть в файле list-discord.txt

UPD: В общем заметил, что если запускать general.bat, то возникает такая проблема, однако при запуске discord.bat такая проблема пропадает. Дальше копать не получилось, к сожалению сильно в этом не разбираюсь, может кто подскажет, что можно поменять в general.bat чтобы все работало так же как и с батником чисто для дискорда.

Пока обхожу эту проблему собственно запуская сначала дискорд.бат, потом сам дискорд и потом вырубаю дискорд бат и врубаю генерал.бат, пока работает, посмотрю как будет дальше и обновлю инфу.

**Comment by posevok** [comment]
> Такая же проблема возникла сегодня, вчера всё работало, не открывается именно cdn.discordapp.com и просто discordapp.com оба домена есть в списке в файле list-discord.txt
> 
> UPD: В общем, заметил, что если запускать general.bat, то возникает такая проблема, однако при запуске discord.bat такая проблема исчезает. Дальше копать не получилось, к сожалению, я не сильно в этом разбираюсь. Может, кто подскажет, что можно изменить в general.bat, чтобы все работало так же, как и с батником только для дискорда.
> 
> Пока я обхожу эту проблему, запуская сначала discord.bat, потом сам Discord, а затем выключаю discord.bat и включаю general.bat. Пока работает, посмотрю, что будет дальше, и обновлю информацию.

спасибо за помощь!

**Comment by johnnyd-78** [comment]
> может кто подскажет, что можно поменять в general.bat

Ничего. Они абсолютно идентичны в плане стратегий для дискорда. Менять надо list-general.txt - удалять оттуда все, что имеет discord в названии и потом вставлять такое:
```
discord.com
discord.gg
discordapp.com
discordapp.io
discordapp.net
discord.media
discordcdn.com
discordstatus.com
discord-attachments-uploads-prd.storage.googleapis.com
```

Смешно. Самая известная сборка на основе zapret в рунете (не считая лаунчера), а списки как-будто какой-то шкальник составлял, который ни запрета ни гудбая никогда не видел о_О

**Comment by Gxtod** [comment]
> Смешно. Самая известная сборка на основе zapret в рунете (не считая лаунчера), а списки как-будто какой-то шкальник составлял, который ни запрета ни гудбая никогда не видел о_О

А мб это ты школьник не? Твои тупые комментарии везде как затычка в бочке.
Давай ка по фактам раскидаем, из того списка шо ты тут накалякал, у меня в лист-генерал да ищО и тхт отсутствовала лишь одна строчка **ОДНА СТРОЧКА !!!** А именно:

**discordapp.io**

**Comment by johnnyd-78** [comment]
Давайкать будешь маме своей, хамло. Иди потеряйся

**Comment by igormeat** [comment]
ща попробовал добавить в list-general.txt сайт cdn.discordapp.com , помогло прогружать видосы не из ютуба. перезагрузить дискорд надо после изменения файла

**Comment by Eptiy** [comment]
> ща попробовал добавить в list-general.txt сайт cdn.discordapp.com , помогло прогружать видосы не из ютуба. перезагрузить дискорд надо после изменения файла

он там уже был, у тебя либо версия старая, либо билд другой.

**Comment by Eptiy** [comment]
> Смешно. Самая известная сборка на основе zapret в рунете (не считая лаунчера), а списки как-будто какой-то шкальник составлял, который ни запрета ни гудбая никогда не видел о_О

Спасибо за наводку на discordapp.io, но _**учись себя адекватно вести в обществе**_. Ни в одном списке я не видел discordapp.io. То, что его здесь не было - ничего не говорит о компетентности автора. То, что ты не сравнил списки и не предложил добавить именно discordapp.io - многое говорит о твоей компетентности.

**Comment by Eptiy** [comment]
Добавлю, что в списке доменов дискорда (https://github.com/v2fly/domain-list-community/blob/master/data/discord)
discordapp.io помечен, как "unused". То есть это ещё надо проверить, меняет его добавление что-то, или нет.

**Comment by Eptiy** [comment]
Обновление по теме: discordapp.io ожидаемо ничего не меняет - https://github.com/Flowseal/zapret-discord-youtube/issues/761#issuecomment-2489140094

**Comment by Eptiy** [comment]
Проверяйте работу в браузере при работающем Secure SNI. https://github.com/Flowseal/zapret-discord-youtube/issues/761#issuecomment-2489478690

**Comment by johnnyd-78** [comment]
@Eptiy Не создавай себе кумиров и учись адекватно воспринимать критику. Если лист дискорда в сборке - гвно, на это никак не повлияет то, "научусь я себя вести в твоем обществе" или нет
К слову, этот домен указан техподдержкой дискорда как используемый и нужный для работы дискорда, и уж ей я поверю больше, чем тебе

**Comment by Eptiy** [comment]
@johnnyd-78, слушай, давай ты по существу будешь писать, а не чирикать тут про то, кому ты веришь, а кому нет. Я выше привёл источник с доменами, где он выписан, как неиспользуемый, привёл пример, где его добавление ничего не решило, помог решить ту проблему в итоге другим способом. Мне вообще плевать, кому ты веришь. Факт в том, что ты обосрал разраба ни за что, и срёшься тут сидишь дальше не по теме. Самый умный - иди создай свой репозиторий.

**Comment by johnnyd-78** [comment]
Ты ответ от топикстартера тут видел, помогло или нет? Вот и я не видел, а твои выводы, что нужно, а что нет - это твои выводы, можишь их себе затолкать куда солнце не светит. Я хз что ты вообще вместе с этим неадекватом влез в разговор, который тебя вообще не касается. Видимо, тут это в порядке вещей.

**Comment by Eptiy** [comment]
Иди в баню, короче. До тебя донести что-то, как раком до Китая проползти. Сидит хамит всем налево и направо, когда можно было изначально написать "попробуйте добавить то-то туда-то" и "школьниками" не кидаться. Ещё и возникает, будто невинный.

**Comment by johnnyd-78** [comment]
Спасибо, и тебе удачно попариться :) Ну а если ты не различаешь "школьник" и "как-будто какой-то школьник" - это твоя проблема, тут ее никто не решит, извини.
Ты не тот человек, который до меня может что-то "донести", не вышел по некоторым параметрам. И твоя поза в этот момент ничего в этом не изменит.
Ладно, до свидания, сиди дальше оценки посетителям репозитория ставь

**Comment by Flowseal** [comment]
Попробуйте ALT'ы. Можете поискать решение тут - https://github.com/Flowseal/zapret-discord-youtube/issues/761
