### ISSUE TITLE
Дискорд CDN и 7TV

### ISSUE THREAD

**Issue by implave** [Flowseal/zapret-discord-youtube#768]
**Проблема:** Как и у многих тут не загружаются файлы (видео, открытие оригиналов) с дискордовского сидиэна, не грузятся некоторые смайлики и аватарки, ещё не работает 7TV с обычными general.bat. 
- версия последняя
- 162.159.129.233 добавлен в ipset-discord
- cloudflare-ech.com и прочие cdn адреса во всех текстовых есть

Единственное, что помогает, это изменение в батнике --dpi-desync=fake,split на --dpi-desync=disorder, как было в одном из комментариев в обсуждениях. Но, как там и отметили, это ломает абсолютно загрузку видео на ютубе.

**Вопрос:** Можно ли как-то разбить в батнике листы на 2, чтоб **list-discord** (и 7tv, ffz и тд.)  использовал **--dpi-desync=disorder** и, к примеру, **list-youtube** использовал **--dpi-desync=fake,split**? Потому что сейчас приходится иметь 2 батника и менять их в зависимости от необходимости.

**Comment by serpen7** [comment]
почему нельзя, у вас есть набросок конфига с листами, вы сами можете прописать и вписать свои листы разделив их, создав новые текстовики с листами и указав их в качестве разделения схем махинации с трафиком, так разные хосты из листов будут использовать разные стратегии обхода которые вы укажете.
list discord
list youtube 
Это что-то из старых версий проги насколько я помню?

**Comment by Flowseal** [comment]
```bash
start "zapret: general" /min "%BIN%winws.exe" --wf-tcp=80,443 --wf-udp=443,50000-50100 ^
--filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-udp=50000-50100 --ipset="ipset-discord.txt" --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --new ^
--filter-tcp=80 --hostlist="list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-tcp=443 --hostlist="list-discord.txt" --dpi-desync=disorder --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin" --new ^
--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake,split --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"
```

**Comment by serpen7** [comment]
> ```shell
> start "zapret: general" /min "%BIN%winws.exe" --wf-tcp=80,443 --wf-udp=443,50000-50100 ^
> --filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
> --filter-udp=50000-50100 --ipset="ipset-discord.txt" --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --new ^
> --filter-tcp=80 --hostlist="list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
> --filter-tcp=443 --hostlist="list-discord.txt" --dpi-desync=disorder --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin" --new ^
> --filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake,split --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"
> ```

а смысл если в лист дискорд и дженерале дублируются те же хосты? На них все равно же будет действовать и дисордер и фейк и сплит этим? Человеку нужно писать свой конфиг и добавлять свой лист чтобы "работал тот же дженерал батник" нормально со своей стратегией. Либо полностью переделывать структуру general листа разграничивая его и переписывая под новые листы конфиг, чтобы то что работало на ютуб работало на ютуб, то что нужно на дискорд будет работать на дискорд, как дженерал батник в целом но с разной стратегией на разные ресурсы
