### ISSUE TITLE
Не работает на провайдере МТС

### ISSUE THREAD

**Issue by del2H** [Flowseal/zapret-discord-youtube#77]
Сделал как всё указано, Discord работает, но идёт бесконечное подключение в голосовые чаты. Такая же проблема у моего знакомого (также провайдер МТС) и у человека с этим [issue](https://github.com/Flowseal/zapret-discord-youtube/issues/11). Кто-то знает что надо сделать? Или на этом провайдере проблема вряд-ли решаема?

**Comment by Egocentrism** [comment]
Как решишь проблему отпиши пожалуйста

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
