### ISSUE TITLE
Не грузятся видео на ютубе

### ISSUE THREAD

**Issue by BlackWolf212006GTHB** [Flowseal/zapret-discord-youtube#770]
ни в general ни в discord ютуб не хочет грузится
помогите народ!

**Comment by johnnyd-78** [comment]
В дискорд он грузиться и не будет.
В general можно попробовать поменять
`--filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^`
на
`--filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake,udplen --dpi-desync-udplen-increment=5 --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --dpi-desync-cutoff=n3 --dpi-desync-repeats=2 --new ^`

А
`--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake,split --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"`
на
`--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=split --dpi-desync-fooling=md5sig,badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin" --dpi-desync-split-tls=sni --dpi-desync-repeats=10 --dpi-desync-autottl`

Сохранить измененный cmd, перезапустить. Перезапустить браузер. Проверить ютуб

**Comment by ghost** [comment]
> В дискорд он грузиться и не будет. В general можно попробовать поменять `--filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^` на `--filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake,udplen --dpi-desync-udplen-increment=5 --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --dpi-desync-cutoff=n3 --dpi-desync-repeats=2 --new ^`
> 
> А `--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake,split --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"` на `--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=split --dpi-desync-fooling=md5sig,badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin" --dpi-desync-split-tls=sni --dpi-desync-repeats=10 --dpi-desync-autottl`
> 
> Сохранить измененный cmd, перезапустить. Перезапустить браузер. Проверить ютуб


а где менять в каком файле точнее

**Comment by ghost** [comment]
и еще вопрос
если в цмд то его надо каждый раз так делать?

**Comment by CyberWot** [comment]
> и еще вопрос, если в цмд то ему надо каждый раз так делать?

General bat через правую клавишу мыши.нажать изменить. откроется блокнот. стереть старые строчки и вместо них вставить новые которые Вам предложили, потом сохранить все это дело и все. далее по инструкции запускаете батник и потом браузер.проверяете работу ютуба. делается это 1 раз. так как уже внесенные данные сохраняются в бат файле. 
меняете строчки которые перечеркнуты красным цветом. это как пример
![Безымянный](https://github.com/user-attachments/assets/3e89f536-e018-414c-8956-c8ba81db7c6c)

**Comment by ghost** [comment]
спасибо

**Comment by Flowseal** [comment]
> --dpi-desync=fake,udplen --dpi-desync-udplen-increment=5

🫡
