### ISSUE TITLE
Видео перестают загружаться на 59 секунде

### ISSUE THREAD

**Issue by EgoaRro** [Flowseal/zapret-discord-youtube#773]
При иcпользовании любого батника ютуб работает, однако видео перестают дальше грузиться ровно на 59 секунде, пытался пользоваться впном - такая же проблема. Раньше все было нормально. Помогите пожалуйста  :(

**Comment by Sansel57** [comment]
Connection Speed постепенно падает

**Comment by foxaxaN1** [comment]
у мене такойже проблема

**Comment by foxaxaN1** [comment]
как решить
