### ISSUE TITLE
Сервис не "дружит" с Call of Duty

### ISSUE THREAD

**Issue by stSkamSX** [Flowseal/zapret-discord-youtube#778]
Доброго! Если запускать ваш сервис, все работает кроме Колды. При запущенной программке, Коду вышибает на стадии проверки сетевого соединения, это можно как-то починить?

**Comment by Flowseal** [comment]
Нельзя. Устанавливайте zapret на роутер, используйте что-то ещё или выключайте ПО во время игры

**Comment by stSkamSX** [comment]
> Нельзя. Устанавливайте zapret на роутер, используйте что-то ещё или выключайте ПО во время игры

Спасибо.
