### ISSUE TITLE
МГТС не открывается дискорд MGTS

### ISSUE THREAD

**Issue by trxsted** [Flowseal/zapret-discord-youtube#780]
Пробовал все старые версии,новую тоже попробовал,каждый батник пооткрывал,не заработало ни разу,не то что не пускает к войсам даже не открывается дискорд,батник с наименованием МГТС тоже пробовал открывать,не работает,может у кого так же было подскажите как решить это? Уже с ума сводит без дискорда жить
![image](https://github.com/user-attachments/assets/30ed816c-2685-4981-aef2-91848e9f9456)
(Это даже с изменением в строчке —filter-tcp=443,убрал ,split)

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
