### ISSUE TITLE
Перестали отображаться картинки аватарки каналов и людей.

### ISSUE THREAD

**Issue by HimmelsSturmer** [Flowseal/zapret-discord-youtube#781]
Перестали отображаться все аватарки каналов и людей. Накатил вчера версию 1.6.1. До этого лишь небольшая часть не отображалась. 

![image](https://github.com/user-attachments/assets/cb0a70ef-ec32-4cc7-8283-4353a705c3a4)

**Comment by HimmelsSturmer** [comment]
Пытался переустановить сервис на всякий случай. Не помогло.

**Comment by Yasaka1Magatama** [comment]
Мне помогло запустить дискорд с совместимостью с виндовс 8. Пока грузится дискорд откоючить совместимость и после загрузки все аватарки наместе только голосовой неработает.

**Comment by EgorWeders** [comment]
Вы учитывайте, что некоторые варианты обходов перестают быть рабочими со временем и это нормально.

**Comment by Eptiy** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252#discussioncomment-11340177

**Comment by XacHi92** [comment]
Мне помогло вот это: https://github.com/Flowseal/zapret-discord-youtube/issues/607#issuecomment-2460571309

**Comment by AndreyK54** [comment]
> Мне помогло вот это: [#607 (comment)](https://github.com/Flowseal/zapret-discord-youtube/issues/607#issuecomment-2460571309)
если в ipset поставить disorder перестаёт работать голосовая связь

**Comment by AndreyK54** [comment]
Мне помогло вот это: --dpi-desync=fake поменял на disorder в строчках filter-udp=443 и filter-tdp=443
Вот так выглядит оригинальный файл discord.bat:
![image1](https://github.com/user-attachments/assets/d17aa3dd-e87e-4d57-ab04-2de9b5452d41)
Вот так я прописал у себя и все работает, и голосовой и картинки грузятся:
![image2](https://github.com/user-attachments/assets/202daa1d-fcd3-4cee-b765-961951f2aed8)
Так же у меня в ipset-discord.txt дописан еще адрес 162.159.129.233

**Comment by ShrikerChestTrees** [comment]
> Мне помогло вот это: --dpi-desync=fake поменял на disorder в строчках filter-udp=443 и filter-tdp=443
Так же у меня в ipset-discord.txt дописан еще адрес 162.159.129.233

Я так сделал, только теперь вылетает zapret discord при запуске.

**Comment by ShrikerChestTrees** [comment]
> Я так сделал, только теперь вылетает zapret discord при запуске.

Я заметил, что надо убрать ещё и ",split".
Теперь всё работает ~~кроме голосовых~~.

**Comment by ShrikerChestTrees** [comment]
Когда захожу в голосовые, то оно может не работать (Долгое подключение), а может работать.
Есть новые решения проблем?

**Comment by AndreyK54** [comment]
> Когда захожу в голосовые, то оно может не работать (Долгое подключение), а может работать. Есть новые решения проблем?

Не знаю,у меня все нормально сейчас работает. Может от провайдера зависит еще. Скорее всего, нужно подбирать другие параметры в строчке ipset. Не особо разбираюсь в этой программе, не могу подсказать какие параметры менять, просто предполагаю.

**Comment by ShrikerChestTrees** [comment]
> Когда захожу в голосовые, то оно может не работать (Долгое подключение), а может работать. Есть новые решения проблем?

Оказывается оно долго подключается к гс, но у других быстро заходит...

**Comment by Eptiy** [comment]
Ты уверен, что у тебя запрет вылетал из-за split? Может быть, ты сервисы забыл удалить или ещё что? Возможно, этот параметр важен для работы голосовых.

**Comment by ShrikerChestTrees** [comment]
> Не знаю,у меня все нормально сейчас работает. Может от провайдера зависит еще. Скорее всего, нужно подбирать другие параметры в строчке ipset. Не особо разбираюсь в этой программе, не могу подсказать какие параметры менять, просто предполагаю.

Удалил --ipset="ipset-discord.txt" и теперь RTC подключение быстрее подключается к голосовым каналам (В которых запрещён микро).

**Comment by ShrikerChestTrees** [comment]
> Ты уверен, что у тебя запрет вылетал из-за split? Может быть, ты сервисы забыл удалить или ещё что? Возможно, этот параметр важен для работы голосовых.

Да, а если поглядеть, то у того был удалён split и поэтому у него не вылетал.
Предполагаю, что ,split предназначен для fake, а не для disorder.

**Comment by ShrikerChestTrees** [comment]
Заметил, что я подключаюсь только к гс каналам, где заблокирован микрофон.

**Comment by ShrikerChestTrees** [comment]
Оказывается у меня МТС и пришлось поставить код для МТС и теперь всё работает, только подключаться к гс очень долго, но оно хотя бы происходит и пинг показывает нормальный (20-23 ms).

**Comment by ShrikerChestTrees** [comment]
Оказывается, что оно работает, но это подключение долгое, чем тогда (до 21 ноября)...
Есть способ ускорения?

**Comment by HimmelsSturmer** [comment]
Как итог, я единственное что сделал, это добавил новый домен: 162.159.129.233 в файл ipset-discord и все снова заработало. Всем спасибо.

**Comment by HimmelsSturmer** [comment]
BB
