### ISSUE TITLE
Не работает ни один батник на ноутбуке

### ISSUE THREAD

**Issue by KiVi00** [Flowseal/zapret-discord-youtube#782]
На ПК (по кабелю) и первом ноутбуке (по WI-FI) всё работает, а на втором ноутбуке нет. В чем может быть причина или как её определить?

**Comment by EgorWeders** [comment]
Что происходит при запуске батников? Открывается и закрывается окно? И укажите спецификации ноута.

**Comment by serpen7** [comment]
Если в ноуте сетевуха киллер нетворк то нужно в ПО вырубать все оптимизации и фильтры трафика, оно не дает запрету работать.
Вот тут все в ПО киллера должно быть вырублено 
![image](https://github.com/user-attachments/assets/d0076072-78bb-445b-bae4-120026259cee)

**Comment by KiVi00** [comment]
> Если в ноуте сетевуха киллер нетворк то нужно в ПО вырубать все оптимизации и фильтры трафика, оно не дает запрету работать. Вот тут все в ПО киллера должно быть вырублено ![image](https://private-user-images.githubusercontent.com/134365619/388890849-d0076072-78bb-445b-bae4-120026259cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzMzNzgsIm5iZiI6MTczMjI3MzA3OCwicGF0aCI6Ii8xMzQzNjU2MTkvMzg4ODkwODQ5LWQwMDc2MDcyLTc4YmItNDQ1Yi1iYWU0LTEyMDAyNjI1OWNlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMDU3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTc0NzM3ZGIwM2FiMDVjYzRjZmQ1YjhlZGM4NzFjOTU4ZmEwNTAxOGY1ZWM5ZTM1YzRkZjRjZDU2NGFmM2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.y6oPV-MgbeyD6KY22H_hLmfja7_ZG1s-tFfWJac6MMk)

**Comment by KiVi00** [comment]
Помогло отключение оптимизаций в Killer, спасибо
