### ISSUE TITLE
Отключение ECH со стороны клиента

### ISSUE THREAD

**Issue by NullPointerExeptionBruh** [Flowseal/zapret-discord-youtube#789]
У CloudFlare есть функция ECH которая схожа с работой ByeDPI/Zapret и т.д, и из за этого многие сайты не работают, как его можно отключить? TLS 1.3 выключил а на сайт всё равно не заходит (https://www.multiplayerpiano.org)

**Comment by Eptiy** [comment]
Его наоборот нужно включать. Сайты с этой функцией не работают, т.к. cloudflare-ech.com заблокирован ркн. Запрет обходит блокировку ECH.

**Comment by Flowseal** [comment]
Схожа с работой zapret?..
Это включается/выключается на уровне самого cloudflare. Zapret может обойти блокировку ech от ркн
