### ISSUE TITLE
YouTube не грузится

### ISSUE THREAD

**Issue by Derpachi** [Flowseal/zapret-discord-youtube#79]
Не загружается сайт ютуба, при этом дискорд работает прекрасно. Ошибка - ERR_CONNECTION_RESET
![Снимок экрана (1)](https://github.com/user-attachments/assets/cfe8fed1-5ba9-406c-a4ab-51953a5d7cf0)

**Comment by Flowseal** [comment]
Попробуйте отключить Kyber: chrome://flags/kyber#enable-tls13-kyber
Если работало с GoodbyeDPI, то можете пользоваться им параллельно с service_goodbye_discord.bat.
В README.md есть всё необходимое для работы.

**Comment by MAX1MDEV** [comment]
+, gdpi тоже перестал работать

**Comment by ApokGG** [comment]
если и gdpi перестал работать то проверяйте запущенные сервисы, может провайдер новые фильтры поставил, перебирайте новые настройки

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90
