### ISSUE TITLE
🟣 Обход Discord

### ISSUE THREAD

**Issue by Chaser251** [Flowseal/zapret-discord-youtube#792]
Не запускается Call of Duty совместно с zapret !!!
Игра сначала пытается запустится, а потом просто вылетает и в стиме пишет "играть"

**Comment by ShrikerChestTrees** [comment]
Придётся вырубать как это написано в #778 от разработчика...

**Comment by ShrikerChestTrees** [comment]
Придётся вырубать zapret, как это написано в #778 от разработчика...
