### ISSUE TITLE
Пропадает интернет

### ISSUE THREAD

**Issue by GayyGay** [Flowseal/zapret-discord-youtube#795]
Столкнулся с проблемой которая беспокоит меня уже больше месяца. Интернет пропадает на пару секунд, почти каждую минуту(иногда может все работать больше двух часов, но через какое-то время начинается снова) при этом роутер не выключается, а открывается вкладка в браузере с описанием проблемы «DHCP сервер недоступен». Происходит это только при работающем запрете

**Comment by serpen7** [comment]
Возможная проблема роутер, какой он у вас модели? Есть логи в роутере, что пишет на момент падений? От провайдера или свой?

**Comment by GayyGay** [comment]
> Возможная проблема роутер, какой он у вас модели? Есть логи в роутере, что пишет на момент падений? От провайдера или свой?

Модель: Mi Router 4A, покупал сам. Логи посмотрю скину что найду

**Comment by GayyGay** [comment]
![image](https://github.com/user-attachments/assets/f7d90666-5bb1-45eb-8393-dd3bfe0d970e)
момент падения

**Comment by GayyGay** [comment]
![image](https://github.com/user-attachments/assets/828cf147-ceb0-4542-81d1-e9fbe1a45a87)

**Comment by Eptiy** [comment]
QoS выключить пробовал?

**Comment by serpen7** [comment]
> ![image](https://private-user-images.githubusercontent.com/130283156/389895883-f7d90666-5bb1-45eb-8393-dd3bfe0d970e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjYyNjEsIm5iZiI6MTczMjYyNTk2MSwicGF0aCI6Ii8xMzAyODMxNTYvMzg5ODk1ODgzLWY3ZDkwNjY2LTViYjEtNDVlYi04MzkzLWRkM2JmZTBkOTcwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMjU5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWM5ZDg4YTNiZjY2YjhiOWQ4ZmIzMjg0MDA5OTkxNGVkMzRjNTE4MmVmZGE2MWI4NzMzNTYwMjczNjkyOGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qBcOD4nY3zCQonkgcynCWqx7ufYRQ_9PVdUS0PVa8aw) момент падения

чето в настройках роутера по самой сети, скорее всего связанно с его службой по контролю трафика или подобного. А еще заметил странность что роутер пытается уйти в слип. Это какая то энергосберегайка походу. В общем надо копаться в настройках роутера, чето ему не нравится в трафике и он дропает коннект, а потом якобы уходит в слип без палева, потому что брокера нет.

Тут малость непонятная игра слов, если брокер и клиент это одно и тоже, то тогда роутер отрубает коннект по какому то правилу сети, а если брокер это поставщик интернета ака твой провайдер, то тут как бы вопросы почему твой пров гасит иннет при каких то условиях. Непонятно немного, но настройки роутера покопать бы стоило на предмет энергосберегаек и вообще фильтров трафика\балансировки.

**Comment by GayyGay** [comment]
> > ![image](https://private-user-images.githubusercontent.com/130283156/389895883-f7d90666-5bb1-45eb-8393-dd3bfe0d970e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjYyNjEsIm5iZiI6MTczMjYyNTk2MSwicGF0aCI6Ii8xMzAyODMxNTYvMzg5ODk1ODgzLWY3ZDkwNjY2LTViYjEtNDVlYi04MzkzLWRkM2JmZTBkOTcwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMjU5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWM5ZDg4YTNiZjY2YjhiOWQ4ZmIzMjg0MDA5OTkxNGVkMzRjNTE4MmVmZGE2MWI4NzMzNTYwMjczNjkyOGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qBcOD4nY3zCQonkgcynCWqx7ufYRQ_9PVdUS0PVa8aw) момент падения
> 
> чето в настройках роутера по самой сети, скорее всего связанно с его службой по контролю трафика или подобного. А еще заметил странность что роутер пытается уйти в слип. Это какая то энергосберегайка походу. В общем надо копаться в настройках роутера, чето ему не нравится в трафике и он дропает коннект, а потом якобы уходит в слип без палева, потому что брокера нет.

Я понизил уровень сигнала 5g. Вроде бы результат есть

**Comment by GayyGay** [comment]
> QoS выключить пробовал?

нет

**Comment by serpen7** [comment]
> Я понизил уровень сигнала 5g. Вроде бы результат есть

это трогать смысла нет, там вопрос в другом.

**Comment by Eptiy** [comment]
> > QoS выключить пробовал?
> 
> нет

в последних строчках роутер ругался на то, что сам же и выключил qos, попробуй выключить его в принципе.

**Comment by GayyGay** [comment]
> > > QoS выключить пробовал?
> > 
> > 
> > нет
> 
> в последних строчках роутер ругался на то, что сам же и выключил qos, попробуй выключить его в принципе.

он отключен был

**Comment by serpen7** [comment]
Мне кажется тебя пров отрубает от сети. 
![image](https://github.com/user-attachments/assets/e8ca9d29-12e7-48ab-b09b-7698c6a1fe2e)
Потому что у тебя даже аутентификация сразу не проходит при переподключении. Почему? А это надо спрашивать у провайдера и вряд ли обычный сотрудник ТП будет это знать. Это надо на чувака который этой системой заведует и знает как она работает спрашивать.

**Comment by serpen7** [comment]
> > > QoS выключить пробовал?
> > 
> > 
> > нет
> 
> в последних строчках роутер ругался на то, что сам же и выключил qos, попробуй выключить его в принципе.

это не ругательства это обычное уведомление о том что роутер не может выполнять функции контроля трафика без включенного QOS. Стандартные вещи когда оно выключенно и просто скипается по сути, но в логах идут сообщения о том что роутер это инициализирует по стандартной процедуре, чтобы потом уже грузить остальные модули которые работают.

**Comment by GayyGay** [comment]
> Мне кажется тебя пров отрубает от сети. ![image](https://private-user-images.githubusercontent.com/134365619/389990725-e8ca9d29-12e7-48ab-b09b-7698c6a1fe2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTI3OTMsIm5iZiI6MTczMjY5MjQ5MywicGF0aCI6Ii8xMzQzNjU2MTkvMzg5OTkwNzI1LWU4Y2E5ZDI5LTEyZTctNDhhYi1iMDliLTc2OThjNmExZmUyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwNzI4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDEwNjQxOWE5MTUxNGZlZmFmODQyM2FjZmJmN2U3MzRiYzM2ZDAyY2Q3YzJkMTE2ZWQ2YzczMThhYzI2YmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B-ZMhhAU3gDI4p_emKtIfUvOC6GWWLyuB1xIuKSvq9g) Потому что у тебя даже аутентификация сразу не проходит при переподключении. Почему? А это надо спрашивать у провайдера и вряд ли обычный сотрудник ТП будет это знать. Это надо на чувака который этой системой заведует и знает как она работает спрашивать.

Я тогда провайдеру напишу, скажу что мне скажут

**Comment by GayyGay** [comment]
Написал провайдеру. Пришел сотрудник. посмотрел провода, сейчас вроде бы все нормально. Спасибо кто помогал))
