### ISSUE TITLE
Не загружает аватарки сервера, других пользователей

### ISSUE THREAD

**Issue by flatixxx** [Flowseal/zapret-discord-youtube#796]
Где-то недели 3 назад у всех перестали работать аватарки
Скачал апдейт который исправил эту проблему
Но спустя какое-то время опять началось
Аватарки не загружает
По каким-то причинам грузит только спустя какое то время некоторые аватарки
Но большинство остаются такими же серыми
![image](https://github.com/user-attachments/assets/a9225ce0-9b2c-43e4-9a5e-05641cdf3592)

**Comment by RailingM4n** [comment]
Я сначала пользовался батником МГТС,такая же фигня случилась,недавно перешел на батник МГТС2 и все аватарки и прочее вернулись. Поэтому просто попробуй другие батники позапускать,возможно пофиксится у тебя,у меня они пофиксились по крайней мере

**Comment by flatixxx** [comment]
> Я сначала пользовался батником МГТС,такая же фигня случилась,недавно перешел на батник МГТС2 и все аватарки и прочее вернулись. Поэтому просто попробуй другие батники позапускать,возможно пофиксится у тебя,у меня они пофиксились по крайней мере

Спасибо. Запустил МГТС2 батник и аватарки вернулись. Огромное спасибо
