### ISSUE TITLE
Можно ли закрывать консоль?

### ISSUE THREAD

**Issue by whtgrp** [Flowseal/zapret-discord-youtube#797]
Можно ли закрывать консоль или для работы дс она должна быть открыта во время использования дс непосредственно? Просто уточнение <3

**Comment by Eptiy** [comment]
Если ты запускаешь батник - закрывать нельзя, он работает только пока открыт. Если ты устанавливаешь сервис через service_install, после установки сервиса консоль можно закрыть.
