### ISSUE TITLE
Как стримить на ютуб с запретом? 

### ISSUE THREAD

**Issue by Rutja023** [Flowseal/zapret-discord-youtube#799]
Пробовал много разных батников, но проблема всегда одна - слишком низкий битрейт. Пару раз оно запустилось с нормальным битрейтом, но это скорее всего исключения, где-то из 20 попыток две были успешны. Я думаю, что вся проблема в провайдере, у меня ростелеком, у моего друга другой провайдер и у него все работает хорошо. Есть идеи как можно исправить это? Просто раньше использовал ютуб как хранилище видео, а сейчас это не получается.

**Comment by EvilPlayer1** [comment]
у меня на мгтс то же самое. стрим стартует с крайне низким битрейтом и с жёсткими потерями кадров. через 10 сек его отпускает и вроде идёт норм, но через 7 минут примерно он просто отваливается. и так постоянно. отвал, потом обс его поднимает обратно, а потом он опять падает

**Comment by Rutja023** [comment]
> у меня на мгтс то же самое. стрим стартует с крайне низким битрейтом и с жёсткими потерями кадров. через 10 сек его отпускает и вроде идёт норм, но через 7 минут примерно он просто отваливается. и так постоянно. отвал, потом обс его поднимает обратно, а потом он опять падает

я кстати нашел решение, это использовать не запрет, а амнезию, с ней всё прекрасно работает
