### ISSUE TITLE
Проблема с ютуб

### ISSUE THREAD

**Issue by Elisei1337** [Flowseal/zapret-discord-youtube#8]
Добрый день. Проблема с дискордом действительно решена, работают как голосовые чаты, так и текстовые. Но вот ютуб при этом не грузит видео, запускаю discord_youtube.bat от имени админа. Каких либо ошибок не возникает, при это ДС работает. а вот YouTube нет. Может кто сталкивался и знает как пофиксить.

**Comment by nyakokitsu** [comment]
Читай #4

**Comment by Warest-KJ** [comment]
Создал такую же тему, но удалил увидев, что есть эта. Видимо создали одновременно)
Но продублирую сюда тоже самое:
Поставил всё согласно инструкции. Путь без пробелов и кириллицы. Чисто Диск/папка. Запуск от админа. Другие впн отключены, гудбай очищен через ремувку.
При запуске discord_youtube.bat без замечаний начинает работать дискорд, но ютуб и бОльшая часть сайтов не открывается. Пытался пошаманить с параметрами с обсуждений на оригинальном zapret, но не вышло. Подозреваю что проблема в операторе, т.к. тот же гудбай пришлось перенастраивать несколько раз.

**Comment by Elisei1337** [comment]
Дополню, что все-таки 10 мин было открыто видео, не грузилось. Только создал Issue и ютуб магическим образом заработал и видео включилось само. Магия ли, но пока работает. Другие сайты итак работали, проблема были именно с ютубом

**Comment by Flowseal** [comment]
Вы можете пользоваться привычным обходом ютуба (например, goodbyedpi) вместе с обходом только дискорда из этого репозитория. Обход ютуба зависит от провайдера к провайдеру и может требовать изменения аургментов.

P.S Если вы используете гудбайдипиай, то zapret должен быть заупен ПОСЛЕ.
