### ISSUE TITLE
Не работает не знаю почему 

### ISSUE THREAD

**Issue by CiL2951** [Flowseal/zapret-discord-youtube#80]
![IMG_20241009_211935_824](https://github.com/user-attachments/assets/8e233bd2-59d9-4696-8f1c-84ca1df972d2)
Не работает виндофс 11

**Comment by l4yw33** [comment]
Путь содержит пробелы.
Пожалуйста, переместите скрипт в директорию без пробелов.

**Comment by CiL2951** [comment]
Это где?

**Comment by CiL2951** [comment]
Где именно я на рабочий стол папку добавил

**Comment by Flowseal** [comment]
> Где именно я на рабочий стол папку добавил

рабочий стол. Пробел видите между словами?
Распакуйте архив в папку в корень диска

**Comment by CiL2951** [comment]
Всё нормально спасибо за помощь

**Comment by yar83** [comment]
Не грузится видео в ютубе, в батнике service_discord_youtube написано убрать пробелы, но там нет никаких пробелов. Папка с программой распакована в корень диска С. Путь расположения батника: "C:\zapret-discord-youtube-main". Подскажите что делать?

**Comment by CiL2951** [comment]
> Не грузится видео в ютубе, в батнике service_discord_youtube написано убрать пробелы, но там нет никаких пробелов. Папка с программой распакована в корень диска С. Путь расположения батника: "C:\zapret-discord-youtube-main". Подскажите что делать?
ты скачал распакуй через winrar в загрузки и запусти файл
