### ISSUE TITLE
не могу удалить старый запрет что-бы установить новый

### ISSUE THREAD

**Issue by lolasaman** [Flowseal/zapret-discord-youtube#800]
![Снимок экрана 2024-11-24 130721](https://github.com/user-attachments/assets/2b38d520-c1e3-409f-9237-317b56657d9a)
что делать и какую задачу надо завершить?

**Comment by Eptiy** [comment]
Используй service_remove от имени администратора. Перезагрузись. Повтори первый шаг. Проверь наличие службы в диспетчере задач.

**Comment by apexpredatrr** [comment]
спасибо
