### ISSUE TITLE
Почему я вижу слово bitcoin?

### ISSUE THREAD

**Issue by qwreqwrqwer** [Flowseal/zapret-discord-youtube#805]
При попытке удаления пишет что этот файл открыт, как его удалить, и почему я вижу слово Bitcoin.
Заранее говорю, я не разбираюсь в этом, и не говорю что это вирус или майнер, может кто обьяснить, что это за файл?
![5339183522398726708](https://github.com/user-attachments/assets/8096d708-f600-412a-9b78-c51f3236dc29)

**Comment by d-ovs** [comment]
В описании файла (в метаданных) указан адрес некоего Bitcoin-кошелька, вероятно, адрес для пожертвований автору утилиты, но я данный факт не проверял, и принадлежность кошелька сказать не могу. На майнер или вирус прямо или косвенно это не указывает, т.к. это просто строка в метаданных, с таким же успехом можно было, к примеру, написать эту строчку в самом названии файла, или же в ридми рядом с файлом.

**Comment by Alexsuper8783** [comment]
Что бы корекктно удалить zapret нужно сначало открыть service_remove.bat что бы убрать сервис работающий на фоне

**Comment by EgorWeders** [comment]
Это адрес кошелька разраба WinDivert Basil для пожертвований. А не удаляется он потому что у вас он используется сервисом либо чем-то другим.
