### ISSUE TITLE
Не работают именно на моём пк, и на ноуте гс каналы(все) версия 1.6.1(у моего соседа всё работает, впны все выключенны, а каких-то сильных отличий в программах нет, или я что-то не замечаю) провайдер Ростелеком

### ISSUE THREAD

**Issue by HeromenYOUTUBE** [Flowseal/zapret-discord-youtube#809]

**Comment by HeromenYOUTUBE** [comment]
идёт "типо" подключение к RTC, а после идёт "не установлен маршрут"

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by cairojr** [comment]
ARENA BREAKOUT HAck + Beta KEY 

When I try to download the cheat to test it shows an error in the download link, I can't download it.
