### ISSUE TITLE
Требуется драйвер с цифровой подписью

### ISSUE THREAD

**Issue by Kubrix** [Flowseal/zapret-discord-youtube#81]
Win7x64 
Запуск discord_youtube.bat от имени админа
Окно быстро закрывается
Система выдает сообщение

![image](https://github.com/user-attachments/assets/d167bcfa-e53f-4910-8947-a673be387fd9)

**Comment by Flowseal** [comment]
Работа на windows7 не гарантирована. Выдержка со страницы GoodbyeDPI:
> Horribly outdated Windows 7 installations are not able to load WinDivert driver due to missing support for SHA256 digital signatures. Install KB3033929 [x86](https://www.microsoft.com/en-us/download/details.aspx?id=46078)/[x64](https://www.microsoft.com/en-us/download/details.aspx?id=46148), or better, update the whole system using Windows Update.

**Comment by Kubrix** [comment]
Не решено KB3033929 уже стоит 
![image](https://github.com/user-attachments/assets/5bc754d5-5a4e-41f6-9f7d-8ae35c06726b)
