### ISSUE TITLE
Добрый день, есть вопрос

### ISSUE THREAD

**Issue by OihhoMoiss** [Flowseal/zapret-discord-youtube#811]
Добрый день, я хотел бы знать является ли эта программа ВПН-ом? 
Я играю в игры где за использования Впн могут и забанить, так что я хочу понимать есть ли риски в использовании "Запрета"

**Comment by thevoiddev** [comment]
Ну запусти запрет и зайди на [2ip](https://2ip.ru)
Изменился ли твой ип? Нет? Ну, значит, что не впн

**Comment by serpen7** [comment]
Это не ВПН. Как и гудбайдпи. Это утилиты дурения DPI.
