### ISSUE TITLE
Ошибка sygwin1.dll

### ISSUE THREAD

**Issue by Liber142** [Flowseal/zapret-discord-youtube#813]
Ошибка: Запуск программы невозможен, так как на компьютере отсутсвует sygwin1/dll
Помогите решить. Вроде установил этот файл и куда пихать его непонимаю

**Comment by serpen7** [comment]
Куда установили и зачем если это содержимое папки bin программы? Устанавливать его никуда не нужно.

**Comment by Eptiy** [comment]
Если он отсутствовал, значит его что-то снесло, скорее всего - антивирус. Создай новую папку для запрета, добавь её в исключения, туда помести архив и распакуй. Старые файлы запрета удали.
