### ISSUE TITLE
"Нет подключения к интернету" в YouTube при использовании service_goodbye_discord

### ISSUE THREAD

**Issue by lockgat** [Flowseal/zapret-discord-youtube#82]
При перезагрузке ПК, оба сервиса GoodbyeDPI и Zapret выполняются, однако YouTube пишет "Нет подключения к интернету", но если перезапустить сервис Zapret, то всё начинает работать исправно. Не особо хочется при каждом запуске ПК лезть в сервисы и перезапускать Zapret, есть ли какой-то способ это исправить?

**Comment by Flowseal** [comment]
Странное поведение, так как zapret не может запуститься раньше goodbyedpi, просто потому что зависим от него. Точно запускали через service_goodbye_discord? Попробуйте удалить и заного через этот батник.

**Comment by ApokGG** [comment]
юзал GDPI пока дискорд не обрубили, щас попробовал запретдпи, смысла держать обе проги открытыми не вижу, запрет справляется полностью. Советую отказаться от GDPI и пользоваться только запретом. Так же, рекомендую не лезть в сервисы вообще, а запускать батник с консолью и держать окно открытым, если глаза мазолит то делай как я, создай новый рабочий стол и закинь туда окно

**Comment by lockgat** [comment]
> Странное поведение, так как zapret не может запуститься раньше goodbyedpi, просто потому что зависим от него. Точно запускали через service_goodbye_discord? Попробуйте удалить и заного через этот батник.

Попробовал с нуля два раза установить сервис, чтобы понять принцип воспроизведения ошибки. 
Изначально, при запуске service_goodbye_discord выдаёт следующее, не уверен важно это или нет:
![image](https://github.com/user-attachments/assets/a10d9cde-93c7-4170-9336-8dbf93d13fb4)

При продолжении сервис удачно ставится и сразу начинает работать, параллельно с GoodbyeDPI.

При первом перезапуске ПК результат был разный: В первом случае GoodbyeDPI не выполнялся автоматически, я вручную его запустил и всё работало. Во втором случае, всё сразу работало.

В обоих случаях, при всех последующих перезапусках ПК появлялась проблема, описанная в начале ("Нет подключения 
к интернету"). В зависимостях у Zapret GoodbyeDPI стоит (и называется именно GoodbyeDPI)
![image](https://github.com/user-attachments/assets/43935da6-79c1-461e-8b51-01c8952f89f0)

**Comment by lockgat** [comment]
> Так же, рекомендую не лезть в сервисы вообще, а запускать батник с консолью и держать окно открытым, если глаза мазолит то делай как я, создай новый рабочий стол и закинь туда окно

Почему не стоит лезть в сервисы? Разве не удобнее когда всё работает сразу при запуске системы?

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90
