### ISSUE TITLE
Не работает   обход дискорда 

### ISSUE THREAD

**Issue by Goodkill9715** [Flowseal/zapret-discord-youtube#834]
Вот что выдаёт  при запуске  файла для обхода ди
![IMG_20241128_164449_959](https://github.com/user-attachments/assets/f6a4ec73-355c-474f-bbe4-cd629989b833)
скорда.

**Comment by serpen7** [comment]
ты пытаешься запустить его из архива =\
Разархивируй программу в папку нормально, все файлы чтобы были в ней и потом пробуй уже батники.

**Comment by Goodkill9715** [comment]
> ты пытаешься запустить его из архива = Разархивируй программу в папку нормально, все файлы чтобы были в ней и потом пробуй уже батники.
 
 Я все сделал,  но батник просто запускает Cmd и она быстро исчезает. Дс не работает

**Comment by serpen7** [comment]
> > ты пытаешься запустить его из архива = Разархивируй программу в папку нормально, все файлы чтобы были в ней и потом пробуй уже батники.
> 
> Я все сделал, но батник просто запускает Cmd и она быстро исчезает. Дс не работает

вместо смд должно появлятся окошко программы winws в минимизированном виде на панельке задач

**Comment by Goodkill9715** [comment]
> > > ты пытаешься запустить его из архива = Разархивируй программу в папку нормально, все файлы чтобы были в ней и потом пробуй уже батники.
> > 
> > 
> > Я все сделал, но батник просто запускает Cmd и она быстро исчезает. Дс не работает
> 
> вместо смд должно появлятся окошко программы winws в минимизированном виде на панельке задач

Есть ещё один  обход, я запускаю и там пишет  файл winws1.exe не найден

**Comment by serpen7** [comment]
> Есть ещё один обход, я запускаю и там пишет файл winws1.exe не найден

ты скачивал вирусную сборку которую распространяют ща по интернету с модифицированным файлом и вирусом, называемым winws1.exe. Это уже известная приблуда.
Такого файла ни в этом, ни в оригиналньном репозитории нет. Молись чтобы по нему отработал антивирус и оно не заразило твою машину.

![image](https://github.com/user-attachments/assets/52aad7bc-0e02-4d44-bcfb-42fd9f884f16)
![image](https://github.com/user-attachments/assets/cf327e0b-aeb5-46c9-ac56-30e771daca77)
