### ISSUE TITLE
discord.bat не работает 

### ISSUE THREAD

**Issue by Goodkill9715** [Flowseal/zapret-discord-youtube#836]
запускаю discord.bat от имени админа, cmd просто быстро исчезает, а дс не работат

**Comment by serpen7** [comment]
делай service remove bat от имени администратора, если будет окно с выводом желательно бы скриншотик окна.

**Comment by Goodkill9715** [comment]
> запускаю discord.bat от имени админа, cmd просто быстро исчезает, а дс не работат

Вот скриншот
![Uploading 20241128_175941.jpg…]()

**Comment by serpen7** [comment]
он не загрузился, вставляя скриншот дождись его загрузки в поле.

**Comment by Goodkill9715** [comment]
> делай service remove bat от имени администратора, если будет окно с выводом желательно бы скриншотик окна.

![Uploading 20241128_175941.jpg…]()

**Comment by Goodkill9715** [comment]
> он не загрузился, вставляя скриншот дождись его загрузки в поле.

![20241128_175941](https://github.com/user-attachments/assets/817c32e6-a02f-4528-95c7-e3a04fde274c)

**Comment by serpen7** [comment]
все, сервиса и драйвера виндайверта нет. запуская батники у тебя после его запуска он и должен закрываться и должно открываться приложение winws.exe под названием окна zapret вместо него на панельке задач внизу.
Такое вот 
![image](https://github.com/user-attachments/assets/7c2c309a-8c56-47be-a6ce-9fc570480146)

**Comment by Goodkill9715** [comment]
> все, сервиса и драйвера виндайверта нет. запуская батники у тебя после его запуска он и должен закрываться и должно открываться приложение winws.exe под названием окна zapret вместо него на панельке задач внизу. Такое вот ![image](https://private-user-images.githubusercontent.com/134365619/390774211-7c2c309a-8c56-47be-a6ce-9fc570480146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTU3NjAsIm5iZiI6MTczMjc5NTQ2MCwicGF0aCI6Ii8xMzQzNjU2MTkvMzkwNzc0MjExLTdjMmMzMDlhLThjNTYtNDdiZS1hNmNlLTlmYzU3MDQ4MDE0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxMjA0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWVlNjQwZGIzOTc2OTRkNzZlYjJmOGZjMTcxZjQ0MWVjYzU2YTBkOTFmZDE5Y2QyOWMyN2JiOWMxYzc4ZTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.92_zMgn_drNMEm4mshHI8XkcUuqHuduuAiklV21Hp_I)

У меня нету  Winws.exe
![20241128_180556](https://github.com/user-attachments/assets/1305d59f-015d-4cf4-bb03-65b1cdfbdaea)

**Comment by serpen7** [comment]
> > все, сервиса и драйвера виндайверта нет. запуская батники у тебя после его запуска он и должен закрываться и должно открываться приложение winws.exe под названием окна zapret вместо него на панельке задач внизу. Такое вот ![image](https://private-user-images.githubusercontent.com/134365619/390774211-7c2c309a-8c56-47be-a6ce-9fc570480146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTU3NjAsIm5iZiI6MTczMjc5NTQ2MCwicGF0aCI6Ii8xMzQzNjU2MTkvMzkwNzc0MjExLTdjMmMzMDlhLThjNTYtNDdiZS1hNmNlLTlmYzU3MDQ4MDE0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxMjA0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWVlNjQwZGIzOTc2OTRkNzZlYjJmOGZjMTcxZjQ0MWVjYzU2YTBkOTFmZDE5Y2QyOWMyN2JiOWMxYzc4ZTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.92_zMgn_drNMEm4mshHI8XkcUuqHuduuAiklV21Hp_I)
> 
> У меня нету Winws.exe ![20241128_180556](https://private-user-images.githubusercontent.com/189977222/390774739-1305d59f-015d-4cf4-bb03-65b1cdfbdaea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTYzMTMsIm5iZiI6MTczMjc5NjAxMywicGF0aCI6Ii8xODk5NzcyMjIvMzkwNzc0NzM5LTEzMDVkNTlmLTAxNWQtNGNmNC1iYjAzLTY1YjFjZGZiZGFlYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxMjEzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDNiNjI2ZDc5NDQ1MzNhMDE2NzQ0OTYzNmViZTQzMTA1ZTU0NjNhYThhYTE2ZTI0NDlmZDVhOGRhODIzMzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1pzOUU_D0XAOi1RIstXY-oN1vALvpi8w1MivmOQimcM)

ты опять запускаешь вирусную сборку с файлом winws1. Ты качал её не с этого репозитория а откуда то из интернета. Ты хочешь заразить себе ПК вирусней?

**Comment by Goodkill9715** [comment]
> > > все, сервиса и драйвера виндайверта нет. запуская батники у тебя после его запуска он и должен закрываться и должно открываться приложение winws.exe под названием окна zapret вместо него на панельке задач внизу. Такое вот ![image](https://private-user-images.githubusercontent.com/134365619/390774211-7c2c309a-8c56-47be-a6ce-9fc570480146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTU3NjAsIm5iZiI6MTczMjc5NTQ2MCwicGF0aCI6Ii8xMzQzNjU2MTkvMzkwNzc0MjExLTdjMmMzMDlhLThjNTYtNDdiZS1hNmNlLTlmYzU3MDQ4MDE0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxMjA0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWVlNjQwZGIzOTc2OTRkNzZlYjJmOGZjMTcxZjQ0MWVjYzU2YTBkOTFmZDE5Y2QyOWMyN2JiOWMxYzc4ZTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.92_zMgn_drNMEm4mshHI8XkcUuqHuduuAiklV21Hp_I)
> > 
> > 
> > У меня нету Winws.exe ![20241128_180556](https://private-user-images.githubusercontent.com/189977222/390774739-1305d59f-015d-4cf4-bb03-65b1cdfbdaea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTYzMTMsIm5iZiI6MTczMjc5NjAxMywicGF0aCI6Ii8xODk5NzcyMjIvMzkwNzc0NzM5LTEzMDVkNTlmLTAxNWQtNGNmNC1iYjAzLTY1YjFjZGZiZGFlYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxMjEzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDNiNjI2ZDc5NDQ1MzNhMDE2NzQ0OTYzNmViZTQzMTA1ZTU0NjNhYThhYTE2ZTI0NDlmZDVhOGRhODIzMzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1pzOUU_D0XAOi1RIstXY-oN1vALvpi8w1MivmOQimcM)
> 
> ты опять запускаешь вирусную сборку с файлом winws1. Ты качал её не с этого репозитория а откуда то из интернета. Ты хочешь заразить себе ПК вирусней?

 Можешь оставить ссылку  на нормальную?

**Comment by serpen7** [comment]
> Можешь оставить ссылку на нормальную?

Так ты ж в репозитории пишешь где нормальная сборка в релизах лежит https://github.com/Flowseal/zapret-discord-youtube/releases
Качать надо [zapret-discord-youtube-1.6.1.rar](https://github.com/Flowseal/zapret-discord-youtube/releases/download/1.6.1/zapret-discord-youtube-1.6.1.rar)

**Comment by serpen7** [comment]
Это хорошо что у тебя еще антивирь врублен и он видимо и снес этот зараженник winws1.exe. Я ж писал в предыдущей теме тебе по этому поводу. Что это давно уже известные вирусные сборки, которые распространяют даже сейчас и в интернете и на ютубе особенно которому до жалоб на авторов распространяющих вирусы побоку.

**Comment by Goodkill9715** [comment]
> > Можешь оставить ссылку на нормальную?
> 
> Так ты ж в репозитории пишешь где нормальная сборка в релизах лежит https://github.com/Flowseal/zapret-discord-youtube/releases Качать надо [zapret-discord-youtube-1.6.1.rar](https://github.com/Flowseal/zapret-discord-youtube/releases/download/1.6.1/zapret-discord-youtube-1.6.1.rar)

![image](https://github.com/user-attachments/assets/78c4b699-b0e7-46e5-9efd-962291b33370)
она пустая

**Comment by Goodkill9715** [comment]
> Это хорошо что у тебя еще антивирь врублен и он видимо и снес этот зараженник winws1.exe. Я ж писал в предыдущей теме тебе по этому поводу. Что это давно уже известные вирусные сборки, которые распространяют даже сейчас и в интернете и на ютубе особенно которому до жалоб на авторов распространяющих вирусы побоку.

Заработал дс, но есть проблема

**Comment by Goodkill9715** [comment]
> Это хорошо что у тебя еще антивирь врублен и он видимо и снес этот зараженник winws1.exe. Я ж писал в предыдущей теме тебе по этому поводу. Что это давно уже известные вирусные сборки, которые распространяют даже сейчас и в интернете и на ютубе особенно которому до жалоб на авторов распространяющих вирусы побоку.

![20241128_182359](https://github.com/user-attachments/assets/26344575-2ddd-45a5-b797-9afb40d82dc2)
 Оно как раньше  теперь  всегда будет вылетать, опыт был

**Comment by serpen7** [comment]
> > Это хорошо что у тебя еще антивирь врублен и он видимо и снес этот зараженник winws1.exe. Я ж писал в предыдущей теме тебе по этому поводу. Что это давно уже известные вирусные сборки, которые распространяют даже сейчас и в интернете и на ютубе особенно которому до жалоб на авторов распространяющих вирусы побоку.
> 
> ![20241128_182359](https://private-user-images.githubusercontent.com/189977222/390781217-26344575-2ddd-45a5-b797-9afb40d82dc2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTczMDMsIm5iZiI6MTczMjc5NzAwMywicGF0aCI6Ii8xODk5NzcyMjIvMzkwNzgxMjE3LTI2MzQ0NTc1LTJkZGQtNDVhNS1iNzk3LTlhZmI0MGQ4MmRjMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxMjMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDE4ZDk3MmNlN2ExMjhhNTdlNjM1ZTk5MDE4NjlkMWFhYTk0ODY0NDUwZTA5ZTZjODM4YWE5MTRlMTBjNjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-hZk2lm6WArqtf30e6myI6kscB2AZagaFxGcRdXXCV4) Оно как раньше теперь всегда будет вылетать, опыт был

а этот бсод знаю, у знакомого была проблема с дровами видяхи которые вызывали его  при включенном аппаратном ускорении в дискорде или в браузере. Хотя это могут быть и так же проблемы с памятью или чем то еще не особо понятным.
