### ISSUE TITLE
Не все сайты и приложения работают.

### ISSUE THREAD

**Issue by TON618OFF** [Flowseal/zapret-discord-youtube#84]
## Пояснение.
Скопировал всё содержание файла russia-blacklist.txt из goodbyedpi, чтобы вставить в list-general.txt, стали загружать больше сайтов. Но со стимов проблемы. Я запускаю zapret-discord, но у меня магазин стима не прогружает стили страницы.

## Вопрос:
Как получить доступ к названию хоста, которое надо будет прописать в list-general.txt? Откуда его брать?

**Comment by Flowseal** [comment]
Если в названии бат файла нет youtube, то используется файл list-discord.txt, добавляйте туда.
Чтобы посмотреть хосты, которые использует стим, можете воспользоваться панелью разработчиков в браузере, вкладка Network. Думаю, дальше нагуглите
