### ISSUE TITLE
Проблема с загрузкой аватарок в играх Steam

### ISSUE THREAD

**Issue by ranpo300** [Flowseal/zapret-discord-youtube#841]
Что в CS, что в Dota 2, никогда не загружаются аватарки, моя так же не грузится, есть ли решение этой проблемы?
Если что попробовал все батники, результат не изменился

**Comment by EgorWeders** [comment]
1. При работе онлайн игр (особенно с античитами) лучше отключать любые обходы, так как вас могут забанить.
2. Вероятно вам нужно определить домен с которых берутся аватарки и добавить его в список для обхода.

**Comment by serpen7** [comment]
можете попробовать добавить steamcommunity.com и steamstatic.com в листы но это вряд ли поможет потому что РКН не воздействует на стим, а значит проблема непрогрузки аватарок может быть сторонняя.

**Comment by Flowseal** [comment]
РКН не блокирует Steam. Проблема не с этой стороны
