### ISSUE TITLE
Если у кого-то не запускается service-install.bat(может быть поможет) 

### ISSUE THREAD

**Issue by IamProgramm** [Flowseal/zapret-discord-youtube#843]
И так, для начала надо 
1) чтобы в конечной директории(пути к файлу) не было кириллицы(правильно C:/Users/1/Desktop/zapret... . Неправильно: С:/Users/1/Папка/zapret). 
2) Далее надо поменять кодировку самого файла service-install.bat. Если у вас как и у меня стоял UTF-8, надо поставить ANSI(вместо стандартного сообщения будут символы, не пугаемся, это из-за кодировки, на работу не повлияет)
3) Запускаем service-install.bat ОТ ИМЕНИ АДМИНИСТРАТОРА !! 
4) Нажимаем Enter, далее нажимаем 9 и Enter.
PROFIT

**Comment by IamProgramm** [comment]
UDP: чтобы поменять кодировку нужно: открыть service-install.bat через блокнот, далее Файл - Сохранить как. Внизу будет установленная кодировка, меняем её на ANSI

**Comment by serpen7** [comment]
там просто приколюха что путь должен так же не содержать спецсимволов типа ZapretDiscord&Youtube.
А так же должен качатся рар архив с релизов, а не соурс или с мейн репозитория в zip т.к. там файлы сделаны батников в LF же кодикорвке насколько в понимаю. Рар а они вот для в винды собираются в CR LF.

![image](https://github.com/user-attachments/assets/6a205258-ea3e-4b7b-9960-5f8d8e7de04d)
