### ISSUE TITLE
Почему не работает?

### ISSUE THREAD

**Issue by Dixeone** [Flowseal/zapret-discord-youtube#85]
Нажмите любую клавишу, чтобы продолжить создание сервиса.
Press any key to continue . . .
The zapret DPI bypass : winws1 service is not started.

More help is available by typing NET HELPMSG 3521.

[SC] DeleteService SUCCESS
[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: zapret
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 12184
        FLAGS              :
Press any key to continue . . .
![image](https://github.com/user-attachments/assets/12c2f8c9-966d-4a67-8118-e9bba1a63173)

**Comment by Flowseal** [comment]
Возможно, из-за провайдера. Эксперементируйте с параметром аргумента `--dpi-desync`
Документация: https://github.com/bol-van/zapret

**Comment by Dixeone** [comment]
> Возможно, из-за провайдера. Эксперементируйте с параметром аргумента `--dpi-desync` Документация: https://github.com/bol-van/zapret

Мне же это читать весь день, где менять параметр аргумента?

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92
