### ISSUE TITLE
Это что - майнер?

### ISSUE THREAD

**Issue by MrDrakuls** [Flowseal/zapret-discord-youtube#850]
При удалении выдаёт такую ошибку. Это что такое??? Криптокошелёк биткоина??? Помогите у меня паника!

См. описание файла: 

![image](https://github.com/user-attachments/assets/11d4ebe8-d7d3-4c9f-8b72-b5d0008c586a)

**Comment by serpen7** [comment]
Ты когда нибудь встречал вирусы майнеры которые пишут в описании файла майнера сайт создателя драйвера и колешек биткоинов для поддержки?

**Comment by serpen7** [comment]
Ты когда нибудь встречал вирусы майнеры которые пишут в описании файла майнера сайт создателя драйвера и кошелек биткоинов для поддержки создания драйвера?

https://reqrypt.org/windivert.html
https://github.com/basil00/WinDivert

**Comment by MrDrakuls** [comment]
> Ты когда нибудь встречал вирусы майнеры которые пишут в описании файла майнера сайт создателя драйвера и колешек биткоинов для поддержки?

Он просто не удаляется, не могу поставить новую версию. Я поэтому и подозревал вирус

**Comment by serpen7** [comment]
> > Ты когда нибудь встречал вирусы майнеры которые пишут в описании файла майнера сайт создателя драйвера и колешек биткоинов для поддержки?
> 
> Он просто не удаляется, не могу поставить новую версию. Я поэтому и подозревал вирус

Он и не удалится если работает, как и все любое другое на ОС.

**Comment by serpen7** [comment]
Для этого и есть сервис ремув батник чтобы остановить это все и выдрать с памяти чтобы оно могло свободно удалится если надо. Сервис ремув нужно запускать от имени администратора иначе нет разрешений на удаление службы и сервисов.

**Comment by MrDrakuls** [comment]
> [serpen7](/serpen7)

Спасибо большое! Я думал уже всё, без компьютера останусь :С
Спасибо ❤

**Comment by MrDrakuls** [comment]
Закрываю!
