### ISSUE TITLE
sirex

### ISSUE THREAD

**Issue by Sirex11** [Flowseal/zapret-discord-youtube#852]
![2024-11-30_17-59-17](https://github.com/user-attachments/assets/39d66ba4-9369-4882-a5cd-acd5c75a35d9)
скачал файл ,в свойствах разблокировал и сделал администратором ,открывая нужные файлы вылезает такая ошибка что делать?
Заходил в service remove выдает Restarted with admin rights
The service name is invalid
More help is available by typing NET HELPMSG 2185.
[SC] OpenService FAILED 1060
[SC] OpenService FAILED 1060:
More help is available by typing NET HELPMSG 2185.
[SC] OpenService FAILED 1060:
The specified service does not exist as an installed service.
и многое другое ,подскажжите как быть?

**Comment by serpen7** [comment]
ты файл с архива пытаешься открывать. Нужно распаковать файлы программы все в отдельную папку с названием на английском языке. Один файл сам по себе и не работает из целой программы.
