### ISSUE TITLE
Не работает Discord

### ISSUE THREAD

**Issue by Egoiste1303** [Flowseal/zapret-discord-youtube#854]
Доброго времени суток, давно пользуюсь обходкой Zapret всё работало, 3 дня назад переустановил винду, и 3 дня не пользовался дискордом, сегодня появилась необходимость, начал всё ставить и не получается настроить обход, пробовал старую версию 1.3.0 которая стояла у меня ранее, пробовал 1.6.1 последнюю все Альты, перезагружал удалял ставил.. решил написать пост, удалил обход, перегрузил ноут, и заново начал ставить всё обратил внимание что выдает ошибку при запуске батника OpenService! на ноуте нету антивирусов, брандмауер виндовс пробовал отключать польностью но тоже самое... на скринах ошибка при запуске батника, если включаю VPN то дискорд работает, за ютуб не знаю так как он на моём провайдере работает и без обходов.
![discord](https://github.com/user-attachments/assets/57c26903-3286-48b9-8cb8-e721c3d9795c)
![службы](https://github.com/user-attachments/assets/c57622b1-a795-4981-abaf-157e1887127c)
![обход](https://github.com/user-attachments/assets/5de86b47-58d7-4d72-a053-cf8983b96c63)

**Comment by Egoiste1303** [comment]
![1 6 1 ошибка 1060](https://github.com/user-attachments/assets/f57a68ce-2a33-456d-bb48-a338b2b44976)
 тоже самое ошибка 1060 при запуске 1.6.1 версии

**Comment by serpen7** [comment]
это не ошибка это уведомление о том что служба не существует т.к. в ее создатель встроенна так же очистка службы перед её созданием. 
![image](https://github.com/user-attachments/assets/c61810fe-e483-44c8-9117-05c928c583e7)

В отличии от remove батника оно просто пытается убить службу если она установлена, чтобы её переустановить. Но не настроено на то чтобы пытаться "убить" виндайверт который используется прогой и службой и который винда может заблочить иногда непонятно почему по правам доступа. Поэтому лучше перед созданием службы запускать сервис ремув каждый раз от администратора, чтобы удостоверится что не работает драйвер виндайверта и служба будет удалена так же, а так же увидеть возможные проблемы блокировки от винды по доступу к виндайверту.

**Comment by serpen7** [comment]
Итого дапустите service remove bat от имени администратора и посмотрите что выведет.

**Comment by Egoiste1303** [comment]
Запустил service remove bat от имени администратора
![remove от ИА](https://github.com/user-attachments/assets/b05df6ef-b5d3-4cb7-8666-57928cec89cb)
просто уже много раз удалил устанавливал удалял устанавливал, причину по каторой не работает так и не пойму

**Comment by serpen7** [comment]
> Запустил service remove bat от имени администратора ![remove от ИА](https://private-user-images.githubusercontent.com/190188714/391303909-b05df6ef-b5d3-4cb7-8666-57928cec89cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMzk4NDIsIm5iZiI6MTczMzAzOTU0MiwicGF0aCI6Ii8xOTAxODg3MTQvMzkxMzAzOTA5LWIwNWRmNmVmLWI1ZDMtNGNiNy04NjY2LTU3OTI4Y2VjODljYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQwNzUyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTdkNDI0MDVhYWEzN2YxZmI1NmY1MThkNDg5NzNkOGQ2ZGIzZDI5NGE3ODk2ZGE4ODlmYTZmOGYyNTk0ODUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cUufxZTwO9HaBcCKabzyPCGa6F_OPRELGVk5OLsEA8c) просто уже много раз удалил устанавливал удалял устанавливал, причину по каторой не работает так и не пойму

Виндайверт работал и по его выводу он остановился теперь и вычищен. Ты случаем раньше не пользовался гудбайдпи с его сервисом? Если да, то скачивай последний релиз гудбайдпи [goodbyedpi-0.2.3rc3-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc3/goodbyedpi-0.2.3rc3-2.zip) и запускай оттуда от администратора батник сервис ремув тоже. Даже если точно не помнишь. Множественные фильтры конфликтуют между собой порой, особенно из за разных стратегий могут создавать горы флуда в трафике.

Сервисы не нужно сразу ставить, нужно пробовать батники и найти тот который работает. А уже потом ставить его как сервис если захочешь.

**Comment by subaridji** [comment]
Аналогичные симптомы. После вычистки goodbyedpi и запуска discord.bat удается открыть только чат в web-версии, при этом попытки подключения в голосовой канал, отправки изображения в чат или запуска приложения (апдейт при запуске) успехом не завершаются.

**Comment by serpen7** [comment]
> Аналогичные симптомы. После вычистки goodbyedpi и запуска discord.bat удается открыть только чат в web-версии, при этом попытки подключения в голосовой канал, отправки изображения в чат или запуска приложения (апдейт при запуске) успехом не завершаются.

так пробуйте другие батники, на одном дженерале и дискорд батах стратегии не замкнулись.

**Comment by Flowseal** [comment]
Win+R -> services.msc -> найдите сервисы с названием VPN, Killer, Check Point, SmartByte и удалите (либо, более безопасный вариант, зайти в их свойства, тип запуска поставить "Отключена" и остановить)
