### ISSUE TITLE
winws.exe не найден ?

### ISSUE THREAD

**Issue by TheCrazy02** [Flowseal/zapret-discord-youtube#855]
![image](https://github.com/user-attachments/assets/09e8af01-af7f-40f0-a712-d9b315cde4cf)

Заранее, антивирус выключен, обходов других нету.

```
команды в cmd 
sc delete windivert
sc stop windivert

```

Не помогли.

**Comment by serpen7** [comment]
у вас файл winws.exe из папки bin снесло антивирем походу.
