### ISSUE TITLE
WinDivert64.sys - майнер.

### ISSUE THREAD

**Issue by Tarxyn** [Flowseal/zapret-discord-youtube#859]
Если открыть свойства файла WinDivert64.sys по пути (путь к вашей директории файлов обхода/bin/WinDivert64.sys), можно увидеть ссылку на криптокошелек. Описание файла на VirusTotal прилагаю: https://www.virustotal.com/gui/file/8da085332782708d8767bcace5327a6ec7283c17cfb85e40b03cd2323a90ddc2/detection

Кроме того, если не запускать BAT-файлы, можно безопасно удалить эту директорию с вашего персонального компьютера. Однако, если попытаться удалить или переместить файлы после выполнения BAT-скрипта, можно заметить, что данный файл нельзя переместить или удалить, так как он используется другой программой.

Я не обвиняю автора идеи и создателя данного репозитория. Просто прошу посмотреть на безопасность этого проекта со стороны и попросить пользователей быть более бдительными и внимательными при скачивании файлов из репозиториев.

Попрошу быть аккуратным и внимательным при установке файлов и, пожалуйста, исправьте этот недостаток в будущих версиях данного программного обеспечения.

**Comment by serpen7** [comment]
да сколько ж вас ппц то таких интересных которые майнер определяют по описанияю в свойстве файла.

> Вы когда нибудь встречали вирусы майнеры которые пишут в описании файла майнера сайт создателя драйвера и кошелек биткоинов для поддержки создания драйвера?

И удивительно что вы даже не хотите хотя бы перейти на тот же сайт чтобы посмотреть кто создатель, что там есть кошельки для поддержки в биткоине. И так же то что это сетевой фильтр\модификатор пакетов для оболочки ОС на пользовательском уровне. 
![image](https://github.com/user-attachments/assets/32f1a448-e8f6-47bb-8b4a-95b870687aab)

Не спорю лишь о том что есть фейковые сборки гудбайдпи и запрета, которые распространяются по интернету незнамо от кого и откуда, особенно на ютубе. Которые используют виндайверт для дурения ТСПУ, которые содержат реальные вирусы. Но в оригинальных репозиториях и репозиториях которые делались с оригинального репозитория, нормальных - вирусов нет банально.

**Comment by serpen7** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/850
https://github.com/Flowseal/zapret-discord-youtube/issues/805
https://github.com/Flowseal/zapret-discord-youtube/issues/606
https://github.com/Flowseal/zapret-discord-youtube/issues/474
https://github.com/Flowseal/zapret-discord-youtube/issues/425
https://github.com/Flowseal/zapret-discord-youtube/issues/230
https://github.com/Flowseal/zapret-discord-youtube/issues/143

И господи вам даже на вирустотале пишет что это "уязвимый драйвер", "не вирус, виндайверт тулл"
![image](https://github.com/user-attachments/assets/d053418b-200f-4747-9c76-59d2c0288a12)

Но да если убедить себя что все майнер - то все будет майнером.
Вам самому не смешно?

**Comment by exzolink** [comment]
Да пора банить таких уже

**Comment by Gizmarian** [comment]
Ставим антивирус - и не запускаем всякое - рекламируемое зумера ))) у них от редбула мозги в трубочке  (youtub... "лопата" для зумеров, смеятся тут)
