### ISSUE TITLE
YouTube не догружает видео

### ISSUE THREAD

**Issue by Spiderr961** [Flowseal/zapret-discord-youtube#86]
дискорд работает прекрасно, но что до ютуба.... тут все похуже.  Сайт прекрасно прогружается но видео не могут запустится. Пробовал запускать вместе с гудбаем - тоже не помогло. Возможно проблема с моим провайдером? просто я уже не знаю что думать

**Comment by Flowseal** [comment]
Возможно, из-за провайдера. Эксперементируйте с параметром аргумента --dpi-desync
Документация: https://github.com/bol-van/zapret

**Comment by Spiderr961** [comment]
![Uploading Снимок экрана 2024-10-09 235431.png…]()

это?

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90
