### ISSUE TITLE
Дискорд работает а ютуб нет

### ISSUE THREAD

**Issue by MaksimBebra** [Flowseal/zapret-discord-youtube#860]
У меня стоит последний релиз 1.6.1, пользовался general.bat, несколько минут назад ютуб перестал работать (бесконечная загрузка) батники ALT не помогают

**Comment by Flowseal** [comment]
Попробуйте переустановить:
- запустите service_remove.bat
- удалите папку с программой
- скачайте .rar архив с последнего релиза
- распакуйте в папку
- тестируйте батники

**Comment by Flowseal** [comment]
Также читайте README + https://github.com/Flowseal/zapret-discord-youtube/discussions/251
