### ISSUE TITLE
проверка 

### ISSUE THREAD

**Issue by davchiik** [Flowseal/zapret-discord-youtube#862]
Помогите пожалуйста, я вроде все делаю правильно, но когда пытаюсь присоединиться к звонку у меня идет постоянное подключение которое не заканчивается 
![{C6224C03-81A8-41B0-B70B-2E2C2812FE6E}](https://github.com/user-attachments/assets/80792572-7595-4723-b529-2f51d58d34c3)
что с этим можно сделать? как исправить?

**Comment by serpen7** [comment]
Использовать другие батники?

**Comment by davchiik** [comment]
вопросов больше нет извините за дурацкий вопрос
