### ISSUE TITLE
Нашел способ для себя чтобы войс чат в дс заработал

### ISSUE THREAD

**Issue by HodovVladislav** [Flowseal/zapret-discord-youtube#865]
Проблема:
Работало все кроме войс чата в дисе. Перепробовал кучу способов, но ни один не помог.

Решение:
Проблема была в службе SmartByte Network Service. Остановил ее, и войс чат заработал

**Comment by Flowseal** [comment]
![image](https://github.com/user-attachments/assets/b7cf06ff-8757-47fb-8f8e-0780ee471380)
