### ISSUE TITLE
Не работает дискорд

### ISSUE THREAD

**Issue by kiriru13** [Flowseal/zapret-discord-youtube#866]
![Снимок экрана 2024-12-03 010513](https://github.com/user-attachments/assets/e0a48afb-e61c-4f22-bc5a-fb707a962f11)
Выдаёт вот такое вечное подключение, помогите

**Comment by Relstren** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/865 Если работает все кроме войс чата, то чекни этот пост

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
