### ISSUE TITLE
Не работает обход дискорда.

### ISSUE THREAD

**Issue by Cups1ze** [Flowseal/zapret-discord-youtube#869]
Мой друг столкнулся с проблемой полной неработоспособности ВСЕХ .bat файлов. Переустанавливали по несколько раз, отключали антивирус, перезагружали ПК (запуск файлов был с помощью администратора). При запуске батника открывается консоль в которой пишет, что как бы все окей, но при запуске дискорда происходит бесконечная загрузка (Update checking или failked)

**Comment by serpen7** [comment]
тогда вашему другу следует искать другие стратегии, либо писать\переписывать их на свой лад и пробовать.

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
