### ISSUE TITLE
Не работает для видосов ютуба

### ISSUE THREAD

**Issue by Lozaruss** [Flowseal/zapret-discord-youtube#87]
Запускаю discord_youtube, сайт ютуба грузит, но сами видосы на сайте нет

**Comment by NuclearBeggar** [comment]
Он сейчас даже у гудбая лежит дохлый... Только ждать

**Comment by PunisherT1000** [comment]
тоже самое

**Comment by 0k0r0k** [comment]
Час назад у меня GoodbyeDPI перестал грузить видосы, перешел на запрет и всё стало грузиться

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/90
