### ISSUE TITLE
Можно ли раздать по локальной сети трафик?

### ISSUE THREAD

**Issue by Thegreq** [Flowseal/zapret-discord-youtube#871]
Имеется телевизор samsung с tizen os и компьютер с двумя сетевыми картами. Можно ли как то раздать трафик с пк на телевизор, через zapret?

**Comment by serpen7** [comment]
По идее можно если создать из ПК точку доступа и у него есть вайфай модуль на материнке и вайфай работает. Поэтому ПК будет раздавать иннет уже с модом трафика на ваш ТВ т.к. запрет действует на трафик всей системы в целом.

Но это не точно и в теории в целом...

**Comment by Thegreq** [comment]
> По идее можно если создать с ПК точку доступа и у него есть модуль вайфай на материнке и вайфай работает. Поэтому ПК будет раздавать инет уже с модом трафика на вашем ТВ т.к. Запрет действует на всей системе трафика в целом.
> 
> Но это не точно и в теории в целом...

Пробовал так, не получилось. Ютуб так же не работает на телевизоре

**Comment by Flowseal** [comment]
Принцип такой же, как и в раздаче интернета под впном. Прокси.
