### ISSUE TITLE
Как удалить WinDivert64 из папки bin?

### ISSUE THREAD

**Issue by DeniZleet** [Flowseal/zapret-discord-youtube#872]
Процесса и службы такой нет, через Unlocker почему то тоже не удаляется. Как быть?
![image](https://github.com/user-attachments/assets/54aa2cdd-cbad-4048-9af2-6084ba5cbd7a)
Есть вариант удалить через Unlocker при следующем запуске системы. Добавлю сюда коммент в зависимости от результата.
![image](https://github.com/user-attachments/assets/967c4533-c060-4c3a-9128-518052c9d21f)

**Comment by serpen7** [comment]
не нужно ничего удалять через анлокер и нарушать права доступа к файлам, делаете сервис ремув бат от имени адинистратора, перезагружаете пк и делаете его снова от имени администратора. Если вдруг не работает значит вы ставили до этого гудбайдпи службу скорее всего. качаете это [goodbyedpi-0.2.3rc3-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc3/goodbyedpi-0.2.3rc3-2.zip) и запускаете так же оттуда сервис ремув от имени администратора. 
Все, все службы виндайверта, гудбайдпи, запрета полностью удалены из системы, можно спокойно удалять папку.

**Comment by DeniZleet** [comment]
> не нужно ничего удалять через анлокер и нарушать права доступа к файлам, делаете сервис ремув бат от имени адинистратора, перезагружаете пк и делаете его снова от имени администратора. Если вдруг не работает значит вы ставили до этого гудбайдпи службу скорее всего. качаете это [goodbyedpi-0.2.3rc3-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc3/goodbyedpi-0.2.3rc3-2.zip) и запускаете так же оттуда сервис ремув от имени администратора. Все, все службы виндайверта, гудбайдпи, запрета полностью удалены из системы, можно спокойно удалять папку.

Каким образом Unlocker может нарушать права доступа к файлам?
Мне нужно удалить именно этот файл для удаления папки, service_remove удаляет сервис через CMD, но сам сервис WinDivert64 мне нужен, мне лишь нужно удалить конкретно этот файл.

**Comment by serpen7** [comment]
> > не нужно ничего удалять через анлокер и нарушать права доступа к файлам, делаете сервис ремув бат от имени адинистратора, перезагружаете пк и делаете его снова от имени администратора. Если вдруг не работает значит вы ставили до этого гудбайдпи службу скорее всего. качаете это [goodbyedpi-0.2.3rc3-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc3/goodbyedpi-0.2.3rc3-2.zip) и запускаете так же оттуда сервис ремув от имени администратора. Все, все службы виндайверта, гудбайдпи, запрета полностью удалены из системы, можно спокойно удалять папку.
> 
> Каким образом Unlocker может нарушать права доступа к файлам? Мне нужно удалить именно этот файл для удаления папки, service_remove удаляет сервис через CMD, но сам сервис WinDivert64 мне нужен, мне лишь нужно удалить конкретно этот файл.

Тем что он как раз таки и делает это чтобы получить права владения файлом и владельцем, чтобы снять ограничение системы?
Вам нужно удалить виндайверт но вы хотите использовать виндайверт и не удалять его? Это как?

**Comment by DeniZleet** [comment]
> > > не нужно ничего удалять через анлокер и нарушать права доступа к файлам, делаете сервис ремув бат от имени адинистратора, перезагружаете пк и делаете его снова от имени администратора. Если вдруг не работает значит вы ставили до этого гудбайдпи службу скорее всего. качаете это [goodbyedpi-0.2.3rc3-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc3/goodbyedpi-0.2.3rc3-2.zip) и запускаете так же оттуда сервис ремув от имени администратора. Все, все службы виндайверта, гудбайдпи, запрета полностью удалены из системы, можно спокойно удалять папку.
> > 
> > 
> > Каким образом Unlocker может нарушать права доступа к файлам? Мне нужно удалить именно этот файл для удаления папки, service_remove удаляет сервис через CMD, но сам сервис WinDivert64 мне нужен, мне лишь нужно удалить конкретно этот файл.
> 
> Тем что он как раз таки и делает это чтобы получить права владения файлом и владельцем, чтобы снять ограничение системы? Вам нужно удалить виндайверт но вы хотите использовать виндайверт и не удалять его? Это как?

Мне нужно удалить конкретно этот файл по этому расположению, у меня есть такой же в другой папке.
У системы и у моего юзера и так стоит полный доступ, никакие права владения Unlocker не меняет. Проблема в том, что файл/процесс запущен на компьютере, и из-за этого, через обычное удаление его не удалить. Если бы я знал название службы или процесса, я бы мануально его отключил и удалил файл, но я не знаю где его найти.
Зачем Вы пытаетесь разобратся в причинах моего действия, если я просто хотел узнать способы его осуществления?

**Comment by serpen7** [comment]
> Проблема в том, что файл/процесс запущен на компьютере, и из-за этого, через обычное удаление его не удалить. Если бы я знал название службы или процесса, я бы мануально его отключил и удалил файл, но я не знаю где его найти.
> Зачем Вы пытаетесь разобратся в причинах моего действия, если я просто хотел узнать способы его осуществления?

Потому что вы буквально не читаете что вам пишут и не хотите удалить эту службу\процесс\драйвер из системы нормально по тому что вам пишут. Виндайверт ключевой драйвер в работе утилиты. Удаляете его и утилита не работает. Удаляете папку установив сервис и утилита не работает. А иначе я не понимаю зачем вам виндайверт залоченный виндой и тем что вы не читаете как его удалить, чтобы использовать заново нормально. У вас в голове "я босс", я должен удалить это грубо ибо "я босс" чтобы показать ей, "кто тут хозяин". Вам самому не смешно? Притом что вы не понимаете что грубое удаление откуда либо тем же анлокером имеет последствия, если вы не понимаете то что делаете(да я вкурсе что вы напишите что вы понимаете то, что делаете. Но судя по вашей тут писанине вы КРАЙНЕ не понимаете, то, что делаете). Вместо того чтобы сделать все по уму. =\

"Эта штука используется, я хочу её удалить, но не удалить". Это вообще как так? =\

Анлокер буквально проделывает банальные скрипты системы по владению файлом и разрешения на файл, чтобы его удалить. Если вы не знали. Вы можете их проделать и сами если погуглите буквально пару минуток. Ничего из "магиии" в этом нет. Проблема в том что такие вещи могут сохранятся и нарушать целостность системы безопасности в системе. Поэтому и анлокер и рекомендуют использовать только как последнюю меру все кто знает как он работает. Потому что так проще из-за автоматизации скриптов владения\разрешений.

**Comment by DeniZleet** [comment]
> > Проблема в том, что файл/процесс запущен на компьютере, и из-за этого, через обычное удаление его не удалить. Если бы я знал название службы или процесса, я бы мануально его отключил и удалил файл, но я не знаю где его найти.
> > Зачем Вы пытаетесь разобратся в причинах моего действия, если я просто хотел узнать способы его осуществления?
> 
> Потому что вы буквально не читаете что вам пишут и не хотите удалить эту службу\процесс\драйвер из системы нормально по тому что вам пишут. Виндайверт ключевой драйвер в работе утилиты. Удаляете его и утилита не работает. Удаляете папку установив сервис и утилита не работает. А иначе я не понимаю зачем вам виндайверт залоченный виндой и тем что вы не читаете как его удалить, чтобы использовать заново нормально. У вас в голове "я босс", я должен удалить это грубо ибо "я босс" чтобы показать ей, "кто тут хозяин". Вам самому не смешно? Притом что вы не понимаете что грубое удаление откуда либо тем же анлокером имеет последствия, если вы не понимаете то что делаете(да я вкурсе что вы напишите что вы понимаете то, что делаете. Но судя по вашей тут писанине вы КРАЙНЕ не понимаете, то, что делаете). Вместо того чтобы сделать все по уму. =\

Literally попросил помочь удалить файл не удаляя сервис.

> Удаляете его и утилита не работает. Удаляете папку установив сервис и утилита не работает.
 - Буквально нужно было удалить файл не затрагивая работу сервиса.
 

> Анлокер буквально проделывает банальные скрипты системы по владению файлом и разрешения на файл, чтобы его удалить. Если вы не знали.
- [Unlocker Wiki](https://ru.wikipedia.org/wiki/Unlocker#:~:text=Unlocker%20%D1%81%D0%BF%D0%BE%D1%81%D0%BE%D0%B1%D0%BD%D0%B0%20%D1%80%D0%B0%D0%B7%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D0%BF%D0%BE%D1%87%D1%82%D0%B8%20%D0%BB%D1%8E%D0%B1%D0%BE%D0%B9,%D0%BA%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D0%BE%D0%BC%D1%83%20%D0%BD%D0%B5%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%20%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C%20%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF.) Как я и предполагал, как и написано в википедии и сторонних ресурсах: "... но и остановить эти процессы или освободить от них файл". В моем случае, я выбрал удаление файла после перезагрузки. Так как сервис не мог завершить процесс во время работы системы, ему потребовалось произвести удаление во время загрузки системы, перед запуском этой службы.

> Вы можете их проделать и сами если погуглите буквально пару минуток.
- Ни ссылок на источник, ни, как оказалось, подтверждающей Ваше заявление информации в интернете.

Все получилось, коммент будет ниже.

**Comment by DeniZleet** [comment]
После перезагрузки Unlocker, как и полагалось, безпрепятственно удалил файл WinDivert64.sys из папки, требуемой к удалению, до запуска самого процесса.
При этом сервис "zapret-discord-youtube" работает исправно, служба WinDivert64.sys функционирует исправно, как и полагалось.

**Comment by serpen7** [comment]
> Literally попросил помочь удалить файл не удаляя сервис.

Это как вы хотите не удалять сервис но удалить файлы которые он пользует?

**Comment by serpen7** [comment]
> После перезагрузки Unlocker, как и полагалось, безпрепятственно удалил файл WinDivert64.sys из папки, требуемой к удалению, до запуска самого процесса. При этом сервис "zapret-discord-youtube" работает исправно, служба WinDivert64.sys функционирует исправно, как и полагалось.

сервис просто создан и будет работать но без фильтра трафика виндайверт потому что вы его удалили. Путь к файлам сервиса прописан в самом сервисе. =/
По сути дела бесполезно.

**Comment by serpen7** [comment]
Т.е. по сути дела вы хотите чтобы программа работала в сервисах без файлов что она пользует? Это как? В какой вселенной вы ставите сервис какой либо, удаляете файлы, но при этом сервис программы продолжает корректно работать без файлов на которые опирается сервис? Вы говорите они у вас в другом расположении есть такие же? А сервис об этом знает? Или вы предполагаете что он "самосознанием" вычислит это?

Жду очередную тему почему у меня не работает сервис запрета.

**Comment by DeniZleet** [comment]
> > После перезагрузки Unlocker, как и полагалось, безпрепятственно удалил файл WinDivert64.sys из папки, требуемой к удалению, до запуска самого процесса. При этом сервис "zapret-discord-youtube" работает исправно, служба WinDivert64.sys функционирует исправно, как и полагалось.
> 
> сервис просто создан и будет работать но без фильтра трафика виндайверт потому что вы его удалили =\

WinDivert64.sys у меня остался, но в другой дериктории.
Прилагаю проверку статуса работы сервиса через CMD: 
![image](https://github.com/user-attachments/assets/b67a76bb-ce56-438f-b4cb-9ac72b32dd64)
Echo работы сервиса "zapret: discord":
![image](https://github.com/user-attachments/assets/b94de4d5-da22-4d51-a475-1a511dc869a8)

Дальнейшие комментарии от Вас не будут рассматриваться мной в силу вашей некомпетентности.

**Comment by serpen7** [comment]
> > > После перезагрузки Unlocker, как и полагалось, безпрепятственно удалил файл WinDivert64.sys из папки, требуемой к удалению, до запуска самого процесса. При этом сервис "zapret-discord-youtube" работает исправно, служба WinDivert64.sys функционирует исправно, как и полагалось.
> > 
> > 
> > сервис просто создан и будет работать но без фильтра трафика виндайверт потому что вы его удалили =\
> 
> WinDivert64.sys у меня остался, но в другой дериктории. Прилагаю проверку статуса работы сервиса через CMD: ![image](https://private-user-images.githubusercontent.com/184478450/392166515-b67a76bb-ce56-438f-b4cb-9ac72b32dd64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNjgyMjUsIm5iZiI6MTczMzI2NzkyNSwicGF0aCI6Ii8xODQ0Nzg0NTAvMzkyMTY2NTE1LWI2N2E3NmJiLWNlNTYtNDM4Zi1iNGNiLTlhYzcyYjMyZGQ2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QyMzE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjUxZDJiNTIyYTAyMmY1OGM5NTIyYjFkMjZjMzhiZTI1ZWFiMjY1MTM5ZTc0YTViZWExODU0NjVhNDQ0M2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TOkdlHJaFSruJXOqiqr8EmMHCsEg0HO2DmvC-dE0-qk) Echo работы сервиса "zapret: discord": ![image](https://private-user-images.githubusercontent.com/184478450/392167458-b94de4d5-da22-4d51-a475-1a511dc869a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNjgyMjUsIm5iZiI6MTczMzI2NzkyNSwicGF0aCI6Ii8xODQ0Nzg0NTAvMzkyMTY3NDU4LWI5NGRlNGQ1LWRhMjItNGQ1MS1hNDc1LTFhNTExZGM4NjlhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QyMzE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjBjMmNlN2E2ZDNmZTJjZDgzNzA2NmNmZjQwMzA0NjljMTRlODE0MWIxYWUxYzE3ZTNmZTgwNDgyMTM4Zjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T6OXsuiYdm6b19J5FIqX5SvU7HvdXQpzjBHUhUKaBfs)
> 
> Дальнейшие комментарии от Вас не будут рассматриваться мной в силу вашей некомпетентности.

я вас честно говоря не понял и не понимаю до сих пор что вы хотели т.к. писал как выгрузить драйвер и удалить сервис еще изначально, чтобы если надо его загрузить из другой дирректории без всяких анлокеров и проблем. Но да ладно. Хотите думайте что думаете. Это ваши проблемы и ваш ПК.
Ах да севрис запрета называется zapret, а не названием драйвера виндайверта который он использует. То что драйвер находится в системе не делает его используемым сервисом у которого прописан путь к своему драйверу в своей дирректории, который вы возможно таки удалили
![image](https://github.com/user-attachments/assets/54bad0d4-1dc4-4c7a-b99d-3df7bd165f83)

Все равно жду тему на предмет "не работает запрет, удалил его файлы, но они же были где-то еще, почему он не подхватил драйвер виндайверта который ему нужен из другой дирректории?".

Удачи.

**Comment by sk8rthug** [comment]
> Прилагаю проверку статуса работы сервиса через CMD:

А попробуйте вбить в командную строку
sc qc windivert
Интересно, что он покажет

**Comment by DeniZleet** [comment]
> > Прилагаю проверку статуса работы сервиса через CMD:
> 
> А попробуйте вбить в командную строку sc qc windivert Интересно, что он покажет

![image](https://github.com/user-attachments/assets/b00a5eac-3168-40a4-8b1a-d80a1ce7ac2d)

**Comment by sk8rthug** [comment]
Ну понятно. У вас есть папка Flawseal-zapret_1.5.1 и папка zapret-discord-youtube-1.5.1. Видимо служба запрета была установлена из первой папки, а виндиверт установлен из второй. По-хорошему нужно было юзануть service_remove.bat из обеих папок, удалить лишнюю папку, и установить службу по-новой.

**Comment by DeniZleet** [comment]
> Ну понятно. У вас есть папка Flawseal-zapret_1.5.1 и папка zapret-discord-youtube-1.5.1. Видимо служба запрета была установлена из первой папки, а виндиверт установлен из второй. По-хорошему нужно было юзануть service_remove.bat из обеих папок, удалить лишнюю папку, и установить службу по-новой.

А служба ставится сразу при первом запуске батника? Просто я кроме discord.bat ничего не запускал.

**Comment by sk8rthug** [comment]
> А служба ставится сразу при первом запуске батника? Просто я кроме discord.bat ничего не запускал.

Сейчас потестил - да, так и есть (речь не о службе запрета, а о службе именно виндиверта, если что). Если когда-то запрет запускался из другой директории, то после запуска или установки запрета в новой директории команда "sc qc windivert" всё равно выдаёт старый путь к виндиверту. Однако сам запрет в любом случае будет использовать тот виндиверт, который лежи в его папке - ему всё равно, какой путь помнит система. А почему у вас его заблочила система, я не знаю, лично я у себя его спокойно удаляю даже во время работы службы (разумеется, без него служба запрета уже не перезапустится, проработает до первого отключения, но это уже другой разговор), но у меня семёрка, наверное на 10-11 по-другому.
