### ISSUE TITLE
Ютуб  нормально не работает.

### ISSUE THREAD

**Issue by DeathPart404** [Flowseal/zapret-discord-youtube#873]
Приветствую!
   Столкнулся с проблемой. Ютуб временами не подгружает обложки, виде часто зависает на одном месте, решается это обновлением страницы, но через 10 секунд оно опять может повиснуть. Иногда бывает, что всё прекрасно, грузит абсолютно всё. Но очень часто начинаются провисания раз за разом, от чего начинает уже подгорать. 
  
  Использую "general (ALT3)", только он мне помогает, другие не грузят ничего вообще. Хотел поинтересоваться, в силу своего не знания. Может  ли быть такое из-за того что я использую "general" для разблокировки ютуба и дискорда, с учётом того, что дискорд у меня не заблокирован? То есть я могу его спокойно использовать ДС, но юзаю general файл только для ютуба.
  
   Может ли быть какой-то конфликт в этом, или может быть нужен какой-то файл влияющий только на работу ютуба, а не на всё целиком? Подскажите, пожалуйста. Буду очень и очень благодарен <3

**Comment by Flowseal** [comment]
> Может ли быть такое из-за того что я использую "general" для разблокировки ютуба и дискорда, с учётом того, что дискорд у меня не заблокирован

Нет

Пробуйте blockcheck. Инструкция есть в оригианльном репозитории.
