### ISSUE TITLE
cloudflare

### ISSUE THREAD

**Issue by Mitradis** [Flowseal/zapret-discord-youtube#874]
Добавление cloudflare-ech.com перестало работать для сайта rutracker.org и korrespondent.net
Причем позавчера работал и открывался. Если активировать плагин обхода в браузере то заходит на сайт. Но хотелось бы без плагинов, с ними другие проблемы возникают. Есть какие-то еще домены у cloudflare? Менял днс не помогает. Подозреваю тоже самое случится в скором времени с другими сайтами. Использую совмещенный файл russia-blacklist.txt от гудбай в list-general.txt.

![image](https://github.com/user-attachments/assets/a263e7d0-0937-4a6b-8612-5abcfff8cc7f)

**Comment by serpen7** [comment]
Оно не перестало работать, просто узел через который вы подрубаетесь по клаудфлерю к рутреккеру на конечном сервере рутреккера выдает ошибку. У вас же явно видно что вас подрубает к сети клаудфларя, так что все работает, но не подрубает к серверу рутрекера. 
The 504 (Gateway Timeout)
Серверная ошибка, видимо работает ддос защита.

**Comment by Flowseal** [comment]
FastProxy - обход блокировки сайтов
FastProxy 
Proxy
https://en.wikipedia.org/wiki/Proxy_server
