### ISSUE TITLE
хочу зайти в звонок, а пишет подключение и всё

### ISSUE THREAD

**Issue by WERERICH** [Flowseal/zapret-discord-youtube#875]
![19CD1673-85A1-4C3D-BD74-BBDF465E1D97](https://github.com/user-attachments/assets/1743df7e-57ef-4ca5-ac27-ee6742b50a3e)

**Comment by Flowseal** [comment]
Пробуйте другие батники, https://github.com/Flowseal/zapret-discord-youtube/discussions/252
