### ISSUE TITLE
discord doesn't work

### ISSUE THREAD

**Issue by Mam1241** [Flowseal/zapret-discord-youtube#876]
![Screenshot_55](https://github.com/user-attachments/assets/20ca46cf-e41d-4d2a-b15b-ebf51ec54d36)

**Comment by Mam1241** [comment]
что делать 
в этом случии

**Comment by electrifying** [comment]
> что делать в этом случии

windivert не работает с win 7

**Comment by serpen7** [comment]
Виндайверт не работает с виндой7. Есть вариант попробовать заменить файлы виндайверта из гудбайдпи в запретовские, может заработает. [goodbyedpi-0.2.3rc3-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc3/goodbyedpi-0.2.3rc3-2.zip) 
![image](https://github.com/user-attachments/assets/aba26b84-a89c-498a-b83d-f6749fa4eb75)

**Comment by Flowseal** [comment]
На Win7 работа не гарантирована
