### ISSUE TITLE
Не хотите расширить обход ограничений и добавить в zapret сайты с аниме которые заблокировали?

### ISSUE THREAD

**Issue by LowPingH** [Flowseal/zapret-discord-youtube#879]

**Comment by joerV2** [comment]
Открываешь list-general.txt, переходишь на новую строку и вставляешь домен нужного сайта. Сохраняешь и после перезапуска всё заработает.
А вообще, советую скопировать список из гудбая и в конец просто вставить всё из файла запрета

**Comment by GorigoLewis** [comment]
Сам можешь все сделать тупо впиши в general Jut.su и другие домены сайтов (ток тот кто читает обновитесь до последней версии, иначе ужасно работать будет)
Если тупой и не знаешь что такое домен (это домик для сайта, если домик блокируют то сайт не работае)
Чтобы узнать что за домен можешь воспользоватся этим https://www.reg.ru/whois/jut.su
Вписывай ссылку и тебе покажет домен, его то и впишешь

**Comment by Flowseal** [comment]
Добавьте сами
