### ISSUE TITLE
Как удалить?

### ISSUE THREAD

**Issue by Glebushkafff** [Flowseal/zapret-discord-youtube#88]
Всё работает очень криво с GDPI. Снёс службу через remove. Вот только она не сносится, и папку нет возможности удалить, даже после перезагрузки пк.

**Comment by Glebushkafff** [comment]
Пытался удалить через sc stop windivert, ошибка 5

**Comment by Glebushkafff** [comment]
А, всё, просто не от админа запустил терминал) всё гуд, удалил

**Comment by WeskersTentacles** [comment]
Не могу удалить даже через админа...
