### ISSUE TITLE
-аниме сайты РКН спасибо

### ISSUE THREAD

**Issue by FlipperKastDev** [Flowseal/zapret-discord-youtube#883]
Могли бы вы обновить версию чтоб заработали они?

**Comment by p1xeless** [comment]
А зачем обновлять, ты в list-general.txt добавь ссылки и будет тебе счастье, на будущее.
[list-general.txt](https://github.com/user-attachments/files/18021486/list-general.txt)
Вот тебе мой лист, который у меня стоит

**Comment by unisns** [comment]
> А зачем обновлять, ты в list-general.txt добавь ссылки и будет тебе счастье, на будущее. [list-general.txt](https://github.com/user-attachments/files/18021486/list-general.txt) Вот тебе мой лист, который у меня стоит

Даже с добавлением в list-general не заходит =/

**Comment by kotisoff** [comment]
попробуй сервис переустановить или перезапустить пк

**Comment by danilaavdonin** [comment]
почему то только с yummyani.meme помогло
комп ребутал, сервис переустанавливал 

> А зачем обновлять, ты в list-general.txt добавь ссылки и будет тебе счастье, на будущее. [list-general.txt](https://github.com/user-attachments/files/18021486/list-general.txt) Вот тебе мой лист, который у меня стоит
