### ISSUE TITLE
Вирусы

### ISSUE THREAD

**Issue by The-Verdi** [Flowseal/zapret-discord-youtube#884]
Я нашел как минимум 2 трояна и еще пару других вирусов в весии 1.6.1, последняя версия без вирусов была 1.5.1 но она уже еле работает

**Comment by Darknesxaker** [comment]
где ты их там нашел, я малварём все проверил нет там ничего, меньше с торрентов непонятных качай олух

**Comment by The-Verdi** [comment]
Единственный олух тут ты, я через как ты выразился непонятные торенты ничего не качал гений

**Comment by exzolink** [comment]
В лупу что ли заметил? Или как ты их там нашел в скомпилированном билде. Все, что тебе пишет вирустотал или антивирус - полная чушь
