### ISSUE TITLE
Не могу понять

### ISSUE THREAD

**Issue by Gxtod** [Flowseal/zapret-discord-youtube#885]
В очередной раз обновилась сборка - **Zapret WinBundle 03.12.2024** https://github.com/bol-van/zapret-win-bundle/

Почему у вас нет обновлений сборки? Чё они там правят то всё время? 

@Flowseal прошу дайте ответ, у вас последняя сборка от [v1.6.1](https://github.com/Flowseal/zapret-discord-youtube/releases/tag/1.6.1) уже прошло 3 недели.

Ну неужели нельзя учесть все эти обращения, вот эти https://github.com/Flowseal/zapret-discord-youtube/issues

И уже наконец-то или в конце-то концов обновить сборку, алгоритмы там новые добавить, батники, бантики, фигантики и тд.?

Или проще ничего не обновлять, ну типо - сами криворукие е*****ь как хотите?

**Comment by electrifying** [comment]
> Или проще ничего не обновлять

Ну а что автор сделать должен тут вся сборка строится на том что запусти 1 батник,2,3,10 не сработало? Ну значит не повезло

**Comment by TheSolenOne** [comment]
Зачем ты вообще что-то пишешь, если даже не понимаешь о чем говоришь? Кринж
Как там говорилось? Милая, тебе никто ничего не должен

**Comment by Flowseal** [comment]
ну лично Вам могу сказать
> сами криворукие е*****ь как хотите

Вам никто ничего не должен. Если у кого-то есть свободное время - милости прошу в PR. У меня сейчас свободного врмени нет.
