### ISSUE TITLE
Активность Discord

### ISSUE THREAD

**Issue by IvanDruzya** [Flowseal/zapret-discord-youtube#886]
Когда я запускаю активность Discord. Там просто белый экран и ничего не работает. Сможете решить эту проблему? Это работает на всех активностях!

**Comment by Flowseal** [comment]
Не сталкивался. Используйте последнюю версию / другие батники. Смотрите по траффику, куда стучится активность, и, добавляйте хосты сами, в случае чего.

**Comment by IvanDruzya** [comment]
> Не сталкивался. Используйте последнюю версию / другие батники. Смотрите по траффику, куда стучится активность, и, добавляйте хосты сами, в случае чего.

Все равно белое вне зависимости от версии приложения, поэтому это не закрыто.

**Comment by K1beM** [comment]
Я столкнулся с такой же проблемой

> Не сталкивался. Используйте последнюю версию / другие батники. Смотрите по трафику, куда стучится активность, и добавляйте хосты самостоятельно, в случае чего.

**Comment by K1beM** [comment]
Даже дискорд переустанавливал
