### ISSUE TITLE
Не работают обновления Дискорд

### ISSUE THREAD

**Issue by salat3112** [Flowseal/zapret-discord-youtube#887]
Захожу с запретом в дискорд, у меня на пол экрана вылезает Downloading update 1/15 и так бесконечно, с впном все работает @Flowseal почини пожалуйста

**Comment by Flowseal** [comment]
Пробуйте другие батники, смотрите откуда идёт обновление по траффику. Самый лёгкий способ - на время обновления использовать специальные сервисы
