### ISSUE TITLE
youtube робит но не голосовой чат в дискорде.

### ISSUE THREAD

**Issue by kanjiden** [Flowseal/zapret-discord-youtube#89]
провайдер МГТС (хз важно это или нет)
в обоих вариантах работает youtube, но не discord. бесконечное подключение к голосовому чату идет.

**Comment by kanjiden** [comment]
нюанс, дискорд работает кроме ГЧ

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92

**Comment by prostovan** [comment]
Тоже самое, дискорд польностью работает,но не в голосовом чате, провайдер МГТС,

**Comment by Lemonch1kOsu** [comment]
@prostovan Тоже
