### ISSUE TITLE
не работает дискорд и ютуб

### ISSUE THREAD

**Issue by venyyyt** [Flowseal/zapret-discord-youtube#891]
пишет при ремуве ошибку 1060 всё началось после того как я скачал впн для игры потом увидел что с ним не работает запрет и я его удалил полностью потом перезагружаю пк тоже не работает потом перескачиваю запрет серовно ничего не работает что делать?

**Comment by Flowseal** [comment]
1060 - не ошибка
https://github.com/Flowseal/zapret-discord-youtube/discussions/251
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
