### ISSUE TITLE
Не работает войс в Дискорде. Провайдер Ростелеком

### ISSUE THREAD

**Issue by loisakilla** [Flowseal/zapret-discord-youtube#894]
Пишет "Подключение к RTC" и бесконечные попытки переподключиться. Использовал general.bat. Что имеет смысл поменять в батнике, чтобы подключиться к войсу?

**Comment by Kitsunmer** [comment]
Тоже самое, последняя версия, пробовал разные батники, зависает на Подключение к RTC

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
