### ISSUE TITLE
Не запускается zapret после перезапукска пк

### ISSUE THREAD

**Issue by DeadM1nd3** [Flowseal/zapret-discord-youtube#895]
Добрый день. Столкнулся с проблемой что сервис не запускается автоматически после перезапуска винды и его приходится удалять и ставить заново чтобы он заработал. Можно ли это как то исправить?

**Comment by serpen7** [comment]
а что в службах services.msc показывает на сервисе zapret после перезагрузки?

**Comment by serpen7** [comment]
так же не мешало бы посмотреть журнал системы после перезагрузки ПК на предмет того почему служба не загружается, если она действительно не загружается. На наличие событий ближайших связанных с службами и запретом.
![image](https://github.com/user-attachments/assets/fa0aef11-2bfe-4d5a-9b16-a0f4fbaa4213)

**Comment by Flowseal** [comment]
service_install используете?

**Comment by DeadM1nd3** [comment]
> а что в службах services.msc показывает на сервисе zapret после перезагрузки?
в службах после перезапуска она отключена,а при попытке ее включить выдает ошибку 2, не обнаружен файл

**Comment by DeadM1nd3** [comment]
service_install использую. только через него ее запускаю

**Comment by DeadM1nd3** [comment]
![изображение_2024-12-07_154910640](https://github.com/user-attachments/assets/179ec1a7-ca62-4f42-a214-ab687ec36109)
![image](https://github.com/user-attachments/assets/944ddc10-7fb2-4a38-ab55-7ad8b3cc6c1e)
такая ошибка

**Comment by DeadM1nd3** [comment]
в журнале кроме таких ошибок с windivert и zapret "не удается найти указанный файл" ничего нет

**Comment by serpen7** [comment]
> в журнале кроме таких ошибок с windivert и zapret "не удается найти указанный файл" ничего нет

а ну так либо вы перенесли папочку запрета, либо антивирь снес файл какой то с программы.
Удаляйте службу с сервис ремув батника от имени администратора, устанавливайте её заново от имени администратора с сервис инсталл батником. И проверьте чтобы все файлы были в папке бин. Если чего то нет, то придется перекачивать запрет и восстанавливать файлы. Либо же смотреть антивирь, если он не удалил и просто поместил в карантин то восстанавливать оттуда занося файл в исключения попутно.
![image](https://github.com/user-attachments/assets/b3ad1804-cb3e-4c77-af73-cb24792117cb)

**Comment by DeadM1nd3** [comment]
Дело в том что антивирусом не пользуюсь,а системный отключен и в каратине ничего нет, а файлы запрета все на месте, я переустанавливал новый апдейт и ничего оттуда не вытаксивал

**Comment by serpen7** [comment]
> Дело в том что антивирусом не пользуюсь,а системный отключен и в каратине ничего нет, а файлы запрета все на месте, я переустанавливал новый апдейт и ничего оттуда не вытаксивал

а путь какой к файлу winws? Вы его в службах можете увидеть 
![image](https://github.com/user-attachments/assets/c28a7084-d6f8-4ba2-bcdb-6a392124e265)

**Comment by DeadM1nd3** [comment]
![image](https://github.com/user-attachments/assets/7944564d-9861-49ed-afb2-91520a5f7cea)
вот путь, это после переустановки службы он работает. если сейчас перезагружу комп - служба отключится

**Comment by DeadM1nd3** [comment]
![image](https://github.com/user-attachments/assets/c9888628-da51-4644-bdc3-f06fe51f76e3)
![image](https://github.com/user-attachments/assets/b52c999f-02e8-4d21-9d36-34517574601e)
![image](https://github.com/user-attachments/assets/9c5b32cb-ced5-49b6-8c0b-8174ee9efe71)
вроде все на месте

**Comment by serpen7** [comment]
> ![image](https://private-user-images.githubusercontent.com/190744248/393762129-7944564d-9861-49ed-afb2-91520a5f7cea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzYxMTAsIm5iZiI6MTczMzczNTgxMCwicGF0aCI6Ii8xOTA3NDQyNDgvMzkzNzYyMTI5LTc5NDQ1NjRkLTk4NjEtNDllZC1hZmIyLTkxNTIwYTVmN2NlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQwOTE2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTAxZTAxOTMxODVjYzMzM2NiYzg0Njk2MDg4ZjI2NmM4YzRlNGZhMDA5MGNiMTUwZjg4NDA3ODY2OGM1OTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8NsyPtdlKQUhrQiz54xmuwTtbeSXxJB_2nLUjz99wmA) вот путь, это после переустановки службы он работает. если сейчас перезагружу комп - служба отключится

Вы не тот запрет скачали, он не для винды, там батники в юниксе LF, вам нужен RAR архив из релизов, который в CR LF кодировке батников для винды. Не соурс код, не сорс код с мейн репозитория на главной странице, а RAR архив из релизов.
![image](https://github.com/user-attachments/assets/07df42fd-0cbf-464e-ba57-9b3bf8c3780d)

**Comment by DeadM1nd3** [comment]
сейчас проверю

**Comment by DeadM1nd3** [comment]
переустановил то что вы сказали, результата нет, не запускается с такой же ошибкой
![image](https://github.com/user-attachments/assets/f37ad352-146d-491d-83a2-382d41b015b9)

**Comment by serpen7** [comment]
> переустановил то что вы сказали, результата нет, не запускается с такой же ошибкой ![image](https://private-user-images.githubusercontent.com/190744248/393858358-f37ad352-146d-491d-83a2-382d41b015b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjQwMDksIm5iZiI6MTczMzc2MzcwOSwicGF0aCI6Ii8xOTA3NDQyNDgvMzkzODU4MzU4LWYzN2FkMzUyLTE0NmQtNDkxZC04M2EyLTM4MmQ0MWIwMTViOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNzAxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODE4ZWQ4ODJiYTdjYTJjMTU3YTYyNGZlZjM0YzI0NDE0YmE3ZTRhN2QyMTg2YWJmZGI1OTg0NGIyYmE2Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sn6n_kTGtXhDDd8NjgnExCnEC30AG_phK6IGmhep1hQ)

а где ошибка?

**Comment by DeadM1nd3** [comment]
та же ошибка "не удается найти указанный файл"

**Comment by serpen7** [comment]
> та же ошибка "не удается найти указанный файл"

странно, такое чувство что файл блокируется по какому то доступу, он есть по пути но система его почему то не видит.

**Comment by DeadM1nd3** [comment]
печально. спасибо за попытку помочь
