### ISSUE TITLE
Нет доступа к сайтам с аниме при добавлении их в список list-general.txt

### ISSUE THREAD

**Issue by unisns** [Flowseal/zapret-discord-youtube#899]
Привет! Добавил в list-general.txt следующие сайты:

```
jut.su
yummyani.me
yummyani.meme
animego.org
```

Заработал только [yummyani.me](https://yummyani.me/). Перезагружал ПК и переустанавливал сервис. Через ВПН есть подключение. Провайдер - Телеком Центр.

**Comment by Verity-Freedom** [comment]
Тут надо обновлять ядро оно устарело на месяц. Тут надо пробовать разные параметры для персонально ваших сайтов.

**Comment by Flowseal** [comment]
У меня работает с ALT4 - пробуйте другие батники
