### ISSUE TITLE
zapret отвалился

### ISSUE THREAD

**Issue by ZhylevarYTRUS** [Flowseal/zapret-discord-youtube#901]
смотрел видео и просто отвалился.

**Comment by dartse9** [comment]
сегодня с zapret на ютуб загружается примерно одна минута видео и зависает, при перемотке видео не грузит вообще.

**Comment by ImperatorOfIntellectualism** [comment]
Могу подтвердить, что сегодня программа перестала работать. Ждем когда разрабы починят

**Comment by Flowseal** [comment]
Пробуйте другие стратегии. Проблема носит локальный характер
