### ISSUE TITLE
Опечатка в check updates

### ISSUE THREAD

**Issue by Verity-Freedom** [Flowseal/zapret-discord-youtube#905]
if not defined NEW_VERSION (
    echo Erorr reading new version
    goto :EOF
)

**Comment by pokoizi** [comment]
что это??

**Comment by serpen7** [comment]
вы бы хоть написали в чем ошибка

А все понял в слове "Erorr" вместо "Error", строка 54. Но благо она ни на что не влияет, это просто выводимый текст. Внесут на исправление думаю.

**Comment by Gojikovi** [comment]
Откройте Pull request.

**Comment by Flowseal** [comment]
Такое надо в PR, а не в Issue.
