### ISSUE TITLE
bat запускается, но сразу закрывается

### ISSUE THREAD

**Issue by KoshkaMoroshka** [Flowseal/zapret-discord-youtube#91]
Продебажил через @echo путь до файла правильный

Как будто команда start игнорируется и не понятно, в чём может быть проблема. set bin работает верно.

Но start вообще не отзывается и приложение просто закрывается

**Comment by Flowseal** [comment]
Попробуйте перезагрузить устройство

**Comment by KoshkaMoroshka** [comment]
Перезагружал, не помогло.

**Comment by Doraaaaa1** [comment]
у меня аналогичная проблема, перезагрузка не исправила ситуацию.

**Comment by KoshkaMoroshka** [comment]
@Doraaaaa1 а попробуй продебажить путь
После set BIN=%~dp0bin\ напиши
@echo %BIN% и напиши, что у тебя выдаёт

**Comment by Flowseal** [comment]
> Но start вообще не отзывается и приложение просто закрывается

Если приложение открывается, то значит start работает
Выведите логи работы приложения в файл через аргумент.

Выдержка из оригинального репозитория:
> --debug позволяет выводить подробный лог действий на консоль, в syslog или в файл.
Может быть важен порядок следования опций. --debug лучше всего указывать в самом начале.
Опции анализируются последовательно. Если ошибка будет при проверке опции, а до анализа --debug еще дело не дошло,
то сообщения не будут выведены в файл или syslog.
При логировании в файл процесс не держит файл открытым. Ради каждой записи файл открывается и потом закрывается.
Так что файл можно удалить в любой момент, и он будет создан заново при первом же сообщении в лог.
Но имейте в виду, что если вы запускаете процесс под root, то будет сменен UID на не-root.
В начале на лог файл меняется owner, иначе запись будет невозможна. Если вы потом удалите файл,
и у процесса не будет прав на создание файла в его директории, лог больше не будет вестись.
Вместо удаления лучше использовать truncate.
В шелле это можно сделать через команду ": >filename"

**Comment by Doraaaaa1** [comment]
> @Doraaaaa1 а попробуй продебажить путь После set BIN=%~dp0bin\ напиши @echo %BIN% и напиши, что у тебя выдаёт

бесполезно там что-то чинить, я снесла, буду завтра трясти парня, чтобы починил. Если найду решение, напишу тут.

**Comment by KoshkaMoroshka** [comment]
Попробовали, но не понимаем, как с Shell работать, так как при изменении файла и запуском с рутами приложения просто открывается и закрывается без логов

**Comment by xunlu-t** [comment]
точно в пути до файла нет пробелов и русских символов?

**Comment by KoshkaMoroshka** [comment]
точно

**Comment by Flowseal** [comment]
Выполните эти инструкции:
### Остановка и удаление обхода
Для удаления оставшегося драйвера WinDivert, откройте cmd от имени администратора и пропишите следующее:
```
sc stop WinDivert
sc delete WinDivert
```
> [!NOTE]  
> Возможно, драйвер у вас будет записан по-другому. Для уточнения названия пропишите `driverquery | find "Divert"` в cmd.

**Comment by AlexGolder** [comment]
> Выполните эти инструкции:
> ### Остановка и удаление обхода
> 
> Для удаления оставшегося драйвера WinDivert, откройте cmd от имени администратора и пропишите следующее:
> 
> ```
> sc stop WinDivert
> sc delete WinDivert
> ```
> 
> Note
> 
> Возможно, драйвер у вас будет записан по-другому. Для уточнения названия пропишите `driverquery | find "Divert"` в cmd.

Увы не помогло. Я не раз перепроверял путь, пробовал в корневую диска ставить. И не раз сносил Диверт. У меня почему-то их было 2 разных. Сам .bat файл у меня сработал при первом скачивании, на следующий день перестал запускаться. И да, от лица администратора запускаю.

**Comment by Afrogaus** [comment]
@Flowseal Лучший <3

**Comment by Sailenso** [comment]
> Возможно, драйвер у вас будет записан по-другому. Для уточнения названия пропишите `driverquery | find "Divert"` в cmd.

А что делать если в списке после этой комнды нет драйвера?

**Comment by gv1nPin** [comment]
> > Возможно, драйвер у вас будет записан по-другому. Для уточнения названия пропишите `driverquery | find "Divert"` в cmd.
> 
> А что делать если в списке после этой комнды нет драйвера?

в любом случае должен быть драйвер, иначе не работает это все, который прописан в папке bin

**Comment by Demafaet** [comment]
Я знаю как пофиксить я использовал прогу для обхода ютуба и дискорда. Потом при запуске закрывалось резко и ничего не работало. Чтобы пофиксеть я ввел в cmd от имени администратора 2 команды
sc stop WinDivert
sc delete WinDivert
после этого все должно работать

**Comment by pampersok0385** [comment]
Не помогло, вписываю данные команды не помагает пишет "Служба не запущена." и "Указанная служба была отмечена для удаления.". Даже не знаю что можно сделать с этим(

**Comment by DamirYFY** [comment]
я когда открываю что то у меня командная строка стразу закрывается и дискорд не начинает работать

**Comment by Casual322** [comment]
> Я знаю как пофиксить я использовал прогу для обхода ютуба и дискорда. Потом при запуске закрывалось резко и ничего не работало. Чтобы пофиксеть я ввел в cmd от имени администратора 2 команды sc stop WinDivert sc delete WinDivert после этого все должно работать

Пользуюсь обходом ютуба и дискорда и выходит вот эта ошибка при запуске bat. Уже пробовал вписать команды в cmd, не помогло.

<img width="1468" height="194" alt="Image" src="https://github.com/user-attachments/assets/b8887e4d-303b-4eff-ad96-7edd114c5c31" />
