### ISSUE TITLE
Перестал работать обход

### ISSUE THREAD

**Issue by legenda116** [Flowseal/zapret-discord-youtube#915]
Всё до этого работало нормально, стояла версия 1.2.0 вроде как, но чёт теперь батник любой запускается и через секунду закрывается :( ставил последнюю версию, ничего не изменилось

**Comment by MacsGeran** [comment]
может антивирус блочит?

**Comment by legenda116** [comment]
> может антивирус блочит?

ну до этого не блочил, да и не ругался, а тут внезапно перестал, но это наверное я что-то сломалa, потому что точка восстановления недельной дальности всё пофиксила
