### ISSUE TITLE
Zapret-discord мешает запустить приложение Call of Duty

### ISSUE THREAD

**Issue by a-aganesov** [Flowseal/zapret-discord-youtube#917]
При включенном скрипте, вне зависимости от того включен general или discord, невозможно запустить "Call of Duty" в Steam. Игра буквально на секунду открывается после чего сразу же закрывается. После выключения скрипта игра запускается штатно. Также пробовал сначала запустить игру и после чего уже скрипт, но результат тот же.

**Comment by dezgasting** [comment]
У GDPI та же проблема. Современная колда тупо не работает с запретом/гдпи.
