### ISSUE TITLE
Обход блокировки аниме сайтов

### ISSUE THREAD

**Issue by PandaYaY** [Flowseal/zapret-discord-youtube#918]
Недавно на просторах интернета забанили ряд сайтов с аниме(animego.org, jut.su, yamianime, и пр. ...).
Есть возможность добавлять свои домены или в будущих версиях добавить сайты связанные с аниме тематикой?

**Comment by PandaYaY** [comment]
Хотя вроде решил с помощью добавления сайтов в файл `list-general.txt`
`animego.org - сам сайт
aniboom.one - плеер по идее`
для решения проблемы с сайтом animego.org

Встает вопрос другой. Есть ли поддержка комментариев при парсинге этого файла, чтобы было проще понимать и подписывать добавленные сайты)

**Comment by Flowseal** [comment]
можно использовать # в начале для комментирования отдельных доменов.

**Comment by eco8011** [comment]
![image](https://github.com/user-attachments/assets/7343eda0-d999-4afe-80bf-1b5d215311d3)
у меня в это теперь вылезает. Прокси помогает, но появляются проблемы на других сайтах
