### ISSUE TITLE
Troyan.Wacatac

### ISSUE THREAD

**Issue by printRush** [Flowseal/zapret-discord-youtube#922]
При запуске батника в первый раз, виндовс дефендер поймал и удалил 2 трояна

**Comment by serpen7** [comment]
все норм, это эвристика сработала потому что у фильтра действительно поведение "трояна" чтобы перехватывать трафик в соответствии с конфигом и модифицировать его, чтобы обходить оборудование но при этом не давать модифицированным пакетам доходить до сервера в таком виде. Вакатак это эвристика общая по сигнатуре виндефендера что означает, что поведение похоже на троянца, но распознать его не может и сигнатуру троянца не приписывает конкретную, а лишь общую по поведению. Главное чтобы вы скачивали запрет из проверенных репозиториев. То же относится и к гудбайдпи. Потому что сейчас очень много фейковых версий, которые действительно напичканы вирусами. Незнамо от кого и откуда, особенно с ютуба его скачивать не надо.

**Comment by serpen7** [comment]
Занесите просто файлы в исключение и восстановите их из скачанного архива в последнем релизе данного репозитория. Всю папку вносить в исключения не надо, это не совсем хорошо для безопасности. Просто потому что если вы вдруг скачаете не дай бог вирусную сборку какую, то вся папка в исключениях даст вирусам зеленый свет. Занесите только файлы конкретные на которые вин дефендер триггерится. Как вы говорите у вас их 2 и это скорее всего винвс и сигвин1 или виндайверт.

**Comment by printRush** [comment]
Я не силен в безопасности, но правильно ли я понял что из за поведения как у трояна виндовс их решил утилизировать, и как тогда без этих файлов работал discord.bat?
К сожалению поздно что либо вносить, в процессе распределения места на новой винде xd

**Comment by serpen7** [comment]
> Я не силен в безопасности, но правильно ли я понял что из за поведения как у трояна виндовс их решил утилизировать, и как тогда без этих файлов работал discord.bat?

 работало не от проги запрета явно если винда снесла даже тот же исполняющий файл запрета или виндайверт драйвер фильтр.
