### ISSUE TITLE
Конфликт с новостными статьями на Mail.ru

### ISSUE THREAD

**Issue by NilFable** [Flowseal/zapret-discord-youtube#924]
Добрый день!
Обратил внимание, что при запуске  general (ALT5).bat происходит конфликт с прогрузкой содержимого сайта mail.ru в части перехода по статьям/новостям. Не грузит. Кто-то сталкивался с такой проблемой?
![Скрин](https://github.com/user-attachments/assets/f0262443-5025-4407-b5cb-d91d2ddc424d)

**Comment by StatusQQ** [comment]
Такая же проблема

**Comment by Flowseal** [comment]
ALT5 использует syndata, который работает до SNI - дурение всего 443 TCP. Пробуйте другие батники.

**Comment by NilFable** [comment]
К сожалению другие батники мне не помогли. Возможно связано с тем ,ч то я использую обход находясь в Турции. Посоветуйте иные решения.
