### ISSUE TITLE
Сайт Jut.su больше не работает через Zapret discord

### ISSUE THREAD

**Issue by GorigoLewis** [Flowseal/zapret-discord-youtube#925]

**Comment by serpen7** [comment]
да вроде работает 
![image](https://github.com/user-attachments/assets/04070a9c-934b-4c61-b80e-7ab0437d96e6)

**Comment by amogus8** [comment]
не работает
и аниме го не работает у меня тоже!!!

**Comment by serpen7** [comment]
> не работает и аниме го не работает у меня тоже!!!

анимего закрылся от РФ полностью, там без впна теперь не посмотришь будет выдавать ошибку 504. Закошмарили его РКН. И это уже не блокировка РКНа, это чисто с серверной стороны самого ресурса. 
![image](https://github.com/user-attachments/assets/f22ff0c5-ed37-437b-8e4c-a05854c54fab)

**Comment by GorigoLewis** [comment]
> > не работает и аниме го не работает у меня тоже!!!
> 
> анимего закрылся от РФ полностью, там без впна теперь не посмотришь будет выдавать ошибку 504. Закошмарили его РКН. И это уже не блокировка РКНа, это чисто с серверной стороны самого ресурса. ![image](https://private-user-images.githubusercontent.com/134365619/394711675-f22ff0c5-ed37-437b-8e4c-a05854c54fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODA0NzcsIm5iZiI6MTczMzk4MDE3NywicGF0aCI6Ii8xMzQzNjU2MTkvMzk0NzExNjc1LWYyMmZmMGM1LWVkMzctNDM3Yi04ZTRjLWEwNTg1NGM1NGZhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwNTA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2E4Y2Q0MDI2ZTMzMTY4YTY2MjNkNGY3ZjZiNTk3OWMwMzA2ZjM0YzZjZjU5NjAxZGI4Y2NkZmI3ZWY5OTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._Vb5PHl6WFnUE6wDxfEZfQVQWAC-KMK4lITbePPE-xE)

это еще тот идиотизм кнш

**Comment by GorigoLewis** [comment]
видимо jutsu закрылся тоже от РФ, вот честно не понимаю почему они так делаю, я до этого обсуждал что блокировку РКН обойти легко а блокировку сервера нет, пришли соевые и начали говорит какой РКН плохой (не бы обойти блокировку и забить тк РКН просто для показухи все делает) но нет давайте им насирать под дверь и тд, причем jutsu тоже после блокировки РКН начал со стороны сервера банить абсолютно любые видео (не смотря на содержание) что тоже бред

**Comment by serpen7** [comment]
> видимо jutsu закрылся тоже от РФ, вот честно не понимаю почему они так делаю, я до этого обсуждал что блокировку РКН обойти легко а блокировку сервера нет, пришли соевые и начали говорит какой РКН плохой (не бы обойти блокировку и забить тк РКН просто для показухи все делает) но нет давайте им насирать под дверь и тд, причем jutsu тоже после блокировки РКН начал со стороны сервера банить абсолютно любые видео (не смотря на содержание) что тоже бред

нет если бы джутсу закрылся от рф, я бы на него не смог зайти и смотреть видео, так что тут промах.

**Comment by Flowseal** [comment]
Пробуйте другие батники
