### ISSUE TITLE
Не открывается сайт animego.org

### ISSUE THREAD

**Issue by MikShale** [Flowseal/zapret-discord-youtube#927]
Сайт внесен в list-general.txt 

10.12.2024 работало. 

Попробовал по очереди запускать каждый из general с перезапуском страницы без кэша (ctrl+f5).

**Comment by spyderomega** [comment]
Их заблокировал РКН и они решили полностью ограничить работу для РФ. Используйте vpn

**Comment by Eptiy** [comment]
Чтобы было понятнее, перефразирую. Сначала их заблокировали в РКН, такую блокировку можно обойти запретом. Потом они сами заблокировали доступ из РФ, такую блокировку можно обойти только сменой местоположения, например - впн. Та же ситуация, например, с ChatGPT.

**Comment by ghost** [comment]
Странно, страны СНГ тоже под раздачу попали? Я из Армении но доступа к сайту нет

**Comment by MMLYSHEV** [comment]
> Странно, страны СНГ тоже под раздачу попали? Я из Армении но доступа к сайту нет
 в Эстонии тоже не работает

**Comment by Eptiy** [comment]
Мб это проблема интернета в целом? С тем же ютубом проблемы сейчас из многих регионов, даже за пределами постсоветского пространства. Мб связано с перерезанным в балтике кабелем?

**Comment by MikShale** [comment]
not a defect

**Comment by MikShale** [comment]
not a defect

**Comment by MikShale** [comment]
not a defect

**Comment by sic20101** [comment]
Не грузит не через ригу, ни через германию. VPN собственные сервера, так что проблем точно не в них. У кого нибудь есть какая-то информация?

**Comment by Kaybe1** [comment]
Два домена надо добавить в прокси, тогда будет работать
```
animego.me
animego.org
```
