### ISSUE TITLE
как запустить general в service.instal

### ISSUE THREAD

**Issue by KuralezBarmaleev** [Flowseal/zapret-discord-youtube#929]

**Comment by EgorWeders** [comment]
У вас при запуске service.install не спрашивает какой файл выбрать? Или вам просто general.bat нужен?

**Comment by KuralezBarmaleev** [comment]
спрашивает, мне нужно вписать general.bat

**Comment by EgorWeders** [comment]
Тогда впишите его номер в списке , если не понятно, что делать, скиньте скрин с выбором файла

**Comment by Flowseal** [comment]
Нужно вписать его порядковый номер и нажать Enter
