### ISSUE TITLE
Игра вылает после запуска дискорд бат РЕШЕНИЕ

### ISSUE THREAD

**Issue by Fanvarli** [Flowseal/zapret-discord-youtube#93]
Запускайте дискорд бат, запустите дискорд и зайдите в голос канал, потом закройте дисокрд бат и запустите игру

**Comment by Flowseal** [comment]
Напиши об этом сюда https://github.com/Flowseal/zapret-discord-youtube/issues/92
Напиши конкретно, что за игра.
