### ISSUE TITLE
не до конца запускается запрет

### ISSUE THREAD

**Issue by kirillinf1** [Flowseal/zapret-discord-youtube#935]
с сегодняшнего дня не работал дискорд я скачал последнюю версию запрета но там файлы что так что от имени администратора запускаются не до конца(на панели задач вместо значка документ) и логично дискорд не открывается пишет ищет обновления вечно но без ошиьки когда файлом remove закрываю файл zapret пишет в cmd ошибка 1060 кто знает как исправить помогите пожалуйста

**Comment by kirillinf1** [comment]
все еще нужна помощь

**Comment by Flowseal** [comment]
Пробуйте другие батники. 
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
