### ISSUE TITLE
Builds with debugging symbols? / Сборки с отладочными символами?

### ISSUE THREAD

**Issue by MichaelAgarkov** [Flowseal/zapret-discord-youtube#939]
It would be nice if builds with debugging symbols would be provided so you could use GDB to see why something may not be working. Thanks in advance.
/
Было бы неплохо если были бы сборки с отладочными символами чтобы можно было в GDB посмотреть почему что-то может не работать. Заранее спасибо.

**Comment by Flowseal** [comment]
I bet if you know what it is, you can build the source code yourself
