### ISSUE TITLE
не получается открыть

### ISSUE THREAD

**Issue by Fronzay** [Flowseal/zapret-discord-youtube#940]
что с этим делать?
![8f0db39e-7a30-494c-8397-b5a46cdc4bbc](https://github.com/user-attachments/assets/f3665478-abdd-4faf-aa56-e08f7a026da6)

**Comment by serpen7** [comment]
ты из архива целую программу пытаешься запустить одним файлом? Может все таки переместишь все файлы из архива в папочку нормальную и уже тогда будешь пытаться запускать программу? Не я понимаю прога работала бы от одного файла тогда бы такое открытие из архива прокатило бы. Но надо все.

**Comment by Fronzay** [comment]
человек разархивировал давно еще, и все равно не получалось.

**Comment by serpen7** [comment]
> человек разархивировал давно еще, и все равно не получалось.

человек разархивировал давно еще именно поэтому у него путь к запуску файла временный темповский, использующийся архивами из которых запускают файлы или разархивируют их? Вы вообще понимаете о чем говорите?
![image](https://github.com/user-attachments/assets/695fec39-7a33-478f-82cf-aab6b4a6515b)

Вас палит строчка темпа, временной папки ОС. 
![image](https://github.com/user-attachments/assets/2ecade29-f8cf-42f9-9456-b7890ca804bd)
Вы не разархивировали архив и не запускаете его как положенно всеми файлами из папки. Вы запускаете его напрямую из архива.
Разархивированный батник ничего не сделает без исполняемых файлов т.к. он при открытии через архив разархивируется только один. Вы вообще с архивами встречались когда либо?

**Comment by Fronzay** [comment]
а кто вам говорил, что на скрине разорхивированный архив?

**Comment by Fronzay** [comment]
я сказал что человек давно разорхивировал, скриншот старый просто. Но разорхивация не помогала. Сейчас все норм

**Comment by serpen7** [comment]
> я сказал что человек давно разорхивировал, скриншот старый просто. Но разорхивация не помогала. Сейчас все норм

Это хорошо что все нормализовалось. Доброго вам вечера.
