### ISSUE TITLE
Windows антивирус ругается на скрипт "запрета"

### ISSUE THREAD

**Issue by SUPERpuperGH** [Flowseal/zapret-discord-youtube#946]
антивирус винды ругается на скрипт и указывает на папку "запрета"
![Снимок экрана (74)](https://github.com/user-attachments/assets/7311b4f2-c72b-46fb-ac95-e6eea1e5bae5)
есть ли основания беспокоиться? или антивирус просто агрится на неизвестный ему скрипт?

**Comment by Flowseal** [comment]
Читайте README.

**Comment by SUPERpuperGH** [comment]
> Читайте README.

второй раз перечитал, ответа на вопрос не нашел
