### ISSUE TITLE
Не работают некоторые сайты и программы.

### ISSUE THREAD

**Issue by TON618OFF** [Flowseal/zapret-discord-youtube#95]
## Пояснение:
Выполнил все рекомендации. С момента установки я запускал от имени администратора батник только для и дискорда и сразу для дискорда + ютуба. Если запускаю бат дискорд + ютуб, то в терминале пишет, мол хосты принимаются из файла `list-general.txt`, однако все необходимые хосты, используемые сайтом `steam` я указал в этом файле, но ничего не работает. 
Хосты, которые я нашёл, вставил в файл и сохранил:
- store.akamai.steamstatic.com
- store.steampowered.com
- shared.akamai.steamstatic.com

## Дополнение:
Также перезапускал батник, перезагружал автоматическую службу, + перезагружал устройство

**Comment by TON618OFF** [comment]
## Проблема с программами:
Не получилось обновить `steam` с запущенным батником, так как steam'у кажется, что нету доступа к интернету.

**Comment by Flowseal** [comment]
Последнюю версию 1.1.1 используете?

**Comment by TON618OFF** [comment]
> Последнюю версию 1.1.1 используете?

Только сегодня вечером ставил софт, мб не ласт, сейчас переустановлю и проверю

**Comment by TON618OFF** [comment]
> > Последнюю версию 1.1.1 используете?
> 
> Только сегодня вечером ставил софт, мб не ласт, сейчас переустановлю и проверю

Установил 1.1.1, но и с ней стим ломанный. 
Всё равно огромное спасибо за такую возможность в дискорде посидеть, так что все вопросы к вам лишь для того, чтобы разобраться в проблеме - вдруг реально получится доработать батники до идеала

**Comment by Flowseal** [comment]
Попробуйте начисто удалить старую версию, и с нуля установить последнюю (1.1.1), не изменя списки.

**Comment by TON618OFF** [comment]
> Попробуйте начисто удалить старую версию, и с нуля установить последнюю (1.1.1), не изменя списки.

Не знаю в чём прикол заключался, но заработало... Почему-то в списке всего 31 хост, но теперь стим исправно отображается, плюс monkeytype тоже грузить начал (сайт для скоропечатания).
