### ISSUE TITLE
Ютуб не работает

### ISSUE THREAD

**Issue by screwsen** [Flowseal/zapret-discord-youtube#951]
Со второй половины дня перестал работать обход блокировки ютуба. Иконки видео загружаются, а само видео уходит в бесконечную загрузку. Обход дискорда работает, скачан последний релиз, в файлах ничего не менял, так как итак все работало. Помогите пж, что делать?

**Comment by Eptiy** [comment]
Пробуй другие батники. Попробуй билд от Censorliber (https://github.com/censorliber/zapret), у него куча своих конфигов. На крайняк - подбирай конфиги блокчеком.

Если проблема с прогрузкой дальше 0.59, иди в обсуждение обхода ютуба, мб, там найдётся решение.

**Comment by screwsen** [comment]
> Пробуй другие батники. Попробуй билд от Censorliber (https://github.com/censorliber/zapret), у него куча своих конфигов. На крайняк - подбирай конфиги блокчеком.
> 
> Если проблема с прогрузкой дальше 0.59, иди в обсуждение обхода ютуба, мб, там найдётся решение.

Нет проблема не с прогрузкой дальше 0.59, сделал все из этого и не сработало, иконки видео загружаются а само видео нет. Блокчек не пробовал, тк не знаю что это

**Comment by Eptiy** [comment]
Ты уже перепробовал все конфиги Censorliber? Blockcheck - штука, которая проверяет, какие методы обхода работают. Гайд на неё можно почитать тут https://github.com/bol-van/zapret?tab=readme-ov-file#проверка-провайдера.

**Comment by screwsen** [comment]
> Ты уже перепробовал все конфиги Censorliber? Blockcheck — штука, которая, наконец, какие методы обхода работают. Гайд на ней можно почитать тут [https://github.com/bol-van/zapret?tab=readme-ov-file#проверка-провайдера](https://github.com/bol-van/zapret?tab=readme-ov-file#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%BF%D1%80%D0%BE%D0%B2%D0%B0%D0%B9%D0%B4%D0%B5%D1%80%D0%B0) .

ну конфиги это ведь всё те файлы которые у него представлены, по типу start1 start2 и тд? Елси это оно то да всё перепробовал, hosts не прописывал тк как там он инста и фейсбук(файлы hosts тоже у него прописаны). Щас блокчек попробуб

**Comment by screwsen** [comment]
Чет не разобрался в блокчеке, вроде запустил проверочку, а что дальше?

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/251

Попробуйте полностью удалить обход:
- Запустите service_remove.bat
- Удалите папку с обходом

Если использовали другие обходы, то удалите отключите их тоже

Затем скачайте последнюю версию из релизов и распакуйте в другую папку.

**Comment by screwsen** [comment]
не помогло

**Comment by screwsen** [comment]
> #251
> 
> постарайтесь удалить полностью в обход:
> 
> * Запустите service_remove.bat
> * Удалите переключатель обходным путем.
> 
> Если использовались другие обходы, отключите и отключите их тоже.
> 
> Затем скачайте последнюю версию из релизов и распакуйте по второму адресу.

не помогло

**Comment by ASyomkin** [comment]
Тоже посреди дня перестал работать ютуб, перепробовал все альт-конфиги, сейчас пробую конфиги из блокчека, пока безрезультатно. Дискорд работает, на ютубе всё грузит(сайт, аватарки, комменты), кроме видео🤷‍♂️

**Comment by screwsen** [comment]
> Аналогичный вопрос, день перестал работать на ютубе, перепробовал все альт-конфиги, сейчас пробую конфиги из блокчека, пока безрезультатно. Дискорд работает, на ютубе всё грузит(сайт, аватарки, комменты), кроме видео🤷‍♂️

вот один в один как у тебя, тоже перепробовал разные запреты конфиги и тд и тп, и ничего, иконки аватарки грузит, видео нет. Если найдешь решение скинь пожалуйста

**Comment by Eptiy** [comment]
> Чет не разобрался в блокчеке, вроде запустил проверочку, а что дальше?

Читай внимательно гайд, можешь поискать более подробные гайды в обсуждениях оригинального репозитория, или в целом в интернете. После проверки тебе выдаст варианты конфигов, их пробуешь уже вживую, заменяя конфиги в батниках.

**Comment by ASyomkin** [comment]
> > Чет не разобрался в блокчеке, вроде запустил проверочку, а что дальше?
> 
> Читай внимательно гайд, можешь поискать более подробные гайды в обсуждениях оригинального репозитория, или в целом в интернете. После проверки тебе выдаст варианты конфигов, их пробуешь уже вживую, заменяя конфиги в батниках.

Пробую брать конфиги из блокчека, но после того как вношу изменения в батник, он перестаёт запускаться.

**Comment by Eptiy** [comment]
Возможно, ты что-то неправильно изменяешь. Скинь конфиги, я попробую у себя их.

**Comment by gamakpok** [comment]
> Со второй половины дня перестал работать обход блокировки ютуба. Иконки видео загружаются, а само видео уходит в бесконечную загрузку. Обход дискорда работает, скачан последний релиз, в файлах ничего не менял, так как итак все работало. Помогите пж, что делать?

Попробуй скачать оригинал запрет https://github.com/bol-van/zapret/tree/master там скачиваешь и распаковываешь zapret-win-bundle-master и запускаешь preset-russia.cmd мне помогло

**Comment by screwsen** [comment]
> > Со второй половины дня перестал работать обход блокировки ютуба. Иконки видео загружаются, а само видео уходит в бесконечную загрузку. Обход дискорда работает, скачан последний релиз, в файлах ничего не менял, так как итак все работало. Помогите пж, что делать?
> 
> Попробуй скачать оригинал запрет https://github.com/bol-van/zapret/tree/master там скачиваешь и распаковываешь zapret-win-bundle-master и запускаешь preset-russia.cmd мне помогло

Попробовал, не помогло

**Comment by Eptiy** [comment]
> Попробовал, не помогло

С блокчеком разобрался?

**Comment by screwsen** [comment]
> > Попробовал, не помогло
> 
> С блокчеком разобрался?

Чет вообще нет, полазил по форумам, по выопросам в гитхабе, и у всех по разному

**Comment by Eptiy** [comment]
Когда запускаешь блокчек, просто на все вопросы отвечай так, как указано в самом вопросе по умолчанию. Степень проверки указывай standart. Когда спросит домены, пиши все, связанные с ютубом, которые есть в списке list-general, домены пишутся в одну строчку через пробел. Потом остаётся только ждать. Скорее всего - несколько часов. Если хочешь быстрее - сократи список доменов, можно для начала только youtube.com протестировать.

Важно, чтобы в это время ни на пк, ни на роутере не было запущено никаких модификаторов трафика, впн и т.д. и т.п. Также желательно выставить на пк днс гугла (8.8.8.8 и 8.8.4.4) или клаудфлэйр (1.1.1.1 и 1.0.0.1), по возможности включить doh (на 11 винде это "DNS по протоколу HTTPS - автоматический шаблон").

**Comment by screwsen** [comment]
> Когда запускаешь блокчек, просто на все вопросы отвечай так, как указано в самом вопросе по умолчанию. Степень проверки указывай standart. Когда спросит домены, пиши все, связанные с ютубом, которые есть в списке list-general, домены пишутся в одну строчку через пробел. Потом остаётся только ждать. Скорее всего - очень долго. Если хочешь быстрее - сократи список доменов, можно для начала только youtube.com протестировать.
> 
> Важно, чтобы в это время ни на пк, ни на роутере не было запущено никаких модификаторов трафика, впн и т.д. и т.п. Также желательно выставить на пк днс гугла (8.8.8.8 и 8.8.4.4) или клаудфлэйр (1.1.1.1 и 1.0.0.1), по возможности включить doh (на 11 винде это "DNS по протоколу HTTPS - автоматический шаблон").

Как sh файл запустить, я прочитал что нужен cygwin, но его там нет

**Comment by Eptiy** [comment]
Ты скачал с основного репозитория, там файлы для линукса. Вот отсюда качай для винды https://github.com/bol-van/zapret-win-bundle

**Comment by Eptiy** [comment]
Там нет релизов, если что, просто код зипом скачивай.

**Comment by screwsen** [comment]
> youtube.com

выдал кучу строк в summary, дальше нужно по примеру конфигов сделать свой, ну а там как свой сделать, что именно в конфиге заменять нужно?

**Comment by screwsen** [comment]
> Ты скачал с основного репозитория, там файлы для линукса. Вот отсюда качай для винды https://github.com/bol-van/zapret-win-bundle

выдал кучу строк в summary, дальше нужно по примеру конфигов сделать свой, ну а там как свой сделать, что именно в конфиге заменять нужно?

**Comment by Eptiy** [comment]
Тебя интересуют конфиги nfqws. В них http - 80 порт. tls1.2/https - 443 порт. Копируешь строку и заменяешь ей всё после аргумента --hostlist и до --new в соответствующей строке (filter-tcp, порты 80 и 443). В последней по счёту строке --new не должно быть.

**Comment by screwsen** [comment]
Немного не понял, мне блокчек очень много строк выдал, мне их всех копировать, или только одну рандомную в фильтр 80 и 443 запихать?

**Comment by Eptiy** [comment]
Там есть строки под http и под tls1.2. Для обоих выбираешь по строке, лучше всего по порядку сверху вниз, и заменяешь строки в конфиге. Строки http идут в 80, строки tls1.2 идут в 443.

**Comment by screwsen** [comment]
http3 к 80 или 443?

**Comment by screwsen** [comment]
> Там есть строки под http и под tls1.2. Для обоих выбираешь по строке, лучше всего по порядку сверху вниз, и заменяешь строки в конфиге. Строки http идут в 80, строки tls1.2 идут в 443.

http3 к 80 или 443?

**Comment by Eptiy** [comment]
ни туда, ни туда, игнорируй пока. Если там строки под http, http2, http3, то http2 - 443

**Comment by screwsen** [comment]
> ни туда, ни туда, игнорируй пока. Если там строки под http, http2, http3, то http2 - 443

Запускаю, он открывается и сразу закрывается

**Comment by Eptiy** [comment]
скинь, что выдал блокчек

**Comment by screwsen** [comment]
> скинь, что выдал блокчек

ipv4 youtube.com curl_test_http : working without bypass
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=multisplit --dpi-desync-split-pos=2
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-fake-tls=0x00000000
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-fooling=badsum
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-fooling=badseq
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-fooling=datanoack
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-fooling=md5sig
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=1
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=2
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=3
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=4
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-fake-tls=0x00000000
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata --dpi-desync-fake-syndata=/cygdrive/h/zapret-win-bundle-master/zapret-win-bundle-master/blockcheck/zapret/files/fake/tls_clienthello_iana_org.bin
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata,multidisorder --dpi-desync-fake-syndata=/cygdrive/h/zapret-win-bundle-master/zapret-win-bundle-master/blockcheck/zapret/files/fake/tls_clienthello_iana_org.bin --dpi-desync-split-pos=1
ipv4 youtube.com curl_test_https_tls13 : working without bypass
ipv4 youtube.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=fake --dpi-desync-repeats=2
ipv4 youtube.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=ipfrag2 --dpi-desync-ipfrag-pos-udp=8
ipv4 youtube.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=ipfrag2 --dpi-desync-ipfrag-pos-udp=16
ipv4 youtube.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=ipfrag2 --dpi-desync-ipfrag-pos-udp=24
ipv4 youtube.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=ipfrag2 --dpi-desync-ipfrag-pos-udp=32

**Comment by Eptiy** [comment]
У тебя в твоём конфиге должна получиться строка:
--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=multisplit --dpi-desync-split-pos=2

т.к. выдало
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=multisplit --dpi-desync-split-pos=2

В строке блокчека игнорируешь
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443

дальше начинается уже конфиг, т.е. только
--dpi-desync=multisplit --dpi-desync-split-pos=2

**Comment by Eptiy** [comment]
Следом за http3 идёт udp=443, значит можно применить конфиг к filter-udp=443. Такая должна быть строка:

--filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-repeats=2  --new ^

http выдал "working without bypass", значит строчку filter-tcp=80 оставляешь без изменений.

**Comment by Eptiy** [comment]
Кстати, проверил, с --dpi-desync=multisplit действительно вылетает батник. Значит, конфиг с ним пропускай всегда.

А ещё убери из конфига строчки
call check_updates.bat soft
echo:

**Comment by screwsen** [comment]
все равно срразу вылетает, мне нужно вот это удалить?: --dpi-desync=multisplit( в строке --filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=multisplit --dpi-desync-split-pos=2), или удалить всю эту строку и взять следующую из blockcheck?

**Comment by Eptiy** [comment]
Удали всё из строки, начиная с -dpi-desync=multisplit, замени другой строкой из блокчека

Должно получиться
--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-fake-tls=0x00000000

**Comment by screwsen** [comment]
> Удали всё из строки, начиная с -dpi-desync=multisplit, замени другой строкой из блокчека
> 
> Должно получиться --filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-fake-tls=0x00000000

так и начал делать, перепробовал все эти  строчки и результата 0, сам ютуб загружается быстро, нажимаю на видео и оно уходит в бесконечную загрузку, вобщем проблема не ушла

**Comment by Eptiy** [comment]
Я же объяснял уже, что одного youtube.com может не хватить. Проверяй все домены ютуба из списка list-general.

**Comment by screwsen** [comment]
> > > Чет не разобрался в блокчеке, вроде запустил проверочку, а что дальше?
> > 
> > 
> > Читай внимательно гайд, можешь поискать более подробные гайды в обсуждениях оригинального репозитория, или в целом в интернете. После проверки тебе выдаст варианты конфигов, их пробуешь уже вживую, заменяя конфиги в батниках.
> 
> Пробую брать конфиги из блокчека, но после того как вношу изменения в батник, он перестаёт запускаться.

Ты решил как-то проблему?

**Comment by ASyomkin** [comment]
> > > > Чет не разобрался в блокчеке, вроде запустил проверочку, а что дальше?
> > > 
> > > 
> > > Читай внимательно гайд, можешь поискать более подробные гайды в обсуждениях оригинального репозитория, или в целом в интернете. После проверки тебе выдаст варианты конфигов, их пробуешь уже вживую, заменяя конфиги в батниках.
> > 
> > 
> > Пробую брать конфиги из блокчека, но после того как вношу изменения в батник, он перестаёт запускаться.
> 
> Ты решил как-то проблему?

Сегодня не до этого было, запущу блокчек заново, но со всеми доменами, а то я только с одним делал.

**Comment by Eptiy** [comment]
если какие-то конфиги вызывают вылет, просто пропускайте, проверяйте другие.

**Comment by screwsen** [comment]
> если какие-то конфиги вызывают вылет, просто пропускайте, проверяйте другие.

так и делал, все конфиги попробовал которые блокчек выдал, результата 0, на некоторые домены не выдал ничего для фильтр 443, сейчас чисто их в блок чеке проверяю

**Comment by Hoioblao** [comment]
Маленький вопрос который возможно не относится к главному делу: какой у вас провайдер и отключали ли вам свет в момент того как zapret перестал работать?

**Comment by screwsen** [comment]
> Маленький вопрос который возможно не относится к главному делу: какой у вас провайдер и отключали ли вам свет в момент того как zapret перестал работать?

провайдер Sampo.ru и свет не выключали

**Comment by screwsen** [comment]
кстати заработал запрет, которые самый обычный, где оригинальный конфиг

**Comment by ASyomkin** [comment]
> провайдер Sampo.ru и свет не выключали

А, так я тоже с птз=)

**Comment by screwsen** [comment]
> > провайдер Sampo.ru и свет не выключали
> 
> А, так я тоже с птз=)

Оо, кайф. видимо какой-то рофлянчик в ПТЗ был

**Comment by ASyomkin** [comment]
> Оо, кайф. видимо какой-то рофлянчик в ПТЗ был

Подумываю сейчас на ситилинк перейти, 5к на счёт дают, если до НГ подключить.

**Comment by Hoioblao** [comment]
> > Маленький вопрос который возможно не относится к главному делу: какой у вас провайдер и отключали ли вам свет в момент того как zapret перестал работать?
> 
> провайдер Sampo.ru и свет не выключали

А ну да у меня тоже сампо был но уже всё починился
