### ISSUE TITLE
discord перестал работать

### ISSUE THREAD

**Issue by adrenvchrome** [Flowseal/zapret-discord-youtube#954]
дискорд просто перестал запускаться сегодня, провайдер билайн, хз может они чет натворили, что можно сделать?

**Comment by Toctep21** [comment]
То же самое, провайдер билайн и дискорд больше не работает

**Comment by Flowseal** [comment]
> что можно сделать?

Пробовать другие батники.
Затем советы отсюда (читайте моё первое сообщение особенно в этом топике) - https://github.com/Flowseal/zapret-discord-youtube/discussions/252
