### ISSUE TITLE
батник не запускается

### ISSUE THREAD

**Issue by T1ska-siska** [Flowseal/zapret-discord-youtube#955]
скачал запрет должно было все быть норм запускаю дс ошибка, генерал тоде ошибка. Что делать?
![Screenshot_2](https://github.com/user-attachments/assets/60abd12c-5cab-457a-93cf-b8049a5358d3)

**Comment by Eptiy** [comment]
Ты не распаковал архив и запускаешь прямо из архива. Сначала распакуй, потом запускай.
