### ISSUE TITLE
биткоин бесплатно

### ISSUE THREAD

**Issue by enficus** [Flowseal/zapret-discord-youtube#956]
чуваки в папке bin в описании файла .sys написано :"BITKOIN^_^" я няшка всем поки!!

**Comment by serpen7** [comment]
ну да, у драйвера виндайверта в описании есть сайт его создателя и криптокошелек для поддержки его создателя, тем кто пожелает его поддержать. То же самое и на сайте его создателя https://reqrypt.org/windivert.html. Сам создатель там же написан там Basil. И у него есть свой гит тоже https://github.com/basil00/WinDivert
![image](https://github.com/user-attachments/assets/f1d17f96-f964-4a18-a3f0-05d6d235dd07)
Если ты так пытался потроллить людей о якобы майнере - то это было очень глупо с твоей стороны)
Майнеры-вирусы в описании файла такого писать не будут и указывать что либо на своего создателя тоже. Их цель как можно быстрее заразить машину без следов и отсылок.  Вирусы майнеры по описанию в теле файла метаданных о файле вычислять и опознавать как то глупо.

**Comment by Eptiy** [comment]
> чуваки в папке bin в описании файла .sys написано :"BITKOIN^_^" я няшка всем поки!!

чел ты кринж

**Comment by Ruslan152rus** [comment]
> чуваки в папке bin в описании файла .sys написано :"BITKOIN^_^" я няшка всем поки!!

боже...удали программу тупень

**Comment by Flowseal** [comment]
а где биткоин то забрать бесплатно?
