### ISSUE TITLE
Дискорд работает, но не загружаются прикрепленные файлы

### ISSUE THREAD

**Issue by darsig** [Flowseal/zapret-discord-youtube#957]
Дискорд работает чат голос, но не загружаются прикрепленные файлы. Прикрепляешь любой файл и полоса загрузка висит на 0% С включенным впн загрузка файлов работает.
Может нужно дописать какую строку хост в list-discord.txt?

**Comment by Flowseal** [comment]
Аттачменты прикрепляются через discord-attachments-uploads-prd.storage.googleapis.com
Этот домен уже есть в списке.
Проверьте, что используется последняя версия.
Если всё равно не работает - пробуйте другие батники.
