### ISSUE TITLE
Не запускается сервис

### ISSUE THREAD

**Issue by kupettt** [Flowseal/zapret-discord-youtube#96]
Привет! Не понимаю что не так, пробелов нет и русских символов тоже, да и как я понял там бы ошибку такую и выдало бы. Пробовал запускать и просто discord, и youtube_discord, попробовал и goodbyedpi. Скриншот от попытки с goodbyedpi, перед запуском service_goodbye_discord я делал remove_service.
![изображение_2024-10-09_225449843](https://github.com/user-attachments/assets/74670549-7dd7-4459-b13c-c92873835742)

**Comment by Flowseal** [comment]
Прочитайте в README про `service_goodbye_discord`. Пришлите скриншот с другим сервисом

**Comment by kupettt** [comment]
Вот скрин от discord_youtube
![image](https://github.com/user-attachments/assets/2a57ee24-0fe2-48b6-ac49-306994bdb666)

**Comment by kupettt** [comment]
С ним запускается дс, но идет бесконечное "Подключение" к голосовому каналу

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/92

**Comment by Fanvarli** [comment]
У меня так же было, я перекачал файл и сохранил на раб стол, проблема исчезла.
