### ISSUE TITLE
При запуске любого батника закрывается консоль

### ISSUE THREAD

**Issue by dreamerenigma** [Flowseal/zapret-discord-youtube#960]
Добрый день, не пойму в чем проблема, вчера работал запуск батника, сегодня перестал. Брандмауэр был включен, проблем не возникало, сегодня при запуске батника отображается на несколько секунд и закрывается, в чем проблема?

**Comment by serpen7** [comment]
У вас работает служба, она не дает запустить батники т.к. какой то уже работает из них на системном уровне. Используйте сервис ремув от администратора.

**Comment by dreamerenigma** [comment]
Помогло удаление служб и при запуске батника service_remove.bat и после этого запустил general.bat, все отлично, но если подобная проблема ещё появится, может есть другие пути чем просто удаление сервисов?

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/522

**Comment by kysatel** [comment]
Помогите, пожалуйста, я в IT полный чайник и ничего толком не понимаю. У меня в последнее время перестал работать запрет. Я открываю батник от имени администратора, а он открывается на считанные секунды и тут же закрывается. Пока что ничего не помогало, никакие советы.
