### ISSUE TITLE
люди звучат как роботыы

### ISSUE THREAD

**Issue by llizixs** [Flowseal/zapret-discord-youtube#962]
иногда норм иногда как роботы как фиксануть

**Comment by Eptiy** [comment]
Сервер поменяй у голосового канала, например, на автоматический выбор, обычно помогает. Нормально работает только на рф и финляндии. В остальных регионах пинг высокий+нестабильный.

**Comment by TenshiHeisei** [comment]
Поменяли регион с России на English, и мс стал адекватным
