### ISSUE TITLE
Здравствуйте не работает обход 1.6.1

### ISSUE THREAD

**Issue by hio546** [Flowseal/zapret-discord-youtube#963]
перестал работать

**Comment by linuxdc** [comment]
+++ МГТС

**Comment by Flowseal** [comment]
Пробуйте другие батники

https://github.com/Flowseal/zapret-discord-youtube/discussions/252

https://github.com/Flowseal/zapret-discord-youtube/discussions/251

**Comment by Kijiraven** [comment]
Перестал запускаться, на всех батниках пишет:
Skipping the update check because it hasnt been 6 hours

Access is denied.

**Comment by zaraza00** [comment]
Перестал запускаться, на всех батниках пишет:
Пропуск проверки обновлений, так как не прошло 6 часов
