### ISSUE TITLE
Обход ютуба перестал работать

### ISSUE THREAD

**Issue by Hoioblao** [Flowseal/zapret-discord-youtube#964]
День назад обход просто перестал работать и начал бесконечную загрузку видео. сам сайт работает и грузит всё но видео не грузятся. И обход дискорда всё ещё работает

**Comment by screwsen** [comment]
Такая же проблема

**Comment by ScarRus** [comment]
Проблема схожая, но у меня грузится видео ровно на одну минуту и больше не может дальше. Пробовал все доступные стратегии (кроме с МГТС), никак не грузил только на АLT и ALT5.

**Comment by Hoioblao** [comment]
обход только что сам починился и я без понятия как
