### ISSUE TITLE
Не работает OpenService 

### ISSUE THREAD

**Issue by Karlionow** [Flowseal/zapret-discord-youtube#965]
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

Все запускаю нормально, не не запускается в норме. Первый раз скачал такой батник, и не качал ДПИ.
![image](https://github.com/user-attachments/assets/a92e8112-a896-4b6c-b92d-89b723238a07)

**Comment by serpen7** [comment]
по вашему тексту ничего не понятно, если честно. Что? Как? И о чем вы говорите, о какой проблеме?

**Comment by Karlionow** [comment]
выдает ошибку [SC] OpenService FAILED 1060 , и сайты в которые я заходил выдавали ошибку. Как это исправить?

**Comment by Eptiy** [comment]
[SC] OpenService FAILED 1060 - не ошибка. Это нормальная работа установочника сервиса.

С сайтами что не так, можно поподробнее?

**Comment by Karlionow** [comment]
![image](https://github.com/user-attachments/assets/1afe258e-8e37-4a11-bd16-c6e49d9da229)
![image](https://github.com/user-attachments/assets/2e86cba2-f57b-4eb1-a4a2-71c01b6db230)

я для этого сайта скачивал

**Comment by serpen7** [comment]
Его нет в листах, в лист его нужно добавлять вручную и при этом удаляя сервис с помощью service remove от имени администратора, а потом ставить его заново если пожелаете не запускать батники, а сразу в сервис. Потому что иначе прога не обновит конфигу с захватываемым трафиком от конфига.

Запрет в этом репозитории не гудбайдпи, тут нет разблокировки множества ресурсов с обновлением листов блокированных ресурсов. Изначально из коробки запрет работает стратегиями только с прописанными хостами и ИП адресами дискорда и ютуба. 

Вы можете прикрутить тот же лист гудбайдпи, но однако это нужно будет немного переделать конфиг, либо скопировать его и модифицировать от батника который работает, чтобы этот лист учитывался.

**Comment by Karlionow** [comment]
Хорошо, спасибо
