### ISSUE TITLE
не могу сделать ремув

### ISSUE THREAD

**Issue by blox-blop** [Flowseal/zapret-discord-youtube#966]
![Desktop Screenshot 2024 12 15 - 10 49 45 98](https://github.com/user-attachments/assets/ae07e8cd-3ccc-4b84-8831-6af9d104ca56)

**Comment by serpen7** [comment]
эм а что не так? Все вроде нормально и пишет прямо что ремувать нечего, нет сервиса или запущенных виндайвертов.
