### ISSUE TITLE
запускаю general а он мне про какие то 6 часов

### ISSUE THREAD

**Issue by blox-blop** [Flowseal/zapret-discord-youtube#967]
![Desktop Screenshot 2024 12 15 - 10 55 20 68](https://github.com/user-attachments/assets/2c288ece-5a30-47d3-a04d-8cfbe49bc9e3)

**Comment by serpen7** [comment]
вам антивирь снес винвс скорее всего от этого и висит окно т.к. винвс невозможно запустить с параметрами т.к. его нет.
