### ISSUE TITLE
Дискорд перестал работать

### ISSUE THREAD

**Issue by Slaboym** [Flowseal/zapret-discord-youtube#975]
Пользовался обходом с момента появление , но пришлось полную очистку делать , теперь не работает не старая версия ни новая.

Батник discord ,сразу закрывается при открытие с остальными все в порядке, но все равно не работает

В дискорд даже не заходит 
![image](https://github.com/user-attachments/assets/6645598c-ac4b-40a9-a8b6-6fc82555fc1e)

Помогите пожалуйста.

(обновление) А нет заходит, только спустя огромное количество времени, я заметил что второй день подряд бесконечная загрузка иногда отступает и все таки дает мне зайти, но со случайным временем ожидания

**Comment by Fotorob0t** [comment]
Тоже самое началось, даже не знаю что делать(

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
