### ISSUE TITLE
Идея

### ISSUE THREAD

**Issue by VaskaGROM** [Flowseal/zapret-discord-youtube#977]
Я бы мог создать сайт для скачивания zapret, с подробной инструкцией, из-за того что гит заблокирован.

**Comment by k1suzu** [comment]
гит заблокирован?

**Comment by EgorWeders** [comment]
Если гит заблокирован (нет), то ваш сайт намного легче будет заблокировать. Плюс к гиту есть чуток доверия по содержимому скачиваемых релизов. Много было проблем с зараженными сборками запрета и goodbyedpi.

**Comment by Flowseal** [comment]
нет
