### ISSUE TITLE
Сборки Zapret внесены в список Online Malicious URL Blocklist (AdGuard)

### ISSUE THREAD

**Issue by censorliber** [Flowseal/zapret-discord-youtube#979]
Причины до конца не ясны.

![image](https://github.com/user-attachments/assets/64b176a6-7354-4c06-bf56-7e4719c9938e)

https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-online.txt

**Comment by madsk1ils** [comment]
Для тупых, что это значит?

**Comment by PlasticShitlord** [comment]
> cock.exe

кек

**Comment by EgorWeders** [comment]
Это старая версия вроде, а так да, часто zapret (не путать с этим репозиторием) и goodbyedpi (а точнее windivert) расценивается как малварь.

**Comment by Flowseal** [comment]
ну, ладно?
