### ISSUE TITLE
Аниме-сайт (джутсу)

### ISSUE THREAD

**Issue by Debil387** [Flowseal/zapret-discord-youtube#982]
До этого пользовался jut.su, занеся его в list-general.txt, попользовался так около 2 недель. Сейчас же даже с запретом не грузится сайт, а остальные работают всё также вместе с ДС. Есть решение?

**Comment by SaD1sT1337** [comment]
Такая же история. На днях перестали грузиться рутрекер и сайты на клаудфлейр через запрет.
Работают только дискорд и ютуб(

**Comment by Eptiy** [comment]
Сайты на клаудфлэйр, возможно, требуют рабочий tls1.3, а то и esni. Рутрекер у меня грузится при рабочем tls1.3, возможности без него проверить нет. Jut.su не грузится, но у него полно зеркал, например jut-su.im.

**Comment by Debil387** [comment]
Ну походу да, клаудфейр и прочая херь. Рутрекер тоже самое с tls1.3, а зеркалка неудобна тем, что нельзя войти/зарегаться, добавлять тайтлы и продолжать просмотр с определённой серии и момента. А так благодарю

**Comment by Eptiy** [comment]
У меня стоит запрет на роутере с openwrt, добавил туда jut.su, заработало с таким конфигом:

`--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig <HOSTLIST> --new

--filter-tcp=443 --dpi-desync=fake,split --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="/opt/zapret/files/fake/tls_clienthello_www_google_com.bin" <HOSTLIST> --new

--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic="/opt/zapret/files/fake/quic_initial_www_google_com.bin" <HOSTLIST_NOAUTO> --new

--filter-udp=50000-50100 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --dpi-desync-fake-quic="/opt/zapret/files/fake/quic_initial_www_google_com.bin"`

Только тут хостлисты по-другому прописаны. "HOSTLIST" удаляете, ставите строчку с хостлистом из имеющихся конфигов.
Вообще, конфиг этот я делал не сам, просто как франкенштейна собрал из конфигов разных билдов. По сути, фильтры по udp вам вообще не нужны.

**Comment by Flowseal** [comment]
Пробуйте другие батники при добавленном домене в список
