### ISSUE TITLE
Не запускает дискорд с zapret-discord

### ISSUE THREAD

**Issue by maksimkirill** [Flowseal/zapret-discord-youtube#983]
Запускаю батник от имени админа, он запускается, а дискорд просто грузит плашку Starting и не заходит, антивирусов нету, дефендер отключен ,в чем может быть проблема?

**Comment by maksimkirill** [comment]
![Uploading photo_2024-12-18_19-51-57.jpg…]()

**Comment by maksimkirill** [comment]
![photo_2024-12-18_19-51-57](https://github.com/user-attachments/assets/08de4a04-e28f-4e74-af43-9b6e6f9f22d3)

**Comment by Flowseal** [comment]
Пробуйте другие батники
Дальше сюда
https://github.com/Flowseal/zapret-discord-youtube/discussions/252

**Comment by maksimkirill** [comment]
+
Отключение брэндмауэра помогло

**Comment by Nnneym** [comment]
> Отключение брэндмауэра помогло

не шарю, что это и как отключить?
