### ISSUE TITLE
дискорд работает через alt 2

### ISSUE THREAD

**Issue by Clevertopr** [Flowseal/zapret-discord-youtube#988]
дс запустился через генерал alt 2

**Comment by KARASIK123** [comment]
> дс запустился через генерал alt 2

Clevertopr, спасибо большое, мне помогло

**Comment by PsychoISDEL** [comment]
У меня через alt 3

**Comment by TEMPLE1231234124** [comment]
ПОМОГИТЕ ЕСЛИ НЕ ЧЕРЕЗ ЧТО НИ РАБОТАЕТ

**Comment by pikitich** [comment]
спасибо брат помогло
