### ISSUE TITLE
открываю файлы, а они сразу сворачиваются. Я скачивал разные версии всё одно и тоже, хз что делать, я не разбираюсь в этом помогите.

### ISSUE THREAD

**Issue by sneki24** [Flowseal/zapret-discord-youtube#991]

**Comment by BurizaDoKyanon** [comment]
Тоже самое, вдобавок ко всему перестал работать Дискорд. ALT2 не помогает, буду рад если решение проблемы будет в ближайшие время

**Comment by Flowseal** [comment]
Если cmd сворачивается (закрывается) и появляется в панели задач новая программа - это нормальная работа
Если вы хотите, чтобы он работал в фоне и сам запускался - используйте service_installer

Если нет, то https://github.com/Flowseal/zapret-discord-youtube/issues/522
