### ISSUE TITLE
Не работает Discord #2

### ISSUE THREAD

**Issue by BurizaDoKyanon** [Flowseal/zapret-discord-youtube#992]
не работает дискорд,все ALT не работают,GoodByeDpi не установлен,4 часа назад слетел дс и не открывается.

**Comment by Hinartxxx** [comment]
+

**Comment by Flowseal** [comment]
https://github.com/Flowseal/zapret-discord-youtube/issues/986
https://github.com/Flowseal/zapret-discord-youtube/discussions/252
