### ISSUE TITLE
Снова не работает "ДС"

### ISSUE THREAD

**Issue by Dreameradon** [Flowseal/zapret-discord-youtube#995]
Короче уже обращался с данной проблемой, но потом я на неё забил и со временем само как-то решилось, но в начале этой недели это проблема опять возникла, по пробывал фиксить, пробавал способ с preset_russia. Не помогло

**Comment by Flowseal** [comment]
Пробуйте другие батники

https://github.com/Flowseal/zapret-discord-youtube/discussions/252
