### ISSUE TITLE
Начал лагать войс чат в Valorant после установки сервисов

### ISSUE THREAD

**Issue by kashinbtw** [Flowseal/zapret-discord-youtube#996]
Начал лагать войс чат в Valorant после установки сервисов. Удаление сервисов не помогает.

**Comment by EgorWeders** [comment]
Проверьте что вы их удалили (осталась ли служба zapret)

**Comment by kashinbtw** [comment]
Проверял, удалились

**Comment by Flowseal** [comment]
Значит, проблема не в запрете
